### ISSUE TITLE
Integrating compression-webpack-plugin

### ISSUE THREAD

**Issue by jairusd** [jantimon/html-webpack-plugin#1000]
Hi, great work on this plugin guys, this isn't a bug report but a question. How do we use html webpack plugin with compression webpack plugin?

https://github.com/webpack-contrib/compression-webpack-plugin

Thanks for the response!

**Comment by jantimon** [comment]
Sorry I don't know if the compression-webpack-plugin supports the html-webpack-plugin - better create an issue on their issue tracker or on stackoverflow.

If you find a solution I would love to know :)

**Comment by jairusd** [comment]
Closing issue
