### ISSUE TITLE
How do I add certain script snippets inside <head> and <body> tags when using HtmlWebackPlugin

### ISSUE THREAD

**Issue by sujeetbuddiga** [jantimon/html-webpack-plugin#1001]
## Description

I would like to add custom script at different parts of `<head>` and `<body>` tags.

Use case: trying to add GTM tags to different pages.

Example:

How do I,

1. Add `<script> alert('in head tag') </script>` inside the `<head>` tag as the first child
2. Add `<script> alert('in body tag') </script>` inside the `<body>` tag as the first child

Here is the stackoverflow link: https://stackoverflow.com/questions/51285711/how-do-i-add-certain-script-tags-inside-head-and-body-tags-when-using-htmlwe

Here is the snippet in my Webpack config

### Config
```
      new HtmlWebpackPlugin({
        hash: true,
        chunks: ["app"],
        filename: path.resolve(__dirname, "./public/pages/app.html"),
        title: "Title of webpage",
        template: path.resolve(__dirname, "./src/pages/app.page.html"),
        minify: {
            collapseWhitespace: true
        }
    })
```

**Comment by jantimon** [comment]
The next major will provide an easier way to inject html tags to the head or body.  
For now you can already use the `htmlWebpackPluginAlterAssetTags` hook.

For now I wrote down a solution quickly without testing - so it might not work properly.  
But hopefully you still get the idea and will be able to finalize it:

This could look like the following (in a new file or in your webpack config)
```js
class GoogleTagManagerHtmlPlugin{
  apply(compiler) {
    // Hook into a webpack compilation
    compiler.hooks.compilation.tap('GoogleTagManagerHtmlPlugin', (compilation) => {
      // Hook into `htmlWebpackPluginAlterAssetTags`
      // !! Careful this will change in the upcoming html webpack plugin version !!
      compilation.hooks.htmlWebpackPluginAlterAssetTags.tapAsync('GoogleTagManagerHtmlPlugin',
        (pluginArgs, cb) => {
          // You can use either `head` or `body` and either `push` or `unshift`:
          pluginArgs.head.push({
            tagName: 'script',
            voidTag: false,
            attributes: {
            },
            innerHTML: 'alert("hello world")'
          });
          cb(null, pluginArgs)
      })
    })
  }
}
```

The plugin section of your config
```js
[
   new HtmlWebpackPlugin({ /* your config  */}),
   new GoogleTagManagerHtmlPlugin()
}
```
