### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded when i update html or style file

### ISSUE THREAD

**Issue by 2016caicai** [jantimon/html-webpack-plugin#1002]
## Current behaviour

![image](https://user-images.githubusercontent.com/17995300/42680991-1756c0ac-86b9-11e8-9fef-00017dfb678b.png)

## Environment

node: 8.9.0
webpack: ^4.16.0
webpack-cli: ^3.0.8
html-webpack-plugin: ^4.0.0-alpha

```
webpack-dev-server --mode development --hot --inline
```

### Config

my webpack.config

```js
module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'index.js'
  },
  module: {
    rules: [
      {
        test: /\.less$/,
        use: [
          {
            loader: miniCssExtractPlugin.loader,
            options: {
              publicPath: '../'
            }
          },
          "css-loader",
          "less-loader"
        ]
      },
      {
        test: /\.js$/,
        include:[
          path.resolve(__dirname, 'src')
        ],
        use: 'babel-loader'
      },
      {
        test:/\.css$/,
        use:['style-loader','css-loader']
      }
    ]
  },
  resolve: { 
    extensions: [".js", ".json", ".jsx",".less", ".css"], 
    alias: { 
        utils: path.resolve(__dirname,'src/utils')
    }
  },
  // devtool: "source-map",
  plugins: [  
    new webpack.HotModuleReplacementPlugin(),
    new htmlWebpackPlugin({ 
        file: 'index.html',
        template: './src/index.html'
    }),
    new miniCssExtractPlugin('style.css'),
    new webpack.ProvidePlugin({
      '_': 'lodash', 
      '$': 'jquery'
    })
  ],
  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    open: true,
    port: 9000
  }
}
```

**Comment by jantimon** [comment]
Hey thank you for submitting a bug report 👍

Could you please try to create a [minimal reproduction example](https://stackoverflow.com/help/mcve) (especially remove all dependencies, loaders and plugins which are not necessary for reproduction) and attach it (with out node_modules) as a zip to this issue?

**Comment by jantimon** [comment]
Maybe @ooflorent can help us to add a `test` to our spec files: https://github.com/jantimon/html-webpack-plugin/tree/webpack-4/spec

**Comment by 2016caicai** [comment]
[try-webpack.zip](https://github.com/jantimon/html-webpack-plugin/files/2191928/try-webpack.zip)

**Comment by jantimon** [comment]
@2016caicai can you please remove remove all dependencies, loaders and plugins which are not necessary for reproduction?

For example: less-loader, babel-loader and MiniCssExtractPlugin, and ProvidePlugin ... as well as the resolve settings - unless the bug would not occur without them?

**Comment by yuxuemei** [comment]
you can add code:--max-old-space-size=6000 in package.json file scripts object

"scripts": {
    "dev": "node --max-old-space-size=6000 ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --profile --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "lint": "eslint --ext .js,.vue src",
    "build": "node build/build.js"
  },

**Comment by jantimon** [comment]
@2016caicai any update here?
