### ISSUE TITLE
Error when I remove a PUG template on Webpack Dev Server

### ISSUE THREAD

**Issue by firestar300** [jantimon/html-webpack-plugin#1005]
Hello there,

## Expected behaviour

I use PUG templates to build my HTML views with Webpack and html-webpack-plugin thanks to my config :

```js
const htmlRender = require('./html-render.js')('./../src/templates/', ['pages', 'partials'])

rules: [
      {
        test: /\.pug$/,
        use: {
          loader: 'pug-loader',
          options: {
            pretty: true,
            self: true,
          },
        },
      },
      { ... }
],
plugins: [
    ...,
    new HtmlWebpackHarddiskPlugin(),
].concat(htmlRender),
```

And there is my html-render.js file to generate HTML files :

```js
const fs = require('fs')
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const imagesSizes = require('./image-sizes')
const flatten = array => [].concat(...array)

module.exports = function(templateDir, folders) {
  const imagesDatas = imagesSizes()
  let templateFiles = []

  folders.map(folder => {
    let files = fs.readdirSync(path.resolve(__dirname, templateDir + folder))

    files = files.map(file => folder + '/' + file)

    templateFiles.push(files)
  })

  return flatten(templateFiles)
    .filter(templateFile => templateFile.split('.')[1] === 'pug')
    .map(templateFile => {
      console.log('\x1b[32m', '🤘 Fetch ' + templateFile)
      const parts = templateFile.split('.')
      const name = parts[0]
      const extension = parts[1]
      const filename = name.includes('pages/') ? name.replace('pages/', '') : name

      return new HtmlWebpackPlugin({
        alwaysWriteToDisk: true,
        inject: false,
        filename: `../${filename}.html`,
        template: path.resolve(__dirname, `${templateDir}/${name}.${extension}`),
        imagesDatas,
      })
    })
}
```

It works as well, the HTML files are generated when I started my Webpack Dev Server, but during the local server is up, if I remove a PUG file, I get an error like this :

```
[failed] [1 error]

    ERROR in ./node_modules/html-webpack-plugin/lib/loader.js!./src/templates/pages/03-archive-default.pug
    Module build failed: Error: ENOENT: no such file or directory, open '/src/templates/pages/03-archive-default.pug'
```

There is a way to watch add or remove templates files to regenerate HTML views with html-webpack-plugin ?

Sorry for my bad English :zipper_mouth_face:

**Comment by mastilver** [comment]
Nothing to do with webpack-dev-server, your code is not working in watch mode

When you start webpack, your code instantiate one HtmlWebpackPlugin instance per template
Then when you remove that file, the HtmlWebpackPlugin instance is still there looking for that file

I guess removing a template is not something you do all the time, so I would just keep it that way and restart webpack when it happens
Otherwise you will need to create a webpack plugin that removes `HtmlWebpackPlugin` (I have no idea if it's doable tho :/)

**Comment by firestar300** [comment]
Thank you for your answer @mastilver 

> I guess removing a template is not something you do all the time, so I would just keep it that way and restart webpack when it happens

You're right but the problem is real when I add new templates. PUG  is useful for creating partials : https://pugjs.org/language/includes.html so I have to relaunch Webpack Dev Server every time I create new Pug partials or Pug templates.

**Comment by mastilver** [comment]
Try what I suggested, listen to start watch event and add / remove plugins
