### ISSUE TITLE
chunks path incorrect

### ISSUE THREAD

**Issue by mybigman** [jantimon/html-webpack-plugin#1009]
## Expected behaviour

The injected chunks path to point to the correct location.
```html
<script type="text/javascript" src="auth.9fbb17da.js"></script>
```

## Current behaviour

The injected chunks path is incorrect

```html
<script type="text/javascript" src="../../module/auth/auth.9fbb17da.js"></script>
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
Node.js v10.5.0
darwin 17.5.0
6.0.1
webpack@4.16.1
html-webpack-plugin@3.2.0
```

### Config
```js
module.exports = {
  entry: {
    app: './src/app.js',
    'module/auth/auth': './src/modules/auth/app.js',
  },

  output: {
    path: resolve('dist'),
    // publicPath: resolve('dist'),
    filename: '[name].[chunkhash:8].js',
  },
...
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'src/index.html',
      inject: true,
      chunks: ['vendor', 'app']
    }),

    new HtmlWebpackPlugin({
      filename: 'module/auth/index.html',
      template: 'src/index.html',
      inject: true,
      chunks: ['vendor', 'module/auth/auth']
    }),

    new VueLoaderPlugin(),
  ]
}
```
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <div id="app"></div>
<script type="text/javascript" src="../../vendor.7c5b44e9.js"></script>
<script type="text/javascript" src="../../module/auth/auth.9fbb17da.js"></script>
</body>
</html>
```
![image](https://user-images.githubusercontent.com/1289916/43205457-c3938d4e-9066-11e8-92b1-7dc339f1e4d8.png)

It puts everything in the right locations except for the path for the auth.js

Also, if there's a better way to handle this I am all ears or is it eyes :)

Thanks

**Comment by mastilver** [comment]
try to set publicPath to `/`
Also replace `entry['module/auth/auth']` by `entry['auth']` (or keep it like that, but the path will have `module/auth`)

**Comment by mybigman** [comment]
Ok...

Setting `publicPath: '/'` and changing the entry to -

```
entry: {
  app: './src/app.js',
  auth: './src/modules/auth/app.js',
},
...
new HtmlWebpackPlugin({
  filename: 'module/auth/index.html',
  template: 'src/index.html',
  inject: true,
  chunks: ['vendor', 'auth']
})
```
Injects the below and places auth.js in root using absolute paths, which is not what we want.
```
<script type="text/javascript" src="/vendor.js"></script>
<script type="text/javascript" src="/auth.9cb34237.js"></script>
```
Using entry `'module/auth/auth': './src/modules/auth/app.js'` and plugins `chunks: ['vendor', 'module/auth/auth']` results in an absolute path which is not ideal  as anyone trying to open locally will fail to load those resources :/

```
<script type="text/javascript" src="/vendor.js"></script>
<script type="text/javascript" src="/modules/auth/auth.9f1f4566.js"></script>
```

Any other way to handle this?

Thanks

**Comment by jantimon** [comment]
If you specify an absolute `publicPath` all your url paths will be absolute.  
That's how publicPath works.

I guess the problem is that we don't support `/` in entry names (yet).

```
<script type="text/javascript" src="../../vendor.7c5b44e9.js"></script>
<script type="text/javascript" src="../../module/auth/auth.9fbb17da.js"></script>
```

But the path does still resolve the correct file doesn't it?

**Comment by mybigman** [comment]
Yes the path resolves as of my last post providing served off server. Hopefully more features are added to this awesome plugin which gives fine grade control :)

**Comment by jantimon** [comment]
Right now this is the current logic - maybe you could come up with a better solution?

https://github.com/jantimon/html-webpack-plugin/blob/cef150258e58721dc0a4c1b89091401b7cc446ba/index.js#L443-L457

**Comment by mybigman** [comment]
I will have a look through your code and if there's anything.

I will close as it currently resolves the issue.

Thanks...  much appreciated.
