### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by tzookb** [jantimon/html-webpack-plugin#1010]
## Expected behavior

well simply work

## Current behavior

currently, it breaks, with this error

`Path must be a string. Received undefined`

## Environment

Node.js v8.10.0
darwin 17.7.0
webpack 3.5.5
html-webpack-plugin 3.2.0

### Config

https://gist.github.com/tzookb/17ae6356478344f9429d46c94756c59a

Copy your template file if it is part of this issue:
this could work as well, as even if I dont set a template it breaks.

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
    </body>
</html>
```

## Relevant Links

https://gist.github.com/tzookb/17ae6356478344f9429d46c94756c59a

## Additional contex

Even when I try to load the plugin with only the defaults it still breaks, that is why I tried to fill out all the defaults just in case but still the same issue. When I remove the plugin, the build works

**Comment by jantimon** [comment]
I took a look and your config does not use the html-webpack-plugin:
https://gist.github.com/tzookb/17ae6356478344f9429d46c94756c59a#file-webpack-config-js-L75-L105

Hey thank you for submitting a bug report 👍  
I having troubles to find out how I could reproduce this bug.  
Could you please try to create a minimal reproduction example (especially remove all dependencies, loaders and plugins which are not necessary for reproduction) and attach it (with out node_modules) as a zip to this issue?

Could you please try to create a minimal reproduction example (especially remove all dependencies, aliases, loaders and plugins which are not necessary for reproduction) and attach it (with out node_modules) as a zip to this issue?
