### ISSUE TITLE
SSR with mini-css-extract-plugin problem 

### ISSUE THREAD

**Issue by kingda** [jantimon/html-webpack-plugin#1011]
### This is original problem : [issues#219](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/219)
The author of it tell me to get some help from here . And This is the github for the bug ： [ NS-Bug](https://github.com/kingda/mini-css-extract-plugin-NS-bug) 

I hoped that u can fixed it . Thanks~

**Comment by jantimon** [comment]
similar to #579 - it can probably not be solved by the html-webpack-plugin.
