### ISSUE TITLE
html-webpack-plugin@4.0.0-alpha - webpack is not defined

### ISSUE THREAD

**Issue by ganapativs** [jantimon/html-webpack-plugin#1012]
## Expected behaviour

html-webpack-plugin should write html with compiled bundles.

## Current behaviour

html-webpack-plugin throws `ReferenceError: webpack is not defined` on 4.0.0-alpha version, works with package version 3.2.0.

```
    ERROR in Template execution failed: ReferenceError: webpack is not defined
    
    ERROR in   ReferenceError: webpack is not defined
      
      - loader.js:25 eval
        [landing.ejs?.]/[html-webpack-plugin]/lib/loader.js:25:52
      
      - loader.js:44 module.exports
        [landing.ejs?.]/[html-webpack-plugin]/lib/loader.js:44:3
      
      - index.js:286 HtmlWebpackPlugin.executeTemplate
        [oooo]/[html-webpack-plugin]/index.js:286:14
      
      - index.js:176 Promise.resolve.then.then.then.then.then.compilationResult
        [oooo]/[html-webpack-plugin]/index.js:176:20
      
      - next_tick.js:68 process._tickCallback
        internal/process/next_tick.js:68:7
```

## Environment
OS: MacOS 10.13.6 (darwin 17.7.0)
Node: 10.6.0
NPM: 6.1.0
Yarn: 1.7.0
html-webpack-plugin: 4.0.0-alpha
webpack: 4.16.2 
webpack-cli: 3.1.0

### Config

```js
module.exports = {
  entry: 'app.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  module: {
    rules: [
      ...
    ]
  }
  plugins: [
    new HtmlWebpackPlugin({
		title,
	    filename: `landing.html`,
	    template: `landing.ejs`,
	    inject: false,
	    chunksSortMode: 'none',
	}),
    ...
  ]
}
```

## Additional context

Was trying out alpha package to find fix for multi compiler rebuild speed issues.

**Comment by jantimon** [comment]
Do you have any idea why this is not happening here?
https://travis-ci.org/jantimon/html-webpack-plugin/jobs/404444866

**Comment by ganapativs** [comment]
I'm not sure, I'll try to create reproduce repo asap. But everything works fine with  package version 3.2.0, did any configuration changed?

**Comment by ganapativs** [comment]
Reproduced bug here 👉 https://github.com/ganapativs/html-webpack-plugin-bug-reproduce

Looks like its bug with `webpack` variable used in ejs template. This used to work with 3.2.0, now it doesn't! Alternatives?

**Comment by jantimon** [comment]
Wow - that's one of the best reproduction tickets I have seen here 👍

Unfortunately this behaviour is a "feature" it will speed up the build a lot.  
The template variable structure was changed and will change even a little bit more in the alpha.

To reproduce the exact same values like in 3.x you would have to use the `templateParameters` option with a function.

Please let me know if that helps or if you need further information on this topic.

**Comment by ganapativs** [comment]
Great, I'll try to replace `webpack` variable with `htmlWebpackPlugin` options and see if I can achieve the same thing with it 👍
