### ISSUE TITLE
Javascript chunks that do not end in `.js` are excluded

### ISSUE THREAD

**Issue by sechel** [jantimon/html-webpack-plugin#1013]
## Expected behaviour

Add javascript chunk files that do not end in `.js`.

## Current behaviour

Chunk files that do not end in `.js` are excluded explicitly since `v3.0.4`, see 0348d6b48c7313806bc3350ac6516f1ad1bff645.

## Environment

This problem occurs when using `html-webpack-plugin` in conjunction with `karma-webpack` as they use the chunk name as file name (https://github.com/webpack-contrib/karma-webpack/blob/1ac16eaa7b11ee154a2127d4f03cbfd1a81533f6/src/karma-webpack.js#L65). Not sure though who should move you or them 😄.

**Comment by jantimon** [comment]
Oh thanks a lot 👍 
Right now we are doing some heavy lifting to get to version 4 of the plugin: https://github.com/jantimon/html-webpack-plugin/pull/953

Maybe the asset gathering will also pick up karma-webpack files.  
However filtering for `.js` chunks doesn't sound wrong to me

**Comment by sechel** [comment]
Hey @jantimon, the best thing would be to analyze the contents of the asset (or maybe webpack does know anyways?). But actually you are right it sound more right to me that the `karma-webpack` folks should rename their test bundles to end with `.js` 😄 I will link from their place to here.

**Comment by sechel** [comment]
See also https://github.com/webpack-contrib/karma-webpack/issues/334
