### ISSUE TITLE
How to include link to css file with inlined (base64) urls

### ISSUE THREAD

**Issue by whitecolor** [jantimon/html-webpack-plugin#1015]
Sorry for bothering with a support question for a few days could not get any answer on the SO.

Input:
1) Webpack 3.
2) Css file with urls to OTF font files.
3) HtmlWebpackPlugin

Output:
1) Html that contains link to **hashed** css file produced from original css and with inlined base64 fonts.
2) This css is copied to build dir while build and should work with dev-server

What are the ways to accomplish this?

I found it really cumbersome to figure out what plugins and workflow should be used shuld there be used `copy-webpack-plugin` and `html-webpack-include-assets-plugin`, I didn't see the obvious straightforward solution for this seemed to be a simple task.

**Comment by jantimon** [comment]
This should work with the https://github.com/webpack-contrib/mini-css-extract-plugin instead of the copy-webpack-plugin
