### ISSUE TITLE
Infinite loop/out of memory when attempting to reference a variable in a custom template

### ISSUE THREAD

**Issue by toebes** [jantimon/html-webpack-plugin#1019]
## Expected behaviour

html-webpack-plugin should not go into an infinite loop and properly process a file include

## Current behaviour

html-webpack-plugin runs out of memory in an infinite loop. 

```
<--- Last few GCs --->

[1744:000001882C91A720]   229864 ms: Mark-sweep 1324.3 (1435.1) -> 1310.4 (1421.2) MB, 97.6 / 0.0 ms  allocation failure GC in old space requested
[1744:000001882C91A720]   229970 ms: Mark-sweep 1310.4 (1421.2) -> 1310.4 (1378.7) MB, 105.9 / 0.0 ms  last resort GC in old space requested
[1744:000001882C91A720]   230060 ms: Mark-sweep 1310.4 (1378.7) -> 1310.4 (1378.7) MB, 89.5 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000002002C9A57C1 <JSObject>
    0: builtin exit frame: stringify(this=000002002C988FF1 <Object map = 000003F7EE082BA1>,000000C8578022D1 <undefined>,000000C8578022D1 <undefined>,00000185439BAE41 <Very long string[25447510]>)

    1: arguments adaptor frame: 1->3
    2: /* anonymous */(aka /* anonymous */) [U:\JOHN\WebSites\Ciphers\node_modules\webpack\lib\EvalSourceMapDevToolModuleTemplatePlugin.js:98] [bytecode=000003388...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewRawTwoByteString
 5: v8::internal::Smi::SmiPrint
 6: v8::internal::StackGuard::HandleInterrupts
 7: v8::internal::wasm::LocalDeclEncoder::Size
 8: v8::internal::wasm::LocalDeclEncoder::Size
 9: v8_inspector::protocol::Debugger::API::SearchMatch::fromJSONString
10: v8_inspector::protocol::Debugger::API::SearchMatch::fromJSONString
11: 000002AADAD06B21
The terminal process terminated with exit code: 3
```

## Environment

Node.js v8.11.1
win32 10.0.17134
npm 6.3.0
webpack@4.16.4
html-webpack-plugin@3.2.0

### Config

I started with with the example from https://github.com/jantimon/html-webpack-plugin/tree/master/examples/custom-template and made the following changes:

I updated `webpack.config.js` to eliminate the use of the extract-text-webpack-plugin and fixed the errors webpack complained about `loaders` under `module`.    Lastly, I added a `part` option passed into the html-webpack-plugin so that it can be used in the template.

```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin')
var webpackMajorVersion = require('webpack/package.json').version.split('.')[0];

module.exports = {
  context: __dirname,
  entry: './example.js',
  output: {
    path: path.join(__dirname, 'dist/webpack-' + webpackMajorVersion),
    publicPath: '',
    filename: 'bundle.js'
  },
  module: {
    rules: [
      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
      { test: /\.png$/, loader: 'file-loader' }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'template.html',
      part: 'partial.html',
    }),
  ]
};
```

Additionally I updated the template.html file to use the `part` option passed in for the require statement.  

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title><%= htmlWebpackPlugin.options.title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= require('html-loader!./'+htmlWebpackPlugin.options.part) %>
</body>
</html>
```

## Relevant Links

Complete repro project can be found at:
https://github.com/toebes/webpack-plugin-bug

## Additional contex

After quite a bit of debugging I have determined a number of things 
1) If I kept the line in template.html as 
  <%= require('html-loader!./partial.html' %>
it successfully runs as expected.  It is only when I attempt to reference `htmlWebpackPlugin.options._anything_` that it runs out of memory.  

2) If you delete any of the files out of the `Languages` directory, it fails in a different manner.  Note that none of the files in that directory are actually used by the example or emitted in the result, but their existence affects running.

**Comment by toebes** [comment]
Ok, I've tried changing template.html to be

```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>
        <%= title %>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <!-- change the next line to 'html-loader!./partial.html' to avoid the bug -->
    <!-- %= require('html-loader!./'+htmlWebpackPlugin.options.part) %-- >
    <%= require('html-loader!./partial.html') %>
    <!-- <%= require('html-loader!'+base) %> -->
</body>

</html>
```
and the plugins portion of webpack.config.js to be:
```js
    plugins: [
        new HtmlWebpackPlugin({
            templateParameters: {
                base: './partial.html',
                title: "this is the title",
              },
            template: 'template.html',
        }),
````

and the result is even more bizarre:
  ERROR in Template execution failed: Error: Cannot find module 'html-loader!./partial.html'
  ERROR in   Error: Cannot find module 'html-loader!./partial.html'

**Comment by jantimon** [comment]
To be honest I am not 100% sure why this would happen but you are using a require with expression:
`<%= require('html-loader!./'+htmlWebpackPlugin.options.part) %>` https://webpack.js.org/guides/dependency-management/#require-with-expression

Webpack can't import during runtime so it has to import during build time.  
That means that it will analyse from `require('html-loader!./'+htmlWebpackPlugin.options.part)` that you might want to import a file from your current directory and try to include **all** files in your current directory into the bundle. 

From their [docs](https://webpack.js.org/guides/dependency-management/#require-with-expression):

> context module
> 
> A context module is generated. It contains references to all modules in that directory that can be required with a request matching the regular expression. The context module contains a map which translates requests to module ids.

**Comment by toebes** [comment]
I could have my files include a common header/footer.  Is there a good example on how to do that?

**Comment by jantimon** [comment]
Unfortunately not but maybe someone on stackoverflow can help.
