### ISSUE TITLE
devServer not works on files required in HtmlWebpackPlugin options

### ISSUE THREAD

**Issue by pldg** [jantimon/html-webpack-plugin#1020]
https://github.com/webpack/webpack-dev-server/issues/1431

**Comment by jantimon** [comment]
You use require inside `webpack.config.js` to a react file - I guess that won't work.

**Comment by pldg** [comment]
I'm not using react.

I built a simple static site generator with Webpack: I use *page1.js* to generate static html contents and require it inside `HtmlWebpackPlugin` to generate html file.

My project only have those files:

- *webpack.config.js* - with **only** `HtmlWebpackPlugin` configuration inside, as seen in the link above
- *index.js* - with **only** a simple `console.log` statement, this is the **only** entry point
- *html-template.ejs* - as seen in the link above
- *page1.js* - as seen in the link above

When I run `webpack` everything works fine, *dist/index.html* is generated along side with *dist/main.js*.

If I run `webpack-dev-server` and try to edit *page1.js*, `devServer` doesn't update the changes.

**Comment by jantimon** [comment]
Oh sorry I completely misread your post.  
There is no HMR support for the html-webpack-plugin.

Most people manipulate the html afterwards using javascript so it's almost impossible to roll those changes back, apply the changes, and rerun the javascript changes again.

The only way would be to reload the entire page on every change - but that would probably be an awful developer experience.

Do you have any suggestions how HMR could work for the html-webpack-plugin?

**Comment by pldg** [comment]
I'm not sure I completely understand. I know that `devServer` doesn't watch for *webpack.config.js* changes. But why `require` a file into *html-webpack-plugin* options doesn't connect that file to `devServer`? Instead, using a `require` call inside an *html-webpack-plugin* template will link that file to `devServer` correctly.

I don't have any suggestions on how to implement HMR for *html-webpack-plugin*.

**Comment by jantimon** [comment]
All require calls inside your webpack.config.js file are executed by node.  
All require calls inside html-webpack-plugin templates are executed by webpack.

That's why the ones from your webpack.config.js won't be tracked but the once inside your template are.
