### ISSUE TITLE
Error in tagged template literal in script tag

### ISSUE THREAD

**Issue by mizchi** [jantimon/html-webpack-plugin#1023]
## Expected behaviour

Pass this code.

```
<!--  index.html -->
<script>
  if (window.location.hostname !== 'localhost' && window.location.protocol === 'http:') {
    window.location.href = `https://${location.host}/${location.search}`
  }
</script>
```

## Current behaviour

```
ERROR in Template execution failed: ReferenceError: location is not defined

ERROR in   ReferenceError: location is not defined


  - loader.js:4 eval
    [index.html?.]/[html-webpack-plugin]/lib/loader.js:4:10

  - loader.js:9 module.exports
    [index.html?.]/[html-webpack-plugin]/lib/loader.js:9:3

  - index.js:284 Promise.resolve.then
    [myapp]/[html-webpack-plugin]/index.js:284:18

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

## Environment

```
    "webpack": "4.16.5",
    "html-webpack-plugin": "^3.2.0"
```

### Config

```
        new HtmlPlugin({
          template: path.join(__dirname, "src/index.html")
        }),
```

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
    <script>
        if (window.location.hostname !== 'localhost' && window.location.protocol === 'http:') {
          window.location.href = `https://${location.host}/${location.search}`
        }
    </script>
    </body>
</html>
```

**Comment by jantimon** [comment]
Could you please check if this bug has already been solved in the current alpha release?

```
npm i html-webpack-plugin@next
```

**Comment by RealWeeks** [comment]
I'm having this issue as well after running `npm i html-webpack-plugin@next`

**Comment by jantimon** [comment]
Okay we should add a unit test for that 👍

**Comment by acarl005** [comment]
I'm also having this issue.

**Comment by HairyRabbit** [comment]
looks it works when apply html-loader

**Comment by jantimon** [comment]
According to #950 this should be fixed:
https://github.com/jantimon/html-webpack-plugin/commit/e570fb473391c3bf6235a9921f9d27ef1aae509b

Unfortunately that didn't fix the entire issue - Any ideas how we could solve it?

**Comment by HairyRabbit** [comment]
yeap, the es6/erb template are all valid for lodash, but it's difficult to know which `${ ... }` are users want :). I think disable the es6 delimiter is the easy way.

**Comment by jantimon** [comment]
@HairyRabbit how can we disable the es6 delimiter in addition to https://github.com/jantimon/html-webpack-plugin/commit/e570fb473391c3bf6235a9921f9d27ef1aae509b ?

**Comment by no-simpler** [comment]
Definitely a problem for me.

My template is in fact a Thymeleaf template, and contains snippets similar to below that need to stay untouched:

```html
<html lang="en" xmlns:th="http://www.thymeleaf.org" th:lang="${#locale}">
```

I am using lodash to inject chunk filenames into the template.

Lodash, unfortunately, doesn’t provide an opportunity to escape ES template literal delimiter directly in template and only allows to replace said delimiter with custom RegExp using `_.templateSettings.interpolate = /{{([\s\S]+?)}}/g;`

@jantimon, is there a way to issue that command immediately before my template is compiled? Or should I move to, say, Handlebars? (Although, I dare not think what kind of delimiter collisions I’m going to encounter there.)

**Comment by jantimon** [comment]
Do you mean this code?

https://github.com/jantimon/html-webpack-plugin/blob/55e86ba3941b66da14ea33d60f1dda058cf6b66a/lib/loader.js#L26

It is part of the current beta

**Comment by funkyLover** [comment]
@jantimon same issue when using ES6 template in html.

I know it has been fixed in 4.x version, but In my team's projects are still in 3.x version. And wrote some plugins for team's need using the 3.x hooks API. 

can I fix this issue by extending htmlPlugin3.x with hooks?

**Comment by jantimon** [comment]
@funkyLover you can fix this by changing to another loader like this:

```
 new HtmlPlugin({
          template: require.resolve('./custom-loader') + '!!' + path.join(__dirname, "src/index.html")
        }),
```

**Comment by funkyLover** [comment]
@jantimon thanks!

just copy the [default loader](https://github.com/jantimon/html-webpack-plugin/blob/master/lib/loader.js),  and update config like `template: '!!' + require.resolve('./loader') + '!' + template` fix the problem.

**Comment by jantimon** [comment]
Cool 👍
