### ISSUE TITLE
Tune injections (injectAssetsIntoHtml)

### ISSUE THREAD

**Issue by yenesey** [jantimon/html-webpack-plugin#1026]
Hi.
Default injection look's like this:
before:
```
    <body>
      <div id="app"></div>
    </body>
```
after
```
    <body>
      <div id="app"></div>
<script src="vendors.js"></script></body>
```
But, what if I want to keep indentation?
so I modify regexp
`const bodyRegExp = /([\r|\n]*?)([\t| ]*?)(<\/body\s*>)/i;`

and replace
`html = html.replace(bodyRegExp, (match, g1, g2) => g1 + g2.repeat(2) + body.join('') +  match);`
where g1 is newline (if exists), g2 is indentation (if exists)

After that injection look's like this:
```
    <body>
      <div id="app"></div>
      <script src="vendors.js"></script>
    </body>
```
Head tag handled in the same way.
Dev's probably find more elegant solution...

**Comment by joepvl** [comment]
I ran into the same thing, and solved it using `htmlWebpackPlugin.files.(css|js)` in my template (which I only found out about in the docs earlier today, after having used this plugin for literally over a year and experiencing low-key OCD over the aesthetically unpleasing tag injections all that time 😉). For example, when using ejs:

```ejs
<html>
  <head>
    <!-- meta stuff, title, etc. -->
    <%=
      htmlWebpackPlugin.files.css.map(href =>
        `<link rel="stylesheet" type="text/css" href="${href}">`
      ).join("\n    ")
    %>
    <link rel="stylesheet" type="text/css" href="https://example.com/some-hardcoded-stylesheet.css">
  </head>
  <body>
    <div id="app">
    <%=
      htmlWebpackPlugin.files.js.map(src =>
        `<script type="text/javascript" src="${src}"></script>`
      ).join("\n    ")
    %>
  </body>
</html>
```

Be sure to put the right amount of indentation in the string you pass to `join()` when using this method, for maximum OCD satisfaction.
PS I'm almost sure there's a way to do the indentation more cleanly using `<%-` etc, but I kept getting  errors when trying that so I went with the above.
