### ISSUE TITLE
Copied hashed asset name in generated HTML

### ISSUE THREAD

**Issue by whitecolor** [jantimon/html-webpack-plugin#1028]
Could not get an answer on SO: https://stackoverflow.com/questions/51799293/copied-hashed-asset-name-in-generated-html

Input:

- Image png file
- Webpack 3
- HTMLPlugin

Output:
- Image file copied to the build dir with HASHED name
- Generated HTML (with HTLMPlugin) contains img tag with src pointing to a copied image file.

What is the best way to achieve this? Myabe using copy-webpack-plugin? But I'm not sure how. Advice would be appreciated.

**Comment by whitecolor** [comment]
Thanks! Didn't know that it was possible to use `require` inside ejs template found it in https://github.com/jantimon/html-webpack-plugin/blob/master/migration.md#loaders-in-templates

maybe should be in the main README.

**Comment by whitecolor** [comment]
@jantimon 

if to use `js` for templates, is it possible to access `htmlWebpackPlugin.options` from there somehow?
```
module.exports =  `<!DOCTYPE html>
<html>
```

**Comment by jantimon** [comment]
Yes you can export a function which returns the string

**Comment by whitecolor** [comment]
Very nice, thanks)
