### ISSUE TITLE
Invalidate templateParameters cache

### ISSUE THREAD

**Issue by quentinneyraud** [jantimon/html-webpack-plugin#1037]
## Expected behaviour

Invalidate `templateParameters` option cache

## Current behaviour

`templateParameters` values remain the same on all build with `webpack-dev-server`

## Environment

Node version: 10.7.0
Npm version: 6.1.0
webpack version: 4.17.1
html-webpack-plugin version: 3.2.0 

### Config

```js

// pages/home/data.js
module.exports = {
  pageName: 'home',
  title: 'Hello world'
}


```

```pug
//- pages/home/index.pug
extends ../../base.pug

block content
  h1= title

```

```js
// webpack.config.js

// plugins
new HtmlWebpackPlugin({
    'dist/index.html',
    template: 'pages/home/index.pug',
    templateParameters: () => ({
      ...require('pages/home/data.js')
    })
  })

// and

new ExtraWatchWebpackPlugin({
    files: [ 'pages/home/data.js' ]
  })
```

I try to generate HTML files using HtmlWebpackPlugin to inject datas from `data.js` in `index.pug`. It works well with `webpack` command but i want to regenerate HTML files when i update `data.js` file with `webpack-dev-server` command. I added [ExtraWatchWebpackPlugin](https://github.com/pigcan/extra-watch-webpack-plugin#readme) to watch data file (not included in webpack bundle) and rebuild on update but datas in the builded HTML file never change.

I tried :
- set `cache: false` in HtmlWebpackPlugin options
- return object in `templateParameters` option

```js
// webpack.config.js

// plugins
new HtmlWebpackPlugin({
    'dist/index.html',
    template: 'pages/home/index.pug',
    templateParameters: {
      ...require('pages/home/data.js')
    }
  })
```

**Comment by jantimon** [comment]
The `webpack.config.js` is not compiled by webpack and therefore it is not watched.  
Same is true for all require statements inside the `webpack.config.js` file.

What you could try instead is to use a javascript file as template:

template.js
```
module.exports = function(templateData) {
  const data = {...templateData, require('pages/home/data.js')};
  return require('./pages/home/index.pug')(data);
}
```

Please let me know if that worked for you :)

**Comment by quentinneyraud** [comment]
I have `SyntaxError: Unexpected token extends` when i require `pug` file, i think because `pug-loader` is not added yet. when i require my template.

**Comment by quentinneyraud** [comment]
It works ! I just updated webpack config :

Instead of

```js
new HtmlWebpackPlugin({
    'dist/index.html',
    template: 'pages/home/index.pug',
    templateParameters: () => ({
      ...require('pages/home/data.js')
    })
  })
```

i delete the require cache like this

```js
new HtmlWebpackPlugin({
    'dist/index.html',
    template: 'pages/home/index.pug',
    templateParameters: () => {
      delete require.cache['pages/home/data.js']
      return {
        ...require('pages/home/data.js')
      }
    }
  })
```

Thank you for your help

**Comment by jantimon** [comment]
Cool 👍
