### ISSUE TITLE
Replace pretty-error?

### ISSUE THREAD

**Issue by honzajavorek** [jantimon/html-webpack-plugin#1040]
I don't know how important `pretty-error` is for the functionality of `html-webpack-plugin`, but it has some serious licensing issues down its dependencies: https://github.com/AriaMinaei/RenderKid/issues/8

It seems to me @fb55's dependencies and the `css-select` project act as a single point of failure in such a successful project as `html-webpack-plugin` is. Even if you don't care about licensing, it's apparently naive to expect the dependencies will ever get updated, bugs fixed, etc.

**Comment by jantimon** [comment]
The html-webpack-plugin allows you to use very complex templates and even pure javascript code as a template (just use a `.js` file). If the evaluation of this code fails I tried to provide as much useful information as possible and came across pretty error.

However the current pretty error integration has definitely some room for improvements - maybe @AriaMinaei could take a look at the current implementation.

@honzajavorek  Can you recommend a similar solution?

**Comment by AriaMinaei** [comment]
This is important. I'm looking for a replacement for css-select now. Will ping you guys here once it's done.

**Comment by AriaMinaei** [comment]
Not yet. Trying to find the time to do [this](https://github.com/AriaMinaei/RenderKid/issues/8#issuecomment-420257615) :)
