### ISSUE TITLE
issue with root path w/ express router

### ISSUE THREAD

**Issue by brewster1134** [jantimon/html-webpack-plugin#1043]
i have been having an issue with integrating the html plugin with express only with using the root path

```javascript
router.get('/', function() {console.log('this IS NOT logging when requesting http://localhost')});
router.get('/foo', function() {console.log('this IS logging when requesting http://localhost/foo')});
```

if i remove the html-webpack-plugin from my webpack.config, the router works as expected. i have trued using both `app.use rootRouter` and `app.use '/', rootRouter`, but the result is the same. is there special treatment needed for this to work with the root path?

and oddly, ONLY when i request the root page, does the html plugin render the html file with my entry points in the markup. on the pages that seem to use the router correctly, there are no link or script tags with my webpack bundles added to the markup

**Comment by jantimon** [comment]
Sorry I don't know how I might help you with your express configuration.  
Maybe asking on stackoverflow could help.
