### ISSUE TITLE
ReferenceError: webpack is not defined

### ISSUE THREAD

**Issue by pl12133** [jantimon/html-webpack-plugin#1046]
## Expected behaviour

The global `webpack` representing the webpack stats object should be available inside of a template; as described in the [README](https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates), under "The following variables are available in the template" -> `webpack`.

## Current behaviour

As of `html-webpack-plugin@next`, the global `webpack` is NOT available inside of a template.

## Environment

Affected versions are `4.0.0-alpha` and `4.0.0-alpha.2`.

### Config

The issue is present using default Webpack config, with a custom template that accesses the `webpack` object:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <% for (var chunk of webpack.chunks) { %>  <!-- This is the relevant line -->
      <% for (var file of chunk.files) { %>
        <% if (file.match(/manifest\.json$/)) { %>
          <link rel="manifest" href="<%= htmlWebpackPlugin.files.publicPath + file %>">
        <% } %>
      <% } %>
    <% } %>
  </head>
  <body>
    <noscript>
      Please enable JavaScript.
    </noscript>
  </body>
</html>
```

## Additional context

I apologize for not providing a minimal reproduction case, but this bug seems very cut and dry: the relevant code appears *fixed* on master:

https://github.com/jantimon/html-webpack-plugin/blob/55abb36ee8cad6e8eb32fcc0848c785099316f2d/index.js#L719-L729

However when installing from `npm`, the `webpack` property is not defined in the `templateParametersGenerator` function:

```js
function templateParametersGenerator (compilation, assets, assetTags, options) {
  const xhtml = options.xhtml;
  assetTags.headTags.toString = function () {
    return this.map((assetTagObject) => htmlTagObjectToString(assetTagObject, xhtml)).join('');
  };
  assetTags.bodyTags.toString = function () {
    return this.map((assetTagObject) => htmlTagObjectToString(assetTagObject, xhtml)).join('');
  };
  return {
    compilation: compilation,
    webpackConfig: compilation.options,
    htmlWebpackPlugin: {
      tags: assetTags,
      files: assets,
      options: options
    }
  };
}
```

## Workaround

Since the `webpack` object is produced by the `compilation` object, access `compilation.toStats().toJson()` instead of `webpack`.

___

Thanks, let me know if I can help.

**Comment by jantimon** [comment]
Hey - thanks for your report.  
This behavior is a feature 😄

The direct access to the stats object was removed as it is slow since webpack 3

So it’s not set by default to be faster for people who don’t need the object anyway

**Comment by pl12133** [comment]
@jantimon Thank you for clearing that up, I didn't realize accessing the stats object degraded performance after webpack3. I can use my workaround to access the stats object if I still need it.

I'm wondering how this could fit into the `README`; we can probably remove the list item for the `webpack` stats object and mention it is available through the `compilation` object instead.
