### ISSUE TITLE
HtmlWebpackPlugin for multiple files and Webpack-dev-middleware. won't work for the code below.

### ISSUE THREAD

**Issue by pks90** [jantimon/html-webpack-plugin#1050]
Following the post by @jantimon in [#145](https://github.com/jantimon/html-webpack-plugin/issues/145#issuecomment-170554832)

How can work for a project where HtmlWebpackPlugin works for multiple html files.

I have mentioned the details in the following thread,

https://stackoverflow.com/questions/52399795/bundle-js-served-via-webpack-not-working-for-webpack-dev-middleware-htmlwebpac

**Comment by jantimon** [comment]
Hey @pks90 

you added so much code and configuration and it would take me very long to understand why you added all those components together and what you expect it to do.

Could you please try to remove as much as possible so I can get a better understanding whats going on?

**Comment by pks90** [comment]
I have modified the code a bit specially the `srcServer.js` file. I think `webpack.config.js` doesn't have any extra code i.e. you may need it to understand my configuration. 

In this application I want to emit various html pages via webpack and for that you will see multiple **new HtmlWebpackPlugin({}) ...** statements.

In the screenshots there are two things :


- Project structure so that if there is a relative path issue present it can be figured out easily.
- Inspect element showing the page source where bundle.js emmited by webpack is present that has all the js bundles present. 

The problem is that the function which you have suggested in #145 returns/redirects the index.html for any of the url hits.

e.g. when I hit localhost:8080/dashboard then I should get dashboard.html instead I receive index.html

I am also not getting why the javascript (bundle.js) doesn't execute methods on the index.html page. Maybe its something related to **webpack-dev-middleware** and calling the jquery methods in the following way ,

```
$(document).ready(function() {

  $("#formAlert").show()

  window.login = function() {
    getUsers().then(result => {
      if(isJson(result)) {
        var udetail = JSON.parse(createJSONLogin())
        var arr = $.parseJSON(result)
        for (var i = 0, len = arr.length; i < len; i++) {
          if(arr[i].uname === udetail.uname && arr[i].pass === udetail.pass)
          {
            window.location.href = getBaseUrl()+"dashboard"
          }
          else
          {
            $("#formAlert").removeClass("hidden")
            $("#formAlert").show()
          }
        }
      }
    })
  }
});
```

**Comment by pks90** [comment]
@jantimon 

Do you have any inputs on the resolution of this ?

**Comment by jantimon** [comment]
@pks90 the link seems to be broken.

could you please try to reduce your devDependencies and dependencies?  
I guess we won't need more than 10 to reproduce this issue.

Also most of the files in the `src` folder don't seem to be related to this issue.

**Comment by pks90** [comment]
@jantimon , removed non required dependencies and to execute the project as required you will need the artifacts present in the src folder , you may please avoid the files in src as most of them are used by copywebpack plugin.

**Comment by jantimon** [comment]
```
app.use(WebpackHotMiddleware(compiler))
```

This line has to be removed on production

**Comment by pks90** [comment]
@jantimon  **I am doing development and the above code doesn't work as expected that is the problem.** I have a different webpack file for the production that's not an issue.

**Comment by jantimon** [comment]
Okay so what was your problem again?

**Comment by pks90** [comment]
HTML code changes do not reflect on the browser even though I see HMR Connected in the console.
For any url that I try to hit , I get redirected to the login page again (I don't want this as want to make a MPA and not SPA).
