### ISSUE TITLE
Add support for AMD libraries

### ISSUE THREAD

**Issue by eemeli** [jantimon/html-webpack-plugin#1052]
This is related to webpack/webpack#8079, i.e. the requirement to set `libraryTarget: 'amd'` when depending on any external libraries that are only available as AMD dependencies. When using that target, the Webpack output is wrapped in a `define()` wrapper, and therefore is not directly executed when imported.

As a result, HtmlWebpackPlugin is not currently usable in this case as the `generatedScriptTags` method (on the webpack-4 branch, which I presume is the current dev target) hard-codes the script tag representation.

Here's a sketch of a minimal fix for the issue. I'm willing to turn it into a proper PR if given a bit of direction for the proper way of doing this:

```diff
--- a/index.js
+++ b/index.js
@@ -211,7 +211,7 @@ class HtmlWebpackPlugin {
           // And allow third-party-plugin authors to reorder and change the assetTags before they are grouped
           .then(({assets}) => getHtmlWebpackPluginHooks(compilation).alterAssetTags.promise({
             assetTags: {
-              scripts: self.generatedScriptTags(assets.js),
+              scripts: self.generatedScriptTags(assets.js, compilation.options),
               styles: self.generateStyleTags(assets.css),
               meta: [
                 ...self.generatedMetaTags(self.options.meta),
@@ -676,7 +676,18 @@ class HtmlWebpackPlugin {
    * @param {Array<string>} jsAssets
    * @returns {Array<HtmlTagObject>}
    */
-  generatedScriptTags (jsAssets) {
+  generatedScriptTags (jsAssets, webpackConfig) {
+    if (webpackConfig.output.libraryTarget === 'amd') {
+      const req = jsAssets.map(scriptAsset => (
+        JSON.stringify('./' + scriptAsset.replace(/\.js$/, ''))
+      ))
+      return [{
+        tagName: 'script',
+        voidTag: false,
+        attributes: {},
+        innerHTML: `require([${req.join(',')}])`
+      }]
+    }
     return jsAssets.map(scriptAsset => ({
       tagName: 'script',
       voidTag: false,
```

**Comment by jantimon** [comment]
I am not sure about this - are `amd` libraries really meant to be executed directly?

**Comment by eemeli** [comment]
I guess that's pretty much the same as asking whether ES6 modules are meant to be executed directly. :)

The now-merged Webpack PR that's linked above should in fact provide a solution to my problem by adding a new "amd-require" library target that produces code with `require()` rather than `define()` as a wrapper, which means that nothing needs to be done here.
