### ISSUE TITLE
[4.0.0-alpha.2] show html-webpack-plugin-after-emit error

### ISSUE THREAD

**Issue by s524797336** [jantimon/html-webpack-plugin#1054]
## Expected behaviour

not show this error

## Current behaviour

show error 
error: plugin could not be registered at 'html-webpack-plugin-after-emit'. Hook was not found.
but 4.0.0-alpha is ok

**Comment by jantimon** [comment]
The event names have changed:

![Event Flow](https://raw.githubusercontent.com/jantimon/html-webpack-plugin/14b4456ba67a5b85421b558bbd5f1d59c7b410b3/flow.png)

**Comment by s524797336** [comment]
So how to prevent this crash?

**Comment by jantimon** [comment]
Don't use  'html-webpack-plugin-after-emit'
