### ISSUE TITLE
[4.0.0-alpha.2] Files are not injected into custom template

### ISSUE THREAD

**Issue by pshurygin** [jantimon/html-webpack-plugin#1056]
## Expected behaviour
When setting inject: false and using 
```html
<% _.each(htmlWebpackPlugin.files.js, function(file){ %>
    <script src="<%= file.path %>"></script>
<% }); %>
```
in template there should be generated <script> tags with correct file references in src attribute

## Current behaviour

Generated html file contains <script src="(unknown)"> tags. The same issue goes for link tags

## Environment

The issue appeared after updating from 4.0.0-alpha to 4.0.0-alpha.2. Reverting version back solves the problem.

node v 8.9.4
npm v 5.8.0
windows 10

### Config

```js
module.exports = {
  entry: 'app.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  module: {
    rules: [
      ...
    ]
  }
  plugins: [
           new HtmlWebpackPlugin({
                filename: 'index.html',
                template: 'Frontend/index.html',
                inject: false,
                chunks: ['runtime', 'vendor','common']
            }),
  ]
}
```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <title></title>

    <% _.each(htmlWebpackPlugin.files.css, function(file){ %>
    <link href="<%= file.path %>" rel="stylesheet"></link>
    <% }); %>
</head>
<body>
    <app></app>
    <% _.each(htmlWebpackPlugin.files.js, function(file){ %>
    <script src="<%= file.path %>"></script>
    <% }); %>
</body>
</html>
```

**Comment by jantimon** [comment]
Unfortunately we had to change it once again so right now you would have to drop the `.path` part:

https://github.com/jantimon/html-webpack-plugin/blob/3c9740572d661c66ae15419b3da694fdfbcee949/index.js#L895-L932

**Comment by pshurygin** [comment]
Ok, thanks to the provided source code change i managed to make it work using this for link tags (no loop required):
`<%= htmlWebpackPlugin.tags.headTags %>`
And this is for script tags: 
`<%= htmlWebpackPlugin.tags.bodyTags %>`

So the result template should look like this:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <title></title>
    <%= htmlWebpackPlugin.tags.headTags %>
    <!-- your custom additional tags may go here -->
</head>
<body>
    <app></app>
    <%= htmlWebpackPlugin.tags.bodyTags %>
    <!-- your custom additional tags may go here -->
</body>
</html>
```
