### ISSUE TITLE
html-webpack-plugin output html with id="app" div empty

### ISSUE THREAD

**Issue by dextherry** [jantimon/html-webpack-plugin#1058]
Hi, I am running this plugin into an laravel mix project, but the generated html file has the id="app" empty 

```
//this is the generated index.html 
<div id="app"></div>
<script src="js/app.js"></script>
```

is there a way to output the content that is generated for the app.js file? (as loaded in the browser when the app run)
like this:
```
//this is the generate index.html 
<div id="app">
**this is the html content**
</div>
<script src="js/app.js"></script>
```

this is the plugin options:

```
mix.js('resources/assets/js/app.js', 'public/js')
    .webpackConfig({
        plugins: [
          new HtmlWebpackPlugin({
           template: Mix.paths.root('resources/views/home/index.blade.php'),
           inject: false
         }),
        ],
      });
```

**it is possible to render correctly html generated by the vue code**? currently it is only generated an html file with the php file content without rendering the vue part

Thanks

**Comment by jantimon** [comment]
Yes that's called server side rendering - it's pretty advanced and I haven't tested it with vue.  
You would have to use a `.js` file as template which would execute the app server side rendering.
