### ISSUE TITLE
webpack4 splitChunks with html-webpack-plugin

### ISSUE THREAD

**Issue by cfkxzsat** [jantimon/html-webpack-plugin#1069]
Someone could tell me if I can do this or not.
I asked on stackoverflow, but no response...I need help...Thx in advance!!

[https://stackoverflow.com/questions/52621102/webpack4-splitchunks-html-webpack-plugin-mpa](https://stackoverflow.com/questions/52621102/webpack4-splitchunks-html-webpack-plugin-mpa)

## Expected behaviour

html will be generated after splitChunks name callback execute.

## Current behaviour

I can't get common chunk info when generating html files.

## Environment

webpack4

**Comment by jantimon** [comment]
Did you try the html-webpack-plugin@next version?  
It should allow splitting out of the box

**Comment by cfkxzsat** [comment]
Wow! That's awesome!It worked.
But is there a beta version of html-webpack-plugin 's documentation out there?or change log?
:-)

**Comment by sibelius** [comment]
`html-webpack-plugin@next` is ready?

**Comment by 354503413** [comment]
Child dependence , That's a good idea

**Comment by 354503413** [comment]
splitChunks Dependency automatic injection , That's a good idea

**Comment by 354503413** [comment]
splitChunks Dependency automatic injection , Very important

**Comment by jantimon** [comment]
Some plugins have not been updated for the html-webpack-plugin but if you don't need them you should be good to go :)
