### ISSUE TITLE
[4.0.0-beta.1] @types/tapable installed as a dependency

### ISSUE THREAD

**Issue by AviVahl** [jantimon/html-webpack-plugin#1075]
## Expected behaviour

`html-webpack-plugin` should not install any `@types` packages in user's project.

## Current behaviour

`html-webpack-plugin` has `@types/tapable` as a dependency in its `package.json`, so package is installed in user's project.

## Environment

```
Node.js v8.12.0
linux 4.18.12-200.fc28.x86_64
6.4.1
stylable@ /home/avi/projects/stylable
└── webpack@4.20.2

stylable@ /home/avi/projects/stylable
└── html-webpack-plugin@4.0.0-beta.1```
```

### Config

Irrelevant.

**Comment by jantimon** [comment]
Yes that seems quite valid the @types/tapable is only required if you would write a plugin for the html webpack plugin 

Could you please create a pull request?

**Comment by AviVahl** [comment]
done. had to adjust fixture bundles, as upstream webpack changed output a bit.

**Comment by jantimon** [comment]
Thanks @AviVahl 

I'll add it again if plugin authors are having problems typing hooks of the html-webpack-plugin.
