### ISSUE TITLE
es6 imported variables don't work with options in ejs templates

### ISSUE THREAD

**Issue by soulofmischief** [jantimon/html-webpack-plugin#1077]
## Expected behaviour

In the following code, `title` is missing from options when accessed inside the ejs template.

#### vars.js
```
export const title = 'Hello world'
```

#### plugins.js
```
import { title } from './vars'

export default [ 
  new HtmlWebpackPlugin({
    template: './index.ejs',
    title,
  }),
]
```

#### index.ejs
```
<!DOCTYPE html>
<head>
  <title><%= htmlWebpackPlugin.options.title %></title>
</head>
</html>
```

The title of the document should be "Hello world".

## Current behaviour

Title is missing from the options parameter in htmlWebpackPlugin.

I tested this by appending `<%= JSON.stringify( htmlWebpackPlugin.options ) %>` to the template.

## Environment
Node.js v10.12.0
linux 4.18.7-200.fc28.x86_64
npm@6.4.1
webpack@4.20.2
html-webpack-plugin@3.2.0

**Comment by jantimon** [comment]
Actually I would expect that to work.  
Could you please add a console.log to the constructor of the html-webpack-plugin?

**Comment by soulofmischief** [comment]
I imagine this bug is still present. I will try to look into it more soon. I've just been working on other things.

**Comment by jantimon** [comment]
thanks a lot @soulofmischief please take a look at the 4.x version: https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-beta.5

**Comment by soulofmischief** [comment]
@jantimon I did some more digging and it seems this is a general webpack issue. Exported variables defined at the top of my configuration's entry file are undefined after being imported in any other part of my webpack configuration.
