### ISSUE TITLE
generated html file is not minified

### ISSUE THREAD

**Issue by jamessouth** [jantimon/html-webpack-plugin#1081]
## Expected behaviour

```
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Webpack App</title></head><body><script src="main.a70592c0fcd7919c0ff6.js"></script></body></html>
```

## Current behaviour

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Webpack App</title>
  </head>
  <body>
  <script type="text/javascript" src="main.a70592c0fcd7919c0ff6.js"></script></body>
</html>
```

## Environment

```
Node.js v8.10.0
win32 10.0.17134
npm 6.4.0
webpack 4.17.2
html-webpack-plugin 3.2.0
```

### Config

```js
const path = require('path');
const webpack = require('webpack');
const HTMLWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  mode: 'production',
  entry: {
    main: './src/js/test.js',
  },
  output: {
    filename: '[name].[contenthash].js',
    chunkFilename: '[name].[contenthash].js',
    path: path.resolve(__dirname, 'test'),
  },
  plugins: [
    new HTMLWebpackPlugin(),
  ],
};
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.

[MY REPO](https://github.com/jamessouth/Project-12)

## Additional context

Whether I use my html5 template or not, specify the minify option true/false or not, use html-loader or not, import my html into my js entry or not, I can't get minified output. The test.js entry is a blank file.  My full config has the usual rules, plugins, etc, but even removing all that as above, no minified output.  I don't know what's going on.  When I run my full build, the only part that is minified is the 3 injected script tags, the rest of the generated html file is pretty, just like the source template html file.

**Comment by jantimon** [comment]
Can you please update to the html-webpack-plugin 4.x ?

**Comment by jamessouth** [comment]
Hello!  How do I do that?  It doesn't come up when I run ```npm outdated``` and 3.2.0 is given when I run ```npm search```.  I tried:

```bash
npm i -D --dry-run html-webpack-plugin@latest
```
and got:
```bash
html-webpack-plugin@3.2.0
```
Next I tried:
```bash
npm i -D --dry-run html-webpack-plugin@">=4.0.0"
```
and got an error, no matching version found
Then:
```bash
npm update html-webpack-plugin
npm update html-webpack-plugin@">=4.0.0"
```
and there was no effect, 3.2.0 still in my package.json

**Comment by jamessouth** [comment]
I use ```@next``` instead of ```@latest``` apparently??

**Comment by jamessouth** [comment]
ok I installed the ```@next``` version ```4.0.0-beta.2```, however, as someone opened [here](https://github.com/numical/script-ext-html-webpack-plugin/issues/51) (alpha.2) it doesn't work with ```script-ext-html-webpack-plugin``` anymore (```Cannot read property 'tap' of undefined```), BUT, when I disable ```script-ext-html-webpack-plugin```, it does indeed generate a minified html file.

**Comment by jantimon** [comment]
Cool 👍 hopefully the script-ext-html-webpack-plugin maintainers will upgrade to the html-webpack-plugin version soon

**Comment by atdiff** [comment]
@jantimon, any timeline on when html-webpack-plugin v4 will be released? Also seeing this problem with HTML not being minified automatically.

**Comment by jantimon** [comment]
Create React App is already using the current implementation.  
I am waiting for bug reports to come in for the beta so that the release is as smooth as possible :)

Right now we noticed one bug in the caching #1072
