### ISSUE TITLE
Entry point undefined causes build failure

### ISSUE THREAD

**Issue by HassanNemir** [jantimon/html-webpack-plugin#1082]
## Expected behaviour
Build Success

## Current behaviour
Build failure with the message:
```
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       1 module
Entrypoint undefined = index.html
```
## Environment

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"

Node.js v8.10.0
linux 4.15.0-36-generic

npm --version
6.4.1

npm ls webpack

└── webpack@4.20.0 

npm ls html-webpack-plugin

└── html-webpack-plugin@3.2.0 
```

### Config

```js
new HtmlWebpackPlugin({
    inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
    entryPoint: 'app/index.html',
  }),
```

## Relevant Links
I have tried all the solutions here including installing v3.0.2 
[#895](https://github.com/jantimon/html-webpack-plugin/issues/895)
and unfortunately it's not just a log message [#895 (comment)](https://github.com/jantimon/html-webpack-plugin/issues/895#issuecomment-379006202)

**Comment by jantimon** [comment]
undefined is only the name of the entrypoint - it does not cause any errors
