### ISSUE TITLE
Multiple Entry, Multiple Html

### ISSUE THREAD

**Issue by nschubach** [jantimon/html-webpack-plugin#1083]
## Expected behaviour

Adding multiple plugins should general multiple files.

## Current behaviour

Plugins are only generating one file in the root and overwriting it(?)

## Environment
```
Node.js@v8.10.0
OS@darwin 16.7.0
npm@6.4.0
webpack@4.12.0
html-webpack-plugin@3.2.0  (Also tried @next)
```
### Config
```
context: path.resolve(__dirname, 'root'),
entry: {
	'index': './index.html.js',
	'page1/index': './page1/index.html.js',
	'page2/index': './page2/index.html.js'
}
plugins: [
	new HtmlWebpackPlugin({ inject: 'body', chunks: [ 'index' ], fileName: '/index.html' }),
	new HtmlWebpackPlugin({ inject: 'body', chunks: [ 'page1/index' ], fileName: '/page1/index.html' }),
	new HtmlWebpackPlugin({ inject: 'body', chunks: [ 'page2/index' ], fileName: '/page2/index.html' })
],
output: {
	filename: join('assets', 'scripts', '[name].js'),
	path: path.resolve(__dirname, 'dist'),
	chunkFilename: join('assets', 'scripts', '[name].[chunkhash].js'),
	publicPath: '/'
}
```
Where:
```
root/index.html.js
root/page1/index.html.js
root/page2/index.html.js
```
Are my three files that I want to generate an html page for and they have logic to append their content to the body.

## Additional context

~~Now, I'm programmatically generating these configuration options by getting a list of the files in the folders and creating the plugins like so: (I don't think this is the problem?)~~ Edit: not the problem.

Edit: Removed irrelevant code block

~~I wanted to do this because I wanted to pre-render the React using prerender-loader so when I build the project it will start off with a basic static file that shows the initial state of things, but that's even failing for me, so I stripped it down the basics and just wanted a simple htmlWebpackPlugin drop.~~ Edit: not the problem/not relevant

From everything I'm reading, it appears as though I should be getting multiple HTML files output in the format of:
```
dist/index.html
dist/page1/index.html
dist/page2/index.html
```
But what I'm seeing is that the page2 content is being used for the root `index.html` as if it's just writing all the files to the same 'dist/index.html'.

The output of Webpack for the plugin is:
```
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/html-webpack-plugin/lib/loader.js!../node_modules/html-webpack-plugin/default_index.ejs] 376 bytes {0} [built]
    [../node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [../node_modules/webpack/buildin/global.js] 509 bytes {0} [built]
    [../node_modules/webpack/buildin/module.js] 519 bytes {0} [built]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/html-webpack-plugin/lib/loader.js!../node_modules/html-webpack-plugin/default_index.ejs] 376 bytes {0} [built]
    [../node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [../node_modules/webpack/buildin/global.js] 509 bytes {0} [built]
    [../node_modules/webpack/buildin/module.js] 519 bytes {0} [built]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/html-webpack-plugin/lib/loader.js!../node_modules/html-webpack-plugin/default_index.ejs] 376 bytes {0} [built]
    [../node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [../node_modules/webpack/buildin/global.js] 509 bytes {0} [built]
    [../node_modules/webpack/buildin/module.js] 519 bytes {0} [built]
```
Which makes me think it's failing because I assume that the `Child html-webpack-plugin for "index.html":` should each be the different files I'm trying to create and the "undefined = index.html" should probably have more to it?

**Comment by nschubach** [comment]
Just posting to confirm that hardcoding the entries and plugins I need instead of using the glob package to scan the directories for those specific files does not change any of the outcomes. so that portion is invalid to the issue.

**Comment by nschubach** [comment]
Now I feel so dumb... 

`filename` vs. `fileName`

I'll close this issue.

**Comment by jantimon** [comment]
Thanks for closing 👍
Maybe we should lint the incoming options and add better error messages.
