### ISSUE TITLE
Lock bot generates a lot of noise when watching the repository

### ISSUE THREAD

**Issue by edmorley** [jantimon/html-webpack-plugin#1085]
Hi!

Currently the lock bot is configured to lock both closed issues and pull requests after 30 days of inactivity, and to leave a comment when it does so:
https://github.com/jantimon/html-webpack-plugin/blob/65879ebe5061d821c9cbc9639915d855a612851b/.github/lock.yml

Example of locking + comment:
https://github.com/jantimon/html-webpack-plugin/issues/1039#issuecomment-431575466

This generates a lot of GitHub notification emails if watching the repository - enough that I've almost unwatched the repo on several occasions.

@jantimon, now that lock bot supports setting a label at time of locking - would you be open to using an informative label instead of a comment? (eg `locked-for-inactivity` or similar). The supported options are here:
https://github.com/dessant/lock-threads#configuration

Also, could PRs perhaps be excluded from locking? I would imagine it's much more common for unrelated comments to be added to old issues, than to old PRs - and for PRs it's more likely that there may be valid implementation questions at a later date.

Many thanks :-)

**Comment by jantimon** [comment]
Sure let’s change that.  
The idea of locking closed issues and pull requests is that new issues are created if regressions occur
