### ISSUE TITLE
How can I prevent the head tag from wrapping the style tags?

### ISSUE THREAD

**Issue by webdeveloperpr** [jantimon/html-webpack-plugin#1087]
**Is your feature request related to a problem? Please describe.**
I am trying to create some ad creative templates and I need to generate html, css and js scripts. Everything works fine. The only problem is that there is a head tag wrapping the style tag. Is there a way to get rid of it?

**Describe the solution you'd like**
I would like to get rid of the head tags any suggestions?

**Comment by jantimon** [comment]
You would have to disable the `inject` mode and write a custom template

**Comment by webdeveloperpr** [comment]
Ok thx!

**Comment by webdeveloperpr** [comment]
It was somewhat confusing but I got it working by creating an ejs template! I'm leaving this comment here just in case someone else needs it.

```html
<div class="ad-template">
  <!-- css Files -->
  <style>
    <% if (htmlWebpackPlugin.files.css) { %>
      <% htmlWebpackPlugin.files.css.forEach(function(css){ %>
        <%= compilation.assets[css.substr(htmlWebpackPlugin.files.publicPath.length)].source() %>
      <% }); %>
    <% } %>
  </style>

  <!-- html files -->
  <script>
    <% if (htmlWebpackPlugin.files.html) { %>
      <% htmlWebpackPlugin.files.html.forEach(function(html){ %>
        <%= compilation.assets[html.substr(htmlWebpackPlugin.files.publicPath.length)].source() %>
      <% }); %>
    <% } %>
  </script>

  <!-- js files -->
  <script>
    <% if (htmlWebpackPlugin.files.js) { %>
      <% htmlWebpackPlugin.files.js.forEach(function(js){ %>
        <%= compilation.assets[js.substr(htmlWebpackPlugin.files.publicPath.length)].source() %>
      <% }); %>
    <% } %>
  </script>
</div>

```

**Comment by matt-snider** [comment]
It would be nice if all available properties and their values were documented. I skimmed through the code, expecting the properties in the return value of [`templateParametersGenerator`](https://github.com/jantimon/html-webpack-plugin/blob/298635f4b3fb19fe920b1e0b982b61af0f31239d/index.js#L926) to be available, but that doesn't seem to work
```js
  return {
    compilation: compilation,
    webpackConfig: compilation.options,
    htmlWebpackPlugin: {
      tags: assetTags,
      files: assets,
      options: options
    }
  }
```

**Comment by matt-snider** [comment]
Sorry that was a bit careless -- I was on an older version before `htmlWebpackPlugin.tags` was available 

I also found exactly what I was looking for in case it helps someone else: [interface HtmlWebpackPluginTemplateParameter](https://github.com/jantimon/html-webpack-plugin/blob/298635f4b3fb19fe920b1e0b982b61af0f31239d/typings.d.ts#L122)

This is only available starting v4 which is beta at the moment.
