### ISSUE TITLE
[v4-beta.2] Alternative to htmlPluginData.assets.chunks?

### ISSUE THREAD

**Issue by jeffposnick** [jantimon/html-webpack-plugin#1092]
I'm working on getting `preload-webpack-plugin` updated to work with `html-webpack-plugin` v4. The current WIP code is at https://github.com/GoogleChromeLabs/preload-webpack-plugin/tree/html-plugin-updates

One issue that I'm running into, which is alluded to in https://github.com/jantimon/html-webpack-plugin/pull/953#issue-189369685, is that previous versions of `html-webpack-plugin` would pass in plugin data to `htmlWebpackPluginAfterHtmlProcessing` that included an `assets` as a property, and in that `assets` object, `chunks`.

The release notes say:

> The assets object which is used for the template parameters and inside hooks was changed. The chunks property was removed and the js and css property was converted from a string into an object `{ entryName: string, path: string}`

However, from what I'm seeing, after moving from `htmlWebpackPluginAfterHtmlProcessing` to `beforeEmit`, the plugin data that's passed to my callback doesn't have `assets` set at all. (I'm being passed a plugin data object with 3 properties: `html`, `plugin`, and `outputName`.)

How can I get the equivalent of `pluginData.assets.chunks` in v4?

Or, more to the point, why isn't `assets` being set? Could it be related to the issues I'm having tapping into the right hook (see https://github.com/jantimon/html-webpack-plugin/issues/1091)?

(See https://github.com/GoogleChromeLabs/preload-webpack-plugin/blob/c57b0b3521ca31091e0a77784bdb56a8ae8ba98d/src/index.js#L156-L159 for the context of where I'm trying to get that data.)

**Comment by jeffposnick** [comment]
Here's how that info was being used when working with `html-webpack-plugin` v3:

https://github.com/GoogleChromeLabs/preload-webpack-plugin/blob/798fc677f42e9ed2c1176065f733efa6b7fdc735/index.js#L172-L190

The main sticking point here is that the `preload-webpack-plugin` allowed white/blacklists to operate on the basis of `chunk` names, and in order to apply that (especially in a model where there might be multiple `html-webpack-plugin` instances for a given compilation), we needed to know which chunk names (not asset names) were associated with a given `html-webpack-plugin` instance.

**Comment by jantimon** [comment]
For performance reasons we switched from the `chunks` to `entries` - which is very similar but a different webpack api.

The idea of restructuring the hooks is to provide only one truth but I understand your need.  
How could a api for the `alterAssetTags` look like to suite your needs?

Should we pass through the chunks option?

**Comment by jeffposnick** [comment]
Passing through `chunks` would be enough to offer the same functionality that we previously offered, yes.

If the performance difference is significant, then perhaps there's a way to only generate that info if someone taps into a specific event, like `alterAssetTagsWithChunks` or something like that?

**Comment by jantimon** [comment]
The performance issue was to request `webpack stats` which included the chunks information.

**Comment by jeffposnick** [comment]
Gotcha.

Well, if it's is something that you're not going to support anymore in `html-webpack-plugin` v4, then we can deprecate the code that was using it as part of the corresponding `preload-webpack-plugin` release.

**Comment by kouhin** [comment]
This is my solution. 
I put the old code of html-webpack-plugin into `templateParameters`.
And it looks like this (also add supports for custom parameters)

```js
function createTemplateParameters(customParams) {
  return function templateParametersGenerator(
    compilation,
    inAssets,
    assetTags,
    options
  ) {
    const assets = {
      ...inAssets,
      chunks: {}
    };
    const chunks = compilation.getStats().toJson().chunks;
    function appendHash (url, hash) {
      if (!url) {
        return url;
      }
      return url + (url.indexOf('?') === -1 ? '?' : '&') + hash;
    }
    for (let i = 0; i < chunks.length; i++) {
      const chunk = chunks[i];
      const chunkName = chunk.names[0];
      assets.chunks[chunkName] = {};
      // Prepend the public path to all chunk files
      let chunkFiles = [].concat(chunk.files).map(chunkFile => assets.publicPath + chunkFile);

      // Append a hash for cache busting
      if (options.hash) {
        chunkFiles = chunkFiles.map(chunkFile => appendHash(chunkFile, compilationHash));
      }
      // Webpack outputs an array for each chunk when using sourcemaps
      // or when one chunk hosts js and css simultaneously
      const js = chunkFiles.find(chunkFile => /.js($|\?)/.test(chunkFile));
      if (js) {
        assets.chunks[chunkName].size = chunk.size;
        assets.chunks[chunkName].entry = js;
        assets.chunks[chunkName].hash = chunk.hash;
        assets.js.push(js);
      }
      // Gather all css files
      const css = chunkFiles.filter(chunkFile => /.css($|\?)/.test(chunkFile));
      assets.chunks[chunkName].css = css;
    }
    const xhtml = options.xhtml;
    assetTags.headTags.toString = function() {
      return this.map(assetTagObject =>
        htmlTagObjectToString(assetTagObject, xhtml)
      ).join("");
    };
    assetTags.bodyTags.toString = function() {
      return this.map(assetTagObject =>
        htmlTagObjectToString(assetTagObject, xhtml)
      ).join("");
    };
    return Object.assign(
      {},
      {
        compilation: compilation,
        webpackConfig: compilation.options,
        htmlWebpackPlugin: {
          tags: assetTags,
          files: assets,
          options: options
        },
      },
      customParams || {}
    );
  };
}
```

And then, use this function with HtmlWebpackPlugin

```
new HtmlWebpackPlugin({
      minify: false,
      inject: false,
     "build/mytemplate.html"
      template: "templates/mytemplate.html",
      templateParameters: createTemplateParameters({ process: process })
    })
```
