### ISSUE TITLE
Feature Request: Add option to only generate script tags no boilerplate!

### ISSUE THREAD

**Issue by techsin** [jantimon/html-webpack-plugin#1105]
Problem: I've is that I don't want to generate the whole index.html, I want to genearte ONLY script tags with hashed filenames. Then I can include them in my files as I NEED them.

an option that prevents generation of HTML, BODY, HEAD tags. I tried providing empty html file as a template it still generate those tags.

So why?
I have an multiple apps in a website. So there isn't ONE index.js. There are multiple entry points. I have multiple views which include different js files. But I want to use hashed filenames in script src to utilize cache busting. But to do that I've to manually update filename in views. I'm trying to html webpack plugin to generate the html script tags Automatically so in my views templating system I can simply include the files that would contain script tag with correct src url. Meaning it'd have hash in the file name.

**Comment by edmorley** [comment]
> I have an multiple apps in a website. So there isn't ONE index.js. There are multiple entry points.

When using multiple entrypoints, you can use multiple instances of `html-webpack-plugin`, and pass the `chunks` option to specify the relevant entrypoint for each.

If the issue is instead that you want to include the tags in some other markup/view (eg Django template), then it seems like `html-webpack-plugin` is actually the wrong tool to use - and instead perhaps use the webpack file manifest to generate the necessary tags?

**Comment by techsin** [comment]
It's neither.
I don't need help generating multiple files.
I don't need help generating help with templating engines.

Issue is i want to generate html file like this:

`<script src='company.com/js/filename.h3939.js'> </script>`

Not

Issue is i want to generate html file like this:

`<script src='company.com/js/filename.h3939.js'> </script>`

Not

```
<html>
<head>
<script src='company.com/js/filename.h3939.js'> </script>
</head>
<body>
</body>
</html>
```

**Comment by jantimon** [comment]
set inject to false

**Comment by techsin** [comment]
it didnt generate anything html file is empty?

**Comment by techsin** [comment]
got it solved. using loop and variables exposed by html webpack thanks.
