### ISSUE TITLE
Throw an error if chunk not found

### ISSUE THREAD

**Issue by BenAttenborough** [jantimon/html-webpack-plugin#1106]
At the moment providing a non-existent chunk name fails silently.

```
 new HtmlWebpackPlugin({
            inject: true,
            chunks: ["wrongName"],
            filename: "homepage.html",
            template: "src/html-templates/default.html"
}),
```

**Describe the solution you'd like**
If the chunk name doesn't exist an error should appear in the console output. Possibly consider the build failing if the chunk name is wrong so the dev has to fix it.

**Comment by jantimon** [comment]
The current code is quite simple (to stay as fast as possible):

https://github.com/jantimon/html-webpack-plugin/blob/f40aeae312af73c6c5263cd99e81069f41d3b699/lib/chunksorter.js#L18-L35

**Comment by BenAttenborough** [comment]
Okay, fair enough!
