### ISSUE TITLE
Missings `typings` property in `package.json` in beta

### ISSUE THREAD

**Issue by SimonSchick** [jantimon/html-webpack-plugin#1108]
## Expected behaviour

Types load correctly.

## Current behaviour

Types do not load.

## Environment

Latest TS version on node 10.12.

### Config

```ts
import HTMLPlugin from 'html-webpack-plugin';
```

## Relevant Links

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by SimonSchick** [comment]
Actually, the typings you are shipping seem to be incorrect in general as you are not exporting the class instance correctly.

**Comment by SimonSchick** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/html-webpack-plugin/index.d.ts

**Comment by jantimon** [comment]
Could you please be a little bit more concrete?

**Comment by hornta** [comment]
Or we can rename typings.d.ts to index.d.ts according to https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by wingrunr21** [comment]
Adding a `types` property is advised even if it is named `index.d.ts`

**Comment by jantimon** [comment]
But we don’t export the typings - we use the typescript salsa feature jsdocs as typings. 

The typings.d.ts is just an internal helper for the html-webpack-plugin.

However the typescript team is working on generating definition files from salsa files.

Once that works we will provide a typing file which we will link from the package.json to the type file

**Comment by wingrunr21** [comment]
@jantimon does that mean you aren't interested in merging #1132? I opened that precisely so that this project would export typings that are usable in TS based webpack configs.
