### ISSUE TITLE
The HtmlWebpackPlugin.getHooks is not defined

### ISSUE THREAD

**Issue by yibingxiong** [jantimon/html-webpack-plugin#1110]
## Expected behaviour

I want to use `HtmlWebpackPlugin.getHooks` to use hook function to do something. But I found `HtmlWebpackPlugin.getHooks` is not defined.  Not same with the docs. The version is 3.2.0. 

## Current behaviour

`HtmlWebpackPlugin.getHooks` is not defined.  Not same with the docs.

## Environment

- node v10.8.0
- webpack v4.25.1
- html-webpack-plugin v3.2.0
- npm v6.2.0

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
var path = require('path');
const MyExampleWebpackPlugin = require('./myplugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
  mode: 'development',
  entry: './test_plugin/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  plugins: [
    new HtmlWebpackPlugin(),
    new MyExampleWebpackPlugin()
  ]
};
```

Copy your template file if it is part of this issue:

no template file, use default.

## Relevant Links

This is for test, no public links

## Additional contex

```js
const HtmlWebpackPlugin = require('html-webpack-plugin');

class MyExampleWebpackPlugin {
    apply(compiler) {

        compiler.hooks.compilation.tap('MyPlugin', (compilation) => {
          console.log(typeof HtmlWebpackPlugin.getHooks); // outputs undefined, expected 'function'
        })
    }
}

module.exports = MyExampleWebpackPlugin;
```

**Comment by jantimon** [comment]
`getHooks` requires html-webpack-plugin 4

**Comment by yibingxiong** [comment]
Thanks. I know.

**Comment by annayo** [comment]
I'm having the same issue. Using:

- node v10.8.0
- webpack v4.26.1
- html-webpack-plugin v3.2.0
- npm v6.2.0

@yibingxiong were you able to resolve it?

**Comment by Dalqin** [comment]
> 
> 
> `getHooks` requires html-webpack-plugin 4

What do you mean? There highest version of html-webpack-plugin is 3.2.0.

**Comment by jantimon** [comment]
https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-beta.4

**Comment by Dalqin** [comment]
Oh it's a beta! Thanks for clarifying.

**Comment by ericmorand** [comment]
Why is the documentation written for the v4 version while the npm package is still set to 3.2.0?

**Comment by dtweedle** [comment]
> Why is the documentation written for the v4 version while the npm package is still set to 3.2.0?

This x1000

**Comment by jole78** [comment]
I would agree it's a little confusing that this requires a beta version to work but anyway. Here's an example of the difference if you want it for v3 and compare it to v4.
https://github.com/facebook/create-react-app/pull/5031/files#diff-3b55301108483c3bb5289672dd9caa59L26
