### ISSUE TITLE
Option links in the README.md are pointing nowhere

### ISSUE THREAD

**Issue by lazarljubenovic** [jantimon/html-webpack-plugin#1111]
The README.md has a neat table listing available options, with the first column being links to... nowhere? I also didn't see that each option even has a relevant "longer" explanation below -- although some do, so I wasn't sure what the intention was.

I wasn't sure how to improve it with a PR so I thought that I should ask here first what the intention was.

(I know that I'm supposed to use the template, but given that this is a documentation issue I didn't think any of the fields from it were relevant. Sorry if I should've still followed it.)

**Comment by jantimon** [comment]
hey @lazarljubenovic 

I guess those links where introduced to align closer with the general webpack plugin readme layout.   
You are more than welcome to provide ideas to improve the docs! :)
