### ISSUE TITLE
Don't overwrite default templateParameters when passing object

### ISSUE THREAD

**Issue by robwierzbowski** [jantimon/html-webpack-plugin#1117]
## Expected behaviour

`templateParameters` added as an object are merged with the the default template parameters.

## Current behaviour

`templateParameters` added as as an object prevent loading of the default template parameters. See this code:  https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L365-L379. If we use a function to set the params we are able to merge our custom params with the default params.

## Environment

npm --version
npm ls webpack
npm ls html-webpack-plugin

Node.js v11.2.0
darwin 18.2.0
6.4.1

└── webpack@4.14.0 

└── html-webpack-plugin@4.0.0-beta.2 

### Config

```js
module.exports = {
  entry: 'app.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },

  plugins: [
    new HtmlWebpackPlugin({
      myParam: 'myParam',
    }),
  ]
}
```

## Additional context

Lots of HTMLWebpackPlugin 3.x.x documentation uses the default params. It seems they've changed a little in HTMLWebpackPlugin 4.

I don't know if this is intentional or not. If it's a Do Not Fix, I'd be happy to add more complete documentation to `templateParameters` describing the function args and the behavior.

**Comment by jantimon** [comment]
You are right the documentation could be improved for that feature.

You can find the function here:

https://github.com/jantimon/html-webpack-plugin/blob/298635f4b3fb19fe920b1e0b982b61af0f31239d/index.js#L906-L943

This will convert your options like

```
new HtmlWebpackPlugin({
      myParam: 'myParam',
    }),
```

To:
```
htmlWebpackPlugin.options.myParam
```

**Comment by uraz** [comment]
Is it possilbe to extend `templateParameters` like this? 
```
{ 
  compilation: compilation, 
  webpackConfig: compilation.options, 
  htmlWebpackPlugin: { ... },
  customProperty: value
}
```

**Comment by jantimon** [comment]
Yes you can provide your own function which provides such a structure by setting a `templateParameters` callback.
