### ISSUE TITLE
EJS include throws errors

### ISSUE THREAD

**Issue by ZebraFlesh** [jantimon/html-webpack-plugin#1118]
## Expected behaviour

ejs `include` directives are correctly processed and content is included in the parent template

## Current behaviour

Errors occur:
```
   ERROR in Template execution failed: ReferenceError: include is not defined

    ERROR in   ReferenceError: include is not defined

      - index.ejs:767
        C:/Users/NOPE/myproject/demo/src/index.ejs:767:2

      - index.ejs:770 ./node_modules/html-webpack-plugin/lib/loader.js!./demo/src/index.ejs.module.exports
        C:/Users/NOPE/myproject/demo/src/index.ejs:770:3

      - index.js:284 Promise.resolve.then
        [myproject]/[html-webpack-plugin]/index.js:284:18

      - next_tick.js:68 process._tickCallback
        internal/process/next_tick.js:68:7
```

## Environment

Node.js v10.13.0
win32 10.0.17134
yarn 1.12.1
webpack 4.26.1
html-webpack-plugin: 3.2.0 (also tried 4.0.0-beta.4, same result)

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  entries: {
    demo: 'DemoMount.js'
  },
  output: {
    path: 'dist',
    filename: 'js/[name].[hash].js'
  },
  module: {
    rules: [
      ... babel7, scss ...
    ]
  }
  plugins: [
    new HtmlWebpackPlugin({
        template: path.join(settings.paths.src.js, 'index.ejs')
    }),
    ...
  ]
}
```

Copy your template file if it is part of this issue:

*index.ejs*
```ejs
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">
    </head>
    <body>
        <% include('test') %>
        <div id="root"></div>
    </body>
</html>
```

*test.ejs*
```ejs
<div id="foo">foo</div>
```

## Additional context

As you can see from the templates, a very simple ejs `include` blows things up.

**Comment by jantimon** [comment]
Unfortunately the html-webpack-plugin is not supporting all ejs features.  
Under the hood it is using https://lodash.com/docs/4.17.10#template

But you can use any webpack loader you like.  
So you would have to do a quick research for a loader that fits your needs.

Maybe the [ejs-loader](https://www.npmjs.com/package/ejs-loader) fits your needs.

```
new HtmlWebpackPlugin({
        template: '!!ejs-loader!' + path.join(settings.paths.src.js, 'index.ejs')
    }),
```

**Comment by appsparkler** [comment]
This link was quite useful for examples : https://github.com/jantimon/html-webpack-plugin/tree/master/examples
