### ISSUE TITLE
Also add hash to head link tags

### ISSUE THREAD

**Issue by aesfer** [jantimon/html-webpack-plugin#1119]
When using option `hash: true`, the hash is only added to the injected `<script>` tags in the body but it is not added to the respective `<link>` tags in the head.

For instance:
```
        <!DOCTYPE html>
        <html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <link href="static/app.js" rel="preload" as="script">
            </head>

            <body>
                <script type="text/javascript" src="static/app.js?7f6fe83096222ee0df3e"></script>
            </body>
        </html>
```

This results in chrome giving the following warning:

> The resource http://localhost/static/app.js was preloaded using link preload but not used within a few seconds from the window's load event.

Shouldn't the hash be added to all tags pointing to the same resources so they match the same version in case of browser caching?

Cheers

**Comment by jantimon** [comment]
Actually it should also work for css files: 

https://github.com/jantimon/html-webpack-plugin/blob/298635f4b3fb19fe920b1e0b982b61af0f31239d/index.js#L590-L622
