### ISSUE TITLE
HTML elements in template are being modified unnecessarily with 4.0.0-beta.4

### ISSUE THREAD

**Issue by LaniMoo** [jantimon/html-webpack-plugin#1121]
I've noticed after upgrading to 4.0.0-beta.4 that many HTML elements within the template (some of which have nothing to do with the plugin's injection) have been changed. A few things I noticed:

1. Mime types are no longer included for injected elements.
2. Mime types are removed from existing elements.
3. All elements and their attributes are changed to lower case.

I'm also using .NET .aspx pages as the template, which now fail to load since this last update. Some elements are specific to the .NET Framework so it is absolutely crucial that they do not get modified at all. 

### Example:

Before (using 4.0.0-alpha.2):
**Scenario 1:** `<link type="text/css" rel="stylesheet" href="styles.css">`
**Scenario 2:** `<script type="text/javascript">console.log("Hello, world!")</script>`
**Scenario 3:** `<asp:ContentPlaceHolder ID="head" runat="server" />`

After (using 4.0.0-beta.4):
**Scenario 1:** `<link rel="stylesheet" href="styles.css">`
**Scenario 2:** `<script>console.log("Hello, world!")</script>`
**Scenario 3:** `<asp:contentplaceholder id="head" runat="server" />`

**Comment by jantimon** [comment]
We had many discussions about that topic.

According to: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script 

> Omitted or a JavaScript MIME type: For HTML5-compliant browsers this indicates the script is JavaScript. HTML5 specification urges authors to omit the attribute rather than provide a redundant MIME type. In earlier browsers, this identified the scripting language of the embedded or imported (via the src attribute) code. JavaScript MIME types are listed in the specification.

You can easily add the type or other attributes with a custom plugin by using the `alterTags` hook (~15 lines of code).

**Comment by edmorley** [comment]
> 3. All elements and their attributes are changed to lower case.

This can be prevented by disabling minification, or else leaving it enabled but with `caseSensitive: true`. See:
https://github.com/jantimon/html-webpack-plugin#minification
https://github.com/kangax/html-minifier#options-quick-reference
