### ISSUE TITLE
Plugin generates HTML with all chunks included

### ISSUE THREAD

**Issue by AlexPravdin** [jantimon/html-webpack-plugin#1125]
I have an application with few 2 MB JS code bundles, each for every entry point. I'm splitting my bundles with the webpack code split feature to move common code to a chunk or chunks. Next I want to add all chunks required by PARTICULAR entry point to the corresponding HTML file. I plan to use the HtmlWebpackPlugin.

## Expected behaviour

Plugin generates HTML file including only the chunks required by the particular entry point.

## Current behaviour

HTML file include ALL the chunks which makes code splitting totally useless. Why do I need to split my bundle if all of it will be loaded at once in any way? For rexample, I dont need to download Dashboard chunk if user not authenticated yet.

**Comment by jantimon** [comment]
It is hard to guess wether a chunk is a vendor chunk or a application chunk.

You can easily specify which chunks should be injected by specifying the `chunks` option.

**Comment by AlexPravdin** [comment]
Could you mention this issue in the docs please?

**Comment by AlexPravdin** [comment]
Also, could you please add an option to define a chunk file name mask? For example, defaut chnk splitting creates the following list of chunks:

```
auth.js
dashboard.js
vendors~auth.js
vendors~auth~dashboard.js
vendors~dashboard.js
```

It would be very nice to have ability to add all chunks with the mask `*auth*` for `auth` entry point and `*dashboard*` for the `dashboard` entry point.
