### ISSUE TITLE
Make it works with .mjs files

### ISSUE THREAD

**Issue by levvsha** [jantimon/html-webpack-plugin#1126]
Great approach with compiling of mjs files for modern browsers is described in [this article](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/). I faced with a problem when I specify `output.filename` in a webpack configuration file as a file with `.mjs` extension:
```
output: {
  filename: 'main.mjs',
  path: path.resolve(__dirname, 'public'),
},
```
Webpack is sucessfully compile all files but html-webpack-plugin does not append the generated files to the template (`htmlWebpackPlugin.files.js` is an empty array). It would be great to make it works with `.mjs` output files by default or with some flag in the configuration.
Expected result: the string `<script type="module" src="main.mjs"></script>` is appended in the template.

**Comment by jantimon** [comment]
Sure - could you please open a pull request?

**Comment by jantimon** [comment]
@levvsha any updates on this issue?

**Comment by artemirq** [comment]
@jantimon Should be closed in #1207

**Comment by artemirq** [comment]
@levvsha I don't sure that closing this issue now is good idea, because PR is not merged yet

**Comment by levvsha** [comment]
@artemirq Reopened.

**Comment by jantimon** [comment]
Can you please update https://github.com/jantimon/html-webpack-plugin/pull/1207 so we can merge it?

**Comment by artemirq** [comment]
@jantimon Sure

**Comment by jantimon** [comment]
Thanks al lot @artemirq - do you think we should also add unit tests?

**Comment by artemirq** [comment]
@jantimon Thanks. I don't sure
