### ISSUE TITLE
'publicPath' question about html-webpack-plugin and mini-css-extract-plugin

### ISSUE THREAD

**Issue by KokoTa** [jantimon/html-webpack-plugin#1127]
I want set a 'styles' and 'js' directory to put my css/js files, but when i set publiPath, it can't work. Please see this [Link](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/222#issuecomment-415864347)

I don't know what problem is...

**Comment by jantimon** [comment]
Sorry that won't work as the `publicPath` will also apply for the html file.

**Comment by KokoTa** [comment]
If I want set CDN just like `//js.cdn.com` and '//css.cdn.com'，but html will lik：

```js
```

**Comment by KokoTa** [comment]
If i want use CDN like:

```html
<link href="//css.cdn.com/main.css">
<script src="//js.cdn.com/main.js">
```

how to set it ?

I set output.publicPath = '//js.cdn.com' and MiniCssExtractPlugin fiename = '//css.cdn.com/main.css', the result is:

```html
<link href="//js.cdn.com///css.cdn.com/main.css">
<script src="//js.cdn.com/main.js">
```

Thank you for your watching> <
