### ISSUE TITLE
Replace existing tag's path if output path is the same

### ISSUE THREAD

**Issue by notlmn** [jantimon/html-webpack-plugin#1128]
### Is your feature request related to a problem? Please describe.
The plugin appends a new script tag to the end of `<body>` tag. This happens even if you already have a reference to the script file that will be injected.

``` html
<body>
	<script src="/scripts/main.js"></script>
</body>
```

The URL here is generated somehow by webpack, but after the injection it looks like this:

``` html
<body>
	<script src="/scripts/main.js"></script>
	<script src="/scripts/main.a53fdb8ecda1f2bba044.js"></script>
</body>
```

### Describe the solution you'd like
The existing `<script>` tag's `src` attribute value to be replaced with the new URL instead of adding an entire new `<script>` tag even if the end URL is the same in both the tags (excluding hash part), or add an option to be able to do the same.

This would **allow the original source code to stay unmodified**, not be specific to Webpack or some specific plugin that generates HTML content. So the code works even if it is not bundled/passed through Webpack.

### Describe alternatives you've considered
As the JS only contain plain ES6 imports, I considered to add `type="module"` to the original script tag, and let the plugin add the bundled script tag.

The above alternative obviously works great, but I still think that there should be a more precise way to be able to control where and how the resulting `<script>` tag ends up (excluding writing your own plugin using hooks though).

**Comment by jantimon** [comment]
I might be wrong but I don't see a great demand in this feature and some additional performance costs for parsing the html.

What about an "inline" plugin?

```
plugins: [
  new HtmlWebpackPlugin(),
  { apply: (compiler) => compiler.hooks.compilation.tap('ScriptReplacer', (compilation) => HtmlWebpackPlugin.getHooks(compilation).beforeEmit.tapAsync('ScriptReplacer',(data, cb) => {
    // Manipulate the content
    data.html += 'The Magic Footer'
    // Tell webpack to move on
    cb(null, data)
  })}
]
```

**Comment by notlmn** [comment]
> I don't see a great demand in this feature

Yeah, I might be the only person using Webpack asking for this feature.

> some additional performance costs for parsing the html.

Yes, but I think you can still find and replace a `<script>` tag using regexp, without having to parse all of the HTML.

I didn't look into the internals of this plugin before opening this issue and thought that it was already parsing HTML, but I think this can be fairly easily implemented using regex.

I'll try using custom plugin + hooks method to do this, thanks!

**Comment by jantimon** [comment]
Cool - please let me know if it worked :)

**Comment by notlmn** [comment]
While trying to do this I realized that it is way more complex than replacing text using regex, you should know how the Webpack entry assets path maps to source of script attribute.

The user (me in this case 😅) would rather let the plugin add the script tag and be done with it, instead of adding all the complexity and configuration that is required for making this work.

@jantimon Thanks for the pointers anyway, at least I'm getting better at Webpack internals 🤷‍♂️.
