### ISSUE TITLE
Add ability to output JS / non-html files

### ISSUE THREAD

**Issue by zhishaofei3** [jantimon/html-webpack-plugin#1131]
**Is your feature request related to a problem? Please describe.**

hello!

My project is not a html page, it's a javascript SDK file.
so I don't need build a html page.

I want output 3 files: sdk-load.js main.[hash].js css.[hash].js

sdk-load.js is my custom js file, is main.[hash].js css.[hash].js loader,
to dynamic loading main.[hash].js css.[hash].js

I need to be able to calculate the name every time, and update file.

sdk-load.js such as:
````javascript
var script = document.createElement('script')
script.src = 'http://xxx.com/main.[hash].js'
document.body.appendChild(node);
````

but sdk-load.js is not html file..
thank you

**Comment by jantimon** [comment]
That’s no problem just disable the inject option

**Comment by zhishaofei3** [comment]
webpack.prod.conf.js:
````
new HtmlWebpackPlugin({
      filename: 'file-load.js',
      template: resolve('src/templates/file-load.ejs'),
      inject: false,
      libName: 'base2.min',
      chunks: ['manifest', 'dby']
    }),
````

file-load.ejs:
````javascript
var loadcss = '##LOAD_CSS##';
var loadjs = '##LOAD_JS##';
var logpath = '##LOG_PATH##';

<% for (var index in htmlWebpackPlugin.files.js) { %>
var loadjs = "<%= htmlWebpackPlugin.files.js[index] %>";
<% } %>
````

**Comment by dgeibi** [comment]
use javascript template:

```js
// src/template.js

module.exports = templateParams => {
  return `var loadjs = '${templateParams.htmlWebpackPlugin.files.js[0]}';`;
};
```


```js
// webpack.config.js
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
    plugins: [
        new HtmlWebpackPlugin({
            template: './src/template.js',
            filename: 'file-load.js',
            inject: false,
        })
    ],
    output: {
        filename: '[hash].js'
    }
}
```

**Comment by zhishaofei3** [comment]
> use javascript template:
> 
> ```js
> // src/template.js
> 
> module.exports = templateParams => {
>   return `var loadjs = '${templateParams.htmlWebpackPlugin.files.js[0]}';`;
> };
> ```
> 
> ```js
> // webpack.config.js
> const HtmlWebpackPlugin = require('html-webpack-plugin')
> 
> module.exports = {
>     plugins: [
>         new HtmlWebpackPlugin({
>             template: './src/template.js',
>             filename: 'file-load.js',
>             inject: false,
>         })
>     ],
>     output: {
>         filename: '[hash].js'
>     }
> }
> ```

ERROR in Error: The loader "/Users/xxx/WebstormProjects/vue-webpack-test/node_modules/html-webpack-plugin/lib/loader.js!/Users/xxx/WebstormProjects/vue-webpack-test/src/template.js" didn't return html.


  Build failed with errors.

**Comment by dgeibi** [comment]
@zhishaofei3 

https://github.com/dgeibi/html-webpack-plugin-js-output-demo

**Comment by zhishaofei3** [comment]
@dgeibi 感谢，应该是版本问题
