### ISSUE TITLE
Inject assets in .aspx / .master templates

### ISSUE THREAD

**Issue by higbdesign** [jantimon/html-webpack-plugin#1134]
## Expected behaviour
get a .master file with links and scripts injected

## Current behaviour
throw error on webpack compilation

### Config

```js
module.exports = {
  entry: 'app.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  module: {
    rules: [
      ...
    ]
  }
  plugins: [
    new HtmlWebpackPlugin({
           inject: "body",
           filename: '../../site.master',
           template: 'master_template.master',
}),
    ...
  ]
}
```

The masterpage begins with:

```
<%@ Master Language="VB" CodeFile="site.master.vb" Inherits="site" %>
...
```

## Relevant Links

https://github.com/jantimon/html-webpack-plugin/issues/815

## Additional context

After various tests I understand that the issue depends on `lodash template interpolate` delimiter that is the same of **aspx delimiter** (I read [this issue](https://github.com/jantimon/html-webpack-plugin/issues/815) and I tried in every way, I tried with file-loader and raw-loader but the result is the same).
I read the lodash documentation about template and you can use **backslashes** to treat the delimiter as plain text and it works! (e.g. `\\<%@ Master Language="VB" CodeFile="site.master.vb" Inherits="site" %\\>`)
But the output file contains the backslashes...

Is there a way to change this delimiter through webpack.config?
Should I duplicate the whole loader, edit loader.js and set _.templateSettings.interpolate to a custom delimiter?
Could the solution be a templateParameter option where you can set a custom template interpolate delimiter?

**Comment by jantimon** [comment]
If you use a different loader like the raw-loader it should work
