### ISSUE TITLE
HTMLs not minfied

### ISSUE THREAD

**Issue by abhijithvijayan** [jantimon/html-webpack-plugin#1136]
## Expected behaviour

HTML minification

## Current behaviour

No Change

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:
```
Node.js v8.12.0
win32 10.0.17134
npm 6.5.0
webpack@4.28.3
html-webpack-plugin@3.2.0
```

### Config

```
module.exports = {
    entry: {
      options: ["./src/scripts/options.js", './src/styles/options.scss'],
      popup: ["./src/scripts/popup.js", './src/styles/popup.scss'],
      background: ["babel-polyfill", "./src/scripts/background.js"]
    },
    output: {
      path: path.resolve(__dirname, "extension"),
      filename: "js/[name].js",
      publicPath: ""
    },
    node: {
        fs: 'empty'
    },
   plugins: [
      new HtmlWebpackPlugin({
        template: 'src/options.html',
        inject: false,
        minify: true,
        filename: 'options.html'
      }),
    ]
};
```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
    </body>
</html>
```

## Relevant Links

https://github.com/abhijithvijayan/kuttUrl-Chrome-extension

**Comment by jantimon** [comment]
Can you please try with the html-webpack-plugin@4 ?

**Comment by jantimon** [comment]
If you don't set any options it should minify only for production.

**Comment by jantimon** [comment]
oh could you please show me your development config?

**Comment by abhijithvijayan** [comment]
> oh could you please show me your development config?

https://github.com/abhijithvijayan/kuttUrl-browser-extension/blob/master/webpack.config.js

**Comment by jantimon** [comment]
if you set the config to `mode: "production"` minifcation should be enabled but with `mode: "development"` it should be disabled - you didn't set any mode

**Comment by abhijithvijayan** [comment]
my bad. sorry. Thanks anyway. @jantimon
