### ISSUE TITLE
Opt-out functionality for avoiding the removal of index.html comments

### ISSUE THREAD

**Issue by 4iAmAve** [jantimon/html-webpack-plugin#1141]
Hi,

for my project I want to provide SSI through nginx. Therefore, I have to add an `include` comment into the index.html, like the following.

`<!--# include virtual="/test.html" -->`

Now, since the html-webpack-plugin removes all comments or comment like content from the index.html, I have to work around it. 

However, is it/will it be possible to include such a flag into the plugin to opt-out of this feature?

**Comment by jantimon** [comment]
Without details on your environment and version it is hard to give an example but opt-out from magnification is possible.

**Comment by 4iAmAve** [comment]
@jantimon 
We are always on the latest release version. 
How can one opt-out? Haven't found any option in the doc.

Thanks in advance.

**Comment by jantimon** [comment]
You can set `minify` to `false`.
