### ISSUE TITLE
Templates with filenames other than "index.html" fail to execute/compile

### ISSUE THREAD

**Issue by docmars** [jantimon/html-webpack-plugin#1143]
I'm setting up my project to output two HTML files, per these instructions:
https://github.com/jantimon/html-webpack-plugin#generating-multiple-html-files

This is also happening with just one HtmlWebpackPlugin instance.

## Expected behaviour

When specifying any filename other than `index.html` for the `template` option, such as `assets.html` or `page.html`, HtmlWebpackPlugin should be able to read the template correctly, regardless of its name.

## Current behaviour

**With src/assets/index.html:**
```
{
  template: 'src/assets/index.html',
  filename: 'assets/index.html'
}
```
Everything works just dandy! Visiting `localhost:8080/assets/` pulls the page right up.

---

**With src/assets/assets.html:**
(index.html renamed to assets.html)
```
{
  template: 'src/assets/assets.html',
  filename: 'assets/index.html'
}
```

When visiting `localhost:8080/assets/`, the generated output of HtmlWebpackPlugin is:

```
ERROR in Template execution failed: TypeError: Cannot set property '_handlers' of undefined

ERROR in   TypeError: Cannot set property '_handlers' of undefined

  - assets.html:1825 init
    /Users/andrew.merskin/Desktop/Proteus Workspace/Platform/scree    ner/src/assets/assets.html:1825:22

  - assets.html:805 Assets
    /Users/andrew.merskin/Desktop/Proteus Workspace/Platform/scree    ner/src/assets/assets.html:805:19

  - index.js:284 Promise.resolve.then
    [screener]/[html-webpack-plugin]/index.js:284:18


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
```

## Environment

Node.js v8.10.0
darwin 18.0.0
npm 6.5.0
webpack 4.19.0
html-webpack-plugin 3.2.0 (was also happening in 4.0.0-alpha)

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  entry: {
    example: './src/example.js'
  },
  output: {
    path: `${__dirname}/dist`,
    filename: '[name].js',
    chunkFilename: '[name].[id].js'
  },
  module: {
    rules: [
      {
        // parse any files that end in .html
        test: /\.html$/,
        // exclude node_modules and the index.html page,
        // but include the svelte module, which needs to be transpiled down from ES6
        // https://github.com/babel/babel-loader/issues/171
        exclude: [/node_modules\/(?!svelte)/, /index.html/],
        // transpile JS
        use: [
          {
            loader: 'babel-loader',
            options: {
              cacheDirectory: !prod, // cache in dev for speedier recompilation
              babelrc: true
            }
          },
          {
            // parse svelte component files
            loader: 'svelte-loader',
            options: {
              hotReload: true,
              emitCss: true,
              preprocess: svelteConfig.preprocess
            }
          }
        ]
      },
    ]
  }
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'assets/index.html',
      template: 'src/assets/assets.html', // src/assets/index.html works, anything else doesn't
      hash: true
    })
  ]
}
```

## Relevant Links
This is a private project and cannot be shared.

**Comment by docmars** [comment]
**Update**

I managed to fix this issue by adding `/assets.html/` to the `exclude` list for the **html rule**.

I'm not clear on why this fixes it—is it that `assets.html` was being fed through `svelte-loader` before getting to HtmlWebpackPlugin?

**Comment by jantimon** [comment]
Hey @docmars 

I am very sorry for not answering earlier.  
If you tell webpack to use the `babel-loader` and `svelte-loader` for your asset.html file before it is passed to the html-webpack-plugin the html-webpack-plugin will get a svelte transformed file which  seems to be not renderable
