### ISSUE TITLE
ERROR in   TypeError: Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by lls94** [jantimon/html-webpack-plugin#1147]
ERROR in   TypeError: Cannot read property 'hash' of undefined

  - compiler.js:265 childCompiler.compileTemplates.then
    [test]/[html-webpack-plugin]/lib/compiler.js:265:30

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7

  - loader.js:744 Function.Module.runMain
    internal/modules/cjs/loader.js:744:11

  - node.js:285 startup
    internal/bootstrap/node.js:285:19

  - node.js:739 bootstrapNodeJSCore
    internal/bootstrap/node.js:739:3

![21321](https://user-images.githubusercontent.com/29952649/51782504-7c750200-2164-11e9-85da-32152e80812b.PNG)

**Comment by lls94** [comment]
html-webpack-plugin      4.0.0-beta.5

**Comment by jantimon** [comment]
Hey thank you for submitting a bug report 👍  
I having troubles to find out how I could reproduce this bug.  

Could you please try to create a [minimal reproduction example](https://stackoverflow.com/help/mcve) (especially remove all dependencies, loaders and plugins which are not necessary for reproduction) and attach it (with out node_modules) as a zip to this issue?
