### ISSUE TITLE
Roadmap for releasing 4.0.0 final

### ISSUE THREAD

**Issue by edmorley** [jantimon/html-webpack-plugin#1148]
Hi!

I was wondering what steps were remaining before the release of v4.0.0 as a non-pre-release?

It seems that the various compatibility issues with webpack 4 have now been resolved, and that there may not be any more breaking changes in the plugin for the short term? If so, then perhaps it's safe to release v4.0.0, with any remaining polish fixes being released in subsequent point releases?

**Comment by jantimon** [comment]
The most important issue is this one: https://github.com/jantimon/html-webpack-plugin/issues/1129 it handles the compatibility to webpack 5.  

If we manage to solve this issue we should release it as a stable version.

**Comment by sibiraj-sr** [comment]
@jantimon I would say #1129 can be tracked in html-webpack-plugin@5.alpha. and final version v4 can be released now.

**Comment by jdmerinor** [comment]
I agree with @sibiraj-sr having the V4 in hold because of an issue with V5 seems odd to me.

**Comment by jantimon** [comment]
People will have a lot of work to migrate from 3 to 4 because of plugin incompatibility anyway - I don't want to introduce the next breaking version to soon after that.

**Comment by maclockard** [comment]
Its probably going to be a while before folks migrate to webpack 5 considering it still hasn't been released and they will need to wait for all the plugins they use to support webpack 5 as well. Meanwhile, folks have been migrating to webpack 4 across last year and most commonly used webpack plugins support webpack 4 at this point.

Right now there isn't a stable version of html webpack plugin that has explicit support for webpack 4. Feels strange to block folks already on webpack 4 from being able to fully take advantage of webpack 4 features such as preload/prefetch split chunks without taking a beta version.

**Comment by edmorley** [comment]
Please can we release v4 as stable now? Version numbers are cheap, and it's likely to be longer than we think until webpack 5 is ready for use. Delaying the v4 release is confusing users since the repo readme is not in sync with what the users get with a default install (ref #1094).

**Comment by dweedon-stripe** [comment]
Bumping this. Would really like to see v4 released as stable.

**Comment by richardthombs** [comment]
Likewise, it is November 2019 and still this is in beta. Please push it!

**Comment by edmorley** [comment]
@jantimon Hi! Is there anything we can do to help with the release of v4 final? :-)

**Comment by econner** [comment]
Also agree, some guidance on which version of this library to use with each version of webpack would be helpful. We had pegged to `github:jantimon/html-webpack-plugin#webpack-4`, but that branch seems to be gone now. Instead we've installed via `npm i --save-dev html-webpack-plugin@next` and that seems to be working.

For google, the error we got when building,
```
Error: Command failed: /usr/bin/git checkout webpack-4
remote:        error: pathspec 'webpack-4' did not match any file(s) known to git.
```

**Comment by glen-84** [comment]
@jantimon,

4.x is nearly 2 years old already, and webpack 5 has still not been released. Please don't wait for it.

**Comment by CryZe** [comment]
What's really annoying to me is that the stable version of the favicons-webpack-plugin depends on html-webpack-plugin 4.0, which isn't even released.

**Comment by sibelius** [comment]
is there a migration guide to v4 of this plugin?

**Comment by jantimon** [comment]
Finally :) thanks to all of you for your work! 
https://dev.to/jantimon/html-webpack-plugin-4-has-been-released-125d
