### ISSUE TITLE
Support for webpackPrefetch and webpackPreload

### ISSUE THREAD

**Issue by jomaxx** [jantimon/html-webpack-plugin#1150]
**Is your feature request related to a problem? Please describe.**
Hello, not a problem but a useful enhancement. Webpack has support for preloading and prefetching via [magic comments](https://webpack.js.org/api/module-methods/#magic-comments). Currently html-webpack-plugin doesn't make any use of this.

**Describe the solution you'd like**
Add preloaded and prefetched bundles to the final html output.

**Describe alternatives you've considered**
The alternative is to do this as a post-build step.

**Additional context**
https://webpack.js.org/api/module-methods/#magic-comments

**Comment by jantimon** [comment]
I really like this idea and we almost integrated this feature.  
Unfortunately the only way to access information about magic comments is using the api of [webpack stats](https://webpack.js.org/configuration/stats/) which is very slow and will slow down the compilation for everyone who does not require prefetch or preload tags.

If we can find a better solution I would be very happy to merge a pull request

**Comment by MIreland** [comment]
Would it make sense to have it available as a disabled-by-default option, so that those of us who would benefit from it could enable it on production builds?

**Comment by jantimon** [comment]
Great approach 👍
