### ISSUE TITLE
Explain output path on README.md 

### ISSUE THREAD

**Issue by hg-pyun** [jantimon/html-webpack-plugin#1155]
There seems to be no content in the document about specifying output routes. We've found a lot of similar issues. Wouldn't it be better to explain them to `README.md`

#250, #286

like this situation. Want to make the following folder structure.
```
dist
  |- js
      |- bundle.[hash].js
  |- index.html
```
``` js
{
    output: {
        path: path.resolve(__dirname, '../dist'),
        filename: 'js/bundle.[hash].js'
    },
    ...
    plugins: [
        new CleanWebpackPlugin(['../dist'], {
            root: __dirname,
            allowExternal: true
        }),
        new HtmlWebpackPlugin({
            template: path.resolve(__dirname, '../src/template/index.html')
        })
    ]
};
```
It seems that quite a few people have the same problem. 
Thank you.

**Comment by jantimon** [comment]
The output path is managed by webpack - the html webpack plugin just adds a file to that output path.

The easiest way would be to set the entry name of your javascript to "js/main"

**Comment by hg-pyun** [comment]
Yes, I already know that. Don't you think it's a good idea to put this in the document?

**Comment by jantimon** [comment]
I am not sure..

Do you think really naming of javascript files is part of a plugin which generates html files 🤔 

Maybe we can link to the webpack documentation?

**Comment by hg-pyun** [comment]
It seems like a lot of people are searching for the above information.
