### ISSUE TITLE
Ability to indicate different inject position ('body' or 'head') to different chunk.

### ISSUE THREAD

**Issue by architgarg** [jantimon/html-webpack-plugin#1158]
Feature request - I want to inject two chunks - one chunk in head and another in body.

```
module.exports = {
  entry: {
    index: "./index.ts",
    index_head: "./index.css" // adding "_head" at the end to inject in head. (injects in head)
  },
  output: {
    path: "./dist",
    filename: "[name].bundle.js"
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./index.html",
      filename: "./dist/index.html",
      chunks: ["index", "index_head"]
    }),
    new HtmlWebpackInjector()
  ]
}
```

And I get the output as:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Archit's App</title>
    <script type="text/javascript" src="index_head.bundle.js"></script></head>
  </head>
  <body>
    <script src="index_bundle.js"></script> 
  </body>
</html>
```

**Comment by thearchitgarg** [comment]
A lot of people want something for this:

https://github.com/jantimon/html-webpack-plugin/issues/381
https://github.com/jantimon/html-webpack-plugin/issues/818
https://github.com/jantimon/html-webpack-plugin/issues/667

**Comment by thearchitgarg** [comment]
t

**Comment by thearchitgarg** [comment]
t

**Comment by thearchitgarg** [comment]
t

**Comment by chestnutchen** [comment]
Need such ability to do more things.
Since we had a lot of plugins dealing resouces in html such as `ScriptExtHtmlWebpackPlugin`, `HtmlResourceCdnPlugin` etc., we use options `inject: default|true` to benifit from these plugins. When some css or independent js should appear in other places which are not in `head|body`, we should set `inject: false` and rewrite many things or make a webpack plugins to hack it. This is so inefficient.

**Comment by afilp** [comment]
We really need this capability too.

How about this proposal?

```
chunks: ["index", "index_head"]
inject: ['body', 'head']
```

This syntax should be optional, and should have a 1-to-1 relation with the `chunks` array.

**Comment by dementor5** [comment]
It is necessary to have an opportunity, where to add a script - to body or head to specify async or defer.

**Comment by afilp** [comment]
Any ideas if this can be supported? Thanks!

**Comment by thearchitgarg** [comment]
@afilp What issue are you facing? Also please specify the html-webpack-plugin version you are using.

**Comment by jantimon** [comment]
Please give https://github.com/thearchitgarg/html-webpack-injector a try

**Comment by AlanZou007** [comment]
Any ideas if this can be supported? Thanks!

**Comment by lopesc** [comment]
+1
