### ISSUE TITLE
Unable to execute JS script in global context bundled using script-loader

### ISSUE THREAD

**Issue by sampathkumarm** [jantimon/html-webpack-plugin#1168]
## Expected behaviour

I am bundling some legacy JS with script-loader as there are many things global which gets bundled perfectly and also works when hardcoded the bundles in HTML.
![script-loader](https://user-images.githubusercontent.com/6489309/53059452-aa9be800-346b-11e9-80ae-b498ba9d9139.PNG)
![head-bundle](https://user-images.githubusercontent.com/6489309/53059387-80e2c100-346b-11e9-8327-ed5cdff4daba.PNG)

The issue appears when i use html-webpack-plugin to inject those bundled files dynamically using the template.
![template](https://user-images.githubusercontent.com/6489309/53059531-f2bb0a80-346b-11e9-997f-bf24aba7c0de.PNG)

Though the bundles are created and injected properly the page throws many JS "Uncaught errors" like 
![errors](https://user-images.githubusercontent.com/6489309/53059582-301f9800-346c-11e9-88c9-b0da169accfc.PNG)
because I feel the plugin is somehow conflicting with the script-loader and the resulting bundle is not the same as without using the html-webpack-plugin.

**I expect that the plugin should inject the bundled files as is created by webpack using script-loader as shown below.**

## Current behaviour
Bundle created when html-webpack-plugin not used:
![correct-bundle](https://user-images.githubusercontent.com/6489309/53059846-38c49e00-346d-11e9-9e20-86464d5c368b.PNG)

Bundle created when html-webpack-plugin used:
![wrong-bundle](https://user-images.githubusercontent.com/6489309/53059865-4b3ed780-346d-11e9-8c7c-4aa78b28f333.PNG)

Also i get errors when i do not add ".cshtml" to the script-loader
![script-loader-without-cshtml](https://user-images.githubusercontent.com/6489309/53060015-c43e2f00-346d-11e9-919e-997dbd6ef50b.PNG)
![cshtml-error](https://user-images.githubusercontent.com/6489309/53060018-c6a08900-346d-11e9-9e8a-ac0365c7a17d.PNG)
which then does not create the html at all.

## Tell us what the html-webpack-plugin does instead.
I expect that the plugin should inject the bundled files as is created by webpack using script-loader.

## Environment
OS: Windows 7
NodeJS: 8.9.4
NPM: 5.6.0
![modules](https://user-images.githubusercontent.com/6489309/53060221-855ca900-346e-11e9-86a5-484902fe2a48.PNG)

### Config
```js
const glob = require('glob');
const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
// const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
// const webpack = require('webpack');

module.exports = {
    entry: {
        'app': glob.sync('./Websites/FRB/Assets/theme-main/js/**/*.js', {
            ignore: [
                './Websites/FRB/Assets/theme-main/js/analytics/tealium.js',
                './Websites/FRB/Assets/theme-main/js/analytics/tealiumProducts.js',
                './Websites/FRB/Assets/theme-main/js/digitalBanking/**/*.js',
                './Websites/FRB/Assets/theme-main/js/pages/FRB.customHeadScripts.js',
                './Websites/FRB/Assets/theme-main/js/pages/Sitecore.edit.js'
            ],
        }),
        'head': [
            './Websites/WebUI/Assets/vendorjs/foundation-sites-5/modernizr/modernizr.js',
            './node_modules/mobile-detect/mobile-detect.js',
            './Websites/FRB/Assets/theme-main/js/analytics/tealium.js',
            './Websites/FRB/Assets/theme-main/js/pages/FRB.customHeadScripts.js'
        ],
        'jqx': [
            './Websites/WebUI/Assets/vendorjs/jqx/jqxcore.js',
            './Websites/WebUI/Assets/vendorjs/jqx/jqxdata.js',
            './Websites/WebUI/Assets/vendorjs/jqx/jqxchart.js'
        ],
        'vendor': [
            './Websites/WebUI/Assets/vendorjs/foundation-sites-5/jquery/dist/jquery.min.js',
            './Websites/WebUI/Assets/vendorjs/foundation-sites-5/foundation/js/foundation.min.js',
            './node_modules/jquery.cookie/jquery.cookie.js',
            './Websites/WebUI/Assets/vendorjs/jquery-ui/dist/jquery-ui.min.js',
            './Websites/WebUI/Assets/vendorjs/jquery-ui-touch/jquery.ui.touch-punch.min.js',
            './Websites/WebUI/Assets/vendorjs/jquery-inputmask/jquery.inputmask.bundle.js',
            './node_modules/jquery-validation/dist/jquery.validate.min.js',
            './node_modules/fullpage.js/dist/jquery.fullpage.min.js',
            './node_modules/mediaelement/build/mediaelement-and-player.min.js',
            './node_modules/slick-carousel/slick/slick.min.js',
            './Websites/WebUI/Assets/vendorjs/markerwithlabel/markerwithlabel_packed.js'
        ],
        'd3': [
            './Websites/WebUI/Assets/vendorjs/d3/d3.js'
        ],
        'wffm': [
            './Websites/FRB/sitecore modules/Web/Web Forms for Marketers/mvc/main.js'
        ]
    },
    mode: 'production',
    module: {
        rules: [
            {
                test: /!\.cshtml\.js$/,
                use: ['script-loader']
            }
        ]
    },
    output: {
        filename: 'frb.legacy.[name].bundle.js',
        path: path.resolve(__dirname, './Websites/FRB/Assets/theme-main/dist')
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: path.resolve(__dirname, './Websites/FRB/Views/Layouts/MainLayoutTemplate.cshtml'),
            filename: path.resolve(__dirname, './Websites/FRB/Views/Layouts/MainLayout.cshtml'),
            inject: false,
        }),
        new CleanWebpackPlugin(['./Websites/FRB/Assets/theme-main/dist'])
    ]
};
```

**Comment by sampathkumarm** [comment]
@jantimon can you please provide any insight on this?

**Comment by jantimon** [comment]
Sorry I don't fully understand this issue. 

Could you please provide a very simple minimalistic example of 1 js file, 1 cshtml file and a webpack config which contains only required configurations so I can try to reproduce your problem better?
