### ISSUE TITLE
`useShortDoctype: true` generates not correct html code `<!doctypehtml>`

### ISSUE THREAD

**Issue by alundiak** [jantimon/html-webpack-plugin#1171]
Isn't it proper to have `<!doctype html>` with space between "doctype" and "html"?

http://perfectionkills.com/experimenting-with-html-minifier/#use_short_doctype says:

![image](https://user-images.githubusercontent.com/2131633/53685794-a7341680-3d1f-11e9-8b2b-a85fe73fd480.png)

**Comment by jantimon** [comment]
What do you mean?  
This is the current code:

https://github.com/jantimon/html-webpack-plugin/blob/c27e5e46a334d9c1e177a521ea7c9a5ba3c6d980/default_index.ejs#L1
