### ISSUE TITLE
Inject meta before any elements in head

### ISSUE THREAD

**Issue by otakustay** [jantimon/html-webpack-plugin#1172]
**Is your feature request related to a problem? Please describe.**
When I customize my template, this plugin will inject `<meta>` tags specified via `meta` options to the tail of `<head>` element, like:

```html
<head>
    <title>App</title>
    <style>/* some customized style */</style>
    <meta name="charset" content="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
</head>
```

This can result in correct HTML parsing behavior since charset is defined after a `<style>` element, if inside `<style>` tag we have some non-ascii characters, browsers cannot decode them with specified charset.

**Describe the solution you'd like**
I'd like this plugin to inject all meta tags in head of `<head>` element, before `<title>`.

**Describe alternatives you've considered**
Currently we can write `<meta>` tags directly inside html template, however we cannot utilize the default template and inject styles and scripts via webpack plugins.

**Comment by jantimon** [comment]
I am really sorry for the inconvenience here.

Unfortunately you will not be able to inject `<meta name="charset" content="utf-8">` in your case but have to add it to the template manually.
