### ISSUE TITLE
你好  我想提个问题

### ISSUE THREAD

**Issue by yawangliang** [jantimon/html-webpack-plugin#1173]
你好  关于这个问题 就是个小问题
就是 我该如何在他们访问时自动生成一个url部分的随机数 来规避缓存的问题 
而不是在webpack直接配置编译一个定死的文件  这不是我们想看到的
我们想看到的是 在编译完以后 上传到web目录 访问的时候 他自动生成随机数在uri部分来规避静态缓存
大概如下：
a.com/b/c.js
a.com/b/c.js?214235231  #需求
谢谢

**Comment by jantimon** [comment]
Could you please ask in english?

**Comment by xyzhanjiang** [comment]
`new HtmlWebpackPlugin({hash: true})`
