### ISSUE TITLE
Requiring html by passed parameters makes errors

### ISSUE THREAD

**Issue by AK2806** [jantimon/html-webpack-plugin#1174]
## Expected behaviour

So I made a html template "container" including <header> <footer> <nav> etc. for my app. And I used a JSON file to configure the location of inner content htmls. Then, I passed the JSON's data as parameters to html-webpack-plugin.

I'm using the codes below to reuse the container template with injecting different inner page.
`<%= require('html-loader!./' + htmlWebpackPlugin.options.innerContentFilename + '.html') %>`
If it's working correctly, then different html pages using one same "container" should be produced.

## Current behaviour

Webpack couldn't process other assets path correctly.
At first, I thought that's my fault. But I made some tests as below

`<%= 'html-loader!./' + htmlWebpackPlugin.options.innerContentFilename + '.html' %>      // => show "html-loader!./index.html"`
`<%= require('html-loader!./index.html') %>      // => works`
`<%= require('html-loader!./' + htmlWebpackPlugin.options.innerContentFilename + '.html') %>      // => failed`

So I doubt it's a html-webpack-plugin bug or a lodash template parsing bug or something else.

## Environment

I've tried these on html-webpack-plugin 3.2.0 and 4.0.0beta5, all of them doesn't work.
My node.js is 10.15.2, npm is 6.4.1, webpack is 4.29.6. OS is win10.0.17134

### Config

webpack.config.js as below

```js
const Path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const pages = require(Path.resolve(__dirname, 'src/pages/pages.json'));

let isProduct = false;
let entries = {};
let htmlPlugins = [];

pages.forEach(page => {
    entries[page.name] = Path.resolve(__dirname, `src/js/${page.jsFilename}`);
    htmlPlugins.push(new HtmlWebpackPlugin({
        chunks: [page.name],
        filename: `${page.name}.html`,
        title: page.title,
        favicon: Path.resolve(__dirname, `src/img/favicon.ico`),
        template: Path.resolve(__dirname, `src/pages/${page.templateFilename}`),
        innerContentFilename: page.innerContentFilename
    }));
});

module.exports = {
    mode: isProduct ? 'production' : 'development',
    entry: entries,
    output: {
        path: Path.resolve(__dirname, 'dist'),
        filename: isProduct ? '[name].bundle.min.js' : '[name].bundle.js'
    },
    devtool: 'inline-source-map',
    devServer: {
        contentBase: './dist',
        port: 9200
    },
    plugins: [
        new CleanWebpackPlugin(),
        new MiniCssExtractPlugin({
            filename: isProduct ? '[name].min.css' : '[name].css'
        }),
        ...htmlPlugins
    ],
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env']
                    }
                }
            },
            {
                test: /\.css$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    'css-loader'
                ]
            },
            {
                test: /\.(png|svg|jpg|gif)$/,
                use: {
                    loader: 'file-loader',
                    options: {
                        outputPath: 'img'
                    }
                }
            },
            {
                test: /\.(ttf|eot|woff|woff2|otf)/,
                use: {
                    loader: 'file-loader',
                    options: {
                        outputPath: 'fonts'
                    }
                }
            }
        ]
    }
}
```

"container" template as below

```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title><%= htmlWebpackPlugin.options.title %></title>
  <!-- other things -->
</head>

<body>
  <div class="page">
    <!-- Main Navbar-->
    <header class="header">
      <!-- ........... -->
    </header>
    <div class="page-content d-flex align-items-stretch">
      <!-- Side Navbar -->
      <nav class="side-navbar">
        <!-- ........... -->
      </nav>
      <div class="content-inner">
        <%= require('html-loader!./' + htmlWebpackPlugin.options.innerContentFilename + '.html') %>
        <!-- Page Footer-->
        <footer>
        <!-- ........... -->
        </footer>
      </div>
    </div>
  </div>
</body>

</html>
```

pages.json as below

```json
[
    {
        "name": "index",
        "templateFilename": "container.html",
        "title": "Home",
        "innerContentFilename": "index",
        "jsFilename": "index.js"
    },
    {
        "name": "charts",
        "templateFilename": "container.html",
        "title": "Charts",
        "innerContentFilename": "charts",
        "jsFilename": "charts.js"
    }
]
```

directory structure as below

![tim 20190307184737](https://user-images.githubusercontent.com/6488012/53951519-9ada0000-4109-11e9-8c25-130514a85318.png)

**Comment by AK2806** [comment]
I've tried a lot for testing where the bug occurs.

I moved other html files except index.html charts.html and container.html, seems get to work.

I noticed there was a Warning message shows:

> WARNING in ./src/pages/pages.json (./node_modules/html-loader!./src/pages/pages.json)
    Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = "[\...'
    You may need an appropriate loader to handle this file type.

And requiring the html file statically shows no warning message.

I'm not sure what's happening, maybe a bug of json-loader?

**Comment by jantimon** [comment]
```
<%= require('html-loader!./' + htmlWebpackPlugin.options.innerContentFilename + '.html') %> // => failed
```

The support for requires like this have only limited support by webpack.  
Unfortunately there is not much we can do about that in this plugin

**Comment by AK2806** [comment]
Thank you for your reply @jantimon  . Now I'm just moving all the 'unused' htmls out of my pages directory. I found that if I only keep the necessary html files, the webpack won't trigger any errors and work well for me.
