### ISSUE TITLE
Can't reload html with HMR in webpack-dever-server

### ISSUE THREAD

**Issue by chillyond** [jantimon/html-webpack-plugin#1176]
## Expected behaviour

If enabled HMR, when html files changed, trigger an full reload

## Current behaviour

It does not reload

### Config

```js
{
     plugins: [
        new HtmlWebpackPlugin({
          template: './index.html'
        }),
        new webpack.HotModuleReplacementPlugin()
      ],
      devServer: {
        hot: true
      }
}
```

**Comment by Austaras** [comment]
well, it's because webpack-dev-server don't watch HTML file changes. There is a few solution for this:

1. put HTML files into assets and pass following config to webpack-dev-server
``` javascript
contentBase: __dirname + '/src/assets',
watchContentBase: true,
```
create-react-app is currently using this
2. pass 
``` javascript
 before(_, server) {
            server._watch(__dirname + '/src/index.html')
        }
```
to webpack-dev-server, however `_watch` is a private api

**Comment by jantimon** [comment]
Unfortunately there is not much we can do about that here for the plugin.  
The plugin is doing a recompile for the index.html file and the `webpack-dev-server` gets informed about the `index.html` file change.

However right now the hot module reloading is meant to be used only for replacing javascript code but not the underlying template.

As @Austaras said there are some workarounds but for a proper solution we would have to add this feature to the webpack-dev-server.
