### ISSUE TITLE
The old script tag are not deleted after build

### ISSUE THREAD

**Issue by Tinalst** [jantimon/html-webpack-plugin#1177]
## Expected behaviour

Auto deleted the old script after build 

## Current behaviour

The old script tag are not deleted after build

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
Node.js v10.15.1
darwin 17.5.0
npm --version 6.4.1
webpack@4.29.6 
html-webpack-plugin@3.2.0 

```

### Config
{
  "name": "server-setting",
  "version": "1.0.0",
  "description": "webpack dev server ",
  "main": "index.js",
  "scripts": {
    "dev": "webpack --mode development --config ./config/webpack.dev.conf.js",
    "build": "webpack --mode production --config ./config/webpack.prod.conf.js",
    "start": "webpack-dev-server --mode development --config ./config/webpack.dev.conf.js"
  },
  "author": "tinamlim",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.3.4",
    "@babel/preset-env": "^7.3.4",
    "autoprefixer": "^9.4.10",
    "babel-loader": "^8.0.5",
    "clean-webpack-plugin": "^2.0.0",
    "copy-webpack-plugin": "^5.0.1",
    "css-loader": "^2.1.1",
    "file-loader": "^3.0.1",
    "happypack": "^5.0.1",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "mini-css-extract-plugin": "^0.5.0",
    "node-sass": "^4.11.0",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "postcss-loader": "^3.0.0",
    "rxjs": "^6.4.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.29.6",
    "webpack-bundle-analyzer": "^3.1.0",
    "webpack-cli": "^3.2.3",
    "webpack-dev-server": "^3.2.1",
    "webpack-merge": "^4.2.1"
  },
  "browserslist": [
    "ie >= 8",
    "Firefox >= 20",
    "Safari >= 5",
    "Android >= 4",
    "Ios >= 6",
    "last 4 version"
  ]
}

```js

_webpack.common.conf.js_
const path = require('path');
const webpack = require('webpack');
const HtmlWebPackPlugin = require('html-webpack-plugin');
const HappyPack = require('happypack');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

function resolve(dir){
    return path.join(__dirname, '..', dir);
}

let enrties = {
    index: 'index',
    pageone: 'pageone'
};

module.exports = {
    entry: {
        index: './public/pages/index/index.js',
        pageone: './public/pages/pageone/index.js'
    },
    output: {
        filename: '[name].bundle.[hash].js',        

        path: path.resolve(__dirname, '../build/pages')  
    },
    module: {
        noParse: /public\/js\/jquery-3.3.1.min.js/, 
        rules: [ 
            {       
                test: /\.css$/,            
                use: [                    
                    'happypack/loader?id=happyCss'
                ]
            },
            {       
                test: /\.less$/,
                use: [
                    'happypack/loader?id=happyLess'
                ]
            },
            {     
                test: /\.scss$/,
                use: [
                  'happypack/loader?id=happyScss'
                ]
            },
            {     
                test: /\.(png|jpg|gif|jpeg)$/,   
                use:[{
                    loader: 'file-loader',
                    options: {
                        name: '[hash]bg.jpg',        
                        outputPath: '../images'      
                    }
                }]

            },
            {
                test: /\.(eot|svg|ttf|woff|woff2)$/,
                use: [{
                    loader: 'file-loader', 
                    options: {
                        outputPath: '../fonts'
                    }
                }]

            },
            {  
                test: /\.js$/,
                include: [resolve('public')], 
                exclude: /node_modules/, 
                loader: 'happypack/loader?id=happyBabel' 
            },
            {
                test: /\.(html)$/,
                include: [resolve('public')], //构建优化
                exclude:  /node_modules/,
                use: [
                    'happypack/loader?id=happyHtml'
                ]
            }
        ],
    },
    resolve: {
        extensions: ['.js'], 
        modules: [
          resolve('public'),
          resolve('node_modules')
        ],
        alias: {
            jQuery: path.resolve(__dirname, '../public/js/jquery-3.3.1.min.js')
        }
    },
    plugins: Object.keys(enrties).map(key => {
        return new HtmlWebPackPlugin({
            template: './public/pages/' + key +'/index.html', 
            filename: key + '.[hash].html',                  
            minify: {
                minimize: true,               
                removeAttributeQuotes: true,  
                removeComments: true,      
                collapseWhitespace: true,     
                minifyCSS: true,              
                minifyJS: true,              
                removeEmptyElements: true    
            },
            hash: true,                       
            chunks: [key]                     
        })
    }).concat([ 
        new webpack.ProvidePlugin({ 
            jQ: 'jQuery'            
        }),
        new HappyPack({  
            id: 'happyBabel',
            threads: 3,
            loaders:[
                {
                    loader: 'babel-loader',
                    query: {
                        presets: ['@babel/preset-env'],
                        cacheDirectory: true
                    }
                }
            ]
        }),
        new HappyPack({
            id: 'happyScss',
            threads: 4,
            loaders: ['style-loader!css-loader!sass-loader!postcss-loader']
        }),
        new HappyPack({
            id: 'happyCss',
            threads: 5,
            loaders: ['style-loader!css-loader']
        }),
        new HappyPack({
            id: 'happyLess',
            threads: 6,
            loaders: [ 'style-loader!css-loader!less-loader']
        }),
        new HappyPack({
            id: 'happyHtml',
            threads: 7,
            loaders: [
                {
                    loader: 'html-loader',
                    query: {
                        attrs: ['img:src', 'img:data-src']
                    }
                }
            ]
        }),
        // new BundleAnalyzerPlugin()
    ])

};

_webpack.conf.dev.js_

const path = require('path');
const webpack = require('webpack');
const webpackMerge = require('webpack-merge');
const CleanWebpackPlugin = require('clean-webpack-plugin');

const common = require('./webpack.common.conf');

module.exports =  webpackMerge(common, {
    devtool: "cheap-module-eval-source-map",
    devServer: {
        contentBase: './build', 
        host: 'localhost',      
        port: 8080,            
        open: true,           
        hot: true,             
        hotOnly: true           
    },
    plugins: [
        new webpack.NamedModulesPlugin(), 
        new webpack.HotModuleReplacementPlugin() 
    ]

});
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <div id="header">1     </div>
  <img src="../../images/WX20190312-175911@2x.png" data-src="../../images/WX20190312-175911@2x.png">
  <script src="index.js"></script>
</body>
</html>
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

**Comment by Broham** [comment]
I'm having this same issue.

**Comment by jantimon** [comment]
Sorry I don't understand what the html-webpack-plugin is supposed to do here.  
It takes all assets from the current build and includes them to the template you provide.  
It is not supposed to remove any script tags.

**Comment by Tinalst** [comment]
> Sorry I don't understand what you are asking for.
> The html-webpack-plugin takes all assets which it gets from the current webpack build and includes them to the template you provide.
> 
> It is not supposed to remove any script tags.

yes , theoretically speaking, I create a html template and include a script like this: 
```
...
<body>
 ....
      <script src="index.js">
 </body>
...
```
After build, the index.js -> bundle.js ,and the html template will look like this:
```
...
<body>
....
    <script src="bundle.js">
</body>
...
```
Actually, the template as below:
```
...
<body>
....
    <script src="index.js"> // this line shouldn't appear， however， it still appear. 
    <script src="bundle.js">
</body>
...
```
Actually, index.js file has be bundled to bundle.js, which means the  <script src="index.js">  should remove , it is right ?

**Comment by jantimon** [comment]
Most people are using the `webpack-dev-server` during development and therefore don't need to add the `index.js` file manually.

Therefore this plugin will never delete scripts from the html file as it does not know which to delete and which to keep.

However you might just have two templates - one for development and one for production to workaround this issue.

**Comment by Tinalst** [comment]
> Most people are using the `webpack-dev-server` during development and therefore don't need to add the `index.js` file manually.
> 
> Therefore this plugin will never delete scripts from the html file as it does not know which to delete and which to keep.
> 
> However you might just have two templates - one for development and one for production to workaround this issue.

sorry，I not really understand what you said. Do you mean that create two html file one for development and one for production? It seems unpractical.  If not add index.js to  index.html (not add pageone.js to pageone.html ), I am confused the webpack how to know the correspondence between them.

**Comment by jantimon** [comment]
You have two options:

- use `webpack-dev-server` with only one index.html
- use it without the `webpack-dev-server` and create two html files

**Comment by Tinalst** [comment]
> You have two options:
> 
> * use `webpack-dev-server` with only one index.html
> * use it without the `webpack-dev-server` and create two html files

Howerver, in this issue, I want to   test multiple pages application not single page application

**Comment by jantimon** [comment]
I guess in that case you should go with `webpack-dev-server` here
