### ISSUE TITLE
Specify version of JavaScript files in <script> tag.

### ISSUE THREAD

**Issue by envious** [jantimon/html-webpack-plugin#1178]
I'm trying to automatically set the version in the injected JavaScript <script> tag i.e.

    <script type="text/javascript" src="/main.b366711b36452b7fdfa6.bundle.js" version="xyz"></script>

Is such a feature already available in this plugin, if not, are others in agreement that it should be?

**Comment by jantimon** [comment]
There is no `version` attribute for script tags so it is very unlikely that it will ever be implemented in this plugin.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Browser_compatibility

You can achieve that by turning of the `inject` feature in the HtmlWebpackPlugin options or writing a plugin which processes the script tags before they get injected.
