### ISSUE TITLE
Performance issue in version 3.x

### ISSUE THREAD

**Issue by maksimr** [jantimon/html-webpack-plugin#1180]
## Expected behavior
Recompilation should have reasonable recompilation time 

## Current behavior
This plugin spend too much time in recompilation

## Environment

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v10.15.0
darwin 18.2.0

npm --version
6.4.1

npm ls webpack
webpack@3.12.0

npm ls html-webpack-plugin
html-webpack-plugin@3.2.0
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```bash
webpack-dev-server --config=config.js -d  --progress --inline --devtool eval --colors
```

```js
    return [
      'foo.html',
      'bar.html',
      'zoo.html'
    ].map(function(fileName) {
      return new HtmlWebpackPlugin({
        inject: false,
        template: require('path').resolve('myDir', fileName),
        filename: fileName,
        iconMeta: iconMeta,
        AppBuildConfig: AppBuildConfig
      });
    });
```

```html
<!doctype html>
<head>
  ...
  <base href="<%=htmlWebpackPlugin.options.AppBuildConfig.backend.youtrackBaseUri%>">
  <%=htmlWebpackPlugin.options.iconMeta%>
</head>
<body>
 <div id="app">...</div>
<script src="<%=htmlWebpackPlugin.files.chunks.vendor.entry%>"></script>
<script src="<%=htmlWebpackPlugin.files.chunks.main.entry%>"></script>
</body>
</html>
```

This commit https://github.com/jantimon/html-webpack-plugin/commit/06c59a7
have improved performance 3-4 times but subjectively this plugin still spends too much time.

![image](https://user-images.githubusercontent.com/616193/54829828-541f0500-4cc8-11e9-894b-54d4c087a593.png)

From the screenshot above you can see that most of the CPU consume [`compilation.getStats().toJson()`](https://github.com/jantimon/html-webpack-plugin/blob/v3.2.0/index.js#L720) maybe we can avoid calling this method and get needed information from another place

Thanks

**Comment by maksimr** [comment]
Thanks for such customizable API so I have solved my problem just passing custom function `templateParameters`
```js
        templateParameters: (compilation, assets, options) => ({
          htmlWebpackPlugin: {
            files: assets,
            options: options
          }
        })
```

**Comment by jantimon** [comment]
you can also use 4.x

**Comment by maksimr** [comment]
@jantimon looks like 4.x requires webpack@4.x

**Comment by maclockard** [comment]
@jantimon It looks like 4.x still hasn't been released yet, it requires taking a beta version. Are there any plans to release it?

**Comment by jantimon** [comment]
@maclockard we wait for some support here: https://github.com/jantimon/html-webpack-plugin/issues/1129
