### ISSUE TITLE
Offer to add collapseBooleanAttributes: true to default minimize config

### ISSUE THREAD

**Issue by utrumo** [jantimon/html-webpack-plugin#1185]
**Is your feature request related to a problem? Please describe.**
When i run prod build, all my html files are minimizing.
Line `<script src="my-script.js" defer></script>`
turns into it `<script src="my-script.js" defer="defer"</script>`
https://github.com/kangax/html-minifier/issues/997

defer="defer" - it is a xhtml syntax.
https://www.w3schools.com/tags/att_script_defer.asp

**Describe the solution you'd like**
Add collapseBooleanAttributs to default minify config.

**Comment by jantimon** [comment]
Good point we should take a look if we can combine it with the `xhtml` option

**Comment by jantimon** [comment]
Would you like to create a pull request for this feature?
