### ISSUE TITLE
Generated hash is always the same

### ISSUE THREAD

**Issue by aprilmintacpineda** [jantimon/html-webpack-plugin#1190]
## Expected behaviour

Hash should be different every build.

## Current behaviour

Hash is always the same.

## Environment

Node.js: 11.13.9, darwin 18.2.0
npm: 6.9.0
webpack: 4.29.6
html-webpack-plugin: 3.2.0. Run the following to get it quickly:

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
new HTMLWebpackPlugin({
  dynamicConcat,
  publicUrl: JSON.stringify(`/${helpers.cleanSlashes(publicUrl)}`),
  title: process.env.WEBSITE_NAME,
  template: path.join(__dirname, '../public/index.html'),
  path: path.join(__dirname, `../build/${target}`),
  filename: 'index.html',
  minify: {
    removeComments: true,
    collapseWhitespace: true,
    removeRedundantAttributes: true,
    useShortDoctype: true,
    removeEmptyAttributes: true,
    removeStyleLinkTypeAttributes: true,
    keepClosingSlash: true,
    minifyJS: true,
    minifyCSS: true,
    minifyURLs: true
  }
}),
```

However, hashes of other files generated by webpack are correct.

**Comment by jantimon** [comment]
Have you already try the beta version?  
https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-beta.5
