### ISSUE TITLE
[4.0.0-beta-5] excludeChunks is ignored when chunks is an entry point

### ISSUE THREAD

**Issue by ewingrj** [jantimon/html-webpack-plugin#1204]
## Expected behaviour

Tell us what you would expect the html-webpack-plugin should.

All chunks in the `excludeChunks` option should be ignored.

## Current behaviour

Tell us what the html-webpack-plugin does instead.

They are included if they are a dep of any specified chunks

Ex.

```
entry = {
    signup: 'file/path'
}

optimization = {
    runtimeChunk: 'single'
}

plugins = {
 new HtmlWebpackPlugin({
      chunks: ['signup'],
      excludeChunks: ['runtime'],
    })
}
```

I would expect the outputted html to exclude the runtime chunk b/c I already include it in the template & am using the 'single' runtime optimization.

However the output includes both the runtime & signup chunks as well as any split chunks that signup entry relies on.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
npm --version
npm ls webpack
npm ls html-webpack-plugin
```
Node.js v8.11.3
darwin 18.5.0
npm: 6.9.0
html-webpack-plugin@4.0.0-beta.5
webpack@4.30.0

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

**Comment by jantimon** [comment]
Right now this is the implementation of the exclude logic:

https://github.com/jantimon/html-webpack-plugin/blob/25465510df1633f76005f430b098cc7783e0495b/index.js#L495-L514

Which is executed with the data from `Array.from(compilation.entrypoints.keys())` here:

https://github.com/jantimon/html-webpack-plugin/blob/25465510df1633f76005f430b098cc7783e0495b/index.js#L179-L180

How can we improve it?

**Comment by ewingrj** [comment]
So I looked at this a bit more and the reason the runtime isn't filtered is because it isn't returned in `compilation.entrypoints.keys()`. It appears that the `runtime` chunk is handled differently then the other chunks.

The runtime is returned here:

https://github.com/jantimon/html-webpack-plugin/blob/655cbcdb9a81db774dd1a66fada085dd6c20dee0/index.js#L601

**Comment by jantimon** [comment]
Maybe the runtime chunk hasn't been created at the time of filtering.

Could you please try to fix this in a pull request?
