### ISSUE TITLE
htmlWebpackPlugin.options in custom loader

### ISSUE THREAD

**Issue by kwhat** [jantimon/html-webpack-plugin#1208]
## Expected behaviour
I do not think this is a bug with html-webpack-plugin, more of a question about why the ejs-html-loader is not working.
 
## Current behaviour
Trying to access htmlWebpackPlugin.options properties via custom loader [ejs-html-loader](https://github.com/mcmath/ejs-html-loader) and the htmlWebpackPlugin property is never defined and I am not sure why.  There doesn't appear to be a whole lot of documentation for creating 3rd party loaders, so I am hoping that you can point me in the right direction.  Everything else about the loader appears to work correctly.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

Node.js v10.14.1
win32 10.0.17134
npm --version: 6.4.1
-- webpack@4.30.0
-- html-webpack-plugin@3.2.0

### Config

```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const WebpackMd5Hash = require('webpack-md5-hash');
const CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
    entry: {
        'app': 'app.js'
    },
    output: {
        path: __dirname + '/dist',
        filename: 'app.js'
    },
    resolve: {
        modules: [
            'node_modules',
            path.resolve(__dirname, './')
        ]
    },
    module: {
        rules: [
            {
                test: /\.html$/,
                use: [
                    {
                        loader: 'html-loader'
                    },
                    {
                        loader: 'ejs-html-loader',
                        options: {
                            title: 'TEST2',
                            page: './testing.html',
                            production: process.env.ENV === 'production'
                        }
                    }
                ]
            }
        ]
    },
    plugins: [
        new CleanWebpackPlugin(),
        new HtmlWebpackPlugin({
            inject: false,
            hash: true,
            publicPath: '/',
            title: 'TEST1',
            page: './testing.html',
            template: './layout.html',
            filename: 'dashboard.html',
            showErrors: true
        }),
        new WebpackMd5Hash()
    ]
}
```

Copy your template file if it is part of this issue:

layout.html

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title><%= htmlWebpackPlugin.options.title %></title>
        
        <script src="/app.js"></script>
    </head>
    <body>
        <%- include(page) %>
    </body>
</html>
```

testing.html

```html
<div class="content">
    Hello World!
</div>
```

## Relevant Links
https://github.com/mcmath/ejs-html-loader

## Additional context
The loader options are available in the template:

```
options: {
    title: 'TEST2',
    page: './testing.html',
    production: process.env.ENV === 'production'
}
```

I would just like to use the htmlWebpackPlugin.options instead or in addition to the above options.

```
{
    inject: false,
    hash: true,
    publicPath: '/',
    title: 'TEST1',
    page: './testing.html',
    template: './layout.html',
    filename: 'dashboard.html',
    showErrors: true
}
```

Any documentation related to getting this properties to be available in the loader would be helpful.

**Comment by jantimon** [comment]
Sorry I don't know how the ejs-html-loader works in detail.

The html-webpack-plugin logic is the following:

1. load the html file using the html-webpack-plugin internal loader
2. if the interal loader detects that there is an additional loader present like in your example it will just path everything over to that loader
3. the custom loader compiles the html file to a js function e.g. `<h1><%= hello %></h1>`  -> `(data) => `<h1>${data.hello}</h1>`
4. the html-webpack-plugin sends the data from `templateParameters` to the compiled template and gets html in return
5. the html-webpack-plugin injects css and js tags

**Comment by kwhat** [comment]
I am trying to use one of the templateParameters options with the ejs `<%- include(htmlWebpackPlugin.options.page) %>` at step 3 but the variable is not available until step 4.
