### ISSUE TITLE
Feature Request: documentation on using with Express

### ISSUE THREAD

**Issue by stoplion** [jantimon/html-webpack-plugin#1209]
Hi, since it's been asked many times on here (unanswered) and numerous times on SO (mostly unanswered) seems it might be a worth while adding some documentation on how to use this plugin with Express.

**Comment by jantimon** [comment]
Can you please give a little bit more context?  
The `html-webpack-plugin` can't be used together with express directly.  

For development you can use  `webpack-dev-middleware`   
For production you need to build the files first so you will get a html file which can [be served by express as static file](https://expressjs.com/en/starter/static-files.html)
