### ISSUE TITLE
Which situation will cause the templateParameters is not used

### ISSUE THREAD

**Issue by WeiFei365** [jantimon/html-webpack-plugin#1210]
Which situation will cause ```typeof newSource === 'string'``` in here:
https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L348

in my configs, i passed the parameter *templateParameters*, but it not used, so i debug the *html-webpack-plugin* source code, and found the ```typeof newSource === 'string'``` is true, this will cause the ```self.executeTemplate``` not be called in here:
https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L263

so the *templateParameters* is not used.

need help please!

**Comment by jantimon** [comment]
The html-webpack-plugins supports a wide range of different loaders.  
Some of them return template functions other return plain html as a string.

It looks like you are using one which returns just a string.  
You can try `console.log(newSource)`

**Comment by WeiFei365** [comment]
finally, i use the compile-ejs-loader to preprocess the html template.

before that, i don't know if the html-loader return the plain html as a string, and i did't find any documention about why & how.

in the beginning, i try to use the ejs-loader to replace html-loader, but it can't work, there are some problems:

* the ejs-loader use lodash to compile the html template, so i can't pass the templateParameters which defined in the html-webpack-plugin

* i can't use the include to import sub-template

* others

then, i try to use ejs-compiled-loader, it also not work, [#33](https://github.com/bazilio91/ejs-compiled-loader/issues/33#issuecomment-343377891)、[#38](https://github.com/bazilio91/ejs-compiled-loader/issues/38#issuecomment-412362465)



finally, i use the compile-ejs-loader to preprocess the html template. it use the ejs engine, i can use 'require' to import sub-template ([#33](https://github.com/bazilio91/ejs-compiled-loader/issues/33#issuecomment-343377891)), i can use templateParameters in the main html template and sub-template, also i can use the ejs language...

Great!
Just remarks and hope to helps  friends!
