### ISSUE TITLE
The delimiter here should be parameter controllable

### ISSUE THREAD

**Issue by huzunjie** [jantimon/html-webpack-plugin#1220]
Correlation code ：
https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L919
https://github.com/jantimon/html-webpack-plugin/blob/master/lib/loader.js#L26

There is a risk of conflict between the html-webpack-plugin template engine and the web server ejs template engine.

# Solutions:

Rewrite the method getFullTemplatePath
```
HtmlWebpackPlugin.prototype.getFullTemplatePath = function(template, context) {
  // Resolve template path
  return template.replace(
    /([!])([^/\\][^!?]+|[^/\\!?])($|\?[^!?\n]+$)/,
    (match, prefix, filepath, postfix) => prefix + path.resolve(filepath) + postfix
  );
}
```
Add Webpack/module/rules 
```
     {
        test: /\.ejs$/,
        loader: 'html-webpack-plugin/lib/loader.js',
        options: {
          escape: /{%-([\s\S]+?)%}/g,
          evaluate: /{%([\s\S]+?)%}/g,
          interpolate: /{%=([\s\S]+?)%}/g
        }
      }
```

**Comment by jantimon** [comment]
You can use another template loader if the default behaviour das not fit your needs.  

E.g. 
```
new HtmlWebpackPlugin({
   template: '!!ejs-loader!index.ejs'
})
```
