### ISSUE TITLE
when 'inject' is false, no favicon shotcut link is injected even if 'favicon' option is set

### ISSUE THREAD

**Issue by ariel42** [jantimon/html-webpack-plugin#1222]
## Expected behaviour

Since favicon.ico is not a script, and 'favicon' option is configured, I would expect the plugin to inject the shortcut icon link as usual, even though the 'inject' option is false. Turning 'inject' to false is useful sometimes, for example when the html file doesn't have any script.

## Current behaviour

When 'inject'=false the 'favicon' option is ignored even if set, and no shortcut icon link is injected.

## Environment
```
Node.js 10.13.0
Windows 10.0.17134
npm 6.4.1
webpack 4.32.2
html-webpack-plugin 3.2.0
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  ...
  plugins: [
    new HtmlWebpackPlugin({
        inject: false,
        minify: htmlMinifySettings, //defined somewhere
        favicon: 'favicon.ico',
        template: 'index.html',
        filename: 'index.html',
   }),
  ]
}
```

**Comment by jantimon** [comment]
Hey @ariel42 

right now injection covers every post modification of the html code.

If you disable this feature you always have to do that inside your template
