### ISSUE TITLE
Generate cache friendly favicon path

### ISSUE THREAD

**Issue by rightaway** [jantimon/html-webpack-plugin#1224]
When I set `favicon` property the path is generated in the html as `/favicon.png` which isn't good for long term caching. We should be able to configure a name just like `file-loader` allows so that we can include `[contenthash]` so whenever the favicon contents change the path is different.

Or at least include in documentation a workaround, if there's a way to do this if we use `file-loader` instead of this plugin and manually add the `<link>` to the html template to have it use the generated cache friendly path.

**Comment by jantimon** [comment]
Using the file loader should work - you can probably do sth like:

```<link rel="shortcut icon" href="<%= require('favicon.ico' %>">```

**Comment by disfated** [comment]
You actually can't...

**Comment by jantimon** [comment]
Why?

**Comment by disfated** [comment]
My bad. You can :)
My problem was that plugin was trying to parse html-comments for some reason.
