### ISSUE TITLE
Wrong description of meta-tag usage

### ISSUE THREAD

**Issue by solveigmarianes** [jantimon/html-webpack-plugin#1226]
I use html-webpack-plugin with html-webpack-template. Currently the readme says that usage of meta tag should look like this:
 ```js
        meta: {
            viewport: 'width=device-width, initial-scale=1, shrink-to-fit=no'
        }
```

However, I found that usage with html-webpack-template required me to use it like this:
```js
        meta: [{
            name: 'viewport',
            content: 'width=device-width, initial-scale=1, shrink-to-fit=no'
        }]
```

I don't know if this is an issue with other templates, but it certainly is with this one.
Just thought you should know, and possibly add a note to your readme about this.

**Comment by jantimon** [comment]
Hey @solveigmarianes right now the default for html-webpack-plugin **4.x** is the following:

https://github.com/jantimon/html-webpack-plugin/blob/895db297d06e1c31aa89c73969f5f040ba7ef88d/index.js#L66-L69
