### ISSUE TITLE
How to use without "htmlWebpackPlugin.options"

### ISSUE THREAD

**Issue by hg-pyun** [jantimon/html-webpack-plugin#1227]
Hello, I have a question about using the plugin. How do I replace directly without the parent path `htmlWebpackPlugin.options`?

#### AS-IS
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
  </head>
  <body>
    <h1><%= htmlWebpackPlugin.options.hello %></h1>
  </body>
</html>
```

#### TO-BE
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
  </head>
  <body>
    <h1><%= hello %></h1>
  </body>
</html>
```
`htmlWebpackPlugin.options` is a good module, but I think it is too long. Is there any way to reduce it?

**Comment by jantimon** [comment]
You can use `templateParameters` in different ways:

```js
new HtmlWebpackPlugin({
 templateParameters: { hello: 'World' }
})
```

or 

```js
new HtmlWebpackPlugin({
 templateParameters: (compilation, assets, assetTags, options) => {
    return { hello: 'World' }
  }
})
```

or even with a async function:



```js
new HtmlWebpackPlugin({
 templateParameters: async (compilation, assets, assetTags, options) => {
    return { hello: 'World' }
  }
})
```

**Comment by hg-pyun** [comment]
@jantimon Thank you!, I will try it :D

**Comment by jantimon** [comment]
Cool - please let me know if it work as expected

**Comment by sim2github** [comment]
@jantimon thanks for the explanation.

If i include data with external file:
```js
new HtmlWebpackPlugin({
 templateParameters: (compilation, assets, assetTags, options) => {
    return require("./src/data.json");
  }
})
```
Can i with `compilation` parameter emit rerender `template` on data change?

**Comment by jantimon** [comment]
@sim2github as fast as I know this is not possible - however if you use this inside your template it should work

**Comment by sim2github** [comment]
@jantimon client side rendering is not what i looking for (i prefer static site generator). Thanks.

**Comment by sim2github** [comment]
Actually deep dive in [webpack plugin interaction](https://github.com/webpack/docs/wiki/How-to-write-a-plugin#monitoring-the-watch-graph) give me the way to emit rebuild instance.
All we need is add my data file to `compilation.fileDependencies` watch list.
```js
new HtmlWebpackPlugin({
 templateParameters: (compilation, assets, assetTags, options) => {
     const dataFile = "./src/data.json";
     if (compilation.fileDependencies.add) {
        compilation.fileDependencies.add(dataFile);
      } else {
        // Before Webpack 4 - fileDepenencies was an array
        compilation.fileDependencies.push(dataFile);
      }
     
    delete require.cache[require.resolve(dataFile)];
    return require(dataFile);
  }
})
```

**Comment by jantimon** [comment]
The template is executed during build time - so it is not client side rendering and will automatically do the file watching for you.

Your template would like this (probably you should use a function as export):

https://github.com/jantimon/html-webpack-plugin/blob/35a154186501fba3ecddb819b6f632556d37a58f/examples/javascript/template.js#L1-L6

**Comment by sim2github** [comment]
I use handlebars-loader "sugar" syntax with current plugin to inject assets and it works perfect in production mode with just
```js
new HtmlWebpackPlugin({
 template: './path/to/template.hbs',
 templateParameters: require('./path/to/data/file.json');
})
```
but in development mode plugin watch changes of `template` and not `templateParameters` value. So
```js
new HtmlWebpackPlugin({
 template: './path/to/template.hbs',
 templateParameters(compilation) {
     const DATA = './path/to/data/file.json';
    // Add datafile path to watch and rebuild when data changes
    compilation.fileDependencies.add(DATA);
    // Clear previous cached data from file if exist
    delete require.cache[require.resolve(DATA)];
    // Return always fresh data
    return require(DATA);
  }
})
```
works perfect for me (rebuild on `file.json` change and update page on dev-server).

Thanks. Now i'm happy.

**Comment by jantimon** [comment]
Cool that should work 👍

Another approach would be to use a a `.js` file as template:

template.js

```js
module.exports = function() {
  const data = require('./some/file.json');
  return require('./path/to/template.hbs')(data);
}
```

```js
new HtmlWebpackPlugin({
 template: './template.js'
})
```

**Comment by hg-pyun** [comment]
@jantimon It works for me. Good advice. Thank you.
