### ISSUE TITLE
the default delimiter `<%` should be configurable or escapable 

### ISSUE THREAD

**Issue by xiangnanscu** [jantimon/html-webpack-plugin#1228]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use html-webpack-plugin to make a template file (the output file contains `<%- foo %>`)

**Describe the solution you'd like**
the default delimiter `<%` should be configurable or escapable 

**Describe alternatives you've considered**

**Additional context**

**Comment by jantimon** [comment]
By default the html-webpack-plugin is using a ejs like loader.  

To get around this you can use the `raw-loader` for example like this: `template: '!!raw-loader!index.ejs'`
