### ISSUE TITLE
whether i can use React JSX as a template

### ISSUE THREAD

**Issue by zhangyuang** [jantimon/html-webpack-plugin#1229]
now, i want to use jsx as a template.
because, i want to render meta label dynamically。
if i use template engine, i think it is not smart
i hope i can use this code
```
function Html (props) {
return (
<html>
props.meta.map(item => {
return <meta {item.type}={item.value} />
})
</html>
)
}
```

**Comment by jantimon** [comment]
yes

**Comment by zhangyuang** [comment]
> yes

html-webpack-plugin template option can receive a react component? or we can contribute pr？

**Comment by jantimon** [comment]
A template has to return a function which returns a string.

So you will have to use react renderToString
