### ISSUE TITLE
onerror attribute on scripts

### ISSUE THREAD

**Issue by victornpb** [jantimon/html-webpack-plugin#1232]
**Is your feature request related to a problem? Please describe.**
The users of our application were unable to load our SPA app because they were getting errors while loading the entry point script.

We currently have a "splash screen" with a loading spinner inlined in the index.html, I would like to detect when a script failed to load and present a refresh button to the user.

**Describe the solution you'd like**
Be able to add a onerror attribute to the <script> tag so I can handle it.
```html
<script type="text/javascript" src="main.a303745140bb6228bdd2.js" onerror="[expression]"></script>
```

**Describe alternatives you've considered**
I tried to add an inline script containing a window.onerror handler, but It failed to detect errors.
I could also post-process the index.html, but it sounds like a job for the html-webpack-plugin.

**Additional context**
![Screen Shot 2019-06-25 at 2 48 11 PM](https://user-images.githubusercontent.com/3372598/60121038-95580280-9758-11e9-8c54-19223e1e7921.png)

**Comment by jantimon** [comment]
What about the following:

```
window.onerror = function() { ... }
```

Another solution would be to set `inject` to false and iterate over the scripts by yourself.

**Comment by victornpb** [comment]
I tried adding an inline script in the head of my index template, it doesn't actually trigger a global error event.

Can you point me to a handbook or some sort of example that I can base of to do 3.?

**Comment by jantimon** [comment]
Sure here: https://github.com/jantimon/html-webpack-plugin#events
