### ISSUE TITLE
Parameter 'assets' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by Austaras** [jantimon/html-webpack-plugin#1243]
## Expected behaviour

No typing error when using TypeScript

## Current behaviour
version 4.0.0-beta.7

ERROR in /home/chla/Code/template/node_modules/html-webpack-plugin/typings.d.ts(105,11):
TS7006: Parameter 'assets' implicitly has an 'any' type.

ERROR in /home/chla/Code/template/node_modules/html-webpack-plugin/typings.d.ts(114,11):
TS7006: Parameter 'assets' implicitly has an 'any' type.

## Environment
tsc 3.5.3 with noImplicitAny enabled

## fix
manually add any type to `assets` will fix this error

**Comment by jantimon** [comment]
Oh thanks for the report.
Probably we can just use the typings from here:

https://github.com/jantimon/html-webpack-plugin/blob/8b7255f555423dd1bfa51a3c28700e4bd116f97b/index.js#L356-L362

Could you please create a pull request for this?

**Comment by Austaras** [comment]
done

**Comment by jantimon** [comment]
4.0.0-beta.8
