### ISSUE TITLE
Special target URL for the script bundle/css

### ISSUE THREAD

**Issue by CMCDragonkai** [jantimon/html-webpack-plugin#1246]
I'm planning to have my Javascript bundle be hosted on S3. However the `index.html` is hosted on a different origin like `mywebsite.com`. In this case, the plugin generates HTML with the script be located at a relative URL. Now I'm aware that I can use the base tag to allow me to load the URLs script from the S3 origin, but that seems way all-encompassing as that would affect all relative URLs and I have other relative URLs that would acquire resources from my own origin.

Is there a way/option to make the target of the script bundle or CSS to come from a different origin?

**Comment by jantimon** [comment]
Set the webpack publicPath to your cdn.  
The html-webpack-plugin will pick it up and use it instead of realtive paths.
