### ISSUE TITLE
option base does not work

### ISSUE THREAD

**Issue by heartcase** [jantimon/html-webpack-plugin#1250]
## Expected behaviour
expected a base tag injected into the index.html

## Current behaviour
the tag did not appear

## Environment
```
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.35.0",
    "webpack-dev-server": "^3.7.2"
```
### Config

```
  plugins: [
    new HtmlWebpackPlugin({
      'base': 'http://example.com/some/page.html'
    })
  ]
```

```html
<head>
    <meta charset="UTF-8">
    <title>Webpack App</title>
  <style type="text/css">div {
  background-color: darkcyan
}</style></head>
```

**Comment by jantimon** [comment]
This feature is only included in the current beta version html-webpack-plugin 4.x

**Comment by heartcase** [comment]
> This feature is only included in the current beta version html-webpack-plugin 4.x

Oh i see, thanks!
