### ISSUE TITLE
Can't seem to work with PUG

### ISSUE THREAD

**Issue by nmaxcom** [jantimon/html-webpack-plugin#1251]
## Expected behavior

Using HMR and html-webpack-plugin, I expect a quick development experience, being able to see my *.pug files show data sent down by the controller, as in. Also, browser should auto refresh on changes (I know, this may be more on the webpack-dev-server side)

Because I'm not doing a SPA, and I think one has to spawn a new plugin object per *.pug page, I made a util.js to collect all the pages so I can do this:

```
    new HtmlWebPackPlugin({
      filename: 'index.html',
      template: './src/views/pages/index.pug',
      inject: true,
    }), ...pugPages.pages(env),
```
I've tested and it works so that's a tone of idiotic code I don't need to write.

## Current behavior

With that hack, I get to see the PUG pages. But they don't seem to receive the data sent down by the Express controller. For example:

`index.js:`
```javascript
router.get('/', (req, res, next) => {
  res.render('index', { msg: 'index page' });
  next();
});
```

`index.pug:`:
```pug
extends ../layout

block head
  include ../partials/head

block content
  h1 You ware in #{msg}
  //h1= htmlWebpackPlugin.options.title
  //p Welcome to #{htmlWebpackPlugin.options.title}
  //script.
  //  console.log(!{JSON.stringify(htmlWebpackPlugin.options)})

```
As you can tell I was trying with htmlWebpackPlugin.options.title. But if that's the only way this works, how can I get pug the data from Express? Does html-webpack-plugin make templates static?

## Environment

```
Node.js v10.16.0
darwin 16.7.0
npm 6.9.0
webpack 4.29.0
html-webpack-plugin 3.2.0
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  target: 'node',
  externals: [nodeExternals()],
  entry: {
    server: [hotModuleScript, './server.js'],
  },
  mode: env,
  output: {
    filename: '[name]-[hash:7].bundle.js',
    path: path.resolve(__dirname, './dist'),
    publicPath: '/',
  },
  devServer: {
    clientLogLevel: 'debug',
    // contentBase: '/', Only for static files
    overlay: true,
    hot: true,
    stats: { colors: true },
  },
  devtool: 'eval', // Very fast, may not be accurate
  // devtool: 'eval-source-map', // Not as fast but accurate
  module: {
    rules: [js, css, sass, images, pug],
  },
  plugins: [
    new HtmlWebPackPlugin({
      filename: 'index.html',
      template: './src/views/pages/index.pug',
      inject: true,
    }), ...pugPages.pages(env), // ...pugPages.pages(env, 'blog'),
    new webpack.HotModuleReplacementPlugin(), // Enable HMR
    new webpack.NoEmitOnErrorsPlugin()],
};

```

Copy your template file if it is part of this issue:

```html
extends ../layout

block head
  include ../partials/head

block content
  h1 You ware in -> #{msg}
  //h1= htmlWebpackPlugin.options.title
  //p Welcome to #{htmlWebpackPlugin.options.title}
  //script.
  //  console.log(!{JSON.stringify(htmlWebpackPlugin.options)})

```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

I made a leaner branch with everything in place just for the bonus points! Here it is:
 https://github.com/nmaxcom/Express-pug-webpack

**Comment by jantimon** [comment]
You are trying to use the html-wegpack-plugin as a pug-express template genetator.

You will probably have two different template languages and to set object:false to get it to work however HMR can’t help you here as the html page is not a module

**Comment by nmaxcom** [comment]
Thanks for replying, Jan

All my frontend is pug+css+js. I don't think I understood you well. You mean I should tell html-webpack to convert pug to html in memory (the two templates?).
I get that HMR can't help with the frontend, but I thought by using webpack-dev-middleware and this plugin, the frontend should refresh, shouldn't it?

**Comment by jantimon** [comment]
Unfortunately hot-module-replacement will work only for js and css.

Maybe I misunderstood your intention.  
Where do you want the pug rendering to happen - during build (where you can use `#{htmlWebpackPlugin.options.title}`) or during express delivering (where you can use `#{msg}`)?

**Comment by nmaxcom** [comment]
I don't want it to render to html. Meaning I need a dynamic template just like pug to dynamically load/show data directly from the server (probably coming from the db).

That's something that has confused me a lot. Any way I try using webpack and its plugins to speed up development seem like they want to flatten pug to html one way or the other, which in my head would make using pug and other engines pointless. Is that so?

To answer your question, I'm trying to use `#{msg}` and some form of fullstack live reload.

Thank you for helping, Jan.

**Comment by jantimon** [comment]
So you want to generate a dynamic pug template with webpack?

**Comment by nmaxcom** [comment]
I want to use the dynamical pug template with a live reload after any changes to the codebase, yeah.

**Comment by jantimon** [comment]
Although this might theoretically be possible with a lot of work you might be happier if you just use a dev environment which can already provide all features you are looking for.

Take a look at for example next.js https://www.youtube.com/watch?v=IkOVe40Sy0U
It is simple to start - copy your markup into a file and you are done. It has live reload, express server side rendering and frontend bundling.

The only difference is the template language.
