### ISSUE TITLE
Outdated 'inject: false' readme.md

### ISSUE THREAD

**Issue by theFra985** [jantimon/html-webpack-plugin#1253]
In readme description [here](https://github.com/jantimon/html-webpack-plugin/tree/master/examples/custom-insertion-position) is written the usage of `htmlWebpackPlugin.tags.headTags` when the `tags` property is undefined

**Comment by jantimon** [comment]
Sorry for this - hopefully we will be able to release 4.x soon

**Comment by andrewplummer** [comment]
For me with the latest version `htmlWebpackPlugin` itself is undefined (just when installing as shown in the readme)

**Comment by jantimon** [comment]
You can see an example for it here:

https://github.com/jantimon/html-webpack-plugin/blob/35a154186501fba3ecddb819b6f632556d37a58f/examples/custom-insertion-position/index.ejs#L1-L12

You have to use [html-webpack-plugin 4.x](https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-beta.8) or newer

**Comment by andrewplummer** [comment]
Oh I see, it's a beta version. Well considering npm won't install that by default, maybe a note there might be of help... just an idea.
