### ISSUE TITLE
Url of chunk filenames are not `urlencoded`

### ISSUE THREAD

**Issue by zbigg** [jantimon/html-webpack-plugin#1254]
## Expected behaviour

URI of files in emitted HTML should be "urlencoded".

## Current behaviour

URI of files in emitted to HTML as is, with no visible encoding.

### Config

```js
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
    context: __dirname,
    entry: {
        "app+foo": "./index.js",
    },
    plugins: [
        new HtmlWebpackPlugin()
    ]
}
```

Expected that emitted `<script>` tag contains `src="app%2bfoo.js"`.
But, we see `src="app+foo.js"`, which points at "app foo.js" (space inside).

## Relevant Links

- Repro: https://github.com/zbigg/hwp-urlencode

## Environment

```
html-webpack-plugin@3.2.0 
webpack@4.38.0 
```

**Comment by jantimon** [comment]
Hey @zbigg thanks for your feedback!

This is the part where the asset path is build up and probably the place where we could also encode:

https://github.com/jantimon/html-webpack-plugin/blob/34d8aa572c7acc59c26f3b5d15bf489a07aa4c24/index.js#L607

We should also try how this behaves for output configurations which contain a slash:

```
 output: {
       filename: 'folder/prefix+[name].bundle.js'
},
```

**Comment by zbigg** [comment]
@jantimon With such good hint, it should be easy to add. I'll look into making PR for this.
