### ISSUE TITLE
Please update the Readme for "filename" property in webpack.config.js 

### ISSUE THREAD

**Issue by damienromito** [jantimon/html-webpack-plugin#1259]
As resolved in this issue (https://github.com/jantimon/html-webpack-plugin/issues/895), the user report a syntax error in the readme. 
line 196
```js
      fileName: 'test.html',
```
and not 
```js
      filename: 'test.html',
```

Please update the readme or the property syntax "filename" looks better.

**Comment by jantimon** [comment]
I am not sure what you mean - Can you please create a pull request?
