### ISSUE TITLE
`html-minifier` uses `uglify-js` what doesn't support ecma6+

### ISSUE THREAD

**Issue by evilebottnawi** [jantimon/html-webpack-plugin#1262]
## Expected behaviour

Minify js in ecma6+

## Current behaviour

https://github.com/webpack-contrib/terser-webpack-plugin/issues/114

## Environment

No matter

### Config

No matter

## Relevant Links

https://github.com/kangax/html-minifier/blob/gh-pages/package.json#L63

## Additional context

honestly, I don’t even know how best to fix it, maybe we’ll create our own module for minification, but it may be overhead, maybe we should raise this issue `html-minifier`, any ideas?

**Comment by jantimon** [comment]
@evilebottnawi I asked the `html-minifier` maintainers to upgrade to terser - what exactly is happening right now? Is es6 code just ignored or is it causing errors?

**Comment by evilebottnawi** [comment]
@jantimon error, whaen people use es6 code

**Comment by evilebottnawi** [comment]
@jantimon i have idea, maybe i can create hook inside `terser-webpack-plugin` and you will use hook for js minification, it is allow to use do better integration with terser?

**Comment by jantimon** [comment]
`html-webpack-plugin` 4.0.0-beta.11 switched to `html-minifier-terser`
