### ISSUE TITLE
minify should ignore environment variables

### ISSUE THREAD

**Issue by stuck1233333** [jantimon/html-webpack-plugin#1264]
## Expected behaviour

Tell us what you would expect the html-webpack-plugin should.

In production, html-webpack-plugin should not minify environment variables.

## Current behaviour

Tell us what the html-webpack-plugin does instead.

html-webpack-plugin minifies environment variables:
process.env.SERVER_URL || "https://google.com" turns into undefined || "https://google.com";

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
new HtmlWebpackPlugin({
      template: 'app/index.html',
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: false,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
      cache: false,
      inject: true,
    })
```

Copy your template file if it is part of this issue:

const ROOT_URL = process.env.SERVER_URL || "https://google.com";

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

**Comment by jantimon** [comment]
Sorry I having a hard time to reproduce the error.

Could you please show a little bit more of your template?

**Comment by stuck1233333** [comment]
Absolutely--in package.json our command is: "start:prod": "cross-env NODE_ENV=production node server".

We run SERVER_URL=https://github.com yarn run start:prod but the ROOT_URL is still "https://google.com"

Here's more of the config:
`module.exports = require('./webpack.base.babel')({
  mode: 'production',

  // In production, we skip all hot-reloading stuff
  entry: [path.join(process.cwd(), 'app/app.js')],

  // Utilize long-term caching by adding content hashes (not compilation hashes) to compiled assets
  output: {
    filename: '[name].[chunkhash].js',
    chunkFilename: '[name].[chunkhash].chunk.js',
  },

  optimization: {
    minimize: true,
    nodeEnv: 'production',
    sideEffects: true,
    concatenateModules: true,
    splitChunks: { chunks: 'all' },
    runtimeChunk: true,
  },

  plugins: [
    // Minify and optimize the index.html
    new HtmlWebpackPlugin({
      template: 'app/index.html',
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: false,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
      cache: false,
      inject: true,
    }),
`

**Comment by jantimon** [comment]
I can't see where you are using `SERVER_URL` is it part of your index.html?

**Comment by stuck1233333** [comment]
It's in a .ts file that I import in app.js

**Comment by jantimon** [comment]
How is this related to the html-webpack-plugin? The minification only affects the html code

**Comment by stuck1233333** [comment]
That is a good question. When I set minify to false, I can use the SERVER_URL variable. When i set minify to 
```
 minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: false,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
```
The SERVER_URL variable gets replaced. This version uses Terser Webpack Plugin (https://github.com/webpack-contrib/terser-webpack-plugin) for minification
