### ISSUE TITLE
Ability to pass query string from dictionary to every injected chunk

### ISSUE THREAD

**Issue by iongion** [jantimon/html-webpack-plugin#1267]
**Is your feature request related to a problem? Please describe.**
Currently, for cache busting, developer uses hashes as part of the file name. This method causes problems because in deployment scenarios where files are copied to a remote web location, they get accumulated instead of overwritten.

**Describe the solution you'd like**
Ability to pass query string arguments to every injected chunk.
This would allow us to pass version(but not only) of our choice to requested files.

**Describe alternatives you've considered**
There is no alternative. Maybe using a custom template, but it is very hard to get that right. And whenever html-webpack-plugin will update, the template should be updated. Better to have an option key with this.

**Additional context**
Currently, this is by-passed by performing first a take down of files at remote location(such as S3), followed by a re-upload. This introduces additional deployment time.

This issue is asking kind of the same thing https://github.com/jantimon/html-webpack-plugin/issues/811

**Comment by jantimon** [comment]
Right now the recommended way is using `[contenthash]` as part of the filename as this will bust the cache only if the contents of the file changed.  
This allows even partial cache hits for every new release.

Right now there are some alternatives:

- Disable `inject:true` and handle the script/link injection by yourself. This api changes very very rarely and if changed upgrading is done within minutes or at max within some hours
- Enable the `hash` option which will append a hash to the querystring
- Write a plugin for the html-webpack-plugin which adds such a hash
