### ISSUE TITLE
EJS unescape delimiter is wrong

### ISSUE THREAD

**Issue by aminpaks** [jantimon/html-webpack-plugin#1268]
## Expected behaviour

According to [EJS project](https://github.com/tj/ejs#features) `<%- VAR %>` should keep the variable contents unescaped.

## Current behaviour

The escape and unescape behaviours are inverse.

`<%- ESCAPED_VAR %>`
`<%= UNESCAPED_VAR %>`

## Environment

Running on MacOS using Node 12.0 and Webpack 4.0
Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
Node.js v12.10.0
darwin 18.7.0
npm 6.11.3
webpack@4.36.1
html-webpack-plugin@4.0.0-beta.5 
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  entry: 'app.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  module: {
    rules: [
      ...
    ]
  }
  plugins: [
      new HtmlWebpackPlugin({
        template: 'static/index.ejs',
        templateParameters: {
          SCRIPTS: '<script>console.log("check");</script>'
        }
      }),
    ...
  ]
}
```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
       <%- SCRIPTS %>
    </body>
</html>
```

**Comment by jantimon** [comment]
Hey @aminpaks 

you are not limited to the build in lodash template loader.  
Feel free to use any other loader (e.g. ejs jsx hbs blueimp ... ) which fits your needs.

Please let me know if that helps

**Comment by aminpaks** [comment]
I think I misunderstood the documentation. I thought the default loader internally is EJS.
So according to [this example](https://github.com/jantimon/html-webpack-plugin/blob/master/examples/pug-loader/webpack.config.js) should I just add `ejs-loader` to rules?

**Comment by jantimon** [comment]
The fallback loader which kicks in if you don't use any other loader uses the https://lodash.com/docs/4.17.15#template which uses a ejs syntax:

https://github.com/jantimon/html-webpack-plugin/blob/6de319b48e661477a0c229ef48dd0f893cf3aa1d/lib/loader.js#L26

I haven't used the `ejs-loader` by myself but it looks like a good choice 👍

**Comment by aminpaks** [comment]
@jantimon Thanks for reply. I will try the `ejs-loader` and hopefully itll be ok :)

**Comment by jantimon** [comment]
Here is a online demo:
https://codesandbox.io/s/html-webpack-plugin--ejs-loader-ienkk
