### ISSUE TITLE
Prefix for links

### ISSUE THREAD

**Issue by SergiOn** [jantimon/html-webpack-plugin#1271]
Please, add support a prefix for links.
I would like to have the possibility to change the path in the template for JS, CSS chunks.
It's helpful when I use CDN. In this case, I can specify another domain name.

**Comment by jantimon** [comment]
Hey @SergiOn 

thanks for your request! :)  
I believe this should already be possible right now without any changes.

The publicPath setting from webpack allows using cdns.  
If we would add it only for the html-webpack-plugin you couldn't use cdns for dynamic imports.

**Comment by SergiOn** [comment]
Hello @jantimon 

Thank you for explaining.
I got your point.
It looks like I missed this solution in webpack.
Thanks for your indirect help to prevent a problem in my application :)

I will close this request and PR.
