### ISSUE TITLE
there is not support for googletagmanager script

### ISSUE THREAD

**Issue by rajanmagar** [jantimon/html-webpack-plugin#1273]
**Additional context**
We should implement support for googletagmanager or other analytical script by following the web best practice i.e. script with defer or async.

**Comment by jantimon** [comment]
Have you tried adding it to your template?

**Comment by rajanmagar** [comment]
> Have you tried adding it to your template?

Yes i did for my spa but i facing some problem in mpa.

**Comment by jantimon** [comment]
Sorry I have no idea how I can help you with that.
