### ISSUE TITLE
Ability to access just chunk names in template variables

### ISSUE THREAD

**Issue by manatarms** [jantimon/html-webpack-plugin#1274]
I have a situation where my assets are hosted in a different directory structure than my local project due to legacy reason. These assets get proxied through a webserver to the correct locations. 

However template generation requires a bunch of logic to clean out the paths generated by the plugin. There is no easy way to replace the paths for the injected assets AFAICT.

It would be nice to have just the filenames without the path inorder.

For example
Right now I need to do this to get the name of the entry file without the path
`<%= htmlWebpackPlugin.files.chunks.head.entry.replace(/^.*[\\\/]/, '') %>`

It would be nice to just do something like 
`<%= htmlWebpackPlugin.files.chunks.head.entry.name %>`

This is a great plugin, thank you for all the work!

**Comment by jantimon** [comment]
This can be done with the template variables like shown in this example: 
https://github.com/jantimon/html-webpack-plugin/tree/master/examples/template-parameters
