### ISSUE TITLE
Can dev-server support use cached files？

### ISSUE THREAD

**Issue by sinbadmaster** [jantimon/html-webpack-plugin#1276]
In the multiple pages project，i used html-webpack-plugin-for-multihtml option ——multihtmlCache to cache pages that solved HMR slowly。

But when restart dev-server it took major time on 94% asset optimization。

 **SMP  ⏱
General output time took 12 mins, 16.72 secs

 SMP  ⏱  Plugins
HtmlWebpackPlugin took 11 mins, 20.52 secs**

**Comment by jantimon** [comment]
Finally the new version with improved caching is out:

https://dev.to/jantimon/html-webpack-plugin-4-has-been-released-125d
