### ISSUE TITLE
Child template compilation hash overriding module [hash]

### ISSUE THREAD

**Issue by ruimarinho** [jantimon/html-webpack-plugin#1279]
## Expected behaviour

When using the following output configuration:

```
  output: {
    filename: '[hash]/[name].js',
    path: path.join(__dirname, 'public')
  }
```

I was expecting `[hash]` to be the module hash as generated by web pack. However, the following call to `assetPath` to replace the file's placeholders (`[hash]/index.html`) is using the child's template hash instead:

https://github.com/jantimon/html-webpack-plugin/blob/15ad0d260443edfdcc953fa08c675c90c063bac7/lib/compiler.js#L264-L267

At this stage, I am not entirely sure we can have access to compilation hash (i.e. the module hash) since this a tap on the `make` hook, but at least in my use case, this behavior appears to be incorrect.

## Current behaviour

The result is that on everywhere plugin I use `[hash]`, the output is correctly referring to the module hash and every assets is copied to the `[hash]/` directory as expected. Tried with v3 and v4 beta of this plugins with similar outcomes - v4 is actually better as v3 used to generate a new child hash for `[hash]` for each html file referenced. In v4, that is down to one.

On v4, there seems to be a regression though as the resulting index.html will have assets with the filename placeholder in it (literally `[hash]/abcde1234sha.png`) when working in conjunction with `url-loader`.

Before working on a reproduction scenario, I would like to understand if any of this is expected, possible workarounds or where to dig further in the code.

Thanks!

**Comment by jantimon** [comment]
Hey @ruimarinho 

thanks for reporting - this is definitely not the intended behavior however changing it will probably require a complicated solution - what if you try to use a copy plugin?

**Comment by ruimarinho** [comment]
You mean in terms of the expected behaviour?

**Comment by jantimon** [comment]
Yes as it allows to copy files
