### ISSUE TITLE
Avoid calling hooks you don't own

### ISSUE THREAD

**Issue by sokra** [jantimon/html-webpack-plugin#1287]
## Expected behaviour

Hooks (tapable) should only be called by the class that created them.

## Current behaviour

html-webpack-plugin calls hooks from the MainTemplate:
https://github.com/jantimon/html-webpack-plugin/blob/655cbcdb9a81db774dd1a66fada085dd6c20dee0/lib/compiler.js#L182
https://github.com/jantimon/html-webpack-plugin/blob/655cbcdb9a81db774dd1a66fada085dd6c20dee0/lib/compiler.js#L264

Use `mainTemplate.getAssetPath` or `compilation.getPath` (better) instead

## Environment

```
html-webpack-plugin@4.0.0-beta.8
```

## Relevant Links

- tapable API: https://github.com/webpack/tapable/#hookhookmap-interface
  - Only use public API. Protected API should only be used by the hook creating class itself.

## Additional context

Using protected or private API hinders refactoring and increases the change of breaking on internal changes.

**Comment by jantimon** [comment]
Hey @sokra

thanks for the feedback.

This pattern was used by multiple plugins (it was originally copied from webpack core code along time ago).

The idea is to compile hashes inside file names exactly the way webpack is doing it.

What would be the correct way to call the hook?  
Should we switch to https://webpack.js.org/api/compilation-hooks/#assetpath ?
