### ISSUE TITLE
请问4.0大约什么时间能更新成正式版本

### ISSUE THREAD

**Issue by amazingliyuzhao** [jantimon/html-webpack-plugin#1290]
请问4.0大约什么时间能更新成正式版本？

**Comment by chanble** [comment]
https://github.com/jantimon/html-webpack-plugin/pull/953#issuecomment-429716203
10月底

**Comment by amazingliyuzhao** [comment]
真的吗？十月底，这是官方消息吗

**Comment by amazingliyuzhao** [comment]
@chanble 真的吗？十月底，这是官方消息吗

**Comment by Leedehai** [comment]
@amazingliyuzhao https://github.com/jantimon/html-webpack-plugin/pull/953#issuecomment-429716203

**Comment by chanble** [comment]
@Leedehai  Oh,  我太粗心了。。差点误导人
