### ISSUE TITLE
Preventing link & script tags from being automatically added

### ISSUE THREAD

**Issue by thibka** [jantimon/html-webpack-plugin#1297]
I need to use HtmlWebpackPlugin with multiple html files, with an option for each of them allowing me to control whether a `<link>` & a `<script>` tags will be added or not.
The reason is that I want my final build to load html files dynamically with ajax. As thoses html files are meant to be inserted in a main DOM, I need them to be clean of any automatically added tags.

Something like this would be ideal:
```javascript
new HtmlWebpackPlugin({
	template: './src/index.html',
	filename: './index.html'
}),
new HtmlWebpackPlugin({
	template: './src/somepage.html',
	filename: './somepage.html',
	linkTag: false, // here!
	scriptTag: false // and here!
})
```
Or maybe there's already a way to do that?

Thanks :)

**Comment by jantimon** [comment]
You can do this with `inject:false`
