### ISSUE TITLE
Templating Not Working

### ISSUE THREAD

**Issue by ChrisBup** [jantimon/html-webpack-plugin#1308]
## Expected behaviour

I'm trying to follow [this example](https://medium.com/dailyjs/inserting-variables-into-html-and-javascript-with-webpack-80f33625edc6), but am unable to get `HtmlWebpackPlugin` templating to work. I expect adding `<%= htmlWebpackPlugin.options.header %>` to my template file would output "Webpack Demo Header" to the browser.

## Current behaviour

The page is actually displaying `<%= htmlWebpackPlugin.options.header %>` in browser.

## Environment

OS: Mac Mojave 10.14.6 
Node.js version: 10.12.0
npm version: 6.4.1
webpack version: 4.41.2
html-webpack-plugin: 3.2.0

## Config

I have this in `webpack.common.js`:
```js
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  entry: {
    main: "./src/index.js",
    vendor: "./src/vendor.js"
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/template.html",
      title: "Webpack Demo Title",
      header: "Webpack Demo Header"
    })
  ],
  module: {
    rules: [
      {
        test: /\.html$/,
        use: ["html-loader"]
      },
      {
        test: /\.(svg|png|jpg|gif)$/,
        use: {
          loader: "file-loader",
          options: {
            name: "[name].[hash].[ext]",
            outputPath: "imgs"
          }
        }
      }
    ]
  }
};
```

And combining that using  `webpack-merge` with this in `webpack.dev.js`:
```js
const path = require("path");
const common = require("./webpack.common");
const merge = require("webpack-merge");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = merge(common, {
  mode: "development",
  output: {
    filename: "[name].bundle.js",
    path: path.resolve(__dirname, "dist")
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/template.html"
    })
  ],
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: [
          "style-loader", // runs last: injects styles into DOM
          "css-loader", // runs second: translates CSS into CommnJS
          "sass-loader" // runs first: copiles Sass into CSS
        ]
      }
    ]
  }
});
```

And I have this in `template.html`:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body class="container">
    <h1><%= htmlWebpackPlugin.options.header %></h1>
    <img src="./assets/webpack.svg" />
  </body>
</html>
```

Thanks.

**Comment by mastilver** [comment]
Could you try removing:
```
      {
        test: /\.html$/,
        use: ["html-loader"]
      },
```

**Comment by jantimon** [comment]
You didn't specify header in the plugin options.

Try:

```
new HtmlWebpackPlugin({
      template: "./src/template.html",
      header: 'Some Text'
    })
```

**Comment by ChrisBup** [comment]
When I remove this:
```
{
  test: /\.html$/,
  use: ["html-loader"]
},
```
I get empty `h1` tags and broken image links:

![Screen Shot 2019-11-19 at 1 47 58 PM](https://user-images.githubusercontent.com/7212504/69176482-cb18d180-0ad3-11ea-83d5-9b17d9900c3c.png)


And no change when I specify a header. Note that I had already specified it in `webpack.common.js` and am using `webpack-merge` to combine that with `webpack.dev.js` which I thought would mean that the header was already present.
