### ISSUE TITLE
missing dependency (html-minifier)

### ISSUE THREAD

**Issue by obartra** [jantimon/html-webpack-plugin#1311]
## Expected behaviour

Webpack build succeeds

## Current behaviour

Webpack build fails, requiring "html-minifier" from "html-webpack-plugin"

```
ERR!   Error: Cannot find module 'html-minifier'
ERR!   Require stack:
ERR!   - /myproject/node_modules/html-webpack-plugin
```

Manually installing `html-minifier` fixes the issue

## Environment

On `html-webpack-plugin@4.0.0-beta.10`, `webpack@4.41.2`, `node@12.13.0`, `npm@6.12.0`

### Config

NA

## Relevant Links

NA

## Additional context

I suspect adding `html-minifier` to `html-webpack-plugin` dependencies would fix the issue, happy to contribute if that's the desired change

**Comment by jantimon** [comment]
Thanks for the heads up 👍 will take a look

**Comment by jantimon** [comment]
Unfortunately I introduced this with #1309 - however all builds were green 🤔

**Comment by obartra** [comment]
My guess is that it's because `html-loader` is included as a dev dependency which installs it but it's not available by the package when published (only dependencies are).

You should be able to repro this issue if instead of `npm ci` or `npm i` you run `npm i --production`

**Comment by jantimon** [comment]
Hey @obartra can you verify that it works now?

**Comment by obartra** [comment]
I was using `html-webpack-plugin` through storybook so I don't have specific control on the version but regenerating the package-lock.json succeeds now without `html-minifier` as an explicit dependency so I think that did the trick!

Thanks so much for the quick response 🎉

**Comment by jantimon** [comment]
Thanks for your feedback 👍👍
