### ISSUE TITLE
deprecate webpack contrib html-loader in favor this plugin/loader

### ISSUE THREAD

**Issue by evilebottnawi** [jantimon/html-webpack-plugin#1314]
Sorry for removing issue template, i want to deprecated https://github.com/webpack-contrib/html-loader in favor this plugin/loader. 

I would like to know whether it is possible:
- to use loader without plugin 
- support parsing `src`/`srcset`
- interpolation
- export as ES modules?

Thanks for great plugin.

**Comment by quinnjr** [comment]
Unless I'm mistaken, doesn't this plugin add a number of DOM elements that are unnecessary for those of us who use `html-loader` to generate html partials?

**Comment by jantimon** [comment]
I am with @quinnjr 👍
