### ISSUE TITLE
Only one chunk is added to html using beta-11

### ISSUE THREAD

**Issue by wintercounter** [jantimon/html-webpack-plugin#1315]
## Expected behaviour

All necessary chunks added.

## Current behaviour

We were using beta-8. Working fine. Updating to 11 led us only having 1 chunk added to the HTML, no matter what. Try setting maxSize to have multiple chunks.

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  optimization: {
    splitChunks: {
       maxSize: 10000
    }
  }
}
```

**Comment by jantimon** [comment]
Thanks so much for your feedback I'll try to find out what could caused this

**Comment by jantimon** [comment]
Couldn't reproduce :(

Can you please create a reproduction example or even a failing unit test?

My config:

```js
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: './example.js',
  output: {
    filename: 'bundle.js'
  },
  module: {
    rules: [
      { test: /\.css$/, loader: 'style-loader!css-loader' },
    ]
  },
  plugins: [
    new HtmlWebpackPlugin()
  ],
  optimization: {
    splitChunks: {
       maxSize: 100000
    }
  }
};
```

Result with latest version:

<img width="483" alt="split" src="https://user-images.githubusercontent.com/4113649/71669223-3ceb6880-2d6c-11ea-9d8f-45a25b2b7877.png">

As you can see it includes: `<script src="0.bundle.js"></script><script src="bundle.js"></script>`

**Comment by wintercounter** [comment]
I'll try to reproduce this asap, my time is limited now. I'm having this issue on a pretty large project and I think it wont be easy to reproduce. Btw it seems like I forgot to mention that it only affects prod builds for us.

**Comment by jantimon** [comment]
Feel free to reopen if you have time to provide more information
