### ISSUE TITLE
Wrong / outdated template description?

### ISSUE THREAD

**Issue by DanielRuf** [jantimon/html-webpack-plugin#1318]
## Expected behaviour

`src/index.ejs` is used.

## Current behaviour

`default_index.ejs` is used

## Environment

```
npm --version
npm ls webpack
npm ls html-webpack-plugin
Node.js v10.16.3
darwin 18.7.0
6.13.1
patch-cutter-browser@1.0.0 /Users/danielruf/projects/patch-cutter-browser
└── webpack@4.41.2 

patch-cutter-browser@1.0.0 /Users/danielruf/projects/patch-cutter-browser
└── html-webpack-plugin@3.2.0 
```

**Comment by jantimon** [comment]
The documentation is already addressing html-webpack-plugin 4.

I didn't expect it to take it so long to release version 4.

**Comment by DanielRuf** [comment]
Ok so I guess I can close this issue?

Personally I would expect that `master` contains only released (stable) versions and not the beta version which is currently not the version shown on npmjs (beta / next).

https://github.com/jantimon/html-webpack-plugin/releases/tag/v3.2.0

**Comment by DanielRuf** [comment]
At least there is also some cleanup needed (merged branches can be safely deleted imo) =)

https://github.com/jantimon/html-webpack-plugin/branches
