### ISSUE TITLE
`options.chunks` can support more matching formats, such as: RegExp, Function

### ISSUE THREAD

**Issue by zwlijun** [jantimon/html-webpack-plugin#1319]
**Is your feature request related to a problem? Please describe.**
In VUE, when I use multi-page mode, "chunks" are not injected into HTML. 

**Describe the solution you'd like**
I checked the source code of the installation package and learned from the source code that the current filtering of chunks is an exact match. I hope I can improve the current method and add more matching methods, such as:

```js
  filterChunks (chunks, includedChunks, excludedChunks) {
    return chunks.filter(chunkName => {
      // Skip if the chunks should be filtered and the given chunk was not added explicity
      if (Array.isArray(includedChunks) && includedChunks.indexOf(chunkName) === -1) { // chunks: Array
        return false;
      } else if (includedChunks instanceof RegExp) { // chunks: RegExp
        return includedChunks.test(chunkName);
      } else if (typeof includedChunks === 'function') { // chunks: Function
        return includedChunks(chunkName);
      }
      // if (Array.isArray(includedChunks) && includedChunks.indexOf(chunkName) === -1) {
      //   return false;
      // }

      // Skip if the chunks should be filtered and the given chunk was excluded explicity
      if (Array.isArray(excludedChunks) && excludedChunks.indexOf(chunkName) !== -1) { // chunks: Array
        return false;
      } else if (excludedChunks instanceof RegExp) { // chunks: RegExp
        return !excludedChunks.test(chunkName);
      } else if (typeof excludedChunks === 'function') { // chunks: Function
        return excludedChunks(chunkName);
      }
      // if (Array.isArray(excludedChunks) && excludedChunks.indexOf(chunkName) !== -1) {
      //   return false;
      // }
      // Add otherwise
      return true;
    });
  }
```
 

**Describe alternatives you've considered**

**Additional context**

**Comment by zwlijun** [comment]
#1320

**Comment by bensampaio** [comment]
I was just now looking for a solution for this same problem. @zwlijun any updates on your PR?

**Comment by zwlijun** [comment]
> I was just now looking for a solution for this same problem. @zwlijun any updates on your PR?

yeah, I rewrite the filterChunks method and updated in PR.

**Comment by jantimon** [comment]
Can we update this to the current major version?

**Comment by zwlijun** [comment]
@jantimon yeah, I hope so. thanks very much.

**Comment by vjpr** [comment]
Need this too for Module Federation to work. I need to exclude `remoteEntry.js` chunk, but its name is something like `RemoteFoo`.  I want to be able to exclude all chunks starting with `Remote`.
