### ISSUE TITLE
this will override the devserver contentBase?

### ISSUE THREAD

**Issue by nicewahson** [jantimon/html-webpack-plugin#1322]
I am doing some test case, and webpack.config.js is below
<pre>
const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
	devtool: false,
	entry: path.join(__dirname, './src/index.js'),
	output: {
		path: path.resolve(__dirname, 'static'),
		filename: 'bundle.js',
		// publicPath: '/'
	},
	mode: 'development',
	module: {
		rules:[
			{
				test: /\.js$/,
				use: './test-loader.js'
			}
		]
	},
	resolveLoader: {
		// modules: [__dirname]
	},
	devServer: {
		port: 9000,
		// contentBase: false,
		contentBase: false,
		publicPath: '/',
	},
	// plugins: [
	// 	new HtmlWebpackPlugin()
	// ]
}
</pre>
and i found that the contentBase setting in devServer doesn't work, but when i comment out the plugins settings, it works. Can anyone explain this or there's something wrong with my usage?
Hoping for your reply.

**Comment by jantimon** [comment]
What do you mean by "works"''?
