### ISSUE TITLE
htmlWebpackPlugin is not defined (using templateParameters and this variable inside template)

### ISSUE THREAD

**Issue by ZerdoX-x** [jantimon/html-webpack-plugin#1326]
## Expected behaviour

Ordinary work using svg sprites injection [interop svg-sprite-loader with html-webpack-plugin](https://github.com/JetBrains/svg-sprite-loader/tree/master/examples/interop-with-html-webpack-plugin) and templateParameters

## Current behaviour

Exception if I use templateParameters in my webpack config: htmlWebpackConfig variable becomes undefined, so I can't use sprites properly. I guess I also can't use "title" property with templateParameters, it's not svg problem..

## Environment

```
Node.js v10.16.3
linux 5.0.0-37-generic
6.13.2
└── webpack@4.41.2
├── html-webpack-plugin@3.2.0 
└─┬ svg-sprite-loader@4.1.6
  └── html-webpack-plugin@3.2.0 
```

## Relevant Links

- [reproduced-bug repo](https://github.com/ZerdoX-x/html-webpack-plugin_bug-reproduced)
- [ZerdoX-x/webpack-template](https://github.com/ZerdoX-x/webpack-template) //my template where I ran into this problem

## Additional context

I found #323 issue, but moving to 4.0.0 didn't give me good results, same result, but it works worse, it don't even bundling with HtmlBeautifyPlugin, same result if I remove it from my config.

**Comment by ZerdoX-x** [comment]
will add reproduced repo soon

**Comment by ZerdoX-x** [comment]
https://github.com/ZerdoX-x/html-webpack-plugin_bug-reproduced
`npm run build`

**Comment by dudekaa** [comment]
Hi

I was having same issue and after half-day digging I found reason. It's implemented this way as @jantimon explained in #830 at the end

> If it’s empty it would be the same like today (just without the stats)
If it’s a function the current behavior with get stats could be reproduced manually.
If it’s an object it contains only the values of that given object.

So u have to use function, e.g.

```javascript
templateParameters: (compilation, assets, assetTags, options) => {
    return {
        compilation,
        webpackConfig: compilation.options,
        htmlWebpackPlugin: {
            tags: assetTags,
            files: assets,
            options,
        },
        someExtraParam: 'yay!',
    };
},
```

Hope it helps!

Also #1323 is probably duplicate of this issue? ( as react-scripts uses `title` in template as `<%= htmlWebpackPlugin.options.title %>`? )

**Environment**
Linux
```
$ node --version
v10.16.3
```

```
$ yarn --version
1.21.1
```

```
$ yarn why webpack
yarn why v1.21.1
[1/4] Why do we have the module "webpack"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "webpack@4.41.0"
...
Done in 2.32s.

$ yarn why html-webpack-plugin
yarn why v1.21.1
[1/4] Why do we have the module "html-webpack-plugin"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "html-webpack-plugin@4.0.0-beta.11"
...
Done in 2.15s.
```

**Template**
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body <%= bodyStyle ? 'style="' + bodyStyle + '"' : '' %>>
    <div id="root"></div>
  </body>
</html>
```

**Error**
```
Html Webpack Plugin:

  ReferenceError: htmlWebpackPlugin is not defined
  
  - index.html:100 
    /home/nost/projekty/javascript-4.2.0/public/index.html:100:11
  
  - index.html:105 ./node_modules/html-webpack-plugin/lib/loader.js!./public/index.html.module.exports
    /home/nost/projekty/javascript-4.2.0/public/index.html:105:3
  
  - index.js:415 templateParamsPromise.then
    [javascript-4.2.0]/[html-webpack-plugin]/index.js:415:16
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick

**Comment by ZerdoX-x** [comment]
Thank you very much. Strange thing.. I think it's very common that you use templateParameters and title (or svg injection in my case), and you should add it to readme or another example in examples folder so people could easily find it out. Thanks again!

**Comment by dudekaa** [comment]
good thinking. done #1329

**Comment by jantimon** [comment]
There was also a great idea to improve this by @charlyzeng https://github.com/jantimon/html-webpack-plugin/pull/1263
