### ISSUE TITLE
vue-cli3  & html-webpack-plugin 4.x    How to inject cdn dynamically?

### ISSUE THREAD

**Issue by DevinWell1ee** [jantimon/html-webpack-plugin#1333]
## Expected behaviour

in html, Can inject cdn dynamically through htmlWebpackPlugin.options

## Current behaviour

it not work

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  chainWebpack: config => {
     config
      .plugin('html')
      .use(HtmlWebpackPlugin)
      .tap(options => {
        options.cdn = ['production', 'stage'].includes(process.env.NODE_ENV) ? cdn['build'] : cdn['dev']
        return options
      })
  }
}
```

```html
<% for (var i in htmlWebpackPlugin.options.cdn&&htmlWebpackPlugin.options.cdn.js) { %>
    <script src="<%= htmlWebpackPlugin.options.cdn.js[i] %>"></script>
    <% } %>
```

i don't know if delete preload caused it . 
i delete reload, because htmlWebpackPlugin4.x  seems to be in conflict with preload

**Comment by jantimon** [comment]
Can you also change the webpack publicPath to be that cdn?

That would be picked up by the html-webpack-plugin automatically.

**Comment by lijason1121** [comment]
make sure your value of "publicPath" property in "output" is your cdn address.
```js
  output: {
    path: __dirname + '/dist',
    filename:[name].[contenthash:8].bundle.js',
    chunkFilename: [name].[contenthash:8].chunk.js', 
    publicPath: process.env.NODE_ENV === 'production' ?
      `your/cdn/address` :
      ''
  },
```

**Comment by gary-dgc** [comment]
see you [.use(HtmlWebpackPlugin)], guess you got error: [ Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('html').use(<Plugin>) first.]. if you configured multi-pages in vue.config.js, the [plug('html')] not exists in config, coz it's replaced with the multi-pages setting, to identify the html plugin name, you need to run command to list all the plugins:
```
npx vue-cli-service inspect --plugins
[
  'vue-loader',
  'define',
  'case-sensitive-paths',
  'friendly-errors',
  'html-index',
  'html-demo',
  'preload-index',
  'prefetch-index',
  'preload-oeditor',
  'prefetch-oeditor',
  'copy',
  'ThemeColorReplacer',
  'IgnorePlugin'
]

```
Now you can use following to modify the plugin options
```
      config.plugin('html-index')
        .tap(args => {
          args[0].cdn = assetsCDN
          return args
        })
      config.plugin('html-demo')
        .tap(args => {
          args[0].cdn = assetsCDN
          return args
        })
```
