### ISSUE TITLE
does not add tag in proper manner. should add as property not as name

### ISSUE THREAD

**Issue by xerosanyam** [jantimon/html-webpack-plugin#1334]
## Expected behaviour

`<meta property="og:type" content="article" />`

Tell us what you would expect the html-webpack-plugin should.

## Current behaviour
`<meta name="og:type" content="article" />`

Tell us what the html-webpack-plugin does instead.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
npm --version
npm ls webpack
npm ls html-webpack-plugin
```
```
Node.js v10.16.2
darwin 19.2.0
npm 6.13.2

├─┬ @vue/cli-plugin-babel@4.1.1
│ └── webpack@4.41.2 
├─┬ @vue/cli-plugin-eslint@4.1.1
│ └── webpack@4.41.2  deduped
└─┬ @vue/cli-service@4.1.1
  └── webpack@4.41.2  deduped

└─┬ @vue/cli-service@4.1.1
  └── html-webpack-plugin@3.2.0 
```

**Comment by jantimon** [comment]
Hey thank you for submitting a bug report 👍  
I having troubles to find out how I could reproduce this bug.  
Could you please try to create a [minimal reproduction example](https://stackoverflow.com/help/mcve) (especially remove all dependencies, loaders and plugins which are not necessary for reproduction) and attach it (with out node_modules) as a zip to this issue?
