### ISSUE TITLE
 Bug?  webpack optimization, only one asset is injected into the output file

### ISSUE THREAD

**Issue by Legends** [jantimon/html-webpack-plugin#1335]
**html-webpack-plugin v3.2:**

Will this work with v4?

## Expected behaviour
All needed js assets get injected into the output page (/dist)

## Current behaviour

When using optimizations:
```
   optimization: {
        runtimeChunk: 'single',
        splitChunks: {
            cacheGroups: {
                vendor: {
                    test: /[\\/]node_modules[\\/]/,
                    name: 'vendors',
                    enforce: true,
                    chunks: 'all'
                }
            }
        }
    },
```
Produces runtime-chunk, vendor-bundle and page-bundle, **but only the page-bundle gets injected** into the final page.

**Comment by Legends** [comment]
Somewhere in the docs, i guess it was under `SplitChunksPlugin`, I read that the `html-webpack-plugin` handles this.

And I can't find anything about it in the readme of this repo...

@jantimon

**Comment by jantimon** [comment]
By default all webpack css and js files will be added to the html file (for 3.2 and 4.x)

**Comment by Legends** [comment]
Here is the [repo](https://github.com/Legends/html-webpack-plugin-issue), nothing special is configured

**Comment by jantimon** [comment]
You excluded the chunks manually by allowing only the index chunk: `chunks: ['index'],`

**Comment by Legends** [comment]
When I remove this setting then the plugin injects also `about.js` into my` index.html` page.
Which is obviously the wrong place.

I have the following setting:

```
 entry: {
        index: './src/scripts/index/', // script for index.html
        about: './src/scripts/about/' // script for about.html
    },
```
Each of these scripts import a `common.js` file which contains all needed dependencies for the app to run. And each script additionally implements page specific logic.

When using optimization and depending what scripts/packages I will add in the future, the bundle output might change. 

So hard-coding all the needed chunks into `chunks:[]` is possible, but not nice.

**How can I tell the plugin for example:**

For filename: 'index.html' include `entry: index` and all it's dependencies, nothing else.

**Comment by wallzero** [comment]
I am experiencing a similar bug. Everything works properly in version `4.0.0-beta.8` but when I upgrade to either `4.0.0-beta.8` or `4.0.0-beta.11` my chunks are no longer written to `index.html`.

**Comment by jantimon** [comment]
This feature has never been implemented so I would be surprised if it worked for 4.0.0-beta.8.

Can you please prepare a pull request to add the dependency resolution?  
It has to be a fast call as this code would be executed for every code change.

**Comment by Legends** [comment]
I don't understand why the `chunks` property of html-webpack-plugin `options` is an array.
because :

```
 entry: {
        index: './src/scripts/index/',
        about: './src/scripts/about/'
    },
```

are application entry-points.
So in a multi-page app, every page is an entry-point, in a SPA you would have only one.

---

**Here is how I would do it for my use-case:**

```
  new HtmlWebpackPlugin({
            template: './src/layout-composition.js',
            title: 'Index-Page',
            page: 'index/index-body.ejs',
            inject: true,
            chunks: ['index'],   // here I specify my entry-chunk for this page
            filename: 'index.html'  // this is the page
        }),
```

Now in: ` compiler.hooks.emit.tapAsync('HtmlWebpackPlugin',`

Here I would fetch only chunks (`self.options.chunks`) my entry-point needs, like:

`compilation.entrypoints.get("index").chunks`

![image](https://user-images.githubusercontent.com/966368/72639012-ff3e3080-3964-11ea-92d6-0a5d83a23f8a.png)

So here we have all js and css files we need and create the assets.

What do you think?
