### ISSUE TITLE
twig syntax with ternary condition = parse error

### ISSUE THREAD

**Issue by RomainMazB** [jantimon/html-webpack-plugin#1336]
## Expected behaviour

I'm not using a twig parser because I need it to be executed by the serveur.

So I parse them with .htm extension and I just want htmlwebpackplugin to copy them as the raw src file is.

## Current behaviour
This line fail:
```terminal
<a href="{{ item.url }}" {{ item.viewBag.isExternal ? 'target="_blank"' : '' }}>`
> ERROR in   Error: Parse Error: <a href="{{ item.url }}" {{ item.viewBag.isExternal ? 'target="_blank"' : '' }}>
                  {{ item.title }}
              </a>
          {% else %}
              <span>{{ item.title }}</span>
          {% endif %}
          {% if item.items %}
              <ul>{% partial __SELF__ ~ "::items" items=item.items %}</ul>
          {% endif %}
  {% endfor %}
  
  - htmlparser.js:240 new HTMLParser
    [sng]/[html-minifier]/src/htmlparser.js:240:13
  
  - htmlminifier.js:966 minify
    [sng]/[html-minifier]/src/htmlminifier.js:966:3
  
  - htmlminifier.js:1326 exports.minify
    [sng]/[html-minifier]/src/htmlminifier.js:1326:16
  
  - index.js:316 
    [sng]/[html-webpack-plugin]/index.js:316:18
  
  - task_queues.js:94 processTicksAndRejections
    internal/process/task_queues.js:94:5
```

I replaced it with an usual condition and it worked:
`{% if item.viewBag.isExternal %} 'target="_blank"' {% endif %}`

## Environment
Node.js v12.14.1
linux 5.0.0-37-generic (Ubuntu 18.04)
npm 6.13.4
└── webpack@4.41.5 
└── html-webpack-plugin@3.2.0

### Config

Copy the minimal `webpack.config.js` to produce this issue:
My webpack.config.js is kind of huge, I'm using [a personnal tool](https://github.com/RomainMazB/octobercms-tailwindcss-boilerplate/blob/master/webpack.config.js), the HTMLWebpackPlugin is at the end of the file.

Copy your template file if it is part of this issue:

```html
{% for item in items %}
        {% if item.url %}
            <a href="{{ item.url }}" {{ item.viewBag.isExternal ? 'target="_blank"' : '' }}>
                {{ item.title }}
            </a>
        {% else %}
            <span>{{ item.title }}</span>
        {% endif %}

        {% if item.items %}
            <ul>{% partial __SELF__ ~ "::items" items=item.items %}</ul>
        {% endif %}
{% endfor %}
```

## Relevant Links

[I created a repo](https://github.com/RomainMazB/hwp-issue) so you can try by yourself

**Comment by jantimon** [comment]
Can you try to use the https://github.com/webpack-contrib/raw-loader ?

E.g. 

```
plugins: [
  new HtmlWebpackPlugin({
    title: 'Custom template',
    template: '!!raw-loader!./index.html'
  })
]
```

**Comment by jantimon** [comment]
Maybe it is the minification?

**Comment by RomainMazB** [comment]
Without minification, it works...

For now I'm ok to do without html minification (which didn't work with my project anyway, but it may be missconfigured). But I still think it shouldn't happend?

**Comment by jantimon** [comment]
The generated code is send to [html-minifier-terser](https://www.npmjs.com/package/html-minifier-terser) - html-minifier-terser will only accept valid html. 

You can see how it fails here:

https://runkit.com/embed/i2wu6duagj6z

```js
const htmlMinifierTerser = require("html-minifier-terser").minify

JSON.stringify(htmlMinifierTerser(`<html>
  
  <a href="{{ item.url }}" {{ item.viewBag.isExternal ? 'target="_blank"' : '' }}>
    My Link
  </a>
    
</html>`))
```

```
Error: Parse Error: <a href="{{ item.url }}" {{ item.viewBag.isExternal ? ' target="_blank"' : '' }}>
    My Link
  </a>
```

Unfortunately there is not much what we can do about that inside the `html-webpack-plugin`.

**Comment by RomainMazB** [comment]
Oh, didn't know about that little tool :)
I'll disable the cache system for now and will have a deeper look another day. Thanks for the informations.

Since it's not an HTMLWebpackPlugin issue, I close it :)
