### ISSUE TITLE
multi-compiler & HtmlWebpackPlugin incorrect behavior.

### ISSUE THREAD

**Issue by rendomnet** [jantimon/html-webpack-plugin#1351]
## Expected behaviour

Generating html for every compile

## Current behaviour

html generated only for some compiles and ignored for others

## Environment

html-webpack-plugin": "^3.2.0",
webpack 4.41.6
node v10.16.3
mac os

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
var config = {
    // TODO: Add common Configuration
  plugins: [
  ...
  new HtmlWebpackPlugin()
  ]
};

var fooConfig = Object.assign({}, config, {
    name: "a",
    entry: "./a/app",
    output: {
       path: "./a",
       filename: "bundle.js"
    },
});
var barConfig = Object.assign({}, config,{
    name: "b",
    entry: "./b/app",
    output: {
       path: "./b",
       filename: "bundle.js"
    },
});

// Return Array of Configurations
module.exports = [
    fooConfig, barConfig,       
];

```

**Comment by jantimon** [comment]
Can you please try if html-webpack-plugin 4.0.0 fixes this?

**Comment by miklos-eiq** [comment]
@jantimon I have the same issue, upgraded to `4.3.0` from `3.2.0`, but still couldn't make it work.
