### ISSUE TITLE
Version 4 progress tracking

### ISSUE THREAD

**Issue by PlayMa256** [jantimon/html-webpack-plugin#1353]
So we are all aware that this widely used package has been going through changes to deprecate the support for webpack 4 and also add support for the upcoming v5. Something i could not find out is a progress tracking. 

How far from being release are we and what are the features missing?

Can we keep an umbrella issue to track those out? And that also helps to define it's scope!

**Comment by ematipico** [comment]
I think first version 4 should be released (it's in beta for more than an year now) and later talk about version 5 and depreciations.

**Comment by PlayMa256** [comment]
Yes, that is the idea! Move this plugin forward! We need to make things work! Most people out there use this and depend on it!

**Comment by jantimon** [comment]
So Version 4 beta looks quite stable now and has been used by create-react-app and others
I have to summarize the changes from 3.x to 4.x and publish it
Unfortunately I hadn't enough spare time do so in the last months
I will try to push it soon so we can prepare it for webpack 5

**Comment by PlayMa256** [comment]
We will do our bests to help you out with everything! As community we won't leave you with bare hands! We got your back!

**Comment by AviVahl** [comment]
@jantimon `beta.14` is out, but isn't tagged in git or any commit?

**Comment by jantimon** [comment]
Released: https://dev.to/jantimon/html-webpack-plugin-4-has-been-released-125d
