### ISSUE TITLE
Does this work with Code Splitting? 

### ISSUE THREAD

**Issue by simkessy** [jantimon/html-webpack-plugin#1356]
I'm on version 3.2.0

I thought this plugin was useful for handling chunk splitting and injecting into each entry only the chunks which are necessary for the page/entry to run. 

But instead it seems I can only include or exclude certain entries and everything else is injected into the html?

If my code splitting generates 0.vendor.js to 10.vendor.js, this plugin will inject all n.vendor.js chunks into my entries. However what if an entry only cares about chunks 0-3 and my other entry only cares about 4-10.vendor.js? 

I thought the point of code splitting was to handle this scenario where you load only the chunks you need at the time but with this plugging that's not really possible since it injects all chunks. 

What am I missing here?

**Comment by simkessy** [comment]
I take it back. Updating to the @next version does what I expected. Why is the next version not the main version? To be the main version as is doesn't meet expectations.

**Comment by jantimon** [comment]
Actually the html-webpack-plugin 4.x is already used a lot and is close to be released as main version

**Comment by simkessy** [comment]
Sounds good, going to close this.
