### ISSUE TITLE
Rewind to: Auto filling chunks #968

### ISSUE THREAD

**Issue by elchicofrommo** [jantimon/html-webpack-plugin#1358]
Hey guys, I was trying to follow [this](https://github.com/jantimon/html-webpack-plugin/issues/968) thread here and I couldn't quite figure out how it was resolved. I'm having the same issue right now where I have multiple entry points and my splitChunks turned on for webpack, but when I put in the name of the entry point all I get is that one file and  none of it's dependencies in my generated html. What am I missing?

**Comment by jantimon** [comment]
This is (hopfully) fixed in the current beta version: https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-beta.11
