### ISSUE TITLE
html-webpack-plugin should not emit scripts with defer attr after scriptLoading is on

### ISSUE THREAD

**Issue by svltmccc** [jantimon/html-webpack-plugin#1362]
## Expected behaviour

html-webpack-plugin should emit scripts with **defer** attr after scriptLoading is on

## Current behaviour

html-webpack-plugin should not emit scripts with **defer** attr after scriptLoading is on

## Environment

Version detect emits:

```
MacOS darwin 19.3.0
Node.js v13.11.0
NPM v6.14.3

html-webpack-plugin@4.0.0-beta.14 /Users/svltmccc/Projects/html-webpack-plugin
└── webpack@4.35.2 

html-webpack-plugin@4.0.0-beta.14 /Users/svltmccc/Projects/html-webpack-plugin
└── (empty)
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
const {resolve} = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
    mode: "production",
    entry: resolve(__dirname, "src", "main.js"),
    output: {
        path: resolve(__dirname, "dist"),
        filename: "script.js",
    },
    plugins: [
        new HtmlWebpackPlugin({
            scriptLoading: "defer",
        }),
    ],
};
```

**Comment by jantimon** [comment]
Looks good to me.

Can you please show the generate html?

**Comment by svltmccc** [comment]
Thanks for your note.

Can you try to reproduce it with my test-repo? https://github.com/svltmccc/webpack-html-plugin-defer-trouble

Feel free to push anything

**Comment by jantimon** [comment]
Looks like you are using an old version:

https://github.com/svltmccc/webpack-html-plugin-defer-trouble/blob/0316532cc4dc3d4871974721f0706f6828f9ec27/package.json#L28

**Comment by svltmccc** [comment]
Oh, npm says for me **3.2.0** is actual.

Your version is **4.0.0-beta.14**. It looks like uncompleted.
Anyway, I understand only 4+ has the scriptLoading option.

Thank you!

Any thoughts when 4+ will be published like stable?
