### ISSUE TITLE
access compilation hash value 

### ISSUE THREAD

**Issue by z0y1** [jantimon/html-webpack-plugin#1365]
## Expected behaviour

<%= webpack.hash %> output compilation hash string

## Current behaviour

<%= webpack.hash %> output nothing

## Environment
html-webpack-plugin 4.0.1

I notice the changelog of 4.0.0 contains the following BREAKING CHANGES
```
hooks: The html-webpack-plugin doesn't add its hooks to the compilation object anymore
```
so, how to access compilation hash value after v4.0.0?

**Comment by jantimon** [comment]
Can you please try `<%= compilation.hash %>`?

If that does not help you can change the template variables like shown here:

https://github.com/jantimon/html-webpack-plugin/tree/master/examples/template-parameters

or here: https://codesandbox.io/s/html-webpack-plugin--templateparameters-z2j84

**Comment by z0y1** [comment]
@jantimon work like a charm ! Thanks!
