### ISSUE TITLE
splitChunks not working with templates and custom chunks and an entry name with folders

### ISSUE THREAD

**Issue by superheri** [jantimon/html-webpack-plugin#1366]
## Expected and current behaviour

I'm expecting the plugin to add the chunks created by splitChunks, but they are not. From what I see it seems to be an issue of the fact that I'm using '/' in my entries to create folders and organize my files.

The result, is simply that the html file is copied but without any <script> addition.

## Environment

Win 10 1909
npm 6.9.0
node 10.16.3
webpack 4.42.1
html-webpack-plugin 4.0.1

### Config
```js

{
    entry : {
      'a/b': 'main.js',
      //...
    },
    output: {
        path: path.resolve(__dirname, 'dist')
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: './index.html',
            filename: 'a/index.html',
            chunks: ['a/b'],
            inject: 'body'
        })
    ],
    optimization: {
        splitChunks: {
            chunks: 'all',
            maxSize: 250000
        }
    },
}
```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
       <p>Hello World</p>
    </body>
</html>
```

**Comment by jantimon** [comment]
Can you please check that entry config? It looks like you use a `,` instead of a `.`.

The actual filtering is happening in `node_modules/html-webpack-plugin/index.js` line 181:

https://github.com/jantimon/html-webpack-plugin/blob/d1b173f9442d01d814590f991ddcece81c8f0274/index.js#L181

Can you please add a console.log to find out which `entryNames` are availble?

**Comment by superheri** [comment]
Sorry, I just made a mistake writing the issue, but this is really a `.`. Without usint the `splitChunks`, it works fine, but with the `splitChunks` it's not working.

**Comment by superheri** [comment]
Just tested it and what I see in the `console.log` is an array containing all the entry by names only like `['a/b']`

**Comment by jantimon** [comment]
Can you try to trace down where the filtering removes your chunks?

**Comment by superheri** [comment]
After investingating, I found the problem was linked to the `chunks: 'all'` in my webpack config. I don't know why, but this is working correctly without it. Maybe it should be a good idea to investigate further why and maybe adapt the doc, make the corrections or inform webpack of the problem.
