### ISSUE TITLE
Docs should mention multiple entry chunking technique

### ISSUE THREAD

**Issue by jamie-tillman** [jantimon/html-webpack-plugin#1372]
In learning how to use webpack on a multi-entry configuration (non-SPA app), I found html-webpack-plugin to be promising for generating the script tags for all my entries.  Then the main docs said all my entries would be included in the script tags for every generated html file, rendering it useless for my purposes.  That is, until I found this issue report and a proposed approach:

https://github.com/jantimon/html-webpack-plugin/issues/299

https://github.com/jantimon/html-webpack-plugin/issues/299#issuecomment-216448896

The problem is that it took me an hour of scouring the web and poking around in the issue queue to find it.  I suggest someone amend the docs to at least provide some pointers related to this.  It might save some of your users a ton of time at the outset.

**Comment by jantimon** [comment]
I haven’t used that approach by myself yet.

Maybe you can write a blog post about that topic to share how that works in detail to help others with similar requirements.

**Comment by jamie-tillman** [comment]
That's a good idea.  I'll try to do that once I feel confident I've got it figured out well enough to speak intelligently on it.

Unless Webpack is solely focused on SPAs, I do recommend that the docs do a little more to help with multiple entry configurations.  The scenario I described is an inevitable progression for anyone doing a non-trivial, non-SPA Webpack config.  Expecting the dev to figure out the snarl of <script> tags that must be inserted into the HTML to properly support broad code-splitting, while Webpack itself already has the dependency tree worked out, is just utterly ridiculous.  And it looks like html-webpack-plugin is the only tool that tries to remedy this.

**Comment by poacher2k** [comment]
hey @jamie-tillman ! I've been doing this for about a year now for [Wishy.gift](https://wishy.gift) with a small plugin I made just for myself. I didn't even consider publishing it because I was sure it was just me using `HtmlWebpackPlugin` wrong since things didn't work out of the box with multiple entries.

Today I upgraded some packages and since there was a breaking change to `HtmlWebpackPlugin`, I had to rewrite a couple of stuff. Seeing your issue, I then took the opportunity to clean up some stuff and actually publish it.

You can find it at [@wishy-gift/html-include-chunks-webpack-plugin](https://www.npmjs.com/package/@wishy-gift/html-include-chunks-webpack-plugin). Feel free to try it out and give feedback :) 

@jantimon: Perhaps something to mention in the docs in case more people need this?

**Comment by jamie-tillman** [comment]
Hey, thanks @poacher2k .  We are probably going to do a full-bore transition to webpack in a couple of weeks, so I'll make a note to check our your plugin when we get moving.

Despite this little hiccup I encountered, we are very enthusiastic about webpack -- currently on requirejs.

**Comment by simkessy** [comment]
Yea im confused. What's the proper approach for i have multiple entries? I have like 8 entries and it seems like I get 8 bundles in each page. That's crazy lol

**Comment by NickWoodward** [comment]
I may have the wrong end of the stick, but I'm just using a new instance for each entry file. Although webpack-dev-server doesn't seem to play nice with the templates (only the first works)

`    plugins: [
        new HtmlWebpackPlugin({
            filename: 'index.html',
            template: './src/index.html',
            chunks: ['index', 'common']
        }),
        new HtmlWebpackPlugin({
            filename: 'about.html',
            template: './src/about.html',
            chunks: ['about', 'common']
        }),
        new HtmlWebpackPlugin({
            filename: 'admin.html',
            template: './src/admin.html',
            chunks: ['admin', 'common']
        })
    ]`

**Comment by jantimon** [comment]
@NickWoodward "doesn't seem to play nice" is not the best error description 😉 

```
 new HtmlWebpackPlugin({
            filename: 'about.html',
            template: './src/about.html',
            chunks: ['about', 'common']
        }),
```

should be available on `localhost:XXXX/about.html`

**Comment by jamie-tillman** [comment]
Why was this closed?  Is it not an issue that the docs leave non-SPA developers in the dark?  Is there a better place to log issues with documentation deficiencies?

**Comment by poacher2k** [comment]
> Why was this closed? Is it not an issue that the docs leave non-SPA developers in the dark? Is there a better place to log issues with documentation deficiencies?

I guess a PR might be preferred. The solution in my above comment still works very well 10 months later, and could be a candidate to mention in the docs for this use case :)
