### ISSUE TITLE
@types/html-minifier-terser should be in dependencies

### ISSUE THREAD

**Issue by tkrotoff** [jantimon/html-webpack-plugin#1373]
With v4.0.2

`typings.d.ts` depends on `@types/html-minifier-terser`: https://github.com/jantimon/html-webpack-plugin/blob/v4.0.2/typings.d.ts#L3

Thus `@types/html-minifier-terser` should probably be a dependency instead of a devDependency: https://github.com/jantimon/html-webpack-plugin/blob/v4.0.2/package.json#L30-L31

**Comment by jantimon** [comment]
oh - you are right.. could you please create a pull request?

**Comment by tkrotoff** [comment]
@jantimon #1375

**Comment by jantimon** [comment]
Thanks 👍👍

released as html-webpack-plugin 4.0.3
