### ISSUE TITLE
use contenthash instead of hash

### ISSUE THREAD

**Issue by foyzhao** [jantimon/html-webpack-plugin#1374]
I want to insert a content hash instead of hash **AFTER** '?'

`<link href="main.css?[contenthash but not hash]" rel="stylesheet">`
`<script src="main.js?[contenthash but not hash]"></script>`

Maybe config like this:
```
new HtmlWebpackPlugin({
    // hash: true,
    hash: 'contenthash',
}),
```

Because...
I used to append a content hash like this:
```
module.exports = {
  ...
  entry: './src',
  output: {
    filename: '[name].js?[contenthash]',
  },
  ...
}
```
with html-webpack-plugin@3.2.0 it works fine
```
<html>
  <head>
    <meta charset="UTF-8">
    <title>Webpack App</title>
  </head>
  <body>
  <script src="main.js?803bc3411f4f1d2447c9"></script>
  </body>
</html>
```
but with html-webpack-plugin@4.0.2 it inject nothing into body
```
<html>
<head>
  <meta charset="utf-8">
  <title>Webpack App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body></body>
</html>
```

Remark: html-webpack-plugin@4.0.2 could work when config like this
```
module.exports = {
  ...
  entry: './src',
  output: {
    filename: '[name].[contenthash].js',
  },
  ...
}
```
```
<html>
  <head>
    <meta charset="UTF-8">
    <title>Webpack App</title>
  </head>
  <body>
  <script src="main.803bc3411f4f1d2447c9.js"></script>
  </body>
</html>
```
But this is not what I want.

**Comment by statorg** [comment]
Why `filename: '[name].js?[contenthash]'` is not work for inject now? Will it be fixed?

**Comment by jantimon** [comment]
Filenames should not contain question marks.

You could try `[name].[hash].js`

**Comment by foyzhao** [comment]
> Filenames should not contain question marks.
> 
> You could try `[name].[hash].js`

I prefer to put the hash in the query string rather than the filename.

**Comment by jantimon** [comment]
Same as:

#1367
#1346
#1355

**Comment by jantimon** [comment]
I have reported this issue here: https://github.com/webpack/webpack/issues/10638

**Comment by foyzhao** [comment]
I don't want to put a question mark in filename either, so I want to know if there is a way to replace the hash with contenthash, as mentioned at the beginning of this issue, something like add an option to the hash attribute.
hash: {Boolean|String}

**Comment by jantimon** [comment]
I will try to bring back the same behaviour as in 3.2 for details please see #1355
