### ISSUE TITLE
Is it possible to output compiled template javascript in v4

### ISSUE THREAD

**Issue by wood1986** [jantimon/html-webpack-plugin#1376]
**Is your feature request related to a problem? Please describe.**

I have already started using the v4. If you can support this, it will be very useful. When we provide our jsx as the template, you will ask webpack to compile again whose entry is this template and the target is node. Then you will execute this in order to output the html. If you can output the result of the js file, it will be awsome. Here are the benefits:

1. easy to debug. If there are something wrong in the template.jsx, I am unable to inspect the template code and console.log does not help neither. If you can emit the result, I can `node --inspect-brk` this file without running webpack it again.
1. This compiled template js can be re-used for sever-side-rendering purpose without running webpack again.

**Comment by ChildishGiant** [comment]
For me I've just downgraded until it's fixed. `npm i --save-dev html-webpack-plugin@3.2.0 ` I use template parameters to translate my website so without template params my website is just placeholders

**Comment by jantimon** [comment]
Sorry @ChildishGiant I don't think your answer is related.

@wood1986 I see your point but I don't want to add it to html-weblpack-plugin as it would not be the primary purpose of this plugin.

however I believe there are people who will need exactly this feature and therefore it would probably good to enable plugin writers to offer this feature.  

usually plugin writers use hooks (the webpack event system) but right now the html-webpack-plugin is not offering a hook to access the compiled template
I am open to add one so someone could create a `html-template-exporer-webpack-plugin` with the features you need

what do you think?

**Comment by ChildishGiant** [comment]
My issue was that starting with v4 my template params no longer function

**Comment by wood1986** [comment]
@jantimon, I am unable to comment it until the following scenario is resolved.

Right now, I am blocked by a scenario. Even if you can output the template.js, how does [inline js and css](https://github.com/jantimon/html-webpack-plugin/blob/master/examples/inline/template.pug) work because you will pass this `{compilation, webpackConfig, htmlWebpackPlugin`. But if I require this template.js, I cannot pass `compilation, webpackConfig, htmlWebpackPlugin` because it is purely from node not from webpack. It does not have `compilation` for me to inline the js and css.

If the compiled template.js is able to provide or pack the inline css and js in the final output, when I require it and use node to run it, I would expect I do not depend anything during the execution in SSR.

**Comment by wood1986** [comment]
@jantimon, Here is my rough idea about solving the inline scenario and I need RFC. Let's assume every thing is happened in `html-webpack-plugin` first

One template.js input does everything is my minimum requirement. This means html-webpack-plugin should be able to generate the html output and node should be able to run the template.js output to generate the html ouput without depending on anything (no `external`).

I would suggest a new configuration property, `inline` in the plugin option. Users have to specify a list of named chunks. Currently, a big js file whose target is node will be exported. With my suggestion, there will be a new process in `html-webpack-plugin` which will read that `inline` property to generate some code in the template.js output to polyfill and serialize the missing the properties `{compilation, webpackConfig, htmlWebpackPlugin} and templateParameters`. Or you can introduce another property to achieve that.

At this point, if you understand what I have said, I guess you won't add this feature in html-webpack-plugin. Personally, I want to one plugin does everything. With the release of v4 and [your demo](https://codesandbox.io/s/html-webpack-plugin--jsx-sjbcq), [Most plugins](https://github.com/jantimon/html-webpack-plugin#plugins) has become unnecessary. The polyfill and serialization process will be easier to achieve inside the same plugin.

**Comment by jantimon** [comment]
Inlining can be done for example with the [InlineChunkHtmlPlugin](https://github.com/facebook/create-react-app/blob/edc671eeea6b7d26ac3f1eb2050e50f75cf9ad5d/packages/react-scripts/config/webpack.config.js#L592) from facebook

But you are right this is happening after template is executed and rendered.

You are asking for having a smart injection feature which works for jsx but this would be be very very hard to achieve.

Let's assume you would have a hook as we talked before and would like to implement a plugin which does all you proposed:

```js
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = class NodeServerSideRenderingTemplateWebpackPlugin {
  apply (compiler) {

    compiler.hooks.compilation.tap('NodeServerSideRenderingTemplateWebpackPlugin', (compilation) => {
      let template = '';

      HtmlWebpackPlugin.getHooks(compilation).alterTemplate.tapAsync(
        'NodeServerSideRenderingTemplateWebpackPlugin', 
         (data, cb) => {
          template = data.templateCode;
          data.template = () => '';
          cb(null, data)
        }
      );

      HtmlWebpackPlugin.getHooks(compilation).afterTemplateExecution.tapAsync(
        'NodeServerSideRenderingTemplateWebpackPlugin', 
        (data, cb) => {
          data.html = renderTemplate(data)
          cb(null, data)
        }
      );
    })

  }

  renderTemplate({headTags, bodyTags}, templateCode) {
     return `
          // Generated by NodeServerSideRenderingTemplateWebpackPlugin
          module.exports = (data) => {
          const tags = ${JSON.stringify({headTags, bodyTags})};
            return ${templateCode}(data, tags)
          };
`

  }

}
```

As you see writing a plugin would be doable.

The only thing which would not work out of the box would be the inject feature.

So you would have to generate the tags based of the information from `headTags` and `bodyTags`.

**Comment by wood1986** [comment]
>You are asking for having a smart injection feature which works for jsx but this would be be very very hard to achieve.

I do not think it is only for jsx. The plugin does not need to do any injection. Developers can decide how and where to put in their template.js input but a variable `{inline}` or polyfill `{compilation, webpackConfig, htmlWebpackPlugin}` has to be ready when running outside of webpack.

Again hope html-webpack-plugin can take care his. If you do not want, I think your suggestion of creating another hooks is definitely a good idea and gives dev more opportunities.

Unfortunately, I may choose to go to a different path. I will create another webpack plugin which will does everything
1. but it only targets jsx input only.
1. generate html for webpack-dev-server and template.js for ssr.
1. support packing the inline source code.

Thanks for the sharing

**Comment by jantimon** [comment]
The example I showed would work not only for jsx but for everything.

I will allow using `favicons-webpack-plugin` meta-tags, base-tags, caching, ...

Not sure why you would not want to use `html-webpack-plugin` from your plugin

**Comment by wood1986** [comment]
I know your example works for any types template. But I do not want to install so many plugins such as `favicons-webpack-plugin`, `inline-chunk-html-plugin`, `html-template-exporter-webpack-plugin` and so on in my project.

I guess why you need lots of plugin for different purposes is html-webpack-plugin does not bind to react and you want to support different rendering framework. As I said, all `meta` tags can be done in react. I do not need `favicon-webpack-plugin` except for dev friendely reason. I would prefer a little lower level customization. This plugin only targets react and ssr and it allows the template.js to be executed outside webpack.

**Comment by jantimon** [comment]
The idea of plugins is to allow customisation - to support different requirements but also keep flexibility. If you build one very special solution it might work in some case but not for many.

You can also reuse the html-webpack-plugin from within a plugin and add it as dependency:

```
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = class NodeServerSideRenderingTemplateWebpackPlugin {
  apply (compiler) {
     const htmlWebpackPlugin = new HtmlWebpackPlugin({ /* some options */);
     htmlWebpackPlugin.apply(compilter)
     //....
```
