### ISSUE TITLE
[html-webpack-inline-source-plugin] is not working with [html-webpack-plugin@4.0.0 version+]

### ISSUE THREAD

**Issue by DemonCloud** [jantimon/html-webpack-plugin#1379]
see this issue : https://github.com/DustinJackson/html-webpack-inline-source-plugin/issues/75

can not read property "tapAsync" from undefined

@jantimon 
Have you considered building the functionality of inlineSource into html-webpack-plugin?

**Comment by jantimon** [comment]
Is there any information from @DustinJackson if he want's to upgrade?

**Comment by DemonCloud** [comment]
@jantimon ......
html-webpack-inline-source-plugin.  has over 3 years ago... 

In some cases, it is more desirable to maintain this feature by the official. At least embedding the css directly in the head of the html page is a very good performance optimization practice.

**Comment by davidschwegler** [comment]
I'm currently using html-webpack-inline-source-plugin@beta, but that project doesn't seem to be maintained. +1 for including something like that plugin directly in html-webpack-plugin.

**Comment by DustinJackson** [comment]
> Is there any information from @DustinJackson if he want's to upgrade?

@jantimon I'll take a look this weekend to get it working with latest, I'll open an issue to see if anybody else wants to help maintain it

**Comment by DemonCloud** [comment]
@jantimon hope include this feature  with html-webpack-plugin

**Comment by Jaid** [comment]
[DustinJackson/html-webpack-inline-source-plugin](html-webpack-inline-source-plugin) is [deprecated](https://github.com/DustinJackson/html-webpack-inline-source-plugin/issues/75#issuecomment-610098535) now, so it would probably be the best to make it an official feature now.

**Comment by Jaid** [comment]
Meanwhile, the similar plugin [`react-dev-utils/InlineChunkHtmlPlugin`](https://github.com/facebook/create-react-app/tree/master/packages/react-dev-utils#new-inlinechunkhtmlpluginhtmlwebpackplugin-htmlwebpackplugin-tests-regex) can be used as a replacement.

```bash
npm install --save-dev react-dev-utils
```

```js
import HtmlPlugin from "html-webpack-plugin"
import InlineChunkHtmlPlugin from "react-dev-utils/InlineChunkHtmlPlugin"

const webpackConfig = {
  plugins: [
    new HtmlPlugin({
      title: "App",
      meta: {},
    }),
    new InlineChunkHtmlPlugin(HtmlPlugin, [/\.(js|css)$/]),
  ],
}
```

It works well in general, but it isn't suitable for me because unlike [`html-webpack-inline-source-plugin`](https://github.com/DustinJackson/html-webpack-inline-source-plugin) it does not support inlining CSS, only JS, so I'll wait for upcoming alternatives.

**Comment by jk2K** [comment]
find a patch version https://www.npmjs.com/package/@effortlessmotion/html-webpack-inline-source-plugin

support webpack 5
