### ISSUE TITLE
Template parameters broken from 4.0.0 onward

### ISSUE THREAD

**Issue by ChildishGiant** [jantimon/html-webpack-plugin#1380]
## Expected behaviour

Template parameters should be replaced with the supplied param, as documented.

![image](https://user-images.githubusercontent.com/13716824/77896391-1d32e600-7270-11ea-969c-7dde172cee3e.png)

## Current behaviour

Template params are left 
![image](https://user-images.githubusercontent.com/13716824/77896345-08565280-7270-11ea-955a-8486b9579ac1.png)

## Workaround

Downgrading to 3.2.0 (`npm i --save-dev html-webpack-plugin@3.2.0`) fixes the regression. 

## Environment

Node.js v12.14.1
win32 10.0.18363
npm v6.13.4
webpack v4.42.1
html-webpack-plugin v4.0.3
### Config

```js
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
	entry: "./index.js",
	plugins: [
		new HtmlWebpackPlugin({
			templateParameters: {
				test: "It works!"
			},
			template: "template.html"
		})
	]
};
```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<html>
	<body>
		${test}
	</body>
</html>
```

## Relevant Links

Minimal repro: https://gist.github.com/ChildishGiant/e8d5998eb8865b929e84a763a9e64ffd

**Comment by jantimon** [comment]
Works for me:

https://codesandbox.io/s/html-webpack-plugin-template-parameter-7z8nf

<img width="638" alt="works" src="https://user-images.githubusercontent.com/4113649/78002244-32bf1300-7337-11ea-88c0-9649e288bbbf.png">

If you don't use another template language please try `<%= test %>`

Does that solve your question?

**Comment by ChildishGiant** [comment]
I use a plain html file as a template and the template literals format (`${expression}`). If it worked in prior versions surely it's a regression to not be working in 4.0.0 onwards? Try the minimal repro on 3.2.0 and 4.0.3 to see what I mean

**Comment by jantimon** [comment]
I have just tried and it seems you are right - looks like it was an unintended feature in `3.2.0`.

Unfortunately I don't know what broke it for 4.0.3 so it is hard to repair.

Would it be a big issue to use `<%= ` instead of `${` ?

**Comment by ChildishGiant** [comment]
Nah it shouldn't be, just a matter of a regex find and replace (or 15 mins). I'm now wondering where I got doing it this way from, maybe stackoverflow.

**Comment by jantimon** [comment]
Would be good to know why it broke 🤔

**Comment by ChildishGiant** [comment]
"Template strings inside templates are now disabled by default" Could it be related to this?

**Comment by jantimon** [comment]
oh nice find!

you are right: https://github.com/jantimon/html-webpack-plugin/commit/d6b65dd1531038deac1be87c2087da5955903d24

the reason why we introduced it is the following example:

```html
<html>
<body>
<script>
   const demo = "foo";
   const console.log(`example: ${demo}`);
</script>
</body>
</html>
```

without that patch it would try to replace `${demo}` during template rendering and break the javascript code inside the template

**Comment by ChildishGiant** [comment]
Ah okay, I see why you'd want to change that. Does this mean I can pass a param to toggle this back on?

**Comment by jantimon** [comment]
Unfortunately not as you can't pass in a regexp easily :(

**Comment by ChildishGiant** [comment]
Yep I just moved to ejs. From the commit it looks like I'd just need to set the interpolate value back to nothing to re-enable template params if I relied on them?

**Comment by jantimon** [comment]
Correct :)
