### ISSUE TITLE
Automatically add html files

### ISSUE THREAD

**Issue by thibka** [jantimon/html-webpack-plugin#1382]
Instead of doing
```javascript
plugins: [
	new HtmlWebpackPlugin({
		filename: './index.html',
		template: './src/index.html'
	}),
	new HtmlWebpackPlugin({
		filename: './somepage.html',
		template: './src/somepage.html'
	}),
	new HtmlWebpackPlugin({
		filename: './someotherpage.html',
		template: './src/someotherpage.html'
	}),
        // etc...
]
```
It would be nice if you could just do something like
```javascript
plugins: [
	new HtmlWebpackPlugin({
		test: /\.html$/
		template: './src/[name].html'
	})
]
```

**Comment by jantimon** [comment]
The idea is good but not that easy to implement without breaking the entire hooks api.  
I would prefer to focus on preparing webpack 5 compatibility first but if you like you can give it a try and send a pull request.

**Comment by ylavoie** [comment]
How about
```
plugins: [
	new HtmlWebpackPlugin({
		filename: [ 'file1', 'dir/*.html']
		template: './src/[name].html'
	})
]
```
Using an array of regex would be closer to the current api and would simplify the task. I have about a hundred to enumerate for 1 project.

**Comment by jantimon** [comment]
I would prefer to use `'./src/[name].html'` to use the same format as the webpack output options.   

For now as a intermediate solution you can do the following:
```
plugins: [
        ...(['file1', 'file2', 'file3' ].map((file) => new HtmlWebpackPlugin({
		filename: `${file}.html`,
		template: `./src/${file}.html`
	}))
]
```

**Comment by ylavoie** [comment]
I love the syntax. Webpack isn't so fond of it:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.plugins[5] should be one of these:
   object { apply, … } | function
   -> Plugin of type object or instanceof Function
   Details:
    * configuration.plugins[5] should be an object.
      -> Plugin instance
    * configuration.plugins[5] should be an instance of function
      -> Function acting as plugin
```

**Comment by jantimon** [comment]
Can you show your code? I tried the above and it works

**Comment by jantimon** [comment]
The latest 5.x alpha allows to use two new ways:

- `"[name].html"`
- `(chunkName) => `${chunkName}.html`

do we need the name also for template?

all other updates for 5.x can be found in #1527

**Comment by thibka** [comment]
> plugins: [
>         ...(['file1', 'file2', 'file3' ].map((file) => new HtmlWebpackPlugin({
> 		filename: `${file}.html`,
> 		template: `./src/${file}.html`
> 	}))
> ]

It works but one parenthesis is missing at the end :)

```javascript
plugins: [
        ...(['file1', 'file2', 'file3' ].map((file) => new HtmlWebpackPlugin({
		filename: `${file}.html`,
		template: `./src/${file}.html`
	})))
]
```

**Comment by mdmoreau** [comment]
@jantimon Does that mean [name] can be used as a glob entry to replace the map method you mentioned earlier?

**Comment by jantimon** [comment]
@mdmoreau `[name]` will use the entry names for example the following entries

```js 
entry: {
  index: './index.js',
  aboutUs: './aboutUs.js'
}
```

and the following html webpack plugin config:

```js
new HtmlWebpackPlugin({
  filename: '[name].html',
}),

```

would generate:

`index.html` and `aboutUs.html`

**Comment by mdmoreau** [comment]
@jantimon Got it - thanks!
