### ISSUE TITLE
Changing CSS does not update when using webpack-dev-server, or webpack --watch

### ISSUE THREAD

**Issue by davidschwegler** [jantimon/html-webpack-plugin#1384]
## Expected behaviour

When running under webpack-dev-server, changing the .css file should cause the page to reload with the changes.

## Current behaviour

The page does not update (it reloads, but still with the old css).  

This ONLY fails when using the HtmlWebpackPlugin. This is particularly bad when using the HtmlWebpackInlineSourcePlugin, because since the contents are bundled in the output file, not even `webpack --watch` will work.

## Environment

```
Node.js v12.14.0
darwin 19.4.0
npm 6.13.4
webpack@4.42.1 
html-webpack-plugin@4.0.3 
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
// webpack.config.js
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  entry: "./src/index.js",
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: "index.js"
  },
  optimization: {
    minimize: false
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ["style-loader", "css-loader"]      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/template.html",
    }),
  ],
};
```

## Additional context

```
	"scripts": {
		"build": "rimraf dist && cross-env webpack --config webpack.config.js --mode production",
		"watch": "webpack --config webpack.config.js --mode development --watch --watch-poll",
		"start": "webpack-dev-server --inline --no-info --config webpack.config.js --mode development --content-base dist"
	},
```

**Comment by jantimon** [comment]
That sounds like you have an issue with the new caching logic:

https://github.com/jantimon/html-webpack-plugin/blob/ae85345fc49cea418f27338505356aa65853c6cb/index.js#L200-L206

The idea is that if no new files where added we can save the time and reuse the previous html.
To disable that please set `cache: false`

**Comment by davidschwegler** [comment]
> That sounds like you have an issue with the new caching logic:
> 
> https://github.com/jantimon/html-webpack-plugin/blob/ae85345fc49cea418f27338505356aa65853c6cb/index.js#L200-L206
> 
> The idea is that if no new files where added we can save the time and reuse the previous html.
> To disable that please set `cache: false`

<3 that fixed it, thank you! 

I wonder if maybe this should be called out a little more prominently in the docs somewhere to help others? Using webpack-dev-server or webpack --watch seem like typical approaches.

**Comment by jantimon** [comment]
I guess the reason might be `--content-base dist`

**Comment by davidschwegler** [comment]
> I guess the reason might be `--content-base dist`

FWW, removing that had no effect.

**Comment by jantimon** [comment]
So your probleme is only about `webpack` `webpack-dev-server` and `css-loader`?

**Comment by davidschwegler** [comment]
> So your problem is only about `webpack` `webpack-dev-server` and `css-loader`?
> 
> Which update do you expect to be done by the `html-webpack-plugin`?

I don't have any more problems. My problem was fixed by your comment above https://github.com/jantimon/html-webpack-plugin/issues/1384#issuecomment-607471985
