### ISSUE TITLE
EJS Partials Do Not Re-Render with HMR/Browser Sync

### ISSUE THREAD

**Issue by MakingStuffs** [jantimon/html-webpack-plugin#1397]
## Expected behaviour

When I make a change to a partial file which is included in the specified template it should be re-rendered when the browser reloads.

## Current behaviour

The browser reloads but the partial is not re-rendered

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
Node Version: Node.js v12.13.1
OS: darwin 19.3.0
NPM Version: 6.14.4
Webpack Version: 4.42.1 
HmtlWebpackPlugin Version: 3.2.0  
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  ...
    plugins: [
        new BrowserSyncPlugin({
            files: '**/*.ejs',
            proxy: `https://localhost:${process.env.PORT}`
        }),
        new HtmlWebpackPlugin({
            template: 'ejs-webpack-loader!src/views/pages/index.ejs',
            filename: 'index.html',
            domain: process.env.DOMAIN
        })
  ]
}
```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-GB"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <%- include partials/head.ejs %> 
        <title>Making Stuffs | Coming Soon Boilerplate</title>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <%- include partials/navbar.ejs %>
        <%- include partials/intro.ejs %> 
        <%- include partials/about.ejs %> 
        <%- include partials/portfolio.ejs %> 
        <%- include partials/contact.ejs %> 
        <%- include partials/blog.ejs %> 
    </body>
</html>
```

## Relevant Links

GitHub Repo: https://github.com/MakingStuffs/portfolio
StackOverflow: https://stackoverflow.com/questions/61024886/browser-sync-not-re-rendering-ejs-partial-files

## Additional context

Browser Sync is definitely working properly as it is reloading the browser when I save a change on a partial file, so it is obviously _watching_ the partials. The issue is either with HtmlWebpackPlugin or ejs-webpack-plugin. 

Any advice is hugely appreciated.

**Comment by jantimon** [comment]
Wow haven't seen IE6 dedicated code for some time 😉 

I don't know for 100% but it looks like the `ejs-webpack-plugin` has some code in place to watch partial files: 

https://github.com/rorkflash/ejs-webpack-loader/blob/e9df483ecfae3aa0f6ce506b4f9c354849226ccc/index.js#L33-L34

The html-webpack-plugin is also watching its file dependencies.  
You could try the latest version as the caching was improved.

**Comment by MakingStuffs** [comment]
@jantimon Hey thanks for getting back to me mate. 

> Wow haven't seen IE6 dedicated code for some time 😉 
😂God I need to remove that, its from the html5 boiler plate!

I just tried with the latest version of html-webpack-plugin and, sadly, still the same results. If I reload the browser manually it doesn't change either. Weird. 

The only thing that seems to get the partial to re-render is either manually hitting `ctrl+c` and then running the dev script again or going to the main index.ejs file and saving it. 

I forgot to mention that I am running this through an express server with webpack-dev-middleware which then uses the config/compiler but I don't that _should_ be an issue since webpack is handling the compilation and bundling.

**Comment by jantimon** [comment]
I quickly turned it into a codesandbox:

https://codesandbox.io/s/html-webpack-plugin-ejs-includes-l9d64

the demo includes two files:
- `about.ejs` using the `<%- include` directive from `ejs-webpack-loader`
- `footer.ejs` using the `<%= require(` webpack syntax

For the `about` partial it is exactly like you described - files will not trigger a new compile.  
However the `footer` partial triggers a recompile.

Therefore the issue must be related to the `ejs-webpack-loader`

**Comment by MakingStuffs** [comment]
Thanks for doing that for me mate, that definitely works so I will continue with that method for now!
