### ISSUE TITLE
xhtml property is broken

### ISSUE THREAD

**Issue by besLisbeth** [jantimon/html-webpack-plugin#1399]
## Expected behaviour

xhtml property should render the link tags as self-closing

## Current behaviour

xhtml property renders the link tags as non-closed. Everything was ok with version 3.2.0

## Environment

Node.js v12.16.1
win32 10.0.18362
npm 6.14.4
webpack 4.42.1
html-webpack-plugin 4.0.4
### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = env => merge(common(env), {
    mode: 'production',
    output: {
        path: __dirname + '/dist',
        publicPath: '/monitor/',
        filename: 'scripts/[name]/[name].[hash].bundle.js',
        chunkFilename: 'scripts/[name]/[name].[chunkhash].bundle.js'
    },
    plugins: [
        new HtmlWebpackPlugin({
            title: 'index.html',
            template: './index_prod.html',
            xhtml: true,
            chunksSortMode: 'none',
            inlineSource: '.(css)$'
        })
     ]
});
```

**Comment by jantimon** [comment]
Hey thanks for reporting

Can you please add a `console.log` in line 887?  
The file can be found in `node_modules/html-webpack-plugin/index.js`

https://github.com/jantimon/html-webpack-plugin/blob/c5a58824b8d33c3f9b85d1f541a27844a62721e4/index.js#L881-L888

The console.log should be e.g.

```js
console.log(head.join(''), 'xhtml:', this.options.xhtml);
```

**Comment by besLisbeth** [comment]
Hi, @jantimon. Changing options from 
```
options: { minimize: { collapseWhitespace: false, removeComments: false } }
```
to 
```
options: { minimize: false }
```
removes my issue. Maybe, I just used the options wrong, after an update of the dependency.
Thank you a lot for the quick response!

**Comment by jantimon** [comment]
oh good point - we could change the minification default options to `keepClosingSlash: true` if xhtml is active.

what do you think?

**Comment by besLisbeth** [comment]
Yes, it would be perfect. But I didn't find this option in the docs. 

And I'm not totally sure, that `keepClosingSlash` is the minification option, because, with my wrong settings, it didn't remove slashes from the links which I added by myself.
