### ISSUE TITLE
Html templates variables support 

### ISSUE THREAD

**Issue by wizardion** [jantimon/html-webpack-plugin#1400]
## Expected behaviour
Using the HTML file template `index.html`
```
<p>Using env: <%=environment %></p>
```
I'm expecting to get variable value from `templateParameters.environment`, but using the HTML file template it doesn't replace me the variables inside the `.html` after build.

## Current behavior

To get the variable value from `templateParameters.environment`, I need to use `.ejs` file template instead of `.html`. 

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  ...
  plugins: [
    new HtmlWebpackPlugin({
    template: './src/index.html',
    filename: 'product.html',
    templateParameters: {
      environment: 123
    }),
    ...
  ]
}
```

The template file:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
        <p>Using env: <%=environment %></p>
    </body>
</html>
```

Is there any syntax or support to use HTML file templates instead of EJS, to be able to put variables from `templateParameters`?

**Comment by jantimon** [comment]
Looks good - which version are you using?

**Comment by wizardion** [comment]
@jantimon Thank you for your response. I use html-webpack-plugin@4.0.4.
As for the loaders, I use the following packages: 
├── file-loader@6.0.0
├── html-loader@1.1.0
├── html-webpack-plugin@4.0.4
├── url-loader@4.1.0
├── webpack@4.42.1
└── webpack-cli@3.3.11 

So here my entire project's example: [webpack-demo.zip](https://github.com/jantimon/html-webpack-plugin/files/4451642/webpack-demo.zip)

**Comment by wizardion** [comment]
@jantimon After your replay, I figured out that the reason for this issue is an `html-loader`. Once I removed it from the module.rules, the `html-webpack-plugin` started to parse the HTML template by replacing the `templateParameters`. 
So what do you recommend, post an issue into the `html-loader` branch or is there anything we can do/fix with it?

**Comment by jantimon** [comment]
`html-loader` does not support template parameters.
Why do you want to use it?

**Comment by wizardion** [comment]
@wizardion I need the `html-loader` to further using the `url-loader` to inject all the images with `[contenthash]` inside that `html` file. Is there a different way to do that?

**Comment by jantimon** [comment]
You could use a `preprocessor`: https://webpack.js.org/loaders/html-loader/#preprocessor

Or use ejs syntax: `<img src="<%= require('./some/image.jpg' %>">`

**Comment by wizardion** [comment]
Alright, I'll look at that! Thank you for your help!
