### ISSUE TITLE
Is it possible to use raw-loader to output an ejs template whilst still allowing webpack to handle images?

### ISSUE THREAD

**Issue by MakingStuffs** [jantimon/html-webpack-plugin#1405]
**Is your feature request related to a problem? Please describe.**

I am using `html-webpack-plugin` with `raw-loader` to output an ejs file which can be rendered by my express server (I am using my templates with Strapi so wish to render the files on the server side for security). 

I got this idea from the following post: https://github.com/jantimon/html-webpack-plugin/issues/551

The issue is that images are, obviously, not being handled by webpack now as the raw-loader is simply outputting the raw ejs data -- as I wanted it to. I know that I can simply import the images I need to use in my entry JS file and then hard code the predicted url into the template file but I wanted to use hashing in the naming of images to preserve caching on the clientside.

**Describe the solution you'd like**

What I am looking to solve is a way of having `html-webpack-plugin` output a raw EJS template which has taken the path of specified images and replaced them with the newly bundled url which has a hash in the filename.

**Describe alternatives you've considered**

I've considered using other loaders such as `ejs-loader` etc but they will not output a raw ejs file as does `html-webpack-loader` when paired with `raw-loader`. 

I have also considered importing images into my entry JS file and hard coding the predicted image url into the template but I have no way of knowing what the hashed filename will be.

**Comment by jantimon** [comment]
What about the html-loader?

**Comment by MakingStuffs** [comment]
Do you mean import all my ejs files to the main entry point and then use html loader with the test as `/\.ejs$/`?

**Comment by MakingStuffs** [comment]
Got it, adding it inline did the trick. Can I ask you an unrelated question regarding excludeChunks?

**Comment by jantimon** [comment]
sure

**Comment by MakingStuffs** [comment]
Thanks man, I wanted to ask how you would use the exclude chunks option when the entry is an array. I have tried setting the index of the entry point (as both a string and a number) but it doesn't seem to work. 

Is it possible?

**Comment by jantimon** [comment]
I have never faced this issue - what about converting it to an index based object?

**Comment by MakingStuffs** [comment]
Thanks for the reply and sorry for my delay! That would work I guess, objects work fine. Was just wondering whether it was possible to do it with a plain old array. Never mind, it isn't really an issue was just wondering. Thank you for your help mate
