### ISSUE TITLE
keep final filename without hash if output.filename is hashed

### ISSUE THREAD

**Issue by yuwanlin** [jantimon/html-webpack-plugin#1409]
**Is your feature request related to a problem? Please describe.**
similar to [#556](https://github.com/jantimon/html-webpack-plugin/issues/556), but I just wanna html-webpack-plugin emit final html without hashed even if my `output.filename is [name].[contenthash:8].js`. I just wanna mixin entry js file to final html.

because my template html is used by nodejs for render.

**Describe the solution you'd like**
Add a option:   
could add a new function option to custom final filename?

**Additional context**
```
 output: {
    path: path.join(OutputPath, 'statics'),
    filename: '[name].[contenthash:8].js',
    chunkFilename: 'appchunks/app/[id].[contenthash:8].chunk.js',
    publicPath: '/statics/',
    sourceMapFilename : 'sourcemap/app/[file].map'
  }

new HtmlWebpackPlugin({
    template: '!!raw-loader!' + path.join(SourcePath, 'modules/app/views/layout/master.html'),
    filename: path.join(SourcePath, 'modules/app/views/layout/master.html'),
    minify: false,
}),
```

html-webpack-plugin v3.2.0 or v4.0.4 do the same behavior

**Comment by yuwanlin** [comment]
@jantimon hey, Should I need to add more information for this problem? 
Could you give me some Suggestions?

**Comment by jantimon** [comment]
I am very sorry but I don't understand your question.

```
new HtmlWebpackPlugin({
    template: '!!raw-loader!' + path.join(SourcePath, 'modules/app/views/layout/master.html'),
    filename: path.join(SourcePath, 'modules/app/views/layout/master.html'),
    minify: false,
}),
```

Will read from: `modules/app/views/layout/master.html`
and write to: `modules/app/views/layout/master.html`

This will probably add more and more and more script and link tags for every webpack run.

**Comment by yuwanlin** [comment]
In fact, it will emit a `master-somehash.html` in to `modules/app/views/layout`.

so, the **modules/app/views/layout folder** will container `master.html` and `mast-somehash.html`.
```
modules/app/views/layout
- master.html
- master-somehash.html
```

even if I change the filename path, It still will emit `master-somehash.html`. For example:
```
new HtmlWebpackPlugin({
    template: '!!raw-loader!' + path.join(SourcePath, 'modules/app/views/layout/master.html'),
    filename: path.join(SourcePath, 'modules/master.html'),
    minify: false,
}),
```
Final, the **modules folder** container `master-somehash.html`.  

I just wanna html-webpack-plugin emit same name file(master.html) which only injected entry js file.

I am not true if you get my point :)
maybe I should provide a mini repo...

**Comment by jantimon** [comment]
What about this?

```
new HtmlWebpackPlugin({
  filename: 'head-tags.html',
  inject: false,
  templateContent: ({htmlWebpackPlugin}) => `${htmlWebpackPlugin.tags.headTags}`
}),
new HtmlWebpackPlugin({
  filename: 'body-tags.html',
  inject: false,
  templateContent: ({htmlWebpackPlugin}) => `${htmlWebpackPlugin.tags.bodyTags}`
}),
```

**Comment by yuwanlin** [comment]
I tried, It has the same behavior.

![](https://store-g1.seewo.com/50380a32cd05401c8d8bd629f0d9097c)

html-tags-hash.html is empty.
body-tags-hash.html include entry js.
```
<script src="/statics/index.c9ac8ba6.js"></script>
```

so, is There a valid solution or modify the soruce mode?

**Comment by jantimon** [comment]
I have really no idea what you are asking for.
What is your problem everything seems to work fine

**Comment by yuwanlin** [comment]
ok, for example, when I use
```
new HtmlWebpackPlugin({
  filename: 'body-tags.html',
  inject: false,
  templateContent: ({htmlWebpackPlugin}) => `${htmlWebpackPlugin.tags.bodyTags}`
}),
```
I expect html-webpack-plugin emit `body-tags.html` which included entry js instead of `body-tags-cd6f3ddf03.html(above pictrue)`.

I know this is because my output.filename is cotendhashed. so I want to find a solution:
**html-webpack-plugin emit a file without hash even if my output.filename is hashed.**

**Comment by jantimon** [comment]
Yes that should be the default behaviour.   
Can you please try to remove other plugins and configurations to find the reason for this bug?

**Comment by yuwanlin** [comment]
yes, that is the default behaviour because of some source code, but we can't custom if we need hash or not... 

>Can you please try to remove other plugins and configurations to find the reason for this bug?

yes, it need some time, I'am a little busy this week until friday. 

I suppose I could fix it, It's my first to do something for it...
if I can do something for this, should I pull a request?

**Comment by jantimon** [comment]
Actually I don’t think any code change is necessary - I need to try to reproduce your problem

**Comment by yuwanlin** [comment]
yes, I will create a mini repo to reproduce this problem.

**Comment by yuwanlin** [comment]
sorry, It's something wrong  with my build config, html-webpack-config work well :)

thanks for your help~

**Comment by jantimon** [comment]
Good to know that you could solve it 👍
