### ISSUE TITLE
Relation between contentbase and htmlWebpackPlugin

### ISSUE THREAD

**Issue by jimchild49** [jantimon/html-webpack-plugin#1410]
Hi,

Excuse me if I'm posting this here, but I'm preparing a lesson for my students, and there is no better way than getting the info from the source itself, 

having contentBase option tells webpack from where to serve the index.html, if for example I have:

```
devServer: {
    port: 3000,
    contentBase: path.resolve(__dirname, 'public')
 }
```
Webpack will serve the project-root-path/**public/index.html**

But once I use htmlWebpackPlugin like this:

```
new HtmlWebpackPlugin({
    template: './src/template.html'
}),
```
the index.html in my public folder is no longer rendered, the rendered index.html is the one created by HtmlWebpackPlugin, even though in the terminal it says: Content not from webpack is served from **/home/user/project-root-folder/public**

Do I understand that HtmlWebpackPlugin is somethow replacing the index.html in the public folder? 

I would appreciate if you explain what's happening at this stage :)

Thank you a lot.

**Comment by jantimon** [comment]
there are 2 reasons for that:

## Memory File System

webpack dev server is using in memory file system for performance reasons.  
So files are not written on disk but into memory.

You can change this behaviour here:  
https://webpack.js.org/api/node/#custom-file-systems

Webpack will use the html-webpack-plugin to compile your template to `index.html` into this memory file system

## Express JS

webpack-dev-server is using [express](https://www.npmjs.com/package/express)

in express you can define multiple routes for the same route  
in express the first matching route always wins unless it calls `next()`

take a look at the following example pseudo code:

```
app.use('/',funtion(req,res){
   // Here is the webpack code which will try to deliver `index.html` and all your js and css files
   // from the Memory File System
   /* ... */
   // If the requested file does not exist in webpack it just moves on to the next middleware:
   if (doesNotExistInWebpack()){
       next();
   }
})
app.use('/',funtion(req,res){
   // Here is the code which delivers everything from your static content base
})
```

**Comment by jimchild49** [comment]
@jantimon thank you very much for the explanation, totally clear. Just one point about how webpack dev server handles the contentBase

I thought that the contentBase files are loaded into the memory as well?

I mean that... now I understand that webpack dev server will check first to see if any static file (index.html in my case) in memory and use that file (when using htmlWebackPlugin that's exactly what's happening), 

but when the index.html is not found in memory (in case htmlWebpackPlugin is not used) ...

I can think of 2 scenarios:

A) if my contentbase is pointing to project-folder/public/ where my index.html is located,

then webpackDevServer will **load the local project-folder/public/index.html file to the "root" of memory and serve it from memory**

B) The index.html will be **served from the local file system (project-folder/public/) ** directly without loading it to memory**

is my (A) analysis right?

**Comment by jantimon** [comment]
I haven't looked into the webpack-dev-server sources recently so unfortunately I don't know the internals out of my head.  
Could you please take a look and let me know?  
It's an interesting question. My guess is that they will use [`express.static`](https://expressjs.com/en/starter/static-files.html) or something similar.
