### ISSUE TITLE
Change favicon rel type

### ISSUE THREAD

**Issue by Vladi4-gh** [jantimon/html-webpack-plugin#1412]
The shortcut link type is often seen before icon, but this link type is non-conforming, ignored and web authors must not use it anymore.

https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types

**Comment by jantimon** [comment]
What does that mean for this project?

**Comment by Vladi4-gh** [comment]
`shortcut icon` type is obsolete, `icon` is modern one.

**Comment by jantimon** [comment]
I guess you propose to change it here right?

https://github.com/jantimon/html-webpack-plugin/blob/96e0ae607afa7295c40d0a5073c791189def6337/index.js#L770-L777

Is `icon` supported by IE11?

**Comment by jantimon** [comment]
Just checked and it looks like you are totally right - since IE9 all browsers support `icon`: https://en.wikipedia.org/wiki/Favicon#How_to_use

Do you want to create a pull request for this?

**Comment by Vladi4-gh** [comment]
> Do you want to create a pull request for this?

I tried but I couldn't create branch in your repository so I think I can't, and you have to do it by your own.

**Comment by jantimon** [comment]
In Github you need to follows these steps to create a pull request:

1. Fork the repository 
2. Clone the forked repository
3. Change the code 
4. Push it to the forked repository 
5. Go to the original repository and create the pull request

**Comment by Vladi4-gh** [comment]
Here it is 
https://github.com/jantimon/html-webpack-plugin/pull/1420

**Comment by jantimon** [comment]
I fixed the tests :)

According to the [usage table](https://en.wikipedia.org/wiki/Favicon#How_to_use) we need to add the type too:

<img width="520" alt="favicons" src="https://user-images.githubusercontent.com/4113649/80583934-3b2b6c00-8a11-11ea-9bff-df57c38fcb08.png">

Do you know if IE11 will work without the `type` for `gif` and `png`?

**Comment by Vladi4-gh** [comment]
Seems like it works in IE11
![image](https://user-images.githubusercontent.com/20474669/80616874-14d5f280-8a4a-11ea-90c0-11ef9c9d5d2d.png)
![image](https://user-images.githubusercontent.com/20474669/80616889-1a333d00-8a4a-11ea-925c-93a2c74a0039.png)

**Comment by jantimon** [comment]
Cool thanks for testing 👍

**Comment by Vladi4-gh** [comment]
Well, it merged. I close the issue.
