### ISSUE TITLE
JS files are not placed in the head section of the generated html

### ISSUE THREAD

**Issue by rowild** [jantimon/html-webpack-plugin#1413]
## Expected behaviour

Tell us what you would expect the html-webpack-plugin should.

I want to place specific javascript (e.g. a vendor.js) into the head of the html. Therefore I append `_head` to the filename:

```javascript
module.exports = {
  entry: {
    app_head: './src/scripts/appCss.js',
```

which should do the job according to the html-webpack-injector, a dependency of html-webpack-plugin, documentation:
 https://github.com/thearchitgarg/html-webpack-injector

## Current behaviour

The files are *not* placed into the head section of the generated html file, but instead before the closing body tag.

## Environment

darwin 17.7.0 (mac OS 10.13.6)
Node.js v12.16.1
npm 6.14.4
webpack@4.43.0
html-webpack-plugin@3.2.0

### Config

Copy the minimal `webpack.config.js` to produce this issue:

See above.

Is this functionality implemented at all? Or do you recommend a different approach? 
Unfortunately it seems there is no documentation about that...

**Comment by jantimon** [comment]
Usually you would add all scripts to the end of your body tag to make sure that the DOM is ready once the scripts are executed.

Why do you want to add the scripts into the head?

**Comment by rowild** [comment]
No, vendor scripts can and should be in the head, also matomo etc. But that is not the question here.

**Comment by jantimon** [comment]
You should not add scripts to the head.

The reason is that those scripts could theoretically change the DOM.  
So to ensure that the browser has the correct dom it has downloaded and executed the javascripts inside the head.

This will cause an additional delay for your users and will be shown as an error in performance utils like lighthouse.

However if you still want to do it anyway the html-webpack-plugin options allow to do that.  

**Option 1:**  
Inject all scripts into the head:

```js
new HtmlWebpackPlugin({
   inject: 'head'
})
```

**Option 2:**  
Inject nothing and handle the injection manually:

```js
new HtmlWebpackPlugin({
   inject: false
})
```

```html
<html>
  <head>
    <%= htmlWebpackPlugin.tags.headTags %>
    <%= htmlWebpackPlugin.tags.bodyTags %>
  </head>
  <body>
  </body>
</html>
```

**Comment by rowild** [comment]
I appreciate your advice, but I know what I am doing. So please let's stick with the question and not start a discussion about whether to inject scripts into the head or not? Thank you!

Option 1 is a no-go, because I do not want all script in the head, only those, which have `_head` appended to the name. As mentioned before: according to the documentation of html-webpack-injector, which is a dependency of html-webpack-plugin (as mentioned in the html-webpack-plugin documentation), this should be working.

So I wonder, why this is not working? Is it a bug? Or is it intentionally not supported?

Option 2 I need to study and experiment with. Thanks for providing a snippet!

I think this topic should somehow be mentioned in the documentation, since there is already a link to the html-webpack-injector plugin, which does not seem to work as expected.

**Comment by jantimon** [comment]
Please note that your html-webpack-plugin version seems to be outdated.  
The solution described in `Option 2`  requires html-webpack-plugin 4.x.

Unfortunately you seem to know more about the `html-webpack-injector` than I do.  
I have never used it before. Please ask the author of that plugin why it is not working. Thank you.

**Comment by rowild** [comment]
I didn't realise that I have an old version installed - thank you for bringing that to my attention, @jantimon ! it does not solve the problem, but got to know anyway.

I thought that dependencies' functionality is always supported by those libs/plugins etc that use it. My fault of thinking so, so I will take your advice and head over to html-webpack-injector and post my question there. Even though i have the feeling that i will get the answer that the lib that uses it, has to implement the function...

**Comment by rowild** [comment]
Since i do not receive an answer at the `html-webpack-injector`, I will close this issue and follow your advice.
Thank you again!
