### ISSUE TITLE
webpackHotUpdate is not defined since 4.0.0

### ISSUE THREAD

**Issue by pbadenski** [jantimon/html-webpack-plugin#1415]
We started getting a random `webpackHotUpdate is not defined` since upgrading from `3.2.0` to `4.0.0`. I'm confident this would be the problem - I experimented with different configurations and narrowed the error down to this single change.

I managed to predictably reproduce it when a hot update cannot be applied and webpack attempts a full page reload:

```
VM269772 index.js:73 [HMR] Cannot apply update. Need to do a full reload!
[HMR] Error: Aborted because ./app/src/ui/monitoring/metrics.ts is not accepted
main.58f60cde2ee4cdb33316.hot-update.js?8f823c75f1ca1190dcec:1 Uncaught ReferenceError: webpackHotUpdate is not defined
    at main.58f60cde2ee4cdb33316.hot-update.js?8f823c75f1ca1190dcec:1
```

## Environment

```
Node.js v13.13.0
darwin 19.4.0
6.14.4
ui@1.0.0 /Users/pbadenski/workspace/pricingmonkey/app
└── webpack@4.42.1 

ui@1.0.0 /Users/pbadenski/workspace/pricingmonkey/app
└── html-webpack-plugin@4.0.0 
```

**Comment by jantimon** [comment]
Thanks for your feedback - any idea what might have caused this problem?

**Comment by pbadenski** [comment]
Unfortunately this is as much detail as I managed to discover so far... I'll keep you updated if I manage to get something for specific.

**Comment by jantimon** [comment]
I discovered that this part was removed:

https://github.com/jantimon/html-webpack-plugin/blob/e2c6990e94b298ff66bcd885c9a03a78221479f6/index.js#L123-L128

Can you please check if that bug is fixed once you add that back into `node_modules/html-webpack-plugin/index.js` and restart your webpack dev server?

**Comment by pbadenski** [comment]
I just checked.

This part seems to still be present on 4.0.0:
https://github.com/jantimon/html-webpack-plugin/blob/eb73905d4a0f031ded7a7d235d3fb2c761267cc0/index.js#L192-L197

`index.js` via
https://github.com/jantimon/html-webpack-plugin/tree/eb73905d4a0f031ded7a7d235d3fb2c761267cc0 which points to `4.0.0` release branch

**Comment by jantimon** [comment]
I applied a patch in `4.2.1` in #1418  can you please try if this also fixed your problem?

**Comment by pbadenski** [comment]
Checked, looks to me like it's fixed, yay! Thank you!
