### ISSUE TITLE
Since #1331 merged, templateParameters example is out-of-date

### ISSUE THREAD

**Issue by genderquery** [jantimon/html-webpack-plugin#1416]
Since #1331 was merged, `templateParameters` will merge a given object with the default parameters. In the [example ](https://github.com/jantimon/html-webpack-plugin/tree/master/examples/template-parameters) for this option, [the comment about defaults not being merged](https://github.com/jantimon/html-webpack-plugin/blob/96e0ae607afa7295c40d0a5073c791189def6337/examples/template-parameters/webpack.config.js#L14) is no longer correct.

I'm not sure if the comment should be updated to reflect this new feature or the comment simply removed and the example rewritten as follows:

```javascript
plugins: [
  new HtmlWebpackPlugin({
    templateParameters: {
      'foo': 'bar'
    },
    template: 'index.ejs'
  })
]
```

**Comment by jantimon** [comment]
Oh you are right - could you please create a pull request?
