### ISSUE TITLE
Ability to also include/exclude cacheGroups

### ISSUE THREAD

**Issue by iongion** [jantimon/html-webpack-plugin#1421]
**Is your feature request related to a problem? Please describe.**
There is currently no way to exclude chunks coming not only from entry points but also from optimization cacheGroups.
If all unit tests are extracted into a cacheGroup chunk, it is useless to import them in every html page.

**Describe the solution you'd like**
`cacheGroups` should be considered too or provide an option for it.

**Describe alternatives you've considered**
Set `{ "inject": false }` and do it manually, but is very very hard

**Comment by jantimon** [comment]
I haven't used cacheGroups at all can you provide a code sandbox with an example similar to this one?

https://codesandbox.io/s/html-webpack-plugin-body-tag-filtering-fuzxb

**Comment by iongion** [comment]
@jantimon sure, here it is https://codesandbox.io/s/html-webpack-plugin-body-tag-filtering-wwrpf?file=/webpack.config.js

**Comment by jantimon** [comment]
Cool thanks 👍

Just out of curiosity - Why did you use a cacheGroup instead of a entry for the unit tests?

**Comment by iongion** [comment]
For pretty naming of chunks :)

[excl.zip](https://github.com/jantimon/html-webpack-plugin/files/4560499/excl.zip)

I found the issue, it was my weird case, this line

```tools.map(tool => import(`project-tools/${tool}`).then((mod) => console.debug(mod)));```

causes aggressive dynamic import, even spec file, this is the fix

```tools.map(tool => import(`project-tools/${tool}/index`).then((mod) => console.debug(mod)));```

So those chunks were there due to this.
