### ISSUE TITLE
templateParameters doesn't swap out the variable in index.html

### ISSUE THREAD

**Issue by iamnewton** [jantimon/html-webpack-plugin#1422]
## Expected behavior

_Tell us what you would expect the `html-webpack-plugin` should._

Swap out the `asset` variable in my template with the value `file.js`

## Current behavior

_Tell us what the `html-webpack-plugin` does instead._

It doesn't replace the value and instead leaves untouched.

## Environment

_Tell us which operating system you are using, as well as which versions of Node.js, `npm`, `webpack`, and `html-webpack-plugin`. Run the following to get it quickly:_

```
Node.js v13.8.0
darwin 18.7.0
NPM 6.13.7
Webpack 4.43.0
html-webpack-plugin 4.2.1
```

### Config

_Copy the minimal `webpack.config.js` to produce this issue:_

```js
module.exports = {
  entry: path.resolve(__dirname, 'src/index.js')
  mode: 'production',
  optimization: {
    splitChunks: {
      chunks: 'all',
    },
  },
  output: {
    path: path.resolve(__dirname, 'www'),
    filename: '[name].[hash].js',
  },
  module: {
    rules: [{
      test: /\.js$/,
      use: { loader: 'babel-loader' },
    }, {
      test: /\.html$/,
      use: [{
        loader: 'html-loader',
        options: { minimize: true },
      }],
    }],
  },
  plugins: [
    new CleanWebpackPlugin(['www']),
    new HtmlWebpackPlugin({
      meta: {
        charset: 'utf-8',
        viewport: 'width=device-width, initial-scale=1',
      },
      title: 'My Page',
      template: './src/index.html',
      templateParameters: {
        asset: 'file.js',
      },
    }),
    new HtmlWebpackTagsPlugin({
      links: [ 'https://cdn.example.com/styles/components.v3.25.0.css' ]
    }),
  ],
}
```

_Copy your template file if it is part of this issue:_

```html
<!doctype html>
<html lang="en">
    <head><script src="config.js"></script></head>
    <body>
        <div id="app" class="d-xs-flex flex-xs-column app"></div>
        <script>
            function getResources(filename) {
                var script = document.createElement('script');
                script.async = false;
                script.src = window.location.protocol + '//' + window.__config.cdnRoot + '/' + filename;
                document.body.appendChild(script);
            }
            getResources('<%= asset %>');
        </script>
        <%= htmlWebpackPlugin.files.js %>
    </body>
</html>

```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Additional context

_Add any other context about the problem here._

I'm pretty sure I'm doing something wrong here, but thought I'd reach out in the event I had actually found something.

**Comment by iamnewton** [comment]
Sorry, a bit of a noob with `webpack`, but I think this might be due to the fact that I'm also using `html-loader`, which appears to be unnecessary unless I'm importing HTML files into a JS file?

**Comment by jantimon** [comment]
That’s right the html-loader doesn’t know how to handle the `<%=` tag and will just ignore it.

Here is an example which might help:

https://github.com/jantimon/html-webpack-plugin/tree/master/examples/custom-insertion-position

As you see it is using .ejs as file extension to prevent conflicts with the html-loader but you can also just remove the html-loader if you don’t need it to inline html into you javascript

**Comment by iamnewton** [comment]
Perfect. Is that the intended use case for loaders? To inject a type of media into your JavaScript app?

**Comment by jantimon** [comment]
Correct - you can load for example images or templates and inline them in your application.

**Comment by iamnewton** [comment]
Thanks. You can close this issue.
