### ISSUE TITLE
Regenerating the HTML file when a different file changes.

### ISSUE THREAD

**Issue by ObsydianBlackKnight** [jantimon/html-webpack-plugin#1429]
I'm trying to write my first Webpack plugin to modify the HTML page depending on the content of a JSON configuration file.

I'd like to regenerate the HTML code whenever the JSON file changes, but couldn't find a way to do this.

Is it possible to achieve what I need?

**Comment by jantimon** [comment]
Does it have to be a plugin?  
Because that would be harder than if you do the following:

```js
new HtmlWebpackPlugin({
  template: 'template.js' // <-- use a javascript or typescript file as template
})
```

template.js
```js
const data = require('./some/data.json');
module.exports = (templateVariables) => `<html>
  <head>
     <title>Demo</title>
  </head>
  <body>
     ${data.name}
  </body>
</html>`
```

**Comment by ObsydianBlackKnight** [comment]
Thanks for your reply. What you're suggesting is a very clever solution.

I have another problem though:

1. I'd strongly prefer keeping the HTML code (PUG code, actually) in a separate file, to take advantage of my editor support (syntax highlighting, autocompletion etc). I could require/import the PUG file, but:
2. I have multiple PUG files I'd like to process with the same function.

I can't pass the PUG file path as a template parameter because it's a dynamic expression and Webpack is unable to require it.

Can you think of any solutions for this case?

**Comment by jantimon** [comment]
Sure - you can use the pug-loader from within your javascript file.  
And webpack provides a way to load multiple files from a folder using a dynamic require.  

The HtmlWebpackPlugin would always use the same `template.js` and provide a new variable (I called it `page` but you can also rename it):

```js
new HtmlWebpackPlugin({
  template: 'template.js',
  templateParameters: {
     page: 'home'
  }
}),

new HtmlWebpackPlugin({
  template: 'template.js',
  templateParameters: {
     page: 'about-us'
  }
})
```

Inside your `template.js` you can now make use of the `page` variable:

```js
const data = require('./some/data.json');

module.exports = (templateVariables) => {
    // Load template
    const pugTemplate = require(`./some/folder/${templateVariables.page}.pug`);
     // Execute template
    const pugHtml = pugTemplate(templateVariables);
     // Any processing could go here:
    const processedHtml = pugHtml + data.name;
     // Return the final html
    return pugHtml;
}
```

Please let me know if this case works well for you.

**Comment by ObsydianBlackKnight** [comment]
Thanks for your further help. I know the folder with my pug files statically, but can't hardcode it in the JavaScript template file because I'm planning to keep the latter in its own package and require it from a few different ones.

Maybe I can keep the processing logic in an external package and place a wrapper in every package that needs it:

```
// file index.js in "my-logic" NPM package
module.exports = ( html, data ) => {
  return pugHtml + data.name;
};
```

```
// file template.js in every project using webpack and needing "my-logic"
const myLogic = require('my-logic');
const data = require('./some/data.json');

module.exports = (templateVariables) => {
  const html = require(`./some/folder/${templateVariables.page}.pug`);
  return myLogic( html, data );
};
```

A more generic solution could help other plugins with similar use cases (e.g. html-webpack-inline-source-plugin and html-webpack-inline-svg-plugin), but if only very few users are affected then it's definitely not worth it.

Thank you fer helping me reach the solution we found. That works for me. From my side, I'm happy to close the issue.

**Comment by jantimon** [comment]
Okay I can show you some more ideas.

Move the template into its own npm module:

```js
new HtmlWebpackPlugin({
  // you can move the template into a npm module:
  template: require.resolve('my-logic-template/template.js'),
  templateParameters: {
     page: 'about-us'
  }
})
```

And you can use a loader (in your current package or in a foreign node_module) to get access to the full loader api https://webpack.js.org/api/loaders/

I haven't tested the code so probably it is not working on first try but maybe it leads you into the right direction:

```js
new HtmlWebpackPlugin({
  //  !! means use no other loader
  //  require.resolve      will return the absolute path to loader.js 
  //  ?foo/data.json       is sent as query to the loader
  //  !./src/template.js   is the final template
  template: '!!' + require.resolve('my-logic/loader.js') + '?foo/data.json!./src/template.js',
  templateParameters: {
     page: 'about-us'
  }
})
```

my-logic/loader.js
```js
const fs = require('fs');
module.exports = function(templateContent) {
   const jsonPath = this.query.replace(/^\?/, '');
   // If the json is a dependency it will be watched:
   this.addDependency(jsonPath);
   const jsonContent = fs.readFileSync(jsonPath, 'utf-8');
   // A loader has to return a javascript module as a string:
   return `
      var logic = require('./logic.js');
      module.exports = function (templateVariables) {
          return logic(
             require('!!pug-loader!${this.resourcePath}')(templateVariables),
             ${JSON.stringify(jsonContent)}
           );
      }
   `; 
};
```

my-logic/logic.js
```js
// file index.js in "my-logic" NPM package
module.exports = ( html, data ) => {
  return pugHtml + data.name;
};
```

**Comment by ObsydianBlackKnight** [comment]
Ohh, that's awesome! Had no idea about this syntax for webpack loaders.

I'll start experimenting with it and will try having my package generate the loader string too:

```
new HtmlWebpackPlugin({
  template: require('my-logic').template({ data:'foo/data.json', src:'./src/template.js' }),
  templateParameters: {
     page: 'about-us'
  }
})
```

I'll post here my working code, if I manage to make it work.

**Comment by jantimon** [comment]
Cool - keep me posted! :)

**Comment by ObsydianBlackKnight** [comment]
Eventually I made a pretty generic loader which calls a template passing it any number of resources tracked by webpack.

`my-loader/index.js`:
```javascript
const querystring = require('querystring');

module.exports.template = (template, data)=>{
	const loader = require.resolve('./loader.js');
	const query = querystring.stringify(data);

	return `${loader}?${query}!${template}`;
};
```

`my-loader/loader.js`
```javascript
const path = require('path');
const querystring = require('querystring');

function esc( str ) {
	return JSON.stringify( str );
};

module.exports = function( templateContent ) {
	const data = querystring.parse( this.query.substr(1) );
	const template = this.resource;

	// resolving all resource paths
	for( let key in data ) {
		if( ! path.isAbsolute(data[key]) ) { // TODO: mishandles npm packages
			data[key] = path.join( this.rootContext, data[key] );
		}
	}

	return `
module.exports = (templateParameters)=>{
	const data = {
		${
			Object.entries( data )
				.map( ([key,value])=>`${esc(key)}: require(${esc(value)})` )
				.join(', ')
		}
	};

	const template = require( ${esc(template)} );
	return template( data, templateParameters );
}
	`;
};
```

`./webpack.config.js`:
```javascript
const loader = require( 'my-loader' );
new HtmlWebpackPlugin({
	template: loader( './src/template.js', {
		html:'./pug/index.pug', data:'./data.json'
	}),
}),
```

`./src/template.js`:
```javascript
module.exports = ( {html, data}, templateParameters )=>{
  return html() + data();
};
```

**Comment by jantimon** [comment]
Cool so you basically allow to extend the template parameters with any additional data from json and javascript files... really nice

one idea to allow also files from npm packages:

```js
function getAbsolutePath(modulePath, context) {
 try {
    return require.resolve(modulePath);
  } catch (e) {}
  if(!path.isAbsolute(modulePath) ) {
     return path.resolve(context, modulePath);
  }
  return modulePath;
}
```

And maybe you can add it directly to the template parameters:

```js
return template(Object.assign({}, templateParameters, myLoader: data));
```

That way you could even use it without a custom js template:

`pug-loader!my-loader?foo=data/barjson!index.pug`

and inside `index.pug`:

```html
p #{myLoader.foo.name}
```

**Comment by ObsydianBlackKnight** [comment]
I'm not sure whether the `getAbsolutePath()` you're proposing is correct. If you pass it `"./index.js"`, it'll resolve it to `my-loader/index.js` rather than the `index.js` in your project. Maybe checking whether the path starts with `.` might do the trick, not fully sure. I think I'll fix it incrementally when it breaks.

You're right about setting those vars in `templateParameters`. I was afraid of overriding existing members, but I guess spitting out a warning in that case will be enough.

By the way, I read [here](https://webpack.js.org/concepts/loaders/#loader-features) that:

> Loaders can be configured with an options object (using query parameters to set options is still supported but has been deprecated).

I fear that the solution we found might stop working in the future, e.g. in Webpack 5. In case you want to fully support loaders such as the one we're discussing, maybe you can add a `loader` parameter to this plugin which takes a loader object.

**Comment by jantimon** [comment]
Oh you are right - i haven't thought about the `./index.js` resolving.  
Probably `modulePath.substr(0, 1) !== '.'` would fix that just like you proposed.

For the querystring you can use `parseQuery` from https://www.npmjs.com/package/loader-utils it will handle both formats correctly.

**Comment by godbout** [comment]
> Does it have to be a plugin?
> Because that would be harder than if you do the following:
> 
> ```js
> new HtmlWebpackPlugin({
>   template: 'template.js' // <-- use a javascript or typescript file as template
> })
> ```
> 
> template.js
> 
> ```js
> const data = require('./some/data.json');
> module.exports = (templateVariables) => `<html>
>   <head>
>      <title>Demo</title>
>   </head>
>   <body>
>      ${data.name}
>   </body>
> </html>`
> ```
> 
> This example would watch `./some/data.json` for changes.

THANK YOU!

great option.
