### ISSUE TITLE
meta viewport bug

### ISSUE THREAD

**Issue by maystrenkoYurii** [jantimon/html-webpack-plugin#1430]
if used meta property array configs => generated meta tags from my confin + viewport
but my config is includes viewport
![Снимок экрана от 2020-05-03 17-27-23](https://user-images.githubusercontent.com/23016311/80916785-9a67e400-8d63-11ea-8317-1803e82c6a3b.png)
![Снимок экрана от 2020-05-03 17-29-25](https://user-images.githubusercontent.com/23016311/80916796-a784d300-8d63-11ea-9cd9-39dd4f823775.png)

**Comment by jantimon** [comment]
Oh good point - seems we shouldn't use any defaults if an array is used.

Would you like to prepare a pull request?

For now you can do the following:

```js
meta: {
 'viewport': 'width=device-width, initial-scale=1, shrink-to-fit=no',
 'X-UA-Compatible': { 'http-equiv': 'X-UA-Compatible', content: 'IE=edge },
}
```
