### ISSUE TITLE
Handle relative url as modules without using html-loader in order to use templateParameters

### ISSUE THREAD

**Issue by FedericoMameliPrjs** [jantimon/html-webpack-plugin#1431]
## Expected behaviour
Should have the possibility to use the lodash "template engine" with templateParameter and external loader (like html-loader) to import static files, like images, in order to make them be handled by webpack and included in the final bundle.

## Current behaviour
If I use html-loader it processes images, but not compile the "lodash variables" and not injects the bundle generated by webpack. 
If I **NOT** use html-loader, webpack not resolve relative paths in src attirbutes (or like src) and not include static files like images.

## Environment
I'm on Windows 10, node 10.16.3, webpack 4.41.5, npm 6.13.7 and html-webpack-plugin 4.2.1.

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  entry: {
     app: './src/js/index.js'
  },
  output: {
    path: 'dist',
    filename: '[name].js'
  },
  module: {
    rules: [
      ...
      {
        test: /\.(jpg|jpeg|png|svg)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]'
            }
          }
        ]
       },
      {
        test: /\.html$/,
        loader: 'html-loader'
      }
    ]
  }
  plugins: [
    new HtmlWebpackPlugin({
      template: './public/index.html',
      inject: false,
      templateParameters: {
        //...myDataObject
      },
    })
    ...
  ]
}
```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
        <%= htmlWebpackPlugin.tags.headTags %>
    </head>
    <body>
      <img src="./../images/image.png"><!--Should be handled by webpack and file-loader-->
     
       <%= htmlWebpackPlugin.tags.bodyTags %><!--should output <script src="/app.js"></script>
        <script>
         //......
         </script>
    </body>
</html>
```

**Comment by jantimon** [comment]
Unfortunately that is true those loaders are hard to combine.

I am not sure if that would work well for you but what you can do is the following (without the html-loader):

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
        <%= htmlWebpackPlugin.tags.headTags %>
    </head>
    <body>
      <img src="<%= require(./../images/image.png) %>">
       <%= htmlWebpackPlugin.tags.bodyTags %>
        <script>
         //......
         </script>
    </body>
</html>
```

**Comment by FedericoMameliPrjs** [comment]
mh.. ok.
Yes, I've tried and it works, thanks!

**Comment by temple** [comment]
@jantimon, your proposal doesn't work when `html-loader` is set for any `html` file.
It is a bit hard to understand why both loaders cannot be concatenated (_fallback ejs_ and _html-loader_). 
By the way, is it a bit late for requesting it as a feature? I mean, the ability to concatenate both loaders

**Comment by jantimon** [comment]
Unfortunately it is very hard to combine those loaders because the html loader analyses the code statically and the eis loader generated a non static template.

However feel free to give it a try and write a loader which can consume both formats :)

If your problem is that your .html file loader settings are different for your html-webpack-plugin settings you have three options:

1. Use a different file extension for your template:
`new HtmlWebpackPlugin({ template: 'index.ejs' })`
2. Use the !! syntax
`new HtmlWebpackPlugin({ template: '!!some-loader!index.html' })`
3. Add an exclude rule to your loader

**Comment by temple** [comment]
Thank you @jantimon. I'll give a try
