### ISSUE TITLE
MInify incorrectly strips required type attribute from inline `<script type="module">`

### ISSUE THREAD

**Issue by thw0rted** [jantimon/html-webpack-plugin#1434]
## Expected behaviour

Default behavior should not break execution of inline ESM modules.

## Current behaviour

If you load the tag `<script type="module">` without altering the `minify` options, the type will get stripped.  The result, `<script>import { foo } from "./bar.js"; ...</script>`, is a syntax error.

## Environment

* Node.js v12.7.0
* win32 10.0.18363
* webpack@4.43.0
* html-webpack-plugin@4.3.0

### Config / Relevant Links

See this [minimal reproduction](https://github.com/thw0rted/issue-examples/tree/webpack-html-modules) -- just `npm install` then run `webpack`.  Note that in the output, the `script` tag has no `type` attribute, so it will fail to execute because `import` is only allowed in a `module` context.

## Additional context

You can paste [index.html]() into this [online minifier](https://kangax.github.io/html-minifier/), which I believe is supposed to be backed by the same library as this plugin uses for minification. The `type` attribute is left intact.  That suggests that either we're not using a current version of the library, or this plugin doesn't use the same default options when calling the minifier.

**Comment by thw0rted** [comment]
Update: it looks like I was wrong and instead of the Kangax `html-minifier` you're using [this one](https://github.com/DanielRuf/html-minifier-terser), where this problem is a [known issue](https://github.com/DanielRuf/html-minifier-terser/issues/31).  I'm asking them for clarification now.

**Comment by jantimon** [comment]
Oh that sounds horrible - lets see if they are able to fix it.  
Otherwise we need to adjust the default minifcation settings.

**Comment by thw0rted** [comment]
The author put together https://github.com/DanielRuf/html-minifier-terser/pull/40 very quickly, and I think once that's merged it should fix my original problem.

**Comment by DanielRuf** [comment]
This should work now in v5.1.1 which keeps this attribute and its value and strips the others.

**Comment by jantimon** [comment]
Cool so all we need to do to close this issue is to upgrade to 5.1.1?

**Comment by thw0rted** [comment]
It sounds like that's the case, yeah.

**Comment by jantimon** [comment]
Cool would you like to create a pull request which updates the version and adds an additional unit test?

**Comment by thw0rted** [comment]
I cloned the master branch and `npm run test` is behaving strangely.  First run errored with [two faliures](https://gist.github.com/thw0rted/ce452c3d6089d7bc391afff890e0f425), but I figured maybe it was just One Of Those Windows Things, like when sometimes a Git checkout fails because it thinks it can't write to a subdirectory somewhere, but just running the checkout again is fine.  So I ran it a second time and [the result was much worse](https://gist.github.com/thw0rted/e616537c31cf26331912f44a815fe029).  Some of the tests referenced appear to be timing-based; is it possible that they only succeed if you're not doing other stuff with your CPU while the tests run?

**Comment by jantimon** [comment]
Actually it compares the first run with the second run so a slow cpu should not be a problem..
If you create a pull request all tests will be run by travis so maybe that way it is easier.

**Comment by thw0rted** [comment]
Ah, I was trying to do green-red-green testing, and I fell down at step 1.  I figure my test isn't much good if I can't verify that it fails before the dependency upgrade and passes after, right?

**Comment by jantimon** [comment]
correct - you would have to:

1. create a new test 
2. commit and push it
3. create a pr
4. see it fail
5. upgrade dependency
6. see it succeed
7. 🎉

**Comment by DanielRuf** [comment]
>     5\. upgrade dependency

Ehm, the SemVer selector already picks up the 5.x releases so not sure what you mean:

https://github.com/jantimon/html-webpack-plugin/blob/master/package.json#L56

**Comment by DanielRuf** [comment]
>  5. upgrade dependency

Ehm, the SemVer selector already picks up the 5.x releases so not sure what you mean:

https://github.com/jantimon/html-webpack-plugin/blob/master/package.json#L56

![image](https://user-images.githubusercontent.com/827205/81941622-5beee680-95f9-11ea-9c3c-39598c551954.png)

**Comment by jantimon** [comment]
Oh correct - but I guess an additional test wouldn’t hurt :)
