### ISSUE TITLE
can't use require() anymore

### ISSUE THREAD

**Issue by crazyx13th** [jantimon/html-webpack-plugin#1435]
### Description

Hi there,

I have the Problem that I can't use **require()** anymore since **4.0.0**
I get '${require(...)}' inside my output
At 3.2.0 is was working...

Is this a "breaking change"?
What is "the best pracice" now?
Thanks!!

Greetings
crazyx13th

### Config

```js
plugins: [new HtmlWebpackPlugin({
	filename: '../server/index.tpl',
	template: 'src/index.html',
	templateParameters: (): any => ({appName, appVersion, buildHash}),
	inject: false,
	xhtml: true,
	showErrors: true,
	minify: {
		collapseWhitespace: true,
		removeComments: true,
		minifyCSS: true,
		minifyJS: true,
	},
})],
```
template file:

```html
<!DOCTYPE html>
<html>
	<head>
		<style>${require('./preloader/preloader.scss').default}</style>
	</head>
	<body>
		${require('raw-loader!./preloader/preloader.html').default}
		<div id="»am"></div>
	</body>
</html>

```

## Environment

nodejs v12.13.0
npm 6.12.0
win 10

**Comment by crazyx13th** [comment]
ah ok, I can use <%=   ... %>, but looking ugly inside intellij :-)

![grafik](https://user-images.githubusercontent.com/8912561/81826029-9b54fe80-9537-11ea-808c-9c1c7e38b131.png)

**Comment by jantimon** [comment]
That was a bug fix to help people using `${...}` inside inline javascript code:

```html
<html>
<body>

<script>
const name = 'Hello'
console.log(`Hello ${name}`);
</script>
</body>
</html>
```

However you can use a loader which supports the old syntax.  
Maybe the https://github.com/emaphp/underscore-template-loader will work out of the box

**Comment by crazyx13th** [comment]
Ah ok! makes sense... thanks for the info!
Can be closed, sorry
