### ISSUE TITLE
"webpackHotUpdate is not defined"  still exists in webpack 4.23.1

### ISSUE THREAD

**Issue by licongwell** [jantimon/html-webpack-plugin#1436]
## Description
when I change my JavaScript file. I can see this error log "webpackHotUpdate is not defined"。and I find the "XXX.update.js" is still append to the Html.
I saw this issues has fixed this problem in `4.2.1`,But it's a problem again!

In order to use html-webpack-plugin 4.3.0 ,I have to update the webpack to ` 4.43.0`

## Environment

node -- 10.12.0
webpack -- 4.23.1
npm -- 6.4.1
html-webpack-plugin --4.3.0

**Comment by jantimon** [comment]
So you don't want to update to webpack `4.43.0`?

**Comment by licongwell** [comment]
You mean that the `html-webpack-plugin `  must be used on the latest version of webpack. If it doesn't, it's going to be a problem in 'HMR'.

**Comment by jantimon** [comment]
Correct - the feature for the fix was done by webpack 👍 
If you don't have the latest version it is not fixed.

**Comment by licongwell** [comment]
Thanks ~~
