### ISSUE TITLE
How does html-webpack-plugin work with vue

### ISSUE THREAD

**Issue by HoehensteigerGames** [jantimon/html-webpack-plugin#1437]
hi,

i am new and using vue-cli 3 with webpack 4. If i implement the html-webpack-plugin in my vue.config.js the plugin is replacing my whole html body. I hosted the solution on my page:
https://hoehensteigergames.com

You can see that there is no body. I used the following configuration:
module.exports = {
        transpileDependencies: ["vuetify"],
        outputDir: "X:\\ClientBuild",
        css: {
            extract: { ignoreOrder: true }
        },
        configureWebpack: {
            entry: join(__dirname, "./src/main.ts"),
            output: {
                path: "X:\\ClientBuild"
            },
            plugins: [
                new BundleAnalyzerPlugin(),
                new HtmlWebpackPlugin({
                    title: "Höhensteiger Games",
                    inject: true
                }),
                new ResourceHintWebpackPlugin(),
                new HtmlCriticalPlugin({
                    base: "X:\\ClientBuild",
                    src: "index.html",
                    dest: "index.html",
                    inline: true,
                    minify: true,
                    extract: true,
                    width: 375,
                    height: 565,
                    penthouse: {
                        blockJSRequests: false
                    }
                })
            ]
        }
    };

May anyone can help me how to use/configure the plugin with vue? I also use Vuetify as UI Framework.

**Comment by jantimon** [comment]
What do you expect the html-webpack-plugin to generate?

It looks like you are providing an empty template.

Maybe this question would be better for stackoverflow.
