### ISSUE TITLE
Customizing chunk path

### ISSUE THREAD

**Issue by rafaelytakei** [jantimon/html-webpack-plugin#1441]
Hi, I'm currently trying to save my folder structure on production, but I'm running into a problem with paths. My current build folder looks like this: 

dist
 ┣ checkout
 ┃ ┣ checkout.1250022740c1f2b813b8.bundle.js
 ┃ ┣ checkout.1250022740c1f2b813b8.bundle.js.LICENSE.txt
 ┃ ┣ checkout.css
 ┃ ┗ checkout.html
 ┣ animations.1d4259b55977fa1e9653.bundle.js
 ┣ animations.1d4259b55977fa1e9653.bundle.js.LICENSE.txt
 ┣ animations.css
 ┣ animations.html
 ┣ index.b5619d26d74cdeec0170.bundle.js
 ┣ index.b5619d26d74cdeec0170.bundle.js.LICENSE.txt
 ┣ index.css
 ┣ index.html
 ┣ runtime.2c3d0415a90a938674ee.bundle.js

Basically, I have 3 pages (index, animations, checkout), with checkout being inside a 'checkout' folder. For that, I'm following [this](https://stackoverflow.com/a/45278943), which suggest me to have 3 entry points:

`index: src/index.js,
animations: src/animations.js,
checkout/checkout: src/checkout/checkout.js`

However, I'm running into some trouble on the checkout.html paths, which is importing

`./checkout/checkout.css , ./runtime....bundle.js ./checkout/checkout....bundle.js` 

when the right paths would be 

`../checkout/checkout.css , ../runtime....bundle.js ../checkout/checkout....bundle.js` 

(basically one folder up). I can change my publicPath from './' to '../', but then it would break the paths of the index.html and animations.html

Is there a way I can add that extra '.' I need on the paths using this plugin?

**Comment by jantimon** [comment]
What happens if you leave the `publicPath` empty?

**Comment by rafaelytakei** [comment]
With `publicPath` empty I end up getting something like this as my script src:

`../xampp/htdocs/my_project/dist/runtime...bundle.js ../xampp/htdocs/my_project/dist/checkout/checkout.css`

so it ends up adding almost the whole path to the file instead, which wouldn't work

**Comment by jantimon** [comment]
Looks like you are misusing the filename to copy the files to another directory - probably you should rather use the copy-webpack-plugin instead

**Comment by rafaelytakei** [comment]
Managed to get something working using multi-compiler! Ty!
