### ISSUE TITLE
showErrors example, is there one?

### ISSUE THREAD

**Issue by ddonahoevibrenthealth** [jantimon/html-webpack-plugin#1443]
It's late and maybe my brain is dead, but where is the example? I just looked through every one and don't see this parameter referenced anywhere.

Thanks!

--- Original Note:

In the examples folder :)

_Originally posted by @jantimon in https://github.com/jantimon/html-webpack-plugin/issues/328#issuecomment-221485627_

**Comment by jantimon** [comment]
What errors are you looking for?

The ones mentioned in the thread are related to rendering errors. Those errors happen if templates contain buggy rendering logic.

If you look for an example with logic inside templates you can take a look at the Template Support section in https://dev.to/jantimon/html-webpack-plugin-4-has-been-released-125d

**Comment by ddonahoevibrenthealth** [comment]
Ok, nevermind. What I asked didn't really make any sense in hindsight. Closing.
