### ISSUE TITLE
URL of chunck paths are not properly encoded using `path.join`

### ISSUE THREAD

**Issue by lsmenicucci** [jantimon/html-webpack-plugin#1445]
## Expected behaviour

URL of the injected chunk paths should be properly encoded. For example, a config like this
```js
new HtmlWebpackPlugin({
  // ...
  outputFilename: "popup.html",
  js: "/public/js/popup.js"
})
```
should generate a file with
```html
<!-- build/popup.html -->
<script src="../../public/js/modal.js"></script>
```

## Current behaviour

However, following the example, it actually outputs:
```html
<script src="../../public%5Cjs%5Cmodal.js"></script>
```

## Environment

Node.js v12.0.0
win32 10.0.19041
npm 6.9.0
webpack 4.43.0
html-webpack-plugin 4.3.0

### Config

[Minimal reproduction](https://github.com/lsmenicucci/hwp-encoding-issue)

**Comment by silent-tan** [comment]
webpack 4.46.0 meet this problem
