### ISSUE TITLE
Plugin recommendation

### ISSUE THREAD

**Issue by pomelott** [jantimon/html-webpack-plugin#1448]
i wonder if you can put the recommendation of my plugin [html-inline-entry-chunk-plugin](https://github.com/pomelott/html-inline-entry-chunk-plugin)  in your readme file, it can inline all the chunk files that the page needed. it strictly obey the SemVer,  and mainly used in multi-page application. this is a cli named [webpack-multi-page-cli](https://github.com/pomelott/webpack-multi-page-cli) which use html-inline-entry-chunk-plugin, so you can check it. finally i can promise that i will update and optimize it frequently. 

Thanks for reading.

**Comment by jantimon** [comment]
Cool :)

The readme contains only the configuration - do you have an example what the plugin does?

**Comment by pomelott** [comment]
you can view with this url [https://github.com/pomelott/html-inline-entry-chunk-plugin](https://github.com/pomelott/html-inline-entry-chunk-plugin), and there is a specific example [https://github.com/pomelott/webpack-multi-page-cli](https://github.com/pomelott/webpack-multi-page-cli)

**Comment by jantimon** [comment]
I can find only examples on how to configure it but no examples for the result.

When would I use the plugin?

**Comment by pomelott** [comment]
With splitChunkPlugin in multi-page applications, automatically add corresponding dependent js files and css files for different html files. There is no need to add a fixed chunk for the html configuration item in the html-webpack-plugin, because in a multi-page application according to different split logic, it is impossible to know which chunks different HTML needs to introduce
