### ISSUE TITLE
Update pages list when new page created (multipage setup)

### ISSUE THREAD

**Issue by mrlss** [jantimon/html-webpack-plugin#1450]
**Is your feature request related to a problem? Please describe.**
When develop multipage sites, newly created pages are not visible for webpack `cannot get ...`. I understand that all pages are processed during webpack runtime, but is is possible somehow to add those pages to webpack context while it already running?

**Describe the solution you'd like**
Once i created new page - i expect webpack + html-webpack-lugin automatically reload and start watching this page

**Additional context**
I can easily get newly created page path using chokidar event while watching templates directory, but i struggled with solution of how to add this page to context of plugin. I'm also not sure, is this possible at all :D

Thanks.

**Comment by jantimon** [comment]
Sorry but currently there is no way to do that..
