### ISSUE TITLE
file-watcher-api.js with webpack 5

### ISSUE THREAD

**Issue by artola** [jantimon/html-webpack-plugin#1456]
## Expected behaviour

Should not break.

## Current behaviour

```
(node:51039) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createSnapshot' of undefined
    at /Users/.../myproject/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13:36
    at new Promise (<anonymous>)
    at Object.createSnapshot (/Users/.../myproject/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:12:10)
    at /Users/.../myproject/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:219:35
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
Node.js v12.16.2
darwin 19.4.0
npm 6.14.4
webpack 5.0.0-beta.16
html-webpack-plugin 4.3.0
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  entry: 'app.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  module: {
    rules: [
      ...
    ]
  }
  plugins: [
    new HtmlWebpackPlugin(),  // <== nothing special
    ...
  ]
}
```

## Additional context

It seems something related to webpack v5 because with v4 it works.

**Comment by artola** [comment]
because having 2 different versions of webpack running alongside (wrong resolution).

**Comment by artola** [comment]
because having 2 different versions of webpack running alongside (wrong resolution).

**Comment by kulkarnipradnyas** [comment]
Its due to mismatch of webpack version, just check npm list webpack, you will get unmet dependencies written in one of the tree.In package.json put  "peerDependencies": {
    "webpack": "^5.35.1"
  }
