### ISSUE TITLE
accessing chunk names created by dynamic imports in template

### ISSUE THREAD

**Issue by tarponjargon** [jantimon/html-webpack-plugin#1457]
In the template, is there a way to access these non-entrypoint chunks that are created by "magic comment" dynamic import statements (like `webpackPreload`)?

![Screen Shot 2020-06-03 at 8 57 35 AM](https://user-images.githubusercontent.com/12751386/83664541-01550480-a57f-11ea-9251-09cd4a09cef4.png)

I've tried a variety of ways like:

`<%= htmlWebpackPlugin.files.chunks.detail%>`

or 

`<%= htmlWebpackPlugin.files.chunks.detail.entry %>`

(and others) and can't get anything to work.

I'm working on a "traditional" SSR'd site and I'm trying to figure out a way to get some of these to load in parallel to the main app chunk on critical landing pages (like a product page).  Rather than waterfall-ing the http requests main app -> chunks.

**Comment by michaelprescott** [comment]
I think we have a similar problem.  I've been trying to update the dev stack for an ancient (in JavaScript years) product.  My webpack config allowed me to generate multiple entry points correlated to multiple templates with granular control over the chunks injected into each.  In earlier versions, you could access chunks like this:
`
BEGIN: ./partials/partial-body-js
<%= JSON.stringify(htmlWebpackPlugin) %>

<% for (key in htmlWebpackPlugin.files.chunks) { %><%
if (htmlWebpackPlugin.files.jsIntegrity) { %>
    <script
    src="<%= htmlWebpackPlugin.files.chunks[key].entry %>"
    type="text/javascript"
    integrity="<%= htmlWebpackPlugin.files.jsIntegrity[htmlWebpackPlugin.files.js.indexOf(htmlWebpackPlugin.files.chunks[key].entry)] %>"
    crossorigin="<%= webpackConfig.output.crossOriginLoading %>"></script><%
} else { %>
    <script src="<%= htmlWebpackPlugin.files.chunks[key].entry %>" type="text/javascript"></script><%
} %><%
} %>
END: ./partials/partial-body-js
`
In the current version, it looks like the chunks property has been removed.  While trying to debug it, I found I could dump the HTMLWebpackPlugin object into the template like this:
`<%= JSON.stringify(htmlWebpackPlugin) %>` 

That shows something like this:
`
"files": {
    "publicPath": "",
    "js": [
      "runtime_v1.0.0_b20200720_012606.js",
      "index_v1.0.0_b20200720_012606.js"
    ],
    "css": ["index_v1.0.0_b20200720_012606.css"],
    "jsIntegrity": [
      "sha256-zp+kAIOuWz5LDh/aygUpHt9ZOWhHMGOix30b5CfKIss= sha384-KDWKqUzprRxkSHkM9pAZ0/kXzsq1Q3uzU+VJS0zOrmW4lWQ9K/9VP4nTWPr5s002",
      "sha256-4ssD5wJ2GOnu20q/U04Av6cCFnJKPumxn3f5YfrVMqk= sha384-8LfoFnh+SgtJaetig1AuD4413ZKGIOipxIZcRXmV85Vv77X0UExaJmMgDZIObUDT"
    ],
    "cssIntegrity": [
      "sha256-xOv884qYeZ3GseiFMFsyKqIEl6DpYsb1hdKDBL1XBWk= sha384-PnCauCcnQsOtoYbwirbx5+ov4x+A1jSsVgw8EyYKxzQirXnlhjWov4p2HJ9wlPSm"
    ]
  },
`

**Comment by undrafted** [comment]
@tarponjargon were you able to figure this out?

**Comment by jantimon** [comment]
A good solution is the https://github.com/principalstudio/html-webpack-inject-preload

**Comment by tarponjargon** [comment]
> @tarponjargon were you able to figure this out?

I ended up writing and ad-hoc "plugin" right in the webpack config.  It's pretty messy so I'll probably check out the solution that @jantimon posted

**Comment by undrafted** [comment]
Thanks. I figured the  dynamic chunk also gets included in the manifest.json file emitted by the `webpack-manifest-plugin`

**Comment by tarponjargon** [comment]
> Thanks. I figured the dynamic chunk also gets included in the manifest.json file emitted by the `webpack-manifest-plugin`

If you want to go the plugin route here's what worked for me.  It's not super pretty but gets the job done (story of my life i guess).  

	plugins: [
	  ...
	  {
	     apply(compiler) {
		  compiler.hooks.afterEmit.tap("Custom Chunk Processor", compilation => {
		      compilation.chunks.forEach(chunk => {
			  chunk.files.forEach(filename => {
			     console.log("CHUNKFILE", `${filename}`);
			     [APPEND PRELOAD/PREFETCH TAGS TO A FILE HERE, TO BE USED AS AN INCLUDE]
			  }
		      }
		  }
	       }
	    }
	]

**Comment by jantimon** [comment]
`compilation` is also available as a variable inside the html-webpack-plugin template
so you can do that also without writing a custom plugin :)

e.g. 

```
<%= compilation.chunks.map( (chunk) => chunk.name )  %>
```

or you could also prepare the variables which are get send into the plugin: 

```js
new HtmlWebpackPlugin({
      templateParameters: (compilation, assets, assetTags, options) => {

        const chunkNames = compilation.chunks.map(chunk => chunk.name);

        return {
          compilation,
          webpackConfig: compilation.options,
          htmlWebpackPlugin: {
            tags: assetTags,
            files: assets,
            options
          },
          
          chunkNames
        };  
      },

      template: 'index.ejs'
    })
```
