### ISSUE TITLE
It's no longer valid to use Compiler.hooks.emit to modify Compilation.assets

### ISSUE THREAD

**Issue by chenxsan** [jantimon/html-webpack-plugin#1459]
[webpack 5.0.0 beta.17](https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.17) was out with new hook `processAssets`. And according to the pull request here https://github.com/webpack/webpack/pull/10876,

> All modifications to compilation.assets should be done before the compilation is sealed.

> There is a hook Compilation.hook.processAssets for asset modifications/additional/removal, use that.

> It's no longer valid to use Compiler.hooks.emit to modify Compilation.assets. That will emit a deprecation warning now.

I see `html-webpack-plugin` use `compiler.hooks.emit` https://github.com/jantimon/html-webpack-plugin/blob/428f24d2eb053f5431c0d1b39c2d5e1eb0b1ffde/index.js#L130

Which means we might need to update it for webpack 5 in future?

**Comment by jantimon** [comment]
Thanks for the heads up 👍

Will be harder to support webpack 4 and webpack 5 at the same time

**Comment by jantimon** [comment]
This issue has been solved in html-webpack-plugin 5.x - right now there is only an alpha version available
