### ISSUE TITLE
Differents bastpath for generated assets

### ISSUE THREAD

**Issue by isonah** [jantimon/html-webpack-plugin#1466]
Hello,
First of all, thanks for the plugin. It make really life easier.
I'm dealing with an issue and i'm not sure how to handle it.
I have a configuration like that 

`targets.map(env => 
new HtmlWebpackPlugin({
                    filename: env.output,
                    template: env.template,
                    baseUrl: env.staticUrl,
                    minify: {
                   ...
            }}));`

The thing is, since the option "inject" is by default set to true, all my static urls (css, js) are injected with the same basePath "/".  
How can I tell  HtmlWebpackPlugin to consider the base url (here baseUrl) without passing "inject" to "false" and have to deal with injecting files with loops by my self ?

Thanks in advance.

**Comment by jantimon** [comment]
Usually you would generate all webpack files at once and use a copy plugin to move the entire package to the currect location.

That way all paths are correct.

Many plugins provide a `publicPath` option to overrule the default paths - maybe we should add the same for the html-webpack-plugin.

**Comment by isonah** [comment]
Thanks for repyling.
You right a defined option with html-webpack-plugin would make thing easier.
But, let me ask you this : is that publicPath also applies on the injected chunks (PreloadWebpackPlugin) during the runtime ?
Thanks.

**Comment by jantimon** [comment]
The publicPath used at runtime needs to be configured directly in the webpack output settings.

This setting is already being used in the current html-webpack-plugin path resolution.

**Comment by isonah** [comment]
Thanks guys I ended up by running three builds with differents targets [target].env which is more safer and "more natural". That also gave me control of compressing or not some files, dropping console.log from builds etc.
Have a nice one.
