### ISSUE TITLE
webpack.hash is not available since v4

### ISSUE THREAD

**Issue by rapidfixer** [jantimon/html-webpack-plugin#1473]
Before v4 it was possible to use this:
`<meta name="hash" content="<%= webpack.hash %>" />`

After updating to v4 it seems that _webpack_ template variable does not exist anymore.
What solution is recommended to use instead?

**Comment by jantimon** [comment]
You can access the `compilation` template variable.
You can log all available values - the simplest way would be:

```js
new HtmlWebpackPlugin({
  templateContent: (templateParameters) => {
     console.log(templateParameters)
     return '<html><body></body></html>';
  }
})
```

**Comment by comxd** [comment]
```js
const hash = templateParameters.compilation.hash;
```
