### ISSUE TITLE
Build Failure when using Module Federation

### ISSUE THREAD

**Issue by ScriptedAlchemy** [jantimon/html-webpack-plugin#1478]
## Expected behaviour

Should build project successfully

## Current behaviour

We run into some build issues when Module Federation is enabled alongside this plugin. I and a most users in the community who use MF have been running off my fork, which wasn't intended (untested dirty patch to make builds work)

## Environment

This impacts any environment, it's looping over entry chunks that it should not/is not doing it correctly for module federation 

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  entry: "./src/index",
  mode: "development",
  devServer: {
    contentBase: path.join(__dirname, "dist"),
    port: 3001,
  },
  output: {
    publicPath: "http://localhost:3001/",
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: "babel-loader",
        exclude: /node_modules/,
        options: {
          presets: ["@babel/preset-react"],
        },
      },
    ],
  },
  plugins: [
    new ModuleFederationPlugin({
      name: "app1",
      library: { type: "var", name: "app1" },
      filename: "remoteEntry.js",
      remotes: {
        app2: "app2",
      },
      exposes: {
        "./Button": "./src/Button",
      },
      // sharing code based on the installed version, to allow for multiple vendors with different versions
      shared: {
        ...deps,
        react: {
          eager: true,
          singleton: true,
          requiredVersion: deps.react,
        },
        "react-dom": {
          eager: true,
          singleton: true,
          requiredVersion: deps["react-dom"],
        },
      },
    }),
    new HtmlWebpackPlugin({
      template: "./public/index.html",
    }),
  ],
};
```

## Relevant Links

I've got a stack of repos this can be tested against https://github.com/module-federation/module-federation-examples/tree/master/bi-directional

## Additional context

I believe HTML webpack plugin attempts to include the container runtime in an incorrect manner.

**Comment by JulianWielga** [comment]
I see HtmlWebpackPlugin attach an entrypoint made by ModuleFederationPlugin ("remoteEntry.js"). by excluding this chunk you can avoid many problems. I can't find information anywhere if it's the right way, but I didn't notice any negative effects.

**Comment by jantimon** [comment]
Did you already try the latest alpha of html-webpack-plugin

**Comment by raspy8766** [comment]
I've tried this with the latest `stable`, `alpha`, `beta` versions and this is still failing. We're looking to use webpack module federation to with our new micro frontend architecture soon and we were hoping to use a stable version of `html-webpack-plugin` before we transition. Any idea when this will be supported in the future?
