### ISSUE TITLE
Html hot update

### ISSUE THREAD

**Issue by vin-ni** [jantimon/html-webpack-plugin#1480]
Hello,
is it possible to get the html updated on save?

Thanks!

**Comment by jantimon** [comment]
Unfortunately that’s not possible because we don’t know which changes to the html are caused by javascript...

But I am open to ideas to solve this

**Comment by vin-ni** [comment]
Sorry,
i meant the index.html

When I update it, it doesnt reload the page.

**Comment by jantimon** [comment]
Reloading should be possible however we would need help from the webpack core team to use the webpack-dev-server socket connection

**Comment by bebraw** [comment]
@vin-ni To "solve" this issue, I developed [webpack-add-dependency-plugin](https://www.npmjs.com/package/webpack-add-dependency-plugin). It allows you to make webpack aware of these kind of template files that are indirect dependencies to it and I've used it myself to solve a similar use case.

**Comment by jantimon** [comment]
Wow @bebraw that's cool - do you think we should use it directly with the html webpack plugin?

e.g.

```js
apply(compiler) {
  const webpackAddDependencyPlugin = new WebpackAddDependencyPlugin({ path: this.options.template });
  webpackAddDependencyPlugin.apply(compiler);
```

Will it trigger a reload?

**Comment by bebraw** [comment]
It’s worth a go. Check the internals of the plugin, it’s not doing much.

**Comment by bebraw** [comment]
@jantimon Did you find a solution for this in webpack 5?

**Comment by jantimon** [comment]
I checked the webpack-add-dependency-plugin but unfortunately it won’t help here as all files are already added by the html-webpack-plugin

An auto reload feature would need to be exposed by the webpack-dev-server however there is none :(

**Comment by bebraw** [comment]
> I checked the webpack-add-dependency-plugin but unfortunately it won’t help here as all files are already added by the html-webpack-plugin

Ok, I see.

> An auto reload feature would need to be exposed by the webpack-dev-server however there is none :(

Can you [open an issue at webpack-plugin-serve](https://github.com/shellscape/webpack-plugin-serve) describing what you would need? I am not sure if we can do it there but it's worth discussing at least.

**Comment by peteluffman** [comment]
Not sure if it helps anyone, but I got reloading working with webpack 5 by adding `injectClient: true` to my devServer config.

**Comment by alwxkxk** [comment]
With webpack 5,this setting is work for me:

```js
  devServer: {
    hot:true,
    open:true,
    watchFiles: ['src/**/*']
  },
```

- [webpack-dev-server github issue #3881](https://github.com/webpack/webpack-dev-server/issues/3881)
