### ISSUE TITLE
Async Functions / Promises

### ISSUE THREAD

**Issue by vin-ni** [jantimon/html-webpack-plugin#1481]
Hello,
is it possible to add support for async functions to the webpack config?

I've found some approaches on how to add it, but couldn't figure it out:
https://medium.com/@tanbt/configure-async-await-es7-in-webpack-4-78adfda46eac

Basically you add this to the entry: 
`entry: ["@babel/polyfill", "./src/app.js"],`

But i can't get it to work.

Thank you!

**Comment by jantimon** [comment]
Sorry I am not sure what you are asking for or how this relates to the html-webpack-plugin

**Comment by vin-ni** [comment]
I'd like to write code like that in the js file:
```
async function hello() { return "Hello" };
hello().then((value) => console.log(value))
```

**Comment by jantimon** [comment]
how does this relates to the html-webpack-plugin?

**Comment by vin-ni** [comment]
oh, I'm so sorry. This is the wrong repo. My bad.
