### ISSUE TITLE
[Question] updating link href with webpack publicPath in React build

### ISSUE THREAD

**Issue by llaenowyd** [jantimon/html-webpack-plugin#1487]
Hi, sorry somehow my google-fu is failing me.

I have an index.html template that includes the lines
```html
    <link rel="icon" href="favicon.png" />
    <link rel="manifest" href="/manifest.json" />
```
whether those should have the relative or absolute href I'm not sure as I'm seeing both variations

Trying to relocate the application to a (per webpack config) `publicPath` other than the root, the hrefs mentioned above aren't updated, so now I get some errors in the app at runtime where it's requesting these resources that don't exist at that path anymore.

For the same problem in the React jsx I was able to use ``src={`${__webpack_public_path__}/some.png`}`` and via Google for this case I turned up some mentions of `<%= htmlWebpackPlugin.files.publicPath %>`, but I'm not sure this is on point, I think this is handlebars syntax?  For completeness I found one example with
```html
  <link rel="manifest" href="<%= htmlWebpackPlugin.files.publicPath %>static/manifest.json">
```
I don't think I have anything in the stack here that would substitute this.  I also saw a "lodash syntax" mentioned but couldn't find it clearly documented or demonstrated in this case.  Also not sure there is actually an interpretation/substitution step happening during this build that would do anything with "lodash syntax".

Perhaps I'm coming at this wrong and it's typically solved in some other way.  Sorry to spam up your issues tracker with a random question.  🆘

**Comment by jantimon** [comment]
Not sure what you mean maybe you need the https://webpack.js.org/plugins/copy-webpack-plugin/ to relocate the files

**Comment by llaenowyd** [comment]
🤔  `CopyPlugin` copies the source files to the build directory.

I'm moving my application from (webpack) `output.publicPath` (default) '/' to a new public (URL) path

Like the difference between `github.com/` and `github.com/jantimon`

So then the problem to solve during the webpack is to use the webpack `output.publicPath` that is documented to be available via `htmlWebpackPlugin.files.publicPath` but it's not clear if that was the old version or if I really have to use a handlebars interpreter to process my index.html which has some link hrefs that need to be prefixed

**Comment by llaenowyd** [comment]
I notice html-loader doc shows how to use the `preprocessor` option to to call handlebars, that I don't really want as a new dependency to the app, but perhaps if that's kind of the right approach I can just do a `replaceAll('%_MY_OWN_PRIVATE_WILDCARD_%', publicPath)` 

I expected this would be available by some option.  For example where HtmlWebpackPlugin is *adding* a tag it uses its `baseUrl` option to prefix the href.  That's why I directed my question here, I thought it was really close to the solution I was looking for.

**Comment by llaenowyd** [comment]
the above worked
