### ISSUE TITLE
html-webpack-plugin cann't working with webpack-v5.0.0-bata.22

### ISSUE THREAD

**Issue by gapkukb** [jantimon/html-webpack-plugin#1488]
## Expected behaviour

can working with webpack v5

## Current behaviour

cann't working with webpack v5

## Environment

Node.js v12.16.3
win32 10.0.17763
npm v6.14.4
webpack@5.0.0-beta.22
 html-webpack-plugin@4.3.0

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
npm --version
npm ls webpack
npm ls html-webpack-plugin
```

Error information:
(node:32632) [DEP_WEBPACK_MAIN_TEMPLATE_GET_ASSET_PATH] DeprecationWarning: MainTemplate.getAssetPath is deprecated (use Compilation.getAssetPath instead)

I am ensure that problem because of the api changed of webapck v5 . Do you have plan to suit to webpack v5?

**Comment by jantimon** [comment]
Can you please see if this is fixed with html-webpack-plugin@5.0.0-alpha.2 and webpack@5.1.2?  
Please see also #1527
