### ISSUE TITLE
Multiple HtmlWebpackPlugin instances ignore the template property when using webpack-dev-server

### ISSUE THREAD

**Issue by NickWoodward** [jantimon/html-webpack-plugin#1489]
## Expected behaviour
When using multiple HtmlWebpackPlugin instances the template provided in the options object should be used when using webpack-dev-server

## Current behaviour
Only the first instance is using the template provided, the rest are using barebones <html> and <meta> tags and no other content. Each page is having it's css and js injected correctly though.

When not using webpack-dev-server each of the instances **are** using their respective templates

## Environment

node v12.16.3
npm 6.9.0
webpack 4.44.0
windows 10.0.17134

### Config
**webpack.common.js**
```
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: {
        common: './src/js/common.js',
        index: './src/js/index.js',
        about: './src/js/about.js',
        admin: './src/js/admin.js'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                use: 'babel-loader'
            },
            {
                test: /\.html$/,
                use: 'html-loader'
            },
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            filename: 'index.html',
            template: './src/index.html',     // works with webpack-dev-server
            chunks: ['index', 'common']
        }),
        new HtmlWebpackPlugin({
            filename: 'about.html',
            template: './src/about.html',    // doesn't work with webpack-dev-server
            chunks: ['about', 'common']
        }),
        new HtmlWebpackPlugin({
            filename: 'admin.html',
            template: './src/admin.html',     // doesn't work with webpack-dev-server
            chunks: ['admin', 'common']
        })
    ]
}
```
**webpack.dev.js**
```
const common = require("./webpack.common");
const { merge } = require("webpack-merge");

module.exports = merge(common, {
    module: {
        rules: [
            {
                test: /\.scss$/,
                use: ["style-loader", "css-loader", "sass-loader"],
            },
        ],
    },
});
```
**webpack.prod.js**
```
const path = require('path');
const { merge } = require('webpack-merge');
const common = require('./webpack.common');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = merge(common, {
    output: {
        filename: 'js/[name].bundle.[hash:5].js',
        path: path.resolve(__dirname, 'dist')
    },
    module: {
        rules: [
            {
                test: /\.scss$/,
                use: [ 
                    MiniCssExtractPlugin.loader,
                    'css-loader', 
                    'sass-loader'
                ]
            }
        ]
    },
    plugins: [
        new MiniCssExtractPlugin({
            filename: 'css/[name].[contentHash].css'
        })
    ]
});
```

Index.html (template that works)
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Home</title>
    </head>
    <body>
        <p>Index</p>
    </body>
</html>
```

About.html (example of template that doesn't)
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>About</title>
    </head>
    <body>
        <p>About</p>
    </body>
</html>
```

**Comment by jantimon** [comment]
I am very sorry but I have no idea what you are asking for.

Can you try to rename your templates into `about.ejs` so it will not be picked up by your html-loader configuration?

Can you please tell the content of `./src/about.html` the expected output for `/about.html` and the current output for `/about.html`?

**Comment by NickWoodward** [comment]
Hi @jantimon, no need to apologise, it's no doubt my poor explanation! Thanks for taking a look.

So currently **./src/about.html** looks like this:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>About</title>
    </head>
    <body>
        <p>About</p>
    </body>
</html>
```
What I expect is the same as what I get when running `"build": "webpack --config webpack.prod.js"`  (minus the css links)
**./dist/about.html**
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <title>About</title>
        <link href="css/common.09f1e812b625db8383a4.css" rel="stylesheet" />
        <link href="css/about.b9c803e3a4d0dc1f8f80.css" rel="stylesheet" />
    </head>
    <body>
        <p>About</p>
        <script src="js/common.bundle.2d66c.js"></script>
        <script src="js/about.bundle.2d66c.js"></script>
    </body>
</html>
```

What I get is this (view page source) when running ` "start": "webpack-dev-server --config webpack.dev.js --open chrome"`

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
    </head>
    <body>
    <script type="text/javascript" charset="utf-8" src="/about.js"></script>
    </body>
</html>
```
It has injected the scripts (and the css inline), but the content (the <p> tag) and <title> are missing - it seems to be ignoring the template?

It works as expected with index.html both when building and using dev-server.

Changing the template names and the files to .ejs still results in the same problem unfortunately

Thanks again

**Comment by NickWoodward** [comment]
Thought I'd use `write-file-webpack-plugin` to force dev-server to write the files to server, but it too produces an html file that differs to the one being served

**Comment by jantimon** [comment]
I can't see any issues here 🤔

I'll try to setup a codesandbox to reproduce that issue.

**Comment by NickWoodward** [comment]
Hi @jantimon, just an update that you can probably make more sense of than me:

If I navigate to `localhost:8080` the template is used and js link is injected. If I navigate to `localhost:8080/index`, or `localhost:8080/about` (or use `devServer: {openPage:'index'}` / `devServer: {openPage:'about'}`), the js link is injected but the template is not used.
```
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\...\boilerplate
```

It feels like my problem maybe the url I'm navigating to? I'm still struggling with it though 🤔

**Comment by NickWoodward** [comment]
I'm an idiot... I wasn't navigating to /index**.html**. I can't believe I missed that. Sorry for wasting your time!

**Comment by jantimon** [comment]
cool :) thanks letting me know - can we close this?

**Comment by NickWoodward** [comment]
Yeah sure. Quick question though if you don't mind?

Was navigating to `localhost:8080/index` actually serving me with `localhost:8080/index/index.html`? I'm just not entirely sure why /index (or /about) was a valid URL

**Comment by jantimon** [comment]
Maybe you used the devserver history api fallback?
https://webpack.js.org/configuration/dev-server/#devserverhistoryapifallback

**Comment by NickWoodward** [comment]
I mean not that I know of. Oh well, at least it's working! Thanks
