### ISSUE TITLE
Support multiple favicons

### ISSUE THREAD

**Issue by Amndeep7** [jantimon/html-webpack-plugin#1490]
**Is your feature request related to a problem? Please describe.**
There is a need to be able to provide more than one favicon which themselves provide a variety of different browser hints through different `rel`s, `size`s, and so on.  

**Describe the solution you'd like**
Instead of the favicon option only taking in a string for a single path, have it also take in an object and list of objects as well.  

The structure of the object would be something like `{ href: $REQUIRED_PATH_STRING, rel: $OPTIONAL_REL_STRING_DEFAULTS_TO_ICON, optional_size: $SIZE_STRING, optional_whatever: $WHATEVER_STRING }`.  

Essentially, the path to the icon would be a required attribute in the object, the `rel` attribute would default to `icon` but could be replaced, and then it would accept any number of optional attributes that it would insert as necessary in order to accommodate attributes like size and color.

Having it be a STRING|OBJECT|LIST let's you make it so that it's not a breaking change, but also supports something like providing a SVG favicon as the default and then a PNG backup for incompatible browsers.

**Describe alternatives you've considered**
The above seems like the best way to move forward without introducing breaking changes or adding in a whole bunch of manually specified options that wouldn't scale well.

**Additional context**
https://realfavicongenerator.net/blog/favicon-why-youre-doing-it-wrong/ - shows and explains the necessity for a whole bunch of favicon types

https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/ - shows a quick example right at the top of a real world use-case for needing at minimum 2 different favicons (SVG and backup)

https://caniuse.com/#feat=link-icon-svg - many browsers still don't support svg, and even if they all did, there are many additional devices that rely on favicons that don't support svg (ex. windows' metro tiles)

**Comment by jantimon** [comment]
did you see my https://github.com/jantimon/favicons-webpack-plugin ?

**Comment by Amndeep7** [comment]
Sorry for the late reply.  I had not seen it but it's worked really well (at least I think so haha - don't have iphone/mac to test there), except for running into https://github.com/jantimon/favicons-webpack-plugin/issues/198 as well which I don't think gets resolved until vue-cli bumps up the version of this library that they are using.
