### ISSUE TITLE
How to migrate 3.x to 4.x with specific use case

### ISSUE THREAD

**Issue by connorjburton** [jantimon/html-webpack-plugin#1493]
Sorry for deleting the PR template but it didn't seem relevant.

We are currently using the plugin like so:

```
window.chunks = {};
    {{#each htmlWebpackPlugin.files.chunks}}
        window.chunks['{{@key}}'] = {
            js: '{{this.entry}}',
            css: '{{this.css.[0]}}'
        };
    {{/each}}
```

After upgrades `.files.chunks` no longer exists as expected from the docs, and I can loop over both the CSS and JS files however they no longer contain the bundle name from what I can see.

So I have two questions:

How can I achieve a similar result in `4.x` (loop over assets and them being matched up with the bundle name)
How can I debug this? I tried adding plugins via handlebars-loader but just get recursion errors when adding a JSON.stringify helper.

Thanks very much

**Comment by jantimon** [comment]
Unfortunately I didn't have time to provide the chunk information for 4.x.  
It was removed to help with issues during manipulations from different plugins.

What do you use the `window.chunks` variable for?

**Comment by connorjburton** [comment]
We pass down the bundle name we want to use from the server (e.g `app` or `auth` etc.) and then load the relevant file from `window.chunks` dynamically.

It's old code that needs refactoring but have been stuck on upgrading this package for a while now. It's not a major issue, just added a resolution for `lodash` to resolve vulnerability in `html-webpack-plugin` < 4.x.x

**Comment by jantimon** [comment]
I see - did you know that webpack can do that for you?

e.g.

```
entries
  | - entry1.js
  | - entry2.js
  | - entry3.js
  \   entry4.js
```

then in your "real" entry file:

```
function bootEntry(entryName) {
   return import('./src/' + entryName);
}

// Based of some information e.g. ajax or something in the page:
bootEntry("entry1");
```

**Comment by connorjburton** [comment]
Thank you, I will take this into account when refactoring.
