### ISSUE TITLE
No parsing ${} variable

### ISSUE THREAD

**Issue by js-ding** [jantimon/html-webpack-plugin#1497]
## Expected behaviour

Tell us what you would expect the html-webpack-plugin should.

## Current behaviour

Tell us what the html-webpack-plugin does instead.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
npm --version
npm ls webpack
npm ls html-webpack-plugin 4.3.0
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
module.exports = {
  entry: 'app.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  module: {
    rules: [
      ...
    ]
  }
  plugins: [
    new HtmlWebpackPlugin({
            filename: 'index.html',
            template: path.join(__dirname, '../src/index/index.html'),
            inject: true
        }),
    ...
  ]
}
```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<html>
    <head>
       ${ require('raw-loader!./meta.html') }
        <title>My App</title>
    </head>
    <body>
    </body>
</html>
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

**Comment by jantimon** [comment]
Have you specified any special loader rules for html files?

**Comment by js-ding** [comment]
```javascript
```

**Comment by js-ding** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    ${ require('raw-loader!./meta.html') }
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
    <title>my-project</title>
    <script>${ require('raw-loader!babel-loader!../../node_modules/amfe-flexible/index.js') }</script>
</head>
<body>
    <div id="root"></div>
</body>
</html>`
`const path = require('path');
const glob = require('glob');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

const rootPath = process.cwd();

function setMPA() {
    const entry = {},
        htmlWebpackPlugin = [];

    const pageFiles = glob.sync(path.join(rootPath, 'src/*/index.js'));
    Object.keys(pageFiles)
        .forEach(index => {
            const pageFile = pageFiles[index];
            const match = pageFile.match(/src\/(.*)\/index\.js/);
            const pageName = match && match[1];
            entry[pageName] = pageFile;
            htmlWebpackPlugin.push(
                new HtmlWebpackPlugin({
                    filename: `${pageName}.html`,
                    template: path.join(rootPath, `src/${pageName}/index.html`),
                    inject: true, // 打包后的入口文件是否自动注入到html中
                    chunks: [`${pageName}`]
                })
            )
        })

    return {
        entry,
        htmlWebpackPlugin
    }
}

const { entry, htmlWebpackPlugin } = setMPA();

module.exports = {
    mode: 'none',
    entry,
    output: {
        filename: '[name][chunkhash:8].js',
        path: path.join(rootPath, 'dist')
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader'
                }
            },
            {
                test: /\.css$/i,
                use: [
                    MiniCssExtractPlugin.loader,
                    'css-loader'
                ],
            },
            {
                test: /.less$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    'css-loader',
                    {
                        loader: 'postcss-loader',
                        options: {
                            plugins: () => [
                                require('autoprefixer')({
                                    overrideBrowserslist: ['last 2 version', '>1%', 'ios 7']
                                })
                            ]
                        }
                    },
                    {
                        loader: 'px2rem-loader',
                        options: {
                            remUnit: 75,
                            remPrecision: 8
                        }
                    },
                    'less-loader'
                ]
            },
            {
                test: /\.(png|jpe?g|gif|svg)$/i,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name]_[hash:8].[ext]'
                        }
                    },
                ],
            },
            {
                test: /\.(woff|woff2|eot|ttf|otf)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name]_[hash:8].[ext]'
                        }
                    },
                ],
            },
        ]
    },
    plugins: [
        new MiniCssExtractPlugin({
            filename: '[name].[contenthash:8].css'
        }),
        new CleanWebpackPlugin()
    ].concat(htmlWebpackPlugin)
}`
this is my html file and webpack config, not other loader rules

**Comment by jantimon** [comment]
Okay fine 👍

In that case you just need to adjust your syntax to the underscore template syntax:

https://underscorejs.org/#template

```
<%= require('raw-loader!./meta.html') %>
```

Or use a different loader to use your preferred template language instead.

By the way you can also define meta tags with the meta tags option.
