### ISSUE TITLE
Override loader

### ISSUE THREAD

**Issue by donaldpipowitch** [jantimon/html-webpack-plugin#1498]
**Is your feature request related to a problem? Please describe.**
As far as I know loaders are inherited in my template. However I need override this to avoid an error with fast refresh during development: https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/176

**Describe the solution you'd like**
I guess I need something like this:

```
{
  module: {
    rules: [ jsRule, ...sharedRules ] 
  },
  plugins: [
    new HtmlWebpackPlugin({
    rules: [ customJsRule, ...sharedRules ] 
    })
  ]
}
```

**Describe alternatives you've considered**
...

**Additional context**
I have a demo which shows my problem: https://github.com/donaldpipowitch/react-refresh-webpack-plugin-RefreshSig-bug

**Comment by jantimon** [comment]
Can you define the template as `!!your-loader!template.html` ?

The `!!` will tell webpack to ignore all other loader configuraitons

**Comment by donaldpipowitch** [comment]
I don't think so. That would only affect how I load `template.html`. The problem is that _inside_ the template a JS file is loaded (which potentially loads more JS files, which load more JS files again) and those files are partially loaded in the application code (the one from my webpack `entry`) as well. I'd need to have different JS loader configs for those shared files.

**Comment by jantimon** [comment]
I am not sure how we could achieve this
