### ISSUE TITLE
Differences in 3.x and 4.x      Optimization under WebPack

### ISSUE THREAD

**Issue by Arech-github** [jantimon/html-webpack-plugin#1499]
## Expected behaviour

 html-webpack-plugin@4.x's hooks   should include webpack's  optimization.splitChunks.cacheGroups["chunck"]  
 
## Current behaviour
  
 When I use 3.x
![image](https://user-images.githubusercontent.com/40556460/91408763-f7d5f280-e876-11ea-8bf6-baad72cce90f.png)
I can see xbstyle.css

``` 3.x
  compiler.hooks.compilation.tap('HtmlWebpackCustomInject', function (compilation) {
        compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tap('HtmlWebpackCustomInject', function (htmlPluginData, callback) {

    debugger in this
       
        });
      });
```

But when I use 4.x

![image](https://user-images.githubusercontent.com/40556460/91409099-80ed2980-e877-11ea-8e05-495ea13998f2.png)

``` js
  compiler.hooks.compilation.tap('HtmlWebpackCustomInject', function (compilation) {
        HtmlWebpackPlugin.getHooks(compilation).beforeAssetTagGeneration.tapAsync('HtmlWebpackCustomInject', function (htmlPluginData, callback) {
          let htmlWebpackPluginOptions = htmlPluginData.plugin.options;

          callback(null, htmlPluginData)

        });
      });
```
css property not include  xbstyle.css

## Environment
"html-webpack-plugin": "^4.3.0",

``` 
npm --6.13.4
webpack --4.44.1
html-webpack-plugin --4.3.0
```

### Config

 optimization: {
        splitChunks: {
            cacheGroups: {
                xbcore: {
                    name: 'xbcore',
                    test: /[\\/]node_modules[\\/]/,
                    priority: 10,
                    chunks: "all"
                },
                styles: {
                    name: 'xbstyle',
                    test: /[\\/]node_modules[\\/].*\.css$/,
                    enforce: true,
                    priority: 15,
                    chunks: "initial"               
                }
            }
        },
    },
```js 

 var option = {
                inject: false,
                template: file,
                cache: true,
                filename: file.substr(file.indexOf('views')),
                custominject: true,   //my options
                styleplaceholder: '<!--webpack_style_placeholder-->',    //my options
                scriptplaceholder: '<!--webpack_script_placeholder-->',  //my options
                chunks: []
            }
   option.chunks = ['xbcore', 'xbstyle', viewChunk];
 use    new HtmlWebpackPlugin(option)
```

**Comment by jantimon** [comment]
We switched to a new webpack api to improve performance.

But unfortunately I don't know why this is not including the cacheGroup chunk 😞

**Comment by Arech-github** [comment]
I'm planning to switch to 4.x
Do you have any other Suggestions for me to solve this problem.
thanks

**Comment by Arech-github** [comment]
Can I use other hooks to get the cacheGroup chunk ?
@jantimon

**Comment by Arech-github** [comment]
@jantimon 
HI,Is there a solution to my problem or can I solve it in a different way?
I am planning to move my production project to WebPack5, but this is a problem for me.

**Comment by jantimon** [comment]
hey @Arech-github 

sorry I didn't have the time to invest this issue...  
did you?
