### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by desmap** [jantimon/html-webpack-plugin#1502]
@jantimon this is your number one pinned repo, are you still on it? Several issues and PR https://github.com/jantimon/html-webpack-plugin/pull/1454 re webpack 5 compile warnings are lost in space

**Comment by jantimon** [comment]
Yes it is maintained in my limited spare time - feel free to contribute or sponsor the project

**Comment by desmap** [comment]
Cool, I am happy to contribute and press the merge button on turn-key ready PR https://github.com/jantimon/html-webpack-plugin/pull/1454 but I think, you are the only one who has the permission

Or do want first to be sponsored before that merge? Looking fwd to your reply 😉

**Comment by jantimon** [comment]
The pr from @bartdominiak is awesome 👍

Thanks for pinging.

Released as 4.4.0

**Comment by desmap** [comment]
You are awesome, I haven't seen any maintainer THAT fast! Thanks. The new version emit files but webpack 5.0.0-beta.29 tells me now...
(can I put your plugin myself in this `Compilation.hooks.processAssets`?)
```
(node:25523) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at [...]/node_modules/html-webpack-plugin/index.js:279:49
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by desmap** [comment]
btw I have `new HtmlWebpackPlugin()` as the first plugin in `plugins: []`

**Comment by jantimon** [comment]
This deprecation is a little bit harder to fix - I'll try to reach out to the webpack core team.

**Comment by desmap** [comment]
cool thanks!
