### ISSUE TITLE
Webpack 5 gives peer dependency warning

### ISSUE THREAD

**Issue by GaryB432** [jantimon/html-webpack-plugin#1504]
## Expected behaviour

Plugin should allow webpack 5 pre-releases peer dependency without warning

## Current behaviour

> npm install

```
npm WARN html-webpack-plugin@4.4.1 requires a peer of webpack@>=4.0.0 < 6.0.0 but none is installed. You must install peer dependencies yourself.
```

## Environment

```
Node.js v12.18.2
win32 10.0.18362
npm 6.14.5
webpack@5.0.0-beta.29
html-webpack-plugin@4.4.1
```

### Notes

I guess 5.0.0-beta.29 is indeed less than 6.0.0 but I wonder if the embedded spaces in your `peerDependencies` [range specification](https://devhints.io/semver) is correct.  Maybe we want `webpack@>=4.0.0 <6.0.0`

**Comment by GaryB432** [comment]
looks like other plugins are warning about, e.g., `webpack@^4.37.0 || ^5.0.0` too.  I am unsure about the prelease tag handling and why `5.0.0-beta.29` doesn't satisfy this range either.

**Comment by GaryB432** [comment]
ref https://github.com/Masterminds/semver/issues/10#issuecomment-273223907

It seems reasonable that the plugin would warn when webpack has a prerelease tag.  But you still may want to remove your space or use the double-pipe specification as in my prior comment.  Thanks for the great plugin!

**Comment by jantimon** [comment]
Cool - can you please <create a pr?

**Comment by evilebottnawi** [comment]
Please avoid adding `5.0.0-beta.29` because when we something change in `rc` releases you need to keep compatibility with `5.0.0-beta.29` otherwise it will be breaking change
