### ISSUE TITLE
CSS Modules loading cause a error

### ISSUE THREAD

**Issue by ogonkov** [jantimon/html-webpack-plugin#1507]
## Expected behaviour

I expect that i can _at least_ use CSS modules in template that handled by HTMLWebpackLoader.

## Current behaviour

Some weird error happen. I have filed [bug](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/489) to `mini-css-extract-plugin` first. But now i'm not sure that problem is _only_ on their side.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
Node.js v10.17.0
darwin 19.6.0
npm 6.11.3
npm ls webpack
└── webpack@4.44.1
npm ls html-webpack-plugin
└── html-webpack-plugin@4.4.1
```

### Config

https://gist.github.com/ogonkov/2e23941414d6f0b3d5328bd80cba5674

**Comment by jantimon** [comment]
According to https://github.com/webpack-contrib/mini-css-extract-plugin/issues/489 this issue was resolved

**Comment by ogonkov** [comment]
Yep, error is gone, it just didn't do anything now (output empty `class` in HTML).

I will start another bug for this, because it all was to dig how to bundle HTML with CSS-Modules `class`es and corresponding CSS chunk.
