### ISSUE TITLE
__webpack_public_path__ support 

### ISSUE THREAD

**Issue by Mamba-working** [jantimon/html-webpack-plugin#1508]
**Is your feature request related to a problem? Please describe.**

The CDN addresses in different environments are different, and different public paths are needed
But__ webpack_ public_ path__ The entry JS file generated by packaging cannot be affected

**Describe the solution you'd like**

 __webpack_public_path__ support

**Comment by jantimon** [comment]
I don't understand how we can fix this in this plugin.

Did you see the `publicPath` option for this plugin?   
Maybe you could use it to inject a variable.

**Comment by Mamba-working** [comment]
https://github.com/webpack/webpack/issues/2776#issuecomment-233208623

SomeTime publicpath can't be known at compile time

**Comment by jantimon** [comment]
what is your expected html result?

**Comment by dobromir-hristov** [comment]
Correct me if I am wrong, but the only way for this to work, would be for all static assets, (css, js, prefetch tags etc), to be dynamically added at runtime, when the document is parsed. There is simply no other way to do this, as the paths to the assets are well... already written to the html file :)

This however will probably cause issues with load order of certain files, compared to just having them in the markup.

Been trying to do this for an app, that should be served on different environments without re-compiling.

**Comment by jantimon** [comment]
That's correct and it can be done with a custom template:

```
new HtmlWebpackPlugin({
  inject: false,
  templateContent: ({htmlWebpackPlugin}) => `
    <html>
      <body>
        <h1>Hello World</h1>
      <script>
        ${htmlWebpackPlugin.tags.headTags.map((tag) => {
           // Here you would the data from tag to generate the loading code
        }).join(';')}
        ${htmlWebpackPlugin.tags.bodyTags.map((tag) => {
           // Here you would the data from tag to generate the loading code
        }).join(';')} 
      </script>
      </body>
    </html>
  `
})
```

**Comment by dobromir-hristov** [comment]
Hey @jantimon I see no `tags` in `htmlWebpackPlugin`, only `files`and `options`.
Files does have my `css` and `js` which is great, but I wont be able to inject any extra meta tags for example.

**Comment by jantimon** [comment]
Oh - which version are you using?

**Comment by dobromir-hristov** [comment]
Currently `3.2.0`

**Comment by jantimon** [comment]
Oh 3.2.0 is 3 years old - here is a playground where you can fiddle around with 4.x:

https://codesandbox.io/s/html-webpack-plugin-body-tag-filtering-forked-0y9gq?file=/webpack.config.js

**Comment by dobromir-hristov** [comment]
Yeah.. I know :( I will see if I can convince the bosses to update. Thanks allot!

**Comment by lili21** [comment]
won't work for async chunk I think.

**Comment by jantimon** [comment]
for async chunks use the webpack publicPath option

**Comment by lili21** [comment]
I need to output multiple HTML files with different `publicPath`. 
using webpack publicPath option require multi webpack compilation, that would be expensive and increase the ci time,

**Comment by jantimon** [comment]
I am sorry 😐 there is nothing which can be done by the html webpack plugin to help with async chunk loading

**Comment by Mamba-working** [comment]
The solution now is to package multiple HTML file， and set different public path
