### ISSUE TITLE
Empty PublicPath value from Webpack Configuration ignored by templateContent()

### ISSUE THREAD

**Issue by brachycera** [jantimon/html-webpack-plugin#1510]
## Expected behaviour

The Webpack documentation for [Ouput PublicPath](https://webpack.js.org/configuration/output/#outputpublicpath) lists these examples

```javascript
module.exports = {
  //...
  output: {
    // One of the below
    publicPath: 'https://cdn.example.com/assets/', // CDN (always HTTPS)
    publicPath: '//cdn.example.com/assets/', // CDN (same protocol)
    publicPath: '/assets/', // server-relative
    publicPath: 'assets/', // relative to HTML page
    publicPath: '../assets/', // relative to HTML page
    publicPath: '', // relative to HTML page (same directory)
  }
};
```

Settings an empty value for `output.publicPath` should be reflected in `templateContent()`.

## Current behaviour

When the value for `output.publicPath` is defined as empty, html-webpack-plugin will fallback to the `output.path` value instead of keeping the empty value as suggested by the Webpack docs.

## Environment

```
Node.js v12.18.3
darwin 17.7.0
6.14.6
webpack@4.44.1
html-webpack-plugin@4.4.1
```

#### `publicPath` is `'/'`

```javascript
// ...
output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].[chunkhash].js',
    publicPath: '/'
},
// ...
plugins: [
    new HtmlWebpackPlugin({
        templateContent(params) {

            return `${params.htmlWebpackPlugin.files.js.map(

// file = "/css/styles.46c367b54f5a3493d203.css" as expected

                (file) => `<link rel="stylesheet" type="text/css" href="${file}">`
            )}`;

        },
        filename: '../_includes/partials/jsAssets.njk',
        inject: false
    })
})
// ...
```

#### `publicPath` is `''`

```javascript
// ...
output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].[chunkhash].js',
    publicPath: ''
},
// ...
plugins: [
    new HtmlWebpackPlugin({
        templateContent(params) {

            return `${params.htmlWebpackPlugin.files.js.map(

// file = "../../dist/css/styles.46c367b54f5a3493d203.css" wrongly fallback to `output.path`

                (file) => `<link rel="stylesheet" type="text/css" href="${file}">`
            )}`;

        },
        filename: '../_includes/partials/jsAssets.njk',
        inject: false
    })
})
// ...
```

When using an empty value for `publicPath` shouldn't the **expected path** be `css/styles.46c367b54f5a3493d203.css`?

I think the reason for this behavior is the trimming function `const isPublicPathDefined = webpackPublicPath.trim() !== '';`

https://github.com/jantimon/html-webpack-plugin/blob/f3ccdd5125566ba8d2965cfb4f59b058854fa3c9/index.js#L542

Maybe I'm wrong with my expectations and someone can point me in the right direction - thanks in advance!

**Comment by jantimon** [comment]
it's probably because of the file name - I guess the html-webpack-plugin tries to generate a relative file path from the html file to the css file

**Comment by brachycera** [comment]
hey jantimon, thanks for you response! 

> it's probably because of the file name - I guess the html-webpack-plugin tries to generate a relative file path from the html file to the css file

Maybe I'm wrong but shouldn't html-webpack-plugin respect the Webpack configuration value `output.publicPath`? As posted above the Webpack docs mention that it should be possible to set the `output.publicPath` to an empty value for `// relative to HTML page (same directory)`?

I added 3 Debugger Screenshots for you each with a different value for the Webpack Configuration `output.publicPath`.

```javascript
// 1. Screenshot
output.publicPath: '' // empty

// 2. Screenshot
output.publicPath: '/'

// 3. Screenshot
// output.publicPath: '' //undefined
```

<img width="584" alt="path_empty" src="https://user-images.githubusercontent.com/2804515/93114712-36fba480-f6bb-11ea-953c-8fe959775cf2.png">
<img width="575" alt="path_slash" src="https://user-images.githubusercontent.com/2804515/93114714-37943b00-f6bb-11ea-8460-58be6ee059af.png">
<img width="585" alt="path_undefined" src="https://user-images.githubusercontent.com/2804515/93114716-382cd180-f6bb-11ea-9d0a-29ab6b17b346.png">

As you can see html-webpack-plugin sets the variable `const webpackPublicPath` on line [index.js:538](https://github.com/jantimon/html-webpack-plugin/blob/f3ccdd5125566ba8d2965cfb4f59b058854fa3c9/index.js#L538) with the value from the variable `compilation.outputOptions.publicPath`.

When I set the `output.publicPath` as empty `''` I would expect that the `file` var should be without a beginning slash e.g. `css/styles.46c367b54f5a3493d203.css` but instead `../../dist/` is added from html-webpack-plugin.

Shouldn't html-webpack-plugin make a difference between the `output.publicPath` value `undefined` and empty `''`?

**Comment by jantimon** [comment]
maybe we can add that to our next branch - would you like to add a pull request?

what would happen if you don't set a publicPath in webpack at all?

does the publicPath option of html-webpack-plugin fixes this issue for you in the meantime?

**Comment by brachycera** [comment]
> maybe we can add that to our next branch - would you like to add a pull request?

I tried to investigate the problem a little further. It seems the webpack function `compilation.mainTemplate.getPublicPath()`

https://github.com/jantimon/html-webpack-plugin/blob/f3ccdd5125566ba8d2965cfb4f59b058854fa3c9/index.js#L539

returns `''` when `publicPath` is defined as `''` and when it is `undefined`. I'm not sure if this is the intentional fallback from webpack. So if I'm correct, `webpackPublicPath` would never be empty :worried: and the `trim()` function serves the wrong purpose. 
If the `trim()` call is removed then `isPublicPathDefined` would always be `true` and the if clause from `publicPath` could be removed?

I could send you an PR but I'm not 100% sure about my assumption that `getPublicPath()` has the fallback as I described.

https://github.com/jantimon/html-webpack-plugin/blob/f3ccdd5125566ba8d2965cfb4f59b058854fa3c9/index.js#L542-L548

> what would happen if you don't set a publicPath in webpack at all?

you can see this case in the examples above - the 3rd screenshot shows the behavior without the `publicPath` value set (undefined).

> does the publicPath option of html-webpack-plugin fixes this issue for you in the meantime?

Nope this didn't had any effect.

**Comment by jantimon** [comment]
🤔 webpack 5 sets the public path to `'auto'` - so maybe we can ignore the `undefined` case and remove `webpackPublicPath.trim() !== ''` for `html-webpack-plugin@next`

In the meantime setting `publicPath` to empty string should work e.g.:

```js
new HtmlWebpackPlugin({
  publicPath: ''
})
```

<img width="383" alt="index_js_—_html-webpack-plugin" src="https://user-images.githubusercontent.com/4113649/97120375-d2e6ea00-1716-11eb-9ba3-b57ad110049a.png">

<img width="376" alt="empty_string" src="https://user-images.githubusercontent.com/4113649/97120355-af23a400-1716-11eb-98f9-4e6ea2599ed8.png">

**Comment by jantimon** [comment]
I prepared a pull request for the current alpha version which would fix this bug:  
https://github.com/jantimon/html-webpack-plugin/pull/1538

**Comment by brachycera** [comment]
Thanks for the support, jantimon! Sorry I couldn't be helpful with an PR. Closing this issue.
