### ISSUE TITLE
How can i include image in HTML file

### ISSUE THREAD

**Issue by Hemanth10081999** [jantimon/html-webpack-plugin#1520]
**assets are not found when using the plugin**
I have an HTML file, which uses images when I use webpack in production mode, It says images are not found and the images are not copied to the build folder. For now, I am using copywebpackplugin to copy assets to build, Is it the right way to do it, Or Is there any specific way to do it. 

**I can't find any solution**
Where ever I try the demo for this plugin, They have a very simple HTML file with no images for a sample.

**Could u please help me**

**Comment by jantimon** [comment]
You can use the html-loader however it will not allow you to use ejs anymore like `<%= htmlWebpackPlugin.title %>`

**Comment by Th3S4mur41** [comment]
> You can use the html-loader however it will not allow you to use ejs anymore like `<%= htmlWebpackPlugin.title %>`

Any plan to make this possible again in a future version?
I'm looking for a solution to have both the image loading through html-loader and the custom variables from HTMLWebPack Plugin

**Comment by jantimon** [comment]
@Th3S4mur41 unfortunately this has never been possible 

all loaders take a string and generate javascript out of the given input value.  
however there is one difference between the html-loader and other loaders:
<br />

html-loader is generating a string out of a html-input  
e.g. `<h1>Hello World</h1>` ->  
```js
module.exports = '<h1>Hello World</h1>
```

<br />

other loaders e.g. lodash-template-loader, ejs-loader, twig and so on generate a function out of html  
e.g. `<h1><%= title %></h1>` ->  
```js
module.exports = () ({title}) => `<h1>${title}</h1>
```
<br />


this result is handed over to the html-webpack-plugin  and the
html-webpack-plugin executes the template (the string or the function) but it can't send in a title into a string

wouldn't it be possible `<title>Your title</title>` directly to the html?

**Comment by Th3S4mur41** [comment]
Understood, thanks for the clarification.

Of course, setting a title could be done directly into the template.
In my case, I'm setting the build date into the footer of the template and I'd like to avoid using JavaScript to display it to make sure it's also displayed with JS disabled in the browser

**Comment by jantimon** [comment]
I just checked and the html-loader allows to use a preprocessor option.

So you could for example replace all `{date}` strings with the current date:

```
module: {
    rules: [
      {
        test: /\.html$/i,
        loader: 'html-loader',
        options: {
          preprocessor: (content, loaderContext) => {
              return content.replace(/\{date\}/g, new Date().toString())
          }
      }
  ]
}  
```
