### ISSUE TITLE
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.

### ISSUE THREAD

**Issue by LP1994** [jantimon/html-webpack-plugin#1529]
## Expected behaviour
When I use webpack 5, there are no warnings.

## Current behaviour
When I use webpack 5, there are warnings!!!
(node:1652) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at G:\SNWS\sn-micro-front-web-project-template\node_modules\html-webpack-plugin\index.js:280:49
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

## Environment
webpack version: v5.1.2
Node.js version: v14.14.0
Operating System: Windows 10
npm: v6.14.8
html-webpack-plugin:  v4.5.0

### Config
no

## Relevant Links
no

## Additional context
no

**Comment by Thebarda** [comment]
There is a related issue #1523

**Comment by jantimon** [comment]
Can you please see if this is fixed with html-webpack-plugin@5.0.0-alpha.2 ?  
Please see also #1527

**Comment by LP1994** [comment]
> Can you please see if this is fixed with html-webpack-plugin@5.0.0-alpha.2 ?
> Please see also #1527

Thank you! I tried it, and then I turned it off.

**Comment by LP1994** [comment]
> Can you please see if this is fixed with html-webpack-plugin@5.0.0-alpha.2 ?
> Please see also #1527

There is still that warning!!!
![image](https://user-images.githubusercontent.com/12012671/96235861-de773a00-0fcd-11eb-918b-d304acee0285.png)

**Comment by jantimon** [comment]
Sorry it looks like the last release didn't include the full fix - can you please try once again with html-webpack-plugin@5.0.0-alpha.3 ?

**Comment by LP1994** [comment]
> Sorry it looks like the last release didn't include the full fix - can you please try once again with html-webpack-plugin@5.0.0-alpha.3 ?

OK.

**Comment by LP1994** [comment]
> Sorry it looks like the last release didn't include the full fix - can you please try once again with html-webpack-plugin@5.0.0-alpha.3 ?

It's being tested. Wait for my good news!

**Comment by Thebarda** [comment]
html-webpack-plugin@5.0.0-alpha.3 fixes the issue

**Comment by LP1994** [comment]
> Sorry it looks like the last release didn't include the full fix - can you please try once again with html-webpack-plugin@5.0.0-alpha.3 ?

Yes, it did. thank you! The author's timely repair.

**Comment by LP1994** [comment]
> html-webpack-plugin@5.0.0-alpha.3 fixes the issue

Yes, it did. thank you! The author's timely repair.

**Comment by LP1994** [comment]
This issue will also be closed.

**Comment by LP1994** [comment]
> Sorry it looks like the last release didn't include the full fix - can you please try once again with html-webpack-plugin@5.0.0-alpha.3 ?

Looking forward to the update of the official version.

**Comment by slavafomin** [comment]
So, when are you planning to release the `html-webpack-plugin@5` version?

**Comment by jkiss** [comment]
html-webpack-plugin@5.0.0 has released!!!
