### ISSUE TITLE
webpack 5 & html-webpack-plugin 5 - TypeError: htmlPluginData.plugin.addFileToAssets is not a function

### ISSUE THREAD

**Issue by jharris4** [jantimon/html-webpack-plugin#1533]
For the [html-webpack-tags plugin](https://github.com/jharris4/html-webpack-tags-plugin/blob/master/index.js#L430) I use the reference to `htmlPluginData.plugin.addFileToAssets` to add assets, something like this:

```
const onCompilation = compilation => {
    const onBeforeHtmlGeneration = (htmlPluginData, callback) => {
        htmlPluginData.plugin.addFileToAssets('someAssetPath', compilation);
    };
};
```

This works fine with webpack v4 & html-webpack-plugin v4, but when I tried with v5 of both plugins, I get the following error:

```
TypeError: htmlPluginData.plugin.addFileToAssets is not a function
    at addAsset (Source/html-webpack-tags-plugin/index.js:430:40)
    at getPath (Source/html-webpack-tags-plugin/index.js:441:30)
    at Array.map (<anonymous>)
    at onBeforeHtmlGeneration (Source/html-webpack-tags-plugin/index.js:450:42)
    at eval (eval at create (Source/html-webpack-tags-plugin/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:15:1)
    at new Promise (<anonymous>)
    at Hook.eval [as promise] (eval at create (Source/html-webpack-tags-plugin/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:4:8)
    at Hook.PROMISE_DELEGATE [as _promise] (Source/html-webpack-tags-plugin/node_modules/tapable/lib/Hook.js:22:14)
    at Source/html-webpack-tags-plugin/node_modules/html-webpack-plugin/index.js:247:86
```

**Comment by jantimon** [comment]
webpack has now a built in api for that: https://webpack.js.org/api/compilation-object/#emitasset

**Comment by jharris4** [comment]
Yes, I saw that this plugin was refactored to use the new built in api, so I was expecting things to just work... ;-)

For now, I can get `html-webpack-tags-plugin` working by adding the following code that duplicates the logic from `html-webpack-plugin`:

```
      const addAsset = assetPath => {
        try {
          if (htmlPluginData.plugin && htmlPluginData.plugin.addFileToAssets) {
            return htmlPluginData.plugin.addFileToAssets(assetPath, compilation);
          } else {
            assetPath = path.resolve(compilation.compiler.context, assetPath);
            return Promise.all([
              new Promise((resolve, reject) => {
                fs.stat(assetPath, (err, stats) => {
                  if (err) {
                    reject(err);
                  } else {
                    resolve(stats);
                  }
                });
              }),
              new Promise((resolve, reject) => {
                fs.readFile(assetPath, (err, data) => {
                  if (err) {
                    reject(err);
                  } else {
                    resolve(data);
                  }
                });
              })
            ]).then(([stat, source]) => {
              const { size } = stat;
              const basename = path.basename(assetPath);
              source = new webpack.sources.RawSource(source, true);
              compilation.fileDependencies.add(assetPath);
              compilation.emitAsset(basename, source, { size });
            });
          }
        } catch (err) {
          return Promise.reject(err);
        }
      };
```

It would be nice if the `addFileToAssets` function still worked with v5 as it'd remove a lot of duplicated code...

**Comment by jantimon** [comment]
I understand your issue :)

this function was an internal helper to address that this feature is not built into webpack core itself..

adding it back shouldn't be a problem but html-webpack-plugin is not a util library to manipulate the webpack core compilation...

not sure what to do here 🤔

**Comment by jharris4** [comment]
Yes, the code I pasted above was based on the latest implementation :-)

I can see your point about not wanting this plugin to be a util library, but on the other hand, this plugin is designed to be extended by other plugins, and many of the plugins that extend this one manipulate the assets and will all have to build their own implementation to add assets if it's not provided by this plugin...

**Comment by jantimon** [comment]
and it allows only to add files to the dist root directory

**Comment by jharris4** [comment]
> and it allows only to add files to the dist root directory

Oh? Meaning you can’t add sub-directories etc?! 😬

**Comment by jantimon** [comment]
Right now `const basename = path.basename(filename);` will strip away all path information

**Comment by jharris4** [comment]
Ah I see. Also looking at the webpack source for `emitAsset` it doesn't look like they support providing a path within the filename, even via the 3rd assetInfo argument :-(

**Comment by jantimon** [comment]
I'll close this for now - maybe this could be an independent npm package or an webpack core feature to make it easier to add files to a compilation
