### ISSUE TITLE
Unexpected token '<'

### ISSUE THREAD

**Issue by tuvs85** [jantimon/html-webpack-plugin#1534]
// webpack.config.js HtmlWebpackPlugin config
`
/*is Test Data*/

let fileName = 'index'
let H5_VERSION = '0.0.1'
new HtmlWebpackPlugin({
    entry: path.resolve(__dirname, `../src/pages/${fileName}/main.js`),
    template: path.resolve(__dirname, `../src/pages/${fileName}/${fileName}.html`),
    filename: `${fileName}.html`,
    inject: true,
    minify: {
      removeComments: true,
      collapseWhitespace: true,
      removeAttributeQuotes: true
    },
    chunks: [fileName],
    alwaysWriteToDist: true,
    prefetch: false,
    env: "'" + process.env.NODE_ENV + "'",
    version: "'" + H5_VERSION + "'",
    timestamp: "'" + Date.now() + "'",
  })
`
// HTML template
`
//html code .... 

    <script>var _App = {env: <%= htmlWebpackPlugin.options.env || 'pro' %>, version: "<%= htmlWebpackPlugin.options.version %>", ts: "<%= htmlWebpackPlugin.options.timestamp %>"}</script>

`

use webpack5 
run webpack serve 
chrome console output `Uncaught SyntaxError: Unexpected token '<'`
![console](https://user-images.githubusercontent.com/29142360/96374292-6f077300-11a4-11eb-8a0a-bd41478da9ad.png)
![source code](https://user-images.githubusercontent.com/29142360/96374323-a544f280-11a4-11eb-9a36-3ed6cf70ff74.jpg)

**please help me?
Tell me what I used wrong?**

**Comment by jantimon** [comment]
Do you have any loader in place for .html file?

**Comment by tuvs85** [comment]
> 您是否有用于.html文件的加载程序？
I am learning webpack
webpack.config.js
`{
        test: /\.html$/,
        use: [
          {
            loader: 'html-loader',
          }
        ]
      }
`

**Comment by tuvs85** [comment]
> Do you have any loader in place for .html file?

I am learning webpack
webpack.config.js
`{ test: /\.html$/, use: [ { loader: 'html-loader', } ] }`

**Comment by tuvs85** [comment]
> // webpack.config.js HtmlWebpackPlugin config
> `
> /_is Test Data_/
> 
> let fileName = 'index'
> let H5_VERSION = '0.0.1'
> new HtmlWebpackPlugin({
> entry: path.resolve(__dirname, `../src/pages/${fileName}/main.js`),
> template: path.resolve(__dirname, `../src/pages/${fileName}/${fileName}.html`),
> filename: `${fileName}.html`,
> inject: true,
> minify: {
> removeComments: true,
> collapseWhitespace: true,
> removeAttributeQuotes: true
> },
> chunks: [fileName],
> alwaysWriteToDist: true,
> prefetch: false,
> env: "'" + process.env.NODE_ENV + "'",
> version: "'" + H5_VERSION + "'",
> timestamp: "'" + Date.now() + "'",
> })
> `// HTML template`
> //html code ....
> 
> ```
> <script>var _App = {env: <%= htmlWebpackPlugin.options.env || 'pro' %>, version: "<%= htmlWebpackPlugin.options.version %>", ts: "<%= htmlWebpackPlugin.options.timestamp %>"}</script>
> ```
> 
> `
> 
> use webpack5
> run webpack serve
> chrome console output `Uncaught SyntaxError: Unexpected token '<'`
> ![console](https://user-images.githubusercontent.com/29142360/96374292-6f077300-11a4-11eb-8a0a-bd41478da9ad.png)
> ![source code](https://user-images.githubusercontent.com/29142360/96374323-a544f280-11a4-11eb-9a36-3ed6cf70ff74.jpg)
> 
> **please help me? Tell me what I used wrong?**

use 
`
    "html-webpack-plugin": "^5.0.0-alpha.6",
   "webpack": "^5.1.3",
    "webpack-cli": "^4.0.0",
`

**Comment by tuvs85** [comment]
> Do you have any loader in place for .html file?
I know
I delete .html for file loader
run success

**Thank you for your reminder**

**Comment by tuvs85** [comment]
> Do you have any loader in place for .html file?

I know
I delete .html for file loader
run success

Thank you for your reminder

**Comment by jantimon** [comment]
the html-loader does not support `<%=`

**Comment by Nantris** [comment]
@jantimon any advice of debugging these sorts of issues?

After `yarn upgrade` that only affects dependencies of dependencies, now `html-webpack-plugin` seems to be the cause of build failures with: `SyntaxError: Unexpected token ')'`
