### ISSUE TITLE
Webpack 5 errors (and circular dependency introduced?)

### ISSUE THREAD

**Issue by JakeSidSmith** [jantimon/html-webpack-plugin#1541]
I'm currently trying to upgrade our webpack config to use webpack 5. Everything worked fine until I added `html-webpack-plugin`, at which point I recieved:

```
1 ERROR in child compilations
```

This was whilst using `html-webpack-plugin@4`, but I'm getting the same error, and some additional odd behaviour (new circular dependency detected by `circular-dependency-plugin`), since using `5.0.0-alpha.7`.

Note: although the config I've posted below includes `html-webpack-harddisk-plugin`, the errors persist when this is not present.

## Expected behaviour

Not error

## Current behaviour

```
ERROR in   Error: Child compilation failed:
  Circular dependency detected: 
  static/src/index.html -> static/src/index.html
  Error: Circular dependency detected: 
  static/src/index.html -> static/src/index.html
  
  - index.js:55 
    [project]/[circular-dependency-plugin]/index.js:55:25
  
  
  - Hook.js:14 Hook.CALL_DELEGATE [as _call]
    [project]/[webpack]/[tapable]/lib/Hook.js:14:14
  
  - Compilation.js:1897 Compilation.seal
    [project]/[webpack]/lib/Compilation.js:1897:37
  
  - Compiler.js:1005 
    [project]/[webpack]/lib/Compiler.js:1005:20
  
  - Compilation.js:1726 
    [project]/[webpack]/lib/Compilation.js:1726:4
  
  
  
  - FlagDependencyExportsPlugin.js:332 
    [project]/[webpack]/lib/FlagDependencyExportsPlugin.js:332:11
  
  - async.js:2830 
    [project]/[neo-async]/async.js:2830:7
  
  - child-compiler.js:156 
    [project]/[html-webpack-plugin]/lib/child-compiler.js:156:18
  
  - Compiler.js:510 
    [project]/[webpack]/lib/Compiler.js:510:11
  
  - Compiler.js:1014 
    [project]/[webpack]/lib/Compiler.js:1014:17
  
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - task_queues.js:62 runNextTicks
    internal/process/task_queues.js:62:3
  
  - timers.js:412 processImmediate
    internal/timers.js:412:9
  


1 ERROR in child compilations
webpack compiled with 2 errors
```

## Environment

Mac OS Catalina 
Version: 10.15.7 (19H2)

```
Node.js v12.13.0
darwin 19.6.0

NPM 6.14.8

webpack@5.3.0
html-webpack-plugin@5.0.0-alpha.7
```

### Config

Most of our config is generated by a lib so it's hard to show you exactly what there is, but the important parts are:

```js
plugins: [
  // ...
  new CircularDependencyPlugin({
    failOnError: true,
    exclude: /node_modules/,
    cwd: process.cwd(),
  }),
  // ...
]
```

```js
baseConfig.plugins.push(
  new HtmlWebpackPlugin({
    filename: path.resolve(process.cwd(), 'static/build/index.html'),
    template: path.resolve(process.cwd(), 'static/src/index.html'),
    // Removing this line still causes the same errors
    alwaysWriteToDisk: true,
  })
);

// Removing this line still causes the same errors
baseConfig.plugins.push(new HtmlWebpackHarddiskPlugin());
```

I don't think the template is part of the issue, but here it is just in case:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Title</title>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />
  </head>
  <body>
    <div id="app" class="app"></div>

    <script id="current_user" type="application/json">
      { "email": "email@email.email", "name": "Dev Server User" }
    </script>
  </body>
</html>
```

## Relevant Links

We have our own lib to generate most of the webpack config for our projects: https://github.com/dabapps/create-webpack-config, however `html-webpack-plugin` is not mentioned in there.

**Comment by jantimon** [comment]
Wow that sounds strange - could it be a bug of the circular dependencies plugin?

**Comment by JakeSidSmith** [comment]
I only got that error when `html-webpack-plugin@5.0.0-alpha.7` is included, so it's unlikely. It may be that an error within `html-webpack-plugin` is causing the circular dependency checker to give a false positive?

**Comment by jantimon** [comment]
I don't know how to debug the circular dependency plugin but if you can find out what is causing the problem I am open to fix it

Does this problem also occur if you use another loader?

**Comment by JakeSidSmith** [comment]
We're using `babel-loader`, `style-loader`, `css-loader`, `postcss-loader`, `less-loader`, `circular-dependency-plugin`, `fork-ts-checker-webpack-plugin`, `raw-loader`, `html-webpack-harddisk-plugin`, and `html-webpack-plugin`.

When `html-webpack-plugin` is removed, all the other plugins/loaders work fine.

If you need I can try to find some time to setup an example repo (as the ones in question are closed source), but if you don't mind doing so yourself...

Here's the full config (you'll need `@dabapps/create-webpack-config@0.4.0` which constructs most of our config), and the rest should be pretty self explanatory.

```js
const path = require('path');
const createWebpackConfig = require('@dabapps/create-webpack-config');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const HtmlWebpackHarddiskPlugin = require('html-webpack-harddisk-plugin');

const baseConfig = createWebpackConfig({
  input: './static/src/ts/index.tsx',
  outDir: './static/build/js',
  tsconfig: './tsconfig.dist.json',
  rawFileExtensions: ['txt'],
  env: {
    NODE_ENV: 'production',
  },
});

baseConfig.plugins.push(
  new HtmlWebpackPlugin({
    filename: path.resolve(process.cwd(), 'static/build/index.html'),
    template: path.resolve(process.cwd(), 'static/src/index.html'),
    alwaysWriteToDisk: true,
  })
);

baseConfig.plugins.push(new HtmlWebpackHarddiskPlugin());

baseConfig.module.rules.push({
  test: /\.less$/,
  use: ['style-loader', 'css-loader', 'postcss-loader', 'less-loader'],
});

module.exports = {
  ...baseConfig,
  output: {
    ...baseConfig.output,
    filename: 'bundle.[contenthash].js',
    publicPath: '/js/',
  },
  devServer: {
    contentBase: path.resolve(process.cwd(), 'static/build'),
    port: 1337,
    host: '0.0.0.0',
    historyApiFallback: true,
    serveIndex: true,
  },
};
```

**Comment by jantimon** [comment]
here is a minimal repo:

```bash
npm init -y
npm i webpack
npm i html-webpack-plugin@5.0.0-alpha.7
npm i CircularDependencyPlugin
```

webpack.config.js
```js
module.exports = {
  plugins: [
    new HtmlWebpackPlugin(),
    new CircularDependencyPlugin({
      failOnError: true,
      exclude: /node_modules/,
      cwd: process.cwd(),
    }),
  ]
}
```

src/index.js
```js
console.log("hello world");
```

can you try to debug why circular dependency plugin is causing this issue?

**Comment by jrnail23** [comment]
@JakeSidSmith, I don't think `circular-dependency-plugin` is ready for webpack5 yet.  I had to exclude it from my upgraded webpack configs to get anything to work.

**Comment by jantimon** [comment]
Cool can we close this issue?

**Comment by JakeSidSmith** [comment]
> @JakeSidSmith, I don't think `circular-dependency-plugin` is ready for webpack5 yet. I had to exclude it from my upgraded webpack configs to get anything to work.
> EDIT: I see they just dropped v5.2.2 two days ago -- I just tried it in my project, and it seems to work fine now.

Oh, nice. I'll give this a go as soon as I have a chance and let you know if it's working okay for me.

**Comment by JakeSidSmith** [comment]
Yup, that appears to have sorted it. Thanks for your help. 😊
