### ISSUE TITLE
The `ejs-loader` does not provide a `include` function

### ISSUE THREAD

**Issue by rahuldahal** [jantimon/html-webpack-plugin#1542]
The `ejs-loader` does not provide a `include` function

_Originally posted by @jantimon in https://github.com/jantimon/html-webpack-plugin/issues/1216#issuecomment-512141092_

**Comment by rahuldahal** [comment]
So, what is the solution then ?
How can we use `include` in our `ejs` template ?

**Comment by jantimon** [comment]
`<img src="<%= require('./my-image.png') %>">`

**Comment by rahuldahal** [comment]
hmm...
I got that. Thanks!
