### ISSUE TITLE
hook beforeAssetTagGeneration callback never fired

### ISSUE THREAD

**Issue by strongcode9527** [jantimon/html-webpack-plugin#1545]
## Expected behaviour

HtmlWebpackPlugin.getHooks(compilation).beforeAssetTagGeneration  callback can be fired

## Current behaviour

the beforeAssetTagGeneration hook callback function never fired

```
// muPlugin.js
compiler.hooks.compilation.tap('SomePlugin', (compilation) => {
        const hook = HtmlWebpackPlugin.getHooks(compilation).beforeAssetTagGeneration;
        hook.tapAsync(
          'AutoDllPlugin',
          callback
        );
})

// through this，i can inject the  compilation and callback  to Html-webpack-plugin's 
  htmlWebpackPluginHooksMap 

```

```
// html-webpack-plugin

compiler.hooks.emit.tapAsync('HtmlWebpackPlugin',
      (compilation, callback) => {

// when i debugging html-webpack-plugin, I find  htmlWebpackPluginHooksMap.get(compilation), always be undefined.
```

so my plugin callback is never fired or called;

## Environment

webpack @4.21.0
html-webpack-plugin @4.5.0

**Comment by jantimon** [comment]
Sorry I couldn't reproduce this issue

**Comment by LucasUnplugged** [comment]
I don't know @strongcode9527's setup, but I had this issue in a Lerna + Yarn monorepo. The issue ended up being that one package in the monorepo had a nested dependency on v4 of `html-webpack-plugin`, and another package had a dependency on v5, so Lerna kept 2 versions in different places, similarly to #1031.

I was able to resolve it by making sure both packages depended on the same major version.

Hope that helps others!
