### ISSUE TITLE
Absolute path in loader.js breaks Webpack contenthash

### ISSUE THREAD

**Issue by alexandernanberg** [jantimon/html-webpack-plugin#1548]
## Expected behaviour

Building a project should result in the same hash every time, even with different machines.

## Current behaviour

The hash is different when you build with another machine. 

Related https://github.com/webpack/webpack/issues/7179

I used the script in https://github.com/webpack/webpack/issues/7179#issuecomment-547557053 and found that it was html-webpack-plugin that was the cause.

More specifically this exact line https://github.com/jantimon/html-webpack-plugin/blob/86c561c0b3e78e72ec3f24d059be0b492032fdc8/lib/loader.js#L29 

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
Node.js v12.19.0
darwin 19.6.0
NPM 6.14.8
Webpack 4.44.2
html-webpack-plugin 4.5.0
```

### Config

The only relevant parts would be this

```js
    output: {
      filename: 'static/[name].[contenthash:8].js',
	  // ...
    },
    // ...
```

## Relevant Links

N/A

## Additional context

N/A

**Comment by jantimon** [comment]
Good point - I have never thought about that part 🤔 

The result of this compilation is only used temporarily and should not affect anything.  
Does that part improve with `html-webpack-plugion@next` (5.x)?

Do you have a good solution for this problem?

**Comment by alexandernanberg** [comment]
Unfortunately I can't try the latest version of either `webpack` or `html-webpack-plugion` because of downstream dependencies. Our setup is _really_ similar to [CRA](https://github.com/facebook/create-react-app), so I'd guess it has the same problem.

> I could be wrong but I believe filename: 'static/[name].[contenthash:8].js', is not used by the html-webpack-plugin

Right, but I wonder why the contenthash for the JS assets aren't stable because of the html-webpack-plugin then 🤔 

> Do you have a good solution for this problem?

Nothing on top of my mind right now, however I'm not too familiar with the internals of Webpack so might be missing something.

**Comment by jantimon** [comment]
Unfortunately I also don't know why the the contenthash for the JS assets aren't stable..

Please let me know once you found a solution :)

**Comment by alexandernanberg** [comment]
Oh maybe I wasn't clear. I'm pretty sure it's because the `require.resolve` in `loader.js`, because the absolute path for lodash. Let's say the project lives in `~/dev/abc` on one machine and in `~/apps/abc` in another. Then the content webpack hashes is different causing a mismatch in `[contenthash]` between machines.

I don't know how that could be solved though, maybe remove lodash?

**Comment by jantimon** [comment]
The html-webpack-plugin is generating `~/dev/abc/lodash` then it will execute and delete this code and will only keep the result.

The result will not change and therefore contenthash will not change.

**Comment by alexandernanberg** [comment]
Right but Webpack generates the hash when the lodash path is still in the content (you can try it by adding a custom hashFunction to the webpack config https://github.com/webpack/webpack/issues/7179#issuecomment-547557053), not really sure if this is an bug in Webpack or this plugin though. 

Maybe @sokra knows more?

**Comment by jantimon** [comment]
Hey @alexandernanberg  can you please try if the html-webpack-plugin 5.x version resolves this issue?

**Comment by alexandernanberg** [comment]
Nice, I can no longer reproduce it 🎉

**Comment by jantimon** [comment]
Cool thanks for testing :)
