### ISSUE TITLE
Hot Reload results in script tag of bundle removed from index.html 

### ISSUE THREAD

**Issue by karthik-hr** [jantimon/html-webpack-plugin#1555]
# Packages
```
"html-webpack-plugin": "^4.5.0",
"webpack": "^5.4.0",
"webpack-cli": "^4.2.0"

```
# script 
```
webpack serve --env development

````

# Webpack
```
new HtmlWebpackPlugin({
	template: './public/index.html',
}),
```

When React hot reloads, script tag is removed from index.html

**Comment by whyamsx** [comment]
why?
`
ERROR in   Error: The loader "C:\Users\whyamsx\Desktop\bot\node_modules\html-webpack-plugin\lib\loader.js!C:\Users\whyamsx\Deskto  p\bot\index.html" didn't return html.

 - index.js:330 HtmlWebpackPlugin.evaluateCompilationResult
    [bot]/[html-webpack-plugin]/index.js:330:24

  - index.js:237
    [bot]/[html-webpack-plugin]/index.js:237:22

  - async Promise.all

  - async Promise.all
`

**Comment by jantimon** [comment]
Does it work with `html-webpack-plugin@next`?

**Comment by karthik-hr** [comment]
turns out latest copywebpackplugin was the root cause.
closing the issue.
