### ISSUE TITLE
Error: didn't return html

### ISSUE THREAD

**Issue by whyamsx** [jantimon/html-webpack-plugin#1556]
## Expected behaviour

Automatic addition of the built script to the html file from the source to the built project.

## Current behaviour

Shows error (spaces in "Descto p" are also counted):
```
ERROR in   Error: The loader "C:\Users\whyamsx\Desktop\bot\node_modules\html-webpack-plugin\lib\loader.js!C:\Users\whyamsx\Deskto  p\bot\index.html" didn't return html.

  - index.js:330 HtmlWebpackPlugin.evaluateCompilationResult
    [bot]/[html-webpack-plugin]/index.js:330:24

  - index.js:237
    [bot]/[html-webpack-plugin]/index.js:237:22

  - async Promise.all

  - async Promise.all
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v15.0.1
win32 10.0.18362

npm --version
7.0.3

npm ls webpack
tsc-webpack-obfuscator@1.0.0 C:\Users\whyamsx\Desktop\bot
+-- clean-webpack-plugin@3.0.0
| `-- webpack@4.44.2 deduped
+-- html-webpack-plugin@4.5.0
| `-- webpack@4.44.2 deduped
+-- ts-loader@8.0.11
| `-- webpack@4.44.2 deduped
+-- webpack-cli@3.3.12
| `-- webpack@4.44.2 deduped
+-- webpack-obfuscator@1.12.1
| `-- webpack@4.44.2 deduped
`-- webpack@4.44.2
  `-- terser-webpack-plugin@1.4.5
    `-- webpack@4.44.2 deduped

npm ls html-webpack-plugin
tsc-webpack-obfuscator@1.0.0 C:\Users\whyamsx\Desktop\bot
`-- html-webpack-plugin@4.5.0
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
const path = require('path')
const { CleanWebpackPlugin } = require('clean-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
	mode: 'production',
	entry: path.resolve(__dirname, 'app.ts'),
	output: {
		filename: '[hash].js',
		path: path.resolve(__dirname, 'dist'),
	},
	resolve: {
		extensions: ['.ts', '.js'],
	},
	module: {
		rules: [
			{
				loader: 'ts-loader',
			},
		],
	},
	plugins: [
		new CleanWebpackPlugin(),
		new HtmlWebpackPlugin({
			template: path.join(__dirname, 'index.html'),
			inject: true,
			// filename: '[chunkhash].html'
		}),
	],
}

```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  
</body>
</html>
```

**Comment by jantimon** [comment]
I can't reproduce that issue :(

**Comment by piecyk** [comment]
@jantimon looks like it's connected to production mode. 

Having this example https://github.com/piecyk/html-webpack-plugin-1556

```
piecyks-MacBook-Pro:html-webpack-plugin-1556 piecyk$ cat webpack.config.js
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  mode: "production",
  entry: "./src/index.js",
  output: {
    path: __dirname + "/dist",
  },
  plugins: [
    new HtmlWebpackPlugin({
      inject: true,
      template: "./src/index.html.js",
    }),
  ],
};
piecyks-MacBook-Pro:html-webpack-plugin-1556 piecyk$ yarn webpack
yarn run v1.22.10
$ /Users/piecyk/work/my/html-webpack-plugin-1556/node_modules/.bin/webpack
[webpack-cli] Compilation finished
asset index.html 55 bytes [compared for emit]
asset main.js 19 bytes [compared for emit] [minimized] (name: main)
./src/index.js 20 bytes [built] [code generated]
webpack 5.4.0 compiled successfully in 252 ms
✨  Done in 0.93s.
piecyks-MacBook-Pro:html-webpack-plugin-1556 piecyk$ cat ./dist/index.html
use strict<script defer="defer" src="main.js"></script>piecyks-MacBook-Pro:html-webpack-plugin-1556 piecyk$
piecyks-MacBook-Pro:html-webpack-plugin-1556 piecyk$
```

Generated index.html looks like 

```
use strict<script defer="defer" src="main.js"></script>
```

**Comment by whyamsx** [comment]
> @jantimon looks like it's connected to production mode.
> 
> Having this example https://github.com/piecyk/html-webpack-plugin-1556
> 
> ```
> piecyks-MacBook-Pro:html-webpack-plugin-1556 piecyk$ cat webpack.config.js
> const HtmlWebpackPlugin = require("html-webpack-plugin");
> 
> module.exports = {
>   mode: "production",
>   entry: "./src/index.js",
>   output: {
>     path: __dirname + "/dist",
>   },
>   plugins: [
>     new HtmlWebpackPlugin({
>       inject: true,
>       template: "./src/index.html.js",
>     }),
>   ],
> };
> piecyks-MacBook-Pro:html-webpack-plugin-1556 piecyk$ yarn webpack
> yarn run v1.22.10
> $ /Users/piecyk/work/my/html-webpack-plugin-1556/node_modules/.bin/webpack
> [webpack-cli] Compilation finished
> asset index.html 55 bytes [compared for emit]
> asset main.js 19 bytes [compared for emit] [minimized] (name: main)
> ./src/index.js 20 bytes [built] [code generated]
> webpack 5.4.0 compiled successfully in 252 ms
> ✨  Done in 0.93s.
> piecyks-MacBook-Pro:html-webpack-plugin-1556 piecyk$ cat ./dist/index.html
> use strict<script defer="defer" src="main.js"></script>piecyks-MacBook-Pro:html-webpack-plugin-1556 piecyk$
> piecyks-MacBook-Pro:html-webpack-plugin-1556 piecyk$
> ```
> 
> Generated index.html looks like
> 
> ```
> use strict<script defer="defer" src="main.js"></script>
> ```
don't work...

please review my original project https://github.com/whyamsx/html-webpuck-plugin-issues

**Comment by jantimon** [comment]
Blocked by https://github.com/webpack/webpack/issues/11909

**Comment by whyamsx** [comment]
> this looks similar to an issue which is blocked by [webpack/webpack#11909](https://github.com/webpack/webpack/issues/11909) right now - can you try to reproduce this issue based on this codesandbox template?
> 
> https://codesandbox.io/s/html-webpack-plugin-5x-alpha-d37s2?file=/webpack.config.js

use 'yarn build' in Terminal, for reproduce issue
https://codesandbox.io/s/html-webpack-plugin-5x-alpha-forked-4gqu5?file=/app.ts

**Comment by piecyk** [comment]
@jantimon basic got this error when using `template` as function that returns string and mode is `production`, on development works as expected. 

Can't get this error here https://github.com/piecyk/html-webpack-plugin-1556, but generated index.html is not right. Template function is https://github.com/piecyk/html-webpack-plugin-1556/blob/main/src/index.html.js

With this approach i can do build time rendering, for example render react components, as `template` is run in webpack context  

Update the example repo, also will try to pin point where it breaks for production mode.

**Comment by jantimon** [comment]
> > this looks similar to an issue which is blocked by [webpack/webpack#11909](https://github.com/webpack/webpack/issues/11909) right now - can you try to reproduce this issue based on this codesandbox template?
> > https://codesandbox.io/s/html-webpack-plugin-5x-alpha-d37s2?file=/webpack.config.js
> 
> use 'yarn build' in Terminal, for reproduce issue
> https://codesandbox.io/s/html-webpack-plugin-5x-alpha-forked-4gqu5?file=/app.ts

You didn't define a `test` setting for your rules so it will try to run the `ts-loader` for your `index.html` file which fails:

```
 rules: [
      {
        loader: "ts-loader"
      },
      {
        enforce: "post",
        use: {
        ...
```

**Comment by jantimon** [comment]
@piecyk unfortunately that is a bug in `webpack 5`

Your template.js is run with the following child compiler settings:

```js
const outputOptions = {
      filename: '__child-[name]',
      publicPath: mainCompilation.outputOptions.publicPath,
      library: {
        type: 'var',
        name: 'HTML_WEBPACK_PLUGIN_RESULT'
      },
      /** @type {'text/javascript'} */
      scriptType: (/** @type {'text/javascript'} */'text/javascript'),
      iife: false
    };
    const compilerName = 'HtmlWebpackCompiler';
    // Create an additional child compiler which takes the template
    // and turns it into an Node.JS html factory.
    // This allows us to use loaders during the compilation
    const childCompiler = mainCompilation.createChildCompiler(compilerName, outputOptions, [
      // Compile the template to nodejs javascript
      new NodeTemplatePlugin(outputOptions),
      new NodeTargetPlugin(),
      new LoaderTargetPlugin('node')
    ]);
```

As you can see it is defined to return a variable:

```
library: {
        type: 'var',
        name: 'HTML_WEBPACK_PLUGIN_RESULT'
      },
```

However if you take a look at the result of the compilation of your file you will see that this var is missing:

```js
/******/ "use strict";
const template = (hash) => {
  return `<html>
    <head>
      <meta charSet="utf-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=Edge" />
      <meta name="viewport" content="initial-scale=1" />
      <meta name="referrer" content="origin-when-cross-origin" />
    </head>
    <body>
    <div>compilation: ${hash}</div>
    </body>
  </html>`;
};

/* harmony default export */ function __WEBPACK_DEFAULT_EXPORT__({ compilation }) {
  return template(compilation.hash);
}
```

There is not much we can do here until https://github.com/webpack/webpack/issues/11909 is resolved - maybe you can add a link to your repository also there

**Comment by whyamsx** [comment]
> > > это похоже на проблему, которая сейчас заблокирована [webpack / webpack # 11909](https://github.com/webpack/webpack/issues/11909) - можете ли вы попытаться воспроизвести эту проблему на основе этого шаблона codeandbox? 
> > > https://codesandbox.io/s/html-webpack-plugin-5x-alpha-d37s2?file=/webpack.config.js
> > 
> > 
> > используйте 'yarn build' в Терминале для воспроизведения проблемы 
> > https://codesandbox.io/s/html-webpack-plugin-5x-alpha-forked-4gqu5?file=/app.ts
> 
> Вы не определили `test`параметр для своих правил, поэтому он попытается запустить `ts-loader`для вашего `index.html`файла, что не удастся:
> 
> ```
>  rules: [
>       {
>         loader: "ts-loader"
>       },
>       {
>         enforce: "post",
>         use: {
>         ...
> ```

thanks a lot, it helped, you helped me a lot, thanks 🙂

**Comment by trusktr** [comment]
I'm on Webpack 5, and everything except html-webpack-plugin was up to date. I updated html-webpack-plugin from v4 to v5, and the issue went away.
