### ISSUE TITLE
HTML template using <img src="path/to/image" /> won't work!

### ISSUE THREAD

**Issue by tr1s** [jantimon/html-webpack-plugin#1557]
## Expected behaviour

If I do this: `<img src="../path/to/image" />` I get a broken image.

I thought this was a webpack 5 bug, [so I posted it in their issues list](https://github.com/webpack/webpack/issues/11968#issuecomment-725117719), but [they mentioned](https://github.com/webpack/webpack/issues/11968#issuecomment-725446920) that this is a `html-webpack-plugin` bug.

[Here is my repo for reference](https://github.com/tr1s/webpack-5). Just needs an `npm i && npm start`

Is there something I'm doing wrong? Is this a bug or is there a way to fix this?

## Current behaviour

I get this instead of the actual image:

<img width="83" alt="CleanShot 2020-11-10 at 22 21 35@2x" src="https://user-images.githubusercontent.com/19172250/98761761-29edef80-23a4-11eb-8842-ca4545b858ae.png">

I'm trying with `svg`, `png`, and `jpg`. No luck.

## Environment

* macOS latest `10.15.7`
* node `v14.4.0`
* npm `v6.14.5`
* webpack `v5.4.0`
* html-webpack-plugin `v5.0.0-alpha.14`

### Config
[webpack.common.js](https://github.com/tr1s/webpack-5/blob/main/webpack.common.js)

Copy your template file if it is part of this issue:

```html
<img
  class="logo-img"
  src="/src/images/mikasa.png"
  alt="website logo"
/>
```

or any variation of path and/or file extension...!

## Relevant Links

[Full reproduction repo](https://github.com/tr1s/webpack-5).

## Additional context

Any help would be greatly appreciated!

**Comment by jantimon** [comment]
Which loader do you use for your template?

**Comment by tr1s** [comment]
> Which loader do you use for your template?

I didn't have a loader because I thought webpack 5 asset modules would handle it. Then I tried html-loader and still had no luck.

**Comment by jantimon** [comment]
html-loader works with webpack 4 .. not sure if that's broken for the latest version can you please try `html-webpack-plugin@next`

**Comment by jantimon** [comment]
I just tried and everything seems to work:

https://codesandbox.io/s/html-webpack-plugin-5x-alpha-html-loader-q5cg3?file=/src/template.ejs

**Comment by tr1s** [comment]
@jantimon do you happen to know what I'm doing wrong here? I've tried `url-loader` and `asset/resource` both with no luck anymore.

**Comment by jantimon** [comment]
Are you using the html-loader for your template?

**Comment by tr1s** [comment]
Actually I deleted the `url-loader` and updated the `html-webpack-plugin` version and it seems to be working now!

In your latest comment [here](https://github.com/webpack/webpack/issues/11968#issuecomment-739539032), you mention there's partial support. What exactly does that mean, what should I watch out for that won't work?

**Comment by jantimon** [comment]
I am working on that part right now :)

Right now it doesn't support if you have multiple html-webpack-plugins with different relative or absolute public paths

**Comment by jantimon** [comment]
It is fully supported by `html-webpack-plugin@5.0.0-beta.1`

**Comment by n4ks** [comment]
I have same bug
![image](https://user-images.githubusercontent.com/30715874/119268301-fb768a00-bbfa-11eb-8105-c391afa3a265.png)

![image](https://user-images.githubusercontent.com/30715874/119268307-04675b80-bbfb-11eb-90f2-086178c4dc59.png)
![image](https://user-images.githubusercontent.com/30715874/119268345-2eb91900-bbfb-11eb-990b-b5e8df77fe71.png)
![image](https://user-images.githubusercontent.com/30715874/119268352-37a9ea80-bbfb-11eb-8760-f409747973fe.png)

I am using the latest version of the library

**Comment by DiegoMajluf** [comment]
> I have same bug
> ![image](https://user-images.githubusercontent.com/30715874/119268301-fb768a00-bbfa-11eb-8105-c391afa3a265.png)
> 
> ![image](https://user-images.githubusercontent.com/30715874/119268307-04675b80-bbfb-11eb-90f2-086178c4dc59.png)
> ![image](https://user-images.githubusercontent.com/30715874/119268345-2eb91900-bbfb-11eb-990b-b5e8df77fe71.png)
> ![image](https://user-images.githubusercontent.com/30715874/119268352-37a9ea80-bbfb-11eb-8760-f409747973fe.png)
> 
> I am using the latest version of the library

Did you manage to make it work?

**Comment by jantimon** [comment]
@DiegoMajluf @n4ks this issue is about the new webpack 5 asset loading not about using images in html.

The images won't work for you for the following reason:

**By default the html template is "just text"** 

So webpack will not understand that you want to copy the asset referenced inside that text.  
There are multiple solutions to that issues:

- Using any template loader and require the asset e.g. `<img src="<%= require('./images/logo.png') %>" />`
- Using the html-loader (which does not allow template language)
