### ISSUE TITLE
jest playwright = The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by morriq** [jantimon/html-webpack-plugin#1559]
## Current behaviour 💣

I don't have issues running `webpack serve` but when I run `npm t` which runs `jest` with such playwright's setup:
  
```js
const port = 4000;

module.exports = {
  launchOptions: {
    headless: true,
    ignoreDefaultArgs: ['--disable-extensions'],
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-accelerated-2d-canvas',
      '--disable-gpu',
      '--window-size=1920x1080',
    ],
  },
  launchType: '',
  serverOptions: {
    port,
    command: 'npm start',
    debug: true,
    launchTimeout: 180000,
    waitOnScheme: {
      verbose: true,
      resources: [`http://localhost:${port}/webpack-dev-server`],
    },
  },
};

```

then I receive this markup in index.html

> TypeError: The 'compilation' argument must be an instance of Compilation···

## Expected behaviour ☀️

I think it should work but I tried it with older webpack and the same result.

### Reproduction Example 👾

code is here:
sample below not working due to missing dependencies on machine's sandbox

https://codesandbox.io/s/html-webpack-plugin-5x-alpha-forked-qn7h0?file=/jest-playwright.config.js

## Environment 🖥

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v12.16.3
darwin 19.6.0
npm --version: 6.14.4
npm ls webpack: 5.4.0
npm ls html-webpack-plugin: 5.0.0-alpha.10 
```

**Comment by jantimon** [comment]
`The 'compilation' argument must be an instance of Compilation` means that you have multiple webpack versions installed - unfortunately I don't know why this is happening in your case 🤔 - does it work better with html-webpack-plugin: 5.0.0-alpha.14 ?

**Comment by morriq** [comment]
without luck. I changed little flow and this one stops being blocker. I use https://hub.docker.com/r/cypress/included now. Thank you for help.

**Comment by rmariuzzo** [comment]
I just tried `html-webpack-plugin@5.0.0-alpha.14` in the circumstances described and it didn't work for me.

**Comment by jantimon** [comment]
webpack 4 and webpack 5 can't be installed in the same project
