### ISSUE TITLE
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.

### ISSUE THREAD

**Issue by junagao** [jantimon/html-webpack-plugin#1560]
## Current behaviour 💣

I've upgraded to Webpack 5 and I'm getting this error for the build. The 5.0.0-alpha.14 cleared this warning in development mode, but not in production.

```
(node:95108) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```

## Expected behaviour ☀️

Remove deprecation warning.

## Environment 🖥

Node.js v12.18.3
darwin 19.6.0
npm 6.14.6
webpack@5.4.0 
html-webpack-plugin@5.0.0-alpha.14

**Comment by jantimon** [comment]
can you please run `node --trace-deprecation node_modules/.bin/webpack` to get more details?

**Comment by junagao** [comment]
I'm getting this when I run `node --trace-deprecation node_modules/.bin/webpack`

```
ERROR in ./src/index.js 12:2
Module parse failed: Unexpected token (12:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| render(
>   <Router>
|     <ApolloProvider client={client}>
|       <AuthProvider>
```

But I think it has something to do with brotli-webpack-plugin. Because when I commented it out. The deprecation warning disappeared.

This is the plugin's config:

```
  new BrotliPlugin({
      asset: '[path].br[query]',
      test: /\.(js|css|html|svg)$/,
      threshold: 10240,
      minRatio: 0.8,
    }),
```

**Comment by jantimon** [comment]
Okay thanks for letting me know 👍
