### ISSUE TITLE
when use global cli,  webpackMajorVersion is not correct.

### ISSUE THREAD

**Issue by YufJi** [jantimon/html-webpack-plugin#1561]
## Current behaviour 💣
now, i installed a global cli (like webpack-dev-server or webpack-cli)， and installed html-webpack-plugin in my local project.
```js
const webpackMajorVersion = Number(require('webpack/package.json').version.split('.')[0]);
```
👆looks not very good.

## Expected behaviour ☀️
webpackMajorVersion should be set from webpack's runtime (like compilation or compiler).

### Reproduction Example 👾
No

## Environment 🖥
node -v 10.15.1
MacOS
html-webpack-plugin: 4.5.0

**Comment by jantimon** [comment]
Webpack 5 provides an api for that - however this API is not available for webpack 4.

If you are already working with webpack 5 please try the latest alpha from html-webpack-plugin

If you are already working with webpack 4 please ask the webpack core team to backport a `compiler.webpack` api for webpack 4
