### ISSUE TITLE
How to custom inject css/js into twig file with webpack

### ISSUE THREAD

**Issue by fisherspoon** [jantimon/html-webpack-plugin#1562]
Hi, I use html-webpack-plugin with **inject: false** and added tags manually by example
[https://github.com/jantimon/html-webpack-plugin/tree/master/examples/custom-insertion-position](https://github.com/jantimon/html-webpack-plugin/tree/master/examples/custom-insertion-position)

```
<link rel="stylesheet" href="<%= htmlWebpackPlugin.files.chunks.base.css %>">
<script async src="<%= htmlWebpackPlugin.files.chunks.vendors.entry %>"></script>
```
but how to refer to the same file in twig template?
`<link rel="stylesheet" href="{{ htmlWebpackPlugin.files.chunks.base.css }}">`

**Comment by jantimon** [comment]
Render all body tags in twig:

```twig
{{ htmlWebpackPlugin.tags.headTags }}
```

Render all body tags in twig:
```twig
{{ htmlWebpackPlugin.tags.bodyTags }}
```

**Comment by fisherspoon** [comment]
But how do you need to take a file by name?

Example
`<link rel="stylesheet" href="{{ htmlWebpackPlugin.files.chunks.**base**.css }}">`
name file
`**base**.f0b8d2016d8771bfaabb.css`

or

`<script async src="<%= htmlWebpackPlugin.files.chunks.**vendors**.entry %>"></script>`
name file
`**vendors**.c53249214244a493ec0f.js`

**Comment by jantimon** [comment]
You can filter also for `src` or `href` attributes however right now filtering for a chunkname is not possible

**Comment by fisherspoon** [comment]
Based on this, you can get the file name by chunk name using only such a construction
`<%= htmlWebpackPlugin.files.chunks.base.css %>`
and for twig file i can't get this file?(

**Comment by jantimon** [comment]
That's not related to twig - `files.chunks` does not exist anymore.
