### ISSUE TITLE
Add support for prefixing JS and CSS assets

### ISSUE THREAD

**Issue by kintesh** [jantimon/html-webpack-plugin#1564]
**Is your feature request related to a problem? Please describe.**
I have already looked at #1271 and #1272 and the suggested solution to use `output.publicPath` and setting `__webpack_public_path__` is not enough for situations where you deploy the app to multiple environments. Consider the following use case:

Assume you have three environments DEV, QA and PROD. And for each you have the following hosts where the static resources are deployed at.
```
DEV: //localhost:3000 (no cdn)
QA: //static.qa.domain.com (private cdn)
PROD: //static.domain.com (public cdn)
```

Also assume that my `output.publicPath` is simply `/assets` and I use handlebars to generate html for every request. 
Building the app gives you the template containing `<script src="/assets/app.js" />`. In the client side, I set the `__webpack_public_path__` with a hostname based on the environment (see above). 

Now we have a problem; on initial request, the app.js will load from `//domain.com/assets/app.js` and any dynamic imports will load from `//static.domain.com/assets/dynamic.js` (assuming app is deployed to PROD).

A solution I have involves prefixing the static resource with some string (in my case its handlebars syntax) so that when I build the app, the resulting template contains `<script src="{{ host }}/assets/app.js" />`. At runtime, when I render this template all I need to do is supply the `host` variable so the the generated html contains  `<script src="//static.domain.com/assets/app.js" />`. 

**Describe the solution you'd like**
A config that takes some string and prefix it to the JS and CSS tags. The PR (#1207) by @scinos seems promising but I can extend/modify that however you wish :) 

**Describe alternatives you've considered**
Alternative solution is to no use this plugin and dynamically generate the JS and CSS tags with hostname prefix I want and inject it in the handlebars template during render.

**Additional context**
N/A

**Comment by jantimon** [comment]
You can set a prefix only for the html-webpack-plugin:

```js
new HtmlWebpackPlugin({
  filename: 'prod/index.html',
  publicPath: '//static.domain.com'
}),
new HtmlWebpackPlugin({
  filename: 'qa/index.html',
  publicPath: '//static.qa.domain.com'
}),
```

Would that help you here?

**Comment by kintesh** [comment]
@jantimon Thanks for your reply. Setting publicPath option in HtmlWebpackPlugin works if I do this:

```
const publicPath = '/assets';

...

output: {
    publicPath: publicPath,
},

...

new HtmlWebpackPlugin({
  filename: 'prod/index.html',
  publicPath: `{{ host }}${publicPath}`
}),
```

But I was hoping that there was a proper way of doing it via plugin option. If its not a popular request feel free to close it :)
