### ISSUE TITLE
Dev depencencies leaked to non-dev dependencies

### ISSUE THREAD

**Issue by pzavolinsky** [jantimon/html-webpack-plugin#1566]
## Current behaviour 💣

```bash
npm i html-webpack-plugin
```

installs dev dependencies (`@types/webpack`, `@types/tapable`, etc.)

see [here](https://github.com/jantimon/html-webpack-plugin/commit/238da8123950f87267954fd448f3e6b0fb1ead17#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R53)

in particular some of these bring `@types/node` which messes up with basic stuff like `setTimeout`.

## Expected behaviour ☀️

```bash
npm i html-webpack-plugin
```

does not install any `@types/*` package.

### Reproduction Example 👾

```bash
echo '{}' > package.json
npm i html-webpack-plugin
```

## Environment 🖥

```
Node.js v10.16.0
linux 4.15.0-115-generic
6.9.0 # npm --version
```

**Comment by jantimon** [comment]
I am not sure what is the correct behaviour here - but if we don't use them as dependencies the typings of html-webpack-plugin are broken

**Comment by pzavolinsky** [comment]
Usually `@types/*` dependencies (i.e. typescript typings) are dev dependencies and not production dependencies. You are already doing this [here](https://github.com/jantimon/html-webpack-plugin/blob/master/package.json#L32):
![image](https://user-images.githubusercontent.com/2650299/100265109-81f12e00-2f2e-11eb-9845-1d5dbe5fdd94.png)

but for some reason, some `@types/*` deps ended up being [non-dev dependencies](https://github.com/jantimon/html-webpack-plugin/blob/master/package.json#L53) (maybe you forgot the `-D` in `npm i -D @types/....`?).

**Comment by jantimon** [comment]
As you see the public `typings.d.ts` is depending on 3 module types:

https://github.com/jantimon/html-webpack-plugin/blob/657bc605a5dbdbbdb4f8154bd5360492c5687fc9/typings.d.ts#L1-L3

Therefore we need to add those `@type` packages to the dependencies to prevent typing errors.

For `html-webpack-plugin@5` we will be able to remove `webpack` and `tapable` types again as they moved those types directly into the package

**Comment by jantimon** [comment]
hey @pzavolinsky 

for the current alpha I was able to remove both typings as those typings are now part of `webpack` and `tapable`

can you please give it a try? (runs only with webpack 5)

```
npm i html-webpack-plugin@next 
```

**Comment by pzavolinsky** [comment]
@jantimon I just tried the `npm i` and it looks good.

I still see one typing that IMO should be in `devDependencies` but is listed as a regular dependency: `@types/html-minifier-terser` but, unlike the other two, this one has not dependencies of its own so it doesn't break TS by pulling node deps into a browser build.

That being said, I haven't checked the actual TS build as we are running Webpack 4 stil for this project.

Thanks for making this happen Jan!

**Comment by jantimon** [comment]
Thanks for testing and your feedback 👍

I'll close this issue in that case :)
