### ISSUE TITLE
templateParameters in HTML file

### ISSUE THREAD

**Issue by elcirao** [jantimon/html-webpack-plugin#1568]
Hi! im trying to pass templateParameters to a HTML file, but the param is not displaying, and just print `<%= url %>` like a string in the browser.

My webpack: 

```js
module.exports = {
    mode: 'development',
    entry: {
      // Set the single-spa config as the project entry point
        'single-spa.config': 'single-spa.config.js',
    },
    output: {
        crossOriginLoading: 'anonymous',
        publicPath: URL_MFE,
        chunkFilename: '[name].[contenthash].js',
        filename: (pathData) => {
          return pathData.chunk.name === "single-spa.config" ? '[name].js' : '[name].[contenthash].js';
        },
        path: path.resolve(__dirname, 'dist'),
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader']
            },
          {
            test: /\.js$/,
            exclude: [path.resolve(__dirname, 'node_modules')],
            loader: 'babel-loader',
            options: {
             presets: ["@babel/preset-env"]  //Preset used for env setup
            }
          },
            {
                test: /\.(png|jpe?g|woff|woff2|eot|ttf|otf)$/,
                loader: "file-loader",
                options: {
                  esModule: false
                }
            },
            {
              test: /\.svg$/,
              use: [
                {
                  loader: 'svg-url-loader',
                  options: {
                    limit: 10000,
                  }
                }
              ]
            }
        ]
    },
    node: {
        fs: 'empty'
    },
    resolve: {
        modules: [
            __dirname,
            'node_modules',
        ],
    },
    plugins: [
      // A webpack plugin to remove/clean the build folder(s) before building
        new CleanWebpackPlugin(['dist']),
        new HtmlWebpackPlugin({
          favicon: 'src/icon/favicon.ico',
          template: "index.html",
          templateParameters: {
            url: 'http://localhost:8093'
          }
        }),
        new Dotenv({
          path: './.env', // Path to .env file (this is the default)
          safe: true ,// load .env.example (defaults to "false" which does not use dotenv-safe),
          systemvars: true
        })
    ],
    devtool: 'source-map',
    externals: [],
    devServer: {
        historyApiFallback: true,
        port: 8093,
        headers: {
          "Access-Control-Allow-Origin": "*",
          "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS",
          "Access-Control-Allow-Headers": "X-Requested-With, content-type, Authorization"
        }
    }
};

```

My html file: 

```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" type="image/png" sizes="32x32" href="/dist/favicon.ico">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Project Tracker</title>
  </head>
  <body>
    <div id="manager"></div>
    <div id="list"></div>
    <div id="detail"></div>
    <p>
      <%= url %>
    </p>
    <!-- connect to the single-spa config file -->
    <script src="/dist/single-spa.config.js"></script>
  </body>
</html>
```

**Comment by jantimon** [comment]
Please use the issue template

**Comment by frandevel** [comment]
> Hi! im trying to pass templateParameters to a HTML file, but the param is not displaying, and just print `<%= url %>` like a string in the browser.
> 
> My webpack:
> 
> ```js
> module.exports = {
>     mode: 'development',
>     entry: {
>       // Set the single-spa config as the project entry point
>         'single-spa.config': 'single-spa.config.js',
>     },
>     output: {
>         crossOriginLoading: 'anonymous',
>         publicPath: URL_MFE,
>         chunkFilename: '[name].[contenthash].js',
>         filename: (pathData) => {
>           return pathData.chunk.name === "single-spa.config" ? '[name].js' : '[name].[contenthash].js';
>         },
>         path: path.resolve(__dirname, 'dist'),
>     },
>     module: {
>         rules: [
>             {
>                 test: /\.css$/,
>                 use: ['style-loader', 'css-loader']
>             },
>           {
>             test: /\.js$/,
>             exclude: [path.resolve(__dirname, 'node_modules')],
>             loader: 'babel-loader',
>             options: {
>              presets: ["@babel/preset-env"]  //Preset used for env setup
>             }
>           },
>             {
>                 test: /\.(png|jpe?g|woff|woff2|eot|ttf|otf)$/,
>                 loader: "file-loader",
>                 options: {
>                   esModule: false
>                 }
>             },
>             {
>               test: /\.svg$/,
>               use: [
>                 {
>                   loader: 'svg-url-loader',
>                   options: {
>                     limit: 10000,
>                   }
>                 }
>               ]
>             }
>         ]
>     },
>     node: {
>         fs: 'empty'
>     },
>     resolve: {
>         modules: [
>             __dirname,
>             'node_modules',
>         ],
>     },
>     plugins: [
>       // A webpack plugin to remove/clean the build folder(s) before building
>         new CleanWebpackPlugin(['dist']),
>         new HtmlWebpackPlugin({
>           favicon: 'src/icon/favicon.ico',
>           template: "index.html",
>           templateParameters: {
>             url: 'http://localhost:8093'
>           }
>         }),
>         new Dotenv({
>           path: './.env', // Path to .env file (this is the default)
>           safe: true ,// load .env.example (defaults to "false" which does not use dotenv-safe),
>           systemvars: true
>         })
>     ],
>     devtool: 'source-map',
>     externals: [],
>     devServer: {
>         historyApiFallback: true,
>         port: 8093,
>         headers: {
>           "Access-Control-Allow-Origin": "*",
>           "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS",
>           "Access-Control-Allow-Headers": "X-Requested-With, content-type, Authorization"
>         }
>     }
> };
> ```
> 
> My html file:
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <link rel="icon" type="image/png" sizes="32x32" href="/dist/favicon.ico">
>     <meta charset="utf-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
>     <title>Project Tracker</title>
>   </head>
>   <body>
>     <div id="manager"></div>
>     <div id="list"></div>
>     <div id="detail"></div>
>     <p>
>       <%= url %>
>     </p>
>     
>     <script src="/dist/single-spa.config.js"></script>
>   </body>
> </html>
> ```

Same happens to me. I try to use that syntax `<%= XYZ %>` and it's just ignored. What syntax do we need to use for an HTML template?
Thanks in advance

**Comment by webdiscus** [comment]
@frandevel you can try the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin).
This is new alternative to html-webpack-plugin.

For example, there is a template _./src/views/home/index.html_:

```html
<html>
<head>
  <!-- the variable passed via data object in entry -->
  <title><%= title %></title>
  <!-- load source styles here -->
  <link href="./style.scss" rel="stylesheet">
  <!-- load source scripts here (or in body) -->
  <script src="./main.js" defer="defer"></script>
</head>
<body>
  <h1>Hello <%= name %>!</h1>
</body>
</html>
```

To compile this template use the following Webpack configuration:

```js
const HtmlBundlerPlugin = require('html-bundler-webpack-plugin');

module.exports = {
  plugins: [
    new HtmlBundlerPlugin({
      entry: {
        // define templates here, the syntax is the same as Webpack entry
        index: { // => dist/index.html (key is output filename w/o '.html')
          import: 'src/views/home/index.html', // template file
          data: { title: 'Homepage', name: 'Heisenberg' } // pass variables into template
        },
      },
      js: {
        // output filename of extracted JS from source script loaded in HTML via `<script>` tag
        filename: 'assets/js/[name].[contenthash:8].js',
      },
      css: {
        // output filename of extracted CSS from source style loaded in HTML via `<link>` tag
        filename: 'assets/css/[name].[contenthash:8].css',
      },
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(css|sass|scss)$/,
        use: ['css-loader', 'sass-loader'],
      },
    ],
  },
};
```

The generated HTML contains output filenames of processed source files and `link` `script` tags remain in their places:

```html
<html>
<head>
  <title>Homepage</title>
  <link href="/assets/css/style.05e4dd86.css" rel="stylesheet">
  <script src="/assets/js/main.f4b855d8.js" defer="defer"></script>
</head>
<body>
  <h1>Hello Heisenberg!</h1>
</body>
</html>
```

Using the html-bundler-webpack-plugin:
- an `entry point` is an HTML template
- all source script and style files must be specified directly in HTML

**The profit** - you specify all source styles and scripts in one right place, instead of definitions in many places (JS in Webpack Entry, import SCSS in JS).

**Comment by frandevel** [comment]
Very interesting! Thanks.

In the end, I finally opted to move to EJS, just to have a bit more flexibility also in other areas.

**Comment by webdiscus** [comment]
> In the end, I finally opted to move to EJS, just to have a bit more flexibility also in other areas.

you can use any templating engine, such as [Eta](https://eta.js.org), [EJS](https://ejs.co), [Handlebars](https://handlebarsjs.com), [Nunjucks](https://mozilla.github.io/nunjucks/), [LiquidJS](https://github.com/harttle/liquidjs) and others.
Defaults, the html-bundler-webpack-plugin use the [Eta](https://eta.js.org) (EJS-like syntax).

But you can use the original EJS compiler in the preprocessor:
```js
const HtmlBundlerPlugin = require('html-bundler-webpack-plugin');
const ejs = require('ejs');

// create EJS config
const ejsConfig = {
  root: process.cwd(), // define root template path when using `include()`
  async: true, // optional, async rendering
  
}

module.exports = {
  plugins: [
    new HtmlBundlerPlugin({
      entry: {
        // define templates here, the syntax is the same as Webpack entry
        index: { // => dist/index.html (key is output filename w/o '.html')
          import: 'src/views/home/index.html', // template file
          data: { title: 'Homepage', name: 'Heisenberg' } // pass variables into template
        },
      },
      js: {
        // output filename of extracted JS from source script loaded in HTML via `<script>` tag
        filename: 'assets/js/[name].[contenthash:8].js',
      },
      css: {
        // output filename of extracted CSS from source style loaded in HTML via `<link>` tag
        filename: 'assets/css/[name].[contenthash:8].css',
      },
    }),
  ],
  module: {
    rules: [
      // add the rule for EJS templates
      {
        test: /\.(html|ejs)$/,
        loader: HtmlBundlerPlugin.loader,
        options: {
          preprocessor: (template, { data }) => ejs.render(template, data, ejsConfig), // <= use EJS compiler
        },
      },
    ],
  },
};
```
