### ISSUE TITLE
Cannot modify options via plugin hooks anymore with version 5

### ISSUE THREAD

**Issue by jharris4** [jantimon/html-webpack-plugin#1570]
## Current behaviour 💣

In version 4.x and below, it is possible to change the main plugin options via the hooks for extension plugins, like this:

```
const onCompilation = compilation => {
    const onBeforeHtmlGeneration = (htmlPluginData, callback) => {
        htmlPluginData.plugin.options.meta = { /* stuff in here */ }
    }
}
```

## Expected behaviour ☀️

Would like to still be able to change the main plugin options in extension plugins (in my case this is for `html-webpack-tags-plugin`).

## Environment 🖥

webpack 5.10.1
html-webpack-plugin 5.0.0-alpha.15

**Comment by jantimon** [comment]
hey thanks for your feedback - why do you need to change the options?

**Comment by jharris4** [comment]
Hi, thanks for the quick response!

The [html-webpack-tags-plugin](https://github.com/jharris4/html-webpack-tags-plugin) that I maintain supports `metas` option (it was a request from a user) that allows adding meta tags, with a slightly different syntax to the `meta` option from this plugin.

The code for that [is here](https://github.com/jharris4/html-webpack-tags-plugin/blob/master/index.js#L467)

In general, if plugins can add asset tags, it also makes sense for them to be able to add meta tags (or control other options as needed), no?

**Comment by jharris4** [comment]
Yeah, I agree that altering the options could be dangerous...

If I recall correctly, the various `asset` hooks only work for css/js files though, so changing the options was the only possibility to make it work. It seems that right now, setting the favicon is the only way that meta tags get injected via assets.

**Comment by jantimon** [comment]
I am not sure about alterAssetTags but with alterAssetTagGroups you can inject any tag to the head or body

**Comment by jharris4** [comment]
Ok, I was able to rework the plugin to use alterAssetTagGroups instead of modifying the options, so I'll close the issue.

Thanks for the help in solving this! :-)
