### ISSUE TITLE
Allow adding crossorigin to script tags

### ISSUE THREAD

**Issue by IronSean** [jantimon/html-webpack-plugin#1573]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to modify the generated attributes of the <script> tags to customizing features like crossorigin attributes.

**Describe the solution you'd like**
A configurable option in the plugin where these attributes can be specified

**Describe alternatives you've considered**
As mentioned in #382, webpack-subresource-integrity can be used for this. However, it breaks hot reloading and has other concerns which make them not recommend it for development use. In a development environment I may need to set this attribute.

**Additional context**
I have a Server Side Rendered app that loads react apps inside itself on specific URLs. In production it renders normally, and on any URL which belongs to a react app it includes the app.[contentHash].js react bundle in a local script tag. The app initializes, mounts in the specified div, and can exist self contained until the sidebar is used to navigate to a SSR rendered page instead.

For development, in order to use hot reloading, I must instead host the app.js from webpack dev server. So the <script> tags in my layout files are changed from `<script src='/dist/app.[contentHash].js' />` to `<script src='localhost:8080/dist/app.js>` where 8080 is the port webpack dev server is running on. This means that my js bundles get loaded from webpack dev server, which is running on a different port than the page it's running on. In production they're coming from the same origin and this doesn't need to be set. But in development it's coming from a different port, and whenever there's a code error sometimes the error is swallowed with a message about not being able to render errors form cross origin.

I'm therefore trying to find a way to specify this to get my errors accessible to the dev tools while running in development from a separate server than the html file is hosted on.

**Comment by jantimon** [comment]
I am sorry I don't get what you are looking for.  
Usually you use a proxy to not run into these cross origin problems.  
Maybe the `publicPath` option might help:

```js
output: {
  publicPath: 'http://localhost:8080/dist/'
},
plugins: [ new HtmlWebpackPlugin() ]
```

**Comment by IronSean** [comment]
Currently my C# backend runs on localhost:2354, and it includes in it's layout file `<script src='localhost:8080/dist/app.js' />` which was injected by HtmlWebpackPlugin. This does so because hot reloading only works if the files are hosted by webpack, not the C# server. But this recently started causing CrossOrigin rules to swallow error details unless I manually modify the generated layout file to `<script crossorigin='anonymous' src='localhost:8080/dist/app.s' />`. I'm already using `publicPath` to make this work.

It's definitely an edge case from retrofitting new react apps within an existing legacy website, but our react application can't host itself in development mode because the sidebar and topbar on the webpage get rendered serverside by the backend because they link to non-react sections of the site.

In Production this is fine because the C# backend renders the page then serves the frontend bundle from the same server, neither publicPath nor crossorigin are necessary. 

You're correct that for development I could code up a node http-proxy server and possibly use that to conditionally hit either the C# server or the webpack-dev-server, but that feels like a lot of extra work and infrastructure to solve a problem only appeared very recently (perhaps chrome became more strict with it's crossorigin error swallowing?), and that can be solved with an html attribute meant to solve it.

But then again, everything related to CORS seems to fall into the category of "It's probably for the greater good, but it's annoying that it used to just work and now it doesn't" 🤷‍♀️

**Comment by IronSean** [comment]
There are some other npm packages which appear to tackle this by getting registered after html-webpack-plugin and then injecting the crossorigin attribute into the output. They don't have a lot of use (probably indicative of how niche this use case is) but maybe I'll dig into their source and see if one is using an approach that looks safe and stable.

**Comment by jantimon** [comment]
There are different approaches which might work..  

I personally would modify the tags as each tag has attributes which can be changed before it is injected into the html.
You can find all possible attributes in the typings:
https://github.com/jantimon/html-webpack-plugin/blob/3a28ca3c9853eefc9b638354a493c8fb92bc31f6/typings.d.ts#L240-L265

To modify them you have two options:

1. write a plugin for the html-webpack-plugin
2. set `inject: false` and handle it in the template or templateContent

I will quickly write down how 2 might look like (hopefully I won't add any syntax errors):

```js
new HtmlWebpackPlugin({
  inject: false,
  templateContent: ({htmlWebpackPlugin}) => {
    htmlWebpackPlugin.tags.headTags.forEach((tag) => {
      if (tag.tagName === 'script') tag.attributes.crossorigin = 'anonymous';
    });
   return `
    <html>
      <head>
        ${htmlWebpackPlugin.tags.headTags}
      </head>
      <body>
        <h1>Hello World</h1>
        ${htmlWebpackPlugin.tags.bodyTags}
      </body>
    </html>`
 }
})
```

**Comment by IronSean** [comment]
Thank you,

We have a pretty complex template which generates our root C# Layout file, so just returning the html directly like that wouldn't work, but I'll see if I can apply a similar idea within our template file.

**Comment by jantimon** [comment]
It works quite similar when using templates - in that case you might want to modify the templateParameters with the `templateParameters` option
