### ISSUE TITLE
Entrypoint undefined = ./index.html

### ISSUE THREAD

**Issue by sharmaViks** [jantimon/html-webpack-plugin#1577]
I am currently using 
    "html-webpack-plugin": "^3.2.0"

Due to this new update 3 days ago . I am facing this issue :

![Capture](https://user-images.githubusercontent.com/22673614/102751131-21b6a600-438d-11eb-9fde-e7e8a31d3f9d.JPG)

**Comment by jantimon** [comment]
Your html-webpack-plugin is outdated..

The message you are seeing is only saying that the entrypoint has no name.. it's not an error
