### ISSUE TITLE
Add async support to scriptLoading

### ISSUE THREAD

**Issue by rightaway** [jantimon/html-webpack-plugin#1578]
https://github.com/numical/script-ext-html-webpack-plugin is deprecated for webpack 5 and will no longer be maintained. @jantimon comment https://github.com/jantimon/html-webpack-plugin/issues/113#issuecomment-214148015 says that issue for adding `async` option to `scriptLoading` could be closed because of that plugin.

Now is a good time to revisit supporting it in this plugin as `async` is an important feature of modern JS and not having it here would block many people from upgrading to webpack 5. I'm not familiar how it works, is it as simple as allowing the string `async` to appear in that option and printing it in the template, or is it a lot more involved?

**Comment by rightaway** [comment]
If I spell the current option of `defer` wrong, the script tag gets placed with type `defer` anyway and gets placed before the closing `body` tag instead of the closing `head` tag. This seems like a bug as it should give an error, or at least not change where it gets placed.

**Comment by jantimon** [comment]
🤔 we should probably add an assert statement - would you like to create a pull request for the master and for the next branch?

`scriptLoading: 'defer'` is the new default for html-webpack-plugin 5

it is doing almost exactly the same like `async`. However there are two points which are different:

- scripts are executed once the DOM is ready.. without that you would have to check the ready state of the dom and based on that wait for it to become ready or execute directly 
- scripts are executed in order 

do you think defer script loading is not sufficient?

**Comment by rightaway** [comment]
> scriptLoading: 'defer' is the new default for html-webpack-plugin 5

Looks like a bug in current version because with default value of `inject: true` and setting `scriptLoading: 'defer'`, the `script defer` tag gets placed before closing `head` not `body`. So either behavior is wrong or readme is?

> do you think defer script loading is not sufficient?

There are cases where async is valuable. For example `script type="module"`, but even regular non module scripts. As well it's possible to specify both `async` and `defer` in spec https://html.spec.whatwg.org/multipage/scripting.html#attr-script-async. Would be good if plugin supports all options in spec.

**Comment by jantimon** [comment]
Can you explain which performance you are hopping to get from async?

Scripts with defer need to be placed in the head to download in parallel while the browser is parsing the DOM

**Comment by rightaway** [comment]
> Can you explain which performance benefits you are hopping to get from async?

async is very useful for standalone scripts that don't depend on anything else, such as analytics.

The current readme has a mistake. It says that with default value of `inject: true`, the `script defer` tag gets placed before closing `body`. But when you run it it actually gets placed before closing `head`, which is correct because putting scripts at end of `body` was a workaround for not being able to load scripts with `async` or `defer`.

**Comment by jantimon** [comment]
> async is very useful for standalone scripts that don't depend on anything else, such as analytics.

That's true but do you generate those with webpack?   
Because the html-webpack-plugin will only inject assets generated by webpack.

> The current readme has a mistake. It says that with default value of `inject: true`, the `script defer` tag gets placed before closing `body`. But when you run it it actually gets placed before closing `head`, which is correct because putting scripts at end of `body` was a workaround for not being able to load scripts with `async` or `defer`.

Can you please create a pull request to fix this?  
I guess the readme is just outdated back to the time when `scriptLoading` did not exist

**Comment by jantimon** [comment]
Demo of `scriptLoading: 'defer'`:

https://html-webpack-plugin.js.org/?code=new%20HtmlWebpackPlugin(%7B%0A%20%20%20%20scriptLoading%3A%20%27defer%27%0A%7D)%3B%0A

Demo of `scriptLoading: 'blocking':

https://html-webpack-plugin.js.org/?code=new%20HtmlWebpackPlugin(%7B%0A%20%20%20%20scriptLoading%3A%20%27blocking%27%0A%7D)%3B%0A

**Comment by LJJCherry** [comment]
> Demo of `scriptLoading: 'defer'`:
> 
> https://html-webpack-plugin.js.org/?code=new%20HtmlWebpackPlugin(%7B%0A%20%20%20%20scriptLoading%3A%20%27defer%27%0A%7D)%3B%0A
> 
> Demo of `scriptLoading: 'blocking'`:
> 
> https://html-webpack-plugin.js.org/?code=new%20HtmlWebpackPlugin(%7B%0A%20%20%20%20scriptLoading%3A%20%27blocking%27%0A%7D)%3B%0A
> 
> Demo with `async`:
> 
> https://html-webpack-plugin.js.org/?code=new%20HtmlWebpackPlugin(%7B%0A%20%20%20%2F%2F%20Modify%20tags%3A%0A%20%20%20templateParameters%3A%20(compilation%2C%20assets%2C%20tags%2C%20options)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20tags.headTags.forEach((tag)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20if%20(tag.tagName%20%3D%3D%3D%20%27script%27)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20tag.attributes.async%20%3D%20true%3B%0A%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%20return%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20htmlWebpackPlugin%3A%20%7B%20options%20%7D%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%7D)%0A

good！
