### ISSUE TITLE
Can't specify resolve.alias in favicon option

### ISSUE THREAD

**Issue by rightaway** [jantimon/html-webpack-plugin#1579]
I get error `Error: HtmlWebpackPlugin: could not load file ...../~alias/path.jpg` when setting something like `favicon: '~alias/path.jpg'`, where `~alias` is an alias set in `resolve.alias` webpack config option. Same problem also if I use the alias anywhere else in the template file. Being able to set aliases is very helpful in not hardcoding paths throughout the code base and would be good to be consistent with that in the webpack config for this plugin and in the html template too.

**Comment by jantimon** [comment]
I believe most `alias` configurations are technical dept which will become a burden over time as other tools (IDEs, linters, typecheckers, ...) might not understand them

that said you can use an alias in the template like this: `<img src="`<%= require('alias/my-logo.png') %>`">`
