### ISSUE TITLE
A second build is triggered since alpha 17

### ISSUE THREAD

**Issue by zlk89** [jantimon/html-webpack-plugin#1581]
## Current behaviour 💣

Seeing webpack got triggered a second build, since html-webpack-plugin removes a local file after initial build:
```
FILES REMOVED:
  data:text/javascript,__webpack_public_path__ = htmlWebpackPluginPublicPath;
```

It was working fine on alpha 16 version.

## Expected behaviour ☀️

No file removed after initial build

### Reproduction Example 👾

https://codesandbox.io/s/html-webpack-plugin-5x-alpha-forked-57fug?file=/webpack.config.js

You will see it triggers a second build right after initial one under development mode.
(There is a bug in codesandbox, you might need to open a new terminal and run `yarn start` to see the webpack compilation log)

## Environment 🖥

Node.js v12.16.1
darwin 19.6.0
npm version: 6.13.4
webpack: 5.11.1
html-webpack-plugin: 5.0.0-alpha.17

**Comment by jantimon** [comment]
Hey @zlk89 

thank you so much for your bug report - this bug is already known..

The reason is that it is using a new `webpack 5` feature which is not working correctly with `watchpack`.  
The webpack core team is trying to fix it: 

https://github.com/webpack/webpack/issues/12283

**Comment by joealden** [comment]
FYI, webpack/webpack#12283 was resolved in [`webpack@5.12.0`](https://github.com/webpack/webpack/releases/tag/v5.12.0). @zlk89 could you please verify if the problem you were experiencing has been resolved?

**Comment by zlk89** [comment]
tried 5.12.3, looks like it works now!

**Comment by artemirq** [comment]
Issue still reproducible with Yarn 2. With NPM works fine.

```json
{
  "html-webpack-plugin": "5.0.0-beta.6",
  "webpack": "5.16.0",
}
```

**Comment by jantimon** [comment]
maybe yarn installs old versions?

can you please try if the reproduction example without html-webpack-plugin from from https://github.com/webpack/webpack/issues/12283 fails also for yarn 2?

**Comment by artemirq** [comment]
@jantimon I can't reproduce problem with your example. But I can still reproduce it by using simple config:

```js
module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  plugins: [
    new HtmlWebpackPlugin(),
  ]
};
```

So commenting line with `html-webpack-plugin` does fix the issue.

After investigation I think this problem is not related to `html-webpack-plugin`, because I can reproduce it even with `file-loader`, css and Babel stuff. I will create issue in webpack repo

**Comment by artemirq** [comment]
Created issue in webpack repository: https://github.com/webpack/webpack/issues/12483

**Comment by jantimon** [comment]
thank you :)
