### ISSUE TITLE
Is it possible to use a .liquid template and output a .liquid template instead of html?

### ISSUE THREAD

**Issue by dungle-scrubs** [jantimon/html-webpack-plugin#1582]
I'm working on a Shopify app and I'd like to treat a `.liquid` file as my template, which contains all of my markup.  Is this possible?

Thanks

**Comment by jantimon** [comment]
I don't know liquid

But html-webpack-plugin supports all files which are supported by webpack loaders :)

**Comment by jantimon** [comment]
Yes it works with: https://www.npmjs.com/package/liquid-loader

**Comment by dungle-scrubs** [comment]
Thanks, I've found loaders but I must be doing something wrong.  Will update if I find a solution
