### ISSUE TITLE
Closing slash behavior doesn't match documentation

### ISSUE THREAD

**Issue by sjoqvist** [jantimon/html-webpack-plugin#1583]
## Current behaviour 💣
The plugin minifies the production code while keeping closing slashes, which is different from the default behavior of `html-minifier-terser`.

## Expected behaviour ☀️
The closing slashes should be removed according to the documentation. While the documentation doesn't specifically mention `keepClosingSlash`, it mentions other minification overrides which makes the reader believe that this one is unaltered.

This is likely introduced by #1371, which modified the code without modifying the documentation. While I think that the current behavior is reasonable, it took some debugging to understand why it didn't match my expectations. Hence, perhaps the documentation should be updated?

**Comment by jantimon** [comment]
Oh 😨  sorry for that..  
You are right this should be reflected in the documentation - would you like to create a small pr?

**Comment by sjoqvist** [comment]
No worries. I learned more about this plugin along the way. :) Sure, I'll create one.
