### ISSUE TITLE
Expose asset dependencies to template

### ISSUE THREAD

**Issue by driskell** [jantimon/html-webpack-plugin#1585]
**Is your feature request related to a problem? Please describe.**

Maybe this is the wrong plugin but I have never found anything as reliable for generating asset manifests that can be loaded by WordPress/Drupal/Symfony projects. Usually just generating YML files that describe the assets that the project should be loading.

Over time I've started to split down a very large project's frontend code into many different bundles to load at relevant times, and split out common code into common bundles using code splitting. However, this creates a problem in that the Html-Webpack-Plugin just has `css` and `js` entries in `files` so everything is clumped together. There's no way to know that a specific `js` file is only used by a specific entry point. Ideally it would be great to generate the manifest to say that when code needs X entry point it needs to load files Y, Z, A and B (because Y is the main output, and the others dependencies containing code from code splitting). That way the project knows the exact set of files needed for each page and only needs to know which entry point corresponds to that page.

**Describe the solution you'd like**
It would be nice if we could also have a `entries` or something in the `files` variable that is essentially entry point as key and an array of required files as value. Then you could use a single Html-Webpack-Plugin to generate a YML output saying that here are my bundle outputs (based on entry point) and here are the list of files each bundle requires.

**Describe alternatives you've considered**
I've achieved a kind of result by using Html-Webpack-Plugin multiple times and filtering by each entry point chunk. Each generated file then describes each chunk and only it's dependencies so the project knows when it needs said bundle (chunk) it also needs the other commons entries. However it creates a lot of files and makes a mess of the web pack configuration, and effectively for our use case means another post-webpack step to combine these files because our projects expect a single manifest of assets.

**Additional context**
Using @next I can see this would only need a few extra lines for `htmlWebpackPluginAssets` like below. Would be great to hear if this is a complete mis-use of the plugin or if this is something that would be considered a useful feature.

```
      entryPointPublicPaths.forEach((entryPointPublicPath) => {
        const extMatch = extensionRegexp.exec(entryPointPublicPath);
        // Skip if the public path is not a .css, .mjs or .js file
        if (!extMatch) {
          return;
        }
        if (!assets.entries[entryName]) {
            assets.entries[entryName] = [];
        }
        assets.entries[entryName].push(entryPointPublicPath);
```

Would be great to hear if there are other tools too but I like html-webpack-plugin as it's pretty much 99% what we need and superbly maintained in the community <3. OK we're generating YML not HTML but it's all the same just generated code. We just use js-yaml in the template and output a JS object we build inside the template code. Adding this `entries` would give all information a template needs to generate all kinds of outputs - including directly generating a Drupal 8 libraries.yml or even a WordPress functions.php snippet that defines scripts and an exact set of dependencies for them. Happy to PR.

**Comment by jantimon** [comment]
I saw a lot of people generating `.json` files so I guess generating `yml` files is also fine :)

The feature you are talking about has been requested before and was doable with html-webpack-plugin 3.2.  
Unfortunately it got lost during the html-webpack-plugin 4.x refactoring..

I guess the challenge here is that the hooks which the html-webpack-plugin provides should stay in sync with the `asset.entries`. If you have a good solution in mind send in a PR and we can discuss there :)

**Comment by driskell** [comment]
@jantimon Thanks. I've applied the patch I'm currently using to make things work and raised #1587 

I will add a comment in there about hooks.

**Comment by jantimon** [comment]
Thanks @driskell I tried to describe the problem with the hooks in your PR.  
Please let me know if it makes any sense :)
