### ISSUE TITLE
require() tags not working in template

### ISSUE THREAD

**Issue by bigskillet** [jantimon/html-webpack-plugin#1586]
`<%= require() =%>` tags are not working with template. Could this be related to `html-loader` removing interpolation, or am I using the wrong tags?

## Current behaviour 💣

The tags simply pass though and are not recognized or populated. Viewing in the browser, you simply see the tags. Here are two versions I've tried:
```
<%= require('html-loader!./partial.html') =%>
<%= require('./partial.html').default =%>
``` 

## Expected behaviour ☀️

I'm expecting to see the partial content populate the screen, not the `require()` tag.

## Environment 🖥

```
"html-loader": "^1.3.2"
"html-webpack-plugin": "5.0.0-alpha.6",
"webpack": "^5.12.2"
```

**Comment by jantimon** [comment]
html-loader does not support `<%=`.

You need to use a loader which supports interpolations.

For example this one:

https://www.npmjs.com/package/underscore-template-loader

But you can also use other template loaders (ejs/twig/handlebars...) or even jsx

**Comment by cocodelacueva** [comment]
Hi, but you have it as an example here:
https://github.com/jantimon/html-webpack-plugin/blob/master/examples/custom-template/template.html

**Comment by jantimon** [comment]
@cocodelacueva the example you meantioned is not using the `html-loader`

**Comment by b3nk3** [comment]
@jantimon what does it use then?

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title><%= htmlWebpackPlugin.options.title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= require('html-loader!./partial.html').default %>
</body>
</html>
```

**Comment by jantimon** [comment]
This loader is used: https://github.com/jantimon/html-webpack-plugin/blob/main/lib/loader.js

**Comment by b3nk3** [comment]
I might be really thick here, but where is that referenced in the example?

I have a similar setup, only my `template.html` is `.ejs`.

Repo is on the latest webpack/htmlwebpackplugin but it is not working.

**Comment by jantimon** [comment]
It's the default loader
