### ISSUE TITLE
The img tag in the HTML is not parsed

### ISSUE THREAD

**Issue by ttttttssssss** [jantimon/html-webpack-plugin#1591]
## Current behaviour 💣

The image src path in HTML is not loader when i use HtmlWebpackPlugin's template.

Pictures are not packaged.

```html
<!--template-->
<img src="./room.png" alt="">
```
## Expected behaviour ☀️

```shell
execute npm run build
There is a picture(room.png) in dist folder
```

### Reproduction Example 👾

**dir tree**
```shell
.
├── dist
│   ├── index.html
│   └── main.js
├── package-lock.json
├── package.json
├── src
│   ├── index.html
│   ├── index.js
│   └── room.png
└── webpack.config.js
```

**package.json**

```json
{
  "name": "blog",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^5.0.1",
    "html-webpack-plugin": "^4.5.1",
    "style-loader": "^2.0.0",
    "webpack": "^5.19.0",
    "webpack-cli": "^4.4.0"
  }
}

```

**webpack.config.js**

```js
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin')
const path = require('path');

const src = path.join(__dirname, './src');

module.exports = {
    mode: "production",
    output: {
        path: path.join(__dirname, 'dist')
    },
    module: {
        rules: [
            {
                test: /\.(png|jpg|jpeg|gif)$/i,
                type: 'asset/resource',
                generator: {
                    filename: '[name][ext]'
                }
            },
        ]
    },
    plugins: [
        new CleanWebpackPlugin(),
        new HtmlWebpackPlugin({
            template: path.join(src, 'index.html')
        })

    ]
}
```

**index.js**
```js
// empty
```

## Environment 🖥

Operating System: mac 11.0.1

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"

Node.js v12.19.0
darwin 20.1.0

npm --version

6.14.8

npm ls webpack

└── webpack@5.19.0 

npm ls html-webpack-plugin

└── html-webpack-plugin@4.5.1 

```

**Comment by jantimon** [comment]
You have two options:

By default the html-webpack-plugin is using the a loader with lodash template syntax - to make the loader aware of the image you can use this syntax: `<img src="<%= require('./logo.png' %>">`

Another option is to use a different webpack loader which supports automatic html parsing and resource loading - one example for that is the html-loader

**Comment by ttttttssssss** [comment]
so good！

**Comment by ttttttssssss** [comment]
But the reality is more complicated.

i use `handlerbars` template
**webpack.config.js**

```js
 new HtmlWebpackPlugin({
      template: './views/index/index.hbs',
      filename: 'index.html',
      title: 'index',
      favicon: path.join(src, './assets/image/favicon.ico'),
      chunks: ['index']
    }),
```
**handlerbars**

```hbs
<img width="100" height="100" src="<%= require('~@/image/room.png')%>" alt="img">

```

**render**
> As a result, `<%= require('~@/image/room.png')%>` is treated as a `string`
```html 
<img width="100" height="100" src="<%= require('~@/image/room.png')%>" alt="img">
```

**Comment by ttttttssssss** [comment]
I found that there is a syntax that can be used in HTML.

```html
<% function foo(e){ return e };%>
<%= foo('echo')%>
```

He's kind of like `EJS`.Or what is the name of the syntax？I don't see any information about this grammar on the `readme`.

Can it implement the function of the template ? 

He is like 

**art-template**
```art-template
{{extend './layout.art'}}
{{block 'body'}}
   <div>inline-text</div>
{{/block}}
```


**hbs**
```hbs
{{#> layout}}
  {{#*inline "body"~}}
  <div>hello world</div>
  {{~/inline}}
{{/layout}}
```
**ejs**
```ejs
<%- include('header'); -%>
<h1>
  Title
</h1>
<p>
  My page
</p>
<%- include('footer'); -%>
```

**Comment by jantimon** [comment]
It is using the syntax of https://lodash.com/docs/4.17.15#template (very similar to ejs) but you can use for example:

- handlebars-loader for hbs
- ejs-compiled-loader for ejs
- art-template-loader for art

you can also use javascript without any loader e.g.:

```js
new HtmlWebpackPlugin({ template: './template.js' })
```

and `template.js`

```js
const generateBody = () => {
  return "Demo"
}

export default () => `<html>
<head><title>Demo</title></head>
<body>
  ${generateBody()}
</body>
</html>`;
```

**Comment by ttttttssssss** [comment]
Thank you for your answer

**Comment by SinaBYR** [comment]
> You have three options:
> 
> By default the html-webpack-plugin is using the a loader with lodash template syntax - to make the loader aware of the image you can use this syntax: `<img src="<%= require('./logo.png' %>">`
> 
> Another option is to use a different webpack loader which supports automatic html parsing and resource loading - one example for that is the html-loader
> 
> The third option is to use the copy-webpack-plugin to copy the files to the dist folder

Thank you, Jan! Option 2 (html-loader) worked pretty well.

**Comment by CHHuy** [comment]
spending >2hrs looking for solution and end up with this post from 2 yrs ago, thank you so much @jantimon
