### ISSUE TITLE
How to correctly generate multiple HTML files?  ERROR in Conflict: Multiple assets emit different content to the same filename index.html

### ISSUE THREAD

**Issue by raphael10-collab** [jantimon/html-webpack-plugin#1604]
According to the docs, to generate multiple HTML files, I have to declare the plugin more than once.

    plugins: [
      new HtmlWebpackPlugin({
        title: 'MainWindowTemplate',
        template: './index.html'
      }),
      new HtmlWebpackPlugin({
        title:'WindowTypeATemplate',
        template: './index_A.html'
      }) 
    ]

    (base) marco@pc01:~/webMatters/electronMatters/Raphy-Template$ ls -lah | grep .html
    -rwxr-xr-x    1 marco marco  154 feb 17 09:55 index_A.html
    -rwxr-xr-x    1 marco marco  187 feb 16 18:14 index.html

I get this error:

    (base) marco@pc01:~/webMatters/electronMatters/Raphy-Template$ yarn start
    yarn run v1.22.5
    $ yarn run build && electron ./dist/main/main.js
    $ webpack --config ./webpack.config.js
    asset main.js 7.64 MiB [compared for emit] (name: main)
    runtime modules 1.06 KiB 6 modules
    javascript modules 6.03 MiB
      cacheable modules 6.03 MiB 1216 modules
      29 modules
    json modules 391 KiB
      modules by path ./node_modules/har-schema/lib/*.json 6.93 KiB 18 modules
      modules by path ./node_modules/encoding/node_modules/iconv-lite/encodings/tables/*.json 86.7 KiB 8 modules
      modules by path ./node_modules/ajv/lib/refs/*.json 5.58 KiB
        ./node_modules/ajv/lib/refs/json-schema-draft-06.json 2.46 KiB [built] [code generated]
        ./node_modules/ajv/lib/refs/json-schema-draft-07.json 2.72 KiB [built] [code generated]
        ./node_modules/ajv/lib/refs/data.json 409 bytes [built] [code generated]
      7 modules
    webpack 5.22.0 compiled successfully in 6293 ms

    asset renderer.js 1.45 KiB [compared for emit] (name: main)
    asset index.html 195 bytes [emitted]
    ./src/renderer/renderer.js 184 bytes [built] [code generated]

    ERROR in Conflict: Multiple assets emit different content to the same filename index.html

    electron: 11.2.3
    npm: v7.5.2
    node: v14.5.0
    O.S.: Ubuntu 18.04.4 Deskotp

    npm ls webpack
    Raphy-Template@1.0.0 /home/marco/webMatters/electronMatters/Raphy-Template
    ├─┬ babel-loader@8.2.2
    │ └── webpack@5.22.0 deduped
    ├─┬ copy-webpack-plugin@7.0.0
    │ └── webpack@5.22.0 deduped
    ├─┬ css-minimizer-webpack-plugin@1.2.0
    │ └── webpack@5.22.0 deduped
    ├─┬ eslint-loader@4.0.2
    │ └── webpack@5.22.0 deduped
    ├─┬ file-loader@6.2.0
    │ └── webpack@5.22.0 deduped
    ├─┬ html-loader@1.3.2
    │ └── webpack@5.22.0 deduped
    ├─┬ html-webpack-plugin@5.1.0
    │ └── webpack@5.22.0 deduped
    ├─┬ node-polyfill-webpack-plugin@1.0.2
    │ └── webpack@5.22.0 deduped
    ├─┬ ts-loader@8.0.17
    │ └── webpack@5.22.0 deduped
    ├─┬ url-loader@4.1.1
    │ └── webpack@5.22.0 deduped
    ├─┬ webpack-cli@4.5.0
    │ ├─┬ @webpack-cli/configtest@1.0.1
    │ │ └── webpack@5.22.0 deduped
    │ └── webpack@5.22.0 deduped
    ├─┬ webpack-dev-server@3.11.2
    │ ├─┬ webpack-dev-middleware@3.7.3
    │ │ └── webpack@5.22.0 deduped
    │ └── webpack@5.22.0 deduped
    └─┬ webpack@5.22.0
      └─┬ terser-webpack-plugin@5.1.1
        └── webpack@5.22.0 deduped

    (base) marco@pc01:~/webMatters/electronMatters/Raphy-Template$ npm ls html-webpack-plugin
    Raphy-Template@1.0.0 /home/marco/webMatters/electronMatters/Raphy-Template
    └── html-webpack-plugin@5.1.0

How to solve the problem?

**Comment by jantimon** [comment]
By default the html-webpack-plugin generates a new file called `index.html`.  
You didn't change that default so now both plugin instances create a new file called `index.html`.  

Webpack is now confused which `index.html` is the correct one and shows this error.

To fix it you will need to set the `filename` option to define another output filename.

**Comment by raphael10-collab** [comment]
Thank you @jantimon . I understand now that it's the `filename` parameter the cornerstone parameter.


    plugins: [
      new HtmlWebpackPlugin({
        title: 'MainWindowTemplate',
        filename: 'index.html',
        template: './index.html',
        chunks: ['MainWindowEntry']
      }),
      new HtmlWebpackPlugin({
        title:'WindowTypeATemplate',
        filename: 'index_A.html',
        template: './src/app_A/index_A.html',
        chunks: ['WindowTypeAEntry']
      })
    ]

With a different `filename` it works.

Thank you very much.
