### ISSUE TITLE
attributes

### ISSUE THREAD

**Issue by superwf** [jantimon/html-webpack-plugin#1608]
https://github.com/jantimon/html-webpack-plugin/blob/2e30bb13d52f90264f0bd248f077cfec84930ec3/typings.d.ts#L285

meta for each tag may should be optional?

**Comment by jantimon** [comment]
adding it as non optional property was a breaking change from 4 to 5

this allows better filtering for example if you want to have only tags from the favicons-webpack-plugin

**Comment by superwf** [comment]
My plugin tag use HtmlTabObject type for param type, and the _meta_ is not required.
Never mind. I already use a modified type.
`type TagObject = Omit<HtmlTagObject, 'meta'> & {
  meta?: HtmlTagObject['meta']
}
`

**Comment by jantimon** [comment]
Don't hack the type - just add `meta: { pluginName: "yourPlugin" }`
