### ISSUE TITLE
export `instanceOptions` to custom plugin?

### ISSUE THREAD

**Issue by creeperyang** [jantimon/html-webpack-plugin#1611]
**What?**

The `instanceOptions` means the `options` in `hookIntoCompiler (compiler, options, plugin)`.

**Why?**

Give custom plugins the chance to access the **real** resolved `filename`/`template` data.

**Comment by jantimon** [comment]
Yes that would probably be helpful 👍 

Right now you can access only `plugin.options` and `plugin.userOptions`
