### ISSUE TITLE
Webpack build fails with module is not defined

### ISSUE THREAD

**Issue by fivethreeo** [jantimon/html-webpack-plugin#1614]
## Current behaviour 💣

When building with a custom html template the webpack build fails with

```
module.exports = __webpack_require__.p + "static/media/javascript,__webpack_pu  blic_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;.aed5664e.bin  ";\n' +
      '  ^\n' +
      '  ReferenceError: module is not defined\n' +
```

## Expected behaviour ☀️

Should build successfully

## Environment 🖥

Webpack 5.24.0
Html-webpack-plugin 5.2.0

# Fix 

Removing this line makes it build correctly

https://github.com/jantimon/html-webpack-plugin/blob/main/lib/child-compiler.js#L119

**Comment by jantimon** [comment]
Sorry without more information it's impossible to reproduce or fix the issue..

**Comment by fivethreeo** [comment]
For some reason this Entry becomes commonjs with module.exports.

**Comment by fivethreeo** [comment]
Do I need some raw loader?

**Comment by jantimon** [comment]
I assume one of your loader configurations is breaking the build

**Comment by fivethreeo** [comment]
I will close this and investigate more :)

**Comment by fivethreeo** [comment]
Was file-loader, but how to exclude data:text/javacript?

**Comment by fivethreeo** [comment]
If anoyone else has this issue, here is a soultion

```js

{
  exclude: [
    /\.html$/,
    /\.(js|jsx|mjs)$/,
    /\.(ts|tsx)$/,
    /\.(vue)$/,
    /\.(less)$/,
    /\.(re)$/,
    /\.(s?css|sass)$/,
    /\.json$/,
    /\.bmp$/,
    /\.gif$/,
    /\.jpe?g$/,
    /\.png$/
  ],
  use: (info) => {
    return info.compiler !== 'HtmlWebpackCompiler' ? [{
      loader: require.resolve('file-loader')
    }]:[]},
  }

```
