### ISSUE TITLE
How to specify output location not relative to webpack output.path?

### ISSUE THREAD

**Issue by ryancole** [jantimon/html-webpack-plugin#1615]
Hello,

I'm trying to use the HTML webpack plugin, but I can't get the output file to end up where I need it to be. Currently our webpack config saves output to a folder like "/dist/scripts". All of our JS files end up there.

I want this index.html file to output to "/dist/index.html".

I can't figure out how to do this via the plugins config, though. Any ideas?

Is my JS loader output not optimal? Is there a way to set webpack's output.path to something like "/dist" and then tell the JS loader to spit out the output into "/dist/scripts"? I suppose that would fix this for me as well.

Thanks

**Comment by jantimon** [comment]
There are multiple ways which all come with pros and cons:

move `scripts` to entry:

```js
entry: { 'scripts/main' : './src/index.js' }
```

change the [output options](https://webpack.js.org/configuration/output/):

```js
output: { filename: 'scripts/[name].js' }
```

overrule the public path:

```js
new HtmlWebpackPlugin({
  publicPath: 'scripts/'
})
```

**Comment by ryancole** [comment]
OK. Thank you. I went with a combination of modifying the output location and overriding the `HtmlWebpackPlugin.publicPath` setting. I didn't quite understand the ramifications of the entry adjustment.
