### ISSUE TITLE
It becomes an object

### ISSUE THREAD

**Issue by xzy-96** [jantimon/html-webpack-plugin#1616]
![image](https://user-images.githubusercontent.com/51942062/109959891-0f5ccf00-7d23-11eb-8dfa-104a427fd8c3.png)

let HtmlWebpackPlugin = require("html-webpack-plugin")
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const ESLintPlugin = require('eslint-webpack-plugin');

**Comment by xzy-96** [comment]
I use url-loader

**Comment by xzy-96** [comment]
in html

**Comment by jantimon** [comment]
Which loaders do you use for your html files and for your images?

**Comment by xzy-96** [comment]
> 您将哪些加载程序用于html文件和图像？

thank you I'm using HTML-withIMG-loader.

It's the reason
