### ISSUE TITLE
compile html bug

### ISSUE THREAD

**Issue by ouyangzhigang** [jantimon/html-webpack-plugin#1627]
## Environment 🖥
node v6.8.1
webpack v2.7.0
html-webpack-plugin v2.30.1

## template

<body>
  <div id="app"></div>
  <template id="temp">
    <div
      class="integral-center-wrapper"
      :class="iosClass"
      >
      <template v-if="!networkErr">
        
        <template v-if="showSkeleton">
          <div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 1.64rem; left: 0.3rem; width: 0.9rem; height: 0.9rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 1.66rem; left: 1.26rem; width: 2.64063rem; height: 0.54rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 2.2rem; left: 1.26rem; width: 2.64063rem; height: 0.32rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 1.78rem; left: 5.19rem; width: 2.01rem; height: 0.62rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 2.86rem; left: 0.3rem; width: 6.9rem; height: 3.84rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 6.95rem; left: 0.6325rem; width: 1.06rem; height: 1.06rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 8.19rem; left: 0.6825rem; width: 0.96rem; height: 0.24rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 6.95rem; left: 2.3575rem; width: 1.06rem; height: 1.06rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 8.19rem; left: 2.4075rem; width: 0.96rem; height: 0.24rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 6.95rem; left: 4.0825rem; width: 1.06rem; height: 1.06rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 8.19rem; left: 4.1325rem; width: 0.96rem; height: 0.24rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 6.95rem; left: 5.8075rem; width: 1.06rem; height: 1.06rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 8.19rem; left: 5.8575rem; width: 0.96rem; height: 0.24rem;">
            </div>
            <div
              style="position: absolute; background-color: rgb(239, 239, 239); top: 8.97rem; left: 0.3rem; width: 6.9rem; height: 1.80156rem;">
            </div>
          </div>
        </template>
        <template v-else>
          
          <nav-header
                  title="积分中心"
                  @emit-header="headerClick"
                  :title-color="titleColor"
                  :left="leftUrl"
                  :background="bg"
                  :right-icons="rightIcons"
          ></nav-header>
          <div class="integral-center-box">
            <div class="sec1">
              <div class="t0" :key="t0key">
                  <div class="jb bounce-down-infinite" @tap.stop.prevent="clickJb($event,task,index)" v-for="(task, index) in cacheArr||pendingReceivePoints" v-if="index<3">
                    <div class="p1">
                      {{task.point}}
                    </div>
                    <div class="p2">{{task.name}}</div>
                  </div>
              </div>
              <div class="t1" ref="t1" :class="{'down-one':showDown}">
                <div class="u1">
                  <div class="p1" skeleton  @tap.stop.prevent="routerPush('INTEGRAL_DETAIL', '1400602')">
                    <span class="integral-num" ref="integral">{{integralAmt}}</span>
                    <img class="allow" src="https://cdn.daikuan.360.cn/pic/f96e57d1b541af75aa08a4d60e287ef4.png?max_age=2592000" />
                  </div>
                  <div class="p2" skeleton v-if="+showRateStatus === 1">
                    积分等值金额≈{{integralCache}}元
                  </div>
                </div>
                <div class="p3" @tap.stop.prevent="routerPush('INTEGRAL_MALL', '1400603')">提现</div>
              </div>

              <div class="s3" v-if="Array.isArray(signList) && signList.length > 0">
                
                <div class="date" skeleton>
                  <div class="flex-between-center sign-in-tips">
                    <div class="item"  @tap.stop.prevent="goSignDetail(1400634)">
                      <Carousel :interval="2000">
                        <p v-for="v,k in loopTextArr" :key="'a'+k" v-html="v"></p>
                        <p v-for="v,k in loopTextArr" :key="'b'+k" v-html="v"></p>
                        <p v-for="v,k in loopTextArr" :key="'c'+k" v-html="v"></p>
                      </Carousel>
                      <img src="https://cdn.daikuan.360.cn/pic/5e9811a91e7a4aec3af4253f7dee61f1.png?max_age=2592000" @tap="routerPush('INTEGRALCRULE', '1400604')" />
                    </div>
                    <div class="item">
                      <p>签到提醒</p>
                      <Popup tips="已开" :value="notificationSettingOn" :class="[notificationSettingOn?'on':'off']" @change="setNotification(1, '1400605')" />
                    </div>
                  </div>
                  
                  <Scrollable :current="continDay" :padding="'0 0.22rem 0'">
                    <template v-for="(item, index) in signWeekList">
                      <div class="sign-item" :key="index"  @tap="goSignDetail(1400635)" :class="[+item.receiverStatus === 1 && +signSettingStatus !== 0 ? 'today-item' : '', +item.receiverStatus === 0  ? '' : +signSettingStatus === 1 ? 'signed-item' : '']">
                        <div class="sign-item-content">
                          <div class="popover" v-show="item.other"  v-if="item.other">
                            <div class="popover-content">
                              <span v-if="item.other.couponDesc">
                                {{item.other.couponDesc}}
                              </span>
                              <span v-else-if="item.other.signPoint">
                                +{{item.other.signPoint}}
                              </span>
                            </div>
                            <div class="triangle"></div>
                          </div>
                          <img :src="+item.receiverStatus !== 0 ? 'https://cdn.daikuan.360.cn/pic/14281b38b641cddbb1939b678e54b8a7.png?max_age=2592000' : 'https://cdn.daikuan.360.cn/pic/4678bf528eb89fa64975b3779c3f5dcf.png?max_age=2592000'" />
                          <p class="num">+{{item.dailyNum}}</p>
                        </div>
                        <p>{{+item.receiverStatus === 1 ? '今' : item.day}}天</p>
                      </div>
                    </template>
                  </Scrollable>
                </div>
              </div>
            </div>

            
            <div class="sec2" v-if="Array.isArray(dailyWealfareIcons) && dailyWealfareIcons.length > 0">
              <div class="icon-container">
                <template v-for="(item, index) in dailyWealfareIcons">
                  <div class="icon-item left" :key="index" @tap="handleIconsTap(item, index)">
                    <img :src="item.iconPic" skeleton />
                    <p skeleton>{{item.iconTitle}}</p>
                  </div>
                </template>
              </div>
            </div>

            
            <div class="sec4" v-if="(hotTask.list && Array.isArray(hotTask.list) && hotTask.list.length > 0) || (hotTask.stepList && Array.isArray(hotTask.stepList) && hotTask.stepList.length) > 0">
              <p class="top-title">做任务 赚积分</p>
              <div class="step-task-box" v-if="hotTask.stepList && hotTask.stepList.length > 0">
                <step-task :list="hotTask.stepList"  event-id='1401001' @show-desc="showStepTaskDesc" @receive-task="getIntegral" @btn-tap="btnTap" />
              </div>
              <div class="list" v-if="hotTask.list && hotTask.list.length > 0">
                <div class="list-box">
                  <Task-Item v-for="(item, index) in hotTask.list" :data="item" :key="index" @btn-tap="btnTap(item)" @tap="showTaskDec(index)" class-name="no-border">
                  </Task-Item>
                  <p class="more-btn flex align-center justify-center" @tap.stop.prevent="routerPush('integral_task_management.html?currentTab=0', '1400611')">
                    <span>共{{hotTask.taskNum}}个任务，至少可得</span>
                    <span class="red2">{{hotTask.taskBenefit}}积分</span><img src="https://cdn.daikuan.360.cn/pic/2ebb2310616c7851cd9a809216b230e4.png?max_age=2592000" />
                  </p>
                </div>
              </div>
            </div>

            
            <div class="sec3" v-if="Array.isArray(dailyWealfareBanners) && dailyWealfareBanners.length > 0">
              <swipe
              style="border-radius: 0.08rem;"
              :margin="20"
              :initial-swipe="0"
              :autoplay="4000">
                <swipe-item
                        slot="swipes"
                        v-for="(item, i) in dailyWealfareBanners"
                        :key="i"
                        @tap="handleBannderTap(item, i)">
                    <img skeleton :src="item.bannerPic" />
                </swipe-item>
              </swipe>
            </div>
            
            
            <div class="sec5" style="marginTop: .76rem;" v-if="Array.isArray(integralGameIcons) && integralGameIcons.length > 0">
              <div class="flex-between-center sec5-title">
                <p class="top-title">
                  精彩游戏
                </p>
                <p class="more-btn"  @tap.stop.prevent="handleStartGame">
                  查看更多
                  <img src="https://cdn.daikuan.360.cn/pic/2ebb2310616c7851cd9a809216b230e4.png?max_age=2592000" />
                </p>
              </div>
              <div class="game-list">
                <ul class="ul">
                  <li class="li" v-for="(item, index) in integralGameIcons" :key="index" @tap="handleGameTap(item,index)">
                    <div class="left">
                      <div class="p1">{{item.iconTitle}}</div>
                      <div class="p2">{{item.iconSubTitle}}</div>
                    </div>
                    <div class="right"><img :src="item.iconPic" /></div>
                  </li>
                </ul>
              </div>

            </div>

            
            <div class="sec5" style="marginTop: .76rem;" v-show="showExchange">
              <div class="flex-between-center sec5-title">
                <p class="top-title">
                  兑换现金
                </p>
                <p class="more-btn"  @tap.stop.prevent="goMall">
                  查看更多
                  <img src="https://cdn.daikuan.360.cn/pic/2ebb2310616c7851cd9a809216b230e4.png?max_age=2592000" />
                </p>
              </div>
              <exchange-money @feedback="exchangeFeedback"></exchange-money>
            </div>

            
            <div class="sec5" style="marginTop: .76rem;" v-if="couponArr.length">
              <div class="flex-between-center sec5-title">
                <p class="top-title">
                  兑优惠券
                </p>
                <p class="more-btn"  @tap.stop.prevent="goCoupon">
                  查看更多
                  <img src="https://cdn.daikuan.360.cn/pic/2ebb2310616c7851cd9a809216b230e4.png?max_age=2592000" />
                </p>
              </div>
              <exchange-coupon></exchange-coupon>
            </div>
            
            <div class="sec5" style="marginTop: .76rem;" v-if="limitGoods && limitGoods.list && limitGoods.list.length>0" :key="limitKey">
              <div class="flex-between-center sec5-title">
                <p class="top-title">
                  限时秒杀
                  <span class="p1">· 每日10点开抢</span>
                </p>
                <p class="more-btn"  @tap.stop.prevent="goLimitActivity" v-if="limitGoods.homePageUrl">
                  查看更多
                  <img src="https://cdn.daikuan.360.cn/pic/2ebb2310616c7851cd9a809216b230e4.png?max_age=2592000" />
                </p>
              </div>
              <div class="limittime-list">
                <div class="ul">
                  <div class="li" v-for="(item,key) in limitGoods.list" :key="key" @tap="goLimitDetail(item,key)">
                    <div class="list-top" :style="{backgroundImage: item.goodImg ? `url(${item.goodImg})` : ''}">
                      <p class="goods-price">
                        <span class="price">{{item.originalYuanPrice.replace(/\.00$/,'')}}</span><span class="unit">元</span>
                      </p>
                    </div>
                    <div class="list-bottom">
                      <div class="goods-name">
                        {{item.name}}
                      </div>
                      <div class="p2" :class="{qiang:+item.goodStatus===10}">
                        <img src="https://cdn.daikuan.360.cn/pic/5a3a2a0046ff3817a2fb414028c6998d.png?max_age=2592000" alt="">
                        <p class="coin-detail">
                          {{item.secCredits}}<span>{{item.facePrice}}</span>
                        </p>
                        <div class="exchange-btn off" v-if="+item.goodStatus===0">未开始</div>
                        <div class="exchange-btn" v-else-if="+item.goodStatus===10"><img src="https://cdn.daikuan.360.cn/pic/68af694cc23a7ebec8fff8e1f27dbabd.png?max_age=2592000" />抢</div>
                        <div class="exchange-btn disable" v-else-if="+item.goodStatus===20">已结束</div>
                        <div class="exchange-btn disable" v-else>已抢光</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            
            <div class="sec5" style="marginTop: .76rem;" v-if="duibaGoods && duibaGoods.list && duibaGoods.list.length">
              <div class="flex-between-center sec5-title">
                <p class="top-title">
                  特惠好礼
                </p>
                <p class="more-btn"  @tap="goActivity">
                  查看更多
                  <img src="https://cdn.daikuan.360.cn/pic/2ebb2310616c7851cd9a809216b230e4.png?max_age=2592000" />
                </p>
              </div>
              <ul class="sale-gift-list">
                <li v-for="item in duibaGoods.list" @tap="goDuiba(item.duibaGoodsUrl)">
                  <div class="list-top" :style="{backgroundImage: item.picUrl ? `url(${item.picUrl})` : ''}">
                    <p class="goods-price">
                      <span class="price">{{item.originalYuanPrice}}</span><span class="unit">元</span>
                    </p>
                  </div>
                  <div class="list-bottom">
                    <p class="goods-name">
                      {{item.name}}
                    </p>
                    <div class="p2">
                      <img src="https://cdn.daikuan.360.cn/pic/5a3a2a0046ff3817a2fb414028c6998d.png?max_age=2592000" alt="">
                      <p class="coin-detail">
                        {{item.newPrice}}
                      </p>
                      <div class="exchange-btn">兑换</div>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </template>        
      </template>

      <template v-else>
        <nav-header
          title="积分中心"
          @emit-header="routerPush('back')"
          title-color="#333333"
          left="./images/integral/back_grey.png"
          :background="{background: '#fff', borderBottom: '1px solid #EEEEEE'}"
        ></nav-header>
        
        <div class="sign-fail">
          <img src="https://cdn.daikuan.360.cn/pic/716206e0d94343edd62138382fe1e924.png?max_age=2592000" />
          <p>网络不给力</p>
          <p>世界上最遥远的距离莫过于此</p>
          <p @tap="init">刷新</p>
          <p @tap="init">修复</p>
        </div>
      </template>

      
      <div class="count-down" v-if="!!pointHomePendants && !!pointHomePendants.length" @click="pendantClick(pointHomePendants[0])">
        <img :src="pointHomePendants[0].imageUrl">
        <p>
          <Target :end="pointHomePendants[0].targetTime.replace(/-/g, '/')" :system="pointHomePendants[0].systemTime.replace(/-/g, '/')" deal="1">
            <template slot-scope="item">
              <template v-if="item.time.end">
                <span>开奖中</span>
              </template>
              <template v-else>
                夺宝<span v-if="item.time.day !== '00'">{{item.time.day}}天</span><span>{{item.time.hour}}</span>:<span>{{item.time.min}}</span>:<span>{{item.time.sec}}</span>
              </template>
            </template>
          </Target>
        </p>
      </div>

      
      <modal-box v-if="showSignModal" animate>
        <div class="signed-box-contont" :class="[modalSignObj.className]">
          <img class="signed-box-bg" :src="modalSignObj.imgUrl" />
          <div class="sign-box-message" v-if="modalSignObj.className==='sign-1'">
            <p class="p1">连续签到<span>{{modalSignObj.continDay}}</span>天</p>
            <p class="p2">
              <span class="plus">+</span>
              <span class="daily-point">{{modalSignObj.point}}</span>
              <span class="jf">积分</span>
            </p>
            <p class="p3">{{modalSignObj.finalAwardText}}</p>
          </div>
          <div class="sign-box-message" v-else-if="modalSignObj.className==='sign-2'">
            <p class="p0">连续签到<span>{{modalSignObj.continDay}}</span>天</p>
            <div class="p1"><div class="line"></div>恭喜获得<div class="line"></div></div>
            <p class="p2">{{modalSignObj.continArardText}}</p>
            <div class="p3">同时获得<img src="https://cdn.daikuan.360.cn/pic/1196e92823a88918b4c1235204b002da.png?max_age=2592000"/>{{modalSignObj.point}}</div>
            <p class="p4">{{modalSignObj.finalAwardText}}</p>
          </div>
          <div class="signed-box-btn" @tap="modalSignObj.func">{{modalSignObj.txt}}</div>
          <img class="signed-box-close" src="https://cdn.daikuan.360.cn/pic/816f06ed1dbca7512c6b736e7f9a5175.png?max_age=2592000" @tap="closeSignModal" />
        </div>
      </modal-box>

      
      <modal-box v-if="showModal" animate>
        <div class="signed-box-contont">
          <img class="signed-box-bg" :src="modalObj.imgUrl" />
          <div class="sign-box-message">
            <p>
              <span class="plus">+</span>
              <span class="daily-point">{{modalObj.point}}</span>
              <span>积分</span>
              <span class="extral-point" v-if="modalObj.continPoint">
                  含额外奖励{{modalObj.continPoint}}分
              </span>
            </p>

            
            <template v-if="modalObj.taskBenefitToday">
              <p>今日共获得积分+{{modalObj.taskBenefitToday}}</p>
            </template>
            

            
            
            <template v-else-if="signList.length > 0 && +signList[signList.length - 1].receiverStatus === 1">
              <p>新一轮签到明天开始啦～</p>
            </template>
            <template v-else>
              <p>再接再厉，您已连续签到<span>{{modalObj.continDay}}</span>天</p>
            </template>
            

          </div>
          <div class="signed-box-btn" @tap="modalObj.func">{{modalObj.txt}}</div>
          <template v-if="modalObj.noticeBtn">
            <div class="signed-box-switch">
              <p>签到提醒</p>
              <Popup tips="开" :value="notificationSettingOn" @change="setNotification(0,  '1400606')">
                <span class="switch-close-tips" v-if="!notificationSettingOn">关</span>
              </Popup>
            </div>
          </template>
          <template v-if="modalObj.adUrl">
            <div class="signed-ad">
              <img class="signed-ad-img" :src="imgUrlObj.bg1" />
            </div>
          </template>
          <img class="signed-box-close" src="https://cdn.daikuan.360.cn/pic/816f06ed1dbca7512c6b736e7f9a5175.png?max_age=2592000" @tap="operateStatus('showModal', false)" />
        </div>
      </modal-box>

      
      <modal-box v-if="showTaskDecModal" animate>
        <div class="tips-box modal-3">
          <img class="tips-close" src="https://cdn.daikuan.360.cn/pic/c9aad98060999bd6799bb2293c64b893.png?max_age=2592000" @tap="operateStatus('showTaskDecModal', false)" />
          <img class="tips-img-1" :src="currentTask.taskImage" />
          <p class="tips-1">{{currentTask.taskName}}</p>
          <p class="tips-2">
            
            <template v-if="(!currentTask.canReceivePointMax && !currentTask.canReceivePointMin)">
              奖励+{{currentTask.taskFinishedBenefitnum}}积分
            </template>
            <template v-else-if="+currentTask.canReceivePointMin === +currentTask.canReceivePointMax">
              奖励+{{currentTask.canReceivePointMin}}积分
            </template>
            
            <template v-else>
              奖励{{currentTask.canReceivePointMin}}-{{currentTask.canReceivePointMax}}积分
            </template>
          </p>
          <p class="tips-3">{{currentTask.taskDesc}}</p>
          <div class="tips-temp"></div>
          <p class="tips-btn" :class="{finished: currentTask.stepTask !== 'Y'}" @tap="receiveTask(currentTask)" v-if="+currentTask.taskFinishStatus === 0">
            <template v-if="currentTask.stepTask === 'Y'">
              去完成
            </template>
            <template v-else>
              +{{currentTask.taskFinishedBenefitnum}}积分
            </template>
          </p>
          <p class="tips-btn doing" @tap="continueTask(currentTask)" v-if="+currentTask.taskFinishStatus === 1">继续完成</p>
          <p class="tips-btn" @tap="getIntegral(currentTask)" v-if="+currentTask.taskFinishStatus === 2 && currentTask.stepTask !== 'Y'">领{{currentTask.taskFinishedBenefitnum}}积分</p>
          <p class="tips-btn" @tap="operateStatus('showTaskDecModal', false)" v-if="+currentTask.taskFinishStatus === 2 && currentTask.stepTask === 'Y'">我知道了</p>
          <p class="tips-btn done" v-if="+currentTask.taskFinishStatus === 3">已领取</p>
        </div>
      </modal-box>

      
      <modal-box v-if="showStatusModal">
        <div class="tips-box">
          <img class="tips-close" v-if="!statusModalObj.hideClose" src="https://cdn.daikuan.360.cn/pic/c9aad98060999bd6799bb2293c64b893.png?max_age=2592000" @tap="operateStatus('showStatusModal', false)" />
          <img class="tips-img" :src="statusModalObj.imgUrl" />
          <p class="tips-1">{{statusModalObj.title}}</p>
          <p class="tips-3" v-html="statusModalObj.dec"></p>
          <div :class="{'botn-btn': statusModalObj.btns.length > 1}">
            <template v-for="(item, index) in statusModalObj.btns">
              <p class="tips-btn" @tap="item.func">{{item.txt}}</p>
            </template>
          </div>
        </div>
      </modal-box>
      
      <div class="modal" v-if="showRightModel" @tap.stop.prevent="showRightModel=false">
        <div class="right-box">
          <div class="li" @tap.stop.prevent="fenx"><img src="https://cdn.daikuan.360.cn/pic/9da770186458805bdee44e2c235fb8e7.png?max_age=2592000"/>分享</div>
          <div class="li" @tap.stop.prevent="goJfgl"><img src="https://cdn.daikuan.360.cn/pic/c3505980429992f5efb1dac864b9951b.png?max_age=2592000"/>积分攻略</div>
        </div>

      </div>
      
      <modal-box v-if="showShareModel" bottom>
        <div class="share-box">
          <ul class="flex">
            <li class="item1" data-type="wechatFriends" @tap="share('wechatFriends', 1400618)">微信</li>
            <li class="item2" data-type="wechatMoments" @tap="share('wechatMoments', 1400619)">朋友圈</li>
            <li class="item3" data-type="qq" @tap="share('qq', 1400620)">QQ</li>
            <li class="item4" data-type="link" @tap="share('link', 1400621)">复制链接</li>
          </ul>
          <hr></hr>
          <div class="btn cancerbtn" :class="[iosClass]" @tap="operateStatus('showShareModel', false)">取消</div>
        </div>
      </modal-box>
    </div>
  </template>
  
</body>

## bug 💣
ERROR in Template execution failed: ReferenceError: item is not defined
ERROR in   ReferenceError: item is not defined

- integral_center.html:17294
    E:/project/package-h5/app/dist/integral_center.html:17294:10

  - integral_center.html:17299 module.exports
    E:/project/package-h5/app/dist/integral_center.html:17299:3

  - index.js:264
    [package-h5]/[html-webpack-plugin]/index.js:264:16

  - util.js:16 tryCatcher
    [package-h5]/[html-webpack-plugin]/[bluebird]/js/release/util.js:16:23

  - promise.js:547 Promise._settlePromiseFromHandler
    [package-h5]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:547:31

  - promise.js:604 Promise._settlePromise
    [package-h5]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:604:18

  - promise.js:641 Promise._settlePromiseCtx
    [package-h5]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:641:10

  - async.js:97 _drainQueueStep
    [package-h5]/[html-webpack-plugin]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [package-h5]/[html-webpack-plugin]/[bluebird]/js/release/async.js:86:9

  - async.js:102 Async._drainQueues
    [package-h5]/[html-webpack-plugin]/[bluebird]/js/release/async.js:102:5

## expection ☀️ 
dont compile template tag

**Comment by jantimon** [comment]
sorry html-webpack-plugin v2.30.1 is out of support :(
