### ISSUE TITLE
_webpack_base_uri__ is not defined

### ISSUE THREAD

**Issue by yumendexihai** [jantimon/html-webpack-plugin#1631]
"css-loader": "^5.1.3",
  "less": "^4.1.1",
  "less-loader": "^8.0.0",
  "style-loader": "^2.0.0",
  "webpack": "^5.26.3",
  "webpack-cli": "^4.5.0",
  "html-webpack-plugin": "^5.3.1"

const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'build'),
    filename: 'bundle.js'
  },
  module: {
    rules:[
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.less$/,
        use: ['style-loader', 'css-loader', 'less-loader']
      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin()
  ],
  // mode: 'production'
  mode: 'development'
}

**Comment by jantimon** [comment]
Please use the bug report template :)
