### ISSUE TITLE
Minifying JavaScript in script elements doesn't work if option "minifyJS" includes "comments" or "safari10".

### ISSUE THREAD

**Issue by Lohoyo** [jantimon/html-webpack-plugin#1635]
## Current behaviour 💣

Minifying JavaScript in script elements doesn't work if option "minifyJS" includes "comments" or "safari10".

## Expected behaviour ☀️

If the value of option “minifyJS” is an Object, minifying JavaScript in script elements does work whether option "minifyJS" includes "comments" / "safari10" or not.

### Reproduction Example 👾

Repository: https://github.com/Lohoyo/webpack-demo

Reproduction Step:
1. clone the repository above;
2. cd webpack-demo;
3. npm i;
4. npm run build;
5. Now, in the `dist/index.html`, you can see that JavaScript in script elements is not compressed.
6. And, if you remove `comments` and `safari10` in the `webpack.config.js`, then repeat the steps above, JavaScript in script elements is compressed.

## Environment 🖥

`node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"`:
Node.js v12.16.2
darwin 19.6.0

`npm --version`:
6.14.4

`npm ls webpack`:
webpack-demo@1.0.0 /Users/liuhuyue/webpack-demo
└── webpack@4.41.6 

`npm ls html-webpack-plugin`:
webpack-demo@1.0.0 /Users/liuhuyue/webpack-demo
└── html-webpack-plugin@3.2.0 

Thank you very much!

**Comment by jantimon** [comment]
Please upgrade html-webpack-plugin to version 4

**Comment by Lohoyo** [comment]
> Please upgrade html-webpack-plugin to version 4

Thanks!
I will try, but probably not that soon. After that, I will come back with the result.

**Comment by Lohoyo** [comment]
I have upgraded html-webpack-plugin to version 4, but it doesn't work, either.
You can reproduce it with the repository: https://github.com/Lohoyo/webpack-demo
I have updated its html-webpack-plugin to version 4.
