### ISSUE TITLE
Template is emitted even if unchanged and `cache: true`.

### ISSUE THREAD

**Issue by jgerigmeyer** [jantimon/html-webpack-plugin#1641]
## Current behaviour 💣

The docs state that with `cache: true`, the plugin will "emit the file only if it was changed". However, even if the template is cached and entirely unchanged, it is emitted (even if not recompiled) on every Webpack build.

```
assets by status 16.9 MiB [cached] 30 assets
asset templates/index.html 2.31 KiB [emitted]
```

## Expected behaviour ☀️

I would expect that if `cache: true` is set and a rebuild is triggered with no changes to the template, it would not be re-emitted:

```
assets by status 16.9 MiB [cached] 30 assets
```

My use-case is that the generated template is being served by a Django server, which auto-reloads every time it is built (even if unchanged).

### Reproduction Example 👾

https://github.com/jantimon/html-webpack-plugin/compare/main...jgerigmeyer:no-emit-cached-asset

It appears that even when a file is cached and unchanged, [it is still re-emitted](https://github.com/jantimon/html-webpack-plugin/blob/main/index.js#L255-L263). The tests for caching only seem to assert that it is not recompiled. Is this intentional? Apologies if I'm misunderstanding a reason why cached files need to be re-emitted when unchanged. (If so, perhaps I could submit a PR to update the docs to make this more clear?)

**Comment by jantimon** [comment]
The main idea of the cache is to save time by avoiding unnecessary recompilations

Unfortunately there are some edge cases which requires to recompile on every webpack run

So the `cache` option was added to allow opting out

Back then html files were only emitted if the content changes - however with a recent version of webpack it was necessary to emit the file every time to keep compatibility with clean-webpack-plugin and the copy plugin

**Comment by jgerigmeyer** [comment]
> The main idea of the cache is to save time by avoiding unnecessary recompilations
> 
> Unfortunately there are some edge cases which requires to recompile on every webpack run
> 
> So the `cache` option was added to allow opting out
> 
> Back then html files were only emitted if the content changes - however with a recent version of webpack it was necessary to emit the file every time to keep compatibility with clean-webpack-plugin and the copy plugin

@jantimon Thanks, that's very helpful context. Would you be open to allowing an opt-in third choice here, which would neither recompile nor re-emit? I'd imagine something like `cache: "always"` or something. 🤷

**Comment by jantimon** [comment]
What would be the benefit?

**Comment by jgerigmeyer** [comment]
> What would be the benefit?

@jantimon I guess the benefit would be allowing users to use the cache as it's described in the docs ("emit the file only if it was changed"), especially for users who don't need backwards compatibility with clean-webpack-plugin and the copy plugin.

I don't feel strongly that this is a necessary feature, but I'd use it. Like I said initially, my use-case is not wanting to cause other watchers (e.g. Django dev server) to fire on every webpack build when the html file is just being needlessly re-emitted unchanged.

If you don't want to add this, would you consider a PR updating the docs to reflect the actual current functionality?
