### ISSUE TITLE
Upgrade to resolve lodash security vulnerability

### ISSUE THREAD

**Issue by awentzel** [jantimon/html-webpack-plugin#1645]
Please update lodash to use latest and/or at least minor increment to `.21` to resolve security vulnerability https://github.com/microsoft/fast/security/dependabot/yarn.lock/lodash/open for details.

**Comment by tschmidtb51** [comment]
The link isn't working anymore. Please see the [Changelog](https://github.com/lodash/lodash/wiki/Changelog#v41721) instead.

**Comment by jantimon** [comment]
Released as 5.3.2
