### ISSUE TITLE
Support `__dirname` in JavaScript bundle

### ISSUE THREAD

**Issue by timfish** [jantimon/html-webpack-plugin#1649]
It appears that there were some changes to [improve support for SSR](https://github.com/jantimon/html-webpack-plugin/commit/73d2a660b10b9ebf8a341f0ddb173bcaaf1e513c#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R138) but this didn't include the addition of `__dirname`. 

I've hit this myself in a slightly different context when messing around with Webpack + Electron which can have full nodejs in the browser. If your JavaScript bundle contains __dirname`, you get an error in `evaluateCompilationResult` saying that `__dirname is not defined`. I'm currently working around this with `dirname(__filename)`.

**Comment by timfish** [comment]
Ah, and nearly forgot to say... happy to do a PR but not entirely sure what to set `__dirname` as!

**Comment by jantimon** [comment]
adding support for __dirname sounds nice - you might also use `__non_webpack_require__` inside your template to load pure js files with full support for __filename and __dirname
