### ISSUE TITLE
Injected script path was encoded in window os

### ISSUE THREAD

**Issue by silent-tan** [jantimon/html-webpack-plugin#1659]
## Current behaviour 💣

the script or css link path was encoded in windows 
![image](https://user-images.githubusercontent.com/9881593/122925588-8f25ac80-d399-11eb-84b4-80de9884be42.png)

filename define:

![image](https://user-images.githubusercontent.com/9881593/122926582-97cab280-d39a-11eb-8f64-4d7984077500.png)

![image](https://user-images.githubusercontent.com/9881593/122926673-b2049080-d39a-11eb-882a-472327718951.png)

## Environment 🖥

Node.js v14.16.0
npm 6.14.11
html-webpack-plugin 4.5.1

**Comment by silent-tan** [comment]
#1445

**Comment by jantimon** [comment]
Isn't that caused because of `path.join`?

**Comment by silent-tan** [comment]
but the build result is correct which in mac os or centos

**Comment by nraskoti** [comment]
Facing the same issue works in mac but not on windows.

**Comment by jantimon** [comment]
A asset path is always a url and must not use `\`.
You can use `path.posix.join` instead of `path.join` to get a web compatible path.
