### ISSUE TITLE
v5+ manipulate assets which conflict with computed SRI hash

### ISSUE THREAD

**Issue by themgoncalves** [jantimon/html-webpack-plugin#1668]
## Current behaviour 💣

After upgrading the `html-webpack-plugin` to `v5+`, somehow the assets are being manipulated in a way that it does not match the previously computed `integrity` hash anymore, outputing the following error on Browser's console:

> Failed to find a valid digest in the 'integrity' attribute for resource '<name>.bundle.js' with computed SHA-256 integrity 'pYpTWHH....'. The resource has been blocked.

The `Sub Resource Integrity` is done by `webpack-subresource-integrity`.

## Expected behaviour ☀️

Keep assets as it was received.

### Reproduction Example 👾

```js
const path = require('path');
const SriPlugin = require('webpack-subresource-integrity');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  target: 'web',
  entry: {
    app: ['./src/application.tsx'],
  },
  output: {
    publicPath: '/',
    path: path.join(__dirname, './public'),
    filename: 'js/[name].bundle.js',
    chunkFilename: 'js/[name].chunk.js',
    crossOriginLoading: 'anonymous',
  },
  plugins: [
    new SriPlugin({
      hashFuncNames: ['sha256', 'sha384', 'sha512'],
      enabled: true,
    }),
    new HtmlWebpackPlugin({
      template: './src/index.html',
      inject: true,
      minify: {
        collapseWhitespace: true,
        preserveLineBreaks: false,
      },
    }),
  ],
};

```

## Environment 🖥

```
Node.js v14.17.3
darwin 20.5.0

NPM v6.14.13

Webpack v5.47.0
html-webpack-plugin v5
```

**Comment by jantimon** [comment]
Can you please open an issue for the SRI plugin?

**Comment by themgoncalves** [comment]
@jantimon I'm not sure how is this a SRI plugin issue, this behaviour only occurs exclusively after `html-webpack-plugin` is updated; the rest remains the same, untouched.

**Comment by jantimon** [comment]
webpack 5 deprecated hooks - therefore html-webpack-plugin 5 is using the new recommended hooks..

integrating them with SRI is quite difficult and maybe there is a bug but probably it can't be fixed by the html-webpack-plugin.

please see https://github.com/webpack/webpack/issues/11822

**Comment by themgoncalves** [comment]
@jantimon thanks for the explanation! Will rise this issue there as well.

**Comment by themgoncalves** [comment]
Closing this issue as @jantimon pointed out, the issue was really caused by `webpack-subresource-integrity` using old Webpack hooks. More info can be found on issue raised there.
