### ISSUE TITLE
How to merge chunks ?

### ISSUE THREAD

**Issue by gunsela92** [jantimon/html-webpack-plugin#1669]
## Description

Im trying to build my react-app. After build i have 30+ js files. I want only one js file. Where is my mistake ?

### Error Message & Stack Trace

![folderView](https://user-images.githubusercontent.com/35037442/127866619-22b1fe67-2c91-46f3-9263-e88cf6f69617.png)

### Config

Copy the relevant section from `webpack.config.js`:

```js
module.exports = require('./webpack.common')({
  mode: 'production',

  // In production, we skip all hot-reloading stuff
  entry: [path.join(process.cwd(), 'src/app.js')],

  plugins: [
    new HtmlWebpackPlugin({
      template: 'src/index.html',
      chunks : ['all'],
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
      inject: true,
    }),
    new ResourceManifestPlugin(),
  ],

  performance: {
    assetFilter: assetFilename =>
      !/(\.map$)|(^(main\.|favicon\.))/.test(assetFilename),
  },
});
```

My build report:

![Build report](https://user-images.githubusercontent.com/35037442/127866534-22836a79-dfda-46e9-a402-ac2c32cf9405.png)

**Comment by jantimon** [comment]
this is not related to the html-webpack-plugin but probably you could something like this:

```
 entry: { main: [path.join(process.cwd(), 'src/app.js')] },
```
