### ISSUE TITLE
Module Federation: injecting scripts for remotes with HtmlWebpackPlugin

### ISSUE THREAD

**Issue by serrg** [jantimon/html-webpack-plugin#1671]
## Current behaviour 💣

During runtime when request to remote application **is pending**, injected script is blocking the page.

## Expected behaviour ☀️

1. When `inject: body` is set with `HtmlWebpackPlugin` put loading script at the end of the body tag.
2. Do not block page/application when remote entry is not responding.

### Reproduction Example 👾

In the scenario we have host and remote applications:

- host application `shell` (`localhost:3000`)
- remote `app` (`localhost:3002`) which is not responding, we simulate `request pending` by setting the timeout

`shell` webpack configuration:
```
new ModuleFederationPlugin({
  name: "shell",
  filename: "remoteEntry.js",
  remotes: {
    app: 'app@http://localhost:3002/remoteEntry.js',
  }
})
new HtmlWebpackPlugin({
    template: "./public/index.html",
    inject: "body",
})
```

Source code of `app`:
```
const express = require("express");
const app = express();
const port = 3002;
app.use((req, res, next) => setTimeout(next, 30000));
app.get("*", (req, res) => { res.send("Hello World!"); });
app.listen(port, () => { console.log(`Example app listening at http://localhost:${port}`); });
```

<img width="759" alt="Screenshot 2021-08-04 at 13 52 19" src="https://user-images.githubusercontent.com/1391453/128188972-f94ffcd6-6311-4157-b1d3-5caf56d5aa76.png">

As you can see script connecting for the remote entry is located in `head` tag. 

We can use [promise based loaders for remotes](https://webpack.js.org/concepts/module-federation/#promise-based-dynamic-remotes), pass a promise to this remote and inject into `body` tag:
```
market: `promise new Promise(resolve => {
  const remoteUrl = 'http://localhost:3002/remoteEntry.js'
  const script = document.createElement('script')
  script.async = true;
  script.defer = true;
  script.src = remoteUrl
  document.body.appendChild(script);
})
`
```

and at runtime script is located at the end body but the page is still blocked by loading remote entry.

<img width="566" alt="Screenshot 2021-08-04 at 14 13 31" src="https://user-images.githubusercontent.com/1391453/128189000-8d6340fe-b0e2-4b4f-acef-0c1146ad30b3.png">

Alternatively we can dynamically load remotes during runtime using [this](https://github.com/webpack/webpack/issues/11033#issuecomment-644349386) 

## Environment 🖥

Node.js v14.17.1
darwin 20.6.0
npm 6.14.13
webpack 5.38.1 
html-webpack-plugin 5.3.1

**Comment by jantimon** [comment]
What is the content of public/index.html ?

**Comment by jantimon** [comment]
Okay that's strange I have no idea who is injecting the blocking script..
