### ISSUE TITLE
The generated file is opened in the browser, <%= htmlWebpackPlugin.options.title %> cannot be correctly parsed into the title tag

### ISSUE THREAD

**Issue by seechangan** [jantimon/html-webpack-plugin#1673]
## Current behaviour 💣
![image](https://user-images.githubusercontent.com/31404297/128626942-05b5a1bb-5778-4bda-81f1-1569202fb163.png)

因为我的html有使用到 <img  src="./xxx/xx.jpg"> 所以我必须使用html-loader来确保我页面图片正常显示;可能是html-loader解析之后以字符串的形式输入,导致未识别到ejs语法。

## Expected behaviour ☀️
![image](https://user-images.githubusercontent.com/31404297/128626994-3cdbb521-3527-49ea-a110-9d27a47b002d.png)

### Reproduction Example 👾

const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  module:{
          rules:{
              test: /\.html$/i,
              loader: "html-loader",
            }
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Custom template',
      template: './src/index.html'
    })
  ]
};

## Environment 🖥
npm --version 6.14.13
npm ls webpack ^4.46.0
npm ls html-webpack-plugin ^3.2.0
npm Is html-loader ^1.3.2

**Comment by rowild** [comment]
having the same probem. Also a required partial is not rendered, but instead this is generated:

```html
<%= require('./partials/header.html') %>
```
