### ISSUE TITLE
Images hash name diffrent with images in production html when use ImageMinimizerPlugin

### ISSUE THREAD

**Issue by taosapp** [jantimon/html-webpack-plugin#1677]
## Current behaviour 💣

Asset Modules and ImageMinimizerWebpackPlugin, 

`assetModuleFilename: 'img/[name].[hash:8][ext][query]'` 

`npm run build`

the images name diffrent with HTML image name, such as _logo.7c70fb17.png_ in _img_ folder but  _img/logo.6d5cc11e.png_ in HTML

## Expected behaviour ☀️

images name same as images src value in HTML after build

### Reproduction Example 👾

[codesandbox](https://codesandbox.io/s/html-webpack-plugin-5-x-alpha-forked-i74vl?file=/webpack.config.js)

## Environment 🖥
Node.js v16.7.0
win32 10.0.19043
npm 7.21.0
webpack 5.51.1
webpack-cli 4.8.0
webpack-dev-server 4.0.0
html-webpack-plugin 5.3.2

**Comment by dpi-pixelo** [comment]
Using ImageMinimizerPlugin as a standalone loader fixes the issue for me. see https://webpack.js.org/plugins/image-minimizer-webpack-plugin/#standalone-loader
