### ISSUE TITLE
Statement "no loader defined => falls back to ejs/lodash" is simply not true

### ISSUE THREAD

**Issue by rowild** [jantimon/html-webpack-plugin#1680]
The documentation, under "Writing your own templates"
https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates

claims that lodash is used "out of the box", if no loader is defined. But that is simply not true. This sandbox proves it:
https://codesandbox.io/s/divine-bird-rqtqz

This template provides a working pug configuration alongside the failing html template configuration.

If I am wrong, would you please be so kind as to point out what the culprit is?
And if I am right, is there any chance to fix this problem?

Thank you!

**Comment by jantimon** [comment]
Sorry I have a hard time to understand what you mean..

html-webpack-plugin willl add a small lodash based template loader - this loader checks if another loader is registered for the very same file and bail out if needed:

https://github.com/jantimon/html-webpack-plugin/blob/2f5de7ab9e8bca60e9e200f2e4b4cfab90db28d4/lib/loader.js#L13-L16
