### ISSUE TITLE
Are you using the html-loader to gether with a template.**html** file?

### ISSUE THREAD

**Issue by rowild** [jantimon/html-webpack-plugin#1681]
Are you using the html-loader to gether with a template.**html** file?
Because then the html-loader would kick in instead of the lodash loader.

There are several examples in the examples folder:

https://github.com/ampedandwired/html-webpack-plugin/tree/master/examples/custom-template

_Originally posted by @jantimon in https://github.com/jantimon/html-webpack-plugin/issues/193#issuecomment-175426159_

This should really go into the documentation! "Do not configure html-loader, but attach it right in front of the partial". This took me almost 5 days (!!!) to find out. Please improve your documentation! Thank you!

**Comment by jantimon** [comment]
Do you mean the docs folder?
https://github.com/jantimon/html-webpack-plugin/blob/main/docs/template-option.md
