### ISSUE TITLE
html-webpack-plugin.template not render webpack template variable

### ISSUE THREAD

**Issue by loynoir** [jantimon/html-webpack-plugin#1684]
## BUG
`HtmlWebpackPlugin.filename` render webpack template string `[name].html` correctly.

But `HtmlWebpackPlugin.template` render webpack template string `[name].html` with Error.

Plus, ~60 lines of error is written into output.

## Config

<details>
  <summary>webpack.config.js</summary>
  <p>
 
```js
// webpack.config.js
var path = require('path');
var HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  mode: "development",
  entry: {
    firstEntry: "./first.js",
    secondEntry: "./second.js",
  },
  output: {
    path: path.join(
      __dirname,
      "dist",
      process.env.SKIP_TEMPLATE_TEMPLATE
        ? "skip-template-template"
        :  "template-template"
    ),
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: process.env.SKIP_TEMPLATE_TEMPLATE
        ? "first.html"
        : "[name].html",
      filename: "[name].html",
    }),
  ],
};
```

  </p>
</details>

## Current behaviour 💣

`HtmlWebpackPlugin.template` render webpack template string `[name].html` with Error.

```sh
$ pnpm run test
```

```txt
ERROR in   Error: Child compilation failed: 
  Module not found: Error: Can't resolve 'path/to/reproduce-example/[name].html' in 'path/to/reproduce-example'             
  ModuleNotFoundError: Module not found: Error: Can't resolve 'path/to/reproduce-example/[name].html' in 'path/to/reproduce-example'
```

Plus, ~60 lines of error is written into output.

```html
<head><script defer src="firstEntry.js"></script><script defer src="secondEntry.js"></script></head>Html Webpack Plugin:
<pre>
  Error: Child compilation failed:
  ....
</pre>
```

## Expected behaviour ☀️

```sh
$ pnpm run test
```

```txt
🎉 Test OK
```

If detect error, don't write to file.

### Reproduction Example 👾

https://github.com/loynoir/reproduce-html-webpack-plugin

## Environment 🖥

```txt
node 14.17.4
npm 7.21.0
pnpm 6.14.3
webpack 5.52.1
html-webpack-plugin 5.3.2
```

**Comment by loynoir** [comment]
@jantimon Sorry, I open a new issue. Because I can't comment or edit in the previous.

**Comment by loynoir** [comment]
Seems `HtmlWebpackPlugin.chunks` also not render `[name]`.

Below also not work
```js
    new HtmlWebpackPlugin({
      chunks: ['[name]'],
      filename: '[name].html',
      template: './src/[name].html'
    })
```

@jantimon Is `HtmlWebpackPlugin.filename` the only option can render `[name]`?

**Comment by jantimon** [comment]
Yes that's correct :)

**Comment by loynoir** [comment]
@jantimon

Why? Are there any reason/limitation? 
Which line is the rendering line in source code? 😂
