### ISSUE TITLE
Upgrade to Terser 5 + html-minifier-terser 6

### ISSUE THREAD

**Issue by slorber** [jantimon/html-webpack-plugin#1687]
**Is your feature request related to a problem? Please describe.**

Docusaurus users using mono repo had problems due to conflict between Terser 4 / Terser 5

html-minifier-terser v6 has been released recently with Terser 5 support (API is now async), so this lib could also try to upgrade, ensuring we are now all using Terser 5, having less problems in monorepos, reduce install size/time

**Describe the solution you'd like**

Upgrade libs, keep same behavior.

Make `minifyHtml` async (The caller sites are already async)

https://github.com/jantimon/html-webpack-plugin/blob/0a6568d587a82d88fd3a0617234ca98d26a1e0a6/index.js#L1044

**Describe alternatives you've considered**

NA

**Additional context**

- https://github.com/terser/html-minifier-terser/issues/49
- https://github.com/facebook/docusaurus/issues/3515
- https://github.com/facebook/docusaurus/pull/5609

**Comment by jantimon** [comment]
hey 👋 

thanks for reaching out - if it's only about sync vs async we should just add this.. do you have time to create a pr?


are there any other breaking changes? e.g. dropping nodejs support or anything which might cause issues for html-webpack-plugin users?

**Comment by gabrielcsapo** [comment]
I can pick this up throwing a PR up now.
