### ISSUE TITLE
Which good way for building html layouts with partial contents?

### ISSUE THREAD

**Issue by taitrd** [jantimon/html-webpack-plugin#1690]
I would like to use this plugin for building html templates and i found this way that is not in [**examples**](https://github.com/jantimon/html-webpack-plugin/tree/main/examples) or this may be necessary for  [**custom-template**](https://github.com/jantimon/html-webpack-plugin/tree/main/examples/custom-template) example.

This solution use html-loader and file stream to build layouts, partial html without rewrite other tags in each page and it should be simplest way if there is a case with many layouts, pages. The code is here:
```
// layout.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= title %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
  <ul>
      <li><a href="index.html">Home</a></li>
      <li><a href="about.html">About</a></li>
  </ul>
  <header><%= require('html-loader!./header.html').default %></header>
  <main><% if(pageContent) { %><%= pageContent %><% } %></main>
</body>
</html>

// header.html
<p>Header</p>

// pages/home.html
<p>Home page</p>

// pages/about.html
<p>About page</p>

// webpack.config.js
const fs = require('fs');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const htmlPlugins = [
  { template: 'layout.html', filename: 'index.html', content: 'pages/home.html', title: 'Home' },
  { template: 'layout.html', filename: 'about.html', content: 'pages/about.html', title: 'About' },
].map(v => {
  v.inject = 'body';
  v.templateParameters = () => {
    return { pageContent: fs.readFileSync(v.content, 'utf8'), title: v.title };
  };
  return new HtmlWebpackPlugin(v);
});

module.exports = () => {
  return {
        // we could include script entries for chunks of each html
  	entry: {},
  	output: { path: '/dist' },
  	plugins: htmlPlugins,
  };
};
```

The disadvantage is webpack cannot reach watch mode in content html files so we need to add them to entries with html-loader or compilation dependencies of plugin (i guess). 

```
// pages/about.js (entry)
import './about.html';

// webpack.config.js
module.exports = () => {
  return {
    entry: {
      about: 'pages/about.js',
    },
    output: { path: '/dist' },
    plugins: htmlPlugins,
    {
      test: /\.html$/i,
      loader: "html-loader",
      include: [path.resolve(__dirname, "pages")], // load html in pages directory only
    },
  };
};
```

I have tried other solutions: [injection body plugin](https://github.com/Jaid/inject-body-webpack-plugin), dynamic partial html or [dynamic html loader](https://github.com/webpack-contrib/html-loader/issues/291). but it was not working or too complex. i hope this solution is useful for the idea or is there any better one?

Some relative and unresolved issues i researched before:
* [1330](https://github.com/jantimon/html-webpack-plugin/issues/1330)

**Comment by jantimon** [comment]
html-webpack-plugin supports any webpack loader compatible template language..  
so the challenge is to pick a webpack loader which is capable of handling layouts

one solution might be **handlebars** using the following packages:

- handlebars
- handlebars-loader
- webpack 5.x
- html-webpack-plugin 5.x

You can see it live or download it here:  
https://codesandbox.io/s/html-webpack-plugin-hbs-kuhgc?file=/webpack.config.js

```js
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  module: {
    rules: [
      {
        test: /\.hbs$/,
        loader: "handlebars-loader",
        options: {
          inlineRequires: "/images/"
        }
      },
      {
        test: /\.(png|svg|jpg|jpeg|gif)$/i,
        type: "asset/resource"
      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: "Home",
      template: "src/pages/home.hbs",
      filename: "index.html"
    })
  ]
};
```

home.hbs
```hbs
{{#[helpers/layout] htmlWebpackPlugin}}

<p>
  Go to <a href="/about.html">About</a>
</p>

{{/[helpers/layout]}} 
```

footer.hbs
```html
<footer>
  The Footer
  <img src="../images/footer.png">
</footer>
```

**Comment by SamiKalliomaki** [comment]
My initial thought was this:
```html
  <main><%= require(page).default %></main>
```

And then:
```js
new HtmlWebpackPlugin({
  template: 'layout.html',
  filename: 'about.html',
  templateParameters: { page: './about.html' }
});
```

However, this does not work since `require` cannot have a dynamic argument.

There are a couple ways I can think of that this could be made to work with just `html-webpack-plugin`:

1. Add an option `templateFileParameters` that instead compiles a file and provides the output as a template parameter. Then this would work:
```html
  <main><%= pageContent %></main>
```
```js
new HtmlWebpackPlugin({
  template: 'layout.html',
  filename: 'about.html',
  templateFileParameters: { pageContent: 'about.html' }
});
```
2. Support compiling the template twice. Then this could work (assuming `<?= ?>` is the first pass):
```html
  <main><%= require('<?= page ?>').default %></main>
```

And on the second pass this would become (which should compile fine):
```html
  <main><%= require('./about.html').default %></main>
```

With quick prototyping solution 1 seems to be at least possible to implement.

**Comment by taitrd** [comment]
> My initial thought was this:
> 
> ```
>   <main><%= require(page).default %></main>
> ```
> 
> And then:
> 
> ```js
> new HtmlWebpackPlugin({
>   template: 'layout.html',
>   filename: 'about.html',
>   templateParameters: { page: './about.html' }
> });
> ```
> 
> However, this does not work since `require` cannot have a dynamic argument.
> 
> There are a couple ways I can think of that this could be made to work with just `html-webpack-plugin`:
> 
> 1. Add an option `templateFileParameters` that instead compiles a file and provides the output as a template parameter. Then this would work:
> 
> ```
>   <main><%= pageContent %></main>
> ```
> 
> ```js
> new HtmlWebpackPlugin({
>   template: 'layout.html',
>   filename: 'about.html',
>   templateFileParameters: { pageContent: 'about.html' }
> });
> ```
> 
> 1. Support compiling the template twice. Then this could work (assuming `<?= ?>` is the first pass):
> 
> ```
>   <main><%= require('<?= page ?>').default %></main>
> ```
> 
> And on the second pass this would become (which should compile fine):
> 
> ```
>   <main><%= require('./about.html').default %></main>
> ```
> 
> With quick prototyping solution 1 seems to be at least possible to implement.
