### ISSUE TITLE
@types/html-minifier-terser 6 requires node >= 12

### ISSUE THREAD

**Issue by stefan-toubia** [jantimon/html-webpack-plugin#1698]
## Current behaviour 💣

It looks like `html-webpack-plugin` 5.4 bumped `@types/html-minifier-terser` version from 5.0 to 6.0. Version 6.0 requires node >= 12, but `html-webpack-plugin` still lists node 10.13 as the minimum required version. 5.4 was a breaking change for node 10 users.

**Comment by alexander-akait** [comment]
Sorry, there is no engines for `@types` - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/html-minifier-terser/package.json, feel free to feedback
