### ISSUE TITLE
Any JS entry plugin for injecting CSS?

### ISSUE THREAD

**Issue by liam61** [jantimon/html-webpack-plugin#1699]
**Is your feature request related to a problem? Please describe.**
Hi, we are using js entry for a micro frontend project, but may collect css source while the entry bundling

So we may lost some styles without `html-webpack-plugin`

**Describe the solution you'd like**
I wanna know if there any `JS entry plugin` to solve this css bundle problem, or `html-webpack-plugin` for the js entry usage

Thanks~

**Comment by alexander-akait** [comment]
Close in favor https://github.com/jantimon/html-webpack-plugin/pull/1732
