### ISSUE TITLE
Boolean attributes can be made shorter

### ISSUE THREAD

**Issue by koooge** [jantimon/html-webpack-plugin#1704]
Hi there, 

## Current behaviour 💣
http-webpack-plugin generates:

```
<script defer="defer">
<script defer="defer" nomodule="">
```

## Expected behaviour ☀️

defer is boolean attributes https://html.spec.whatwg.org/multipage/scripting.html#attr-script-defer . 

```
<script defer>
<script defer nomodule>
```

I am not sure if it's on purpose. They are equivalent but it would be shorter and simpler. 

## Environment 🖥

```
$ npm ls html-webpack-plugin

  └── html-webpack-plugin@5.5.0
```

**Comment by jantimon** [comment]
Doesn't the html-minifier minify that for production?

**Comment by koooge** [comment]
It does not. I opened #1705 .

**Comment by jantimon** [comment]
I guess changing this default setting might break some production apps..

We tried to pick only the safe values:
https://github.com/jantimon/html-webpack-plugin/pull/1048

but you can easily adjust the minification settings according to your requirements in the options

**Comment by alexander-akait** [comment]
Yes, we can't enable it by default because of this http://perfectionkills.com/experimenting-with-html-minifier/#collapse_boolean_attributes, it can be unsafe, so please enable it on own side if it is safe for you, anyway thank you for the issue
