### ISSUE TITLE
I'm wondering why we don't use topological sort in chunksorter?

### ISSUE THREAD

**Issue by wfnuser** [jantimon/html-webpack-plugin#1708]
Hi, there. I'm trying to build some package management system. And I thought maybe I can take a look at `html-webpack-plugin`. Since chunks has dependencies on each other, there must be someplace that implements topological sort .
But I'm surprised that there are not? So does the `toposort` function is implement in some dependency of `html-webpack-plugin` or there are no need for topological sort.

It's just a question. It will help me a lot if anyone can answer it.

**Comment by jantimon** [comment]
earlier versions of the html-webpack-plugin shipped with `toposort` however webpack 5 managed to load files independently from the order so we removed it for faster builds

**Comment by wfnuser** [comment]
> earlier versions of the html-webpack-plugin shipped with `toposort` however webpack 5 managed to load files independently from the order so we removed it for faster builds

@jantimon Yep. I have noticed that. Thanks very much for replying. 😄
