### ISSUE TITLE
List strict-csp-html-webpack-plugin in the README?

### ISSUE THREAD

**Issue by maudnals** [jantimon/html-webpack-plugin#1717]
**Is your feature request related to a problem? Please describe.**
Setting a Content-Security-Policy (CSP) that efficiently protects users from XSS is hard.
The [strict-csp-html-webpack-plugin](https://www.npmjs.com/package/strict-csp-html-webpack-plugin), that relies on html-webpack-plugin, plugin helps developers do that. 

**Describe the solution you'd like**
As discussed with @jantimon, we may want to list this plugin in the helpful list of plugins in [html-webpack-plugin's README](https://github.com/jantimon/html-webpack-plugin#plugins).

**Additional context**
This plugin can be considered experimental. 
It will soon be added to [Squoosh](https://github.com/GoogleChromeLabs/squoosh/pull/1197), a widely-used web app, which will help us test it.
* Should we wait and see how the plugin behaves in Squoosh in production, before listing it here in the README?
* Or should we list it and mark it as _experimental_?

**Comment by maudnals** [comment]
(I'm happy to open the PR)

**Comment by jantimon** [comment]
just add it - people will let you know if something is broken :)

**Comment by maudnals** [comment]
Sounds good - "experimental" is also mentioned in the plugin docs. 
Added, see PR.
