### ISSUE TITLE
The `ejs-loader` does not provide a `include` function

### ISSUE THREAD

**Issue by tjcchen** [jantimon/html-webpack-plugin#1721]
The `ejs-loader` does not provide a `include` function

html-webpack-plugin uses <%- include('path/to/file.ejs') %>

Any suggestions on how to resolve this problem, thanks in advance!

_Originally posted by @jantimon in https://github.com/jantimon/html-webpack-plugin/issues/1216#issuecomment-512141092_

**Comment by isaacalves** [comment]
hey @tjcchen have you found any solution for this?

**Comment by alexander-akait** [comment]
Sorry, we can't fix it here, please open an issue in `ejs-loader`, we tried to move `ejs-loader` to webpack-org to fix such problems, but not luck, we really can't fix it here, sorry for long answer and feel free to feedback

**Comment by zzzMaple** [comment]
Any ejs-loader could with latest html-webpack-plugin now?

**Comment by zzzMaple** [comment]
I try a lot of loader but seems all of them not body maintain now
