### ISSUE TITLE
Dynamic entry with using devMiddleware.invalidate will not generate the new html

### ISSUE THREAD

**Issue by moyueating** [jantimon/html-webpack-plugin#1722]
Currently using **webpack5**, **html-webpack-plugin**, I want to achieve incremental compilation through dynamic entry, but when I trigger the update through devmiddleware.invalidate(), I only get the compiled js and css files but not the expected html files. The following is the general configuration and usage.
```js
let cacheEntries = [ 'pages/page1/main.js' ] 

module.exports = {
    entry = () => cacheEntries,
    optimization: {
         runtimeChunk: 'single'
    },
    devServer: {
         onBeforeSetupMiddleware: devServer => {
             const app = devServer.app;
             const compiler = devServer.compiler 
             const devMiddlewareInstance = devServer.middleware
             app.use((req, res, next) => {
                      cacheEntries['page2'] = [path.resolve(process.cwd(), `./src/pages/page2/main.js`)]
                      new HTMLWebpackPlugin({
                           filename: 'page2/index.html',
                           template: path.resolve(process.cwd(), './public/index.html')  
                      }).apply(compiler)
                      devMiddlewareInstance.invalidate()
            })
        }
    }
}
```
Then I looked at the source code of html-webpack-plugin and found that entryOptions is handled on the hook of compiler.initialize. Does this mean that dynamic entry is not supported? If it is really not supported, is there any good way for the implementation of dynamic entry incremental compilation?

![image](https://user-images.githubusercontent.com/17477200/151308402-a0078243-99bb-4108-b4c9-6c0a02472348.png)

Looking forward to your answer, thanks！

**Comment by alexander-akait** [comment]
I want to close this in favor of https://github.com/jantimon/html-webpack-plugin/issues/1768, because `html-webpack-plugin` uses hook to init options, it doesn't work dynamically right now (more context - https://github.com/webpack/webpack/issues/16312#issuecomment-1262993892), I want to fix it soon
