### ISSUE TITLE
How to mange jsp file

### ISSUE THREAD

**Issue by teger** [jantimon/html-webpack-plugin#1724]
Hi,

How to manage jsp file with this plugin or another plugin please ?

the HtmlWebplugin crashs with  tag <%= %>  in jsp file,

Thanks for your help,

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
