### ISSUE TITLE
 Module build failed (from ../../#Front-end/my-app/node_modules/html-webpack-plugin/lib/loader.js)

### ISSUE THREAD

**Issue by rassadin11** [jantimon/html-webpack-plugin#1728]
Hello!
I create default react application with **npx create-react-app project --template typescript** but when I write **npm start** I see this error:
![image](https://user-images.githubusercontent.com/58170052/153595616-aa313683-9b5b-4754-9b1f-063bfa19a8a3.png)

I tried:
    1. Install other node versions (16.14.*, 17.4.0, 17.5.0 - active)
    2. Create app in other directories

Help me, please

**Comment by alexander-akait** [comment]
Please try to use the latest version of `CRA`, all works fine for me, thank you and sorry for a long answer
