### ISSUE TITLE
Inject bundled JS and CSS to the existing file

### ISSUE THREAD

**Issue by jeevasusej** [jantimon/html-webpack-plugin#1754]
## Current behaviour 💣

I can copy the template and generate index.html.

## Expected behaviour ☀️

I am using Asp.net MVC file. I want to inject bundled JS and CSS to external existing file which is _layout.cshtml.

Is there any configuration to modify this?

**Comment by Xiaoooyooo** [comment]
I think you can try `templateContent` option, [here is a example](https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates)

**Comment by Somnium7** [comment]
You can use [html-inline-script-webpack-plugin](https://github.com/icelam/html-inline-script-webpack-plugin).

**Comment by Somnium7** [comment]
> I think you can try `templateContent` option, [here is a example](https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates)

I have tried this, but hot reloading did not work for me, as it is not working when I change template. Or maybe I was doing something wrong?

**Comment by webdiscus** [comment]
You can try to use new modern [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin#recipe-inline-css).
This plugin support inline JS and CSS  in HTML "out of the box", without additional plugins and loaders.

For example, there is  _style.scss_:
```scss
$color: red;
h1 {
  color: $color;
}
```
and _script.js_:
```js
console.log('Hello inline JS!');
```

Specify source style and script files directly in HTML and add the `?inline` query to the filename:
```html
<html>
<head>
  <!-- inline style -->
  <link href="./style.scss?inline" rel="stylesheet" />
  <!-- inline script -->
  <script src="./script.js?inline"></script>
</head>
<body>
  <h1>Hello World!</h1>
</body>
</html>
```

The generated HTML contains inline JS and CSS already processed via Webpack:

```html
<html>
<head>
  <!-- inline style -->
  <style>
    h1{color: red;}
  </style>
  <!-- inline script -->
  <script>
    (()=>{"use strict";console.log("Hello JS!")})();
  </script>
</head>
<body>
  <h1>Hello World!</h1>
</body>
</html>
```

Webpack config:
```js
const HtmlBundlerPlugin = require('html-bundler-webpack-plugin');

module.exports = {
  plugins: [
    new HtmlBundlerPlugin({
      entry: {
        // define templates here, the syntax is the same Webpack entry
        index: 'src/views/home/index.html', // output dist/index.html
        'pages/about': 'src/views/about/index.html', // output dist/pages/about.html
      },
    }),
  ],
   module: {
    rules: [
      // style loader
      {
        test: /\.(css|sass|scss)$/,
        use: ['css-loader', 'sass-loader'],
      },
    ],
  },
};
```

The details see here [How to inline CSS and JS  in HTML](https://github.com/webdiscus/html-bundler-webpack-plugin#recipe-inline-css).

P.S. the html-bundler-webpack-plugin support HTML templates with EJS-like "out of the box", without additional template loaders.

**Comment by alexander-akait** [comment]
There is an example https://github.com/jantimon/html-webpack-plugin/issues/1754#issuecomment-1186809285, feel free to feedback if you need a help
