### ISSUE TITLE
Recursively build when I inject a customed plugin

### ISSUE THREAD

**Issue by kaiwenxiao** [jantimon/html-webpack-plugin#1755]
I build an app which using Vuecli 4 and using Webpack 5.x

I have a plugin build my own, which maybe help me for change what html file I would get and alternatively edit it. Look like this
![image](https://user-images.githubusercontent.com/31737119/181485685-3f48a077-fdd4-43f2-b0b2-f31cc4d5d876.png)
![image](https://user-images.githubusercontent.com/31737119/181486306-534309b9-6084-4084-9fb3-e2256220d570.png)

and the result looks like this, recursively:
![image](https://user-images.githubusercontent.com/31737119/181486032-fca4caa0-ae33-4275-b0a4-238a49333a91.png)

how to stop the loop, and correctly trigge my plugin? A Lots of Thanks!

**Comment by jantimon** [comment]
hey :) 

the `.plugin` api is outdated - you will have to use the `.tap` api

**Comment by kaiwenxiao** [comment]
Okay, when using ```compilation.tap()```, it will occur ``` TypeError: compilation.tap is not a function```

**Comment by jantimon** [comment]
In that case you are somehow using webpack 4

**Comment by alexander-akait** [comment]
Answered
