### ISSUE TITLE
how to distinguish htmlwebpackplugin instances in beforeEmit hook

### ISSUE THREAD

**Issue by Gong-Elory** [jantimon/html-webpack-plugin#1762]
**Is your feature request related to a problem? Please describe.**
there are many custom plugin instances which rely on beforeEmit hook，i don know which htmlwebpackplugin instance triggered the hook.
eg.
```
new HTMLWebpaclPluginA({
// config is invisible for me
}),
new HTMLWebpaclPluginB({
// config is invisible for me
}),
new MyCustonPluginA({}),
new MyCustonPluginB({}),
```

in MyCustonPluginA，i dont know which HTMLWebpaclPlugin (A or B ) triggered the beforeEmit hook

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alexander-akait** [comment]
Sorry, we migrated away from the `beforeEmit` hook, because it was deprecated and should not be used for assets emitting, feel free to feedback
