### ISSUE TITLE
CSS resolving order

### ISSUE THREAD

**Issue by Devinora** [jantimon/html-webpack-plugin#1765]
Faced with the problem of connecting CSS files. I do not know how to sort the correct order. JS is ok. I tried to use chunksSortMode, but it is not suitable for CSS, and the function itself provides few options. Is there a way to control the file connection process?

```js
import '../../scss/pages/index';
import '../../scss/base/_footer';
```

```html
<head>
   <meta charset="utf-8">
   <title>Webpack: Home</title>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,shrink-to-fit=no">
   <link rel="shortcut icon" type="image/png" href="img/favicon~6a4b5400..png">
   <link href="css/styles~cart~index~_footer~7620310d.css" rel="stylesheet">
   <link href="css/styles~index~8752d8ff.css" rel="stylesheet">
</head>
```

**Comment by webdiscus** [comment]
@Devinora 

you can try to use the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin) (modern alternative) to have full control for CSS and JS in the generating HTML.

Using this plugin you can define source styles and scripts directly in HTML template. So you can specify the order of CSS in HTML by yourself.

```html
<html>
<head>
  <!-- load source styles here -->
  <link href="./style.scss" rel="stylesheet">
  <link href="./footer.scss" rel="stylesheet">
  <!-- load source scripts here -->
  <script src="./main.js" defer="defer"></script>
</head>
<body>
  <h1>Hello World!</h1>
</body>
</html>
```

The generated HTML contains same order of scripts and styles:
```html
<html>
<head>
  <link href="css/style.05e4dd86.css" rel="stylesheet">
  <link href="css/footer.dd8605e4.css" rel="stylesheet">
  <script src="js/main.f4b855d8.js" defer="defer"></script>
</head>
<body>
  <h1>Hello World!</h1>
</body>
</html>
```

**Comment by Devinora** [comment]
@webdiscus
I have tried your product. it is still damp and does not work very well.

looks very ambitious. if finalized, it will be a great tool.

**Comment by webdiscus** [comment]
> @webdiscus I have tried your product. it is still damp and does not work very well.
> 
> looks very ambitious. if finalized, it will be a great tool.

Can you please create a small repo with reproducible issue [here](https://github.com/webdiscus/html-bundler-webpack-plugin/issues), I try to fix it.

**Comment by Devinora** [comment]
@webdiscus
Good afternoon. I don't have time to help you right now. I also don't speak English. you can write me an email or telegram, and I can share the problem.
tg: @estevus
mail: kh.devinora@gmail.com

**Comment by wswmsword** [comment]
`optimization.splitChunks.cacheGroups.[group].priority` can be used to solve the order problem:
```
module.exports = {
  optimization: {
    splitChunks: {
      cacheGroups: {
        index: {
          chunks: "all",
          enforce: true,
          test: /index.css$/i,
          name: "index",
          priority: 102,         
        },
        footer : {
          chunks: "all",
          enforce: true,
          test: /_footer.css$/i,
          name: "footer",
          priority: 101,  
        }
      }
    }
  }
}
```

**Comment by alexander-akait** [comment]
Let's close, answer above, feel free to feedback
