### ISSUE TITLE
Hash: false Still hashing JavaScript file names. 

### ISSUE THREAD

**Issue by Johnathan-Aretos** [jantimon/html-webpack-plugin#1766]
## Current behaviour 💣

Currently, I have my Config for my HTMLwebpackplugin 

`hash: false`

In my index.html. It is still hashing my JavaScript files. For example, the templateHTML index.html looks like 

`<script src=config.js >`

but when htmlwebpackplugin processes it, it becomes. 

`<script src=/2aec43dvxxxxxxx.js >`

## Expected behaviour ☀️
When

hash: false 

the index.html should be 

`<script src=config.js >`

### Reproduction Example 👾

To reproduce, in the plugins section of webpack 

add: 

```
new HTMLWebPackPlugin({ 
  hash: false
)}
```

## Environment 🖥

Using WebPack 5

html-webpack-plugin = 5.5.0

-->

**Comment by alexander-akait** [comment]
This options for hash busting in dev enviroment, i.e. use `./main.js?hash=compilation_hash`, not for files, added example https://github.com/jantimon/html-webpack-plugin/pull/1808
