### ISSUE TITLE
feat: Add configuration to decide whether to use the urlencodePath method

### ISSUE THREAD

**Issue by jingegebuguai** [jantimon/html-webpack-plugin#1767]
My entry sometimes has special characters, which is an irresistible factor that causes characters to be escaped when writing html, which is not what I want.

```
const entryPointPublicPaths = entryPointFiles.map((chunkFile) => {
        const entryPointPublicPath = publicPath + urlencodePath(chunkFile);
        return options.hash
          ? appendHash(entryPointPublicPath, compilationHash)
          : entryPointPublicPath;
      });
```

webpack 4 && webpack 5

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
