### ISSUE TITLE
Question: how to control generating css link in html after build

### ISSUE THREAD

**Issue by fantasticsoul** [jantimon/html-webpack-plugin#1769]
It seems that output of the latest `cra` has no css link file any more, for development mode I really like this feature but for some special reason I still hope it will be injected to body in production mode, just like below:

<img width="974" alt="image" src="https://user-images.githubusercontent.com/7334950/194735526-00d70a1e-7e60-4e79-b370-a9602e5f920c.png">

how do modify `HtmlWebpackPlugin.options` to achieve this goal, can someone give me some help?  I can't find any helpful message in doc.

**Comment by webdiscus** [comment]
@fantasticsoul 

you can try to use the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin) (modern alternative) to have full control for CSS and JS in generation HTML.

Using this plugin you can define source styles and scripts directly in HTML template.

**Comment by alexander-akait** [comment]
Please open an issue in `CRA`, `mini-css-extract-plugin` applied only for `mode: "production"`, so in development mode you will have `link`s, feel free to feedback
