### ISSUE TITLE
Control the order at which scripts are presented in template and executed

### ISSUE THREAD

**Issue by ackvf** [jantimon/html-webpack-plugin#1781]
**Context:**
I am developing a JIRA plugin app that relies on some window objects that I am mocking in another bundle.

**Problem:**
The requested `window.AJS` object is being called from the main bundle before the mock is executed (100ms later).
![image](https://user-images.githubusercontent.com/2313018/217291130-4a92f2d5-d70d-4d12-86df-0ee13b3bca43.png)

I need to be able to inject the mock bundle first and make it finish processing sooner than the main app bundle.

**Solution:**

- I don't really mind if both are `defer` as long as they are **executed in correct order**.
  -> solution: respect order of `chunks`
- Acceptable solution would also be to use `blocking` with the mock bundle and `defer` with the main bundle.
  -> solution: allow separate `scriptLoading` configuration for each chunk. e.g.:
  `scriptLoading?: "blocking" | "defer" | "module" | undefined | Record<string, "blocking" | "defer" | "module" | undefined>`
    ```
    scriptLoading: {
      index_head: 'blocking',
      index: 'defer',
    }
    ```
Order of chunks defined in options do not affect the order at which they are presented in the template.
![image](https://user-images.githubusercontent.com/2313018/217291441-eb6dec9c-06d7-4e54-befb-f19ae5958a8f.png) ![image](https://user-images.githubusercontent.com/2313018/217291553-f4d77b8f-4b0e-4bf8-bc19-7d06570b1de9.png)

**Comment by ackvf** [comment]
Okay, please disregard this. The order at which the bundles are injected is controlled by `entry` field of Webpack config.

![image](https://user-images.githubusercontent.com/2313018/217296256-ce35795c-b582-44cb-8dee-e1add1be2273.png)

**Comment by webdiscus** [comment]
@ackvf 

you can try to use new [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin) to have full control for all scripts and styles used in a HTML template.

Specify source scripts and styles directly in HTML where you need:

```html
<html>
<head>
  <!-- load source style -->
  <link href="./style.scss" rel="stylesheet">
  <!-- load source script -->
  <script src="./mocks/AJS.ts" defer="defer"></script>
</head>
<body>
  <h1>Hello World!</h1>
  <!-- load source script -->
  <script src="./index.tsx"></script>
</body>
</html>
```

The generated HTML:
```html
<html>
<head>
  <link href="css/style.css" rel="stylesheet">
  <script src="js/AJS.f4b855d8.js" defer="defer"></script>
</head>
<body>
  <h1>Hello World!</h1>
  <script src="js/index.5d8f4b85.js"></script>
</body>
</html>
```

_Webpack config_
```js
const path = require('path');
const HtmlBundlerPlugin = require('html-bundler-webpack-plugin');

module.exports = {
  plugins: [
    new HtmlBundlerPlugin({
      entry: {
        // define HTML templates here
        index: 'src/views/home/index.html', // output dist/index.html
      },
      js: {
        // output filename of extracted JS from source script loaded in HTML via `<script>` tag
        filename: 'js/[name].[contenthash:8].js',
      },
      css: {
        // output filename of extracted CSS from source style loaded in HTML via `<link>` tag
        filename: 'css/[name].[contenthash:8].css',
      },
    }),
  ],
  module: {
    rules: [
      {
        test: /.html/,
        loader: HtmlBundlerPlugin.loader, // HTML template loader
      },
      // ... other rules, e.g. for TypeScript, SCSS, images, fonts, etc.
    ],
  },
};
```
