### ISSUE TITLE
template parameters are not injected into index.html

### ISSUE THREAD

**Issue by aditya81070** [jantimon/html-webpack-plugin#1785]
## Current behaviour 💣

I am using a react application and overriding the webpack configuration using react-rewired to use module federation. For some configuration, I want to set `window._remotes` so I can use this object at another place. For this, I am trying to pass `remotes` as an template parameter/options but it is not passed. I have checked the docs and also checked internal code of this plugin to understand options.

## Expected behaviour ☀️

The template parameters should be available in the template file by using `<%= htmlWebpackPlugin.options.remotes %>`. 

> Disclaimer: This was working with webpack@beta version but now I am using webpack@5.76.3. 

### Reproduction Example 👾

Index.html
```
<!DOCTYPE html>
<html lang="en">

<head>
  <script type="text/javascript">
    window._remotes = <%= htmlWebpackPlugin.options.remotes %>;
  </script>
</head>

<body>
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div class="app-container" id="app"></div>

 
</body>

</html>
```

I have tried following ways to pass `remotes` in the index.html template:

1. Setting the `option` as mentioned in the `HtmlWebpackOptions`
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/30300772/227440815-db251429-ef52-4e26-82b7-4e98b507e578.png">

```
 if (plugin.constructor.name === 'HtmlWebpackPlugin') {
        plugin.option = { ...plugin.option, remotes: JSON.stringify(windowObject) };
      }
```

2. Setting the `.remotes` on  `userOptions` as it had `template` and other parameters. 
```
 if (plugin.constructor.name === 'HtmlWebpackPlugin') {
        plugin.userOptions = { ...plugin.userOptions, remotes: JSON.stringify(windowObject) };
      }
```

3. Setting the `.remotes` on the `templateParameters` as it is passed in the template
```
 if (plugin.constructor.name === 'HtmlWebpackPlugin') {
        if(plugin.userOptions.templateParameters) {
                plugin.userOptions.templateParameters.remotes = JSON.stringify(windowObject)
      } else {
                plugin.userOptions.templateParameters = {remotes : JSON.stringify(windowObject) }
      }
```
4. This one was working with webpack beta version. It started throwing error as `options` was undefined.
```
plugin.options.remotes = JSON.stringify(windowObject);
```

## Environment 🖥

```
Node.js v16.18.0
darwin 22.1.0
Using yarn instead of npm:
yarn: 1.22.19
webpack: webpack@5.76.3
html-webpack-plugin: html-webpack-plugin@5.5.0
```

**Comment by alexander-akait** [comment]
Sorry, reading `windows` is impossible because we run code on Node.js side, feel free to feedback
