### ISSUE TITLE
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.

### ISSUE THREAD

**Issue by First-Jim** [jantimon/html-webpack-plugin#1786]
HI，thanks for your works, but still have depreciation warnings with the latest versions. 

## Current behaviour 💣
yarn run start
==========
✔ Webpack
  Compiled successfully in 53.73s

Listening on port 8080 !
<i> [webpack-dev-middleware] wait until bundle finished: /__webpack_hmr
(node:3096) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)

## Environment 🖥
yarn：v1.22.18
node：v16.14.0
webpack：v5.77.0
html-webpack-plugin：5.5.0

**Comment by alexander-akait** [comment]
Please run `npm ls html-webpack-plugin` and `npm ls webpack`

**Comment by First-Jim** [comment]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/53132610/230258211-9c21ea69-38f9-4536-baa0-8016e12ab69e.png">
  "less": "^3.9.0",
    "less-loader": "^5.0.0"

**Comment by First-Jim** [comment]
> Please run `npm ls html-webpack-plugin` and `npm ls webpack`

<img width="812" alt="image" src="https://user-images.githubusercontent.com/53132610/230258211-9c21ea69-38f9-4536-baa0-8016e12ab69e.png">
  "less": "^3.9.0",
    "less-loader": "^5.0.0"，

**Comment by alexander-akait** [comment]
Looks like you have old version of `less-loader`, also please don't use `thread-loader`, replace it on the the `cache` option

**Comment by First-Jim** [comment]
ok, Thanks for your works.

**Comment by First-Jim** [comment]
> Looks like you have old version of `less-loader`, also please don't use `thread-loader`, replace it on the the `cache` option

ok, Thanks for your works.
