### ISSUE TITLE
lazy-require pretty-error to improve startup time

### ISSUE THREAD

**Issue by Knagis** [jantimon/html-webpack-plugin#1788]
## Current behaviour 💣

`require("pretty-error")` is run at startup since it is required in module scope. However, somehow that is rather heavy package to load, can take 200ms.

## Expected behaviour ☀️

Only do `require("pretty-error")` when actual error happens.

### Reproduction Example 👾

Anything that includes html-webpack-plugin, start node with `--inspect-brk`, attach debugger and profile. Or put console.logs in errors.js

## Environment 🖥

```
node 16, node 18
html-webpack-plugin 5.5.0
```

**Comment by alexander-akait** [comment]
@Knagis yeah, let's do it, do you want to send a PR?

**Comment by Knagis** [comment]
ok, will do

**Comment by Knagis** [comment]
PR ready.
