### ISSUE TITLE
Failed to install html-webpack-plugin with Node v18.15.0

### ISSUE THREAD

**Issue by nguem123** [jantimon/html-webpack-plugin#1790]
## Current behaviour 💣

I get the error while trying to install html-webpack-plugin:

npm ERR! Cannot convert a Symbol value to a string

## Expected behaviour ☀️

Install html-webpack-plugin with NodeJs v18.15.0

### Reproduction Example 👾
npm i -D html-webpack-plugin

## Environment 🖥
npm 6.14.15
webpack 5.79.0
html-webpack-plugin latest

**Comment by alexander-akait** [comment]
Sorry, I can't reproduce, feel free to feedback
