### ISSUE TITLE
this plugin Not allows if HTML file contains this symbols ( <,=,<=,<=)

### ISSUE THREAD

**Issue by Kranthi32** [jantimon/html-webpack-plugin#1791]
ERROR in Error: html-webpack-plugin could not minify the generated output.
In production mode the html minifcation is enabled by default.
If you are not generating a valid html output please disable it manually.
You can do so by adding the following setting to your HtmlWebpackPlugin config:
|
| minify: false
|
See https://github.com/jantimon/html-webpack-plugin#options for details.
For parser dedicated bugs please create an issue here:
https://danielruf.github.io/html-minifier-terser/
Parse Error: <,=,<=,<=)

**Comment by alexander-akait** [comment]
Please fill out the issue template, thank you
