### ISSUE TITLE
Insert just defer, not defer=defer

### ISSUE THREAD

**Issue by alexander-xyz** [jantimon/html-webpack-plugin#1817]
Hi. I use this config
`
new HtmlWebpackPlugin({
  inject: 'body',
  template: path.resolve(srcDir, 'empty.html'),
  filename: 'app.html',
}),
`
but it's insert just attribute defer=defer for <script>. Better to insert just defer (not defer=defer).

**Comment by alexander-akait** [comment]
You can enable minification mode and it will compress boolean attributes https://github.com/jantimon/html-webpack-plugin#minification
