### ISSUE TITLE
Don't update static link file in template.html

### ISSUE THREAD

**Issue by Paladnix** [jantimon/html-webpack-plugin#1825]
How to keep origin <link> code not been updated?

There are some fixed css code and personal css code, link like this. BUT, it is been updated by plugin.
```
  <link rel="stylesheet" href="/static/plugins/prism/prism.css" type="text/css" />
```

**Comment by alexander-akait** [comment]
You should can you `webpackConfig.output.publicPath` in template to use the valid public path, please read here https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates, feel free to feedback
