### ISSUE TITLE
how to make webpack recompile on dev mode with cache on?

### ISSUE THREAD

**Issue by robotsmeagol** [jantimon/html-webpack-plugin#1845]
trying to write a plugin based on HtmlWebpackPlugin to change the output of html.

dev mode with cache on, if index.html is not changed, how to make webpack recompile and generate html
```
class MyPlugin {
  apply(compiler) {
    compiler.hooks.compilation.tap("MyPlugin", (compilation) => {
      HtmlWebpackPlugin.getCompilationHooks(compilation).beforeEmit.tapAsync(
        "MyPlugin",
        (data, cb) => {
           data.html += Date.now();
           cb(null, data);
        },
      );
    });

    setInterval(() => {
      compiler.compile()
    }, 60000)
  }
}
```
dev mode with cache on, compiler.compile() won't regenerate html.

**Comment by alexander-akait** [comment]
You should not run:
```
setInterval(() => {
      compiler.compile()
    }, 60000)
```

it is bad for perf

**Comment by alexander-akait** [comment]
Sorry I don't undestand what do you try to do

**Comment by robotsmeagol** [comment]
i'm trying to get data from server and inject into html, like this
```
const res = await axios.get('xxx.com/xxxxx')
data.html += res.data
```
on dev mode, i want to use timer to check whether data from server changed and regenerate html if changed

**Comment by alexander-akait** [comment]
Please use `HtmlWebpackPlugin.getHooks(compilation).beforeEmit` right now (`getCompilationHooks` is not released), I don't recommend to run `compiler.compile` using times, you can send a `HEAD` request and check it is `304` code or not, and only when somethings changed re-run compilation

**Comment by robotsmeagol** [comment]
how to **re-run compilation**, do u mean `npm run dev` again?

**Comment by robotsmeagol** [comment]
i tried `compiler.watching.invalidate()`, but only first time this would works, after that html won't regenerate

**Comment by alexander-akait** [comment]
What do you mean won't regenerate?

**Comment by robotsmeagol** [comment]
U can check on this [demo](https://codesandbox.io/p/devbox/test-html-l8p784?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluwg6i5k00073b6iw7euq0bm%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluwg6i5j00023b6ic5puj96w%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluwg6i5j00043b6ix29r9k6l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluwg6i5k00063b6i19z6wcl5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluwg6i5j00023b6ic5puj96w%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluwg6i5j00013b6io0evpfx3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluwg6i5j00023b6ic5puj96w%2522%252C%2522activeTabId%2522%253A%2522cluwg6i5j00013b6io0evpfx3%2522%257D%252C%2522cluwg6i5k00063b6i19z6wcl5%2522%253A%257B%2522id%2522%253A%2522cluwg6i5k00063b6i19z6wcl5%2522%252C%2522activeTabId%2522%253A%2522cluwhrf6101cw3b6i8uj925mc%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cluwhrf6101cw3b6i8uj925mc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cluwg6i5j00043b6ix29r9k6l%2522%253A%257B%2522id%2522%253A%2522cluwg6i5j00043b6ix29r9k6l%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cluwhjaks00zr3b6ibyq2sg6d%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluwhjaks00zr3b6ibyq2sg6d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
customData is always 100 and never changed

**Comment by alexander-akait** [comment]
Solution:
```js
const HtmlWebpackPlugin = require("html-webpack-plugin");
const path = require("path");

class MyPlugin {
  constructor() {
    this.pathToData = path.resolve(__dirname, "./my-data.json");
  }

  apply(compiler) {
    compiler.hooks.thisCompilation.tap("MyPlugin", (compilation) => {
      HtmlWebpackPlugin.getHooks(compilation).beforeEmit.tapAsync(
        "MyPlugin",
        (data, cb) => {
            let content;

            try {
                content = compilation.inputFileSystem.readFileSync(this.pathToData, "utf8");
            } catch (error) {
                cb(error);

                return;
            }

            content = JSON.parse(content);

            compilation.fileDependencies.add(this.pathToData);

            data.html = data.html.replace(
                "</head>",
                `<script>window.customData=${JSON.stringify(content.value)}</script></head>`,
            );

            cb(null, data);
        },
      );
    });
  }
}

module.exports = MyPlugin;
```

File:

**my-data.json**

```
{
  "value": "11244123"
}
```

Add:
```js
{
  watchFiles: [require("path").resolve(__dirname, "my-data.json")],
  // Other options
}
```

to `config/webpackDevServer.config.js`

And disable cache for HtmlWebpackPlugin
```js
new HtmlWebpackPlugin(
        Object.assign(
          {},
          {
            cache: false,
            inject: true,
            template: paths.appHtml,
          },
          isEnvProduction
            ? {
                minify: {
                  removeComments: true,
                  collapseWhitespace: true,
                  removeRedundantAttributes: true,
                  useShortDoctype: true,
                  removeEmptyAttributes: true,
                  removeStyleLinkTypeAttributes: true,
                  keepClosingSlash: true,
                  minifyJS: true,
                  minifyCSS: true,
                  minifyURLs: true,
                },
              }
            : undefined,
        ),
      ),
```

i.e. `cache: false`, so webpack will automatically reload page and apply new data

**Comment by alexander-akait** [comment]
There is a bug in `cache` for html-webpack-plugin, that is why we disable it, I am working on the new major release without this bug, cache will work without extra setup in future and without bugs

**Comment by HcySunYang** [comment]
Hi @alexander-akait , has the issue about the `cache` been fixed right now?

**Comment by alexander-akait** [comment]
Yeah( I am still working on it, anyway HTML generation is fast, so just check it out

**Comment by HcySunYang** [comment]
The HTML can be generated fast, but it causes the dev server to reload the whole page, HMR won't work in that case, right? So in a large project, the impact is significant
