### ISSUE TITLE
How to use alias in <%= require('html-loader!./partial.html').default %>?

### ISSUE THREAD

**Issue by chishuix** [jantimon/html-webpack-plugin#1849]
I configured the following alias
```js
  resolve: {
    alias: {
      // ...
      "components": path.resolve(__dirname, "./src/common/components"),
    }
  },
```
But when I use it as follows, I get a `Can't resolve ... ` error .
```html
<%= require('html-loader!components/partial.html').default %>
<%= require('html-loader!~components/partial.html').default %>
<%= require('html-loader!@components/partial.html').default %>
```
So, how do I use aliases here?
Thx.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
