### ISSUE TITLE
remove inline script from index.html

### ISSUE THREAD

**Issue by lizhanglong** [jantimon/html-webpack-plugin#1852]
## Current behaviour 💣
there are inline script in index.html after build action
<script>!function(e){function t(t){f.........</script>

## Expected behaviour ☀️

I want to put the inline script in a file so that I can configure the CSP.

## Environment 🖥
Node.js v14.21.2
win32 10.0.22631
NPM 6.14.17
webpack@4.44.2
html-webpack-plugin@4.5.0

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
