### ISSUE TITLE
Sometimes index.html is not packaged into the dist directory，about 1/3 probability or 1/4 probability

### ISSUE THREAD

**Issue by liminggezs** [jantimon/html-webpack-plugin#1854]
![WechatIMG3209](https://github.com/user-attachments/assets/dd43661c-e939-43d0-970b-657b505541df)

old project used webpack@2.7.0   "html-webpack-plugin": "^2.30.1"

**Comment by liminggezs** [comment]
![Uploading WechatIMG3210.jpg…]()

**Comment by liminggezs** [comment]
![WechatIMG3210](https://github.com/user-attachments/assets/c8cfd0a5-0b05-4e7e-8f20-3b380a504a58)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
