### ISSUE TITLE
html-webpack-plugin seemingly causes arrow functions to be escaped to `() =&gt;` after yarn upgrade

### ISSUE THREAD

**Issue by Nantris** [jantimon/html-webpack-plugin#1856]
## Current behaviour 💣

Suddenly our builds cannot work due to our code being HTML-escaped

## Expected behaviour ☀️

JavaScript is not treated as HTML in need of escaping

### Reproduction Example 👾

Unknown. I've been trying to discover the precise cause of this for days but it's not easy when your `yarn.lock` has hundreds of changed lines. The `yarn upgrade` was only done after we'd already manually upgraded all of our direct dependencies, so it only upgraded sub-dependencies and it's been impossible to pinpoint which is the cause so far despite hours of trial and error.

## Environment 🖥

```
Node.js v20.14.0
linux 6.8.0-41-generic
10.7.0
```

**Comment by Nantris** [comment]
Apparently `minify` is not false even when the mode is not `production`. `minify` is the issue.

**Comment by Nantris** [comment]
Specifically `minifyCSS` seems to have caused our problem.

**Comment by alexander-akait** [comment]
please open an issue in `html-minifier-terser`, we can't fix it here and we don't change it in laster releases, thank you
