### ISSUE TITLE
Security Policy

### ISSUE THREAD

**Issue by jackfromeast** [jantimon/html-webpack-plugin#1858]
Hi, `html-webpack-plugin` devlopers, @jantimon and @mastilver!

Could you guys set up a security policy (enable the entry for reporting and patching vulnerabilities privately) for this repository to support responsible reporting of security issues?

Thank you!

**Comment by alexander-akait** [comment]
It is the same - https://github.com/webpack/webpack/blob/main/SECURITY.md
