### ISSUE TITLE
eslint 9: unknown option "extensions"

### ISSUE THREAD

**Issue by doits** [jantimon/html-webpack-plugin#1859]
## Current behaviour 💣

With eslint 9, the following error happens:

```
 Error: Child compilation failed:
  [eslint] Invalid Options:
  - Unknown options: extensions
  - 'extensions' has been removed.

  - child-compiler.js:174
    [project]/[html-webpack-plugin]/lib/child-compiler.js:174:18
```

## Expected behaviour ☀️

It should be compatible with eslint 9.

## More information

It was briefly discussed at https://github.com/eslint/eslint/discussions/18674 already, with not further outcome.

**Comment by alexander-akait** [comment]
Sorry, not related to `html-webpack-plugin`, I think you need - https://github.com/webpack-contrib/eslint-webpack-plugin/issues/263#issuecomment-2292928594

**Comment by doits** [comment]
Sorry for the noise and thank you for the right direction, I fixed it with your hint!
