### ISSUE TITLE
Latest release 5.6.2 breaks webpack-favicons

### ISSUE THREAD

**Issue by aleho** [jantimon/html-webpack-plugin#1866]
The latest release broke webpack-favicons output for me.

## Current behaviour 💣

With the example below on version 5.6.2 `html/favicons.html` will look like this:

```html
<script defer src="/build/build_name/app/runtime.js"></script><script defer src="/build/build_name/app/app.js"></script><link href="/bu
ild/build_name/app/app.css" rel="stylesheet">
```

## Expected behaviour ☀️

On version 5.6.0 it looked like this:

```html
<link rel="shortcut icon" href="/build/build_name/app/favicons/favicon.ico"><link rel="icon" type="image/png" sizes="16x16" href="/b
uild/build_name/app/favicons/favicon-16x16.png"><link rel="icon" type="image/png" sizes="32x32" href="/build/build_name/app/favicons/fa
vicon-32x32.png"><link rel="icon" type="image/png" sizes="48x48" href="/build/build_name/app/favicons/favicon-48x48.png"><script def
er src="/build/build_name/app/runtime.js"></script><script defer src="/build/build_name/app/app.js"></script><link href="/build/build_name
/app/app.css" rel="stylesheet">
```

### Reproduction Example 👾

Using the following template and configuration:

```
<%= htmlWebpackPlugin.tags.headTags %>
<%= htmlWebpackPlugin.tags.bodyTags %>
```

```
new HtmlWebpackPlugin({
    template: 'html.tmpl',
    filename: 'html/favicons.html',
    minify:   false,
    inject:   false,
})

new WebpackFavicons({
    src:  'favicon.svg',
    path: 'favicons',
    icons: {
        favicons: true
    },
})
```

## Environment 🖥

```
Node.js v20.17.0
linux 6.11.3-200.fc40.x86_64
Npm 10.9.0
webpack@5.95.0
webpack-favicons@1.3.8
```

**Comment by alexander-akait** [comment]
Could you create a reproducible repository using github?

**Comment by alexander-akait** [comment]
Found the problem - https://github.com/drolsen/webpack-favicons/blob/master/index.js#L78

Now:

```js
require('html-webpack-plugin/lib/hooks').getHtmlWebpackPluginHooks(compilation).alterAssetTags.tapAsync(
```

How to fix:

```js
require('html-webpack-plugin').getCompilationHooks(compilation).alterAssetTags.tapAsync(
```

`html-webpack-plugin/lib/hooks'` is a module which has never been public and using it in this way is very dangerous, as the project structure may change 

There is a fix - https://github.com/jantimon/html-webpack-plugin/pull/1867, but I would recommend raising the issue in `webpack-favicons`, because it will stop working in the next major religion

**Comment by aleho** [comment]
Thank you very much! I opened an issue in webpack-favicons as well.
