### ISSUE TITLE
extract-text-plugin isn't compatible with webpack 2 anymore

### ISSUE THREAD

**Issue by jantimon** [jantimon/html-webpack-plugin#401]
extract-text-plugin isn't compatible with webpack 2 anymore and therefore all examples are broken for webpack 2.

unfortunately the integration tests use those examples to verify that the webpack-html-plugin is compatible with webpack 2.

**Comment by robwise** [comment]
what about using extract-text-plugin `2.0.0-beta.3` since it's webpack-2 compatible?

**Comment by jantimon** [comment]
Then we would have to drop all webpack 1 integration tests as extract-text-plugin 2 is not compatible with webpack 1

**Comment by numical** [comment]
Hi Jan,
FYI.
I dealt with this issue for [style-ext-html-webpack-plugin](https://github.com/numical/style-ext-html-webpack-plugin) using a quick monkey-patch of `Module._load` - see the  [test code](https://github.com/numical/style-ext-html-webpack-plugin/blob/master/spec/plugin-spec.js#L79).
I have hived off the monkey-patch into its own [module](https://github.com/numical/dynavers).
Once this module is out of alpha (i.e. I have written some tests for it) would you be interested in a PR for `html-webpack-plugin` on these lines)?

**Comment by jantimon** [comment]
Well we would also have to change all tests.. so installing is not a problem

**Comment by LoicMahieu** [comment]
https://github.com/webpack/extract-text-webpack-plugin supports webpack@2

**Comment by jantimon** [comment]
@LoicMahieu but not webpack1

**Comment by bebraw** [comment]
There's a problem that's specific to running HMR in `multiStep` mode as discussed https://github.com/webpack/webpack/issues/2985 .

To quote Tobias:

> the hot update chunks are also "chunk assets" and it looks like that the html-plugin generates a script tag for them.
> html-plugin should use the new stats.entrypoints data to generate the script tags. This contains all needed files for an entrypoint in correct order.

If you want, I can open a separate issue to track this.

**Comment by jantimon** [comment]
Sure please - is there any developer documentation on stats.entrypoints?
Is there any way to get this backwards compatible?

**Comment by bebraw** [comment]
> Sure please - is there any developer documentation on stats.entrypoints?

Not that I know of.

> Is there any way to get this backwards compatible - like backporting stats.entrypoints to webpack 1?

I expect some ugly check like `require('webpack/package.json').version` might be needed unless the plugin instance passes a version field.

I'll open a separate issue and get Tobias in the loop.

**Comment by luishdz1010** [comment]
Is there a known workaround to make html-webpack-plugin work with webpack 2?

**Comment by brandonb927** [comment]
@luishdz1010 I am running webpack 2.2, am fairly new to webpack itself as well, and have `html-webpack-plugin` running fine

**Comment by bebraw** [comment]
To my understanding only HMR `multiStep` option is broken with webpack 2 as discussed at #533.

**Comment by bebraw** [comment]
@luishdz1010 Are you having any particular issues with it?
