### ISSUE TITLE
working with multiple pages

### ISSUE THREAD

**Issue by sgraham785** [jantimon/html-webpack-plugin#468]
how should i be properly work with multiple pages in a single template?

e.g. dashboard page vs account info page with a common/ shared layout 

possible dir structure:

```
templates/
    layout.html
pages/
    dashboard.html
    account_info.html
components/
    dashboard_widget.html
    left_nav.html
```

i want to simple loop though the pages and interpolate the components in page markup and pages in template. which produces a single markup file per page.

dashboard.html = 

```
<div id="#blah">
  ${require('dashboard_widget.html')}
</div>
```

layout.html = 

```
<html>
<meta>
<head></head>
<body>
<div id="left-nav">
  ${require('../components/left_nav.html')}
</div>
<div id="page-content">
  ${require('../pages/[name].html')}
</div>
</body>
</html>
```

any ideas welcome. can't seem to accomplish this complexity

**Comment by wochap** [comment]
I used [unversal-router](https://github.com/kriasoft/universal-router) (for dynamically load the correct template according the current route), [static-site-generator-webpack-plugin](https://github.com/markdalgleish/static-site-generator-webpack-plugin) (for build the html files) and [pug-loader](https://github.com/pugjs/pug-loader) (extends, partials, [Inheritance](https://pugjs.org/language/inheritance.html))

You can check it [here](https://github.com/wochap/webpack-basic-boilerplate/tree/pug)

**Comment by wochap** [comment]
You could also take a look [html-webpack-harddisk-plugin](https://github.com/jantimon/html-webpack-harddisk-plugin)
