### ISSUE TITLE
Using chunks or excludeChunks config causes webpackJsonp is not defined error

### ISSUE THREAD

**Issue by jbeckton** [jantimon/html-webpack-plugin#475]
I am trying to create 2 separate css files and have only one of them injected into the head of my index.html. The reason behind this is I need to write a theme switcher for my app which essentially sets the style sheet filename from two options, light and dark style sheets.

```
`config.entry = isTest ? {} : {
'dg-light': './src/dg-light.ts',
'dg-dark': './src/dg-dark.ts',
'polyfills': './src/polyfills.ts',
'vendor': './src/vendor.ts',
'app': './src/main.ts' // our angular app
 };`


`new HtmlWebpackPlugin({
template: './src/public/index.html',
chunksSortMode: 'dependency',
chunks: ['vendor', 'polyfills', 'dg-light']
//excludeChunks:  ['dg-dark']
  })`
```

**Comment by jantimon** [comment]
So would it work if you don't exclude the dark theme?

Are you using the common chunks plugin?

**Comment by jbeckton** [comment]
If I use either chunks or excludeChunks it gives the error, so neither work.

I am using the common chunks plugin. I am trying to prevent both dark and light themes from getting injected, just want one of them injected by default, the other is loaded using javascript to toggle light and dark.

**Comment by jantimon** [comment]
Maybe the issue is the chunkSortMode

**Comment by urzhumskov** [comment]
Similar issue here. Two html files generated for two apps sharing much of the code, so JS code is split into several chunks: `commons.js`, `vendor-commons.js`, `vendor-app1.js`, `vendor-app2.js`, `main-app1.js`, `main-app2.js`. Tried to specify the correct order of chunks in options and use `chunksSortMode: "none"`, but the chunks are NOT injected in the order I specified.

**Comment by Sayan751** [comment]
I am also facing the same issue, and described the problem in details [here](http://stackoverflow.com/questions/40379996/how-to-configure-multiple-entry-point-htmls-with-webpack-easy-webpack).

**Comment by jantimon** [comment]
It seems like you are doing a concat like approach which won't work with the html-webpack-plugin.
The webpack plugin can sort all dependencies as long as you keep a valid dependency tree.
