### ISSUE TITLE
Exclamation mark in file-path

### ISSUE THREAD

**Issue by andreasgruenh** [jantimon/html-webpack-plugin#530]
Hello everyone, loving your plugin so far!

Today I encountered the following error:
When ANY parent-directory of your project contains an exclamation-mark in its name, the module won't build.

This is the webpack.config I'm testing this with:

```
var HtmlWebpackPlugin = require('html-webpack-plugin');
var webpackConfig = {
  entry: './index.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  plugins: [new HtmlWebpackPlugin()]
};

module.exports = webpackConfig;
```

**Comment by yoisel** [comment]
I am facing the same issue with angular-cli that uses webpack internally.

Workaround, do a [_subst_](https://technet.microsoft.com/en-us/library/bb491006.aspx) on a new drive letter to root folder of your project and start from there.
Example: Your project is located at C:\!MySources\!AwosomeCompany\Projects\MyBestProject

Do `subst z: "C:\!MySources\!AwosomeCompany\Projects"`

Then use webpack from z:\MyBestProject

**Comment by mastilver** [comment]
I believe this is caused by this line: https://github.com/jantimon/html-webpack-plugin/blob/2d5c42ff18985958b4991eaac615ec9ac467715f/index.js#L15

I'm not sure if it's something we can fix :/
