### ISSUE TITLE
HMR multiStep mode is broken in webpack 2

### ISSUE THREAD

**Issue by bebraw** [jantimon/html-webpack-plugin#533]
Currently enabling `multiStep` mode in `HotModuleReplacementPlugin` breaks html-webpack-plugin. The page simply won't refresh correctly breaking the system. The fix for this requires an underlying change as discussed below.

To quote @sokra 

> the hot update chunks are also "chunk assets" and it looks like that the html-plugin generates a script tag for them.
> html-plugin should use the new stats.entrypoints data to generate the script tags. This contains all needed files for an entrypoint in correct order.

Here's a [quick search against webpack source](https://github.com/webpack/webpack/search?p=3&q=entrypoints&utf8=%E2%9C%93), but I can't find a definitive plugin example on a quick look.

To keep this backwards compatible we would need some way to check webpack version. A simple way to do that is to go through `require('webpack/package.json').version` although it would be better if plugins received the version information from webpack (does this happen already?).

Related to #401.

**Comment by jantimon** [comment]
Could we expose stats.entrypoints also in webpack 1.x?
This would allow us to have a clean upgrade path.

**Comment by sokra** [comment]
`stats.entrypoints` is webpack 2 only. We added it for your use case. It lists all files required for an entrypoint in the correct order. So you don't have to do the ordering yourself. It's exposed by webpack. You may separate files by filetype (i. e. put styles before scripts).

**Comment by jantimon** [comment]
@sokra  Is there any reason not to add `stats.entrypoints` for webpack 1 ?

**Comment by moimael** [comment]
Is this still being worked on ?

**Comment by niieani** [comment]
The problem is:

```
TypeError: Cannot read property 'source' of undefined.
```

It occurs [here](https://github.com/jantimon/html-webpack-plugin/blob/4e6f902cab30d4cd31d688198a79ca9f8b10963b/lib/compiler.js#L88-L99).

Specifically:

1. the asset is deleted: `delete compilation.assets[outputName]`
2. and we try to call a method on a now undefined value: `childCompilation.assets[outputName].source()`

The problem was introduced quite a while ago: https://github.com/jantimon/html-webpack-plugin/commit/be966e70e093cab483a67017bec9e97f65c09c3d#diff-168726dbe96b3ce427e7fedce31bb0bcR195.

**Comment by niieani** [comment]
Actually, scratch that. `childCompilation` doesn't have the asset, so while the error is the same, it's not caused by the `delete` that I've mentioned above. Still, it shouldn't be too hard to fix this, should it?

**Comment by albertotorresfoltyn** [comment]
Here, when changing some js file it realoads the old version

**Comment by sibelius** [comment]
is this fixed on master? or latest version?
