### ISSUE TITLE
Appending chunkhash to the file name instead of a hash

### ISSUE THREAD

**Issue by tomitrescak** [jantimon/html-webpack-plugin#543]
Hi, thank for all the great work!
I wanted to ask if it is possible to append chunkhash to the filename instead of a hash?
Currently the { hash: true } can append `file?#hash` to the file, but I'd really like to add this for all automatically generated chunks.

The idea is to generate chunks only with filename (e.g. mychunk.js) and inserting it to HTML with (mychunk.js?chunkhash).

This way I can store the builds easily in git and when deployed, users will get only recently changed files.

**Comment by damianobarbati** [comment]
Yeah, absolutely +1!!!
Use case: 2 chunks, 1 for the app (frequently changed), 2 for the vendor (almost never change).
Since we append the "bundle hash", the vendor gets invalidated but it didn't change at all!

We should append the hash relative to the chunk, this way only the chunks which really changed will be reloaded by browsers.

**Comment by damianobarbati** [comment]
any news on this?

**Comment by damianobarbati** [comment]
Solved.
Don't use the plugin hash option because it only use the bundle [hash].
Just append [chunkhash] to your outputs.

**Comment by damianobarbati** [comment]
up!

**Comment by damianobarbati** [comment]
@tomitrescak did you find a solution to use chunkhash in the different chunk/assets in the html generated?

**Comment by damianobarbati** [comment]
@jantimon any chance on this? :)

**Comment by caub** [comment]
The only option I can see is to read the output files on disk, hash them with md5 but they are not written on disk yet at that time right?

**Comment by mastilver** [comment]
I personally don't use `hash`, I use `chunkhash` on `output.filename`

**Comment by caub** [comment]
Yes I tried that at the same time `filename: '[name].js?v=[chunkhash:4]'`

html-webpack-plugin generates a 


```
<script type="text/javascript" src="app.js?v=e2b6">
```

but keep the css like:

```
<link href="app.css" rel="stylesheet">
```


webpack config:

```js
module.exports = {
    entry: {
        app: [
            './src/scripts/main.js',
            './src/style/style.scss'
        ],
        'pdf.worker': './node_modules/gravit/lib/import/pdf/pdf.worker.js',
    },
    output: {
        path: process.cwd()+'/build',
        filename: '[name].js?v=[chunkhash:4]',
        // chunkFilename: '[chunkhash].js'
    },
    node: {
        fs: 'empty',
        child_process: 'empty'
    },
    resolve: {
        extensions: ['.js', '.jsx', '.json']
    },
    module: {
        loaders: ....
    },
    plugins: [
        new HtmlWebpackPlugin({
            //hash: true,
            title: '......',
            template: './src/index.html',
            filename: './index.html'
        }),
    ]
};

```

**Comment by mastilver** [comment]
Of course

You need to do the same with `ExtractTextPlugin`'s `filename` but using `[contenthash]`

**Comment by caub** [comment]
thanks!

I think this issue could be closed?

**Comment by viperfx07** [comment]
Tried on webpack 3.5.6, it doesn't work anymore having chunkFilename: '[name].js?v=[chunkhash]'

got Error: ENOENT: no such file or directory,
