### ISSUE TITLE
[name] is not acceptable in filename option

### ISSUE THREAD

**Issue by rdandnayak** [jantimon/html-webpack-plugin#553]
Here is my configuration in webppack.config.js

```
new HtmlWebpackPlugin({
      template: 'src/layouts/index.ejs',
      filename: '[name]/index.html',
 }),
```

for above config [name] is outputting as 0.html
and also i want to generate it in specific folder just like [name]/[name].html

is this supported in this plugin? or any easy workaround available

I will be having multiple directories like this to be created, its multi page web application.
or if you can suggest better approach that would be helpful

**Comment by jantimon** [comment]
That's the same like #556

**Comment by LeoMartinDev** [comment]
+1

**Comment by simshanith** [comment]
For a currently working approach, see discussion https://github.com/jantimon/html-webpack-plugin/issues/218

**Comment by Luomusha** [comment]
+1
When I want to rename my HTML template files dynamically,I met this problem,too.And I perfer no coding in config file.

**Comment by york-xtrem** [comment]
I totally agree, I want to change from Gulp to Webpack but without support for static pages / multipage is being a hell ...

I can not find optimal solutions.

I usually use Panini, but if possible with these other template libraries would be great:

- http://markojs.com/
- https://mozilla.github.io/nunjucks/
- https://pugjs.org/api/getting-started.html

Automatically detect multiple pages and inject css and javascript bundles.

Is that possible?

**Comment by mastilver** [comment]
Give https://github.com/mutualofomaha/multipage-webpack-plugin a try
