### ISSUE TITLE
tutorial on working with multiple compilations/configs

### ISSUE THREAD

**Issue by graingert** [jantimon/html-webpack-plugin#559]
I'd like to create two JS bundles one with esnext->ES5 via babel-preset-env (IE11) and one linking to a config esnext->escurrent-ish via babel-preset-env(chrome 54, firefox 51). 

I'd like to be able to switch between them somehow, eg feature detection in the HTML or something in the server. I think this is a bit of a pain with html-webpack-plugin (not sure though).

Most of our customers are on Chrome >= 54, so we don't mind slowing the site down a bit for those users running ES5.

**Comment by jantimon** [comment]
You could write a plugin which does that using the `html-webpack-plugin-alter-asset-tags` event.

**Comment by graingert** [comment]
for server side switching it's easy: just two configs with different build directories eg: "build/es5", "build/escurrent-ish"

**Comment by graingert** [comment]
closing in favor of https://github.com/jantimon/html-webpack-plugin/issues/782 because chrome 61 supports JS feature detection with type=module / nomodule
