### ISSUE TITLE
Rename closingTag into voidTag like in the official w3c spec.

### ISSUE THREAD

**Issue by jantimon** [jantimon/html-webpack-plugin#576]
@numical (and other plugin authors) might you please give feedback on https://github.com/ampedandwired/html-webpack-plugin/pull/575/commits/0a7d2244f49999ea8df8e4bf367a79ced118e523?

The idea is to use `voidTag` instead of `closingTag` and `selfClosingTag` and to give plugin authors an easy helper to inject new tags.

**Comment by numical** [comment]
Seems sensible enough - consistent tags should be a good thing.  
I cannot see any gotchas from reviewing the commit.
I'll start a branch for my plugins using this and see if I spot any problems.
Any deadline you need feedback by?  i.e. when's v3 being published?
