### ISSUE TITLE
Move repo to jantimon/html-webpack-plugin

### ISSUE THREAD

**Issue by ampedandwired** [jantimon/html-webpack-plugin#577]
When I first created the html-webpack-plugin I never envisioned just how incredibly popular it would become. At the time, personal circumstances prevented me from being able to maintain it on an ongoing basis, so @jantimon kindly stepped in to help out.

He's been an amazing custodian of the project, and has spent countless hours making it what it is today. It has become an integral part of the webpack ecosystem, and is used in many react, angular2 and vue starters. Thanks Jan for the awesome work you've done!

This project has become his far more than it is mine, and he deserves the credit for the time he has put into it. As such I am transferring ownership of the repository to him today. The new repo will be found at https://github.com/jantimon/html-webpack-plugin and this repo will redirect to there.

We'll try to make the transition as smooth as possible, but if you notice anything broken please let us know. The npm package should be unaffected, aside from a change in the source repo URL.

**Comment by ampedandwired** [comment]
The repo has been transferred. New URL is https://github.com/jantimon/html-webpack-plugin

**Comment by jantimon** [comment]
Thanks Charles :)
