### ISSUE TITLE
Angular | Error: Child compilation failed:

### ISSUE THREAD

**Issue by CyberGolem** [jantimon/html-webpack-plugin#578]
Recently I'm not able to get my Angular app to load in Chrome. Instead of the typical "App Works" that appears when loading a newly created skeleton app, I get this ::

Html Webpack Plugin:
  Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'raw-loader' in 'Y:\OneDrive\~webDev\ChazSutherland\my-app':
  Error: Can't resolve 'raw-loader' in 'Y:\OneDrive\~webDev\ChazSutherland\my-app'
  
  - compiler.js:76 
    [npm]/[angular-cli]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:280 Compiler.
    [npm]/[angular-cli]/[webpack]/lib/Compiler.js:280:10
  
  - Compiler.js:480 
    [npm]/[angular-cli]/[webpack]/lib/Compiler.js:480:13
  
  - Tapable.js:138 next
    [npm]/[angular-cli]/[tapable]/lib/Tapable.js:138:11
  
  - CachePlugin.js:62 Compiler.
    [npm]/[angular-cli]/[webpack]/lib/CachePlugin.js:62:5
  
  - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[tapable]/lib/Tapable.js:142:13
  
  - Compiler.js:477 
    [npm]/[angular-cli]/[webpack]/lib/Compiler.js:477:10
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:615 self.applyPluginsAsync.err
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:615:19
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:606 self.applyPluginsAsync.err
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:606:11
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:601 self.applyPluginsAsync.err
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:601:10
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:597 sealPart2
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:597:9
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:545 Compilation.seal
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:545:8
  
  - Compiler.js:474 
    [npm]/[angular-cli]/[webpack]/lib/Compiler.js:474:16
  
  - Tapable.js:225 
    [npm]/[angular-cli]/[tapable]/lib/Tapable.js:225:11
  
  - Compilation.js:452 _addModuleChain
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:452:11
  
  - Compilation.js:345 Compilation.errorAndCallback
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:345:4
  
  - Compilation.js:362 moduleFactory.create
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:362:12
  
  - NormalModuleFactory.js:234 
    [npm]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:234:19
  
  - NormalModuleFactory.js:59 onDoneResolving
    [npm]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:59:20
  
  - NormalModuleFactory.js:183 
    [npm]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:183:21
  
  - async.js:3694 
    [npm]/[angular-cli]/[async]/dist/async.js:3694:9
  
  - async.js:356 
    [npm]/[angular-cli]/[async]/dist/async.js:356:16
  
  - async.js:934 iteratorCallback
    [npm]/[angular-cli]/[async]/dist/async.js:934:13
  
  - async.js:840 
    [npm]/[angular-cli]/[async]/dist/async.js:840:16
  
  - async.js:3691 
    [npm]/[angular-cli]/[async]/dist/async.js:3691:13
  
  - async.js:21 apply
    [npm]/[angular-cli]/[async]/dist/async.js:21:25
  
  - async.js:56 
    [npm]/[angular-cli]/[async]/dist/async.js:56:12
  
  - async.js:1013 
    [npm]/[angular-cli]/[async]/dist/async.js:1013:9
  
  - async.js:356 
    [npm]/[angular-cli]/[async]/dist/async.js:356:16
  
  - async.js:934 iteratorCallback
    [npm]/[angular-cli]/[async]/dist/async.js:934:13
  
  - async.js:840 
    [npm]/[angular-cli]/[async]/dist/async.js:840:16
  
  - async.js:1010 
    [npm]/[angular-cli]/[async]/dist/async.js:1010:13
  
  - NormalModuleFactory.js:262 
    [npm]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:262:19
  
  - Resolver.js:70 onResolved
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:70:11
  
  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
  - Resolver.js:138 afterInnerCallback
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:138:10
  
  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
  - Tapable.js:181 Resolver.applyPluginsAsyncSeriesBailResult1
    [npm]/[angular-cli]/[tapable]/lib/Tapable.js:181:46
  
  - Resolver.js:125 innerCallback
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:125:19
  
  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
  - Tapable.js:283 
    [npm]/[angular-cli]/[tapable]/lib/Tapable.js:283:15
  
  - UnsafeCachePlugin.js:39 
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/UnsafeCachePlugin.js:39:4
  
  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
  - Resolver.js:138 afterInnerCallback
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:138:10
  
  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
  - Tapable.js:181 Resolver.applyPluginsAsyncSeriesBailResult1
    [npm]/[angular-cli]/[tapable]/lib/Tapable.js:181:46
  
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

I have no idea what to do about it.

**Comment by jantimon** [comment]
`Can't resolve 'raw-loader'` means that webpack can't find the npm module - maybe you forgot to install it. Please ask questions like this on stackoverflow to help users with similar problems

**Comment by CyberGolem** [comment]
Will do and thank you.
