### ISSUE TITLE
Allow easier customization of where link tags are injected

### ISSUE THREAD

**Issue by yaycmyk** [jantimon/html-webpack-plugin#581]
`<link>` tags can be injected inside `<body>` to defer their download time. This can be combined with a plugin like the source inlining one to ensure critical path CSS is available on load, and other non-critical CSS is deferred to later in the page load cascade.

Currently if you set `inject: 'body'`, that only affects `<script>` tags. I think that's probably sensible, but there should be a way to direct this plugin to also place `<link>` tags in an alternate location, like the end of `<body>`.

**Comment by jantimon** [comment]
That would cause a fouc right?
You can already do that using the template option but we should consider this for version 3.x

**Comment by yaycmyk** [comment]
@jantimon There wouldn't be a FOUC if the critical path CSS was inlined as I described.

**Comment by jantimon** [comment]
It would be possible to write a plugin which moves all link tags to the body and inlines the critical css similar to https://github.com/numical/style-ext-html-webpack-plugin#use-case-internalize-critical-css-only

style-ext-html-webpack-plugin is quite generic but a plugin which takes only care of critical css could be even more powerfull in its domain

**Comment by numical** [comment]
Alway interested in making style-ext... more useful.  @jantimon - what were you thinking of here - I don't follow..

**Comment by jantimon** [comment]
@numical great to have you involved 👍 

@yaycmyk is looking for a way to move only the critical css into the head and move the rest of the css to the bottom of the page - I guess including this to your plugin might cause a mess so maybe you could work together on a new plugin which focuses only on the critical css path

**Comment by numical** [comment]
Yeah - I thought all modern browsers downloaded eagerly. Though perhaps the processing blocks ..?  @yaycmyk - if you are considering only stylesheets I'm happy to move this to a style-ext... issue ..?

**Comment by numical** [comment]
@yaycmyk - similar (if not identical) requests are being made in an [issue for style-ext-webpack-plugin](https://github.com/numical/script-ext-html-webpack-plugin/issues/6#issuecomment-279149751).
I suggest @jantimon closes the issue here, and you pick it up with me over there...

**Comment by yaycmyk** [comment]
Not quite unless you want to start being responsible for non inlined scripts too
