### ISSUE TITLE
Add support for setting the media attribute on stylesheet link tags

### ISSUE THREAD

**Issue by yaycmyk** [jantimon/html-webpack-plugin#582]
There is a `media` [link element attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#Attributes) that hints to the browser if it should download the CSS file. It would be awesome if there was a way to tell this plugin to add that information to the injected element.

I was thinking that perhaps grabbing this information in Base64 from the filename could be a possibility. Like if you use the ExtractTextPlugin and set the output filename to be:

```
"print" -> base64 -> "cHJpbnQ="

style.media_cHJpbnQ=.css

becomes:

<link rel="stylesheet" src="style.media_cHJpbnQ=.css" media="print" />
```

A more complicated example:

```
"(min-width: 700px), handheld and (orientation: landscape)" -> base64 -> "KG1pbi13aWR0aDogNzAwcHgpLCBoYW5kaGVsZCBhbmQgKG9yaWVudGF0aW9uOiBsYW5kc2NhcGUp"

style.media_KG1pbi13aWR0aDogNzAwcHgpLCBoYW5kaGVsZCBhbmQgKG9yaWVudGF0aW9uOiBsYW5kc2NhcGUp.css

becomes:

<link rel="stylesheet" src="style.media_KG1pbi13aWR0aDogNzAwcHgpLCBoYW5kaGVsZCBhbmQgKG9yaWVudGF0aW9uOiBsYW5kc2NhcGUp.css" media="(min-width: 700px), handheld and (orientation: landscape)" />
```

Base64 is good for this use case because of the parens and other characters that could break the filename in different file systems.

**Comment by jantimon** [comment]
Yes it's quite easy to write a plugin that does exactly that - take a look at the https://github.com/jantimon/resource-hints-webpack-plugin which does sth similar

**Comment by yaycmyk** [comment]
Ah I made a PR last night 😊

**Comment by yaycmyk** [comment]
I can pluginify it though if you don't want the functionality in master

**Comment by jantimon** [comment]
Would be better - we try to keep the master as simple as possible and to move features like that into external plugins :)

You can create a PR to add a link to your plugin in the readme

**Comment by ccorcos** [comment]
How is this supposed to work?

**Comment by probablyup** [comment]
@ccorcos https://www.npmjs.com/package/link-media-html-webpack-plugin
