### ISSUE TITLE
A doubt about the source code at line 20 in loader.js

### ISSUE THREAD

**Issue by JasonKid** [jantimon/html-webpack-plugin#587]
```javascript
  // Skip .js files
  if (/\.js$/.test(this.request)) {
    return source;
  }
```

If it is for skipping process target files of js, should it be :
```javascript
  // Skip .js files
  if (/\.js$/.test(this.resourcePath)) {
    return source;
  }
```

If it is `this.request`, it will not work when the resource file with query params, like `loader?resource.js?rrr`.

> https://webpack.js.org/api/loaders/#resourcepath
> https://webpack.js.org/api/loaders/#request

**Comment by jantimon** [comment]
Where would you be able to use `rrr`?

**Comment by jantimon** [comment]
Yes you are correct - does resourcePath exist for webpack 1?

**Comment by JasonKid** [comment]
It exists for webpack 1.x.

> http://webpack.github.io/docs/loaders.html#resourcepath

**Comment by jantimon** [comment]
Cool just open a pull request and I'll merge it if all tests pass

**Comment by JasonKid** [comment]
Done with it.

**Comment by jantimon** [comment]
thanks 👍
