### ISSUE TITLE
Cannot read property 'html-webpack-plugin-after-emit' of undefined

### ISSUE THREAD

**Issue by vlad-ovsyannikov** [jantimon/html-webpack-plugin#589]
webpack 1.14
node 6.3.1

Cannot read property 'html-webpack-plugin-after-emit' of undefined  |      at build/product/newbuild/webpack/node_modules/tapable/lib/Tapable.js:75:19)  |      at Object.tryCatcher build/product/newbuild/webpack/node_modules/bluebird/js/main/util.js:26:23)  |      at ret (eval at  build/product/newbuild/webpack/node_modules/bluebird/js/main/promisify.js:163:12), :13:39)  |      at build/product/newbuild/webpack/node_modules/html-webpack-plugin/index.js:642:12  |      at build/product/newbuild/webpack/node_modules/html-webpack-plugin/index.js:192:16  |      at tryCatcher build/product/newbuild/webpack/node_modules/bluebird/js/main/util.js:26:23)  |      at build/product/newbuild/webpack/node_modules/bluebird/js/main/promise.js:510:31)  |      at build/product/newbuild/webpack/node_modules/bluebird/js/main/promise.js:584:18)  |      at build/product/newbuild/webpack/node_modules/bluebird/js/main/promise.js:700:14)  |      at build/product/newbuild/webpack/node_modules/bluebird/js/main/async.js:123:16)  |      at build/product/newbuild/webpack/node_modules/bluebird/js/main/async.js:133:10)  |      at build/product/newbuild/webpack/node_modules/bluebird/js/main/async.js:15:14)  |      at tryOnImmediate (timers.js:543:15)  |      at processImm

Could you help me to solve this issue (fails on debian - ok on xubuntu)

**Comment by jantimon** [comment]
Could you please post your webpack plugin and loader versions and their configuration?
