### ISSUE TITLE
Caching and Adding Cached index.html to `compilation.assets`

### ISSUE THREAD

**Issue by destroyerofbuilds** [jantimon/html-webpack-plugin#592]
I'm using `html-webpack-plugin` alongside [webpack-cleanup-plugin](https://www.npmjs.com/package/webpack-cleanup-plugin).

The latter, `webpack-cleanup-plugin`, removes files from the build artifact directory not emitted by Webpack.

When running `webpack --watch`, the contents of my application, and my application's `index.html` file, are written to my project's build artifact directory, `dist/`.

While `webpack --watch` is running, I'll modify one of the JavaScript files comprising my application. 

`webpack --watch` detects the file change, rebuilds my application file, and re-writes it to disk.

Because the name of my application file has not changed (I'm not building in production mode, `-p`, so no hash in the file name), `html-webpack-plugin` will see that the list of assets has not changed, and [will return early](https://github.com/jantimon/html-webpack-plugin/blob/2d5c42ff18985958b4991eaac615ec9ac467715f/index.js#L86), never adding anything to the `compilation.assets` array.

Once all files have been written to disk `webpack-cleanup-plugin` [fetches the list of assets](https://github.com/gpbl/webpack-cleanup-plugin/blob/09718e5c2fd28b12e0321209e441105d24442f0a/src/WebpackCleanupPlugin.js#L22), `stats.toJson().assets`.

Missing from that list is the compiled `index.html` file from `html-webpack-plugin`, because the file was never added to the `assets` array.

Therefore, `webpack-cleanup-plugin` will see `index.html` in the build artifact directory, but not in the assets list, and will remove `index.html` from disk.

**Comment by destroyerofbuilds** [comment]
Would it be acceptable to cache the compiled `index.html` file and, if no other assets have changed, add the previously compiled `index.html` file to the `compilation.assets` array?

**Comment by jantimon** [comment]
You can just turn of the cache

**Comment by destroyerofbuilds** [comment]
@jantimon that is actually what I'm doing now; disabling cache for `html-webpack-plugin`.

I was concerned about the implications to incremental build performance when turning off caching.

**Comment by jantimon** [comment]
👍  if you need more speed check out the webpack dev server instead of webpack --watch
