### ISSUE TITLE
pass variable require html

### ISSUE THREAD

**Issue by liuliangsir** [jantimon/html-webpack-plugin#593]
I encounter this issue, header.html <%= htmlWebpackPlugin.options.title %> not work
so i would like to pass `htmlWebpackPlugin` variable when require('html-loader!../footer/index.html')

project structure 

![image](https://cloud.githubusercontent.com/assets/8049878/22923034/d03b0214-f2da-11e6-9786-483029e461cc.png)

project code

![image](https://cloud.githubusercontent.com/assets/8049878/22922828/28f9bdc4-f2da-11e6-89b2-a4fe807897c0.png)

![image](https://cloud.githubusercontent.com/assets/8049878/22923392/4b59a90e-f2dc-11e6-852c-fbdea97ff37a.png)

look forward to reply

**Comment by jantimon** [comment]
Sounds like a configuration problem please read the faq

**Comment by liuliangsir** [comment]
@jantimon I has read the faq many times,
But i still has found out the cause of issue
My idea as it follows
html-webpack-plugin is used for html template
then pass htmlWebpackPlugin variable in html template
When you use 
```
<%= require('../footer/index.html') %>
```
code
It tells us you use html-loader
Sadly,html loader seems don't provide interface of passing htmlWebpackPlugin variable
If you would like to using htmlWebpackPlugin variable in `../footer/index.html` html template
You ought to use following code snippet
```
    new HtmlWebpackPlugin({
      inject: false,
      filename: 'contact/index.html',
      chunks: ['vendors', 'mainfest'],
      template: common.footerHtml,
      chunksSortMode: 'none'
    })
```
If we do that
But we can't assure that `htmlWebpackPlugin variable`(in footer/index.html template) is same as `htmlWebpackPlugin variable`(in html template which require  footer/index.html template)
look forward to reply

**Comment by jantimon** [comment]
@liuliangsir sorry you are absolutely correct - it is just that the html-loader does not allow to use template variables. See https://github.com/webpack-contrib/html-loader for details

**Comment by liuliangsir** [comment]
@jantimon thx~
