### ISSUE TITLE
HtmlWebpackPlugin Error: TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by ltwaia** [jantimon/html-webpack-plugin#596]
- ExternalModuleFactoryPlugin.js:37 handleExternals
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:33
  
  - ExternalModuleFactoryPlugin.js:46 next
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8
  
  - ExternalModuleFactoryPlugin.js:59 handleExternals
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7
  
  - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5
  
  - NormalModuleFactory.js:233 
    [lib]/[webpack]/lib/NormalModuleFactory.js:233:3
  
  - Tapable.js:196 NormalModuleFactory.applyPluginsAsyncWaterfall
    [lib]/[webpack]/[tapable]/lib/Tapable.js:196:70
  
  - NormalModuleFactory.js:217 NormalModuleFactory.create
    [lib]/[webpack]/lib/NormalModuleFactory.js:217:8
  
  - Compilation.js:377 Compilation._addModuleChain
    [lib]/[webpack]/lib/Compilation.js:377:17
  
  - Compilation.js:455 Compilation.addEntry
    [lib]/[webpack]/lib/Compilation.js:455:8
  
  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [webpack-demos]/[webpack]/lib/SingleEntryPlugin.js:22:15
  
  - Tapable.js:229 Compiler.applyPluginsParallel
    [lib]/[webpack]/[tapable]/lib/Tapable.js:229:14
  
  - Compiler.js:469 
    [lib]/[webpack]/lib/Compiler.js:469:8
  
  - Tapable.js:131 Compiler.applyPluginsAsyncSeries
    [lib]/[webpack]/[tapable]/lib/Tapable.js:131:46
  
  - Compiler.js:462 Compiler.compile
    [lib]/[webpack]/lib/Compiler.js:462:7
  
  - Compiler.js:266 Compiler.runAsChild
    [lib]/[webpack]/lib/Compiler.js:266:7
  
  - compiler.js:70 
    [webpack-demos]/[html-webpack-plugin]/lib/compiler.js:70:19

**Comment by ltwaia** [comment]
- ExternalModuleFactoryPlugin.js:37 handleExternals
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:33
  
  - ExternalModuleFactoryPlugin.js:46 next
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8
  
  - ExternalModuleFactoryPlugin.js:59 handleExternals
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7
  
  - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
    [webpack-demos]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5
  
  - NormalModuleFactory.js:233 
    [lib]/[webpack]/lib/NormalModuleFactory.js:233:3
  
  - Tapable.js:196 NormalModuleFactory.applyPluginsAsyncWaterfall
    [lib]/[webpack]/[tapable]/lib/Tapable.js:196:70
  
  - NormalModuleFactory.js:217 NormalModuleFactory.create
    [lib]/[webpack]/lib/NormalModuleFactory.js:217:8
  
  - Compilation.js:377 Compilation._addModuleChain
    [lib]/[webpack]/lib/Compilation.js:377:17
  
  - Compilation.js:455 Compilation.addEntry
    [lib]/[webpack]/lib/Compilation.js:455:8
  
  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [webpack-demos]/[webpack]/lib/SingleEntryPlugin.js:22:15
  
  - Tapable.js:229 Compiler.applyPluginsParallel
    [lib]/[webpack]/[tapable]/lib/Tapable.js:229:14
  
  - Compiler.js:469 
    [lib]/[webpack]/lib/Compiler.js:469:8
  
  - Tapable.js:131 Compiler.applyPluginsAsyncSeries
    [lib]/[webpack]/[tapable]/lib/Tapable.js:131:46
  
  - Compiler.js:462 Compiler.compile
    [lib]/[webpack]/lib/Compiler.js:462:7
  
  - Compiler.js:266 Compiler.runAsChild
    [lib]/[webpack]/lib/Compiler.js:266:7
  
  - compiler.js:70 
    [webpack-demos]/[html-webpack-plugin]/lib/compiler.js:70:19

**Comment by ltwaia** [comment]
cli webpack version is not fit for require webpack

**Comment by wupengFEX** [comment]
@ltwaia  How to solve it?

**Comment by whitetrefoil** [comment]
@wupengFEX I just met the same error and remove `node_modules/` then re-install it did help.

**Comment by huangyunbo** [comment]
@wupengFEX Ensure project file package.json webpack version "^2.x"

把项目里的packckage.json webpack指定版本换成最新的或者2.x或者2.4.1，再重新npm install webpack --save
