### ISSUE TITLE
Is it possible to pass custom locals when using pug?

### ISSUE THREAD

**Issue by szimek** [jantimon/html-webpack-plugin#597]
`pug-loader` only returns a function that one has to call (optionally passing `locals` object) to get the actual HTML. This means, I can't pass locals to `pug-loader` directly. I can pass custom options to `html-webpack-plugin` that will be available in templates, but they are all available as `htmlWebpackPlugin.<something>`. I'd like to share some templates (partials actually) between apps and thus was wondering it it's possible to somehow pass values, so that they can be available in pug templates as whatever I set, e.g. `config.<something>` instead of `htmlWebpackPlugin.<something>`. 

Is it somehow possible?

**Comment by jantimon** [comment]
Yes the locals are used here: https://github.com/jantimon/html-webpack-plugin/blob/2d5c42ff18985958b4991eaac615ec9ac467715f/index.js#L264

**Comment by szimek** [comment]
@jantimon But it means that all params I pass will always be available via `htmlWebpackPlugin` object and there's no way to change it, right?

Instead of this:
``` js
var templateParams = {
  htmlWebpackPlugin: {
    files: assets,
    options: self.options
  }
};
```
I'd need this (using spread object syntax)
```js
var templateParams = {
  ...self.options.locals,
  htmlWebpackPlugin: {
    files: assets,
    options: self.options
  }
};
```
so that if `locals` is e.g. `{ config: { foo: 1 } }`, I can use `config.foo` in my template directly. I guess it might be dangerous, because it would allow one to overwrite other properties...

**Comment by jantimon** [comment]
You could do a small wrapper around your template:

```template.js
var template = require('template.pug');
module.exports = function(templateParams) {
  return template(templateParams.htmlWebpackPlugin.options);
};
```

**Comment by szimek** [comment]
Thanks! Really cool and simple idea :)
