### ISSUE TITLE
Chunk with a smaller id should be last, this is opposite of what OccurrenceOrderPlugin do ?

### ISSUE THREAD

**Issue by liangklfangl** [jantimon/html-webpack-plugin#598]
It is easy to understand that entry chunks should be ascending order， but , i do not know why chunks with smaller id should be last. This is just opposite of OccurrenceOrderPlugin do ? Can you give me some information ?

**Comment by liangklfangl** [comment]
`module.exports.id = function (chunks) {
  return chunks.sort(function orderEntryLast (a, b) {
    if (a.entry !== b.entry) {
      return b.entry ? 1 : -1;
    } else {
      return b.id - a.id;
    }
  });
};`

**Comment by jantimon** [comment]
That's how webpack 1 used to work .. it's really old code
