### ISSUE TITLE
Conflict: Multiple assets emit to the same filename index.html

### ISSUE THREAD

**Issue by mistic** [jantimon/html-webpack-plugin#599]
Hey guys,

Are you having problems in using html webpack plugin with webpack.optimize.AggressiveSplittingPlugin ? 

Using the 2 plugins at the same time I'm having this error:

`ERROR in   Error: Child compilation failed:
  Conflict: Multiple assets emit to the same filename index.html:
  Error: Conflict: Multiple assets emit to the same filename index.html`

Thanks in advance

**Comment by bruno-serfe** [comment]
Same issue here.

**Comment by jamessharp** [comment]
I have a fix that is doing the job for me here: https://github.com/ortoo/html-webpack-plugin/commit/6d9996d8bd143d5026d63c78d91cd8d0c920c058 (see my comment [here](https://github.com/jantimon/html-webpack-plugin/issues/446#issuecomment-293894911) for more details)

**Comment by mastilver** [comment]
Closing as a duplicate of #446
