### ISSUE TITLE
Move <link> tags to the bottom of the paga (end of body)

### ISSUE THREAD

**Issue by thomaspink** [jantimon/html-webpack-plugin#605]
As described in the documentation, css included with ExtractTextPlugin will be placed into the head tag:
> If you have any CSS assets in webpack's output (for example, CSS extracted with the ExtractTextPlugin) then these will be included with <link> tags in the HTML head.

Is there a way to move this tag to the body (end)?

Usecase:
I have two css files. The first one will be inlined in the head (using the StyleExtHtmlWebpackPlugin). The second one should be at the end of the body.

**Comment by jantimon** [comment]
@numical  Could we please move this over to the StyleExtHtmlWebpackPlugin ?
The StyleExtHtmlWebpackPlugin has all the knowledge about the inlining and can sort the css files inside the hooks which are provided by the html-webpack-plugin

**Comment by thomaspink** [comment]
@jantimon jep i can create it there, but for clarification: StyleExtHtmlWebpackPlugin ist just responsible for inlining, but from my understanding, this does not solve the issue that <link> tags are always in the head and can not be moved to the body?

**Comment by numical** [comment]
@jantimon : did you see [my question](https://github.com/numical/script-ext-html-webpack-plugin/issues/6#issuecomment-280704294) to you regarding this issue?

**Comment by jantimon** [comment]
@thomaspink the StyleExtHtmlWebpackPlugin is able to sort the links
@numical I don't understand the current state - maybe we could have a short chat on this soon?

**Comment by thomaspink** [comment]
Closed because of new issue in StyleExtHtmlWebpackPlugin repo
