### ISSUE TITLE
How to add <meta> in index.html

### ISSUE THREAD

**Issue by jsspace** [jantimon/html-webpack-plugin#606]
How to add <meta> in index.html

**Comment by xtuc** [comment]
More context would be welcome. I would recommend you using a template. See the corresponding [documentation](https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md).

**Comment by mastilver** [comment]
You can provide your own html template: https://github.com/jantimon/html-webpack-plugin#configuration

For example:

`index.html`
```html
<!DOCTYPE html>
<html>
    <head>
        <title>My app</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
    </body>
</html>
```

in `webpack.config.js`
```js
new HtmlWebpackPlugin({
  template: './index.html'
}),
```
