### ISSUE TITLE
Add link to add-asset-html-webpack-plugin

### ISSUE THREAD

**Issue by gamtiq** [jantimon/html-webpack-plugin#608]
It would be useful to add link to [add-asset-html-webpack-plugin](https://github.com/simenb/add-asset-html-webpack-plugin) into [list of addons](https://github.com/jantimon/html-webpack-plugin#third-party-addons).

**Comment by jharris4** [comment]
This plugin is very similar to the [https://github.com/jharris4/html-webpack-include-assets-plugin](html-webpack-include-assets-plugin) which is already linked in the list of addons.

An issue was just created for us to combine forces:

https://github.com/jharris4/html-webpack-include-assets-plugin/issues/4

**Comment by mastilver** [comment]
I prefer yours @jharris4  (I find the API nicer), but I don't thing it hurts to add the other one ;)
