### ISSUE TITLE
How to provide a model the html loader?

### ISSUE THREAD

**Issue by worldspawn** [jantimon/html-webpack-plugin#609]
Hey,

is there a way to provide a view model to the template? I've checked two of the listed loader options and neither provide a way to just inline a viewmodel. The html-loader doesn't provide this option at all and handlebars-loader is expecting the user to do `require('template.hbs')(model)` which i can't seem to do in this scenario.

**Comment by jantimon** [comment]
The model is already passed to the template:

https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates

**Comment by ahc-andrew** [comment]
How is this performed? I want to add my own things to the template

**Comment by Isk1n** [comment]
Webpack config:
```javascript
new HtmlWebpackPlugin({
  filename: 'index.html',
  title: 'Document title',
  template: path.resolve(__dirname, 'template.hbs'),
  myThings: things
});
```
Template:
```hbs
<html>
<head>
  <title>{{htmlWebpackPlugin.options.title}}</title>
</head>
<body class="{{htmlWebpackPlugin.options.myThings}}">
</body>
</html>
```
@ahc-andrew , is this what you were looking for?
