### ISSUE TITLE
Is there a way to ignore publicPath for some assets?

### ISSUE THREAD

**Issue by mastilver** [jantimon/html-webpack-plugin#613]
Every assets is prepends with the `publicPath`, is there a way to tell `html-webpack-plugin` not to add the `publicPath` for some assets especially when those are urls

Related issue: https://github.com/mmiller42/html-webpack-externals-plugin/issues/2

**Comment by jantimon** [comment]
Hmm sounds interesting - I'll have to look into that. It might be a feature for version 3.x

**Comment by mastilver** [comment]
@jantimon Let me know if I can do anything?

Maybe you can give me some pointers to start a PR?

**Comment by japgolly** [comment]
I'm stuck on this too, it's preventing me from being able to use CDN URLs.

Relevant bits:
```js
const HtmlExternalsPlugin = require('html-webpack-externals-plugin');

    output: {
        publicPath: '/prod/',
    },

        new HtmlExternalsPlugin([
            { name: "react", var: "React", url: "https://unpkg.com/react@15.4.2/dist/react.js" },
            { name: "react-dom", var: "ReactDOM", url: "https://unpkg.com/react-dom@15.4.2/dist/react-dom.js" },
        ])

```
and what I'm seeing in my output HMTL is:
```html
<script type="text/javascript" src="/prod/https://unpkg.com/react@15.4.2/dist/react.js"></script>
<script type="text/javascript" src="/prod/https://unpkg.com/react-dom@15.4.2/dist/react-dom.js"></script>
```

**Comment by TheoMer** [comment]
I'm experiencing exactly this issue. The output file is being placed exactly in the correct place, but the specified url in the included script file to be different.

So my webpack is as follows:

```
  output: {
    path: path.join(__dirname, '/public'),
    filename: '[name]-[hash].js',
    publicPath: '/public/'
  },
  new HtmlWebpackPlugin({
    filename: 'index.html',
    template: './index_template.html'
  })
```
but I want the included script file address, in index.html. to be

```
<script type="text/javascript" src="/xxxxxxx.js"></script>
```

How can I achieve this?

P.S.

A setting that would allow something like the following would work

```
  new HtmlWebpackPlugin({
    ......
    stripPrefix: path.join(__dirname, 'public').replace(/\\/g,"/"),
  })

**Comment by mastilver** [comment]
I'm closing this down as I don't see this being added to `html-webpack-plugin`

The way I solved this was to use: https://github.com/jharris4/html-webpack-include-assets-plugin
example: https://github.com/mastilver/modules-cdn-webpack-plugin/blob/master/src/index.js#L121-L143
