### ISSUE TITLE
How to put / in front of the bundle file

### ISSUE THREAD

**Issue by jeud** [jantimon/html-webpack-plugin#614]
Dear all

I'm using very simple `html-webpack-plugin` setup

```js
module.exports = {
    ...
    plugins: [
        new HtmlPlugin({
            template: './template.html'
        })
    ]
}
```
The output HTML `<script>` is: `<script type="text/javascript" src="ab56bd038d9a7da68390.bundle.js"></script>`

Is it possible to have output HTML `<script>` to `<script type="text/javascript" src="/ab56bd038d9a7da68390.bundle.js"></script>` (`/` in front of the bundle file) because without `/` I have a problem when using with `react-router` e.g. when the URL was `http://localhost:8080/customers/101` the browser will look for `/customers/ab56bd038d9a7da68390.bundle.js` instead of `/ab56bd038d9a7da68390.bundle.js`

Please guide thanks

**Comment by mastilver** [comment]
```js
module.exports = {
    ...
    output: {
        publicPath: '/',
        ...
    },
    plugins: [
        new HtmlPlugin({
            template: './template.html'
        })
    ]
}
```
