### ISSUE TITLE
Allow results of `html-webpack-plugin-alter-asset-tags` to work beyond `inject: true` option

### ISSUE THREAD

**Issue by naganowl** [jantimon/html-webpack-plugin#616]
I'm using https://github.com/DustinJackson/html-webpack-inline-source-plugin and noticed that the results of it will only work if `inject` is set to `true` because `postProcessHtml ` discards the results returned from the event when `inject` is `false`  (https://github.com/jantimon/html-webpack-plugin/blob/b8fd1427bc7714f0b37e1ef8ed9e4477a7bbafcd/index.js#L289).

I'd propose that the replacement logic in `injectAssetsIntoHtml` should be applied to `head` and `body` of `results` (https://github.com/jantimon/html-webpack-plugin/blob/b8fd1427bc7714f0b37e1ef8ed9e4477a7bbafcd/index.js#L154) and then exposed on `htmlWebpackPlugin` or anything else that is accessible via the `template` option.

Doing so would allow templates the flexibility of selecting the entry/chunks it needs and still being able to leverage modifications (such as the inline plugin).

**Comment by mastilver** [comment]
If you are already using a template, you can follow that example to inline your code: https://github.com/jantimon/html-webpack-plugin/blob/master/examples/inline/template.jade

**Comment by tangpo** [comment]
I have wrote a plugin called "html-webpack-simple-inlinesource-plugin".  you can try it.
