### ISSUE TITLE
Assets are not available in template processor context when using custom template processor

### ISSUE THREAD

**Issue by airtonix** [jantimon/html-webpack-plugin#617]
When you choose not to use `inject:true`, you'd opt to iterate over `htmlWebpackPlugin.assets` and manually insert them into your template.

However, when your templates are `swig` this is not possible because that template variable is not available.

I tried making a plugin that responds to the `htmlWebpackPlugin` events, but the html generated from the initial build resulted in an empty `htmlWebpackPlugin` variable.

**Comment by jantimon** [comment]
Could you please explain why swig won't allow to use variables in a template function?
