### ISSUE TITLE
FreeMarker template engine ReferenceError

### ISSUE THREAD

**Issue by SweetsXob** [jantimon/html-webpack-plugin#621]
template.ftl (FreeMarker template engine) page has an output variable ${outputValue}
Run the webpack prompt "ERROR in Template execution failed: ReferenceError: outputValue is not defined"

**Comment by mastilver** [comment]
Are you still having that error?

If so can you give us your `template.ftl`, `webpack.config.js` and the error stack trace

**Comment by SweetsXob** [comment]
### index.ftl
`<!DOCTYPE html>
<html>
<head>
    <title>index</title>
</head>
<body>
   this is FreeMarker template engine,
   Read data from server -- ${outputValue}
</body>
</html>`

### webpack.config.js
`var webpack = require("webpack");
var HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
    entry: {
        index: "./dev/zpdj/js/index.js"
    },
    output: {
        path: __dirname,
        filename: "built/zpdj/js/[name].js"
    },
    module: {
        loaders: [
            {
                test: /\.json$/,
                loader: "json-loader"
            },
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader'
            },
            {
                test: /\.css$/,
                loader: 'css-loader!postcss-loader'
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            filename: "./html2/index.ftl",
            template: "./html/index.ftl"
        }),
    ]
}`

### error stack trace
`built/zpdj/js/index.js  2.95 kB       0  [emitted]  index
     ./html2/index.ftl  1.07 kB          [emitted]
   [0] ./dev/zpdj/js/index.js 295 bytes {0} [built]

ERROR in Template execution failed: ReferenceError: outputValue is not defined

ERROR in   ReferenceError: outputValue is not defined

  - index.ftl:17224
    D:/Projects/Projects.Solution/SweetsXob/SweetsXob.Test/zhongpu/html/index.ftl:17224:10

  - index.ftl:17227 module.exports
    D:/Projects/Projects.Solution/SweetsXob/SweetsXob.Test/zhongpu/html/index.ftl:17227:3

  - index.js:265
    [zhongpu]/[html-webpack-plugin]/index.js:265:16

  - util.js:16 tryCatcher
    [zhongpu]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [zhongpu]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [zhongpu]/[bluebird]/js/release/promise.js:569:18

  - promise.js:606 Promise._settlePromiseCtx
    [zhongpu]/[bluebird]/js/release/promise.js:606:10

  - async.js:138 Async._drainQueue
    [zhongpu]/[bluebird]/js/release/async.js:138:12

  - async.js:143 Async._drainQueues
    [zhongpu]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues
    [zhongpu]/[bluebird]/js/release/async.js:17:14`

Thanks for your help

**Comment by mastilver** [comment]
So `outputValue` is dynamic / coming from the server, you don't want `html-webpack-plugin` to change it.

I can see two solutions (I think the second one is better):
- use `html-loader` instead of `ejs-loader`:
```
{
  test: /\.ftl$/,
  loader: "html-loader"
},
```

- escape `outputValue`: `${outputValue}` -> `<%= "\\${outputValue}\\>" %>`

**Comment by SweetsXob** [comment]
Thank you very much for the perfect solution

**Comment by jdbranham** [comment]
Thanks @mastilver 

In my case, this rendered output -
    <meta name="keywords" content="${keywords}"></meta>

was correctly defined in the source as this - 
    <meta name="keywords" content="<%= '\${keywords}' %>"></meta>
