### ISSUE TITLE
Can css ,js be injected to different template?

### ISSUE THREAD

**Issue by aboutqx** [jantimon/html-webpack-plugin#623]
So `header.html`,`footer.html` which reference css,js each can be required in a hole html file,and that html doesn't needed to be updated when using hash,
we can just replace the `header.html` and `footer.html` and then the hole html assets get updated.

**Comment by mastilver** [comment]
You can do it like that:

```
new HtmlWebpackPlugin({
  chunks: ['css'],
  filename: 'header.html',
  template: 'header.ejs'
}),
new HtmlWebpackPlugin({
  chunks: ['app'],
  filename: 'footer.html',
  template: 'footer.ejs'
})
```

you just need to create two `.ejs` template (or any other template engine) for the footer and the header and you are done

-----
https://github.com/jantimon/html-webpack-plugin#generating-multiple-html-files
https://github.com/jantimon/html-webpack-plugin#filtering-chunks
