### ISSUE TITLE
I want to import files in different locations， how to use inject  ???

### ISSUE THREAD

**Issue by zhe-he** [jantimon/html-webpack-plugin#624]
```
new HtmlWebpackPlugin({
		filename: 'dist/index.html',
		template: 'src/index.html',
		inject: "body",
		chunks: ['common','index']
	});
```
it will be: 
```
<head></head>
<body>
    <script src="common.js"></script>
    <script src="index.js"></script>
</body>
```

How to use `inject` can be as follows   ->
```
<head>
    <script src="common.js"></script>
</head>
<body>
    <script src="index.js"></script>
</body>
```

**Comment by Squidies** [comment]
+1

**Comment by mastilver** [comment]
Did you try by using a custom template?

**Comment by Squidies** [comment]
@mastilver 

For my purposes, I found an alternative for what I wanted to accomplish, but to your comment; I'm using `pug-loader` for my templating. I saw the section for adding template section for `.ejs` files, but couldn't find anything on implementing these with other templating loaders. Is the syntax the same regardless of the templating used?

(apologies if im high jacking this thread. i just happened to be looking for this exact question nearly the same time OP posted it)

**Comment by mastilver** [comment]
@Squidies Looks there: https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md

As long as you have the `pug` loader setup and you are using the right extension, it should work

@Squidies Make sure to share your result, so you can help @zhe-he in the meantime ;)

**Comment by zhe-he** [comment]
To be honest, I have not used a custom template.
So, maybe, if you have a solution to the method, can you give me an example, not very grateful.
@Squidies

**Comment by Squidies** [comment]
Thanks @mastilver, I'd taken a look at that, but could only find examples for `.ejs` files with `<%= htmlWebpackPlugin.options.title %>` as an example. I wasn't sure if this syntax would also work with `pug-loader`

Unfortunately I don't think my specific situation will apply. For my situation I was trying to load a custom build for modernizr, but ended up using the `modernizr-webpack-plugin` for my needs.

@zhe-he, check out the link @mastilver provided along with 

https://github.com/jantimon/html-webpack-plugin/tree/master/examples/custom-template

In particular the template.html file. That might be a way to accomplish what you're trying to do.

**Comment by zhe-he** [comment]
@Squidies  I may have seen the fake example, it can not help me.
I only need to be in the template page header and body custom insert javascript. There is no variable inside the template.  /cry.

**Comment by jantimon** [comment]
It won't work with inject - you would have to write a real template.
There are variables available to achieve that

**Comment by mikegrima** [comment]
@jantimon Can you provide an example of a template that would do this?

I have the same use case, where I want to have one bundle located in `<head>`, and another located in `<body>`. I mostly want to leverage the cache-busting capability.

FWIW: I am also not able to get the Title example working. The rendered HTML shows: `<title><%= htmlWebpackPlugin.options.title %></title>`.

**Comment by DmitryGonchar** [comment]
@jantimon 
> There are variables available to achieve that

How to get/provide chunk file name with hash in these variables? From what I know, it is available only after webpack compilation. The closest solution I found is [this one.](https://github.com/webpack/webpack/issues/86#issuecomment-179957661)

But writing your own plugin seems to be an overkill. Imho, it would be much better that such option existed in this plugin. You use `compilation.getStats()` anyway, so why not just put some into the <head> if such option (`headChunks: ['chunkName']` ) is provided?
