### ISSUE TITLE
Link css inside template

### ISSUE THREAD

**Issue by davidanaya** [jantimon/html-webpack-plugin#627]
Hi,

I'm sorry this is probably a very basic question but I've been a while searching in the documentation and issues and I can´t figure out how to do this.

I just have a basic template where I want to import a css file already created, so my template looks like this:

```
<html>
<head>
    <base href="/">
    <link rel="stylesheet" href="/css/styles.css">
</head>
<body>
    <my-app></my-app>
</body>
</html>
```

And my webpack config

```
new HtmlWebpackPlugin({
      template: 'src/index.html'
})

```
Now when I build the project my styles.css is not inside my /dist folder and so the import fails.

Why is the styles.css not inside the /dist? I thought webpack would copy all referenced files inside the distribution folder. What am I missing?

Thanks

**Comment by jantimon** [comment]
There is a copy plugin for webpack which copies those files for you

Could you please move questions concerning the usage of the plugin to stackoverflow and add a backlink to this thread?
