### ISSUE TITLE
How to add dynamic react routes load at html

### ISSUE THREAD

**Issue by alexfqc** [jantimon/html-webpack-plugin#629]
I am using react dynamic routes:

```
<Route
      path="/"
      getComponent={(location, cb) => {
        System.import('./App')
              .then(loadRoute(cb))
              .catch(errorLoading);
      }}
 />
```

I have only one entry point at webpack:

```
context: path.resolve(__dirname),
  entry: {
    app: './assets/js/components/index',
  },
```

and webpack is generating each app.js and one file for each route.
<img width="393" alt="screenshot 2017-03-29 21 54 58" src="https://cloud.githubusercontent.com/assets/1999012/24482846/9d19aacc-14ca-11e7-9722-6c278daab172.png">

But my generated html file does not have the import for these js files.

Is there some setup for this?

**Comment by jantimon** [comment]
Could you please move questions concerning the usage of the plugin to stackoverflow and add a backlink to this thread?

**Comment by alexfqc** [comment]
Ok. Thanks
