### ISSUE TITLE
Multi partial view with html-loader interpolation

### ISSUE THREAD

**Issue by ng-hai** [jantimon/html-webpack-plugin#630]
I have a template like this

```
<head>
    <title>
        <%= htmlWebpackPlugin.options.title %>
    </title>
</head>

<body>
    <header></header>
    <nav></nav>

    <!-- Here I user html-loader for injecting partial view -->
    ${require('somePartialView.html')}

    <footer></footer>
</body>
```
And some partial view like 'About', 'Products' ...

How can I dynamically change `somePartialView.html` into About or Product view without copy the template for each one of them because it's hard to maintain every template if customer's requirement changed?

I have tried some method like

`${require(<%= htmlWebpackPlugin.options.title %> + '.html')}`

or 

`${require(<%= htmlWebpackPlugin.options.filename %>)}`

but ES6 template string cannot handle.

Is there another way to resolve this problem?

**Comment by ng-hai** [comment]
Oops, just create new issue and find the answer immediately. Here how I fixed:

'<%= require('../pages/homepage/'+htmlWebpackPlugin.options.filename) %>'

**Comment by ng-hai** [comment]
I have to reopen this since `require` in `<%= %>` expression not working anymore because of an error

`Critical dependency: the request of a dependency is an expression.'

**Comment by jantimon** [comment]
Afaik Webpack doesn't support dynamic requires - sorry :/

**Comment by ng-hai** [comment]
Last questions

1. What process will be invoked first, `require` or `ejs` expression?
2. Why not use HTML interpolation like `html-loader` but `ejs`, `handlebars`...
