### ISSUE TITLE
Interaction with ts-loader

### ISSUE THREAD

**Issue by Rendalf** [jantimon/html-webpack-plugin#631]
I was trying to use typescript with `ts-loader` for templates.
It seems like `html-webpack-plugin` is unable to reuse instance of `ts-loader` created by webpack it self and creates new instance each time when it compiles/recompiles.

I understand it next way:
1. On start of build I see `ts-loader`s message two times:
> ts-loader: Using typescript@2.2.1 and /Users/artemlipatov/projects/tangle-fe/src/tsconfig.json
> ts-loader: Using typescript@2.2.1 and /Users/artemlipatov/projects/tangle-fe/src/tsconfig.json
2. Each incremental rebuild I see this message one more time.

What may cause this behaviour? Is it caused by webpack or html-plugin? Is there any possibility to reuse `ts-loader` instances? Maybe is it issue of `ts-loader` itself?

Thanks in advance for your answers.

**Comment by jantimon** [comment]
Last time I checked the ts-loader is a big workaround and will probably not allow to be used in child compilers
