### ISSUE TITLE
Is there any way to pass a variable to require()

### ISSUE THREAD

**Issue by mahcr** [jantimon/html-webpack-plugin#633]
I'm using EJS and I was trying to pass a variable to the require function. But it does not work. 

e.g
```
<body>
  <% const data = htmlWebpackPlugin.options; %>
  <img src="<%- require(data.img) %>" />
</body>
```
The terminal throws this error `39:163-180 Critical dependency: the request of a dependency is an expression`

If a use a string it works fine.

Is there anyway to make this work?

**Comment by mastilver** [comment]
Not sure if the following works but you could try:
- set `html-loader` and `ejs-loader` (in that order) for `.ejs` files

Use the follpwing: `index.ejs`

```
<body>
  <% const data = htmlWebpackPlugin.options; %>
  <img src="<%- data.img %>" />
</body>
```

-----
see: https://github.com/webpack-contrib/html-loader#examples

**Comment by mahcr** [comment]
@mastilver Yeah I have tried that, it works, but there are two issues with this approach: 
- The hash is not being added to the images
- Images are not copied to the output folder.

**Comment by mastilver** [comment]
hum..., not sure I can help much...

You do have the a 'file-loader' for the extension you are using (png, jpeg...), right?

Can you share your input ejs and your webpack config
Also, one thing that could be interesting, remove the `html-loader`, run webpack and give us the file outputted by `ejs-loader`

**Comment by mastilver** [comment]
Closing for now as I assume you fixed it yourself

If you still have this issue, feels free to reopen it!
Also stackoverflow is a good place for this kind of question
