### ISSUE TITLE
No starting slash '/' when using webpack 2

### ISSUE THREAD

**Issue by laruiss** [jantimon/html-webpack-plugin#635]
Hello, I need this plugin, but when I use it in webpack 2, the generated script tag is of the form:

```html
<script type="text/javascript" src="static/js/bundle.js"></script>
```

instead of:

```html
<script type="text/javascript" src="/static/js/bundle.js"></script>
```

Note: with the same plugin options, it works as expected in Webpack 1.

Here are the relevant parts of webpack conf:

```javascript
  entry: [
    paths.appIndexJs,
    publicPath,
  ],
  output: {
    pathinfo: true,
    path: paths.appBuild,
    filename: 'static/js/bundle.js',
  },

  // (...)

  plugins: [
    new HtmlWebpackPlugin({
      inject: true,
      template: paths.appHtml,
    }),
```

What am I doing wrong?

**Comment by laruiss** [comment]
I added output.publicPath = '/' and it was OK, I think it would be nice to have this in the examples and/or doc...

**Comment by zcoding** [comment]
so why i have to set output.publicPath: '/' ?
