### ISSUE TITLE
Replace file.[chunkhash] to 'src' attribute of tag <script>

### ISSUE THREAD

**Issue by bigz3ro** [jantimon/html-webpack-plugin#636]
```
<html lang="vi">`
	<head>
		<meta charset="utf-8"/>
	</head>
	<body>
		<div id="app"></div>
		<script async id="main-script"></script>
		<script type="text/javascript">
			document.getElementById("main-script").src =  
'/'+window.location.href.split('://')[1].split('/')[1]+'/app.js';
		</script>
	</body>
</html>
```
I have this code html. I want to build it use html-webpack-plugin that it will remove files bundle above and replace link to new file bundle:
```
document.getElementById("main-script").src =  
'/'+window.location.href.split('://')[1].split('/')[1]+'/app.js';
```
to
```
document.getElementById("main-script").src = 
'/'+window.location.href.split('://')[1].split('/')[1]+'file.[chunkhash].js';
```
Sorry . I don't use English good.Thanks

**Comment by mastilver** [comment]
Can you give use your webpack config?

It looks like you are using this plugin in a wrong way

**Comment by bigz3ro** [comment]
Can you suggest me a plugin? My pupore is that every time run build is done, the browser will re-download this bundle.

**Comment by mastilver** [comment]
This plugin is the one you want to use!

just add, in your webpack config:

```js
output: {
    filename: '[name].[chunkhash].js'
},
```

remove all your scripts in the `index.html`
