### ISSUE TITLE
Update script type from text/javascript to application/javascript

### ISSUE THREAD

**Issue by MrEcko** [jantimon/html-webpack-plugin#645]
**Context**
Current version (2.28.0) sets the type of the script tag to 'text/javascript'.

**Problem**
'text/javascript' is obsolete and it should be updated to 'application/javascript'

**Solution**
Update the the type of the script tag from 'text/javascript' to 'application/javascript' .

Raised Pull Request for it : https://github.com/jantimon/html-webpack-plugin/pull/646

Initially thought it caused the script not to be loaded on browsers which enforce strict MIME type checking (ex. chrome). However the issue may lie somewhere else for me - server's probably setting the wrong header.
Nevertheless, still came across this in an effort to solve my issue.

**Comment by jantimon** [comment]
We will remove the type in 3.x
