### ISSUE TITLE
Unclear on how to set titles. 

### ISSUE THREAD

**Issue by justpie** [jantimon/html-webpack-plugin#651]
How would I set the title from within my app component?  My component has multiple routes so i need to change the title / other metadata on the fly. I'm just unsure of how to do this.

My webpack.common.js is configured and works fine.

      new HtmlWebpackPlugin({
        template: 'src/index.html',
        title: 'TEST',
        chunksSortMode: 'dependency',
        metadata: METADATA,
        inject: 'head'
      }),

**Comment by mastilver** [comment]
`html-webpack-plugin` generate static html file, so you can change title dynamically

This needs to be done at you app level:
- vanilla js: `document.title = 'custom title'`
- react: https://github.com/nfl/react-helmet
- ...
