### ISSUE TITLE
Configure script tag URL

### ISSUE THREAD

**Issue by kurtextrem** [jantimon/html-webpack-plugin#656]
Is there any way to configure the script tag URL?

Now: 
`script src="bundle.js"`

Wanted:
`script src="localhost:8080/bundle.js"`

**Comment by mastilver** [comment]
use webpack `publicPath`: https://webpack.js.org/guides/public-path/#components/sidebar/sidebar.jsx

**Comment by kurtextrem** [comment]
Thank you!
