### ISSUE TITLE
Use html-webpack-plugin with an EJS file or stop webpack from evaluating variables

### ISSUE THREAD

**Issue by donpinkus** [jantimon/html-webpack-plugin#664]
I want to use the HTMLWebpackPlugin to take a .EJS file and insert my bundled assets.  

EJS is just a view template for Express that lets you do print variables into the HTML by doing `<%= my_var %>`.

This example has a EJS variable `<%= API_URL %>`, but webpack is interpreting it. 

How can I stop webpack from substituting the variable?

**Starting "template":**
```
    <!DOCTYPE html>
    <html>
      <head>
      	<meta charset="UTF-8">
      	<title>Monitor</title>
        <script>
          window.config = {
            API_URL: "<%= API_URL %>"
          }
        </script>
      </head>
      <body>
        <div class="container"></div>
      </body>
    </html>
```

**When you try to run webpack:**

`ERROR in Template execution failed: ReferenceError: FOOBAR is not defined`

**webpack.config.js**
```
    var webpack = require('webpack');
    var path = require('path');
    var HtmlWebpackPlugin = require('html-webpack-plugin');
    var ExtractTextPlugin = require('extract-text-webpack-plugin');
    
    module.exports = {
      entry: {
        bundle: './src/index.js'
      },
      output: {
        path: path.join(__dirname, 'dist'),
        filename: '[name].[chunkhash].js'
      },
      module: {
        rules: [
        {
          test: /\.js$/,
          use: 'babel-loader',
          exclude: /node_modules/
        },
        {
          // CSS is imported in app.js.
          test: /\.scss$/,
          use: ExtractTextPlugin.extract({
            fallbackLoader: 'style-loader',
            loader: ["css-loader", "sass-loader"]
          })
        }]
      },
      plugins: [
        new webpack.DefinePlugin({
          'process.env': {
            'NODE_ENV': JSON.stringify(process.env.NODE_ENV),
            'API_URL': JSON.stringify(process.env.API_URL)
          }
        }),
        new HtmlWebpackPlugin({
          template: 'src/index.ejs',
          inject: true
        }),
        new ExtractTextPlugin("styles.css")
      ],
    };
```

#### Don't set any loader

There is a [readme in this repo](https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md) about how to use html-webpack-plugin with inline template vars. The first suggestion is to not specify any loader, stating that `a fallback ejs loader` kicks in.  

This doesn't seem to be the case as running webpack is throwing the error about `<%= FOOBAR %>, FOOBAR is undefined` when it evaluates my index.ejs file.

**Comment by jantimon** [comment]
You can use the https://github.com/webpack-contrib/raw-loader which will ignore ejs templates

**Comment by aseem2625** [comment]
@donpinkus 
I'm having the same issue. Did you make it work! If so , please post solution.

**Comment by kimown** [comment]
@aseem2625
> With only issue that it outputs .html file instead of .ejs

  Hi, I just made a test, you can use this configuration.
```
new HtmlWebpackPlugin({
      template: '!!raw-loader!' + path.join(__dirname, 'template/index.html.ejs'),
      title: 'browser',
      filename: 'index.html.ejs'  // this line decide the extension of output file.
    })
```
After compiled, here is my out put:
```
.
├── bundle.js
└── index.html.output.ejs

```

**Comment by aseem2625** [comment]
@kimown 
Here is mine which works for me:
```
		new HTML({
			template: '!!raw-loader!src/index.ejs',
			filename: 'index.ejs', //for me, output file is index.ejs only and not
			minify: {
				removeComments: true,
				collapseWhitespace: true,
				conservativeCollapse: true
			}
		}),

```
