### ISSUE TITLE
Chunks: replace instead of append?

### ISSUE THREAD

**Issue by HoneyryderChuck** [jantimon/html-webpack-plugin#668]
I'm in the process of generating an index.ejs template for production, where I have all my assets hashed. This is my initial template:

```html
<!DOCTYPE html>
<html>
  <head>
		<meta charset="utf-8">
    <title>GoT Pool</title>
		<script src="/assets/vendor.js" charset="utf-8"></script>
    <script src="/assets/bootstrap.bundle.js" charset="utf-8"></script>
		<link rel="stylesheet" href="/assets/styles.css" />
  </head>
  <body>
		<div id="root">
			<%- body %>
		</div>
		<script type="text/javascript">
			<%- bottom %>
		</script>
    <script src="/assets/app.bundle.js"></script>
  </body>
</html>
```

Each entry (script) matches a chunk. The styles file is generated with the extract text plugin. 

When preparing the production build, I'm expecting all of these entries to be replaced with it. Instead, I see them appended to the bottom of the `<body>`:

```html
<!DOCTYPE html>
<html>
  <head>
		<meta charset="utf-8">
    <title>GoT Pool</title>
		<script src="/assets/vendor.js" charset="utf-8"></script>
    <script src="/assets/bootstrap.bundle.js" charset="utf-8"></script>
		<link rel="stylesheet" href="/assets/styles.css" />
  <link href="/assets/styles-0c9e2b13d39d6ada76c386027c53da71.css" rel="stylesheet"><link href="/assets/styles-42563931afbdce9174d7906b17eb73a2.css" rel="stylesheet"></head>
  <body>
		<div id="root">
			<%- body %>
		</div>
		<script type="text/javascript">
			<%- bottom %>
		</script>
    <script src="/assets/app.bundle.js"></script>
  <script type="text/javascript" src="/assets/vendor-5df5cdfd91300d666024.js"></script><script type="text/javascript" src="/assets/app-5df5cdfd91300d666024.bundle.js"></script><script type="text/javascript" src="/assets/bootstrap-5df5cdfd91300d666024.bundle.js"></script></body>

</html>
```

not the desired intention. Is there an option I might be missing?

**Comment by mastilver** [comment]
We do not support that,

`html-webpack-plugin` get all generated assets by webpack and include them dynamically into an html template

Just remove the hard-coded scripts from your template

**Comment by HoneyryderChuck** [comment]
Ok, fair enough. But what do you suggest me to do? Have two different templates (one for dev and one for prod)? Because, after removing the hard-coded scripts, the chunks only get added in prod mode, the template isn't touched in dev mode (this might be because I'm passing '.ejs' files through the `raw-loader`, is there an alternative to add the chunks dynamically?)

**Comment by mastilver** [comment]
Can't you use the same template for both?

**Comment by HoneyryderChuck** [comment]
I think I have understood my problem:

I'm using express + server-side rendering, in that, in my last matcher, I'm rendering the main index with my redux preloaded state. Problem is, I'm choosing the template based on dev/prod:

```js
if (isDeveloping)
  server.set('views', path.join(__dirname, '/src'));
else
  server.set('views', path.join(__dirname, '/dist/assets'))
```

I've just understood that this will never work, as webpack is putting the transformed template inside `dist/assets` even in dev mode. So I've changed this line to:


```js
server.set('views', path.join(__dirname, '/dist/assets'))
```

It now does everything I want:

* builds the production template with hashed assets;
* delivers the appropriate un-hashed template for server-side rendering;

I hope I'm doing the standard way of solving these things. Ping me back otherwise. 

And thx for the support!
