### ISSUE TITLE
Plugin emits each chunk twice

### ISSUE THREAD

**Issue by ggarek** [jantimon/html-webpack-plugin#669]
If use custom template (e.g. [html-webpack-template/index.ejs](https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs)) then you will end up with **each chunks present twice in the resulting .html**.

One entry per chunk is generated due to template:
```
    <% for (key in htmlWebpackPlugin.files.chunks) { %>
    <script src="<%= htmlWebpackPlugin.files.chunks[key].entry %>" type="text/javascript"></script>
    <% } %>
```

and another one is inserted _(i suppose)_ by the plugin itself.

```
$> cat node_modules/html-webpack-plugin/package.json | grep version
  "version": "2.28.0"
```

**Comment by mastilver** [comment]
Please set `inject` to false

https://github.com/jantimon/html-webpack-plugin#configuration
