### ISSUE TITLE
how to load templete from remote server use html-webpack-plugin

### ISSUE THREAD

**Issue by yueswing07** [jantimon/html-webpack-plugin#671]
my  situation need load html template from remote server , how can i do?
remote server  return html string parse by php.  is there any examples?

**Comment by mastilver** [comment]
Wow, this looks like a weird edge case
The easiest solution would be to download the template before running webpack
A more complex one would be to create a webpack plugin that would download that template

stackoverflow.com might be a better place to ask those kind of questions

**Comment by Ryuurock** [comment]
I have encountered such a problem. Have you solved it?
