### ISSUE TITLE
How to keep the script block?

### ISSUE THREAD

**Issue by scriptPilot** [jantimon/html-webpack-plugin#673]
First of all, thanks for the great piece of code!

I want to keep a `<script>...code...</script>` block within my index.ejs file - how can I realize it?

For now, the script content is extracted and merged to the bundle.

The injection should be done for the bundle / all chunks.

**Comment by mastilver** [comment]
I couldn't reproduce, If you are still having this issue, please provide more details like the template you are using and your webpack.config.js
