### ISSUE TITLE
silently ignores "chunks" option when provided a string

### ISSUE THREAD

**Issue by stephenmathieson** [jantimon/html-webpack-plugin#675]
the outputted HTML given:

```
new HtmlWebpackPlugin({
  chunks: 'options',
  filename: 'options.html'
}),
```

contains all chunks, but this only contains "options":

```
new HtmlWebpackPlugin({
  chunks: [ 'options' ],
  filename: 'options.html'
}),
```

imo the plugin should warn (or something?) when provided arguments it doesn't understand

**Comment by mastilver** [comment]
@jantimon Should we add a schema?

`webpack` is doing it that way: https://github.com/webpack/webpack/blob/83ad4b0f356c290f8ad1575563b033ee2831b23c/lib/webpack.js#L17-L20

I don't mind working on it if it's something you want

**Comment by jantimon** [comment]
That's really a smart idea :)

You might want to take a look at https://www.npmjs.com/package/ajv and https://jsonschema.net/#/editor
