### ISSUE TITLE
Unique identification of plugin instance

### ISSUE THREAD

**Issue by chrisui** [jantimon/html-webpack-plugin#679]
So we are able to generate multiple `html` files by having multiple instances of the `HtmlWebpackPlugin` plugins which is great. We can also include addons such as `HtmlIncludeSourceWebpackPlugin`.

However the issue is that these addons target all instances of `HtmlWebpackPlugin`. I have the use-case now where I want to target certain files with different addon instances.

I propose that we allow, when initialising plugins and addons, to assign each instance a unique id. 

Eg.

```js
[
  // assign an id when creating new plugin instances
  new HtmlWebpackPlugin({id: 'a', ...otherOptions}),
  new HtmlWebpackPlugin({id: 'b', ...otherOptions}),
  // still allow no id (it's opt-in)
  new HtmlWebpackPlugin({...otherOptions}),
  // have the convention for addons to target instances by id
  new HtmlWebpackPluginAddon({id: 'a', ...otherOptions}),
  // allow the usual pattern matching syntax of lists, string, regex
  new HtmlWebpackPluginAddon({id: ['a'], ...otherOptions}),
  new HtmlWebpackPluginAddon({id: /a/, ...otherOptions}),
  // omitting the id has the same behaviour as currently and targets all instances
  new HtmlWebpackPluginAddon({...otherOptions})
]
```

**Comment by mastilver** [comment]
I'm closing this as I think it should be the plugin responsibility to do that

Let's take `HtmlIncludeSourceWebpackPlugin` that you mentioned, by default it won't do anything
You actually need to configure `HtmlWebpackPlugin` to make `HtmlIncludeSourceWebpackPlugin` work and I believe that's what you are asking for

@jantimon If you think this is a legit feature-request please reopen

**Comment by chrisui** [comment]
I think my point is that there seems to be no conventional way for the addons to target a specific plugin instance to enhance.

a. How do I currently make my addon target only a single HtmlWebpackPlugin instance (ie. only affect one output .html file)
b. How do we prevent every addon re-implementing this in their own way

**Comment by mastilver** [comment]
a. in this example `indexa.html` will not have inlined script
```js
plugins: [
  new HtmlWebpackPlugin({ template: 'indexa.html'}),
  new HtmlWebpackPlugin({ template: 'indexb.html', inlineSource: '.js'),
  new HtmlWebpackInlineSourcePlugin()
]  
```

b. They don't have to re-implementing anything, it's already baked in

**Comment by chrisui** [comment]
What about addons which are injecting extra scripts? How do I make them only inject specific scripts for specific html files?

For example https://github.com/numical/script-ext-html-webpack-plugin targets specific assets. How do I make it only target them within specific html files? Ie. I only want to prefetch a given asset in a.html and not b.html

I may just be misunderstanding how these addons interact with the plugin so thanks for bearing with me! :)

**Comment by mastilver** [comment]
That will need to be done at `https://github.com/numical/script-ext-html-webpack-plugin` level

I believe you can get htmlWebpackPlugin options here and merge some with the `options` object

But you will need to check with the author for that
