### ISSUE TITLE
lodash as a dependency ./~/html-webpack-plugin/~/lodash/lodash.js

### ISSUE THREAD

**Issue by t0lkman** [jantimon/html-webpack-plugin#681]
is it possible not to include lodash?
How do I configure the plugin not to use lodash?

**Comment by mastilver** [comment]
What is your argument against `lodash`?

You can use another loader, by following: https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md

**Comment by iamolivinius** [comment]
For me it's no argument pro or against lodash. It just seems like the plugin is the reason why lodash is bundled into my "bundle.js"

**Comment by mastilver** [comment]
@iamolivinius Did you try using another loader?

**Comment by t0lkman** [comment]
btw by default lodash is used but is it only in dev mode bundled into the bundle.js or also in the production?
I really don't care if it's inside the bundle while developing, but I don't want to see it in the production if I don't use any of its features...

**Comment by jantimon** [comment]
If lodash get's bundled into your package that would be either a bug or a miss configured webpack config.

**Comment by iamolivinius** [comment]
Some deeper analysis of our bundle showed that we had a dependency that relies on lodash. Usually we use lodash-es only so I got a little bit confused when I read the output of this plugin. 

From my side: sorry for stirring up the dust! It's all fine 😸

**Comment by ozankasikci** [comment]
I don't even have lodash in my package json but webpack still includes it into production bundle?

**Comment by jacobdam** [comment]
I don't have any argument against lodash. But for me, loading the whole lodash object is unnecessary. I think load specific lodash methods is better than loading the whole lodash object:

```
// This one
var _template = require('lodash/template');
var _defaults = require('lodash/defaults');
_template(source, _defaults(...));

// is better than this one
var _ = require('lodash');
_.template(source, _.defaults(...));
```

**Comment by jantimon** [comment]
@jacobdam thanks this probably the best way to use lodash - but where is the measurable advantage in nodejs over using just the entire lodash library?

**Comment by jacobdam** [comment]
I noticed that after adding this plugin to my project, the command `webpack` displays ~100 lodash modules which I don't use. I don't have any evident that use lodash method style is better than lodash object style. But it seems the lodash method style is used in some popular repo (such as babel, eslint, enzyme, etc).

Btw, From lodash's README, https://github.com/lodash/lodash/#installation.

> // Cherry-pick methods for smaller browserify/rollup/webpack bundles.
> var at = require('lodash/at');
> var curryN = require('lodash/fp/curryN');

**Comment by jacobdam** [comment]
I know that ~100 lodash modules are not emitted into my main bundle. So the lodash method style is just a little bit better than import lodash object style. And in my case, it can help me to debug what in my main bundle easier.

**Comment by jacobdam** [comment]
> webpack displays ~100 lodash modules

I lied about this. babel warning me about code generator has deoptimised module `lodash/lodash.js` > 500kB. I thought lodash added 100 modules.

**Comment by bugeats** [comment]
Uhh, I'm building with `webpack -p` with a basic HtmlWebpackPlugin (^2.30.1) config and it's definitely including lodash in the bundle output -- which adds like 500k.  I've analyzed my dep tree with both npm and webpack, and HtmlWebpackPlugin is the only thing that is requiring lodash.

**Comment by mastilver** [comment]
@bugeats Can you provide us with a repository to reproduce?

**Comment by bugeats** [comment]
@mastilver I'm working on a private repo. I'm not opposed to spinning up a repo to repro, but let's try a few other things first. 

I was able to eliminate lodash from my build by adding this `exclude` key to my js loader config:

```javascript
{
    test: /\.(js|jsx)$/,
    loader: 'babel-loader',
    exclude: path.resolve('node_modules/lodash')
}
```

I get that most people are excluding `node_modules/*` from their builds, and so omitting this common config could be considered user error. However, I still don't understand why adding an `HtmlWebpackPlugin` instance to the webpack plugins would including it's private dependencies in my bundle.

**Comment by mastilver** [comment]
> However, I still don't understand why adding an HtmlWebpackPlugin instance to the webpack plugins would including it's private dependencies in my bundle.

Me neither, that's why a simple repo to reproduce it will move things faster (I'm not experiencing this issue but it still concern me). There is a good change it's not due to htmlwebpackplugin but I would prefer be sure and maybe help you figure out the issue

**Comment by bugeats** [comment]
Derp. I may have been wrong. I can no longer repo lodash in my bundle during `webpack -p`. Of course, it IS still in there with `webpack`, but I understand that's expected.

**Comment by mxstbr** [comment]
I'm also running into this, the stats object shows that htmlwebpackplugin is bundling all of lodash into my browser bundle?!

**Comment by mxstbr** [comment]
Unfortunately `exclude: path.resolve('node_module/lodash')` doesn't work for me :cry:

**Comment by jantimon** [comment]
@mxstbr how could exclude help with that? can you try to find out in your generated js bundle file which script is loading lodash?

**Comment by mxstbr** [comment]
@jantimon dunno, just tried @bugeats suggestion 🤷‍♂️ 

The thing is, none of them are 😅 HTMLWebpackPlugin is the only thing

**Comment by jantimon** [comment]
Any special common chunks configuration?

**Comment by mxstbr** [comment]
Only whatever create-react-app ships with and

```JS
  config.plugins.push(
    new webpack.optimize.CommonsChunkPlugin({
      names: ['bootstrap'],
      filename: './static/js/[name].js',
      minChunks: Infinity,
    })
  );
```

To get a bundle that only has the webpack bootstrapping code.

**Comment by jantimon** [comment]
Well this bug didn't happen for older webpack version - maybe @sokra has an idea what changed

**Comment by DanielSchaffer** [comment]
I just ran into this. From what I understand, `html-webpack-plugin` uses lodash templates by default, which means it has to include lodash as a dependency in order for the templates to be rendered. As an aside, I'm not entirely clear as to why the default functionality is to do it like this rather than statically render the HTML template - but the fix is actually quite easy: Just add a webpack loader for your desired template language. If you're just using a static HTML template, use `html-loader`:

```
{
  test: /\.html/,
  loader: 'html-loader'
}
```

You can also use PUG, or whatever else. FWIW, this is all covered here: https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md
