### ISSUE TITLE
Generate HTML files from others

### ISSUE THREAD

**Issue by rnascunha** [jantimon/html-webpack-plugin#682]
Hi,

I' pretty new even in JavaScript, so maybe is a stupid question... I want to use the plugin to generate the HTML files of a web page. The header and the footer will all be the same, but the main will be different. I made a `base.ejs` file like this:

```
<!DOCTYPE  html>
<html>
 	<head>
 		<title><%= htmlWebpackPlugin.options.title %></title>
 	</head>
 	<body>
 		<header><% include header %></header>
 		<main><% include  htmlWebpackPlugin.options.main %></main>
 		<footer><% include footer %></footer>
 	</body>
</html>
```

There is a file named `header.ejs` and `footer.ejs` at the same folder of `base.ejs` that must be included. The title of the page and the name of the file to be included (`main.ejs`) at the main tag I want to get it from the plugin. My `web.config.js` is like this:

```
modules.export = {
/*...*/
plugins: [
		new HtmlWebpackPlugin({
				title: 'Title of page',
				main: 'main',
				filename: 'index.html',
				template: 'base.ejs'
			})
          ]
}
```

But this is not working. This way the files are not included, or when I use other loader ('ejs-render-loader'), the loader don't get the plugins variables. I tried to do with other loaders, like handlebars, or using server-side-includes, but always miss something.

Is it possible to do what I want?

**Comment by mastilver** [comment]
This won't work if you don't have the right loader setup

Please use https://github.com/bazilio91/ejs-compiled-loader

Reach out again here, if I didn't answer your issue properly

**Comment by rnascunha** [comment]
It's still not working. I installed the loader, and changed the the template line at `webpack.config.js` to `template: 'ejs-compiled-loader!./base.ejs'`, but I'm getting this error:

` ERROR in ./~/ejs-compiled-loader!./base.ejs
    Module build failed: Error: ENOENT: no such file or directory, open 'htmlWebpackPlugin.options.main'`

The `htmlWebpackPlugin.options.main` variable is not being evaluated. Is there a way deal with it?

**Comment by mastilver** [comment]
That not you are suppose to do it:
Check:
- https://webpack.js.org/configuration/module/#rule-use
- https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md
