### ISSUE TITLE
can not work well with webpack-dev-server

### ISSUE THREAD

**Issue by cunjieliu** [jantimon/html-webpack-plugin#685]
hello 
my project dir is 
![image](https://cloud.githubusercontent.com/assets/6039139/26349953/1b608cea-3fe4-11e7-89f2-3c7e36e344a4.png)

and my webpack.dev.config.js is look like this
![image](https://cloud.githubusercontent.com/assets/6039139/26349994/360fccea-3fe4-11e7-87f8-4c487ec14779.png)

and then I run the server without error

but when I visit "http://localhost:1234/build/html/index.html"
it show "Cannot GET /build/html/index.html"

but if i first run this "webpack --config webpack.dev.config.js"
then start the server
and then visit "http://localhost:1234/build/html/index.html", it ok!

how to solve this problem?

**Comment by mastilver** [comment]
#3 duplicate

Just use: https://github.com/jantimon/html-webpack-harddisk-plugin
