### ISSUE TITLE
bundled js and css is not getting added to index.html

### ISSUE THREAD

**Issue by c0debreaker** [jantimon/html-webpack-plugin#686]
The bundled css and js are being generated properly. The filenames are `ifc.main21b9ea73be24c36deee0.js` and `ifc.main21b9ea73be24c36deee0.css`

Below you'll see my configuration for HtmlWebpackPlugin. After the build finishes, I open app/src/index.html so I can see if the 2 files I mentioned above have been added. It's not there. What am I doing wrong?

```
  plugins: [
    new webpack.ResolverPlugin([
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
    ]),
    new ExtractTextPlugin('[name].main[hash].css'),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      _: 'lodash',
      Promise: 'bluebird',
      Backbone: 'backbone',
      Marionette: 'backbone.marionette'
    }),
    new HtmlWebpackPlugin({
      title: 'Main App',
      inject: 'body',
      template: path.resolve(__dirname, 'app', 'src', 'index.html'),
      chunks: ['ifc']
    })
  ]
```

**Comment by mastilver** [comment]
Can you confirm your `entry`is the following:

```
entry: {
  'ifc': './<path to entry>'
}
```

**Comment by c0debreaker** [comment]
This is what I see
```
  entry: {
    ifc: 'js/main.js'
  },
```

I have an update since I've been debugging it last night. When I added `filename` property to my HtmlWebpackPlugin, and I made its value to index_new.html, it worked. If the value is index.html, it never added it. It was really weird. I'm currently investigating if grunt is overwriting it using their copy plugin. 
```
    new HtmlWebpackPlugin({
      hash: true,
      title: 'Main App',
      inject: 'body',
      filename: 'index_new.html', <---------- this one worked but not when value is index.html
      template: path.resolve(__dirname, 'app', 'src', 'index.html'),
      chunks: ['ifc']
    })
```

**Comment by c0debreaker** [comment]
I think I found the culprit which I fixed. Now the question is, how can I put the generated line of code before `</body>`?

Works well but the only missing task is putting it before `</body>`?
```
<script type="text/javascript" src="ifc.main54cbdc243f075a59ebe5.js?54cbdc243f075a59ebe5"></script></body>
```

**Comment by c0debreaker** [comment]
After investigating, it did put it before `</body>`. However, I am not sure why we have `<script></script`> before `</html>`.  So the code I am seeing is like this.

```
<script type="text/javascript" src="ifc.main54cbdc243f075a59ebe5.js?54cbdc243f075a59ebe5"></script>
</body>
<script>
   // ... a javascript function here
</script>
</html>
```

Is that valid?

**Comment by c0debreaker** [comment]
This was our original code before I hashed the filename
```
</script>
</body>
<script>/* some iife here */</script>
<script src="ifc.main.js"></script>
</html>
```
If I'll maintain that invalid structure, how can I tell `html-webpack-plugin` to put `<script type="text/javascript" src="ifc.main54cbdc243f075a59ebe5.js?54cbdc243f075a59ebe5"></script>` before `</html>`?

**Comment by mastilver** [comment]
Is that even valid html? (To have script before closing html)

**Comment by mastilver** [comment]
If you really want to, your final option is to set `inject` to false and use a custom template

**Comment by c0debreaker** [comment]
yeah, searching for blogs/forums, they are saying that putting it before `</html>` is invalid. However, I just want to keep it that way since I don't want to break my other teammate's app.

So is this correct?
```
new HtmlWebpackPlugin({
      hash: true,
      inject: false,
      title: 'Main App',
      inject: 'body',
      filename: 'index.html',
      template: path.resolve(__dirname, 'app', 'src', 'index.html'),
      chunks: ['ifc']
    })
```

But what should I put in the custom index.html?

**Comment by c0debreaker** [comment]
I decided to make the html structure correct. It's now putting it before `</body>`. What I'd like to happen is to put the generated css filename to be the first inside head. It's putting it after the other css files.

**Comment by mastilver** [comment]
If you set `inject` to `true` (the default), it will put css refs in head, js refs in body

If you want to sort them, use `chunkSortMode`: https://github.com/jantimon/html-webpack-plugin#configuration

**Comment by c0debreaker** [comment]
After investigating on the css again, I'm shocked that the css file being referenced doesn't even exists. LOL!
