### ISSUE TITLE
chunks injection: only use chunks filename?

### ISSUE THREAD

**Issue by warpdesign** [jantimon/html-webpack-plugin#690]
## Description

I have a project tree like this:

root
root/app
root/scripts

Webpack is ran from root and outputs its chunks to `app/bundle.js`.

HTMLWebpackPlugin is configured like this:

```js
      new HtmlWebpackPlugin({
          title: 'OnMap v6 player',
          template: 'index.ejs',
          inject: 'body',
          filename: 'app/index.html'
      })
```

It properly writes filename into app/index.html but for some reason, script urls end up being `./app/bundle.f0f5efe44f77d1363e91.js`.

Is there a way to remove the 'app/' before the filename and only copy the filename here?

## Environment

```
Node.js v7.8.0
win32 10.0.16199
npm -4.2.0
webpack 2.6.1
html-webpack-plugin 2.28.0
```

**Comment by mastilver** [comment]
Either edit your `publicPath` or `entry` to remove `./app/` from them

If that didn't solve the issue, feel free to reach out here again
