### ISSUE TITLE
about inject option

### ISSUE THREAD

**Issue by lonelyclick** [jantimon/html-webpack-plugin#691]
The current inject option is to put script in head or to body, but I want some to go to head, and the other to body, that's not supported. I think we can pass in a function to inject, and if this function return true, put it in body, and if the function returns false, put it in head.

```js
new HtmlWebpackPlugin({
  inject: (script) => {
    return script.indexOf('somescriptname') !== -1;
  }
})
```

**Comment by jantimon** [comment]
The inject feature is only for very simple pages - for more advanced templates you should turn it off and use the template variables to add the script tags.

**Comment by st-sloth** [comment]
@jantimon Thanks! That's kind of what I was looking for. I somehow overlooked the "full control over the asset placement" sentence in the README. Spent hours and ended up here, luckily.
Is there a way to get an asset contents in the template, not just the file names, to inline some of them, or can it only be done with another plugin?
