### ISSUE TITLE
Add support for Webpack 3

### ISSUE THREAD

**Issue by tleunen** [jantimon/html-webpack-plugin#699]
Webpack 3.0-rc was released and this plugin currently doesn't support it.

I haven't tested it yet, so it might be just a question of updating the peerDependency.

**Comment by mastilver** [comment]
webpack@3 is getting released today
A PR would consist of:
- update `package.json`: https://github.com/jantimon/html-webpack-plugin/blob/master/package.json#L66
- update `travis.yml`: https://github.com/jantimon/html-webpack-plugin/blob/master/.travis.yml#L6
- run `npm i webpack@3 && npm run build-examples`

**Comment by KarandikarMihir** [comment]
@mastilver Is this taken? Or should I send a PR?
