### ISSUE TITLE
AppCache injection doesnt respect publicPath

### ISSUE THREAD

**Issue by ccorcos** [jantimon/html-webpack-plugin#700]
I'm using the appcache plugin:

```
				new AppCachePlugin({
					cache: appCacheAssets,
					network: ["*"],
					fallback: ["/"],
					settings: [],
					exclude: [],
					output: "index.appcache",
				}),
```

Along with the this html plugin:

```
				new HtmlWebpackPlugin({
					template: "./src/client/index.template",
					config: config,
				}),
```

My output section specifies a public path:

```
		output: {
			filename: output,
			path: outputPath,
			chunkFilename: "[name]-[chunkhash].js",
			pathinfo: true,
			publicPath: "/",
		},
```

But that publicPath is not respected when the appcache file is injected :(

**Comment by mastilver** [comment]
@ccorcos Can you be clearer on how the publicPath is not respected

A repository reproducing the error would be helpful!

**Comment by ccorcos** [comment]
As requested: https://github.com/ccorcos/public-path-issue

**Comment by jantimon** [comment]
@ccorcos  that's correct it should be prepended (probably here):

https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L411-L413

Fixing this would be a breaking change so we should add it to 3.x

**Comment by ccorcos** [comment]
Awesome. Just created a PR https://github.com/jantimon/html-webpack-plugin/pull/710
