### ISSUE TITLE
</body> inside comment breaks index.html compilation

### ISSUE THREAD

**Issue by Hurtak** [jantimon/html-webpack-plugin#702]
### Description

When i have the following comment in index.html

```html
<!DOCTYPE html>
<html>
    ...
    <!-- The build step will place the bundled scripts before the end of </body> tag. -->
  </body>
</html>
```

index.html compiles to this

```html
<!DOCTYPE html>
<html>
    ...
    <!-- The build step will place the bundled scripts before the end of <script type="text/javascript" src="/static/js/bundle.js"></script></body> tag. -->
  </body>
</html>
```

### Config

Create-react-app config

### Related ticket

https://github.com/facebookincubator/create-react-app/issues/2523

**Comment by mastilver** [comment]
This is a really specific issue..., it's caused by: https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L525-L535

I can find a clean way to fix it, if you do feel free to send a PR

**Comment by Janpot** [comment]
Clean way would be actual html parsing?

**Comment by jantimon** [comment]
@Janpot this would decrease the inject speed for all other users.
Please disable the inject feature in that case or don't add the body element to a comment

**Comment by Janpot** [comment]
@jantimon correct, it's a tradeoff between performance and correctness. Question should rather be, is the speed decrease noticeable and problematic? Html parsing can be pretty fast though, it has to happen only once during a run of this plugin, and it usually happens on rather small html files (like in SPAs).

**Comment by Hurtak** [comment]
Two solutions come to mind.
1. We could update the regex so that it does not match the `</body>` when it is between `<!--` and `-->`.
2. There could be some warning if this plugin detects that there is more than one `</body>` inside the html.

**Comment by jantimon** [comment]
@Hurtak both solutions would slow down the compilation speed.
@Janpot you are right but we introduced the inject feature only as a shorthand with this limitation in mind. If it doesn't work in your case please use the `inject:false` and fall back to a template which loops through all assets.
