### ISSUE TITLE
Support html-tidy

### ISSUE THREAD

**Issue by rondonjon** [jantimon/html-webpack-plugin#714]
## Description

The plugin currently supports optional minification for people that want their HTML as small as possible.

As an alternative for people who like their HTML clean and properly indented, I would suggest to add support for [html-tidy](https://www.npmjs.com/package/htmltidy).

Although the user can, to some extent, ensure that the output is "clean" by optimizing the template, this is not entirely true when when html-webpack-plugin is used together with other plugins, like favicons-webpack-plugin, which do not always produce prettified output.

## Example

 * `minify`: `{...} | false` Pass html-minifier's options as object to minify the output.
 * `tidy`: `{...} | false` Pass html-tidy's options as object to tidy the output.

**Comment by jantimon** [comment]
You can easily write a plugin for html-webpack-plugin - let me know once you are done and I will add it to the readme :)

**Comment by luishdez** [comment]
You can check https://github.com/ainsly/tidy-html-webpack-plugin
