### ISSUE TITLE
Is it possible to inject scripts in to multiple html templates

### ISSUE THREAD

**Issue by dinukadesilva** [jantimon/html-webpack-plugin#715]
I was thinking whether it make sense to support the following format 
```
new HtmlWebpackPlugin({
      inject: true,
      template: "./docs/*.html",
    })
```

**Comment by mastilver** [comment]
Thank you for your feature request

I would be interested in how would you handle the `filename` options

Another thing, that I've been thinking about would be to allow an array of options to be passed in, that way you could do:

```
new HtmlWebpackPlugin(
  glob.sync('./docs/*.html').map(file => ({
    inject: true,
    template: file
  }))
)
```

**Comment by dinukadesilva** [comment]
File name could be the same name as it is with the folder structure.

And enabling passing an array offcourse a good idea.

**Comment by mastilver** [comment]
> File name could be the same name as it is with the folder structure.

:/ I'm sure some people would like more customization
