### ISSUE TITLE
Multiple entry points -> multiple html outputs webpack rebuild  very slow

### ISSUE THREAD

**Issue by CharlieLau** [jantimon/html-webpack-plugin#724]
## my  question  is:

- in my project, i has 70's entries and htmls page. when one entry changed, html-webpack-plugin
rebuild  very slowly, Has anyone ever met ？

**Comment by cyqresig** [comment]
I met this, too. Rebuilding is rather slow using html-webpack-plugin@2+ on webpack 2 or 3.
I try to downgrade it to 1.7.0, then everything is ok.
But I think it is a serious bug that need to be fixed as soon as possible.

**Comment by mastilver** [comment]
Could you try if it gets better this: https://github.com/jantimon/html-webpack-plugin/pull/723

**Comment by cyqresig** [comment]
I try the pr code and it works, but I found that:
1. Rebuilding of this has returned to normal, but it is still a little slower than it of version 1.7.0,
2. Initial building of this is almost 30% slower than it of version 1.7.0, and it is almost 25% faster than it of version 2.X.

**Comment by mastilver** [comment]
@cyqresig thank you for you feedback, we will make sure to improve that!

**Comment by CharlieLau** [comment]
@mastilver  I try the pr code,but  it  didn't work .
   I used "webpack multicompile " to resolve it

**Comment by simon-yxl** [comment]
I met this, too.

**Comment by githoniel** [comment]
me two.
when there is 10 entry, rebuild take about 8000ms. i think it's acceptable
when I add to 24 entry, rebuild take about 40000ms.......

**Comment by jantimon** [comment]
Is there a difference between webpack 1 and webpack 3? 
Because we have similar issues here: https://github.com/webpack/webpack/issues/5505#issuecomment-322979832

**Comment by githoniel** [comment]
yes i think it's because of webpack3.
I switch to webpack@2, rebuild is only 300ms.
```
[0] webpack: Compiling...
[0] webpack: wait until bundle finished: /chunk.2.js
[0] webpack building...
[0]  DONE  Compiled successfully in 3001ms14:45:37
[0]
[0] webpack built 0ee20b12b0698f93c3a9 in 3001ms
[0] Hash: 0ee20b12b0698f93c3a9
[0] Version: webpack 2.7.0
[0] Time: 3001ms
```
notice that [0] webpack: wait until bundle finished: /chunk.2.js.
It seem that webpack2 only rebuild chunk2.
but in webpack3，there is a full rebuild.

**Comment by M-torch99** [comment]
me too,but have some difference ways to solve?

**Comment by vhmth** [comment]
Has anyone tried updating to Webpack 4 to see if this fixes whatever issues may be introduced via Webpack 3? Right now this plugin takes up about 50 seconds of a 71-second rebuild time in our main repo.

**Comment by jantimon** [comment]
Maybe @sokra might know what this performance loss might have caused.

**Comment by qiming-kooboo** [comment]
@CharlieLau html-webpack-plugin-for-multihtml this plugin can fix this issue, 
@jantimon Is it possible merge the changes?

**Comment by jantimon** [comment]
Can you give any information which changes improved the performance?

**Comment by jyx12138** [comment]
I used webpack 2.7.0 ,html-webpack-plugin 1.7.0 extract-text-webpack-plugin 2.1.2 to resolve it.

**Comment by funwithtriangles** [comment]
[`html-webpack-plugin-for-multihtml`](https://github.com/daifee/html-webpack-plugin-for-multihtml) fixes this. Can it not be merged into the main repo?

**Comment by jantimon** [comment]
@funwithtriangles could you please go into detail how they fix it? the code is 7 month old and is hardly mergable.

**Comment by funwithtriangles** [comment]
@jantimon understood! Was just asking to see what the situation was.

**Comment by zD98** [comment]
Hi, the same question in Webpack 4 and html-webpack-plugin3.
Is there some solutions ?

**Comment by jantimon** [comment]
The pr (#967) is trying to solve this - if you have time please try if it improves the performance.

**Comment by tongjun741** [comment]
@jantimon It's work for me.

**Comment by vhmth** [comment]
Wow @jantimon thank you for getting this over the finish line and putting something out there. You are going to collectively save our eng team hours of wait time per week for builds/deploys to go through haha. :-P

**Comment by jantimon** [comment]
Right now #972 has still build errors on travis - once we find out why we will finally release a new alpha

**Comment by jantimon** [comment]
Performance findings by different users for v4:
+ https://github.com/jantimon/html-webpack-plugin/issues/962#issuecomment-409070361
+ https://github.com/jantimon/html-webpack-plugin/pull/953#issuecomment-395040726
+ https://github.com/jantimon/html-webpack-plugin/pull/953#issuecomment-417408140

Give it a try: 
https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-alpha.2

**Comment by qianjiahao** [comment]
### 多页打包提速解法（multi html speed up）


#### first step:

````
npm i html-webpack-plugin-for-multihtml
````

#### second step:

````
plugins: [
    new HtmlWebpackPlugin({
      // ...
      multihtmlCache: true // the key for solving this problem !
    })
  ]
````

**Comment by vhmth** [comment]
@jantimon 🤝 gracias!
