### ISSUE TITLE
No "type" attribute in generated "link" elements for stylesheets

### ISSUE THREAD

**Issue by jarkkorantala** [jantimon/html-webpack-plugin#726]
## Description

When generating the link elements for CSS stylesheets, the "type" attribute is omitted.

Although not mandatory as per HTML 4.01 or 5 specification, it provides valuable information for the browser in case the HTTP server serves the CSS files without a Content-Type header.

At least with Internet Explorer 11, a link element with no type and a reference to a file served without a Content-Type header raises error "SEC7113: CSS was ignored due to mime type mismatch".

### Error Message & Stack Trace

Internet Explorer 11:
[SEC7113](https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=EN-GB&k=k(VS.WebClient.Help.SEC7113)): CSS was ignored due to mime type mismatch

### Config

Copy the relevant section from `webpack.config.js`:

```js
module.exports = {
    entry: {
        app: __dirname + '/src/app/core/index.module.js',
        vendor: __dirname + '/src/vendor.lib.js',
    },
    output: {
        path: __dirname + "/dist",
        filename: '[name].bundle.js',
        chunkFilename: '[name].bundle.js',
        sourceMapFilename :'[name].bundle.js.map'
    },
    plugins: [
        new ExtractTextPlugin(
            "[name].css"
        ),
        new HtmlWebpackPlugin({
            filename: 'index.html',
            template: 'src/index.html',
            chunksSortMode: orderByList(['vendor', 'app']),
            title: 'Tree-shaking'
        })
    ],
    module: {
        loaders: [{
            test: /\.html$/,
            loader: "html-loader",
            exclude: ['src/index.html']
        }, {
            test: /\.css$/,
            loader: ExtractTextPlugin.extract({fallback: "style-loader", use: "css-loader"})
        }]
    },
    devtool: 'source-map',
    devServer: {
        contentBase: __dirname + "/src"
    }
}
```

Copy your template file:

```html
<!doctype html>
<html ng-app="myApp">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Site title</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
  </head>
  <body>
    <div top-bar></div>
    <div nav-bar></div>
    <div ui-view></div>
  </body>
</html>
```

## Environment

Internet Explorer 11, and a misconfigured HTTPD server that serves no Content-Type for common MIME types (CSS)

**Comment by mastilver** [comment]
First time I heard about this attribute

I guess it doesn't hurt so adding `type: 'text/css'` to: https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L483-L507 would solve that issue

**Comment by jantimon** [comment]
In the current v4 we removed all `type="text/script"` attributes:  
https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-alpha.2

**Comment by swimmadude66** [comment]
@jantimon I don't know the process for adding a plugin, but I've built one to fix this exact error.

https://github.com/steadyapp/html-webpack-link-type-plugin
