### ISSUE TITLE
Error: "manual" is not a valid chunk sort mode

### ISSUE THREAD

**Issue by bigmgreen** [jantimon/html-webpack-plugin#728]
"npm install html-webpack-plugin --save-dev" done!
and version is 2.29.0
but still shown that error
I found there no "manual" function in chunksorter.js
help me~

**Comment by mastilver** [comment]
manual sort hasn't been released yet

**Comment by chyzwar** [comment]
Please update documentation, I just sped 1h trying make it work.

**Comment by bulkan** [comment]
@mastilver is there an ETA on when manual sort mode will be released ?

**Comment by jantimon** [comment]
Released in 2.30.1

**Comment by light24bulbs** [comment]
there isn't a good explanation in the docs of how manual sort actually works.  It just says the word "manual" and that's it.  How is it "manually" specified?

**Comment by chyzwar** [comment]
I found examples in tests.
```js
      chunksSortMode: 'manual',
      chunks: ['reactHotLoaderPath', 'main'],
```

2017-12-26 15:38 GMT+00:00 light24bulbs <notifications@github.com>:

**Comment by light24bulbs** [comment]
That's exactly where I found the examples too.  It should just say in the
docs "uses order of chunks array"
