### ISSUE TITLE
Is it possible to have an option to add leading slash to the script src attribute value

### ISSUE THREAD

**Issue by NeverwinterMoon** [jantimon/html-webpack-plugin#731]
`html-webpack-plugin` currently generates the following:
```<script type="text/javascript" src="booking.js"></script>```

This doesn't work for HTML 5mode enabled in our SPA with the current configuration. So, basically, if we reload the page at "fake" url "/foo/bar" and src is like above, booking.js will be served at "/foo/bar/index.html".

Now, if we have the leading slash, like so: 
```<script type="text/javascript" src="/booking.js"></script>```

The index file would be served at /.

**Comment by mastilver** [comment]
use `publicPath: '/'`

https://webpack.js.org/guides/public-path/#components/sidebar/sidebar.jsx

**Comment by NeverwinterMoon** [comment]
@mastilver Oh, thanks a lot! I am new to Webpack, just switched our configuration from a bunch of gulp scripts to a Webpack one, so I am still not familiar with some basic stuff. Thanks again.
