### ISSUE TITLE
Is there a way to inject stylesheets into the `body` tag?

### ISSUE THREAD

**Issue by aleen42** [jantimon/html-webpack-plugin#741]
Recently, I have met a confusing problem in my project when I have used a Webpack plugin named `extract-text-webpack-plugin` to extract my stylesheet into one file. But with using `html-webpack-plugin`, I can not find out a proper way to avoid blocking in rendering DOM elements by injecting such a stylesheet file into the body tag, rather than the head. Can you tell me how can I do this?

**Comment by mastilver** [comment]
Not right now, **maybe** in the future

**Comment by aleen42** [comment]
To do so, I may need to write another plugin to extend this, like converting tags to load it dynamically with JavaScript. For instance, I may change the html like this:

```html
<link type="stylesheet" href="main.css"></link>
```

To convert it into this:

```html
<script type="text/javascript">
    document.write('<link type="stylesheet" href="main.css"></link>');
</script>
```

**Comment by mastilver** [comment]
Right now you can use a custom template by setting `inject` to `false`

**Comment by whazap** [comment]
any news on this feature / merge request?
