### ISSUE TITLE
is there anyway to inject mixined js to body with script tag?

### ISSUE THREAD

**Issue by SnowFlowers** [jantimon/html-webpack-plugin#742]
i want to jnject a chunk to my index.html with no extra request.like this:
![image](https://user-images.githubusercontent.com/16875486/28351946-f38fb884-6c85-11e7-91ab-99694097c657.png)
i dont want a script tag with src.i need my minified js code in this tag

**Comment by mastilver** [comment]
try using `html-webpack-inline-source-plugin`
