### ISSUE TITLE
Uglify fails silently when passed in incorrect options

### ISSUE THREAD

**Issue by niieani** [jantimon/html-webpack-plugin#743]
## Description

We've upgraded our dependencies (incl. webpack 3) and suddenly our HTML stopped being minified. There were no errors, simply non-minified code started being emitted.

After debugging, we found out that the error is caused by an incompatible configuration (uglify 2 instead of uglify 3). The reason why the error is silently ignored is that there is no sane default for the "log" function passed into the `html-minifier`, which [tries to log the error](https://github.com/kangax/html-minifier/blob/b1a31b2027a5e0a17cf4b7257f341d1d38669df7/src/htmlminifier.js#L683-L686) and simply returns the non-minified code in case any occur.

A solution would be to add a default `log` function and merge it with the rest of the options passed by the user.

### Config

Relevant section from `webpack.config.js`:

```js
module.exports = {
  plugins: [
    new HtmlWebpackPlugin({
        inject: false,
        template: 'app/core/app.html.ejs',
        filename: 'app.html',
        chunksSortMode: 'dependency',
        minify: {
          removeComments: true,
          collapseWhitespace: true,
          conservativeCollapse: false,
          preserveLineBreaks: true,
          minifyJS: {
            comments: false, // it was failing here!!!
            compress: {
              keep_fnames: true,
              warnings: false,
            },
            output: {
              semicolons: false,
            },
            mangle: true,
          },
        },
      }),
    ...
  ]
}
```

## Environment

Node.js v8.1.3
darwin 16.5.0
webpack@3.3.0
html-webpack-plugin@2.29.0

**Comment by niieani** [comment]
I see minify section is still missing a default for `log`:

https://github.com/jantimon/html-webpack-plugin/blob/75eef8876bb54e80f9493a544759493ed385d7e0/index.js#L317-L318

So this issue is still valid.

**Comment by jantimon** [comment]
Could you please provide a pull request for https://github.com/jantimon/html-webpack-plugin/tree/webpack-4 ?

**Comment by niieani** [comment]
@jantimon I'd love to, but I don't currently have the time. Best I can do is put it on my backlog.

**Comment by niieani** [comment]
Keeping open for the future.

**Comment by niieani** [comment]
Keeping open for the future.

**Comment by niieani** [comment]
Pong.

**Comment by jantimon** [comment]
I tried to fix it with this change: https://github.com/jantimon/html-webpack-plugin/pull/1339
can you please try html-webpack-plugin 4.0.1 ?
