### ISSUE TITLE
Specify path for multipage apps assets

### ISSUE THREAD

**Issue by tqhao94** [jantimon/html-webpack-plugin#745]
## Description

Hi, for a multipage app, I want to specify a path for assets, because the generated html file add all assets from webpack, so an access to one page will download unecessary files. 

Locally I've rewrited a bit in the plugin, so I can add one option like this.

### Config

        new htmlWebpackPlugin({
            template: "./home.html",
            filename: "home/home.html",
            assetPath: "/build/home"
        }),

So the `home.html` will only add assets inside `/buid/home/`

## Environment

Chrome, Windows, Node 8, Webpack 3.2

**Comment by mastilver** [comment]
use `chunks`

https://github.com/jantimon/html-webpack-plugin#configuration
