### ISSUE TITLE
Unable to render dynamic content from config

### ISSUE THREAD

**Issue by FarhadG** [jantimon/html-webpack-plugin#747]
## Description

I've tried to get custom data injected into our `.html` template using this loader without any success. We've been able to successfully build our assets and have them injected, however, the ability to pass in dynamic data has not worked. Looking at the examples provided in this repo, I don't see how `options.title` is passed into the template.

Docs: [Template Example](https://github.com/jantimon/html-webpack-plugin/blob/master/examples/custom-template/template.html#L5)

Code Reference: [Starter kit](https://github.com/AngularClass/NG6-starter)

### Error Message & Stack Trace

```
COPY THE ERROR MESSAGE, INCLUDING STACK TRACE HERE
```

### Config

Copy the relevant section from `webpack.config.js`:

```js
module.exports = {
  devtool: 'source-map',
  entry: {
    app: [
      'babel-polyfill',
      path.join(__dirname, 'client', 'app/app.js')
    ]
  },
  module: {
    loaders: [
       { test: /\.js$/, exclude: [/app\/lib/, /node_modules/], loader: 'ng-annotate-loader!babel-loader' },
       { test: /\.html$/, loader: 'raw-loader' }, // have also tried with the html-loader
       { test: /\.(scss|sass)$/, loader: 'style-loader!css-loader!sass-loader' },
       { test: /\.css$/, loader: 'style-loader!css-loader' }
    ]
  },
  plugins: [
    // Injects bundles in your index.html instead of wiring all manually.
    // It also adds hash to all injected assets so we don't have problems
    // with cache purging during deployment.
    new HtmlWebpackPlugin({
      template: 'client/index.html',
      // inject: 'body',
      // hash: true,
      title: 'TEST!!!!!!!!!!!',
      options: {
        title: "TEST!!!!!!!!!!!!!*"
      },
      chunks: ['vendor', 'app']
    }),

    // Automatically move all modules defined outside of application directory to vendor bundle.
    // If you are using more complicated project structure, consider to specify common chunks manually.
    new webpack.optimize.CommonsChunkPlugin({
      name: "vendor",
      minChunks: module => /node_modules/.test(module.resource)
    })
  ]
};
```

Copy your template file:

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="description" content="NG6-Starter by @AngularClass">
    <link rel="icon" href="data:;base64,iVBORw0KGgo=">
    <base href="/">
  </head>
  <body ng-app="app" ng-strict-di ng-cloak>


  <%= htmlWebpackPlugin.options.title %>

  <%= htmlWebpackPlugin.title %>

  <%= title %>

  <%= '\<\%\= htmlWebpackPlugin.title \%\>' %>

  <%= '\<\%\= htmlWebpackPlugin.options \%\>' %>

  </body>
</html>
```

**Comment by giacomoalonzi** [comment]
I have the same problem, but with .pug file instead html.
Anyone can help us? 🙏

**Comment by mastilver** [comment]
```js
 new HtmlWebpackPlugin({
      template: 'client/index.html',
      // inject: 'body',
      // hash: true,
      title: 'TEST!!!!!!!!!!!',
})
```

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="description" content="NG6-Starter by @AngularClass">
    <link rel="icon" href="data:;base64,iVBORw0KGgo=">
    <base href="/">
  </head>
  <body ng-app="app" ng-strict-di ng-cloak>


    <%= htmlWebpackPlugin.options.title %>
  </body>
</html>
```

Should work

**Comment by FarhadG** [comment]
Thanks for the response, @mastilver, but still no luck. For reference, I've downloaded this starter kit to see if I can get it to work: https://github.com/AngularClass/NG6-starter

**Comment by mastilver** [comment]
Yes, there seems to be an issue...

First you can try using `{ test: /app.*\.html$/, loader: 'raw' },` but it will bring another issue, I will look a bit further on that

**Comment by giacomoalonzi** [comment]
I discovered this https://github.com/velenir/html-webpack-template-pug and if you see this specific file https://github.com/Velenir/html-webpack-template-pug/blob/master/mixins.pug he use the `htmlWebpackPlugin.options.title` in pug template. I did the same thing with no luck! 
I don't know where is the problem, i'm going crazy :|

```
Html Webpack Plugin:
  Error: Child compilation failed:
  Module build failed: TypeError: Cannot read property 'options' of undefined```

**Comment by FarhadG** [comment]
I know exactly what you mean, @giacomoalonzi. I've tried everything under the sun :)

**Comment by mastilver** [comment]
So @FarhadG 

webpack.config.js
```diff
-       { test: /\.html$/, loader: 'raw' },
+       { test: /app.*\.html$/, loader: 'raw' },
```
package.json
```diff
-    "html-webpack-plugin": "^1.7.0",
+    "html-webpack-plugin": "^2.29.0",
```

@giacomoalonzi You are next! 😄 
Can you give me your loaders please

**Comment by giacomoalonzi** [comment]
@mastilver  thank you man 💃 
```
plugins: articles.map(el => {
    const slug = el.title.toLowerCase().split(' ').join('-').split('.').join('')
    return new HtmlWebpackPlugin({
      title: `${el.title} – Aspisec`,
      filename: `news/${slug}.html`,
      template: `./src/views/news/${el.date}.pug`,
      minify: htmlMinifyOptions,
      cache: true,

    })
  }).concat([ // other things
```

```
{
        test: /\.pug$/,
        exclude: ['/node_modules/'],
        use: [
          'html-loader?attrs[]=img:src&attrs[]=video:src&attrs[]=source:src',
          {
            loader: 'pug-html-loader',
            query: {
              pretty: true,
              export: false,
              baseDir: path.resolve(__dirname, 'src/views'),
              data: {
                language: currentLang,
                global: require(`./src/content/${currentLang}/global.json`),
                home: require(`./src/content/${currentLang}/home.json`),
                about: require(`./src/content/${currentLang}/about.json`),
                services: require(`./src/content/${currentLang}/services.json`),
                careers: require(`./src/content/${currentLang}/careers.json`),
                journal: require(`./src/content/${currentLang}/journal.json`),
                news: require(`./src/content/${currentLang}/news.json`),
                contacts: require(`./src/content/${currentLang}/contacts.json`),
                articles
              }
            }
          }
        ]
      },```

**Comment by mastilver** [comment]
First of all did you try following https://github.com/jantimon/html-webpack-plugin/tree/master/examples/jade-loader
I don't know how pug changed a lot since jade

**Comment by giacomoalonzi** [comment]
@mastilver is the same!
watch at line 4
https://github.com/jantimon/html-webpack-plugin/blob/master/examples/jade-loader/template.jade

**Comment by mastilver** [comment]
@giacomoalonzi remove `html-loader`,

`html-loader` transform `html` into `js` which we don't want here

**Comment by FarhadG** [comment]
@mastilver , if it's not too much, could you try your suggestion with the boilerplate code I provided above. I'm not sure if I'm doing something wrong but it doesn't seem to work at all...

**Comment by giacomoalonzi** [comment]
@mastilver uhm, and which loader I have to use?

**Comment by mastilver** [comment]
@giacomoalonzi @FarhadG you have the same issue: `html-loader` is getting in the way of `html-webpack-plugin`, so you need to setup a regex that match all your html files **but** your template

In short your template shouldn't be matched by the `html-loader`

@giacomoalonzi You are using `pug`, so you just need to setup another loader that only match your template

I don't know what's your file structure, but this should make it obvious:

```diff
-       { test: /\.html$/, loader: 'raw' },
+       { test: /app.*\.html$/, loader: 'raw' },
```

Because my template in not inside the `app` folder, I can configure my loader to only match html that are inside the `app` folder and therefor exclude my template

**Comment by FarhadG** [comment]
That makes sense, @mastilver. Let me give it a try...

**Comment by giacomoalonzi** [comment]
What you mean with "You are using pug, so you just need to setup another loader that only match your template" ?

Whats wrong in this?
```
{
        test: /\.pug$/,
        exclude: ['/node_modules/'],
        use: [
          'html-loader?attrs[]=img:src&attrs[]=video:src&attrs[]=source:src',
          {
            loader: 'pug-html-loader',
            query: {
              pretty: true,
              export: false,
              baseDir: path.resolve(__dirname, 'src/views'),
            }
          }
        ]
      },```

btw thank you so much for your time!

**Comment by mastilver** [comment]
if you need pug template elsewhere in your app (if you do `import profile from './profile.pug'`) then keep that one and create a new one for `html-webpack-plugin` which doesn't use `html-loader`

**Comment by giacomoalonzi** [comment]
uhm... and can you suggest me another loader to do this??

**Comment by mastilver** [comment]
```diff
      {
-        test: /\.pug$/,
+        test: /src/views/.+\.pug$/,
        exclude: ['/node_modules/'],
        use: [
          'html-loader',
          {
            loader: 'pug-html-loader',
            query: {
              pretty: true,
              data: {
                global: require('./src/content/global.json'),
                home: require('./src/content/home.json')
              }
            }
          }
        ]
      },
+      {
+        test: test: /src/views/index\.pug$/,
+        exclude: ['/node_modules/'],
+        use: [
+          {
+            loader: 'pug-html-loader',
+            query: {
+              pretty: true,
+              data: {
+                global: require('./src/content/global.json'),
+                home: require('./src/content/home.json')
+              }
+            }
+          }
+        ]
+      },
```

Something like that

**Comment by FarhadG** [comment]
Worked like a charm! You the man, @mastilver. It was truly troubling, going through all of the examples and nothing appeared to work...

**Comment by mastilver** [comment]
As soon as I have more time on my hand, I will start working on making errors like those more obvious

For reference: Need to investigate if it's possible to get the loaders the template will got through (https://github.com/webpack/webpack/blob/927fc54ed74bd426e1064af9871762b7739566f2/lib/CompatibilityPlugin.js#L48)
If so, check if those loaders includes, throw if that the case

**Comment by FarhadG** [comment]
Yeah, the confusing part was that the plugin could, in fact, inject our assets, so it was confusing trying to debug why it wouldn't pass in data. That's what really threw me off...

**Comment by giacomoalonzi** [comment]
not work for me @mastilver :( I've fixed you regex to `/src\/views\/.+\.pug$/,` but if i remove the html-loader i have this error.
`You may need an appropriate loader to handle this file type.`

**Comment by mastilver** [comment]
>  but in your example, why you have specified the same configuration twice?

It's not the same

**Comment by giacomoalonzi** [comment]
@mastilver yes I know. So, I replicate your code 1:1 but options still undefined. :|

**Comment by mastilver** [comment]
Can you give me some code, I will check it tomorrow

**Comment by giacomoalonzi** [comment]
check this boilerplate 
https://github.com/giacomoalonzi/webpack-webapp/blob/v2/webpack.config.js 
thank you so much for you time! 🙏  but we have to solve this issue 👯  :D

**Comment by mastilver** [comment]
I'm sorry I can't help you!

You gave me a code I already looked at many times, which doesn't contains the changes I told you to apply

**Comment by giacomoalonzi** [comment]
@mastilver updatet, sorry I've forgot to push!

**Comment by mastilver** [comment]
@giacomoalonzi So I don't see your issue, your template is an html one (while you were talking about pug) and I can find `Your App Title` inside the generated html file

**Comment by giacomoalonzi** [comment]
Hi @mastilver what you mean? My templates are .pug not .html. Did you switched to branch-v2 of my webpack-webapp repo?

**Comment by mastilver** [comment]
I was on `master` indeed...
I know what's the issue, give me 10 mins

**Comment by giacomoalonzi** [comment]
no problem @mastilver  :)

**Comment by mastilver** [comment]
Use this, only one rule is needed (contrary to what I was saying earlier...)
make sure to install `pug-loader` rather than `pug-html-loader`

`pug-loader`: returns a function
`pug-html-loader`: returns a string, so it's static and no options can be pass through

```
{
        test: /.pug$/,
        exclude: ['/node_modules/'],
        use: [
          {
            loader: 'pug-loader',
            query: {
              pretty: true,
              data: {
                global: require('./src/content/global.json'),
                home: require('./src/content/home.json')
              }
            }
          }
        ]
      },
```

You will still get an error, in `hero.pug`, but I can't do anything for you there, it's an issue with your code

**Comment by giacomoalonzi** [comment]
Works!! With pug-loader work, but i'm not sure if pug-loader accept 'data' like pug-html-loader.
Btw thank you so much.

**Comment by giacomoalonzi** [comment]
@mastilver I've refactored whole project with pug-loader. 
Data is passed by html-webpack-plugin. Works fantastic! 
Thank you so much for your help. You saved my day! <3
