### ISSUE TITLE
hash per file, not compilationHash

### ISSUE THREAD

**Issue by caub** [jantimon/html-webpack-plugin#748]
https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L440 is not optimal, like noted in #543

Do you accept a PR and an option to chunk per file?

**Comment by mastilver** [comment]
We would definitely consider it, if you manage to make is work nicely, I would be personally up for the change (Not sure what @jantimon opinion on that) :)

I'm not actually sure it's as easy as you thing, but give it a try
I'm closing this one so we can keep conversation on #543
