### ISSUE TITLE
Doesn't inject into body

### ISSUE THREAD

**Issue by yantakus** [jantimon/html-webpack-plugin#750]
I've added an example repo [here](https://github.com/yantakus/html-webpack-plugin-example). As you can see I have `inject: true` option set [here](https://github.com/yantakus/html-webpack-plugin-example/blob/master/internals/webpack/webpack.dev.babel.js#L21). The same with [production config](https://github.com/yantakus/html-webpack-plugin-example/blob/master/internals/webpack/webpack.prod.babel.js#L42).

But it still injects into head. Tried `inject: 'body'` with no luck.

You can just run `npm start` to see it in action.

I'm using:
- webpack v3.3.0
- html-webpack-plugin v2.29.0

Please let me know if you need any additional information.

**Comment by mastilver** [comment]
Can you tell me what index.html output you get, what were you expecting

Currently only the js is impacted by this option not the css

**Comment by yantakus** [comment]
I get the following result:

![lift 2017-07-21 15-52-22](https://user-images.githubusercontent.com/2179726/28464179-b70947f6-6e2c-11e7-8189-39e52ddc2523.png)

And I'm expecting these files to be injected into the body as it is stated in the docs.

**Comment by mastilver** [comment]
Nothing to do with `html-webpack-plugin` those are async chunks (When you use `import()`) that are requested by webpack when needed

`html-webpack-plugin` only take cares about initial chunks

**Comment by yantakus** [comment]
Thanks for the explanation. When I change to `inject: 'head'`, I get this error: `_registerComponent(...): Target container is not a DOM element.` Any ideas?

**Comment by mastilver** [comment]
I know why... but this is not the right place to ask about it... :)

You DOM isn't loaded yet, this is the main reason why most JavaScript scripts are loaded at the end of the body
