### ISSUE TITLE
Clarify EJS delimiter meanings

### ISSUE THREAD

**Issue by ethanresnick** [jantimon/html-webpack-plugin#751]
## Description

At the moment, the docs say that, when no loader is present, an EJS loader is used. But this is confusing/not enough information, as different implementations of EJS use the `<%-` and the `<%=` delimiters differently. Namely, at least [one](https://github.com/sstephenson/ruby-ejs/) ruby implementation of EJS seems to use `<%=` for outputting content without escaping it, like html-webpack-plugin does, but [most](http://ejs.co/) [node](https://github.com/tj/ejs) implementations use `<%=` to signify output _with_ escaping. Conversely, `<%-` means "escape" in the Ruby implementation but means "don't escape" in the Node implementations. Hence issues like #734, where users expect a delimiter to do the opposite of what it does. 

This confusion seems like it could easily lead to people mistakenly not escaping their output, which seems like a security issue. To avoid that, I think the library should clearly document the delimiter conventions it's using, and possibly switch to the convention used by the Node libraries I linked above, which I believe were the canonical implementations of EJS.

**Comment by mastilver** [comment]
> which seems like a security issue

html-webpack-plugin is a build tool, your users can't interact with it

> But this is confusing/not enough information, as different implementations of EJS use the <%- and the <%= delimiters differently. 

The doc clearly state which delimiter to use

> <%- means "escape" in the Ruby implementation but means "don't escape" in the Node implementations.

NO <%- -> is escaping hence why you had your issue, <%= %> doesn't escape 

And if you think the docs are wrong or unclear, just send a PR

**Comment by jantimon** [comment]
Also it is the same implementation like https://github.com/okonet/ejs-loader
