### ISSUE TITLE
add asyncChunks as new configuration option

### ISSUE THREAD

**Issue by borisirota** [jantimon/html-webpack-plugin#759]
## Description

When building an app with dynamic imports, there are some cases where it is beneficial to include link to an async chunk in the html in order to have in page load.

One use case is a fully static app where pages are loaded dynamically based on router. In this case, there is one entry point (for simplicity) which includes all the common code and the async chunks includes the specific code for each page.

In order to support SEO + minimal load time, each page is rendered at build time (e.g. `ReactDomServer.renderToString`) and every html page includes links to the common code and the "async" chuck of that particular page. These assets can be served from a CDN in this case.

One way to require the dynamic imports is with [react-loadable](https://github.com/thejameskyle/react-loadable) with the [babel-plugin-import-inspector](https://github.com/thejameskyle/react-loadable#user-content-babel-plugin-import-inspector) which loads async chunks synchronously if they already present.
This prevents the flickering of serving html to the browser, then react replaces the html with loading component when taking control until the page (async chunk) is loaded, and then setting the same html that was already served with the initial request once the async chuck is loaded -> defeats all the purpose of the html being server rendered.

In order to support this out of the box with `html-webpack-plugin` and because the chucks option doesn't have support for async chunks, there is need to add one more option to the configuration - asyncChunks (which is the same as chunks option but for async chunks).

### Config

```js
//webpack.config.js
const APPS = ['home', 'about', 'profile', ...]

const PATHS = {
  home: '/path',
  about: '/about',
  profile: '/profile',
  ...
}

module.exports = {
  entry: 'index.js',
  ...
  plugins: Object.keys(APPS).map(function (app) {
    return new HtmlWebpackPlugin({
      template: 'html.template.js',
      filename: app + '.html',
      inject: 'head',
      chunksSortMode: 'dependency',
      asyncChunks: [app],
      path: PATHS[app]
    }).concat(new InjectAsyncChunkWebpackPlugin())
}
```

```js
//html.template.js
import { render } from './universal-renderer'

export default function (params) {
  // the render receiving the path of the current page and this way generates specific html for each page
  return `
    <!doctype html>
    <html>
      <head></head>
      <body>
        <div id='app'>${render(params.htmlWebpackPlugin.options.path)}</div> 
      </body>
    </html>
  `
```

Currently, in order to support it, I created the `InjectAsyncChunkWebpackPlugin` plugin:
```js
function InjectAsyncChunksWebpackPlugin () {}

InjectAsyncChunksWebpackPlugin.prototype.apply = function (compiler) {
  compiler.plugin('compilation', function (compilation) {
    compilation.plugin('html-webpack-plugin-alter-chunks', function (chunks, htmlPluginData) {
      var asyncChunks = compilation.getStats().toJson().chunks.filter((chunk) => htmlPluginData.plugin.options.asyncChunks.indexOf(chunk.names[0]) !== -1)
      if (asyncChunks.length) chunks = chunks.concat(asyncChunks)
      return chunks
    })
  })
}

module.exports = InjectAsyncChunksWebpackPlugin
```

## Relevant Links
* [webpack-flush-chunks](https://github.com/faceyspacey/webpack-flush-chunks) - my proposal is to have the same functionality like `webpack-flush-chunks` but on the scripts tags level (which is in the scope of the `html-webpack-plugin`)

As I explained, its beneficial to have this level of flexibility on the async chunks as well.
Is it make sense to have support for that out of the box without this custom plugin ?

Thanks

**Comment by mastilver** [comment]
I probably did not understand your problem properly, but:

If you don't want async chunks, then don't use them! simple :)

**Comment by mastilver** [comment]
you probably want to use: https://github.com/GoogleChrome/preload-webpack-plugin

**Comment by borisirota** [comment]
@mastilver but I do want async chunks and `preload-webpack-plugin` is a solution to a different problem - you did not understand my problem properly :)

On every page I want only the relevant async chuck to be sync. Other chunks should be async so its possible to move to SPA mode with code being loaded dynamically when needed without reloading the browser on every page transition - there is need for more granular configuration for async chunks.

I'll give you a concrete example:

* I have one entry point which includes all the common code - `index.js` - there is a router inside which loaded pages A, B, C and D dynamically.
* I generate the following pages on build time: A.html, B.html, C.html and D.html.

```html
<-- Page A -->
<html>
  <head>
    ...
    <script type="text/javascript" src="/index.js" defer />
    <script type="text/javascript" src="/A.js" defer />
    ...
  </head>
  ...
</html>
```

```html
<-- Page B -->
<html>
  <head>
    ...
    <script type="text/javascript" src="/index.js" defer />
    <script type="text/javascript" src="/B.js" defer />
    ...
  </head>
  ...
</html>
```

```html
<-- Page C -->
<html>
  <head>
    ...
    <script type="text/javascript" src="/index.js" defer />
    <script type="text/javascript" src="/C.js" defer />
    ...
  </head>
  ...
</html>
```

```html
<-- Page D -->
<html>
  <head>
    ...
    <script type="text/javascript" src="/index.js" defer />
    <script type="text/javascript" src="/D.js" defer />
    ...
  </head>
  ...
</html>
```

This way, the html on every page won't be re-rendered because the page already present and loaded synchronously.
On every page, all other chunks should remain async and loaded dynamically and asynchronously only when needed. The logic inside `index.js` in the router component responsible for that.

Is the scenario make sense now ?

**Comment by mastilver** [comment]
> On every page I want only the relevant async chuck to be sync.

I have to insist... don't use async chunks if you don't want them :)

you probably want to use: https://webpack.js.org/plugins/commons-chunk-plugin/#components/sidebar/sidebar.jsx

**Comment by borisirota** [comment]
@mastilver Your solution is to make multiple entries (entry for every page) ? if so, it isn't the most suitable model for this architecture IMHO.

I started this way but then moved to a single entry point because the split point is on the `main` component of the router. all other components and logic are common.
This way it enables you to load the app from every page and then move to SPA mode where page transitions are client side only without refresh. Why load all assets again when there is need to fetch only one chunk ?
In addition, setting DOM mounting, HMR and other stuff on every entry point is tedious, especially when there is no real need for that.
There were additional reasons which i don't remember right now.

> don't use async chunks if you don't want them

I don't see it that way. I see them as async chunks, use them as such and I need all of them as async chunks except of one in specific context only - this specific async chunk is still async on other pages.

Adding granular configuration for asyncChunks adds support to [webpack v3.5.0](https://github.com/webpack/webpack/releases/tag/v3.5.0) release which adds the `import(/* webpackMode: "weak" */ "module")`, [react-loadable webpackRequireWeakId](https://github.com/thejameskyle/react-loadable#user-content-babel-plugin-import-inspector) and other modules where their purpose it to load async chunks synchronously if present.

The custom plugin I made is very simple but IMHO the user should be able to configure it as part of the core functionality.

Boris

**Comment by jantimon** [comment]
I guess that's possible if you use a custom template and set `inject:false`

**Comment by mastilver** [comment]
> Adding granular configuration for asyncChunks adds support to webpack v3.5.0 release which adds the import(/* webpackMode: "weak" */ "module")

Yeah that make more sense now ;)

> Wanted to know your thoughts about making asyncChunks first class citizens in html-webpack-plugin configuration

I think a plugin similar to `preload-webpack-plugin` would be the best

**Comment by borisirota** [comment]
Cool thanks !
