### ISSUE TITLE
HMR triggers full page reload since version 2.30.1 with webpack 3.x

### ISSUE THREAD

**Issue by hendrikeng** [jantimon/html-webpack-plugin#760]
## Description

Since i upgraded `html-webpack-plugin` to version 2.30.1 HMR doesn't work anymore.
It always triggers a full page reload (inject js or scss).

The same config does work with `html-webpack-plugin@2.28.0`, `webpack@2.6.1` and `webpack-dev-server@2.5.0`

### Config
```js
 devServer: {
    hot: true,
    inline: true,
    quiet: true,
    contentBase: path.resolve(__dirname, pkg.paths.src.templates),
  watchContentBase: true,
    watchOptions: {
      poll: false, // might be needed for homestead/vagrant setup, review
    },
}
.
.
.
 new HtmlWebpackPlugin({
      template: pkg.paths.src.ejs + pkg.vars.ejsName,
      filename: pkg.paths.src.templates + pkg.vars.templateName,
      inject: true,
      alwaysWriteToDisk: true,
    }),
```

## Environment

```
webpackalet@0.1.0
├─┬ favicons-webpack-plugin@0.0.7
│ └── webpack@1.15.0
└── webpack@3.5.3

webpackalet@0.1.0
└── html-webpack-plugin@2.30.1
```

**Comment by jantimon** [comment]
Well I just checked with the changelog:

> v2.30.1
> 
> Revert part the performance optimization (#723) because of #753.
> v2.30.0
> 
> Add manual sort
> Performance improvements (#723)
> v2.29.0
> 
> Add support for Webpack 3

And I can't imagine why this would change the HMR behaviour - could you try to debug your environment a little bit and give us an idea where to start?

**Comment by hendrikeng** [comment]
I will setup a minimal repo for testing and post it. Thanks a lot. 

_Sent from my Samsung SM-G920F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hendrikeng** [comment]
@jantimon 

this is the minimal repository:

https://github.com/hendrikeng/webpackHMRtest 

but it seems like its webpack 3 related ..everything works fine , but as soon as i update webpack to 3.x HMR in js or scss triggers a full reload ...should i move the issue to webpack then? 

thanks a lot for your help.

**Comment by jantimon** [comment]
Yes I guess that would be the best way :)
