### ISSUE TITLE
Using bluebird's Promises to init Webpack config with HtmlWebpackPlugin triggers a warning

### ISSUE THREAD

**Issue by ngyikp** [jantimon/html-webpack-plugin#762]
### Error Message & Stack Trace

Not a severe error, everything works fine, but it's semi-annoying to see this pop up every time I relaunch Webpack (plus I guess it could be masking a nastier bug)

```
(node:21434) Warning: a promise was created in a handler at /Users/ngyikp/Desktop/test/node_modules/webpack/bin/webpack.js:383:13 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (/Users/ngyikp/Desktop/test/node_modules/bluebird/js/release/promise.js:79:10)
```

Unfortunately the stack trace is not useful :(

### Config

```js
'use strict';

const Promise = require('bluebird'); // <-- removing this line to use native Promise will fix the issue
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = Promise.resolve({
	entry: './app',
	output: {
		path: '/tmp/',
		filename: '[name]',
	},
	plugins: [
		new HtmlWebpackPlugin(), // <-- or this
	],
});
```

The issue only happens if I use bluebird's Promise to init my Webpack config and HtmlWebpackPlugin together.

## Relevant Links

https://github.com/ngyikp/html-webpack-plugin-bug-demo

## Environment

```
$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v8.3.0
darwin 16.7.0

$ npm --version
5.3.0

$ npm ls webpack
/Users/ngyikp/Desktop/test
└── webpack@3.5.4 

$ npm ls html-webpack-plugin
/Users/ngyikp/Desktop/test
└── html-webpack-plugin@2.30.1 
```

**Comment by mastilver** [comment]
I think it's because we are mixing `Promise` and callback

Unless the above statement is wrong, I don't think, if will ever be fixed

**Comment by mastilver** [comment]
Actually, I was wrong we are already using `bluebird`, maybe it's because the two version are different: https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L5

**Comment by jantimon** [comment]
Node was required for node 0.10 but now for webpack 2 we can probably drop that dependency

**Comment by ngyikp** [comment]
v3.0.0 no longer uses bluebird
https://github.com/jantimon/html-webpack-plugin/pull/861/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L46
