### ISSUE TITLE
Cannot read property 'hash' of undefined only when using KARMA

### ISSUE THREAD

**Issue by c0debreaker** [jantimon/html-webpack-plugin#763]
I get the error **`ERROR in TypeError: Cannot read property 'hash' of undefined`** when I run **`karma start`**. It works perfectly when I execute **`npm run build`**.

I have this code in my index.html template.

```
 if (<%= JSON.stringify(htmlWebpackPlugin.options.myApp || '') %>) {
   window.myHash = <%= JSON.stringify(htmlWebpackPlugin.files.chunks[htmlWebpackPlugin.options.myApp].hash) %>
 }
```

**Comment by jantimon** [comment]
Probably your karma config is different from your build config..
There is nothing we can fix here - please take a look at your configs and move this issue to stackoverflow :)

**Comment by c0debreaker** [comment]
I figured it out by updating the way I'm reading htmlWebpackPlugin.files.chunks[htmlWebpackPlugin.options.myApp].hash. I'm now using _.get and it's not spitting out the errors anymore.
