### ISSUE TITLE
Need optional `evaluateCompilationResult `

### ISSUE THREAD

**Issue by ccqgithub** [jantimon/html-webpack-plugin#764]
## Description

Now, if i use this plugin with `html-loader`, it will also make `evaluateCompilationResult` that we  not really need.

Because `html-loader` can search js dependences from `script:src` and make them as modules, these modules may contains some vars that the nodejs not have (such as window)....

So, if I use `html-loader` like this:

```
{
        test: /\.html$/,
        use: [{
          loader: 'html-loader',
          options: {
            attrs: ['img:src', 'script:src'],
            minimize: true,
            removeComments: false,
            collapseWhitespace: false,
            removeAttributeQuotes: false,
            interpolate: 'require',
          }
        }]
      },
```

It will throw a error : `window is not defined`, the reason is one module of the html dependencies that made from 'script:src' has the `window` variable (what will throw errors when run `evaluateCompilationResult` in nodejs vm).

So, can only run `evaluateCompilationResult` with the html  it self but not with it's dependencies ? 
Or add a options to control it with different template formats ?

**Comment by mastilver** [comment]
You should not use this plugin with `html-loader`

**Comment by mastilver** [comment]
I recommend you use the `exclude` options for your rule
