### ISSUE TITLE
How to add favicon to styleguide document?

### ISSUE THREAD

**Issue by hueyhe** [jantimon/html-webpack-plugin#765]
Hi, I'm trying to add a favicon to my styleguide document via HtmlWebpackPlugin. However, in [Configuring webpack](https://react-styleguidist.js.org/docs/webpack.html) it mentioned that `HtmlWebpackPlugin` would be ignored cause styleguidist also has this plugin. So how can I add favicon to the generated html page? Is there another way to achieve it?

**Comment by mastilver** [comment]
Wrong place to ask, please open an issue on there repository

**Comment by hueyhe** [comment]
What a mistake! Sorry! I was checking docs here and then just switched to the issues tab directly without changing repository. 😅
