### ISSUE TITLE
Access custom variable, without plugin namespace inside of template

### ISSUE THREAD

**Issue by 1ven** [jantimon/html-webpack-plugin#767]
Currently it's possible to access custom variables via `htmlWebpackPlugin.options.[myrVariableName]`
Is there a way to access `myVariable` directly, without `htmlWebpackPlugin.options` path?

I'm asking this, as I'm planning to use the one html template file on a server and webpack, so it's a  little bit dirty to use `htmlWebpackPlugin.options` when rendering template on server.

**Comment by mastilver** [comment]
Hi @1ven 

We won't be supporting that, but it may be possible to do it by assigning a variable at the top of your template that will pick either yours or `htmlWebpackPlugin.options`

I don't know if it's possible though...
