### ISSUE TITLE
Refactor request: replace Bluebird promises with native promises.

### ISSUE THREAD

**Issue by filipesilva** [jantimon/html-webpack-plugin#772]
## Description

This is a feature/refactor request.

`html-webpack-plugin` currently uses Bluebird promises, which use `try...catch`. Such blocks are a known de-optimization (https://github.com/GoogleChrome/devtools-docs/issues/53#issuecomment-175904780) in some versions of V8, like the one present in Node 6 (current LTS). Node 6 also has native promise support though.

Thus using Bluebird promises can cause decreased performance. Below are a few screenshots of a Webpack rebuild, showing the deopt is occurring (all within the `innerArrayForEach` group):

![image](https://user-images.githubusercontent.com/4172079/29824152-99e576ee-8cc8-11e7-8494-7ec1312c5f3b.png)
![image](https://user-images.githubusercontent.com/4172079/29824187-b1bfa5fa-8cc8-11e7-8fa9-7698cbd8978e.png)

I tried replacing this specific use of Promise (it's the one in `html-webpack-plugin/lib/compiler.js (compileTemplate)` with a native promise and I observed roughly 200ms savings on a rebuild in that function group:
![image](https://user-images.githubusercontent.com/4172079/29824316-22afbb74-8cc9-11e7-8de5-e1bc0de5867b.png)

This doesn't mean that all builds would benefit from the same reduction, but since rebuild performance is of high value perhaps this is a worthwhile refactor.

It's worth mentioning that in the V8 engine 6.0 this isn't relevant anymore: https://www.nearform.com/blog/node-js-is-getting-a-new-v8-with-turbofan. But that might be a ways off for a lot of users.

## Environment
```
Node.js v6.11.1
win32 10.0.15063
npm 5.3.0
webpack@3.5.5
html-webpack-plugin@2.30.1
```

**Comment by mastilver** [comment]
https://github.com/jantimon/html-webpack-plugin/issues/762#issuecomment-325685323
> Node was required for node 0.10 but now for webpack 2 we can probably drop that dependency

If you want to submit a PR, go ahead :)

**Comment by filipesilva** [comment]
Here is a PR for it :https://github.com/jantimon/html-webpack-plugin/pull/776. Travis seems happy with it.

**Comment by ngyikp** [comment]
v3.0.0 no longer uses bluebird, this issue can be closed
https://github.com/jantimon/html-webpack-plugin/pull/861/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L46
