### ISSUE TITLE
Build HTML from parts

### ISSUE THREAD

**Issue by alxpsr** [jantimon/html-webpack-plugin#774]
Hi there!
I want build html page from small parts, like this:

## part_1.html
```
<h1>This is first part of big component<h1>
```
## part_2.html
```<h2>This is 2nd part of big component<h2>```

## part_3.html
```<h3>This is 3rd part of big component<h3>```

## section.html (contains all parts from above after webpack compilation)
```
<section>
  <h1>This is first part of big component<h1>
  <h2>This is 2nd part of big component<h2>
  <h3>This is 3rd part of big component<h3>
</section>
```

What is the right way to do this? 
1) HTMLWebPackPlugin ?
2) ejs-loader with <% include ... %> ?
3) any?

**Comment by mastilver** [comment]
I think the right way to achieve that is to use whatever template engine you are using gives you

In your case ejs-loader gives you `<% include ... %>`? Then use that to includes parts
