### ISSUE TITLE
index.html output has some formatting issue in <script> and <link> tags

### ISSUE THREAD

**Issue by petrdanecek** [jantimon/html-webpack-plugin#775]
## Description

The generated index.html is valid, however the injected <script> and <link> tags causes formatting problem. See below examples, the both tags are not properly indented and </head>/</body> tags are inlined with <script>/<link>. They are supposed to be on new line and indented.

Opening the issue without using the template, but the same behavior is experienced with custom template.

### Error Message & Stack Trace
This is the index.html result:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Portal - Login</title>
  <link href="/static/bundles/common-522733bd.css" rel="stylesheet"></head>
  <body>
  <script type="text/javascript" src="/static/bundles/runtime-8d18c8e4.js"></script><script type="text/javascript" src="/static/bundles/vendor-59a0263f.js"></script><script type="text/javascript" src="/static/bundles/common-977057ca.js"></script></body>
</html>
```

### Config
```js
      new HtmlWebpackPlugin({
        title: 'Portal - Login',
        filename: path.join(DEFAULTS.projectDir, 'backend/common/templates/common/index.html'),
        chunks: ['runtime', 'vendor', 'common'],
      }),

```

Copy your template file:
Tested without template, however the same is observed with template as well.

## Environment
```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v7.7.1
linux 2.6.32-642.15.1.el6.x86_64

 npm --version
4.1.2
npm ls webpack
Django-React@1.0.0 /home/petr/djangoreact
└── webpack@3.5.5

npm ls html-webpack-plugin
Django-React@1.0.0 /home/petr/djangoreact
└── html-webpack-plugin@2.30.1


```

**Comment by mastilver** [comment]
I'm sorry, we are not going to fix that

This is a non-issue, it shouldn't matter how your generated html file looks like

**Comment by petrdanecek** [comment]
ok np. Is there any workaround? I'm using customized template so maybe I can select the place where the tags are inserted. I just migrated from django-webpack-loader where it was no problem.

Thanks.

**Comment by mastilver** [comment]
How is it causing you an issue? I'm not following...

**Comment by mastilver** [comment]
you can always set `inject` to `false` and loop through the js files in your template, but I think it's unnecessary.

**Comment by petrdanecek** [comment]
I'm preparing migration from webpack-loader to your html-webpack-plugin which I like.  We don't minify the html. The rest of the team is not going to accept html plugin as long as the output (index.html) file is different.
Anyway thanks for the workaround, going to test it.
