### ISSUE TITLE
HTMLs are fully recompiled in watch mode when have multi html entries

### ISSUE THREAD

**Issue by exports** [jantimon/html-webpack-plugin#778]
I have a webpack project that has about 30 html pages, use html-webpack-plugin makes the rebuild time increases 400% (1s to 5s). Can we only invoke the child compiler only if related chunks are changed?

**Comment by githoniel** [comment]
me too. 
i think this PR should work. or use this https://github.com/jantimon/html-webpack-plugin/pull/797
but for me, I use webpack2 now...

**Comment by jantimon** [comment]
I believe this is still relevant for the current version but it needs some work.  
Open for pull requests.

**Comment by jantimon** [comment]
Performance findings by different users for v4:
+ https://github.com/jantimon/html-webpack-plugin/issues/962#issuecomment-409070361
+ https://github.com/jantimon/html-webpack-plugin/pull/953#issuecomment-395040726
+ https://github.com/jantimon/html-webpack-plugin/pull/953#issuecomment-417408140

Give it a try: 
https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-alpha.2
