### ISSUE TITLE
Hot Reloading Not Working WIth HtmlWebpackPlugin

### ISSUE THREAD

**Issue by developer239** [jantimon/html-webpack-plugin#785]
# Description

Hot module reloading is not working with `HtmlWebpackPlugin`.

### Config / Relevant Links

Repository: https://github.com/developer239/workbox-webpack-react/tree/ssr
Server File: https://github.com/developer239/workbox-webpack-react/blob/ssr/server.js
Webpack Base: https://github.com/developer239/workbox-webpack-react/blob/ssr/webpack.common.js
Webpack Dev: https://github.com/developer239/workbox-webpack-react/blob/ssr/webpack.dev.js
Package.json: https://github.com/developer239/workbox-webpack-react/blob/ssr/package.json

## Environment

npm 4.2.0

node 7.10.0

**Comment by mastilver** [comment]
What do you mean by hot reloading?

is it the js part or the html part

I got the js part working, but unless you use another plugin, you can hot reload the html file generated by `html-webpack-plugin`

**Comment by developer239** [comment]
https://media.giphy.com/media/3ohhwN1ypP9RBU4YaA/giphy.gif

**Comment by developer239** [comment]
@mastilver 

When I change jsx in my app I see that my app is being updated in the console. But I can't see the changes being propagated to the browser.  I am trying to figure out for hours now...

I work in branch ssr https://github.com/developer239/workbox-webpack-react/tree/ssr . Please see the giphy bellow.

![](https://media.giphy.com/media/3ohhwN1ypP9RBU4YaA/giphy.gif)

**Comment by mastilver** [comment]
I'm sorry, this is unrelated to this plugin

Please follow:
- https://github.com/gaearon/react-hot-boilerplate/blob/next/webpack.config.js
- https://github.com/gaearon/react-hot-boilerplate/blob/next/src/index.js

Otherwise stackoverflow is a better place to ask those questions

**Comment by developer239** [comment]
@mastilver I believe that this is related to your plugin. You did not even look at my source code... :( I also tried to ask people on stackoverflow. Nobody helped.

Hot reloading is working fine without your plugin.

**Comment by developer239** [comment]
@Madalosso react-hot-boilerplate is not even using htmlwebpackplugin...

**Comment by fancyboynet** [comment]
@developer239 I have the same issue now, have you resolved that?
