### ISSUE TITLE
Inline demo

### ISSUE THREAD

**Issue by aastudio** [jantimon/html-webpack-plugin#788]
The inline folder demo is not the right one : it's the jade demo.

**Comment by jantimon** [comment]
that's interesting - actually it was never planned to check it in as the ExtractTextPlugin did not work for isomorphic examples like that.

**Comment by buoyantair** [comment]
Hi I'm interested in this issue, can someone please elaborate this issue? I get the the inline folder doesn't seem to have the example it is originally dedicated for, inline demo.

**Comment by blaise-io** [comment]
The inline Jade demo confused the fork out of me, so I tried creating two inline demos using html. Feel free to copy and please let me know if you find a bug.

 1. [Really simple example with hard-coded assets](https://github.com/blaise-io/html-webpack-plugin/tree/hard-coded/examples/inline-simple)
 2. [Slightly more complex example with dynamic assets](https://github.com/blaise-io/html-webpack-plugin/blob/all-assets/examples/inline-simple/template.html)

**Comment by niksajanjic** [comment]
Inline examples have an issue where they still emit files and there are no options to prevent emitting. Because of that, we need to use `ignore-emit-webpack-plugin` to prevent them from emitting, but I feel this lib should provide that option by itself.

**Comment by jantimon** [comment]
@niksajanjic please open a detailed issue for that bug
