### ISSUE TITLE
Template still puts in regular bundle

### ISSUE THREAD

**Issue by nvrgrwld** [jantimon/html-webpack-plugin#790]
Maybe this is a feature.  Maybe I am using it wrong.
But when I make a template, the original bundle still shows up, even if I have used a template to display it.

// from webpack.config.js
```
        new HtmlWebpackPlugin({
           filename: '../Views/Dashboard/Index.cshtml',
            template: './Views/Dashboard/webpackTemplate.cshtml',
        })
```
// from my template
`<script type="text/javascript" src="/dist<%= htmlWebpackPlugin.files.js%>"></script>`

// what gets output
`<script type="text/javascript" src="/dist/app_6ef028de58c023cfe340.js"></script>` (from template)
`<script type="text/javascript" src="/app_6ef028de58c023cfe340.js"></script>` (autogenerated)

Can I turn off the auto generated one?

Like I said, maybe I am abusing the system.  You tell me if I am doing it illegally or wrong.

Thanks,
Greg

**Comment by mastilver** [comment]
Yep, that's a feature... set `inject` to `false`
https://github.com/jantimon/html-webpack-plugin#configuration

**Comment by nvrgrwld** [comment]
Thanks @mastilver , I assumed from the documentation that `inject` equals `false` would turn off all injecting, including the template stuff.

Thanks,
Greg
