### ISSUE TITLE
loader query not accepted by fallback ejs loader

### ISSUE THREAD

**Issue by raiRaiyan** [jantimon/html-webpack-plugin#800]
#### Config
This is my sripped down config

```
    var webpack = require('webpack');
    var path = require('path');
    var HtmlWebpackPlugin = require('html-webpack-plugin');
       
    module.exports = {
      entry: {
        bundle: './src/index.js'
      },
      output: {
        path: path.join(__dirname, 'dist'),
        filename: '[name].[chunkhash].js'
      },
      module: {
     plugins: [
        new HtmlWebpackPlugin({
          template: 'src/index.html?{interpolate: /<%=([\s\S]+?)%>/g }',
          inject: true
        })
      ],
    };
```
I have the query here because I [dont want the loader to interpolate](https://github.com/lodash/lodash/issues/399) the variables in index.html.  

#### Template
My index.html has a script tag like the following (It will be served by a spring server which will interpolate the varaiables within `${}`):

```
<script th:inline="javascript">
    /*<![CDATA[*/
        let foo = /*[[${foo}]]*/ {};
        foo.bar = /*[[${bar}]]*/ {};
    /*]]>*/
 </script>
```
#### Error

```
ERROR in Template execution failed: ReferenceError: foo is not defined
```  

The fallback ejs loader does not accept that query. I saw a similar [issue](https://github.com/jantimon/html-webpack-plugin/issues/664), and I have resolved this by using 'html-loader'.  But it will be good if I can pass query to the fallback loader  to deactivate the delimiter in lodash and not use an extra loader.

**Comment by mpseidel** [comment]
Also want to use the resource query in the fallback loader. Currently trying to get it to work with `ejs-html-loader` but also struggling there :)

**Comment by mpseidel** [comment]
Gave it a stab and made it working by modifying `loader.js`

```
  // The following part renders the tempalte with lodash as aminimalistic loader
  //
  // Get templating options
  var options = loaderUtils.parseQuery(this.query);
  // Webpack 2 does not allow with() statements, which lodash templates use to unwrap
  // the parameters passed to the compiled template inside the scope. We therefore
  // need to unwrap them ourselves here. This is essentially what lodash does internally
  // To tell lodash it should not use with we set a variable


  function getResourceQuery(ctx) {
    return (0, loaderUtils.parseQuery)(ctx.resourceQuery || "?");
  }

  var data = _.defaults(options, { variable: 'data' }, getResourceQuery(this));
  var template = _.template(source, data);
  // All templateVariables which should be available
  // @see HtmlWebpackPlugin.prototype.executeTemplate
  var templateVariables = [
    'compilation',
    'webpack',
    'webpackConfig',
    'htmlWebpackPlugin'
  ];
  return 'var _ = require(' + loaderUtils.stringifyRequest(this, require.resolve('lodash')) + ');' +
    'module.exports = function (templateParams) {' +
    // Declare the template variables in the outer scope of the
    // lodash template to unwrap them
    templateVariables.map(function (variableName) {
      return 'var ' + variableName + ' = templateParams.' + variableName;
    }).join(';') + ';' +

    Object.keys(data).map(function (queryVariableName) {
      return 'var ' + queryVar + ' = ' + JSON.stringify(data[queryVariableName]);
    }).join(';') + ';' +

    // Execute the lodash template
    'return (' + template.source + ')();' +
    '}';
```

Not sure though if that's the way to go or if it would break something.

**Comment by expressiveco** [comment]
interpolate property expects a RegExp object, you could mimick a regexp, [check this](https://github.com/jantimon/html-webpack-plugin/issues/829).

**Comment by expressiveco** [comment]
Why not 
```javascript
return loaderUtils.parseQuery(cts.resourceQuery || "?")
```
but 
```javascript
return (0, loaderUtils.parseQuery)(ctx.resourceQuery || "?");
```
I am just curious about your intention, is it an IIFE remnant thing?

**Comment by mpseidel** [comment]
I think I copied that line from somewhere else so no intention from me. I prefer the regular call as well actually.

**Comment by jantimon** [comment]
If you need a better lodash loader please don't use the fallback loader of the html webpack plugin.
This will allow you to use any template language you want while keeping the complexity of the html-webpack-plugin smaller.

**Comment by mpseidel** [comment]
@jantimon agree that the fallback loader should not be bloated with features that are out of scope. In my case I needed access to the `resourceQuery` data and accessing that in the html webpack plugin was the quickest way without the need of adding other loaders.
