### ISSUE TITLE
HtmlWebpackPlugin not generating correct relative path for bundle.js file

### ISSUE THREAD

**Issue by alexanderwhatley** [jantimon/html-webpack-plugin#803]
The plugin is adding some additional path to the front of the name of the bundle file, which is not what I want. I have the bundle file in the folder called 'static', and the generated index.html and template index_template.html are [inside the 'templates' folder. My config file is below:

```
	entry: ['./js/main.js'],
	output: {
		filename: "static/bundle-[hash].js"
	},
	resolveLoader: {
	moduleExtensions: ['-loader']
	},
	plugins: [
			new CleanWebpackPlugin(['static/bundle-*.js'], {watch: true}),
			new HtmlWebpackPlugin({
				filename: 'templates/index.html',
				template: 'templates/index_template.html',
				inject: 'body'
			})
	],
```
It adds the following line to the index.html file:

`<script type="text/javascript" src="../static/bundle-b9e19068d6fec1ee28fc.js"></script>`

I want the `bundle-b9e19068d6fec1ee28fc.js` part only, without the additional path in front, as this is what the Flask server I am using will be serving. How do I do this?

**Comment by mastilver** [comment]
set `output.path` to `__dirname + '/static` and `output.filename` to `bundle-[hash].js`

**Comment by alexanderwhatley** [comment]
I tried that already; it doesn't work. That causes a 'templates' folder to be created inside the 'static' folder. Is there a way to override the path in the constructor of the HtmlWebpackPlugin object? Thanks.

**Comment by mastilver** [comment]
`filename: __dirname + '/templates/index.html'`

**Comment by alexanderwhatley** [comment]
Sorry, but that's still making 'src="../static/bundle-1ec6dccc3bf7a1ffdfad.js"' in the created index.html file.

**Comment by mastilver** [comment]
Can you provide me with a repo to reproduce it

**Comment by alexanderwhatley** [comment]
Yep, here it is:
https://github.com/alexanderwhatley/html_webpack_plugin_issue/tree/master.
Thanks for your help.
ᐧ

**Comment by mastilver** [comment]
Damn... forgot one thing: `output.publicPath: "/"`
