### ISSUE TITLE
While used with AgressiveSplittingPlugin doesn't emit chunks to html file

### ISSUE THREAD

**Issue by Morishiri** [jantimon/html-webpack-plugin#804]
## Description
While used with Aggressive Splitting Plugin - chunks are not being emitted into `html` file.

### Error Message & Stack Trace

N/A

### Config

Copy the relevant section from `webpack.config.js`.

```js
const webpack = require('webpack');
const path = require('path');
const htmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: './index.js',
    output: {
        filename: '[id].bundle.js',
        path: path.resolve(__dirname, 'dist')
    },
    plugins: [
        new webpack.optimize.AggressiveSplittingPlugin({
            maxSize: 20 //small size because of small input files
        }),
        new htmlWebpackPlugin({
            filename: 'ready.html'
        })
    ]
}
```

Copy your template file:

*Using default*

## Relevant Links

Here is a repository with minimal reporductible example: https://github.com/Morishiri/hwp-asp-plugins-error output is located in `dist` directory.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v6.11.2
linux 4.13.5-200.fc26.x86_64
```
```
$ npm --version
3.10.10
```
```
$ npm ls webpack
wp-asp-error-repo@1.0.0 /home/xxx/yyy/hwp-asp-error-repo
└── webpack@3.8.1 
```
```
$ npm ls html-webpack-plugin
hwp-asp-error-repo@1.0.0 /home/xxx/yyy/hwp-asp-error-repo
└── html-webpack-plugin@2.30.1 
```

**Comment by mastilver** [comment]
Thank you for the detailed issue! :)

> Here is a repository with minimal reporductible example: https://github.com/Morishiri/hwp-asp-plugins-output is located in dist directory.

The link is dead

**Comment by Morishiri** [comment]
Oh, sorry - typo. Here it is: https://github.com/Morishiri/hwp-asp-plugins-error . Also updated in issue description.

**Comment by jantimon** [comment]
@Morishiri could you please try if #953 solves this issue?

**Comment by Morishiri** [comment]
@jantimon Sorry for long time without response. I was not on github for a moment.

I tried that and it looks like it is working right now.

I pushed the new results to `fixed` (https://github.com/Morishiri/hwp-asp-plugins-error/tree/fixed) branch so you could see for yourself.
