### ISSUE TITLE
Multiple loader overrides results in Javascript "exports.module" in the generated html

### ISSUE THREAD

**Issue by 5argon** [jantimon/html-webpack-plugin#805]
For example, I have the following template to be made into HTML :

index.ejs
```html
<%- include src/test %>
<img src="./img/HeaderImage.png"/>
```
test.ejs
```html
<h1>Hello</h1>
```

```js
  plugins: [
    new HtmlWebpackPlugin(),
    chunks: [page],
            filename:  "index.html",
            template: "./src/index.ejs"
  ]
```
I need to use `html-loader` in order to change the `<img>` tag's `src` [This page](https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md) says if I override `html-loader` the fallback `ejs` will be disabled, and so I would not be able to resolve the EJS tag.

There is no solution written after that so I guess I should override with 2 loaders. There are 4 cases that I tried as in these comments :

```js
rules: [
            { 
                test: /\.ejs$/, 
                use: ['ejs-compiled-loader']   //Works fine
                //use: ['html-loader']  //Works fine
                //use: ['ejs-compiled-loader','html-loader']  //Javascript output
                //use: ['html-loader','ejs-compiled-loader'] //Javascript output
            }
```

Only `ejs-compiled-loader` outputs HTML : (as expected)
```html
<h1>Hello</h1>
<img src="./img/HeaderImage.png"/>
```

Only `html-loader` outputs HTML : (as expected)
```html
<%- include src/test %>
<img src="45d78e258eec2443808aa863a25605a5.png"/>
```

`use: ['ejs-compiled-loader','html-loader'] ` outputs HTML : (**not** as expected)
```html
module.exports = "<h1>Hello</h1>\n<img src=\"" + require("./img/HeaderImage.png") + "\"/>\n\n";
```
`use: ['html-loader','ejs-compiled-loader'] ` outputs HTML : (**not** as expected)
```html
module.exports = function anonymous(locals, filters, escape, rethrow) {
    escape = escape || function(html) {
        return String(html).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/'/g, "&#39;").replace(/"/g, "&quot;");
    };
    var __stack = {
        lineno: 1,
        input: '<%- include src/test %>\n<img src="45d78e258eec2443808aa863a25605a5.png"/>\n.....
```

**Comment by jantimon** [comment]
That's how those loaders work - they compile HTML into Javascript.

If you combine them you will compile the HTML to Javascript and the resulting Javascript again in Javascript which will fail as the loader expects it to be HTML.
