### ISSUE TITLE
What is "chunk" in webpack?

### ISSUE THREAD

**Issue by FlamesoFF** [jantimon/html-webpack-plugin#806]
What does mean "chunk" in this plugin? What does this term mean in webpack? How webpack with this plugin can separate "dev" chunk from "prod" chunk, or any other?
Where I can find any information about how to configure that chunks? Oficial documentation has neither of explanation for the exact term, nor how to configure these "chunks" in webpack. What is that a mystery part of webpack that I don't know?
Or this is something for granted?

Link: https://github.com/jantimon/html-webpack-plugin#filtering-chunks

**Comment by jantimon** [comment]
Please take a look at this documentation:

https://webpack.github.io/docs/code-splitting.html
