### ISSUE TITLE
Feature request: inject with query string params

### ISSUE THREAD

**Issue by Owumaro** [jantimon/html-webpack-plugin#811]
### Feature request

Here is my use case: I'm building a js library with webpack and I have an HTML preview page including the js lib. The js lib allows query string params that changes its behavior.

The html webpack plugin allows me to test the library easily, however I can't add query string params to the js script tag.

It would be nice to be able to inject the script with specific query string. For example, if I use a configuration like this :
```
new HtmlWebpackPlugin({
  filename: 'index.html',
  template: 'index.html',
  inject: true,
  injectQueryString: {
    key: 123,
    ver: '1.0'
  }
})
```
Then the generated HTML file would have a script tag with the query string `?key=123&ver=1.0`.

I don't know if this is really possible, especially with more complex webpack bundles creating multiple scripts.

**Comment by jantimon** [comment]
Just disable inject: true and write a custom template

**Comment by adinvadim** [comment]
But what about case, when I want hash suffix and querystring params?

**Comment by cpselvis** [comment]
I also need this feature.

**Comment by jantimon** [comment]
This is already possible using custom templates - please take a look at the readme and at the example section
