### ISSUE TITLE
Bluebird is included in output

### ISSUE THREAD

**Issue by StephanBijzitter** [jantimon/html-webpack-plugin#812]
## Description
I've noticed that using html-webpack-plugin introduces bluebird, as it's compiled into my javascript bundle. This should not happen, as bluebird is way too big. It adds 22KB to our GZIPped size, without providing any value at all.

### Error Message & Stack Trace
None.

### Config

Excerpt from yarn.lock, where this is the only occurrence of bluebird.
```
bluebird@^3.4.7:
  version "3.5.0"
  resolved "https://registry.yarnpkg.com/bluebird/-/bluebird-3.5.0.tgz#791420d7f551eea2897453a8a77653f96606d67c"

html-webpack-plugin@^2.30.1:
  version "2.30.1"
  resolved "https://registry.yarnpkg.com/html-webpack-plugin/-/html-webpack-plugin-2.30.1.tgz#7f9c421b7ea91ec460f56527d78df484ee7537d5"
  dependencies:
    bluebird "^3.4.7"
    html-minifier "^3.2.3"
    loader-utils "^0.2.16"
    lodash "^4.17.3"
    pretty-error "^2.0.2"
    toposort "^1.0.0"
```
Bluebird is somehow included in our javascript bundle:
<img width="775" alt="screen shot 2017-11-21 at 13 11 12" src="https://user-images.githubusercontent.com/1649903/33072035-2921edd8-cebe-11e7-8c21-a8dd4786ac6c.png">

Copy the relevant section from `webpack.config.js`:
This is irrelevant to the issue.

Copy your template file:
This is irrelevant to the issue.

## Environment
Node 8.9.1, NODE_ENV=production, npm is not used, yarn 1.3.2, webpack 3.8.1, html-webpack-plugin 2.30.1

**Comment by jantimon** [comment]
Maybe because of the common chunks plugin?

Can you try to find out which part of your output code is requiring bluebird?

**Comment by StephanBijzitter** [comment]
That's a good question.

Yes, I found the file. Apparently, a few months ago (according to the git history), we/my-team/john doe, committed this little line of code: `import Promise from 'bluebird';` Uh, yeah... that only worked because bluebird was being installed already as part of html-webpack-plugin and the file importing it doesn't even have a valid use for it, seeing it can use native promises without issues.

Yeah now I feel stupid, but hey, that's 22KB less on our bundle :-)

Time to build a tool that checks your imported/required modules against your package.json, so that this can't happen again.
