### ISSUE TITLE
while using webpack html plugin it appends scripts into index.html everytime

### ISSUE THREAD

**Issue by nirmal-techahead** [jantimon/html-webpack-plugin#813]
Hi, I am using HtmlWebpackPlugin and writing scripts and CSS to HTML file.But every time when I run the web pack it appends the new src with the latest hash and not removing the old src path.I also tried {%= o.htmlWebpackPlugin.files.js %} but it did not work for me.

my web.config.js

new HtmlWebpackPlugin({ // Also generate a test.html
filename: 'index.html',
template: 'index.html',
hash:true,
inject: true,

}),

my index.html file

<script type="text/javascript" src="{%= o.htmlWebpackPlugin.files.js %}"></script>

it appending scripts like

<script type="text/javascript" src="vendor.bundle.js?c0805d1ce7c079b459c1"></script>
<script type="text/javascript" src="app.bundle.js?c0805d1ce7c079b459c1"></script>
<script type="text/javascript" src="vendor.bundle.js?0e944c21cd601c02a63a"></script>
<script type="text/javascript" src="app.bundle.js?0e944c21cd601c02a63a"></script>

**Comment by MV88** [comment]
I don't know why you are getting also older version, but i would go with another way.
Did you tried the chunks option?
like chunks: ["app.bundle","vendor.bundle"]
it includes only the entries you want to add in the index.html
by doing that you should remove the script from the index.html 
```
<script type="text/javascript" src="{%= o.htmlWebpackPlugin.files.js %}"></script>
```
