### ISSUE TITLE
Adding filename property breaks index.html file creation on linux

### ISSUE THREAD

**Issue by Mikeg542** [jantimon/html-webpack-plugin#814]
I'm using the html-webpack-plugin that was included in the create-react-app boilerplate. I made a slight modification to add a hash into the html filename using the filename property and it now doesn't create an index file at all on linux machines (but still works as expected on windows/ mac). If I remove the filename property, the linux machines can create a index.html file. Is this an issue with how the how the plugin renames the files or is it more likely something on our end on the linux machines.

(in paths file:)
```
module.exports = {
  appHtml: resolveApp('public/index.html'),
};
```

(in main file)
```
var newHash = '/index.' + Date.now() + '.html';

new HtmlWebpackPlugin({
      inject: true,
      template: paths.appHtml,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true
      },
      filename: newHash
    })
```

Thanks for any help!

**Comment by jantimon** [comment]
Sorry I was not able to reproduce this behavior
