### ISSUE TITLE
webpack v4 migration plan

### ISSUE THREAD

**Issue by TheLarkInn** [jantimon/html-webpack-plugin#816]
Hey @jantimon and html-webpack-plugin contributors/team.

Today we released webpack v4.0.0-alpha as our first experimental release candidate. I'd like to scope out path for migration and figure if we can get the work required to get this v4 compat. 

Our current changelog can be found here: https://github.com/webpack/webpack/issues/6064

Would it be possible that we create a list here (in this issue) of the work that would need to be accomplished to get html-webpack-plugin ready for v4? I know that @jantimon, myself and @sokra discussed in person some of the specifics but would like to open up contribution opportunities for anyone who wants to help with the work. 

Thanks, 
Sean - webpack team

**Comment by Graham42** [comment]
As a starting point, here's the 3 errors that can be seen by running tests with
`webpack@v4.0.0-alpha.0`
`extract-text-webpack-plugin: 3.0.0-beta.3`

(all tests are failing currently but they're all variations on these errors)

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
```
```
TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
```
```
Error: Plugin could not be registered at 'html-webpack-plugin-alter-asset-tags'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
```

**Comment by Graham42** [comment]
Also, I'm starting on this with the goal of getting current tests to pass.

**Comment by Graham42** [comment]
WIP PR opened here https://github.com/jantimon/html-webpack-plugin/pull/823

**Comment by TheLarkInn** [comment]
@Graham42 @jantimon what can we do to help unlock, or further the progress. We are getting a bit closer to RC time, and as we are releasing alpha versions to npm, we want to hopefully see a html-webpack-plugin thats v4 compat in an alpha that folks can leverage. 

What (in any way) can we do to help. We are all ears. Also, if you don't get a response from me, try and ping me on twitter as well (@TheLarkInn also)

**Comment by Graham42** [comment]
I'll get a chance to work on this later this weekend. Just getting back from holidays.

All tests are passing, with the caveat that I need to better understand how development / production modes apply to the fixture tests.

There's still some deprecated functions being called but I don't think that's blocking.

**Comment by bbakhrom** [comment]
any updates guys? Webpack 4 is planned to be released this month right, this plugin needs more attention if its going to happen this month.

**Comment by aulisius** [comment]
@bbakhrom https://github.com/webpack-contrib/html-webpack-plugin/pull/3
