### ISSUE TITLE
erase html head

### ISSUE THREAD

**Issue by littlestar1998** [jantimon/html-webpack-plugin#819]
For project's sake, I want to output <script> or <link> via html-webpack-plugin, but I have a <head> tag no matter how I try it. This is not needed. How do I do this without including < head> tag, for example

<script src = xx.63424fc04010593245ad.js />
<script src = xx.63424fc04010593245ad.css />

No head tag required

thanks

**Comment by jantimon** [comment]
Disable the inject feature and write a custom template like shown in the readme
