### ISSUE TITLE
URIError: Failed to decode param '/%3C%=%20%20htmlWebpackPlugin.files.css[0]%20%%3E'

### ISSUE THREAD

**Issue by iamzuijiasunyou** [jantimon/html-webpack-plugin#820]
I wanna use html-loader to deal img[:src] and use html-webpack-plugin to creation of HTML files。but it's failed.
this is my config.js:

![image](https://user-images.githubusercontent.com/15125049/33755994-58cfc79e-dc2e-11e7-88ea-b0f9954c15bd.png)
![image](https://user-images.githubusercontent.com/15125049/33756006-69e3ac44-dc2e-11e7-967d-0283c13318c6.png)(it is a multiEntry)
![image](https://user-images.githubusercontent.com/15125049/33756027-84b11f3e-dc2e-11e7-8fd6-20ddb7a4eb52.png)
this is my error info:
![image](https://user-images.githubusercontent.com/15125049/33756072-b6e28542-dc2e-11e7-8dda-c0bdcad2ff61.png)

**Comment by jantimon** [comment]
Sorry I have really no idea which could cause this - can you please provide any additional information?

**Comment by dylanspurgin** [comment]
@iamzuijiasunyou It looks like you have to use `ejs` extension on your template for this to work. Hope this helps.
