### ISSUE TITLE
Efficiency way to create new file ?

### ISSUE THREAD

**Issue by zigang93** [jantimon/html-webpack-plugin#821]
## Description

As I know, when we have new file ..  we need write this:
```
 new HtmlWebpackPlugin({
   filename: 'dist/index.html',
    template: 'src/index.html',
 }),
 new HtmlWebpackPlugin({
   filename: 'dist/index2.html',
    template: 'src/index2.html',
 }),
 new HtmlWebpackPlugin({
   filename: 'dist/index3.html',
    template: 'src/index3.html',
 }),
```
What if we have 20++ html ? we need create every new HtmlWebpackPlugin in webpack.config??
any best way to make it more dynamic?

## Example Of What I Think

Maybe I just need to add one `new HtmlWebpackPlugin`
then let it search and find my src folder have how many html file.. then export same amount of html file to dist folder.

```
 new HtmlWebpackPlugin({
   filename: 'dist/*.html',
    template: 'src/*.html',
 }),
```
so if my `src` folder have : index1.html , index2.html and index3.html
it should be output to `dist` folder as index1.html , index2.html and index3.html

or maybe you guys have any suggestion to me??

**Comment by jantimon** [comment]
Unfortunately right now this is not supported as different files usually use different configurations.
