### ISSUE TITLE
Incorrect asset path when using publicPath on Windows

### ISSUE THREAD

**Issue by kytrol** [jantimon/html-webpack-plugin#822]
## Description
`html-webpack-plugin` incorrectly constructs the asset path on Windows when a `publicPath` is specified.  I'd expect the `src` of the `<script>` to be `build\js\bundle.js` instead of `build\/js\bundle.js`. 

I found that this is caused by [this conditional](https://github.com/jantimon/html-webpack-plugin/blob/f6633391a281378a3fcd973165a4b0b72b8850c1/index.js#L401).

When it is changed to:

```js
var separator = path.join('/');
if (publicPath.length && publicPath.substr(-1, 1) !== separator) {
  publicPath += separator;
}
```
The asset path is correctly constructed. Though I don't know if this is the correct, robust solution. Should I even use the `path` module when setting paths in `webpack.config.js`?

Below is the minimum config to reproduce.

### Config
```js
const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: path.join(__dirname, 'script.js'),
  output: {
    filename: path.join('js', 'bundle.js'),
    path: path.join(__dirname, 'build'),
    publicPath: path.join('build', '/')
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: path.join(__dirname, 'index.html'),
      filename: 'index.html',
      minify: false,
      inject: true
    }),
  ]
};
```

Template file:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Path Test</title>
    <meta http-equiv="X-UA-Compatible", content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>
  <body>
    <h1>Path Test</h1>      
  </body>
</html>
```

Template file after injection:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Path Test</title>
    <meta http-equiv="X-UA-Compatible", content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>
  <body>
    <h1>Path Test</h1>
  <script type="text/javascript" src="build\/js\bundle.js"></script></body>
</html>
```
## Environment
Node.js v8.9.1
win32 6.1.7601
npm v5.5.1
webpack@3.10.0
html-webpack-plugin@2.30.1

**Comment by jantimon** [comment]
Just use `/` in public path.
