### ISSUE TITLE
cann't use options or webpack DefinePlugin

### ISSUE THREAD

**Issue by taven-liu** [jantimon/html-webpack-plugin#824]
I have two template a and b, the template a contain template b like this `${require('html-loader?interpolate=require&minimize=false!components/b.html')}
` , and I can use  `  <script src="${htmlWebpackPlugin.options.publicPath}/index.js}"></script>` in template a, also I can use webpack DefinePlugin ` <script src="${publicPath}/index.js}` in template a. but the code doesn't work in template b

**Comment by jantimon** [comment]
Not quite sure what you mean - I would love to clear this for our spring cleanup.  
Please add a new stackoverflow question in case this hasn't been solved yet.
