### ISSUE TITLE
Ability to place async script before inlined css

### ISSUE THREAD

**Issue by resolutecake** [jantimon/html-webpack-plugin#827]
## Prerequisites

Adding to an ejected Create React App config/webpack.config.prod.js:
```js
const HtmlWebpackInlineSourcePlugin = require('html-webpack-inline-source-plugin')
const ScriptExtHtmlWebpackPlugin = require('script-ext-html-webpack-plugin')
…
    new HtmlWebpackPlugin({
      inject: 'head',
…
      inlineSource: '\.css$',
    }),
    new ScriptExtHtmlWebpackPlugin({
      defaultAttribute: 'async',
    }),
    new HtmlWebpackInlineSourcePlugin(),
```
On running ```npm run build``` the script element is placed AFTER styles element of inlined css, build/index.html:
```html
…
  </style>
  <script type="text/javascript" src="/static/js/main.597c5787.js" async></script>
</head>
…
```
FEATURE REQUEST:
possibility to place async script BEFORE css, so that the download progresses while css is being parsed

html-webpack-plugin@2.29.0

**Comment by jantimon** [comment]
You should probably use the https://github.com/GoogleChromeLabs/preload-webpack-plugin which will start downloading the js right away.

Another way would be to set `inject` to `false` and write a template
