### ISSUE TITLE
The path of injected script is incorrect.

### ISSUE THREAD

**Issue by huyaxiong** [jantimon/html-webpack-plugin#828]
This is my webpack config file

```  
    var path = require('path');
    var webpack = require('webpack');
    var autoprefixer = require('autoprefixer');
    var HtmlWebpackPlugin = require('html-webpack-plugin');
    var CleanWebpackPlugin = require('clean-webpack-plugin');
    var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
    var frontendDir = path.resolve(__dirname, 'frontend');
    var srcDir = path.resolve(__dirname, 'frontend', 'src');
    var scssDir = path.resolve(__dirname, 'frontend', 'scss');
    var htmlDir = path.resolve(__dirname, 'frontend', 'htmls');
    var distDir = path.resolve(__dirname, 'frontend', 'dist');
    module.exports = {
        entry: {
            vendor: ['vue', 'axios', 'jquery'],
            'points-gift': [path.resolve(srcDir, 'points-gift.js'), path.resolve(scssDir, 'points-gift-list.scss')],
            wheel: [path.resolve(srcDir, 'wheel.js')],
        },
        output: {
            publicPath: '/frontend/',
            path: distDir,
            filename: '[name].[chunkhash].js',
        },
        module: {
            rules: [
                {
                    test: /\.vue$/,
                    loader: 'vue-loader'
                },
                {
                    test: /\.js$/,
                    loader: 'babel-loader',
                    exclude: /node_modules/
                },
                {
                    test: /\.css$/,
                    use: [
                        "style-loader", "css-loader"
                    ]
                },
                {
                    test: /\.(ttf)$/,
                    loader: 'file-loader',
                    options: {
                        name: '[name].[ext]?[hash]'
                    }
                },
                {
                    test: /\.(png|jpg)$/,
                    loader: 'url-loader'
                },
                {
                    test: /\.scss$/,
                    use: [
                        "style-loader", "css-loader", 'postcss-loader', "sass-loader"
                    ]
                }
            ]
        },
        resolve: {
            alias: {
                'vue$': 'vue/dist/vue.common.js',
                'axios$': 'axios/dist/axios.min.js',
                'jquery$': 'jquery/dist/jquery.min.js',
            }
        },
        devtool: 'cheap-module-eval-source-map',
        plugins: [
            new webpack.optimize.CommonsChunkPlugin({
                name: "vendor",
                minChunks: Infinity
            }),
            new webpack.optimize.OccurrenceOrderPlugin(),
            new HtmlWebpackPlugin({
                inject:'head',
                filename: 'points-gift.html',
                template: path.resolve(htmlDir, 'points-gift.html'),
                chunks: ['vendor', 'points-gift']
            }),
            new HtmlWebpackPlugin({
                inject:'head',
                filename: 'wheel.html',
                template: path.resolve(htmlDir, 'wheel.html'),
                chunks: ['wheel']
            }),
            // new BundleAnalyzerPlugin()
        ]
    };

    if (process.env.NODE_ENV === 'prod') {

        module.exports.devtool = false;
        module.exports.plugins = (module.exports.plugins || []).concat([
            new CleanWebpackPlugin([distDir]),
            new webpack.optimize.UglifyJsPlugin({
                // mangle: false,
                comments: false,
                compress: {
                    warnings: false,
                    pure_funcs: ['console.log', 'console.warn', 'window.console.log.apply']
                }
            }),
            new webpack.DefinePlugin({
                'process.env': {
                    NODE_ENV: '"production"'
                }
            })
        ])
    }
````
And this is my project structure
![image](https://user-images.githubusercontent.com/6245250/34195743-0d7835fe-e59a-11e7-9a78-9a59e72ed01e.png)

This is the result html file
![image](https://user-images.githubusercontent.com/6245250/34195760-24c28bc4-e59a-11e7-82d1-69c8dbfa97db.png)

The result path 

`<script type="text/javascript" src="/frontend/vendor.07ae996b0216817644b8.js"></script>`

should be

`<script type="text/javascript" src="/frontend/dist/vendor.07ae996b0216817644b8.js"></script>`

It missed "/dist", not as what I expected, I think its because that the path was calculated based on output.publichPath but not output.path.

**Comment by huyaxiong** [comment]
version: 2.30.1

**Comment by MZIchenjl** [comment]
set the value of `output.publicPath` to be `/frontend/dist/`

**Comment by huyaxiong** [comment]
@MZIchenjl I knew how to work around it, but I think it refers to the wrong attribute and it should be fixed.

**Comment by MZIchenjl** [comment]
@huyaxiong the `output.path` determines the output path, the `output.publicPath` is prefixed to every URL in your project, they are not the same thing. In this case, the chunks injection in the html file is the second.

**Comment by huyaxiong** [comment]
@MZIchenjl thats exactly my point, the chunks injection in the html file should be based on path, not publicPath. Because the path defines the final script file output, not the publicPath.The usage of publicPath is to indicate where static assets stored, such as images, fonts, totally unrelated to the script file. If the script file is not stored in the publicPath, it would cause problem like I encountered.We shouldnt restrict users to put their script file in the publicPath, its not flexible.

**Comment by uselessaddress** [comment]
@huyaxiong Maybe you can use the 'fileName' to separate the script files and the static assets,just like how the cli creat-react-app do it ,because the true path that inject into html files is made by publicPath+fileName,you can observed the following image that in the cil creat-react-app webpack-config
![tim 20171225181309](https://user-images.githubusercontent.com/14330863/34338084-07a81f0e-e9a0-11e7-8f85-65d3f7060a94.png)
![tim 20171225181338](https://user-images.githubusercontent.com/14330863/34338089-13fb777e-e9a0-11e7-9dec-1720e24ea9e4.png)
![tim 20171225181332](https://user-images.githubusercontent.com/14330863/34338092-1e83702a-e9a0-11e7-901f-bdfd3378f18e.png)
![tim 20171225181328](https://user-images.githubusercontent.com/14330863/34338095-2050f738-e9a0-11e7-9d07-85457a2eb9c7.png)
![tim 20171225182152](https://user-images.githubusercontent.com/14330863/34338123-819eaf6c-e9a0-11e7-94b7-4e6a4648f0e7.png)
the script files and the static assets has the same publicPath and path(build),but difference fileName.

**Comment by huyaxiong** [comment]
@uselessaddress thanks for the help, thats exactly the way how I worked around it, but still I think this problem should be fixed by this plugin's maintainer.

**Comment by mishoo78** [comment]
I believe that the plugin maintainer should change this, as the output.path is a webpack propery. it is configured at webpack level, same with the public path property. if i have this properties set up, and then, for whathever resason, i need to use this plugin, suddenly the application does not work, as the js bundles are referenced in another place. a plugin should not make anyone to change application config, just to make thinngs work again.

**Comment by jantimon** [comment]
Sorry but that's exactly what `publicPath` was made for.  
I can't see anything we can do here.
