### ISSUE TITLE
Alternative interpolate pattern for default(lodash) loader

### ISSUE THREAD

**Issue by expressiveco** [jantimon/html-webpack-plugin#829]
I want to pass an alternative interpolate delimiter to the default [lodash](https://lodash.com/docs/4.17.4#template) loader. We could only pass options as JSON through query and the interpolate option must be a RegExp object.

> [options.interpolate=_.templateSettings.interpolate] (RegExp): The "interpolate" delimiter.

But there is no way to convert RegExp object to JSON and RegExp literal is not valid in JSON. So, we could only mimic it with an object having the source property.

Actually, [lodash's template function](https://github.com/lodash/lodash/blob/d10b44bdef2b735865c493fbaec8687ec8998aef/template.js) does not use the interpolate value as a regex pattern and uses the source property of the interpolate option.
```javascript
 const interpolate = options.interpolate || reNoMatch
  let source = "__p += '"

  // Compile the regexp to match each delimiter.
  const reDelimiters = RegExp(`${[
    (options.escape || reNoMatch).source,
    interpolate.source,
    (interpolate === reInterpolate ? reEsTemplate : reNoMatch).source,
    (options.evaluate || reNoMatch).source
  ].join('|')}|$`, 'g')
```

So, following **source property workaround** works fine;

```javascript
function getCustomLodashTemplateDelimiter(reInterpolate) {
    return JSON.stringify({ interpolate: { source: reInterpolate.source } });
}

function getCustomLodashLoader() {
    return './node_modules/html-webpack-plugin/lib/loader.js?' +
        getCustomLodashTemplateDelimiter(/{{([\s\S]+?)}}/);
}

        new HtmlWebpackPlugin({
            inject: false,
            filename: "../Main.html",
            template: '!' + getCustomLodashLoader() + '!./MainTemplate.html',
            chunks: ["main"]
        }),

````

But it would be better to create RegExp when query has an interpolate property in [html-webpack-plugin's 
 loader.js](https://github.com/jantimon/html-webpack-plugin/blob/master/lib/loader.js);
```javascript
var options = loaderUtils.parseQuery(this.query);
if (options.hasOwnProperty("interpolate"))
  options.interpolate = new RegExp(options.interpolate);
````
IMHO, default lodash loader must handle this because there is no way to convert RegExp to JSON and pass it without a workaround.
So, we could pass the interpolate parameter without the **source property workaround**.

**Comment by jantimon** [comment]
If you need a better lodash loader please don't use the fallback loader of the html webpack plugin.  
This will allow you to use any template language you want while keeping the complexitiy of the html-webpack-plugin smaller.
