### ISSUE TITLE
Webpack upgrade 4 or 3 ?

### ISSUE THREAD

**Issue by alundiak** [jantimon/html-webpack-plugin#836]
I see in package.json =>

```
"webpack": "^1.14.0",
```
And in fact if I use `npm install html-webpack-plugin@latest` it installs `2.30.1` but with webpack@3.10.0 as nested dependency. and my main webpask version is `3.5.4`. So when I migrate to webpack 4.x, this plugin will be still with old version.

**Comment by TrySound** [comment]
@alundiak ```
  "peerDependencies": {
    "webpack": "1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3"
  }
```
dev dependencies do not matter
