### ISSUE TITLE
template file caught by .ejs loader

### ISSUE THREAD

**Issue by christopherjbaker** [jantimon/html-webpack-plugin#837]
## Description

The resolving of the template file goes through webpack resolution methods. My webpack config has a catch-all rule (though a rule to match `.ejs` files would cause the same behaviour) which filters files through the `file-loader`. The result is that my "html" pages are just the new path, as provided by the file loader. (I realize that I could change the `exclude` on that rule, but I do not have access to this code (it is inside `custom-react-scripts`)).

The solution I have found is to [prefix the final path](https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L614) with an `!`, to tell webpack to *not* use the normal resolvers, only the loader that you have provided.

However, I do not know what the consequences of this would be for your project, as this would technically be a breaking change, though I can't imagine any reason that somebody would need to rely on this (but there are a number of configs that would remain unchanged).

^ This is why I did not file a PR. If you would like, I would be happy to do so.

### Config

```js
module.exports = {
  module: {
    rules: [
      {
        oneOf: [
          {
            exclude: [/\.js$/, /\.html$/, /\.json$/],
            loader: require.resolve('file-loader'),
            options: {
              name: 'static/media/[name].[hash:8].[ext]',
            },
          },
        ],
      },
    ],
  },
};
```

## Environment

```
Node.js v8.9.4
darwin 17.2.0
NPM v5.6.0
├─┬ @storybook/react@3.3.9
  └── webpack@3.10.0 
├─┬ @storybook/react@3.3.9
  └── html-webpack-plugin@2.30.1 
```

**Comment by percyhanna** [comment]
Hmm, I wonder if this is the same issue I've been experiencing for 1-2 weeks now.  I initially had a `create-react-app` but then ejected because I needed to add new entry points and HTML files. I added a `background.html` and used `chunks: ['background']` to inject the background entry. However, the generated HTML looks like this:

```
/static/media/default_index.88827167.ejs<script type="text/javascript" src="/static/js/background.feafd5ba.js"></script>
```

**Comment by christopherjbaker** [comment]
@percyhanna that is *exactly* what is happening. The .ejs file is being treated like images, and its return value is the new location, rather than the source, so the script is just thrown at the end, as there is no place to inject it.

Although I'm not sure why this isn't an issue with the normal `create-react-app` output, as that has the same catch-all rule.

**Comment by percyhanna** [comment]
It only seems to happen if you don't use the `template` option, which `create-react-app` uses by default. For now I'm simply excluding `.ejs` files from the `file-loader` since I don't personally use them in my project, and it seems to be working ok thus far. /shrug

**Comment by jantimon** [comment]
I am really sorry but we won't be able to fix this here without any breaking changes.
