### ISSUE TITLE
Webpack 4: compilation.mainTemplate.applyPluginsWaterfall is not a function

### ISSUE THREAD

**Issue by takion** [jantimon/html-webpack-plugin#841]
## Description

Webpack 4 support: compilation.mainTemplate.applyPluginsWaterfall is not a function

### Error Message & Stack Trace

```
compilation.mainTemplate.applyPluginsWaterfall is not a function
    at /var/www/myproject/node_modules/html-webpack-plugin/lib/compiler.js:81:
```

**Comment by jbruni** [comment]
There is a PR for Webpack 4 support: https://github.com/jantimon/html-webpack-plugin/pull/823

Here is the source branch: https://github.com/Graham42/html-webpack-plugin/tree/feat/webpack-4

The author warns about [chunk-related issues](https://github.com/jantimon/html-webpack-plugin/pull/823#issuecomment-359804942), but in my starter Webpack 4 beta setup, it is working.

**Comment by gaterking** [comment]
@jbruni I get an error from the branch.
` compilation.hooks.htmlWebpackPluginAlterChunks = new SyncWaterfallHook(['chunks', 'objectWithPluginRef']);
TypeError: SyncWaterfallHook is not a constructor`

**Comment by stevenfitzpatrick** [comment]
Actually I got a fix for the SyncWaterfallHook error, this seems to be due to different webpack plugin using different versions of Tapable.

But if you install the latest Tapable yourself in your package.json like this

`    "tapable": "1.0.0-beta.5",`

Everything seems to work...

**Comment by damianobarbati** [comment]
@stevenfitzpatrick is your fix still working for you? I tried but it does not seem to work.
Will this be fixed soon in master? I mean, webpack@4 compatibility

**Comment by damianobarbati** [comment]
@jbruni would you share your working starter kit for anyone having this at the moment?

**Comment by jbruni** [comment]
@damianobarbati - There is nothing special to share... I've only used [the fork](https://github.com/Graham42/html-webpack-plugin/tree/feat/webpack-4) in place of the regular plugin.

**Comment by damianobarbati** [comment]
@jbruni sorry for the noise, the error thrown by html-plugin was related to babel.
It's very weird anyway: I wrote a simple plugin on my own to put the assets into the html and exclude html-webpack-plugin possible errors.
It worked flawlessly and the error was instead fired into console at runtime (it's not fired by webpack): how did it end up into the html file? 🤨

**Comment by iliatcymbal** [comment]
Hey, what the status, any news? `new HtmlWebpackPlugin()` still doesn't work for me  
I'm suing config

```
   "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "webpack": "^4.0.0",
    "webpack-cli": "^2.0.9"
  }
```
And got  
```
/node_modules/html-webpack-plugin/lib/compiler.js:81
        var outputName = compilation.mainTemplate.applyPluginsWaterfall('asset-path', outputOptions.filename, {
                                                  ^

TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
```

**Comment by TomasHubelbauer** [comment]
@iliatcymbal Use `yarn add webpack-contrib/html-webpack-plugin -D`, a fork maintained by WebPack until the maintaner of this plugin is able to resolve this, and you'll be set. I did it this morning and it works flawlessly.

**Comment by iliatcymbal** [comment]
@TomasHubelbauer, that works for me, thank you! How did you get this?)

**Comment by francoisromain** [comment]
@TomasHubelbauer I updated to `webpack-contrib/html-webpack-contrib` but still have an error: 

```
compilation.hooks.htmlWebpackPluginAlterChunks = new SyncWaterfallHook(['chunks', 'objectWithPluginRef']);
                                                       ^

TypeError: SyncWaterfallHook is not a constructor
    at /node_modules/html-webpack-plugin/index.js:50:56
```

Any idea why? Thank you

**Comment by kutsan** [comment]
@francoisromain Maybe `rm -rf node_modules/ && npm install`?

**Comment by francoisromain** [comment]
@kutsan I did that already…
Maybe is it related to this: https://github.com/webpack-contrib/html-webpack-plugin/issues/13 ?

**Comment by francoisromain** [comment]
This https://github.com/webpack-contrib/html-webpack-plugin/commit/6319451c00494ec32fea9176bfdcb7528185ab35 fixed it for me. Thanks.

**Comment by stevenfitzpatrick** [comment]
html-webpack-plugin 3.0.0 seems to be out...and everything just works : )

**Comment by Jarch09** [comment]
Still getting a deprecation warning with html-webpack-plugin 3.0.0+
```
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

**Comment by Ghostdar** [comment]
@damianobarbati 
i just meet the same error when i use  webpack4 , do you resolve this case ? 
`ERROR in   TypeError: __webpack_require__(...) is not a function
  
  - es6.regexp.replace.js?:2 eval
    [.]/[core-js]/modules/es6.regexp.replace.js?:2:90
  
  - index.html:339 Object../node_modules/core-js/modules/es6.regexp.replace.js
    /Users/damz/Desktop/yarsk/app/index.html:339:1`

**Comment by giacomocerquone** [comment]
Still getting this error too in a react native project with styleguidist. I'm using this configuration for a project of mine: https://github.com/styleguidist/react-styleguidist/tree/master/examples/react-native

This is the error:

`(node:18009) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:18009) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead

TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
`

**Comment by benoitkoenig** [comment]
@Silvia813 had the same issue, fixed it by installing the latest versions of my babel-loaders

**Comment by zhengkai2001** [comment]
`npm install webpack-contrib/html-webpack-plugin --save-dev` will do the trick if you happen to use npm not yarn like me

**Comment by am** [comment]
@benoitkoenig same happen to me, other dependencies may break your build with the same error:

```sh
[spawn] stderr: (node:35845) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[spawn] stderr: (node:35845) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
[spawn] stderr: /project/node_modules/html-webpack-plugin/lib/compiler.js:81
        var outputName = compilation.mainTemplate.applyPluginsWaterfall('asset-path', outputOptions.filename, {
                                                  ^

TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
    at /project/node_modules/html-webpack-plugin/lib/compiler.js:81:51
```
Even after having updated `html-webpack-plugin` to the latest version a `tapable` resolved to 1.0.0

**Comment by jantimon** [comment]
@am your version is outdated - please take a look at the current source which includes an integration for the new webpack 4 asset path generation:
https://github.com/jantimon/html-webpack-plugin/blob/e6e84648fb3333ec072e06a9d3b1fcc7bee85440/lib/compiler.js#L78-L89

**Comment by am** [comment]
@jantimon thanks for the heads-up. Even after update to the latest version `3.0.6` I still had the same error. Read this thread and the solution that worked for me was to do the same as benoitkoenig proposed, after updating those dependencies the issue is gone. Not sure how it relates, but thought that was worth mention here.

**Comment by kumaresan-subramani** [comment]
error: TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function

i used this command but its not working because  my web-pack version is 4.4.1

> give some idea about this issue

**Comment by giacomocerquone** [comment]
I used to do: `npm  install webpack-contrib/html-webpack-plugin --save-dev`

but now I get:

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/webpack-contrib/html-webpack-plugin.git
npm ERR! 
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

What happened to the repo? This is driving me nuts

**Comment by jantimon** [comment]
It does not exist anymore please use `npm install html-webpack-plugin --save-dev`

**Comment by giacomocerquone** [comment]
@jantimon I tried that, but it doesn't work anymore, it still gives me compilation.mainTemplate.applyPluginsWaterfall is not a function

**Comment by jantimon** [comment]
@giacomocerquone I am very sorry but this was fixed 1 month ago.  
All unit tests and examples work well with webpack 4:
https://travis-ci.org/jantimon/html-webpack-plugin/builds/361541288  
Please make sure that you updated all of your dependencies.  
If updating does not help please open a new issue with the smallest possible webpack config so we can reproduce and fix the issue.

**Comment by kumaresan-subramani** [comment]
**these are my dependencies **
__"dependencies": {
    "@angular/common": "4.4.4",
    "@angular/compiler": "4.4.4",
    "@angular/core": "4.4.4",
    "@angular/forms": "4.4.4",
    "@angular/http": "4.4.4",
    "@angular/platform-browser": "4.4.4",
    "@angular/platform-browser-dynamic": "4.4.4",
    "@angular/router": "4.4.4",
    "@angular/upgrade": "^5.0.0",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-beta.5",
    "@ngx-translate/core": "8.0.0",
    "@ngx-translate/http-loader": "2.0.0",
    "@syncfusion/ej2": "*",
    "@syncfusion/ej2-base": "*",
    "@syncfusion/ej2-cards": "*",
    "@syncfusion/ej2-ng-base": "*",
    "@syncfusion/ej2-ng-buttons": "*",
    "@syncfusion/ej2-ng-calendars": "*",
    "@syncfusion/ej2-ng-charts": "*",
    "@syncfusion/ej2-ng-circulargauge": "*",
    "@syncfusion/ej2-ng-dropdowns": "*",
    "@syncfusion/ej2-ng-grids": "*",
    "@syncfusion/ej2-ng-inputs": "*",
    "@syncfusion/ej2-ng-lineargauge": "*",
    "@syncfusion/ej2-ng-lists": "*",
    "@syncfusion/ej2-ng-maps": "*",
    "@syncfusion/ej2-ng-navigations": "*",
    "@syncfusion/ej2-ng-popups": "*",
    "@syncfusion/ej2-ng-schedule": "*",
    "@syncfusion/ej2-ng-splitbuttons": "*",
    "bootstrap": "4.0.0-beta",
    "core-js": "2.5.1",
    "gulp": "^3.9.1",
    "require-dir": "^0.3.2",
    "run-sequence": "^2.2.1",
    "rxjs": "5.4.3",
    "shelljs": "^0.7.8",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.4.4",
    "@angular/platform-server": "^5.0.0",
    "@ngtools/webpack": "1.7.2",
    "@types/core-js": "0.9.43",
    "@types/jasmine": "2.6.0",
    "@types/node": "8.0.33",
    "es6-module-loader": "^0.17.11",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "3.2.3",
    "codelyzer": "3.2.1",
    "compression-webpack-plugin": "1.0.1",
    "copy-webpack-plugin": "4.1.1",
    "css-loader": "0.28.7",
    "@types/requirejs": "^2.1.26",
    "extract-text-webpack-plugin": "3.0.1",
    "file-loader": "1.1.5",
    "fuse.js": "^3.2.0",
    "html-loader": "0.5.1",
    "html-webpack-plugin": "2.30.1",
    "jasmine-core": "2.8.0",
    "json-loader": "0.5.7",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-jasmine": "1.1.0",
    "karma-mocha-reporter": "2.2.4",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "2.0.5",
    "node-sass": "4.5.3",
    "raw-loader": "0.5.1",
    "rimraf": "2.6.2",
    "sass-loader": "6.0.6",
    "to-string-loader": "1.1.5",
    "ts-helpers": "1.1.2",
    "tslint": "5.7.0",
    "typescript": "2.5.3",
    "webpack": "^3.6.0",
    "webpack-dev-server": "2.9.1",
    "webpack-merge": "4.1.0"
  }
}

**Comment by yan5** [comment]
Somehow the npm install html-webpack-plugin --save-dev is not picking the latest version. 
Use npm install html-webpack-plugin@3.2.0 --save-dev
