### ISSUE TITLE
Using Jade for templates

### ISSUE THREAD

**Issue by mittalyashu** [jantimon/html-webpack-plugin#843]
If we use templating method, do we need to use `pug-loader` separate to convert `.pug` or `.jade` files to HTML or it `html-webpack-plugin` will do it.

IF NOW

Then how it will work?

**Comment by yakuthemes** [comment]
you need to use pug-html-loader with html-webpack-plugin

**Comment by mittalyashu** [comment]
If I add this in a jade template.

```jade
title <%= htmlWebpackPlugin.options.title %>
```

**Comment by jantimon** [comment]
Please ask support question on how to use the pug loader on stackoverflow
