### ISSUE TITLE
Support PWA manifest.json

### ISSUE THREAD

**Issue by diegonvs** [jantimon/html-webpack-plugin#844]
Hey guys, can be added an preset in options to generate a tag linking `manifest.json`?

Something like:

``` javascript
plugins: [
  new HTMLWebpackPlugin({
    title: 'PWA Sample',
    manifest: <path to manifest.json>
  })
]
```

**Comment by diegonvs** [comment]
Work with templates to glue a little line in html its so weird 😢

**Comment by labsvisual** [comment]
What sort of manifest are you talking about?

**Comment by jantimon** [comment]
You can use a template or write a plugin similar to https://github.com/lettertwo/appcache-webpack-plugin
