### ISSUE TITLE
Issue in css file path in browser

### ISSUE THREAD

**Issue by Demon137** [jantimon/html-webpack-plugin#847]
Hi All,

I am working on React project and for bundling, I am using Webpack tool. This is basically an isomorphic application.

The issue that I am facing is that when you do inspect element and check the path of css loaded in the browser 
then the path is http://domainname:port/**fulldirectorypath**

in our case, the URL is like http://localhost:3031/var/www/html/demoproject/app/public/css/main.css

which should be like : http://localhost:3031/app/public/css/main.css

**Comment by jantimon** [comment]
Please ask support question on stackoverflow.
