### ISSUE TITLE
Cannot find module 'source-map' 

### ISSUE THREAD

**Issue by Legends** [jantimon/html-webpack-plugin#849]
- C:\WINDOWS\system32>node -v v9.5.0
- C:\WINDOWS\system32>npm -v 5.6.0
- C:\WINDOWS\system32>tsc -v Version 2.7.1
- Win 10 x64
- VsCode v1.20

After installing this package:
`npm install @types/html-webpack-plugin --save-dev`
, I get the above error, when running `tsc` in my project

![image](https://user-images.githubusercontent.com/966368/36148508-a0e17236-10bc-11e8-9218-346a98fa6f4b.png)

All details about this issue can be found [here](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/231#issuecomment-365235050)

Uninstalling the same package clears the error...

**Comment by jantimon** [comment]
Could you already find out why this is happening?

**Comment by Legends** [comment]
I uninstalled the HTML-WebPlugin and installed a specific version of `source-maps`.
Described [here](https://stackoverflow.com/questions/48757817/typescript-cannot-find-module-source-map-uglify-js) and installed it again.
