### ISSUE TITLE
Using template API in EJS files 

### ISSUE THREAD

**Issue by IskanderMustafin** [jantimon/html-webpack-plugin#857]
Hi,

I have EJS template which should be rendered by server side (Express): 
```
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <title>Some title</title>
</head>
<body>
     <span><%= userName %></title> // should be rendered by Express, userName is not static, so I can't set this variable during build
</body>
</html>
```
Currently I'm using `raw-loader` to load EJS template, so webpack wont throw `variable undefined` errors: 
```
                new HtmlWebpackPlugin({
                    inject: true,
                    chunks: ['business', 'mpaVendor', 'manifest'],
                    filename: `${EJS_TEMPLATES_BUILD_DIR}/business/business.ejs`,
                    template: `!!raw-loader!${EJS_TEMPLATES_SRC_DIR}/business/business.ejs`,
                    minify: {
                        removeComments: true,
                        collapseWhitespace: true,
                        conservativeCollapse: true
                    }
                }),

```
 
But now I need to use `html-webpack-plugin`'s API, i.e. something like this: 
```
<title><%= htmlWebpackPlugin.options.title %></title>
```

I need somehow to execute only `html-webpack-plugin`'s specific stuff during build, but other stuff (like `<%= userName %>`) should not be touched and should not throw any error. 

I think it's impossible. But how you suggest to solve it? Should I use 2 different template engines, one for   `html-webpack-plugin` API, another for server side dynamic stuff?

Thanks.

**Comment by jantimon** [comment]
Please ask support questions like this at stackoverflow so others user might profit as well.

You should either use a different template language or set the interpolation template settings:
http://underscorejs.org/#template

**Comment by yshterev** [comment]
Hi @IskanderMustafin  Have you found a solution? Can you post a link to it?
