### ISSUE TITLE
script tag is being added after the html tag

### ISSUE THREAD

**Issue by Noor0** [jantimon/html-webpack-plugin#859]
i checked my `index.html` after building the and found that `<script>` is being added at the end of the document
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
<link href="styles.css" rel="stylesheet"></head>
<body>
  <nav>
    <ul class="navigation">
      <li><a href="#">About us</a></li>
      <li><a href="#">Pricing</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </nav>

  <body>
</html><script type="text/javascript" src="bundle.js"></script>
```

is this the default behavior? shouldn't it be added before`</body>`?

**Comment by Noor0** [comment]
dont know what was the reason but i added a rule for static assets to use `file-loader` in my config and changed the directory structure a bit and it's fixed now.

**Comment by Noor0** [comment]
dont know what was the reason but i added a rule for static assets to use `file-loader` in my config and changed the directory structure a bit and it's fixed now.

**Comment by jantimon** [comment]
It looks like the reason is that your closing body tag was not closing

**Comment by Noor0** [comment]
oh! i feel so stupid for missing that
