### ISSUE TITLE
Unnecessary peer dependency on extract-text-webpack-plugin

### ISSUE THREAD

**Issue by billyjanitsch** [jantimon/html-webpack-plugin#864]
## Description

extract-text-webpack-plugin was added as a peer dependency in a8a8c2b6ea496c257fd6f501db3a06a51fa03e1e, but that library doesn't seem to actually be used in the source for html-webpack-plugin.

Is this peer dependency necessary? Can it be removed if not? If seems quite plausible that a project would use html-webpack-plugin without extract-text-webpack-plugin (e.g. one without any CSS).

**Comment by jantimon** [comment]
The extract text plugin is only needed for tests. I will release a 3.0.1 soon which removes the dependency.
