### ISSUE TITLE
Webpack 4 > 'html-webpack-plugin-before-html-generation' hook not found.

### ISSUE THREAD

**Issue by CPatchane** [jantimon/html-webpack-plugin#871]
Hi,

First of all, I want to say great work for this plugin and thanks for the webpack 4 support 👍.
For the context, I want to use webpack 4 for my tool [create-cozy-app](https://github.com/CPatchane/create-cozy-app/pull/314), but I still have an issue with this plugin.

## Description

Using the last version of html-webpack-plugin 3.0.3 and webpack 4.1.2, I still have an issue about a not found hook.

### Error Message & Stack Trace

```
Plugin could not be registered at 'html-webpack-plugin-before-html-generation'. Hook was not found.
    BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
```

Thanks by advance.

**Comment by insin** [comment]
The new compilation hooks for Webpack 4 are:

### Sync

- `htmlWebpackPluginAlterChunks`

### Async

- `htmlWebpackPluginBeforeHtmlGeneration`
- `htmlWebpackPluginBeforeHtmlProcessing`
- `htmlWebpackPluginAlterAssetTags`
- `htmlWebpackPluginAfterHtmlProcessing`
- `htmlWebpackPluginAfterEmit`

---

Still working my way through the new Webpack 4 plugin world one `console.log` at a time myself, but it seems you (or your html-webpack-plugin hook-using dependencies) need to do something like this to use the new hooks:

```js
function myPlugin() {
  this.hooks.compilation.tap('myPlugin', compilation => {
    compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tapAsync('myPlugin', (data, cb) => {
      // Do stuff
      cb()
    })
  })
}
```

**Comment by jantimon** [comment]
Exactly that's the new webpack plugin system

**Comment by CPatchane** [comment]
Ok, my bad, I wasn't looking at the right place.
I did actually have this issue due to the `svg-sprite-loader` usage on my side.
Sorry for the noise and thank you for taking time to reply my question @insin and @jantimon  👍 
I close this issue.

**Comment by kane-mason** [comment]
Hi, sorry, i also have this issue and can't see an answer on this thread on how to resolve it?

**Comment by kotchuprik** [comment]
🆙

**Comment by jantimon** [comment]
The reason for this issue is a incompatible plugin or loader.  
As I don't know which incompatible loader you installed I don't know why it is generating the error.  
But if you knew the plugin or loader which is not compatible to the Webpack 4 plugin system it would be better to let the author knew instead of posting it here :)

**Comment by kotchuprik** [comment]
yes, you are right! I fixed this problem :) the problem is in FaviconsWebpackPlugin

**Comment by 4iAmAve** [comment]
@kotchuprik 
How did you fix it. Since i have the same issue after upgrading to webpack 4.

**Comment by kotchuprik** [comment]
@4iAmAve my problem was in old version of FaviconsWebpackPlugin
