### ISSUE TITLE
<link> element is not closed when using favico inject. Cause problem on thymeleaf.

### ISSUE THREAD

**Issue by Renderz** [jantimon/html-webpack-plugin#872]
Hi

- I tried to use html-webpack-plugin to generate the 'thymeleaf html template' and found this issue
- Once add favicon on plugin, a <link> element should be injected on output html.
- The <link> element was not be closed which cause issue on thymeleaf compiling.
- The output html looks like: 
```
<head>
<link rel="shortcut icon" href="favicon.ico"></head>
```
- The error message:
```
element 'link' should be ended by </link>.
```

### Config

new HtmlWebpackPlugin({
            title: 'login',
            filename: 'login.html',
            favicon: __workSpace + "/web/images/favicon.ico",
            chunks: ['login', 'commons'],
            template: __workSpace + "/web/templates/login.tmpl.html"
        }),

## Environment
```
"webpack": "^3.11.0"
"html-webpack-plugin": "^2.30.1",
```

**Comment by jantimon** [comment]
I am not sure but is this really a bug?

**Comment by Renderz** [comment]
Well this is not a bug. But I just wonder whether there is any option to add </link> after packing

**Comment by jantimon** [comment]
Unfortunately there is no way but you could use a custom template for that.

**Comment by drewk** [comment]
Isn't this what the 'xhtml' option in the plugin is for?

From the docs:

> 

xhtml | {Boolean} | false | If true render the link tags as self-closing (XHTML compliant)
-- | -- | -- | --

**Comment by jantimon** [comment]
@drew oh my bad - that's actually a good point and valid html5: https://stackoverflow.com/a/9944108/159319

Could you please create a pull request for https://github.com/jantimon/html-webpack-plugin/tree/webpack-4
