### ISSUE TITLE
ERROR in   TypeError: callback is not a function

### ISSUE THREAD

**Issue by sherlock1982** [jantimon/html-webpack-plugin#873]
## Description

Many other plugins issue error during compilation with 3.0.4.
Affected inline-manifest-webpack-plugin, script-ext-html-webpack-plugin and maybe others.

### Error Message & Stack Trace

```
ERROR in   TypeError: callback is not a function

  - plugin.js:66 compilation.plugin
    [Webclient]/[script-ext-html-webpack-plugin]/lib/plugin.js:66:11


  - new Promise


  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [Webclient]/[html-webpack-plugin]/[tapable]/lib/Hook.js:35:21

  - index.js:645
    [Webclient]/[html-webpack-plugin]/index.js:645:47

  - index.js:182 Promise.resolve.then.then.then.then.then.then.then.result
    [Webclient]/[html-webpack-plugin]/index.js:182:18
```

## Environment

```
Node.js v8.9.1
win32 10.0.16299
NPM 5.6.0
html-webpack-plugin 3.0.4
```

**Comment by JeanBarriere** [comment]
It seems that they moved the `plugin(event, fn(data, cb) {})` function to a promise-based function that just execute the function without waiting for a callback to be called, as `cb` is now `undefined`

The documentation should be updated soon I guess.

**Comment by sherlock1982** [comment]
I'm not a plugin author :-). I'm just seeing that with this change lots of plugins are broken now. 
Could callback function just be provided as dummy so they will continue to work with no changes?

**Comment by sherlock1982** [comment]
Ah I see now. It's Webpack 4 change.

**Comment by chrisregner** [comment]
@sherlock1982 I'm stumped on this as well right now. Have you found any solution? Or it's still WIP?

**Comment by mastilver** [comment]
@chrisregner Just update webpack and webpack plugins

**Comment by chrisregner** [comment]
@mastilver Thanks, now its resolved. It was the chunk-manifest-webpack-plugin which lastest released version doesn't support webpack 4 yet, luckily I also discovered that I don't actually need it for my project so I just removed it.

**Comment by stormit-vn** [comment]
I am facing this problem now.

Here is the details of modules that i am using
"webpack": "4.8.1", **tried with some other versions i.e. 4.0.0, 4.5.0 also not working**
"webpack-cli": "2.1.3",
"webpack-dev-server": "3.1.4",
"script-ext-html-webpack-plugin": "2.0.1",
"extract-text-webpack-plugin": "3.0.2",
"html-webpack-plugin": "3.0.6", **latest version also not working**
"add-asset-html-webpack-plugin": "2.1.3",

Here is the console log
ERROR in   TypeError: callback is not a function

  - index.js:23
    /Users/hoangle/Documents/Working/TCE/Source/brightstar/mobilelife-portal/src/client/config/html-elements-plugin/index.js:23:13


  - new Promise


  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [client]/[tapable]/lib/Hook.js:35:21

  - index.js:647
    [client]/[html-webpack-plugin]/index.js:647:47

  - index.js:162 Promise.resolve.then.then.then.then.compilationResult
    [client]/[html-webpack-plugin]/index.js:162:36


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7

Does anyone know how to fix this problem completely?

Thanks in advance
