### ISSUE TITLE
callback is undefined in 3.0.4

### ISSUE THREAD

**Issue by wizardnet972** [jantimon/html-webpack-plugin#876]
**Prerequisites**
WebPack 4.0.1

**Description**
`html-webpack-plugin-after-emit` doesnt pass `callback`. `callback` is undefined. 

**Error Message & Stack Trace**
...
compilation.plugin('html-webpack-plugin-after-emit', (htmlPluginData, callback) => {
.......
})
...
**Config**
Copy the relevant section from webpack.config.js:

    "webpack": "^4.0.1",
    "webpack-cli": "^2.0.10",

**Environment**
Windows

**Comment by jantimon** [comment]
What do you mean by that?
