### ISSUE TITLE
🐛 Fail to inject code-splitting script files when webpack 4 optimization.splitChunks.name: false

### ISSUE THREAD

**Issue by dwiyatci** [jantimon/html-webpack-plugin#878]
## Description

As @sokra suggested in [one of webpack 4 posts](https://medium.com/webpack/webpack-4-code-splitting-chunk-graph-and-the-splitchunks-optimization-be739a861366) to preserve long term caching:

> or switch off name generation via optimization.splitChunks.name: false

`html-webpack-plugin` somehow fails to inject the generated "splitted" files when I apply this option in combination with `output: { filename: '[name].[chunkhash].js' }`.

### Config

```js
module.exports = {
  mode: 'production',
  output: {
    filename: '[name].[chunkhash].js',
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.ejs',
      favicon: './src/favicon.ico',
    }),
  ],
  optimization: {
    splitChunks: {
      chunks: 'all',
      name: false,
    },
    runtimeChunk: true,
  },
};
```

Template file:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My App</title>
    </head>
    <body>
        <div id="app"></div>
    </body>
</html>
```

## Relevant Links

- https://github.com/dwiyatci/minimalistic-devserver/blob/webpack-4/webpack.config.js

## Environment

```
Node.js v8.9.0
darwin 15.6.0
npm 5.5.1
webpack 4.0.1
html-webpack-plugin 3.0.4
```

**Comment by atilkan** [comment]
+1

**Comment by prencher** [comment]
This happens for us with names on as well, dependent chunks are not included.

**Comment by loveky** [comment]
any update on this issue? is there a walk around or plan to fix ?

**Comment by pspgbhu** [comment]
I met this problem too.

**Comment by softdays** [comment]
+1

**Comment by mqliutie** [comment]
+1

**Comment by boraturant** [comment]
+1

**Comment by dwiyatci** [comment]
@jantimon Works like a charm. :trumpet::kissing::tada: Thanks!
