### ISSUE TITLE
WP4, Multiple Entry Points script injected in all files.

### ISSUE THREAD

**Issue by atilkan** [jantimon/html-webpack-plugin#880]
I am trying to separate entry points. This was ok with webpack 3.
I have 2 entry and expecting 2 different output. 
Basically expecting login script injected to login page, index script injected to index page. No success yet.
<img width="99" alt="screen shot 2018-03-04 at 05 53 23" src="https://user-images.githubusercontent.com/1254613/36948866-e485dd1c-1ff1-11e8-82c6-5da7f1662890.png">

This is the login html file. Network tab.
![screen shot 2018-03-04 at 05 54 44](https://user-images.githubusercontent.com/1254613/36948858-d9cb0136-1ff1-11e8-84c1-d6ef7162d493.png)

This is the index html file. Network tab.
![screen shot 2018-03-04 at 05 55 19](https://user-images.githubusercontent.com/1254613/36948859-ddaf6a44-1ff1-11e8-9b4f-26553bd59b46.png)

I tried both repos. Same result.
webpack-contrib/html-webpack-plugin
jantimon/html-webpack-plugin

And webpack config for chunks. Tried thousand different setting here.
<img width="287" alt="screen shot 2018-03-04 at 06 01 43" src="https://user-images.githubusercontent.com/1254613/36948869-ec899026-1ff1-11e8-92b9-98be53ca4c88.png">

This is the html-webpack-plugin setup. Tried thousand different setting here, too.
<img width="555" alt="screen shot 2018-03-04 at 06 03 08" src="https://user-images.githubusercontent.com/1254613/36948882-16db996e-1ff2-11e8-8668-072eb03a839c.png">

**Comment by atilkan** [comment]
I finally made it work like this. Now all files injected in correct place. 
splitChunks: {
				cacheGroups: {
index: {
						name: "index",
						chunks: "async",
					},
login: {
						name: "login",
						chunks: "async",
					},
}

**Comment by fenivana** [comment]
In order to make splitting initial chunks and generating runtime chunk possible, I wrote this plugin: https://github.com/fenivana/html-webpack-include-sibling-chunks-plugin

**Comment by fvigotti** [comment]
I'm new to webpack , and I'm also trying to setup multiple entry-point , and webpack4 is the first version of webpack I've used.. so I thought that this plugin was not working for multiple-entry point, but now if you say 
 that in version 3 it worked, so probably It's a bug.. 
the problem is that  OR I specify specific chunks and the application will include only those chunks but then I have to explicit the full dependency graph ( entrypoint + commonchunks that this entrypoint partecipated in ) , or if I specify none it will include all entrypoints and chunks in all instances of htmlwebpackplugin 

so definitely both solutions are impossible to use...
(I think that this should be pointed as major bug for this plugin or at least specify in main readme that cannot be used with multiple entrypoint )

**Comment by atilkan** [comment]
Use something else to keep your sanity. Web community is like a sheep. Dont follow crowd. 
.

**Comment by jantimon** [comment]
This issue involves a lot of refactoring as we need to switch to the webpack 4 api.
An entire refactoring will break this plugin for millions of people so we want wo be sure that the change is done well.  
It will probably take about 5 days of work to get it done. 
I am really thankful for your feedback but right now I am not able to get it fixed as fast as I wish I could.  
Hopefully I’ll get the opportunity to invest those five days soon. If you want to support this issue I am happy to help you get into the code or if you don’t want to invest your time but think it’s worth 5$ feel free to support the project on open collective..

**Comment by jantimon** [comment]
Could you please try if this works for you with 4.x alpha?
Pull Request: #958

Npm pre release:
```
npm i html-webpack-plugin@next
```

**Comment by atilkan** [comment]
@jantimon It is ok. Thanks.

**Comment by jakelauer** [comment]
@jantimon How is this meant to be used? I'm running into the same problem, and after installing the @next version of html-webpack-plugin, I'm trying to configure webpack.config.js to work this way but I'm having trouble.
