### ISSUE TITLE
Documentation on how to use EJS templates with html-loader?

### ISSUE THREAD

**Issue by keryja** [jantimon/html-webpack-plugin#891]
I've been trying to figure out if there's a way to chain the fallback template loader with html-loader, so any images specified in the template get copied, and any template tags using `htmlWebpackPlugin.options.title` still get rendered.

Using `ejs-html-loader` could be an option but I am unaware of how to get the `htmlWebpackPlugin` variable injected into that.

I know this sounds more like a support question than anything else but I also feel like this is something that'd be useful to be included in the documentation hence I posted it here.

webpack: 4.1.0
html-loader: 0.5.5
html-webpack-plugin: 3.0.6

**Comment by jekelija** [comment]
I am also having this problem... i was able to circumvent it by declaring my html webpack plugin at the top of the file:
```
const htmlWebpackPlugin = new HtmlWebpackPlugin({
    inject: false,
    template: 'html/index.html',
    metadata: {
        title: 'Kitchen Visualizer',
        version: __VERSION__,
        build_date: __BUILD_DATE__,
        base_url: __BASE_URL__ 
    }
});
```
And then using:
```
test: /\.html$/,
                exclude: [
                    path.resolve(__dirname, 'html/index.html')
                ],
                loader: 'ejs-html-loader',
                options: {
                  htmlWebpackPlugin: htmlWebpackPlugin
                }
```

**Comment by jantimon** [comment]
Please ask this support question on stackoverflow and link the question to this issue.
