### ISSUE TITLE
Usage with webpack-serve

### ISSUE THREAD

**Issue by AndrewPa** [jantimon/html-webpack-plugin#892]
[Webpack-serve ](https://github.com/webpack-contrib/webpack-serve) is fairly new, so I'm unsure if this plugin is compatible. After the bundling is complete, I get a "Not Found" page.  Adding an index.html in my project root had it served as expected. I presume one or more of my paths are wrong.

```
const config = {
    entry: {
        main: "./app/app.js"
    },
    serve: {
      port: 5000
    },
    module: {
        rules: [
           ...
            // Templates
            {
                test: /\.(html)$/,
                use: {
                    loader: 'html-loader',
                    options: {
                        attrs: false
                    }
                }
            }, {
                test: /\.hbs$/,
                loader: 'handlebars-loader'
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            inject: 'head',
            template: './app/index.hbs',
            filename: '../index.html',
            favicon: './/static/img/favicon.ico'
        })
    ],
    output: {
        filename: "[name].js",
        path: path.join(outputRoot, 'webapp', 'app'),
        publicPath: '/app/'
    }
};
```

**Comment by AndrewPa** [comment]
A fix to a similar issue with webpack-dev-server seems to have worked. In the HtmlWebpackPlugin options:

```filename: '../index.html', => filename: 'index.html',```

**Comment by iernie** [comment]
I can't get it to work. Whenever i try using `webpack-serve` I don't get any ouput file from HtmlWebpackPlugin. How did you manage to get it to work?
