### ISSUE TITLE
xhtml for self closing all tags

### ISSUE THREAD

**Issue by atilkan** [jantimon/html-webpack-plugin#893]
## Description
Feature Request

Is there a way to close all self closing tags like **xhtml** setting? It closes all links but not img and input. Can you add this feature if there is no other way?

**Comment by jantimon** [comment]
The html webpack plugin does not generate any img or input tags - but it provides an event/hook which you can use to transform it after it is done

**Comment by atilkan** [comment]
Thanks. Is there a plugin you can recommend for html-webpack-plugin

**Comment by jantimon** [comment]
Please check the readme there are many plugins mentioned
