### ISSUE TITLE
Escape option for thymeleaf templates

### ISSUE THREAD

**Issue by atilkan** [jantimon/html-webpack-plugin#894]
## Description
I have a thymeleaf template which uses special chars in tags like this.

`th:with="pageCSSPath=${'/css/login.css'}, injectRecaptcha=${false}"`

But the output is this:

`th:with="pageCSSPath=/css/profile.css, injectRecaptcha=false"`

I tried many different settings but no success. Is there a way to escape this.

This is my setting.

```
new HtmlWebpackPlugin({ .  
    title: `${key}`,  
    filename: filename,   
    template: path.join(__dirname, `source/pages/${key}/`, `${key}.html`),
    inject: false,
    chunks: [key],
    xhtml: true,
    minify: false,
})```

**Comment by jantimon** [comment]
Did you try a different loader for your html file?

**Comment by atilkan** [comment]
nope, this was the most stable one. I wish to not go that route again.

**Comment by jantimon** [comment]
Which loader are you using?

**Comment by atilkan** [comment]
For html this plugin only. I don't know what other process applied to html in webpack.

**Comment by atilkan** [comment]
I don't use **html-loader** or any other to be specific.
