### ISSUE TITLE
I have an idea to speed up incremental build

### ISSUE THREAD

**Issue by wxlworkhard** [jantimon/html-webpack-plugin#908]
In index.js file:
```
compiler.plugin('emit', function (compilation, callback) {
    if (isCompilationCached && self.options.cache && self.options['xxx']) {
        return callback();
    }
    
    var applyPluginsAsyncWaterfall = Promise.promisify(compilation.applyPluginsAsyncWaterfall, {context: compilation});
    // Get all chunks
    var chunks = self.filterChunks(compilation.getStats().toJson(), self.options.chunks, self.options.excludeChunks);
    ......
```
We can add a xxx attribute to HtmlWebpackPlugin object for incremental build, because hash will not emit generally and url for js will not change.

**Comment by jantimon** [comment]
Could you go a little bit more into detail?

**Comment by wxlworkhard** [comment]
@jantimon 
When I have 50 entries and create 50 HtmlWebpackPlugin instances, it is very slow for incremental build.

`filterChunks`, `sortChunks`, `htmlWebpackPluginAssets` these three steps take 100ms for each instance and take 5000ms totally.

It is not necessary to do these three steps for incremental build, because `self.assetJson` will not change.

**Comment by jantimon** [comment]
Thanks for analyzing 👍👍
We already recognised that this has to be improved (especially the sort part!).
The upcoming version will disable sorting by default and prepare other speed optimisations as well.

For now you can try to set sortChunks to `none`.

**Comment by jantimon** [comment]
@wxlworkhard could you please try if #953 helps to increase your performance problems?
