### ISSUE TITLE
template option returns broken html

### ISSUE THREAD

**Issue by popovdenys** [jantimon/html-webpack-plugin#917]
### Error Message & Stack Trace
no error message

## Description

I follow your documentation and everything was just fine in the beginning ; now when I make some experiments with template I get back broken html even there is no error in compilation. I think already that it's not 100% your bug, but maybe some other plugin installed after may influence it and produce such result.

### Config
```
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
...
, entry: {
            app : [ 'app.css', 'index.js' ]
        }
, plugins: [
            new HtmlWebpackPlugin({
                template: 'index.html'
            })
        ]
}
```

Template file index.html:

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
</body>
</html>
```

## Environment
ubuntu 16.04
node v9.9.0
npm v5.8.0
"webpack": "4.4.1",
"webpack-cli": "^2.0.13",
"html-webpack-plugin": "3.1.0"

## Run
./node_modules/.bin/webpack --mode=development

## Generated index.html
1) with template option : new HtmlWebpackPlugin({ template: 'index.html' })

```
<head><link href="/assets/app.css" rel="stylesheet"></head>�� < ! D O C T Y P E   h t m l > 
 < h t m l > 
 < h e a d > 
         < m e t a   h t t p - e q u i v = " C o n t e n t - t y p e "   c o n t e n t = " t e x t / h t m l ;   c h a r s e t = u t f - 8 " / > 
         < t i t l e > < / t i t l e > 
 < / h e a d > 
 < b o d y > 
 < / b o d y > 
 < / h t m l ><script type="text/javascript" src="/assets/app.js"></script>
```

2) without template option : new HtmlWebpackPlugin()

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Webpack App</title>
  <link href="/assets/app.css" rel="stylesheet"></head>
  <body>
  <script type="text/javascript" src="/assets/app.js"></script></body>
</html>
```

**Comment by popovdenys** [comment]
I've already removed node_modules directory, reinstalled all packages, but the result is persistent.

Regards

**Comment by mastilver** [comment]
That's a weird one...

Only think I can think of is an usual encoding on your template file

I think it should be utf-8

**Comment by popovdenys** [comment]
@mastilver Thanks for your idea.

[The problem is solved](https://www.dropbox.com/s/s9jgtnmjxuwujvl/html-webpack-plugin-2018-03-30_02.57.17.mkv?dl=0) : if, at least once, utf-8 was changed to something else, then the broken output persists until the template will be killed and recreated again with only utf-8.

**Comment by mastilver** [comment]
Glad you manage to fix it!
