### ISSUE TITLE
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'

### ISSUE THREAD

**Issue by mytee306** [jantimon/html-webpack-plugin#919]
**What is the current behavior?**
When I run webpack --plugin html-webpack-plugin I get the following:
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'

NodeTemplatePlugin file is present in the given directory, so the only thing I can think of is that the path is incorrect.

I do know that the error was thrown at webpack.js: 242, but looking at the file I couldn't deduce anything helpful.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. cd ~/documents
2. mkdir test
3. cd test
4. mkdir src
5. touch index.js:
import { hello } from "./hello";
console.dir(hello);
6. touch hello.js:
export const hello = "Hello";
7. npm i -g webpack webpack-cli
8. cd ~
9. npm i -D html-webpack-plugin
10. webpack --plugin html-webpack-plugin

**What is the expected behavior?**
I expect the build to complete without errors and generate a minimum boilerplate html page which include the bundle script tag

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node.js v9.9.0, 
webpack@latest, 
Windows 7

**Comment by mastilver** [comment]
I did see you installed `webpack` locally, please run `npm i -D webpack`
