### ISSUE TITLE
Cannot install plugin via npm

### ISSUE THREAD

**Issue by pkoecker** [jantimon/html-webpack-plugin#920]
Hi,

I cannot install the plugin via NPM anymore. All machines run into the same error:

npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

Any idea what might be the problem?

**Comment by mastilver** [comment]
Please use `html-webpack-plugin` and not `webpack-contrib/html-webpack-plugin`

**Comment by hhubik** [comment]
Just got this on Windows 8.1 x64

```
$ npm i --save-dev html-webpack-plugin
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t ssh://git@github.com/webpack-contrib/html-webpack-plugin.git
npm ERR!
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\xxx\AppData\Roaming\npm-cache\_logs\2018-04-12T15_28_46_553Z-debug.log
```
