### ISSUE TITLE
can not inject js with html-loader

### ISSUE THREAD

**Issue by kunkkaliu** [jantimon/html-webpack-plugin#922]
html-webpack-plugin version: 3.2.0
html-loader version: 0.5.5
webpack version: 4.5.0

<script>
        ${require("html-loader!libs/flexible.js")}
</script>

Question: can not inject the flexible.js

**Comment by jantimon** [comment]
For `html-loader` questions how you use javascript values here please head over to https://github.com/webpack-contrib/html-loader
