### ISSUE TITLE
Cannot specify which loader to use in template

### ISSUE THREAD

**Issue by gmenih341** [jantimon/html-webpack-plugin#923]
## Description

I cannot specify which loader to use for a file. I have a JSON template file, where I use handlebars as the engine. If I try to specify to use the handlebars-loader, it doesn't work, however, if I change the extension to `.hbs` (which is what my loader is testing for), it works.

## Config
Here's the relevant config.
```
plugins: [
    new HtmlWebpackPlugin({
        template: '!!handlebars-loader!./src/manifest.template.json',
        filename: 'manifest.json',
        inject: false,
    }),
],
module: {
    rules: [{
        test: /\.hbs$/,
        loader: 'handlebars-loader',
    }]
},
```

If I rename the file to `manifest.template.hbs`, and then change the template to `./src/manifest.template.hbs`, it works. But specifiying a loader throws me this error:

```
 ERROR in ./manifest.template.json (../node_modules/handlebars-loader!./manifest.template.json)
    Module parse failed: Unexpected token v in JSON at position 0
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token v in JSON at position 0
```

I've also tried it like this `!!handlebars!./src/manifest.template.json`. `handlebars-loader!./src/manifest.template.json`. Nothing works, except if it automatically infers the loader.

**Comment by jantimon** [comment]
Maybe that's a bug in this regular expression:

https://github.com/jantimon/html-webpack-plugin/blob/e2c6990e94b298ff66bcd885c9a03a78221479f6/index.js#L644

could you please try to get some console logs of the replace result?
