### ISSUE TITLE
Embedded javascript inside <script> tags containing ES6 features are not being minified

### ISSUE THREAD

**Issue by diby3ndu** [jantimon/html-webpack-plugin#929]
## Description

We've started using ES6 features (arrow functions, de-structuring, spreading etc.) almost everywhere in our code, be it in `.js` file or inside inline `<script>` tags. But this plugin still uses [uglify-js@2](https://github.com/mishoo/UglifyJS2) for minifying javascript embedded inside `.html` files.

From the [README](https://github.com/mishoo/UglifyJS2#note) of **UglifyJS** it is clear that 

> `uglify-js` only supports JavaScript (`ECMAScript 5`) but not `ES6`.
>  `uglify-js@3` has a simplified API and CLI that is **NOT** backwards compatible with `uglify-js@2`

## Proposed Solution

I think it's time when we should start using **`uglify-js@3`** instead. This won't be of much trouble as we only need to upgrade the package `html-minifier`. Currently we are using `html-minifier` version `3.2.3` which uses `uglify-js` `2.7.x`. This should be upgraded to  `html-minifier` `3.5.15` (latest) which uses `uglify-js` `3.3.x`

## A Scenario

Following is the scenario where it silently failed to minify the embedded javascript written with ES6 features.

### Config

Relevant section from `webpack.config.js`:

```js
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  ...
  plugins: [
    new HtmlWebpackPlugin({
      template: 'client/index.html',
      minify: {
        minifyCSS: true,
        minifyJS: true,
        removeComments: true,
        collapseWhitespace: true,
        preserveLineBreaks: false
      }
    })
  ]
  ...
}
```

HTML Template file:

```html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta http-equiv='Content-type' content='text/html; charset=utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src='//ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js'></script>
    <script async type='text/javascript'>
      let fonts = ['Fredericka the Great', 'Allura'],
          FontLoadStatus = { loaded: false}

      WebFont.load({
        google: {
          families: fonts,
          text
        },
        classes: false,
        active: () => { FontLoadStatus.loaded = true }
      })
    </script>
    <!-- bundled style sheets will be inserted here -->
  </head>
  <body>
    <div id='app'></div>
    <!-- bundled scripts will be inserted here -->
  </body>
</html>
```

Generated HTML file:

```html
<!DOCTYPE html><html lang='en'><head><meta http-equiv='Content-type' content='text/html; charset=utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><script src='//ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js'></script><script async type='text/javascript'>let fonts = ['Fredericka the Great', 'Allura'],
           FontLoadStatus = { loaded: false}

      WebFont.load({
        google: {
          families: fonts,
          text
        },
        classes: false,
        active: () => { FontLoadStatus.loaded = true }
      })</script><link href='login.f783564fbc31cde7.css' rel='stylesheet'></head><body><div id='app'></div><script type='text/javascript' src='vendors~login.c3a791bbab2d353d.js'></script><script type='text/javascript' src='login.8c34c4a2ec888389.js'></script></body></html>
```

## Environment

```
Node.js v9.7.1
darwin 17.4.0
npm v5.6.0
webpack@4.5.0
html-webpack-plugin@3.2.0
```

**Comment by jantimon** [comment]
The generated HTML File looks good to me - what would you expect as output?

**Comment by jantimon** [comment]
If I read the changelog correctly https://github.com/kangax/html-minifier/releases/tag/v3.0.0 does only change the node support to 4+

So it should be no problem to bump the version of the minifier.  
Could you please create a pr?

**Comment by diby3ndu** [comment]
I think the problem is with the package `html-minifier`, as in its latest version (`3.5.15`), it uses `uglify-js` `3.3.x`. But in order to compress scripts containing **ES6** features, one should use the package `uglify-es`. I'll rather create an issue for `html-minifier`.
