### ISSUE TITLE
Add support for `stats.entrypoints[].childAssets`

### ISSUE THREAD

**Issue by jantimon** [jantimon/html-webpack-plugin#934]
Webpack 4.6 allows to prefetch/preload dependencies using dynamic imports:

https://medium.com/webpack/link-rel-prefetch-preload-in-webpack-51a52358f84c

The webpack core api allows to consume those information also for html generation.
So we could turn the following data into `<link />` tags:

```
console.log(stats.entrypoints[].childAssets);

{ 
 main: 
 { 
   assets: ["a.js", "a.css"], 
   childAssets: { 
     preload: [ assets: ["b.js", "b.css"] }, 
     prefetch: { assets: ["c.js", "c.css"] 
    } 
 } 
}
```

--->

```
head
  link(rel=preload, href=a.js, as=script)
  link(rel=preload, href=a.css, as=stylesheet)
  link(rel=preload, href=b.js, as=script)
  link(rel=preload, href=b.css, as=stylesheet)
  link(rel=prefetch, href=c.js, as=script)
  link(rel=prefetch, href=c.css, as=stylesheet)
  ...
  link(rel=stylesheet, href=a.css)
body
  ...
  script(src=a.js)
```

@mastilver do you think we should add this to the html-webpack-plugin itself or rather as a plugin?

**Comment by loveky** [comment]
hi guys, any update on this feature?

**Comment by loveky** [comment]
will look into this to see if I can make a PR

**Comment by jantimon** [comment]
@loveky cool 👍 
right now I am refactoring a lot for #953 so it will take some time till I can work on this topic

**Comment by glen-84** [comment]
@jantimon Should this be re-opened?

**Comment by jantimon** [comment]
I believe this feature would aid many however the information can only be retrieved using a very slow api.

So it would slow down the compilation for all users. If we can find a performance way to access this information I would be more than happy to integrate it

**Comment by glen-84** [comment]
Is there a webpack issue tracking this performance problem?

**Comment by jantimon** [comment]
The webpack core team even provided a new api to get access to the entry point assets so we could speed up the build

**Comment by raRaRa** [comment]
Hi, any update on this? AFAIK, create-react-app are waiting for this fix in order to add support for `webpackPrefetch` and `webpackPreload`.

https://github.com/facebook/create-react-app/issues/3319

**Comment by jantimon** [comment]
As said before this needs support from the webpack api to provide those data in a performant way.

I am not aware if there is already a issue for that on their issue tracker.
