### ISSUE TITLE
The option of templateParameters is conflict with inject

### ISSUE THREAD

**Issue by TerryChenUI** [jantimon/html-webpack-plugin#939]
## Prerequisites

node: 8.10.0
webpack: 4.3.0
html-webpack-plugin: 3.2.0

## Description
I set the option of inject to false. but if I use templateParameters, it will show errors that not found files in jade template

### Error Message & Stack Trace

```
ERROR in Template execution failed: TypeError: Cannot read property 'files' of undefined

ERROR in   TypeError: Cannot read property 'files' of undefined
```

### Config
webpack.config.js
```js
new HtmlWebpackPlugin({
      chunks: ['common', 'index'],
      template: './jade/index.jade',
      filename: '../index.html',
      inject: false,
      cache: false,
      // parameters: templateParameters
    })
```

index.jade
```html
html
    head
        each key in htmlWebpackPlugin.files.css
            link(rel="stylesheet", href=key)
```

**Comment by mastilver** [comment]
If you set `templateParameters` then the plugin won't get the default values from https://github.com/jantimon/html-webpack-plugin/blob/a3ef51493d10c6b5f48b82504c9868d182944da3/index.js#L719

Whatever you put in `templateParameters` will be what you get on the template under the name of `htmlWebpackPlugin`
