### ISSUE TITLE
babel-polyfill - error Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by koutsenko** [jantimon/html-webpack-plugin#940]
## Description

If script tag with inline js is present inside ejs, html-webpack-plugin tries to evaluate it and i got an error.
No matter ES5 or ES6 or smth else.

### Error Message & Stack Trace

```
babel-polyfill - error Error: only one instance of babel-polyfill is allowed
```

### Webpack Config

```js
entry: [
  'babel-polyfill', // IE11 & async/await
  './src/EP.js'
],
```

If i move babel-polifyll from entry to EP.js to avoid double include,
```
if (!global._babelPolyfill) {
	require('babel-polyfill');
}
```

I will get an babel-regenerator error.

How can i tell html-wepback-plugin do not use babel-polyfill?
ejs template i trying to add, is only for dev mode and executing only in latest chrome.

**Comment by mastilver** [comment]
`html-wepback-plugin` doesn't add `babel-polyfill` to your build

It must come from one of your dependencies, try: `npm ls babel-polyfill`

**Comment by koutsenko** [comment]
@mastilver i had babel-polyfill and all worked.
When i added html-webpack-plugin with ejs template, all still worked.
When i added simple inlined js-scripts to ejs template, babel stopped working.
What is the cause of ?

**Comment by koutsenko** [comment]
Switching to idempotent-babel-polyfill resolved the issue.
Sorry for the inconvience.
