### ISSUE TITLE
Release changes from #522

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [jantimon/html-webpack-plugin#943]
Changes from #522 (4b5ee091725f4c35c46c28d575872a3357b69e1e, 3c03d3ad649fbdb24f7611f98fcd55693334a2c1, and ee2df7c9e1065c369d6e8780f96286ede85a5028) are not in any 3.x release of the plugin yet.

The issue was from 1.5 years ago so I think this may have just been missed by mistake.

**Comment by jantimon** [comment]
True the webpack 4 release changed the priority.  
I am very sorry for missing those changes.

**Comment by jantimon** [comment]
Hey @Daniel-Khodabakhsh 

sorry once again for the huuuge delay.
Could you please take a look at https://github.com/jantimon/html-webpack-plugin/tree/webpack-4 ?

**Comment by Daniel-Khodabakhsh** [comment]
@jantimon 
No problem! Thank you for the merge.
Checked the branch and it looks good :+1:

**Comment by jantimon** [comment]
Cool :)

**Comment by jantimon** [comment]
Moved to #953
