### ISSUE TITLE
html-webpack-plugin

### ISSUE THREAD

**Issue by yzgc** [jantimon/html-webpack-plugin#948]
console.log input:
`Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
`
my webpack config:
`    new HtmlWebpackPlugin(
        {
            filename: 'index.html',
            chunks: ['app','vendor'],
            template: SRC_PATH + '/index.html',
            minify: {
                collapseWhitespace: true,
                collapseInlineTagWhitespace: true,
                removeRedundantAttributes: true,
                removeEmptyAttributes: true,
                removeScriptTypeAttributes: true,
                removeStyleLinkTypeAttributes: true,
                removeComments: true
            }
        }
    )`

**Comment by mastilver** [comment]
#895 duplicate

**Comment by echoescn** [comment]
same issues
