### ISSUE TITLE
using es6 template string break the html file build

### ISSUE THREAD

**Issue by tommytroylin** [jantimon/html-webpack-plugin#950]
## Description

This may be something related when html-webpack-html processing html template with lodash/template. 

https://github.com/jantimon/html-webpack-plugin/blob/master/lib/loader.js#L30-L34

### Error Message & Stack Trace

```
ERROR in Template execution failed: ReferenceError: hello is not defined

ERROR in   ReferenceError: hello is not defined

  - loader.js:6 eval
    [index.html?.]/[html-webpack-plugin]/lib/loader.js:6:10

  - loader.js:11 module.exports
    [index.html?.]/[html-webpack-plugin]/lib/loader.js:11:3

  - index.js:284 Promise.resolve.then
    [template-react-typescript]/[html-webpack-plugin]/index.js:284:18


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
```

### Config

Copy the relevant section from `webpack.config.js`:

```js
module.exports = {
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/index.html"
    }),
  ]
}
```

Copy your template file:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        <%= htmlWebpackPlugin.options.title %>
    </title>
    <script>
        const hello = 'hello';
        const world = 'world'
        console.log(`${hello} ${world}`);  // ~this line~
    </script>
</head>

<body>
    <div id="app"></div>
    
</body>

</html>

```

## Environment
```
node 8.11.1
macOS 10.13
npm 6
webpack 4.7
html-webpack-plugin 3.2.0
```

**Comment by jantimon** [comment]
Thanks for reporting this issue - could you please add a `console.log` statement here and post the content of `source`?  

https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L245

**Comment by tommytroylin** [comment]
```
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] (webpack)/buildin/module.js 546 bytes {0} [built]
    [1] (webpack)/buildin/global.js 492 bytes {0} [built]
    [3] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 674 bytes {0} [built]
```
it's a pretty long output and I guess what you need is `module[3]`.
BTW, I've already run `npm update` so webpack should be `4.8.3` now.

The output is
```javascript
(function(module, exports, __webpack_require__) {

var _ = __webpack_require__(2);module.exports = function (templateParams) { with(templateParams) {return (function(data) {
var __t, __p = '';
__p += '<!DOCTYPE html>\n<html lang="en">\n\n<head>\n    <meta charset="UTF-8">\n    <title>\n        ' +
((__t = ( htmlWebpackPlugin.options.title )) == null ? '' : __t) +
'\n    </title>\n    <script>\n        const hello = \'hello\';\n        const world = \'world\'\n        console.log(`' +
((__t = (hello)) == null ? '' : __t) +
' ' +
((__t = (world)) == null ? '' : __t) +
'`);  // ~this line~\n    </script>\n</head>\n\n<body>\n    <div id="app"></div>\n    \n</body>\n\n</html>\n';
return __p
})();}}

})
```
em... seems it unexpectedly processes ES6 template strings as same as `<%= %>` bindings.

**Comment by jantimon** [comment]
Nice 👍 thanks for analyzing.  
This is exactly the reason why it is broken.  
The transformation is done here:

https://github.com/jantimon/html-webpack-plugin/blob/b4312f97fb0764131721ea3cc76c5b2afbae0352/lib/loader.js#L28

Do you have any idea what might be the reason?

**Comment by tommytroylin** [comment]
BTW, Although in all [docs](https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates) it doesn't encourage users to use `${}` syntax, this change may break some users' templates & projects potentially.

I suggest a **semver-minor** change and document it on top of changelog and readme

**Comment by jantimon** [comment]
Hey @tommytroylin  
thank you so much for the fix - I will merge it very soon!
As it sounds like a breaking change I would prefer to merge it into the next major version.  
I hope that's okay for you

**Comment by jantimon** [comment]
Merged into https://github.com/jantimon/html-webpack-plugin/tree/webpack-4
