### ISSUE TITLE
Cannot inline bundle chunks with Webpack 4 

### ISSUE THREAD

**Issue by vladp** [jantimon/html-webpack-plugin#954]
## Description

Documentation request:   Please remove reference (or clarify) to
https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin  
As it is not working with webpack 4 

See
https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin/issues/23

thank you

**Comment by jantimon** [comment]
@vladp unfortunately I don't use that plugin at all - but the `inline-chunk-manifest-html-webpack-plugin` is smaller than most webpack configurations - only 100 lines of code.  

Maybe you could upgrade it and provide a pull request.
