### ISSUE TITLE
Set string or function as hash property

### ISSUE THREAD

**Issue by Franziskus1988** [jantimon/html-webpack-plugin#957]
Currently it's only possible to set a boolean for the hash config property. 

In our company we normally use the build number of our CI tool as hash for file names. This allows us to check if all files were generated within a certain build very easily.

Would it be possible to set a string or a function that returns a string as value for the hash config property?
Thus we could pass in the Ci build number easily.

**Comment by mastilver** [comment]
Just use webpack's entry for that
