### ISSUE TITLE
Can't add a JavaScript or CSS asset to the HTML with 4.x alpha

### ISSUE THREAD

**Issue by kenve** [jantimon/html-webpack-plugin#971]
## Description
I'm using [html-webpack-include-assets-plugin](https://github.com/jharris4/html-webpack-include-assets-plugin) to generate a JavaScript or CSS asset, but it doesn't work. 

## Configuration
```js
 new HtmlWebpackPlugin({
    template: path.join(__dirname, '..', './app/index.html')
 }),
 new HtmlWebpackIncludeAssetsPlugin({
    assets: ['test.js'],
    append: false
 }),
```
## Problem
The HTML generated by `html-webpack-plugin`:
```html
<script src="undefined"></script>
<script src="/app.js"></script>
```
It cannot insert the assets path correctly.

## Possible reason
output `asset`:
```bash
{ publicPath: '/',
  js: [ '/test.js', { entryName: 'main', path: '/app.js' } ],
  css: [ { entryName: 'main', path: '/a.css' }, '/test.css' ],
 ...
}
```
you changed the js and css property  to an object `{ entryName: string, path: string}` , but js and css arrays contain strings. 
```js
 // Turn script files into script tags
 const scripts = assets.js.map(scriptAsset => ({
   tagName: 'script',
   voidTag: false,
   attributes: {
     src: scriptAsset.path
   }
 }));
 // Turn css files into link tags
 const styles = assets.css.map(styleAsset => ({
   tagName: 'link',
   voidTag: true,
   attributes: {
     href: styleAsset.path,
     rel: 'stylesheet'
   }
 }));
```

## Possible fix
I try to fix this behavior by adding the check for `scriptAsset.path` on line 539, also ` styleAsset.path` on line 547.
```js
 // Turn script files into script tags
const scripts = assets.js.map(scriptAsset => ({
  tagName: 'script',
  voidTag: false,
  attributes: {
    src: scriptAsset.path ? scriptAsset.path: scriptAsset
  }
}));
// Turn css files into link tags
const styles = assets.css.map(styleAsset => ({
  tagName: 'link',
  voidTag: true,
  attributes: {
    href: styleAsset.path ? styleAsset.path: styleAsset,
    rel: 'stylesheet'
  }
}));
```
But I'm not sure this is a good solution.

## Environment
```
Node.js v8.11.2
webpack@4.10.2
webpack-cli@2.1.5
html-webpack-plugin@4.0.0-alpha
html-webpack-include-assets-plugin@1.0.4
```

Thanks for the plugin.

**Comment by jharris4** [comment]
@jantimon can you point to docs or a PR that introduce these breaking changes so @SimenB and myself can look at this issue?

**Comment by jantimon** [comment]
@jharris4 thanks for jumping in - the pr is not merged as it is still alpha: 
https://github.com/jantimon/html-webpack-plugin/pull/953

The commit is this one: [342867e1edb7c2a8748b0aca396f160f0b13d42e](https://github.com/jantimon/html-webpack-plugin/pull/953/commits/342867e1edb7c2a8748b0aca396f160f0b13d42e#diff-168726dbe96b3ce427e7fedce31bb0bcR491)

**Comment by SimenB** [comment]
`add-asset-html-webpack-plugin` should have support now, as soon as CI does its job and makes a release. Sorry about the delay, I missed this ping 😅

**Comment by jantimon** [comment]
Thanks a lot @SimenB :)

**Comment by jharris4** [comment]
I finally got around to looking into this myself. I've made a PR to handle version 4.x here:

https://github.com/jharris4/html-webpack-include-assets-plugin/pull/34

@SimenB's PR was a useful guide to get me started, but I'm using the alter assets hooks so I had a couple more hoops to jump through.

**Comment by jharris4** [comment]
I also had to update all my unit tests to remove `type="text/javascript"` from all the expected script tags because 4.X [introduces this change](https://github.com/jantimon/html-webpack-plugin/commit/b46bf67)
