### ISSUE TITLE
Script tags are added to head element even with `inject: 'body'` if there is no body tag in the template

### ISSUE THREAD

**Issue by kzvi** [jantimon/html-webpack-plugin#974]
## Expected behaviour

If you use a HTML template file with no explicit `<html>`, `<head>`, or `<body>` element, for example if this is the HTML template file:

    <!doctype html>
    <meta charset="utf-8">
    <title>Example</title>

Then `html-webpack-plugin` should insert a `<body>` tag if necessary to make sure that the script is only run after the DOM is loaded, for example (generated output):

    <!doctype html>
    <meta charset="utf-8">
    <title>Example</title>
    <body>
    <script type="text/javascript" src="bundle.js"></script>

## Current behaviour

The generated `<script>` tag is simply appended to the end of the file:

    <!doctype html>
    <meta charset="utf-8">
    <title>Example</title><script type="text/javascript" src="bundle.js"></script>

Browsers interpret this as the script tag being in the `<head>`.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
Node.js v10.3.0
darwin 17.5.0
npm 6.1.0
webpack@4.12.0
html-webpack-plugin@3.2.0
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: 'index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'index.html',
      inject: 'body'
    }),
  ],
};
```

Copy your template file if it is part of this issue:

    <!doctype html>
    <meta charset="utf-8">
    <title>Example</title>

**Comment by jantimon** [comment]
Right now index files without a body are not supported well.  
Is there any reason why this would be of use?
