### ISSUE TITLE
why is `meta viewport` is not included by default?

### ISSUE THREAD

**Issue by bochen2014** [jantimon/html-webpack-plugin#978]
I believe this questions has been asked before and the solution been give was  to use custom template. 

My understanding is that ppl don't want to create a separate `index.html` file and that's why we are here; Is there any consideration why `viewport` meta is not included by default?

**Comment by jantimon** [comment]
Please take a look at #897 and #906.

Basically you can use it as follows:

```
new HtmlWebpackPlugin({
   meta: {viewport: 'width=device-width, initial-scale=1, shrink-to-fit=no'}
});
```

Also there is no simple on off viewport but you can configure different options.  
You can find a good list here:  

https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

Is there a standard for a good default?

**Comment by bochen2014** [comment]
i think the example you gave was good enough. 

Most people don't care the nuance of different options, and if they do, they should use custom template. 
make sense?
