### ISSUE TITLE
Add option to prevent assets from being emitted when they are inlined

### ISSUE THREAD

**Issue by niksajanjic** [jantimon/html-webpack-plugin#980]
**Is your feature request related to a problem? Please describe.**
Yes. It is related to inline assets example. When you inline your CSS or JS, it still gets emitted which can be unnecessary.

**Describe the solution you'd like**
When I want to inline my assets instead of emitting them and loading scripts on a client, I also don't want to emit those files. To inline assets, there is an example in this repo: https://github.com/jantimon/html-webpack-plugin/tree/master/examples/inline, but I rather use `html-webpack-inline-source-plugin` so I can have my template HTML as simple as possible. Either way, all assets that are inlined are also emitted at the end so I have to use `ignore-emit-webpack-plugin` to prevent them from emitting. Maybe some property that accepts regex of files we don't want to emit would be helpful.

**Describe alternatives you've considered**
`ignore-emit-webpack-plugin` This plugin prevents emitting certain assets that meet regex criteria by erasing them from compilation object.

**Comment by jantimon** [comment]
This plugin doesn't remove anything from being emitted.  
It only generates html files.

So probably using `ignore-emit-webpack-plugin` would be the best way.  
What do you think?

**Comment by niksajanjic** [comment]
@jantimon I just made a PR to fix deprecation warning in `ignore-emit-webpack-plugin` and update it to new API. I'm ok with using other plugins to solve certain specific issues and I understand the idea of making this plugin as simple as possible. Only thing is that some of these other plugins might not be maintained at the same level as this plugin, and my initial thought about your inline example was that it isn't fully solving the problem as it still emits the files which are probably not needed at that point, that is all.
