### ISSUE TITLE
Allow to only generate a json with assets list

### ISSUE THREAD

**Issue by caub** [jantimon/html-webpack-plugin#982]
I'm wondering if I should add a `chunksSortFile` option, and allow to pass `filename: null` so that the ouput of this plugin is a simple json containing js and css sorted list

Or should it be another plugin, sharing the same sorting logic: https://github.com/caub/webpack-plugin-assets

The goal is to only have this assets list from the build, and handle the html templating independently

**Comment by jantimon** [comment]
You can already do that using a template and setting `inject:false`.  
Please not that we are changing from getStats for performance reasons

**Comment by caub** [comment]
@jantimon Ah right, thanks a lot for telling https://github.com/jantimon/html-webpack-plugin/blob/webpack-4/index.js#L118

There's another apporach I've taken too, it's to use ManifestPlugin and add the assets ordering there: https://github.com/danethurber/webpack-manifest-plugin/pull/93#issuecomment-398585632
then I just filter for the `\.(js|css)$` assets to know the ordered assets

**Comment by caub** [comment]
Concerning what you said
> You can already do that using a template and setting inject:false

I'm not sure I can do it fully, except if I can export the [assetJson](https://github.com/jantimon/html-webpack-plugin/blob/webpack-4/index.js#L133) object

my end goal is I have a template like (I named it `index.html.js`)

```js
module.exports = ({
  htmlWebpackPlugin: {options = {}} = {},
  jsAssets = [],
  cssAssets = [],
  injectedEnv = options.injectedEnv || '',
  nonce = '',
  ..
}) => `<!DOCTYPE html><html> .... `
```
I don't use any index.html, in dev mode I can still use html-webpack-plugin, with inject: false or true actually.

in production mode, I want more flexibility (the injectedEnv, and other dynamic things (like nonce attributes)), and serve this template from a server

**Comment by jantimon** [comment]
You can use the template parameters similar to this example:

https://github.com/jantimon/html-webpack-plugin/tree/master/examples/template-parameters

Instead of using an object you would have to pass a function

**Comment by caub** [comment]
@jantimon awesome work, sincere thanks for that

I see that webpack4 is providing the ordered stuff now, great

I still see some dups in the assets `"/static/js/vendors.5c7232b4.js", ..."/static/js/runtime~main.87700e36.js", "/static/js/vendors.5c7232b4.js", ...` (twice this vendor) but very easy to Set/unique them
