### ISSUE TITLE
Template doesn't resolve relative to context in Webpack 4

### ISSUE THREAD

**Issue by laggingreflex** [jantimon/html-webpack-plugin#983]
[Not sure][qonso] if this is related to Webpack 4 itself but earlier (in Webpack 3) if you specified a `context` in webpack config, the `template` would resolve relative to that. For example this would work in Webpack 3:

```
test
├───web-app
│    └───template.html
└───webpack.config.js
```

**`webpack.config.js`**

```js
{
  context: __dirname + '/web-app',
  plugins: [
    new htmlWebpackPlugin({template: 'template.html'})
  ]
}
```

But it doesn't work in Webpack 4

## Expected behaviour

`template` should resolve relative to the `context` specified in webpack config

## Current behaviour

It doesn't

## Environment

```
Node.js v10.1.0
win32 10.0.16299
npm --version
6.0.1
npm ls webpack
-- webpack@4.12.0
npm ls html-webpack-plugin
-- html-webpack-plugin@4.0.0-alpha
```

[qonso]: https://stackoverflow.com/questions/50927363/context-not-working-in-webpack-4

**Comment by jantimon** [comment]
Could you please try `./template.html` ?

**Comment by laggingreflex** [comment]
The error I get is "Error: Can't resolve 'C:\test\html.js'" (where `C:\test` is the root project dir), which implies it isn't actually taking in the `context` dir at all. 

I'm also having the same issue with Webpack 4 in general ([question on SO](https://stackoverflow.com/questions/50927363/context-not-working-in-webpack-4))

**Comment by jantimon** [comment]
It's probably a windows problem.

Could you please add a console.log to your node_modules/html-webpack-plugin/index.js file here:

https://github.com/jantimon/html-webpack-plugin/blob/8440e4e3af94ae5dced4901a13001c0628b9af87/index.js#L45

e.g.

```js
console.log({
  template: this.options.template, 
  context: compiler.context
})
```

So we can get a better idea whats going on? :)

**Comment by laggingreflex** [comment]
```
{ 
  template: 'C:\\test\\node_modules\\html-webpack-plugin\\lib\\loader.js!C:\\test\\html.js',
  context: 'C:\\test' 
}
```

**Comment by jantimon** [comment]
Could you please try to set the context to `'C:\test\'` or use `/`?

**Comment by laggingreflex** [comment]
You mean the root dir? Tried both, same error.

**Comment by jantimon** [comment]
Ah sorry - my bad `'C:\test\web-app'`

**Comment by jantimon** [comment]
However it looks like it would be a webpack or configuration problem as the path concatenation seems to be correct

**Comment by laggingreflex** [comment]
Didn't work either, see my edit in the previous comment. 

Yeah, I think so too. It's most likely Webpack 4 issue (or I must be doing something wrong) 

Feel free to close. Thanks for the help
