### ISSUE TITLE
Modify injection path

### ISSUE THREAD

**Issue by atilkan** [jantimon/html-webpack-plugin#984]
I have a directory to output the bundles. -> **static/js/**
I have a server that serves the same location as **js/**
So i want to be able to inject as **js/bundle.js**.

I am currently doing this by manually wrting to template, but i can not add version and other features this way.

Is there a feature to modify injection path?

**Comment by mastilver** [comment]
Use `publicPath`

**Comment by atilkan** [comment]
@mastilver Thank you.

**Comment by atilkan** [comment]
@mastilver I don't understand why it doesn't work.

**Comment by atilkan** [comment]
Can't get the desired result though. 
Why just can't you give an option for us to configure, 
Nooooooo i have to know what webpack and htmlwebpackplugin does implicitly.

**Comment by jantimon** [comment]
https://github.com/jantimon/html-webpack-plugin/blob/8440e4e3af94ae5dced4901a13001c0628b9af87/index.js#L411-L420

**Comment by atilkan** [comment]
@jantimon 
That helped a lot, thanks. :P

**Comment by atilkan** [comment]
This solved my problem. 
**output.publicPath: "/"**
It is so easy and hard at the same time. I really don't like webpack ecosystem. 
My filename like this for the record.
**filename: `js/[name].js`,**
