### ISSUE TITLE
i18n for html files

### ISSUE THREAD

**Issue by vict-shevchenko** [jantimon/html-webpack-plugin#985]
Hello, first of all, thanks a lot for a very useful plugin.

I was not sure if such possibility exists, or maybe its possible to solve in some other way. 

**Is your feature request related to a problem? Please describe.**
I need to generate several html files base on one template, each for a particular language.

**Describe the solution you'd like**
There is an[ i18n-webpack-plugin](https://github.com/webpack-contrib/i18n-webpack-plugin), that does what I would like to have but for .js files. I like to have something very similar, but for html-plugin. So inside of the template, I can use `<div>__('Hello World')</div>` and after execution, there are generated several .html files (each for every language passed to the plugin definition) with localized text. ( `<div>Hallo Welt</div>` for German, for example)

**Describe alternatives you've considered**
I have tried to target  `i18n-webpack-plugin` on to .html file - but no result. There is also some `StringReplacePlugin` but not sure its the right choice. 
As a straightforward solution, I can write a node script that will do the replacement.

**Additional context**
Please advice.

**Comment by jantimon** [comment]
The html-webpack-plugin is converting the template into javascript using webpack.  
So it should be possible to combine both plugins.

Did you try `<%= __('Hello World') %>` ?

**Comment by jantimon** [comment]
👍

**Comment by vict-shevchenko** [comment]
Hi!

Thanks for the advice, yes actually plugins can work in this way. And with the configuration like this:
![screen shot 2018-06-25 at 2 56 26 pm](https://user-images.githubusercontent.com/3974306/41848992-2297ae16-7888-11e8-8dcd-cc83eed8733b.png)

I  get exact output, that I need.
![screen shot 2018-06-25 at 2 56 38 pm](https://user-images.githubusercontent.com/3974306/41849004-29dd32cc-7888-11e8-8cd0-b632c3ffd456.png)

My only concern is that it actually overwrites `output.js` for each locale.
![screen shot 2018-06-25 at 3 03 44 pm](https://user-images.githubusercontent.com/3974306/41849292-0c13392a-7889-11e8-917f-140f8719fded.png)

 Not sure how critical this problem is. Believe that can be fixed by changing webpack.config.js to something like this.

`module.exports = [mainConfigObject, Object.keys(languages).map(lang => htmlConfigObject)]`
where for `htmlConfigObject` I shold output nothing, but run `html-webpack-plugin` with appropriate language.
