### ISSUE TITLE
300+ new HtmlWebpackPlugin() cause Unhandled rejection RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mslmsl111** [jantimon/html-webpack-plugin#993]
i upgraded webpack4 and html-webpack-plugin recently. My project was fine before with webpack3

## Expected behaviour
working on 300+ pages

## Current behaviour

Unhandled rejection RangeError: Maximum call stack size exceeded
    at new Function (<anonymous>)
    at AsyncSeriesHookCodeFactory.create (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/HookCodeFactory.js:24:12)
    at AsyncSeriesHook.compile (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/AsyncSeriesHook.js:29:18)
    at AsyncSeriesHook._createCall (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/Hook.js:24:15)

## Environment

mac os

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
exports.htmlPlugin = function () {
  var pages = fs.readdirSync(PAGE_PATH)
  let langName = ['zh','en']
  let minLangName = ['zh','en']
  const IS_DEV_ENV = htmlUtils.isDevEnv()
  if (!IS_DEV_ENV) {
    langName = langUtils.getLangNameList()
  }
  if (IS_DEV_ENV && config.devDebug.debug) {
    pages = config.devDebug.pages
  }
  let arr = []
  // filename 为 文件夹名/语言/index.html
  pages.forEach((filePath) => {
    if (filePath.indexOf('.') > 0 || filePath.indexOf('.') === 0) {
      return
    }
    let filename = filePath.substring(filePath.lastIndexOf('\/') + 1)
    if (!IS_DEV_ENV) {
      arr.push(new HtmlWebpackPlugin(htmlUtils.getRedirectHtml(filename)))
    }
    if (whiteList.indexOf(filename) == -1) {
      minLangName.forEach((lang) => {
        arr.push(new HtmlWebpackPlugin(htmlUtils.getHtml(filename, lang, IS_DEV_ENV)))
      })
    } else {
      langName.forEach((lang) => {
        arr.push(new HtmlWebpackPlugin(htmlUtils.getHtml(filename, lang, IS_DEV_ENV)))
      })
    }
  })
  console.log(arr.length)
  return arr
}
```

**Comment by jantimon** [comment]
Please try `html-webpack-plugin@next` which has full webpack 4 support
