### ISSUE TITLE
error:the loader ... didn't return html, when I use webpack.optimize.UglifyJsPlugin,The HTML_WEBPACK_PLUGIN_RESULT is been compressed

### ISSUE THREAD

**Issue by sinbargit** [jantimon/html-webpack-plugin#994]
I want inject the filepath into a ejs template, but got the error.

here is my config file

```
new webpack.optimize.UglifyJsPlugin({
            exclude:'/.*\/node_modules\/.*/',
            compress: {
                unused: true,
                drop_console: false,
                drop_debugger: true,
                dead_code: true,
                properties: false,
                warnings: false,
                screw_ie8: false,
            },
            mangle: {
                screw_ie8: false,
            },
            output: {
                screw_ie8: false,
            },
            comments: false,
        })
       ...
       new HtmlWebpackPlugin({
            devscript: process.env.NODE_ENV === 'production' ? '' : scriptInject,
            filename: filename_ssr,
            template: template_ssr,
            inject: false
        })
```
The error is:
```
Html Webpack Plugin:
<pre>
  Error: The loader "/Users/xiexing/work/code/static.g.iqiyi.com/game/react/node  _modules/_html-webpack-plugin@2.30.1@html-webpack-plugin/lib/loader.js!/Users/  xiexing/work/code/static.g.iqiyi.com/game/react/node_modules/_html-webpack-plu  gin@2.30.1@html-webpack-plugin/default_index.ejs" didn't return html.
</pre>
```
but if I remove the webpack.optimize.UglifyJsPlugin then every thing working well, and I do a debug with the source code. And found that there is a source variable value is a js file like: var HTML_WEBPACK_PLUGIN_RESULT... ,the js been compressed,and if I remove the webpack.optimize.UglifyJsPlugin the js is uncompressed and working well.

**Comment by sinbargit** [comment]
Any progress here?

**Comment by jantimon** [comment]
Could you please provide a minimal reproduction example?

**Comment by sinbargit** [comment]
@jantimon  Hi, Here is the demo https://github.com/sinbargit/htmlwebpackplugin_demo

just npm install  and npm run build_pro demo. the webpack reference file is /package/webpack.js and /package/webpack.config.js

**Comment by jantimon** [comment]
Can you please reduce it to a minimal version?
Just remove everything configuration and every unrelated file.

**Comment by sinbargit** [comment]
@jantimon  Now it's enough simple，but issue still there

**Comment by jantimon** [comment]
Could you please remove all configurations which are not needed (e.g. your redis config, css files, ..)?

**Comment by sinbargit** [comment]
Done. I removed

**Comment by jantimon** [comment]
Could you please also cleanup the package.json and upgrade the html-webpack-plugin ?  
You are using a very old version

**Comment by sinbargit** [comment]
Hi I update the version to 3.2.0. but issue still there? are you reproduce the issue?

**Comment by sinbargit** [comment]
@jantimon Are there any workaround way can I use?

**Comment by jantimon** [comment]
Sorry for the slow response but I don’t have the time to give one on one support for webpack configurations however I would love to look into this issue so I can fix the underlying bug if any exist.

Could you please create a minimal reproduction example with the newest webpack and html-webpack-plugin versions?

Here is a great summary on how to create a minimal reproduction example:
https://stackoverflow.com/help/mcve
