### ISSUE TITLE
templateParameters is called too early

### ISSUE THREAD

**Issue by gregorvoinov** [jantimon/html-webpack-plugin#998]
Hi,

I started to build my own plugin to merge some json files and the merged files should be used by TemplateParameters, but templateParameters is called too early, I always get the error message 

>  no such file or directory,

I tried to use the hook **htmlWebpackPluginBeforeHtmlGeneration** but then I get the error Message

> TypeError: Cannot read property 'tapAsync' of undefined

    MergeJsons.prototype.apply = function (compiler) {
      compiler.hooks.compilation.tap('MergeJsons', (compilation) => {
        compilation.hooks.htmlWebpackPluginBeforeHtmlGeneration.tapAsync('MergeJsons', () => {
            glob('./src/data/*.json', (error, files) => {
                files.forEach((filename) => {
                    const content = JSON.parse(fs.readFileSync(filename, 'utf8'));
                    Object.assign(merged, content);
                });
                fs.writeFileSync('merged.json', JSON.stringify(merged));
            });
          }
        )
      })
    }

my webpack.config

    new MergeJsons(),
    ...pages.map(page => new HtmlWebpackPlugin({
        template: 'hbs/pages/'+page,
        filename: page.split(".")[0]+".html",
        templateParameters: JSON.parse(fs.readFileSync('merged.json', 'utf8'));
    }))

Should I use another hook? Or how can I achieve that the templateParameters isn't called so early?

**Comment by jantimon** [comment]
We are changing the structure of hooks right now: 
https://github.com/jantimon/html-webpack-plugin/pull/953

It will probably look like documented here:
https://github.com/jantimon/html-webpack-plugin/tree/webpack-4#events

**Comment by jantimon** [comment]
Just a side node - your approach looks very slow.

**Comment by gregorvoinov** [comment]
Thank you. I will try it later.

This is my first plugin. I started with webpack a few weeks ago.  Do you mean I should do

    templateParameters: require('merged.json')

?

**Comment by jantimon** [comment]
Rather inside your hbs helper:

```
require.context('./your/directory/', true, /\.json$/);
const jsons = requireTest.keys().forEach(requireTest);
// maybe some merge logic here
return jsons;
```

**Comment by gregorvoinov** [comment]
I installed 

    npm i html-webpack-plugin@next

but get this error message now

> TypeError:  HtmlWebpackPlugin.getHooks is not a function


    const HtmlWebpackPlugin = require('html-webpack-plugin');

    MergeJsons.prototype.apply = function (compiler) {
      compiler.hooks.compilation.tap('MergeJsons', (compilation) => {
        HtmlWebpackPlugin.getHooks(compilation).beforeHtmlGeneration.tapAsync('MergeJsons', () => {
          ....
        })
      })
    }

**Comment by jantimon** [comment]
@emilio-martinez this will also change with the `@next` version (I'll try to release a beta this week)

**Comment by gregorvoinov** [comment]
any news for the release? ;)

**Comment by jantimon** [comment]
@gregorvoinov sorry it's even more work than expected - I am on it :)

**Comment by jantimon** [comment]
I'll release a beta once #1032 is merged - @gregorvoinov  could you please take a look at it?

**Comment by gregorvoinov** [comment]
sry for late reply,  I was on vacation :)

But no, now I get this error message
> TypeError: Cannot read property 'tapAsync' of undefined 
    at compiler.hooks.compilation.tap (/path/src/plugin/mergeJson.js:16:69)
    at SyncHook.eval [as call] (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:1)
...

This is the latest @next release?
> "html-webpack-plugin": "^4.0.0-alpha.2",

**Comment by jantimon** [comment]
Can you please add the code of `/path/src/plugin/mergeJson.js:16:69)`

Yes 4.0.0-alpha.2 is the current @next release

**Comment by gregorvoinov** [comment]
```javascript
const HtmlWebpackPlugin = require('html-webpack-plugin');

function MergeJsons(options) {

}

MergeJsons.prototype.apply = function (compiler) {
    compiler.hooks.compilation.tap('MergeJsons', (compilation) => {
        HtmlWebpackPlugin.getHooks(compilation).beforeHtmlGeneration.tapAsync('MergeJsons', () 
            console.log('merge something');
        })
    })
}

module.exports = MergeJsons
```

**Comment by jantimon** [comment]
The hooks have been renamed:
<img src="https://raw.githubusercontent.com/jantimon/html-webpack-plugin/webpack-4/flow.png" >
