### ISSUE TITLE
What is the FAQ?

### ISSUE THREAD

**Issue by chemoish** [jantimon/html-webpack-plugin#999]
## Expected behaviour

I would expect FAQ to be present or the comment to be improved (i.e. link to `_.template` or something?).

## Current behaviour

`README.md` states: `// Load a custom template (lodash by default see the FAQ for details)`

**Comment by jantimon** [comment]
Looks like the link got lost somehow:
https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md
